### PR TITLE
✨   MS preflight checks to improve cluster stability

### LINKED ISSUE #8657: MachineSet does not consider current state of Cluster before creating new machines
**Detailed Description:**

When a MachineSet creates machines under certain circumstances, the operation fails or leads to a new machine that will be deleted and recreated in a short timeframe, and this is not ideal.

This issue is about introducing preflight checks (details below) in the MachineSet controller so the machine creation is blocked until circumstances are known to be safe for machine creation, ultimately ensuring stability of workloads in the cluster.

Following cases can be handled more safely by implementing preflight checks:

- When the Kubernetes minor version of the new Machine is greater than control plane minor version, new machine creation might fail (violates Kubernetes version skew)
- When using the KubeadmBootstrapProvider and the  Kubernetes minor version of the new Machine is not equal to the control plane minor version, new machine creation might fail (violates the kubeadm version skew)
- When the control plane is upgrading, similar problem as above might happen + other errors might happen if your load balancer is not fast enough in updating its configuration to CP machines being deleted

Like for kubeadm preflight checks, we are considering to have also options to skip preflight checks (probably an annotation, TBD). The main use case for skipping preflight check is to allow users to run a combination of versions outside the kubeadm policy, given that in some cases this works, but it also seems a nice option given the level of configurability we are asked for.

**Anything else you would like to add?**
**Follow-ups**:
- Surface preflight check failures in a condition that can be bubbled up to the MachineDeployment.

/kind bug

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

This PR adds pre-flight checks before a new Machine is created in the MachineSet controller. These pre-flight checks will help with improving the stability of the cluster.

The following pre-flight checks are performed:
- Ensure that the control plane is not provisioning
- Ensure that the control plane is not upgrading
- Ensure that the MachineSet and ControlPlane versions conform to Kubernetes version skew policy
- If kubedam bootstrap providers is used, ensure that the MachineSet and ControlPlane versions conform to kubeadm version skew policy

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8657

### CODE REVIEW

File: internal/controllers/machineset/machineset_controller.go [hunk 1]
```diff
@@ -966,6 +994,146 @@ func (r *Reconciler) getMachineNode(ctx context.Context, cluster *clusterv1.Clus
...
+	// Kubernetes skew policy: https://kubernetes.io/releases/version-skew-policy/#kubelet
+	floorVersion := semver.Version{
+		Major: cpSemver.Major,
+		Minor: cpSemver.Minor - 2,
+		Patch: 0,
+	}
+	if msSemver.GT(cpSemver) || msSemver.LT(floorVersion) {
+		log.Info(fmt.Sprintf("Pre-flight check failed: MachineSet version (%s) and ControlPlane version (%s) do not conform to the kubernetes version skew policy", msVersion, cpVersion))
+		return ctrl.Result{RequeueAfter: preflightFailedRequeueAfter}, nil
+	}
```
Comment (vincepri) [inline internal/controllers/machineset/machineset_controller.go:1109]: Should this be in a validation webhook?

File: internal/controllers/machineset/machineset_controller.go [hunk 2]
```diff
@@ -966,6 +994,146 @@ func (r *Reconciler) getMachineNode(ctx context.Context, cluster *clusterv1.Clus
...
+	msVersion := *ms.Spec.Template.Spec.Version
+
+	// If using kubeadm bootstrap provider, check the kubeadm version skew policy.
+	// => MS version should match the Control Plane version.
+	// kubeadm skew policy: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#kubeadm-s-skew-against-kubeadm
+	kubeadmBootstrapProviderUsed := ms.Spec.Template.Spec.Bootstrap.ConfigRef != nil &&
+		ms.Spec.Template.Spec.Bootstrap.ConfigRef.Kind == "KubeadmConfigTemplate"
+	if kubeadmBootstrapProviderUsed {
+		if cpVersion != msVersion {
+			log.Info(fmt.Sprintf("Pre-flight check failed: MachineSet version (%s) and ControlPlane version (%s) do not conform to kubeadm version skew policy: kubeadm bootstrap provider only supports joining with the same version as the control plane", msVersion, cpVersion))
```
Comment (vincepri) [inline internal/controllers/machineset/machineset_controller.go:1130]: Hm, shouldn't this allow users to create worker nodes with an older version that's still in the skew policy?

File: api/v1beta1/common_types.go [hunk 3]
```diff
@@ -117,6 +117,25 @@ const (
 	// MachineSkipRemediationAnnotation is the annotation used to mark the machines that should not be considered for remediation by MachineHealthCheck reconciler.
 	MachineSkipRemediationAnnotation = "cluster.x-k8s.io/skip-remediation"
 
+	// MachineSetSkipPreflightChecksAnnotation is the annotations used to provider a coma separated list of
+	// preflight checks that should be skipped during the MachineSet reconciliation.
+	// Supported items are:
+	// - kubeadm (skips the kubeadm version skew preflight check)
+	// Example: "cluster.x-k8s.io/skip-machineset-preflight-checks": "controlplane,kubeadm".
+	MachineSetSkipPreflightChecksAnnotation = "cluster.x-k8s.io/skip-machineset-preflight-checks"
```
Comment (sbueringer) [inline api/v1beta1/common_types.go:125]:
```suggestion
	MachineSetSkipPreflightChecksAnnotation = "machineset.cluster.x-k8s.io/skip-preflight-checks"
```
WDYT?

File: api/v1beta1/common_types.go [hunk 4]
```diff
@@ -117,6 +117,25 @@ const (
...
+
+	// MachineSetPreflightCheckAll can be used to represent all the MachineSet preflight checks.
+	MachineSetPreflightCheckAll = "all"
```
Comment (sbueringer) [inline api/v1beta1/common_types.go:128]: We should probably create a separate type like we did for `MachineAddressType`, in this case maybe `MachineSetPreflightCheck`

File: api/v1beta1/common_types.go [hunk 5]
```diff
@@ -117,6 +117,25 @@ const (
...
+
+	// MachineSetPreflightCheckKubeadm is the name of the kubeadm preflight check.
```
Comment (sbueringer) [inline api/v1beta1/common_types.go:130]: let's add a bit of godoc to describe what these checks are checking

File: api/v1beta1/common_types.go [hunk 6]
```diff
@@ -117,6 +117,25 @@ const (
 	// MachineSkipRemediationAnnotation is the annotation used to mark the machines that should not be considered for remediation by MachineHealthCheck reconciler.
 	MachineSkipRemediationAnnotation = "cluster.x-k8s.io/skip-remediation"
 
+	// MachineSetSkipPreflightChecksAnnotation is the annotations used to provider a coma separated list of
+	// preflight checks that should be skipped during the MachineSet reconciliation.
+	// Supported items are:
+	// - kubeadm (skips the kubeadm version skew preflight check)
```
Comment (sbueringer) [inline api/v1beta1/common_types.go:123]: let's update this list

File: internal/contract/types.go [hunk 7]
```diff
@@ -25,7 +25,8 @@ import (
 	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
 )
 
-var errNotFound = errors.New("not found")
+// ErrNotFound is returned when a field is not found in the object.
+var ErrNotFound = errors.New("not found")
```
Comment (sbueringer) [inline internal/contract/types.go:29]:
```suggestion
// ErrFieldNotFound is returned when a field is not found in the object.
var ErrFieldNotFound = errors.New("field not found")
```
let's fix it up while we're already changing it

File: internal/controllers/machineset/machineset_controller.go [hunk 8]
```diff
@@ -71,6 +73,10 @@ var (
 
 const machineSetManagerName = "capi-machineset"
 
+// preflightFailedRequeueAfter is how long to wait before trying to scale
+// up if some preflight check  has failed.
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:77]: Let's update the doc to reflect the usage in this case

File: internal/controllers/machineset/machineset_controller.go [hunk 9]
```diff
@@ -296,7 +302,12 @@ func (r *Reconciler) reconcile(ctx context.Context, cluster *clusterv1.Cluster,
 		filteredMachines = append(filteredMachines, machine)
 	}
 
+	result := ctrl.Result{}
 	// Remediate failed Machines by deleting them.
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:306]: I would change this section to the following:
```go
	var errs []error
	machinesToRemediate := make([]*clusterv1.Machine, 0, len(filteredMachines))
	for _, machine := range filteredMachines {
		// filteredMachines contains machines in deleting status to calculate correct status.
		// skip remediation for those in deleting status.
		if !machine.DeletionTimestamp.IsZero() {
			continue
		}
		if conditions.IsFalse(machine, clusterv1.MachineOwnerRemediatedCondition) {
			machinesToRemediate = append(machinesToRemediate, machine)
		}
	}

	if len(machinesToRemediate) > 0 {
		preFlightChecksResult, err := r.runPreFlightChecks(ctx, cluster, machineSet)
		if err != nil {
			return ctrl.Result{}, err
		}
		// Delete the machines only if the pre-flight checks have passed. Do not delete machines if we cannot
		// guarantee creating new machines.
		if preFlightChecksResult.IsZero() {
			for _, machine := range machinesToRemediate {
				log.Info("Deleting machine because marked as unhealthy by the MachineHealthCheck controller")
				patch := client.MergeFrom(machine.DeepCopy())
				if err := r.Client.Delete(ctx, machine); err != nil {
					errs = append(errs, errors.Wrap(err, "failed to delete"))
					continue
				}
				conditions.MarkTrue(machine, clusterv1.MachineOwnerRemediatedCondition)
				if err := r.Client.Status().Patch(ctx, machine, patch); err != nil && !apierrors.IsNotFound(err) {
					errs = append(errs, errors.Wrap(err, "failed to update status"))
				}
			}
		} else {
			result = util.LowestNonZeroResult(result, preFlightChecksResult)
		}
	}
```

Then we only run the preflight checks when we actually have to

File: internal/controllers/machineset/machineset_controller.go (hunk 2 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:1130]: The kubeadm skew policy is pretty strict:

> If new nodes are joined to the cluster, the kubeadm binary used for kubeadm join must match the last version of kubeadm used to either create the cluster with kubeadm init or to upgrade the same node with kubeadm upgrade.
> https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#version-skew-policy

File: internal/controllers/machineset/machineset_controller.go (hunk 1 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:1109]: Which one? MD + MS?

At least for the latter check, the webhook is not enough as the CP version can just change and then existing MachineSets "fall" outside of the policy

File: internal/controllers/machineset/machineset_controller.go [hunk 10]
```diff
@@ -966,6 +994,146 @@ func (r *Reconciler) getMachineNode(ctx context.Context, cluster *clusterv1.Clus
...
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform kubernetes version skew pre-flight check: failed to parse MachineSet version %s", msVersion)
+	}
+
+	// Check the Kubernetes version skew policy.
+	// => MS minor version cannot be greater than the Control Plane minor version.
+	// => MS minor version cannot be older than 2 minor version of Control Plane.
+	// Kubernetes skew policy: https://kubernetes.io/releases/version-skew-policy/#kubelet
+	floorVersion := semver.Version{
+		Major: cpSemver.Major,
+		Minor: cpSemver.Minor - 2,
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:1103]: Should this be -3? I think the recent KEP was merged

Might be good to start with -3 so that 1.5.0+ already support th enew policy

File: internal/controllers/machineset/machineset_controller.go [hunk 11]
```diff
@@ -966,6 +994,146 @@ func (r *Reconciler) getMachineNode(ctx context.Context, cluster *clusterv1.Clus
 	return node, nil
 }
 
+func (r *Reconciler) runPreFlightChecks(ctx context.Context, cluster *clusterv1.Cluster, ms *clusterv1.MachineSet) (ctrl.Result, error) {
+	skippable := skippablePreflightChecks(ms)
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:998]: skippable sounds a bit misleading to me. They are all skippable.

**Review by sbueringer — COMMENTED** [review]
First round of feedback, I'll take a closer look tomorrow

**Review by sbueringer — COMMENTED** [review]
First round of feedback, I'll take a closer look tomorrow

File: internal/controllers/machineset/machineset_controller.go (hunk 1 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:1109]: Maybe we want to have it additionally in the webhook?

File: internal/controllers/machineset/machineset_controller.go (hunk 2 above)
Comment (chrischdi) [reply internal/controllers/machineset/machineset_controller.go:1130]: This skew policy is for the kubeadm binary, not for the kubelet version which joins the cluster (kubeadm even tests joining with an older kubelet binary). 

So the preflight check would make the assumption, that the version set at the machineset matches kubeadm version used if I'm reading it correctly? 🤔

File: internal/controllers/machineset/machineset_controller.go (hunk 1 above)
Comment (vincepri) [reply internal/controllers/machineset/machineset_controller.go:1109]: Could be on both sides?

File: api/v1beta1/common_types.go (hunk 3 above)
Comment (ykakarap) [reply api/v1beta1/common_types.go:125]: +1

File: internal/controllers/machineset/machineset_controller.go (hunk 10 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go:1103]: That might depend on the Control Plane version right? If control plane version is >= X then it will support n-3 worker nodes if not it will only support n-2 worker nodes?

File: internal/controllers/machineset/machineset_controller.go (hunk 2 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go:1130]: @chrischdi The version set here determines the VM image (or the appropriate infra specific thing) used and the assumption is that VM image uses the matching kubeadm version binary (which I believe is the is the case for the providers).

@vincepri This preflight check is only performed if using the kubeadm bootstrap provider. The preflight check will only fail when trying to create new Machines (scale down still works) using the old version because `kubeadm join` could fail as the kubeadm version skew is violated. 
Along with that, the user can also just skip the kubeadm preflight check if the user has verified that new workers running an old version can join the control plane.

File: internal/controllers/machineset/machineset_controller.go (hunk 1 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:1118]: I'll have to think a bit about it, but sounds reasonable at a first glance

File: internal/controllers/machineset/machineset_controller.go (hunk 2 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:1149]: The problem is that joining new nodes with an older kubeadm version is not supported by kubeadm upstream. It mostly works but there is no test coverage for it.

An example can be seen here: https://github.com/kubernetes-sigs/cluster-api/issues/7533#issuecomment-1319222151. The old kubeadm version wasn't able to parse the ClusterConfiguration written by the newer kubeadm version: (or in the Cluster API case, KCP)
> error execution phase preflight: unable to fetch the kubeadm-config ConfigMap: failed to decode cluster configuration data: no kind "ClusterConfiguration" is registered for version "kubeadm.k8s.io/v1beta3" in scheme "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31"
But this is just an example we're aware of, as there is no testing on the kubeadm side there simply is no official support for this.

Our idea was to have a preflight check to ensure we're acting within the official support ranges of kubeadm & Kubernetes. For folks who are sure that other combinations work as well (I assume because they tested it) we wanted to provide a way to opt-out.

There are a few cases where it's better to not act if we're outside of the support range and thus can't tell if the Machine has a chance to come up:
* MHC: It's better to keep an (at least momentarily) unhealty Machine vs deleting it and then the creation/join fails
* If autoscaler scales up a MD/MS with an older version and the Machine creations/joins continously fail we can have a lot of Machines around which have no chance for success but can become pretty expensive

File: internal/controllers/machineset/machineset_controller.go (hunk 10 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:1112]: Yeah probably. Just not sure if I want to care about the details and just use n-3 for validation :D

File: api/v1beta1/common_types.go [hunk 12]
```diff
@@ -117,6 +117,16 @@ const (
 	// MachineSkipRemediationAnnotation is the annotation used to mark the machines that should not be considered for remediation by MachineHealthCheck reconciler.
 	MachineSkipRemediationAnnotation = "cluster.x-k8s.io/skip-remediation"
 
+	// MachineSetSkipPreflightChecksAnnotation is the annotations used to provider a coma separated list of
+	// preflight checks that should be skipped during the MachineSet reconciliation.
```
Comment (sbueringer) [inline api/v1beta1/common_types.go:121]:
```suggestion
	// MachineSetSkipPreflightChecksAnnotation is the annotation used to provide a comma-separated list of
	// preflight checks that should be skipped during the MachineSet reconciliation.
```

File: api/v1beta1/common_types.go [hunk 13]
```diff
@@ -117,6 +117,16 @@ const (
...
+	// Supported items are:
```
Comment (sbueringer) [inline api/v1beta1/common_types.go:122]: kubeadm format looks something like this:
* "SystemVerification,Swap,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables"
* "KubernetesVersion", "KubeletVersion"

So I would suggest:
* KubeadmVersion
* KubernetesVersion
* ControlPlaneStable

(I would rename the constants and their values accordingly)

File: api/v1beta1/common_types.go [hunk 14]
```diff
@@ -153,6 +163,26 @@ const (
...
 
+// MachineSetPreflightCheck defines a valid machine set preflight check.
+type MachineSetPreflightCheck string
+
+const (
+	// MachineSetPreflightCheckAll can be used to represent all the MachineSet preflight checks.
+	MachineSetPreflightCheckAll MachineSetPreflightCheck = "all"
+
+	// MachineSetPreflightCheckKubeadm is the name of the kubeadm preflight check.
+	// It checks that the MachineSet and the ControlPlane conform to kubeadm version skew policy.
```
Comment (sbueringer) [inline api/v1beta1/common_types.go:174]:
```suggestion
	// It checks that the MachineSet and the ControlPlane conform to the kubeadm version skew policy.
```

File: internal/controllers/machineset/machineset_controller.go [hunk 15]
```diff
@@ -296,26 +305,43 @@ func (r *Reconciler) reconcile(ctx context.Context, cluster *clusterv1.Cluster,
...
-			}
-			conditions.MarkTrue(machine, clusterv1.MachineOwnerRemediatedCondition)
-			if err := r.Client.Status().Patch(ctx, machine, patch); err != nil && !apierrors.IsNotFound(err) {
-				errs = append(errs, errors.Wrap(err, "failed to update status"))
+			machinesToRemediate = append(machinesToRemediate, machine)
+		}
+	}
+
+	if len(machinesToRemediate) > 0 {
+		preFlightChecksResult, err := r.runPreFlightChecks(ctx, cluster, machineSet)
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:324]:
```suggestion
		preflightChecksResult, err := r.runPreflightChecks(ctx, cluster, machineSet)
```
nit: Please check other places as well

Explanation. Either preflight check is one word or two: preflight vs pre-flight. Depending on that I would use camel case or not. Given that we went with preflight elsewhere I would not use preFlight (kubeadm chose the same)

File: internal/controllers/machineset/machineset_controller.go [hunk 16]
```diff
@@ -551,15 +586,16 @@ func (r *Reconciler) syncReplicas(ctx context.Context, ms *clusterv1.MachineSet,
 		}
 
 		if len(errs) > 0 {
-			return kerrors.NewAggregate(errs)
+			return ctrl.Result{}, kerrors.NewAggregate(errs)
 		}
-		return r.waitForMachineCreation(ctx, machineList)
+		err = r.waitForMachineCreation(ctx, machineList)
+		return ctrl.Result{}, err
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:592]:
```suggestion
		return ctrl.Result{}, r.waitForMachineCreation(ctx, machineList)
```

File: internal/controllers/machineset/machineset_controller.go [hunk 17]
```diff
@@ -994,3 +1181,19 @@ func reconcileExternalTemplateReference(ctx context.Context, c client.Client, cl
...
+	if ms == nil {
+		return skippaed
+	}
+	skip := ms.Annotations[clusterv1.MachineSetSkipPreflightChecksAnnotation]
+	if skip == "" {
+		return skippaed
+	}
+	skippedList := strings.Split(skip, ",")
+	for i := range skippedList {
+		skippaed.Insert(clusterv1.MachineSetPreflightCheck(strings.TrimSpace(skippedList[i])))
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:1196]: What happens if someone is using an invalid string?

File: internal/controllers/machineset/machineset_controller.go [hunk 18]
```diff
@@ -966,6 +1003,156 @@ func (r *Reconciler) getMachineNode(ctx context.Context, cluster *clusterv1.Clus
 	return node, nil
 }
 
+func (r *Reconciler) runPreFlightChecks(ctx context.Context, cluster *clusterv1.Cluster, ms *clusterv1.MachineSet) (ctrl.Result, error) {
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:1006]: WDYT about moving this func and funcs that we use in this func to machineset_preflight.go?

File: api/v1beta1/common_types.go [hunk 19]
```diff
@@ -153,6 +163,26 @@ const (
...
 )
 
+// MachineSetPreflightCheck defines a valid machine set preflight check.
+type MachineSetPreflightCheck string
+
+const (
+	// MachineSetPreflightCheckAll can be used to represent all the MachineSet preflight checks.
+	MachineSetPreflightCheckAll MachineSetPreflightCheck = "all"
+
+	// MachineSetPreflightCheckKubeadm is the name of the kubeadm preflight check.
```
Comment (sbueringer) [inline api/v1beta1/common_types.go:173]: I think it would be good to document for each check under which circumstances it is executed / what it depends on (e.g. controlPlaneRef must exist in Cluster, ...)

File: internal/controllers/machineset/machineset_controller.go [hunk 20]
```diff
@@ -966,6 +1003,156 @@ func (r *Reconciler) getMachineNode(ctx context.Context, cluster *clusterv1.Clus
...
+
+	// If the cluster does not have a control plane reference then there is nothing to do. Return early.
+	if cluster.Spec.ControlPlaneRef == nil {
+		return ctrl.Result{}, nil
+	}
+
+	// Get the control plane object.
+	controlPlane, err := external.Get(ctx, r.Client, cluster.Spec.ControlPlaneRef, cluster.Namespace)
+	if err != nil {
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform pre-flight checks: failed to get ControlPlane %s", klog.KRef(cluster.Spec.ControlPlaneRef.Namespace, cluster.Spec.ControlPlaneRef.Name))
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:1021]:
```suggestion
		return ctrl.Result{}, errors.Wrapf(err, "failed to perform preflight checks: failed to get ControlPlane %s", klog.KRef(cluster.Spec.ControlPlaneRef.Namespace, cluster.Spec.ControlPlaneRef.Name))
```

File: internal/controllers/machineset/machineset_controller.go [hunk 21]
```diff
@@ -966,6 +1003,156 @@ func (r *Reconciler) getMachineNode(ctx context.Context, cluster *clusterv1.Clus
...
+	// we do not have enough information. Return early.
+	cpVersion, err := contract.ControlPlane().Version().Get(controlPlane)
+	if err != nil {
+		if errors.Is(err, contract.ErrFieldNotFound) {
+			return ctrl.Result{}, nil
+		}
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform pre-flight checks: failed to get the version of ControlPlane %s", cpKlogRef)
+	}
+
+	// Run the control plane preflight check.
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:1036]: I think it would be good to run through all preflight checks (only the ones which are not skipped of course) and then aggregate the results

File: internal/controllers/machineset/machineset_controller.go [hunk 22]
```diff
@@ -966,6 +1003,156 @@ func (r *Reconciler) getMachineNode(ctx context.Context, cluster *clusterv1.Clus
...
+	log := ctrl.LoggerFrom(ctx)
+	cpKlogRef := klog.KRef(controlPlane.GetNamespace(), controlPlane.GetName())
+
+	// Check that the control plane is not provisioning.
+	isProvisioning, err := contract.ControlPlane().IsProvisioning(controlPlane)
+	if err != nil {
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform control plane pre-flight check: failed to check if ControlPlane %s is provisioning", cpKlogRef)
+	}
+	if isProvisioning {
+		log.Info(fmt.Sprintf("Pre-flight check failed: ControlPlane %s is provisioning", cpKlogRef))
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:1071]: I generally like the log, but I think it would be good if we provide context about what we're trying to do in this moment (e.g. scale up or delete a Machine for remediation).

Maybe we can pass that down here?

File: internal/controllers/machineset/machineset_controller.go (hunk 10 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:1112]: I think it's fine to use - 2 for now. But this is something we should check when we start bumping to 1.28. Could you already create the Task for 1.28 and add a reminder as a release-specific sub-task?

File: internal/controllers/machineset/machineset_controller.go (hunk 1 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:1118]: I think it's fine to add both checks to the MD + MS validating webhook.

But they should only block on create and on update only if the version is changing. They shouldn't block an update where the version is not changed in my opinion

I would prefer implementing the webhooks in a follow-up PR though.

Hm, but it wouldn't make sense to disable the validation on the webhooks via the skip preflight check annotation. As the webhook is not a preflight check. We could maybe choose to only return warnings in the webhook?

@vincepri WDYT?

File: internal/controllers/machineset/machineset_controller.go [hunk 23]
```diff
@@ -966,6 +1003,156 @@ func (r *Reconciler) getMachineNode(ctx context.Context, cluster *clusterv1.Clus
...
+	// kubeadm skew policy: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#kubeadm-s-skew-against-kubeadm
+	bootstrapConfigRef := ms.Spec.Template.Spec.Bootstrap.ConfigRef
+	groupVersion, err := schema.ParseGroupVersion(bootstrapConfigRef.APIVersion)
+	if err != nil {
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform kubeadm version skew pre-flight check: failed to parse APIVersion %s", bootstrapConfigRef.APIVersion)
+	}
+	kubeadmBootstrapProviderUsed := bootstrapConfigRef.Kind == "KubeadmConfigTemplate" &&
+		groupVersion.Group == bootstrapv1.GroupVersion.Group
+	if kubeadmBootstrapProviderUsed {
+		if cpVersion != msVersion {
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:1148]: Should we only compare major+minor version? I think the patch version should not matter

Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:1148]: (let's move parsing the cpVersion one level up so we do it directly after we get it from the CP and only have to do it once)

File: internal/controllers/machineset/machineset_controller.go (hunk 17 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go:1196]: Effectively it will be ignored.
Example: If a user adds `foobar` in the annotation then it will be considered in the `skipped` set (the type conversion wont be a problem - any string can be converted to `clusterv1.MachineSetPreflightCheck`). Since there is not preflight check called `foobar` it will become no-op.

File: internal/controllers/machineset/machineset_controller.go (hunk 18 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go:1006]: Moved the functions (and the tests) to separate file.

File: internal/controllers/machineset/machineset_controller.go (hunk 23 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go:1148]: You are right. The kubeadm version skew only talks about the MINOR. Will change it.

File: internal/controllers/machineset/machineset_controller.go (hunk 10 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go:1112]: Created the v1.28 issue and added a release specific task under it: https://github.com/kubernetes-sigs/cluster-api/issues/8708

File: internal/controllers/machineset/machineset_controller.go (hunk 22 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go:1071]: Are you suggesting something like adding an `action` (or some better name) argument to all the preflight check functions and adjust the logs accordingly?

`action` - could be `Machine Remediation` or `Scale up` and in the logs we will do something like 
```go
log.Info(fmt.Sprintf("Preflight check %q failed while performing %s: ControlPlane %s is provisioning", clusterv1.MachineSetPreflightCheckControlPlaneStable, action, cpKlogRef))
```
(will also include an if else block to handle the log incase `action == ""`)

Another option would be to pass a a modifed logger in the context that has a key-value pair which would specify the context of the preflight checks.

File: internal/controllers/machineset/machineset_controller.go (hunk 17 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go]: Alright, thx for the info.

Can we add validation in the MS webhook to validate the list?

File: internal/controllers/machineset/machineset_controller.go (hunk 22 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go]: The first. Although it would be nice to flip the order and mention what we're doing first

File: api/v1beta1/common_types.go (hunk 13 above)
Comment (sbueringer) [reply api/v1beta1/common_types.go:122]: @ykakarap Could we use the same kapitalization as kubeadm?

File: config/manager/manager.yaml [hunk 24]
```diff
@@ -22,7 +22,7 @@ spec:
           args:
             - "--leader-elect"
             - "--metrics-bind-addr=localhost:8080"
-            - "--feature-gates=MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false},ClusterTopology=${CLUSTER_TOPOLOGY:=false},RuntimeSDK=${EXP_RUNTIME_SDK:=false},LazyRestmapper=${EXP_LAZY_RESTMAPPER:=false}"
+            - "--feature-gates=MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false},ClusterTopology=${CLUSTER_TOPOLOGY:=false},RuntimeSDK=${EXP_RUNTIME_SDK:=false},LazyRestmapper=${EXP_LAZY_RESTMAPPER:=false},MachineSetPreflightChecks=${MACHINESET_PREFLIGHT_CHECKS:=false}"
```
[the remark this answers is not in the document]
Comment (sbueringer) [reply config/manager/manager.yaml:25]: Let's enable and mention this everywhere (docker.yaml, testing.md, tilt.md, experimental-features.md)

Short mention in experimental-features.md like the other feature gates is fine for this PR. Would be good to have a follow-up PR with more documentation of the experimental feature (short summary of the feature on a page like this: https://cluster-api.sigs.k8s.io/tasks/experimental-features/machine-pools.html).

File: internal/controllers/machineset/machineset_controller.go [hunk 25]
```diff
@@ -355,15 +373,17 @@ func (r *Reconciler) reconcile(ctx context.Context, cluster *clusterv1.Cluster,
...
-		return ctrl.Result{RequeueAfter: time.Duration(machineSet.Spec.MinReadySeconds) * time.Second}, nil
+		minReadyResult := ctrl.Result{RequeueAfter: time.Duration(machineSet.Spec.MinReadySeconds) * time.Second}
+		result = util.LowestNonZeroResult(result, minReadyResult)
+		return result, nil
 	}
 
 	// Quickly reconcile until the nodes become Ready.
 	if machineSet.Status.ReadyReplicas != replicas {
-		return ctrl.Result{RequeueAfter: 15 * time.Second}, nil
+		result = util.LowestNonZeroResult(result, ctrl.Result{RequeueAfter: 15 * time.Second})
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:383]:
```suggestion
		result = util.LowestNonZeroResult(result, ctrl.Result{RequeueAfter: 15 * time.Second})
		return result, nil
```
nit: for consistency and to be more explicit

File: internal/controllers/machineset/machineset_controller.go [hunk 26]
```diff
@@ -355,15 +373,17 @@ func (r *Reconciler) reconcile(ctx context.Context, cluster *clusterv1.Cluster,
...
 	}
 
-	return ctrl.Result{}, nil
+	return result, nil
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:386]:
```suggestion
	return ctrl.Result{}, nil
```

File: internal/controllers/machineset/machineset_preflight.go [hunk 27]
```diff
@@ -0,0 +1,211 @@
...
+	cpVersion, err := contract.ControlPlane().Version().Get(controlPlane)
+	if err != nil {
+		if errors.Is(err, contract.ErrFieldNotFound) {
+			return ctrl.Result{}, nil
+		}
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform preflight checks: failed to get the version of ControlPlane %s", cpKlogRef)
+	}
+	cpSemver, err := semver.ParseTolerant(*cpVersion)
+	if err != nil {
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform preflight checks: failed to parse ControlPlane version %s", *cpVersion)
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight.go:82]:
```suggestion
		return ctrl.Result{}, errors.Wrapf(err, "failed to perform preflight checks: failed to parse version %q of ControlPlane %s", *cpVersion, cpKlogRef)
```

Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight.go:82]: Probably the same for the MachineSet error in l.101. It's a bit redundant in this case as the logger will have the MachineSet as well, but it would be consistent with this error here

File: internal/controllers/machineset/machineset_preflight.go [hunk 28]
```diff
@@ -0,0 +1,211 @@
...
+	// => MS minor version cannot be greater than the Control Plane minor version.
+	// => MS minor version cannot be older than 2 minor versions of Control Plane.
+	// Kubernetes skew policy: https://kubernetes.io/releases/version-skew-policy/#kubelet
+	floorVersion := semver.Version{
+		Major: cpSemver.Major,
+		Minor: cpSemver.Minor - 2,
+		Patch: 0,
+	}
+	if msSemver.GT(cpSemver) || msSemver.LT(floorVersion) {
+		log.Info(fmt.Sprintf("Preflight check %q failed: MachineSet version (%s) and ControlPlane version (%s) do not conform to the kubernetes version skew policy", clusterv1.MachineSetPreflightCheckKubernetesVersion, msSemver.String(), cpSemver.String()))
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight.go:163]: Let's split those cases in individual ifs with logs which describe the exact error, e.g.:
* Preflight check %q failed: MachineSet version (%s) and ControlPlane version (%s) do not conform to the kubernetes version skew policy: MachineSet version is higher than ControlPlane version
* Preflight check %q failed: MachineSet version (%s) and ControlPlane version (%s) do not conform to the kubernetes version skew policy: MachineSet version is more than 2 minor versions older than the ControlPlane version

File: internal/controllers/machineset/machineset_preflight.go [hunk 29]
```diff
@@ -0,0 +1,211 @@
...
+	}
+	if isUpgrading {
+		log.Info(fmt.Sprintf("Preflight check %q failed: ControlPlane %s is upgrading", clusterv1.MachineSetPreflightCheckControlPlaneStable, cpKlogRef))
+		return ctrl.Result{RequeueAfter: preflightFailedRequeueAfter}, nil
+	}
+
+	return ctrl.Result{}, nil
+}
+
+func (r *Reconciler) kubernetesVersionPreflightCheck(ctx context.Context, cpSemver semver.Version, msSemver semver.Version) ctrl.Result {
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight.go:150]:
```suggestion
func (r *Reconciler) kubernetesVersionPreflightCheck(ctx context.Context, cpSemver, msSemver semver.Version) ctrl.Result {
```
nit: same below

File: internal/controllers/machineset/machineset_preflight.go [hunk 30]
```diff
@@ -0,0 +1,211 @@
...
+		return ctrl.Result{}, nil
+	}
+
+	// If using kubeadm bootstrap provider, check the kubeadm version skew policy.
+	// => MS version should match (major+minor) the Control Plane version.
+	// kubeadm skew policy: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#kubeadm-s-skew-against-kubeadm
+	bootstrapConfigRef := ms.Spec.Template.Spec.Bootstrap.ConfigRef
+	groupVersion, err := schema.ParseGroupVersion(bootstrapConfigRef.APIVersion)
+	if err != nil {
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform %q preflight check: failed to parse APIVersion %s", clusterv1.MachineSetPreflightCheckKubeadmVersion, bootstrapConfigRef.APIVersion)
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight.go:184]:
```suggestion
		return ctrl.Result{}, errors.Wrapf(err, "failed to perform %q preflight check: failed to parse bootstrap configRef APIVersion %s", clusterv1.MachineSetPreflightCheckKubeadmVersion, bootstrapConfigRef.APIVersion)
```

File: internal/controllers/machineset/machineset_preflight.go [hunk 31]
```diff
@@ -0,0 +1,211 @@
...
+	}
+	kubeadmBootstrapProviderUsed := bootstrapConfigRef.Kind == "KubeadmConfigTemplate" &&
+		groupVersion.Group == bootstrapv1.GroupVersion.Group
+	if kubeadmBootstrapProviderUsed {
+		if cpSemver.Major != msSemver.Major || cpSemver.Minor != msSemver.Minor {
+			log.Info(fmt.Sprintf("Preflight check %q failed: MachineSet version (%s) and ControlPlane version (%s) do not conform to kubeadm version skew policy: kubeadm bootstrap provider only supports joining with the same (major+minor) version as the control plane", clusterv1.MachineSetPreflightCheckKubeadmVersion, msSemver.String(), cpSemver.String()))
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight.go:190]:
```suggestion
			log.Info(fmt.Sprintf("Preflight check %q failed: MachineSet version (%s) and ControlPlane version (%s) do not conform to kubeadm version skew policy: kubeadm only supports joining with the same (major+minor) version as the control plane", clusterv1.MachineSetPreflightCheckKubeadmVersion, msSemver.String(), cpSemver.String()))
```
nit: Only to keep it a bit shorter

File: internal/controllers/machineset/machineset_preflight_test.go [hunk 32]
```diff
@@ -0,0 +1,472 @@
...
+
+	t.Run("should run preflight checks if the feature gate is enabled", func(t *testing.T) {
+		defer utilfeature.SetFeatureGateDuringTest(t, feature.Gates, feature.MachineSetPreflightChecks, true)()
+
+		tests := []struct {
+			name         string
+			cluster      *clusterv1.Cluster
+			controlPlane *unstructured.Unstructured
+			machineSet   *clusterv1.MachineSet
+			wantPass     bool
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight_test.go:68]: Would be good to also test the error cases

File: internal/controllers/machineset/machineset_preflight_test.go [hunk 33]
```diff
@@ -0,0 +1,472 @@
...
+				},
+				controlPlane: controlPlaneStable,
+				machineSet: &clusterv1.MachineSet{
+					ObjectMeta: metav1.ObjectMeta{
+						Namespace: ns,
+					},
+					Spec: clusterv1.MachineSetSpec{
+						Template: clusterv1.MachineTemplateSpec{
+							Spec: clusterv1.MachineSpec{
+								Version: pointer.String("v1.25.6"),
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight_test.go:297]: Let's please use 1.24.0 to test the lower boundary for a pass

File: internal/controllers/machineset/machineset_preflight_test.go [hunk 34]
```diff
@@ -0,0 +1,472 @@
...
+							},
+						},
+					},
+				},
+				wantPass: true,
+			},
+			{
+				name: "kubeadm version preflight check: should fail if the machine set version is not equal to control plane version when using kubeadm bootstrap provider",
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight_test.go:305]: As far as I can tell major + minor are the same, this should pass?

File: internal/controllers/machineset/machineset_preflight_test.go [hunk 35]
```diff
@@ -0,0 +1,472 @@
...
+				},
+				controlPlane: controlPlaneStable,
+				machineSet: &clusterv1.MachineSet{
+					ObjectMeta: metav1.ObjectMeta{
+						Namespace: ns,
+					},
+					Spec: clusterv1.MachineSetSpec{
+						Template: clusterv1.MachineTemplateSpec{
+							Spec: clusterv1.MachineSpec{
+								Version: pointer.String("v1.26.0"),
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight_test.go:351]: Let's use a version that violates the skew. This should even pass with the preflight check

File: internal/controllers/machineset/machineset_preflight_test.go [hunk 36]
```diff
@@ -0,0 +1,472 @@
...
+					ObjectMeta: metav1.ObjectMeta{
+						Namespace: ns,
+						Annotations: map[string]string{
+							clusterv1.MachineSetSkipPreflightChecksAnnotation: "foobar," + string(clusterv1.MachineSetPreflightCheckKubeadmVersion),
+						},
+					},
+					Spec: clusterv1.MachineSetSpec{
+						Template: clusterv1.MachineTemplateSpec{
+							Spec: clusterv1.MachineSpec{
+								Version: pointer.String("v1.26.0"),
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight_test.go:379]: Same

File: internal/controllers/machineset/machineset_preflight_test.go (hunk 34 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight_test.go:305]: Note: This only fails because it fails the Kubernetes version skew preflight check

File: internal/controllers/machineset/machineset_preflight.go (hunk 28 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight.go:163]: I think `msSemver.GT(cpSemver)` should also check for the minor version. The patch version doesn't seem to matter: https://kubernetes.io/releases/version-skew-policy/#kubelet

File: api/v1beta1/common_types.go (hunk 13 above)
Comment (ykakarap) [reply api/v1beta1/common_types.go:122]: Ah okay.  misunderstood your original comment.

File: internal/controllers/machineset/machineset_controller.go (hunk 26 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go:386]: We need to return `result` here or else the value that we calculate in l.350 is lost and never used.

File: internal/controllers/machineset/machineset_preflight_test.go (hunk 32 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_preflight_test.go:68]: I have added test cases to cover the important error cases. For the other cases, example: `IsProvisioning`, it looks like it would basically become equivalent to testing those functions and the current tests don't seem like the right place to test them.

File: config/manager/manager.yaml (hunk 24 above)
[the remark this answers is not in the document]
Comment (ykakarap) [reply config/manager/manager.yaml:25]: Add some short description about the feature gate in this PR and opened an issue to follow-up for a documentation improvement.

File: internal/controllers/machineset/machineset_controller.go (hunk 22 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go]: Changed it to add the `action` parameter. PTAL.

File: internal/controllers/machineset/machineset_controller.go (hunk 17 above)
Comment (ykakarap) [reply internal/controllers/machineset/machineset_controller.go]: Done. Also added the validation to MD webhook because users might choose to apply the annotation on an MD.

File: internal/controllers/machineset/machineset_controller.go (hunk 26 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:387]: Ah thx. Good point

File: internal/controllers/machineset/machineset_preflight_test.go (hunk 32 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight_test.go:71]: Sounds good!

File: config/manager/manager.yaml [hunk 37]
```diff
@@ -22,7 +22,7 @@ spec:
           args:
             - "--leader-elect"
             - "--metrics-bind-addr=localhost:8080"
-            - "--feature-gates=MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false},ClusterTopology=${CLUSTER_TOPOLOGY:=false},RuntimeSDK=${EXP_RUNTIME_SDK:=false},LazyRestmapper=${EXP_LAZY_RESTMAPPER:=false}"
+            - "--feature-gates=MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false},ClusterTopology=${CLUSTER_TOPOLOGY:=false},RuntimeSDK=${EXP_RUNTIME_SDK:=false},LazyRestmapper=${EXP_LAZY_RESTMAPPER:=false},MachineSetPreflightChecks=${EXP_MACHINESET_PREFLIGHT_CHECKS:=false}"
```
Comment (sbueringer) [inline config/manager/manager.yaml:25]:
```suggestion
            - "--feature-gates=MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false},ClusterTopology=${CLUSTER_TOPOLOGY:=false},RuntimeSDK=${EXP_RUNTIME_SDK:=false},LazyRestmapper=${EXP_LAZY_RESTMAPPER:=false},MachineSetPreflightChecks=${EXP_MACHINE_SET_PREFLIGHT_CHECKS:=false}"
```
nit: following the pattern of MACHINE_POOL and the others

File: docs/book/src/reference/labels_and_annotations.md [hunk 38]
```diff
@@ -19,38 +19,39 @@
...
+| cluster.x-k8s.io/skip-machineset-preflight-checks                 | It can be applied on MachineSet resources to specify the list of pre-flight checks to skip during MachineSet reconciliation. The value is a coma seperated list of skippable pre-flight checks. Supported pre-flight checks are: All, KubeadmVersion, KubernetesVersion, ControlPlaneStable.                                                                                                                                                                                                                                                                |
```
Comment (sbueringer) [inline docs/book/src/reference/labels_and_annotations.md:40]:
```suggestion
| cluster.x-k8s.io/skip-machineset-preflight-checks                 | It can be applied on MachineDeployment and MachineSet resources to specify a comma-separated list of preflight checks that should be skipped during MachineSet reconciliation. Supported pre-flight checks are: All, KubeadmVersion, KubernetesVersion, ControlPlaneStable.                                                                                                                                                                                                                                                                |
```

File: internal/controllers/machineset/machineset_preflight.go [hunk 39]
```diff
@@ -0,0 +1,217 @@
...
+}
+
+func (r *Reconciler) controlPlaneStablePreflightCheck(ctx context.Context, controlPlane *unstructured.Unstructured, action string) (ctrl.Result, error) {
+	log := ctrl.LoggerFrom(ctx)
+	cpKlogRef := klog.KRef(controlPlane.GetNamespace(), controlPlane.GetName())
+
+	// Check that the control plane is not provisioning.
+	isProvisioning, err := contract.ControlPlane().IsProvisioning(controlPlane)
+	if err != nil {
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform %q: failed to perform %q preflight check: failed to check if ControlPlane %s is provisioning", action, clusterv1.MachineSetPreflightCheckControlPlaneStable, cpKlogRef)
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_preflight.go:137]:
```suggestion
		return ctrl.Result{}, errors.Wrapf(err, "failed to perform %q preflight check: failed to check if ControlPlane %s is provisioning", action, clusterv1.MachineSetPreflightCheckControlPlaneStable, cpKlogRef)
```
It's redundant in the errors as we already add the action one layer above when we wrap

(same in other places below, we should keep it in the logs though)

**Comment by sbueringer** [comment]
I think this should be ~ the last round from my side, +/- some nits.

**Comment by ykakarap** [comment]
Based on the discussion during the May 17th office hours we decided to place the MachineSet preflight checks behind a feature gate (`MachineSetPreflightChecks`).

The feature gate is alpha will be off by default and therefore there wont be any changes to any of the existing behavior.
Users can enable the feature gate at their own discretion.

This will give us time in the mean time as kubeadm works on its version skew.
Note that the kubeadm preflight check will still be needed for older Kubernetes versions.

File: api/v1beta1/common_types.go [hunk 40]
```diff
@@ -173,6 +183,33 @@ const (
...
+	MachineSetPreflightCheckKubeadmVersion MachineSetPreflightCheck = "KubeadmVersion"
+
+	// MachineSetPreflightCheckKubernetesVersion is the name of the kubernetes-version preflight check.
+	// It checks that the MachineSet and the ControlPlane conform to the  kubernetes version skew policy.
+	// The preflight check is only run if a ControlPlane is used (controlPlaneRef must exist in the Cluster),
+	// the ControlPlane has a version and the MachineSet has a version.
+	MachineSetPreflightCheckKubernetesVersion MachineSetPreflightCheck = "KubernetesVersion"
+
+	// MachineSetPreflightCheckControlPlaneStable is the name of the control-plane-stable preflight check.
+	// It checks that the control plane is not provisioning and not upgrading.
```
Comment (fabriziopandini) [inline api/v1beta1/common_types.go:207]:
```suggestion
	// MachineSetPreflightCheckControlPlaneStable is the name of the preflight check
	// that verifies if the control plane is stable, which means it is not provisioning and not upgrading.
```

File: api/v1beta1/common_types.go [hunk 41]
```diff
@@ -173,6 +183,33 @@ const (
...
+	// The preflight check is only run if a ControlPlane is used (controlPlaneRef must exist in the Cluster)
+	// and the ControlPlane has a version.
+	MachineSetPreflightCheckControlPlaneStable MachineSetPreflightCheck = "ControlPlaneStable"
```
Comment (fabriziopandini) [inline api/v1beta1/common_types.go:210]:
```suggestion
	MachineSetPreflightCheckControlPlaneIsStable MachineSetPreflightCheck = "ControlPlaneIsStable"
```

File: api/v1beta1/machinedeployment_webhook.go [hunk 42]
```diff
@@ -214,6 +215,14 @@ func (m *MachineDeployment) validate(old *MachineDeployment) error {
 		)
 	}
 
+	// MachineSet preflight checks that should be skipped could also be set as annotation on the MachineDeployment
+	// since MachineDeployment annotations are synced to the MachineSet.
```
Comment (fabriziopandini) [inline api/v1beta1/machinedeployment_webhook.go:219]: Let's add this note to the annotation comment as well, it could be helpful for the users that are not aware of the propagation rules.

File: docs/book/src/tasks/experimental-features/machineset-preflight-checks.md [hunk 43]
```diff
@@ -0,0 +1,12 @@
+# Experimental Feature: MachineSetPreflightChecks (alpha)
+
+The `MachineSetPreflightChecks` feature is introduced to provide additional safety while creating new Machines for a MachineSet.
```
Comment (fabriziopandini) [inline docs/book/src/tasks/experimental-features/machineset-preflight-checks.md:3]:
```suggestion
The `MachineSetPreflightChecks` feature can provide additional safety while creating new Machines for a MachineSet.
```

File: docs/book/src/tasks/experimental-features/machineset-preflight-checks.md [hunk 44]
```diff
@@ -0,0 +1,12 @@
...
+
+**Feature gate name**: `MachineSetPreflightChecks`
+
+**Variable name to enable/disable the feature gate**: `EXP_MACHINE_SET_PREFLIGHT_CHECKS`
+
+The following preflight checks are performed when the feature is enabled:
+* ControlPlaneStable
+* KubeadmVersion
+* KubernetesVersion
```
Comment (fabriziopandini) [inline docs/book/src/tasks/experimental-features/machineset-preflight-checks.md:12]: Is it possible to provide a user-oriented explanation about what is check is implemented/why it is important?

Also, what about adding a note about the possibility to skip preflight check by exception/on a MD or MS bases once the feature flag is enabled?

File: internal/controllers/machineset/machineset_controller.go [hunk 45]
```diff
@@ -296,26 +296,43 @@ func (r *Reconciler) reconcile(ctx context.Context, cluster *clusterv1.Cluster,
 		filteredMachines = append(filteredMachines, machine)
 	}
 
+	result := ctrl.Result{}
```
Comment (fabriziopandini) [inline internal/controllers/machineset/machineset_controller.go:299]: nit, can we move this before L314, where this variable is actually used

File: internal/controllers/machineset/machineset_preflight.go [hunk 46]
```diff
@@ -0,0 +1,220 @@
...
+
+	// If the Control Plane version is not set then we are dealing with a control plane that does not support version
+	// or a control plane where the version is not set. In both cases we cannot perform any preflight checks as
+	// we do not have enough information. Return early.
+	cpVersion, err := contract.ControlPlane().Version().Get(controlPlane)
+	if err != nil {
+		if errors.Is(err, contract.ErrFieldNotFound) {
+			return ctrl.Result{}, nil
+		}
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform %q: failed to perform preflight checks: failed to get the version of ControlPlane %s", action, cpKlogRef)
```
Comment (fabriziopandini) [inline internal/controllers/machineset/machineset_preflight.go:81]: q: should this be treated as error or simply became a no-op given that preflight checks do not apply if CP do not support version?

File: internal/controllers/machineset/machineset_preflight.go [hunk 47]
```diff
@@ -0,0 +1,220 @@
...
+
+	// If the cluster does not have a control plane reference then there is nothing to do. Return early.
+	if cluster.Spec.ControlPlaneRef == nil {
+		return ctrl.Result{}, nil
+	}
+
+	// Get the control plane object.
+	controlPlane, err := external.Get(ctx, r.Client, cluster.Spec.ControlPlaneRef, cluster.Namespace)
+	if err != nil {
+		return ctrl.Result{}, errors.Wrapf(err, "failed to perform %q: failed to perform preflight checks: failed to get ControlPlane %s", action, klog.KRef(cluster.Spec.ControlPlaneRef.Namespace, cluster.Spec.ControlPlaneRef.Name))
```
Comment (fabriziopandini) [inline internal/controllers/machineset/machineset_preflight.go:69]: q: should this be treated as error or simply became a no-op given that preflight checks do not apply if there is no CP?

File: internal/controllers/machineset/machineset_preflight.go [hunk 48]
```diff
@@ -0,0 +1,220 @@
...
+	if len(errList) > 0 {
+		return ctrl.Result{}, errors.Wrapf(kerrors.NewAggregate(errList), "failed to perform %q: failed to perform preflight checks", action)
+	}
+	if len(preflightCheckErrs) > 0 {
+		preflightCheckErrStrings := []string{}
+		for _, v := range preflightCheckErrs {
+			preflightCheckErrStrings = append(preflightCheckErrStrings, *v)
+		}
+		log.Info(fmt.Sprintf("While performing %q preflight checks failed: %s", action, strings.Join(preflightCheckErrStrings, ",")))
+		return ctrl.Result{RequeueAfter: preflightFailedRequeueAfter}, nil
```
Comment (fabriziopandini) [inline internal/controllers/machineset/machineset_preflight.go:138]: cc @sbueringer 
given the work on removing remaining usage of requeue After

File: internal/controllers/machineset/machineset_preflight.go [hunk 49]
```diff
@@ -0,0 +1,220 @@
...
+	ctrl "sigs.k8s.io/controller-runtime"
+
+	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
+	bootstrapv1 "sigs.k8s.io/cluster-api/bootstrap/kubeadm/api/v1beta1"
+	"sigs.k8s.io/cluster-api/controllers/external"
+	"sigs.k8s.io/cluster-api/feature"
+	"sigs.k8s.io/cluster-api/internal/contract"
+)
+
+type preflightCheckError *string
```
Comment (fabriziopandini) [inline internal/controllers/machineset/machineset_preflight.go:42]: should this be 
```suggestion
type preflightCheckMessage *string
```
because calling Error something that is not an error makes the code less readable
(same applies to all the variables storing those messages)

File: internal/controllers/machineset/machineset_preflight.go [hunk 50]
```diff
@@ -0,0 +1,220 @@
...
+func (r *Reconciler) controlPlaneStablePreflightCheck(controlPlane *unstructured.Unstructured) (preflightCheckError, error) {
+	cpKlogRef := klog.KRef(controlPlane.GetNamespace(), controlPlane.GetName())
+
+	// Check that the control plane is not provisioning.
+	isProvisioning, err := contract.ControlPlane().IsProvisioning(controlPlane)
+	if err != nil {
+		return nil, errors.Wrapf(err, "failed to perform %q preflight check: failed to check if ControlPlane %s is provisioning", clusterv1.MachineSetPreflightCheckControlPlaneStable, cpKlogRef)
+	}
+	if isProvisioning {
+		return pointer.String(fmt.Sprintf("preflight check %q failed: ControlPlane %s is provisioning", clusterv1.MachineSetPreflightCheckControlPlaneStable, cpKlogRef)), nil
```
Comment (fabriziopandini) [inline internal/controllers/machineset/machineset_preflight.go:152]: Wondering if this is the right wording, because "preflight check is failed" might suggest the user there is some issue, while instead this is a handled condition that we are handling by deferring machine creation.
(same for other preflight checks).

However, this really depend by how this condition is going to surface to the users

File: api/v1beta1/common_types.go [hunk 51]
```diff
@@ -173,6 +183,33 @@ const (
...
+const (
+	// MachineSetPreflightCheckAll can be used to represent all the MachineSet preflight checks.
+	MachineSetPreflightCheckAll MachineSetPreflightCheck = "All"
+
+	// MachineSetPreflightCheckKubeadmVersion is the name of the kubeadm-version preflight check.
+	// It checks that the MachineSet and the ControlPlane conform to the kubeadm version skew policy.
+	// The preflight check is only run if a ControlPlane is used (controlPlaneRef must exist in the Cluster),
+	// the ControlPlane has a version, the MachineSet has a version and the MachineSet uses the Kubeadm bootstrap
+	// provider.
+	MachineSetPreflightCheckKubeadmVersion MachineSetPreflightCheck = "KubeadmVersion"
```
[the remark this answers is not in the document]
Comment (sbueringer) [reply api/v1beta1/common_types.go:198]: I would have aligned to kubeadm which has a precheck called "KubernetesVersion". But not strong opinion if you prefer "KubernetesVersionSkew" and "KubeadmVersionSkew"

File: api/v1beta1/common_types.go [hunk 52]
```diff
@@ -173,6 +183,33 @@ const (
...
 
+// MachineSetPreflightCheck defines a valid MachineSet preflight check.
+type MachineSetPreflightCheck string
+
+const (
+	// MachineSetPreflightCheckAll can be used to represent all the MachineSet preflight checks.
+	MachineSetPreflightCheckAll MachineSetPreflightCheck = "All"
+
+	// MachineSetPreflightCheckKubeadmVersion is the name of the kubeadm-version preflight check.
+	// It checks that the MachineSet and the ControlPlane conform to the kubeadm version skew policy.
```
[the remark this answers is not in the document]
Comment (sbueringer) [reply api/v1beta1/common_types.go:194]: > if the new machine being created for the MachineSet

we also run this before deleting machines for remedation.

File: docs/book/src/tasks/experimental-features/machineset-preflight-checks.md (hunk 44 above)
Comment (sbueringer) [reply docs/book/src/tasks/experimental-features/machineset-preflight-checks.md:12]: I assume the plan was to do this in https://github.com/kubernetes-sigs/cluster-api/issues/8717 as a follow-up

File: internal/controllers/machineset/machineset_preflight.go (hunk 46 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight.go:81]: I think this case is handled in l.78. This here is the case where the CP has the field but it is not a string.

I would prefer returning the error here to surface the issue

File: internal/controllers/machineset/machineset_preflight.go (hunk 47 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight.go:69]: Same here. This is the case where we have a control plane ref in Cluster but the control plane does not exist. I would prefer surfacing the error over just ignoring it.

File: internal/controllers/machineset/machineset_preflight.go (hunk 48 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight.go:138]: Thx. I already thought about it and would prefer to use a requeue for now. I think this is one of the more complicated cases where it's hard to figure out if we actually get an event for all cases where the preflight checks could have failed.

E.g. is every MachineSet re-reconciled as soon as the Control Plane becomes stable.

I think let's use the requeue for now and if scale tests show that this is a problem let's iterate.

File: internal/controllers/machineset/machineset_preflight.go (hunk 49 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight.go:42]: But isn't it a preflightCheckError? If the problem is the data type vs variable suffix, I would prefer to use `preflightCheckErrorMessage`

We could also change the type to error if you prefer. We just thought it doesn't make sense as we just put a string into an error and then read it back.

File: internal/controllers/machineset/machineset_preflight.go (hunk 50 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight.go:152]: But isn't it correct that the preflight check failed? 

And depending on the situation the user might have to do something, but this depends on a lot of factors (e.g. ClusterClass vs legacy cluster)

File: api/v1beta1/common_types.go (hunk 51 above)
[the remark this answers is not in the document]
Comment (fabriziopandini) [reply api/v1beta1/common_types.go:198]: I think we should look at this from the user's perspective, and make it clear what kind of validation this check is performing; consistency with Kubeadm is less of a concern IMO, mostly because there is nothing enforcing consistency between the implementation of the checks (they might diverge over time, if they are not already).

In this case, it is validating we are consistent with the KubeadmVersion Skew policy, so I think adding skew is a valuable addition.

File: api/v1beta1/common_types.go (hunk 52 above)
[the remark this answers is not in the document]
Comment (fabriziopandini) [reply api/v1beta1/common_types.go:194]: feel free to improve the comment, or add a note at the end, that explains this case (and why are we blocking on deletion vs blocking on create)

File: internal/controllers/machineset/machineset_preflight.go (hunk 49 above)
Comment (fabriziopandini) [reply internal/controllers/machineset/machineset_preflight.go:42]: ok for preflightCheckErrorMessage.

File: internal/controllers/machineset/machineset_preflight.go (hunk 50 above)
Comment (fabriziopandini) [reply internal/controllers/machineset/machineset_preflight.go:152]: > But isn't it correct that the preflight check failed?

This is correct from an implementation PoV, but I'm not sure this is the best approach from a user PoV.

What about something like "Creation of a new Machine is on hold while CP is provisioning"? This tells the user what he is waiting for, that the operation will restart which are IMO the things he cares about the most. We can also eventually add something like "preflight check ... failed" in between parentheses if we want as additional information, but it should be more an additional info than the core of the message

Comment (sbueringer) [reply internal/controllers/machineset/machineset_preflight.go:152]: Ah I see. Yeah that sounds reasonable.

File: api/v1beta1/common_types.go (hunk 52 above)
[the remark this answers is not in the document]
Comment (ykakarap) [reply api/v1beta1/common_types.go:194]: Updated and adjusted a comment a little bit while preserving the points from the discussion.

File: docs/book/src/tasks/experimental-features/machineset-preflight-checks.md (hunk 44 above)
Comment (ykakarap) [reply docs/book/src/tasks/experimental-features/machineset-preflight-checks.md:12]: Yup, there is a follow-up issue to improve the documentation as discussed here: https://github.com/kubernetes-sigs/cluster-api/pull/8595#discussion_r1200422174

File: internal/controllers/machineset/machineset_preflight.go (hunk 50 above)
Comment (fabriziopandini) [reply internal/controllers/machineset/machineset_preflight.go]: looks great!

**Comment by sbueringer** [comment]
/lgtm

approve pending squash

**Comment by ykakarap** [comment]
Squashed.
