### PR TITLE
🐛 Fix node deletion under managed control planes

### LINKED ISSUE #3631: CAPI won't delete Nodes in "managed" control planes because there are no control plane machines
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

- Create cluster with EKS providers in CAPA
- Create some Machines
- Delete those Machines
- Observe nodes not going away, weird scheduling behaviors, etc

**What did you expect to happen:**

Deleting Machines deletes Nodes too.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I'm fairly certain the check here is the issue:

https://github.com/kubernetes-sigs/cluster-api/blob/feaff31a93174f79929f1264f47f8ad057577454/controllers/machine_controller.go#L379-L396

No control plane Machines in an EKS cluster.

**Environment:**

- Cluster-api version: latest
- Minikube/KIND version: v0.8
- Kubernetes version: (use `kubectl version`): v1.17.9
- OS (e.g. from `/etc/os-release`): Amazon Linux 2

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by dthorsen**
**What this PR does / why we need it**:
This PR allows the Machine controller to drain and delete Nodes when running under managed control planes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3631

### CODE REVIEW

**Comment by dthorsen** [comment]
@vincepri As far as I know node objects for control plane are only used under a kubeadm control plane. EKS and GKE don't list control plane nodes.

File: controllers/machine_controller.go [hunk 1]
```diff
@@ -382,18 +382,22 @@ func (r *MachineReconciler) isDeleteNodeAllowed(ctx context.Context, cluster *cl
...
 	// machine is one of them.
-	switch numControlPlaneMachines := len(util.GetControlPlaneMachines(machines)); {
-	case numControlPlaneMachines == 0:
-		// Do not delete the NodeRef if there are no remaining members of
-		// the control plane.
-		return errNoControlPlaneNodes
-	default:
-		// Otherwise it is okay to delete the NodeRef.
-		return nil
+	if cluster.Spec.ControlPlaneRef.Kind == "KubeadmControlPlane" {
```
Comment (vincepri) [inline controllers/machine_controller.go:388]: We can't assume the `Kind` here is always going to be of type `KubeadmControlPlane`, there might be other infrastructure providers, or single-machine control plane nodes (outside of KCP) that are using this feature. The change here makes it opt in only for KCP clusters, which is a behavioral breaking change.

In alternative, we could have a status field that reports the number of available control plane machines, and the machine controller can use it here. We'd have to make this field fail gracefully, to support the current logic in case the field isn't available or it doesn't exist.

If possible, we should try to keep design conversations on the issue itself, wdyt?

Comment (dthorsen) [reply controllers/machine_controller.go:388]: Happy to have the conversation in the issue if you prefer. I had a thought that a couple lines of code would help start the conversation since I was struggling to understand how this section is being used.

File: controllers/machine_controller.go [hunk 2]
```diff
@@ -376,24 +376,38 @@ func (r *MachineReconciler) isDeleteNodeAllowed(ctx context.Context, cluster *cl
...
-		// Do not delete the NodeRef if there are no remaining members of
-		// the control plane.
-		return errNoControlPlaneNodes
-	default:
-		// Otherwise it is okay to delete the NodeRef.
-		return nil
+	// Check if the ControlPlane is externally managed (AKS, EKS, GKE, etc)
+	// and skip the following section if control plane is externally managed
+	// because there will be no control plane nodes registered
+	if !util.IsExternalManagedControlPlane(controlPlane) {
```
[the remark this answers is not in the document]
Comment (vincepri) [reply controllers/machine_controller.go:388]: If we inline, we can wrap all these checks in an `if` condition that checks if the reference is not nil first

File: controllers/machine_controller.go [hunk 3]
```diff
@@ -376,38 +376,42 @@ func (r *MachineReconciler) isDeleteNodeAllowed(ctx context.Context, cluster *cl
...
+		}
 	}
 
 	// Check if the ControlPlane is externally managed (AKS, EKS, GKE, etc)
 	// and skip the following section if control plane is externally managed
 	// because there will be no control plane nodes registered
-	if !util.IsExternalManagedControlPlane(controlPlane) {
+	if controlPlane != nil && util.IsExternalManagedControlPlane(controlPlane) {
+		return nil
+	}
```
Comment (vincepri) [inline controllers/machine_controller.go:395]: If we move this after line 387, we can just check `util.IsExternalManagedControlPlane(controlPlane)` and return right away

File: controllers/machine_controller.go [hunk 4]
```diff
@@ -376,6 +376,25 @@ func (r *MachineReconciler) isDeleteNodeAllowed(ctx context.Context, cluster *cl
 		return errNilNodeRef
 	}
 
+	var controlPlane *unstructured.Unstructured
+
+	// controlPlaneRef is an optional field in the Cluster so skip the external
+	// managed control plane check if it is nil
+	if cluster.Spec.ControlPlaneRef != nil {
+		var err error
```
Comment (vincepri) [inline controllers/machine_controller.go:384]:
```suggestion
	// controlPlaneRef is an optional field in the Cluster so skip the external
	// managed control plane check if it is nil
	if cluster.Spec.ControlPlaneRef != nil {
```

File: controllers/machine_controller.go [hunk 5]
```diff
@@ -376,6 +376,25 @@ func (r *MachineReconciler) isDeleteNodeAllowed(ctx context.Context, cluster *cl
...
+		controlPlane, err = external.Get(ctx, r.Client, cluster.Spec.ControlPlaneRef, cluster.Spec.ControlPlaneRef.Namespace)
```
Comment (vincepri) [inline controllers/machine_controller.go:385]:
```suggestion
		controlPlane, err := external.Get(ctx, r.Client, cluster.Spec.ControlPlaneRef, cluster.Spec.ControlPlaneRef.Namespace)
```

**Review by vincepri — APPROVED** [review]
/approve
/assign @ncdc

**Comment by dthorsen** [comment]
@vincepri or @ncdc It occurred to me that maybe returning an error here:

https://github.com/kubernetes-sigs/cluster-api/pull/3673/files#diff-7ea69dfdf2e12f7bff0fb38e0c59e0b8R384

may also be a breaking change for non-externally-managed control plane clusters in the case of a 404. I think if this error is a 404 we should simply skip the call to `util.IsExternalManagedControlPlane(controlPlane)` and only return the error if it is any error other than a 404. This will probably avoid some edge cases where things could get stuck unable to drain correctly.

**Comment by vincepri** [comment]
Good catch, we should fallback to the old logic (checking machines) if the error is NotFound

**Comment by dthorsen** [comment]
@vincepri @ncdc  I added the check for a NotFound error.

File: util/util.go [hunk 6]
```diff
@@ -197,6 +197,16 @@ func GetControlPlaneMachinesFromList(machineList *clusterv1.MachineList) (res []
 	return
 }
 
+// IsExternalManagedControlPlane returns a bool indicating whether the control plane referenced
+// in the passed Unstructured resource is an externally managed control plane such as AKS, EKS, GKE, etc.
+func IsExternalManagedControlPlane(controlPlane *unstructured.Unstructured) bool {
+	managed, found, err := unstructured.NestedBool(controlPlane.Object, "status", "externalManagedControlPlane")
```
Comment (fabriziopandini) [inline util/util.go:203]: Should we document somewhere that manage control plane implementation should have this field (might be in  https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html#required-status-fields)

**Review by fabriziopandini — COMMENTED** [review]
lgtm for, only a small thing that can be also addressed in a follow up PR

File: util/util.go (hunk 6 above)
Comment (CecileRobertMichon) [reply util/util.go:203]: +1 this isn't part of the contract currently AFAIK

cc @alexeldeib

Comment (vincepri) [reply util/util.go:203]: +1 updating the documentation, just a note though the field is completely optional and there is a fallback to the current behavior during delete

Comment (dthorsen) [reply util/util.go:203]: Makes sense. What are thoughts on making this new field be an optional part of the contract to avoid a breaking change?

Comment (dthorsen) [reply util/util.go:203]: This is an unusual case in that the field is really required for managed control planes like AKS, EKS, GKE, etc otherwise the Machine controller will suffer this pretty bad bug (instance termination without draining nodes), but not required at all for KubeadmControlPlane. No other optional status fields currently appear to modify functionality and are purely informational. If we make it a new required status field though, I think this would need to wait for a new minor version to be released. I'd like to get the bugfix released sooner rather than later if possible.

Comment (ncdc) [reply util/util.go:203]: I'm 👍 to optional. Please update the control plane architecture doc linked above and add it to the list of optional status fields, assuming everyone else agrees.

Comment (dthorsen) [reply util/util.go:203]: Added a blurb to the docs:
https://github.com/kubernetes-sigs/cluster-api/pull/3673/files#diff-cd671ed1b58bf2cf9d0a69033c9a764dR181-R183

File: docs/book/src/developer/architecture/controllers/control-plane.md [hunk 7]
```diff
@@ -174,10 +174,13 @@ following fields defined:
 
 #### Optional `status` fields
 
-The `status` object **may** define several fields that do not affect functionality if missing:
+The `status` object **may** define several fields:
 
 * `failureReason` - is a string that explains why an error has occurred, if possible.
 * `failureMessage` - is a string that holds the message contained by the error.
+* `externalManagedControlPlane` - is a bool that should be set to true if the Node objects do not
+  exist in the cluster. For example, managed control plane providers for AKS, EKS, GKE, etc, should
```
Comment (CecileRobertMichon) [inline docs/book/src/developer/architecture/controllers/control-plane.md:182]: One small note: the AKS implementation doesn't have a separate control plane provider, see https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/19e80de4a7e92082ca0c5eb672e486801da23766/templates/cluster-template-aks.yaml

Would that still work as a field on the AzureManagedControlPlane https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/995da71c822c201cfa72cf99ae1b96652544e352/exp/api/v1alpha3/azuremanagedcontrolplane_types.go#L79 as part of the Azure infra provider?

Comment (CecileRobertMichon) [reply docs/book/src/developer/architecture/controllers/control-plane.md:182]: (I think it should since we're using controlPlaneRef the same way)

Comment (dthorsen) [reply docs/book/src/developer/architecture/controllers/control-plane.md:182]: @CecileRobertMichon Yes, as long as you reference the `AzureManagedControlPlane` in the cluster's `controlPlaneRef` field you should be able to use the status in your resource as well. Since the check here in CAPI is using the unstructured API, the underlying type is not important. Whatever object is referenced by `controlPlaneRef` just needs to have the status field `externalManagedControlPlane` if there are no control plane `Machine` resources in the cluster.

**Review by CecileRobertMichon — APPROVED** [review]
lgtm
