### PR TITLE
:bug: remove duplicate fix for btrfs/zfs support

### LINKED ISSUE #8317: Error encountered when using CAPD on btrfs: `Error response from daemon: Duplicate mount point: /dev/mapper`
### What steps did you take and what happened?

I'm having difficulties running CAPD/the Tilt local development environment. When I deploy a workload cluster, the `DockerCluster` controller immediately errors with the following message:
```
failed to create load balancer: error creating container \"capi-quickstart-lb\": Error response from daemon: Duplicate mount point: /dev/mapper
```
I first reported this issue in a [Slack thread](https://kubernetes.slack.com/archives/C8TSNPY4T/p1679078614167009) where @killianmuldoon kindly helped to identify that the problem is reproducible with the `btrfs` docker storage driver but not with the `overlay2` docker storage driver.

This suggests to me that the issue is unlikely to be within CAPD itself, but more likely a lower layer like kind or docker. However, this can serve as a helpful tracking issue for the issue that bubbles to the surface when attempting to use CAPD.

### What did you expect to happen?

Expected a workload cluster named `capi-quickstart-cluster` to be created.

### Cluster API version

`v1.3.5`

### Kubernetes version

1.26

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by cannonpalms**
If btrfs or zfs is used CAPD adds the /dev/mapper mount twice. This PR ensures we only do it once.

xref to where kind implements this:  https://github.com/kubernetes-sigs/kind/pull/1464

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8317

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/hold
I don't have a way to test this, but there is something I struggle to understand

The code in kind adds a dev mapper for all the containers started by kind; the code in CAPD does the same for all the containers started by CAPD.

The two code paths do not overlap, and they must be kept ~in sync because we use the same base images (which is the only thing shared between kind and CAPD at this point).

Given that, if the mount is required for the containers started by kind, we should not drop adding the same mount for the containers started by CAPD... am I missing something?

**Comment by fabriziopandini** [comment]
Also, please add Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8317 to the PR body

**Comment by cannonpalms** [comment]
Hmm, I see what you mean. I may have fixed the duplicate mount point issue, but re-broke the original problem. I wrote this on an airplane, so let me take a deeper look tomorrow. I appreciate the feedback.

**Comment by killianmuldoon** [comment]
/ok-to-test

I should be able to try to test this on my setup  - will report back if I figure out what the interaction is here.

**Comment by killianmuldoon** [comment]
The issue here isn't that this overlaps with Kind - the update in https://github.com/kubernetes-sigs/cluster-api/pull/8157 added a second code path which mounts `/dev/mapper`. If we remove one it should work.

File: test/infrastructure/container/docker.go [hunk 1]
```diff
@@ -430,15 +424,6 @@ func (d *dockerRuntime) RunContainer(ctx context.Context, runConfig *RunContaine
...
 	containerConfig.Env = envVars
 
-	// handle Docker on Btrfs or ZFS
-	// https://github.com/kubernetes-sigs/kind/issues/1416#issuecomment-606514724
-	if d.mountDevMapper(info) {
-		runConfig.Mounts = append(runConfig.Mounts, Mount{
-			Source: "/dev/mapper",
-			Target: "/dev/mapper",
-		})
-	}
```
Comment (killianmuldoon) [inline test/infrastructure/container/docker.go:440]: @cannonpalms could you remove this block and the associated code (`mountDevMapper`). Removing this alone makes this work for me when running btrfs.

**Comment by killianmuldoon** [comment]
@cannonpalms do you think you'll have time to come back to this?

File: test/infrastructure/container/docker.go (hunk 1 above)
Comment (cannonpalms) [reply test/infrastructure/container/docker.go:440]: I didn't understand clearly what you meant here, so I took it to mean that you were asking me to remove the now-unused `mountDevMapper(...)` and `needsDevMapper(...)` functions, _not_ that this highlighted block alone was the only necessary change & I should restore the previous removal of the block consuming `needsDevMapper(...)`.

Is that correct?

**Comment by guettli** [comment]
@cannonpalms I don't have a btrfs system, so can't test. But we are doing a workshop, and I have concerns that some partitipants have btrfs. Could you check the above PR and tell us if it works for you?

**Comment by cannonpalms** [comment]
> @cannonpalms I don't have a btrfs system, so can't test. But we are doing a workshop, and I have concerns that some partitipants have btrfs. Could you check the above PR and tell us if it works for you?

Travelling right now, but I can tell you that it worked for me at the time of last comment, and the workaround is to edit your docker config and change the storage driver to something like `overlay2`.

**Comment by killianmuldoon** [comment]
I think I'd prefer to verify independently - I should be able to do so in the next couple of days though.

File: test/infrastructure/container/docker.go [hunk 2]
```diff
@@ -412,12 +408,6 @@ func (d *dockerRuntime) RunContainer(ctx context.Context, runConfig *RunContaine
 		return errors.Wrapf(err, "unable to get Docker engine info, failed to create container %q", runConfig.Name)
 	}
 
-	// mount /dev/mapper if docker storage driver if Btrfs or ZFS
-	// https://github.com/kubernetes-sigs/kind/pull/1464
-	if d.needsDevMapper(info) {
-		hostConfig.Binds = append(hostConfig.Binds, "/dev/mapper:/dev/mapper:ro")
-	}
-
```
Comment (killianmuldoon) [inline test/infrastructure/container/docker.go:420]: Let's just remove these lines. I believe that should be sufficient to fix this bug. It is on my Machine. Removing the rest of the functionality breaks Kubelet at least on my Fedora setup running `btrfs`

**Review by killianmuldoon — COMMENTED** [review]
I'm testing with `btrfs`. I tried running this locally and it got past the issue on the load balancer but failed to bring up any Kubernetes nodes. 

AFAIU we need to roll back most of the changes in this PR. The issue is that we try to mount the dev/mapper twice. We should remove the slightly less complete version of that in lines 415-419. I believe that change is sufficient to fix this issue completely.

File: test/infrastructure/container/docker.go (hunk 2 above)
Comment (cannonpalms) [reply test/infrastructure/container/docker.go:420]: Just to clarify, when you say "remove", you mean to remove them from _this diff_, correct? In other words, don't remove these lines at all, as this PR already does?

**Comment by fabriziopandini** [comment]
@cannonpalms it would be great if you could answer to @killianmuldoon comment
otherwise, we can also move on letting the bot to squash
@sbueringer @chrischdi opinions?

**Comment by sbueringer** [comment]
To be honest. I have no idea how that upstream code in kind influences us and thus means that we don't have to do it ourselves.

At which time is the code in provision.go from kind executed in CAPD?

**Comment by cannonpalms** [comment]
Thank you for the re-ping. I missed Killian's original comment over the holidays and hadn't had a chance to get back to it.

I'll go ahead and squash while the discussion continues.

**Comment by chrischdi** [comment]
> To be honest. I have no idea how that upstream code in kind influences us and thus means that we don't have to do it ourselves.
> 
> At which time is the code in provision.go from kind executed in CAPD?
> 
> As far as I can tell we don't run any kind code when CAPD creates a new Docker container. We also don't run any kind binary when we simulate cloud-init with docker exec.
> 
> The code in provision.go seems to be run as part of the kind cluster create command which we don't use in CAPD.
> 
> I would like to wait for an explanation how this all makes sense :)

This PR totally makes sense and it works on btrfs (just tested it).

On main we currently add the `/dev/mapper` twice to the `hostConfig.Binds` struct (when using btrfs / `d.mountDevMapper(info)` returns true):

1.: directly adding it to `hostConfig.Binds`

https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/container/docker.go#L430-L434

2.: via adding it to `runConfig.Mounts` and calling `configureVolumes(...)` (inside configureVolumes we add it then again to `hostConfig.Binds`

https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/container/docker.go#L450-L457

Its not possible to have the same mountpoint defined twice (also one is read only, the other not).

/lgtm

**Comment by sbueringer** [comment]
So it has nothing to do with that kind made the change (https://github.com/kubernetes-sigs/kind/pull/1464) it's just that our code has a bug?

**Comment by chrischdi** [comment]
> So it has nothing to do with that kind made the change ([kubernetes-sigs/kind#1464](https://github.com/kubernetes-sigs/kind/pull/1464)) it's just that our code has a bug?

Yes and no, https://github.com/kubernetes-sigs/kind/pull/1464 fixed an issue.

In CAPD we already had this fix already, but twice. Having it twice breaks it again :-)

**Comment by sbueringer** [comment]
Makes sense. The PR description of this PR just lead me down a very wrong path

> Support for btrfs/zfs was upstreamed to kind in https://github.com/kubernetes-sigs/kind/pull/1464, removing the need for us to hack support in ourselves.

**Comment by sbueringer** [comment]
@chrischdi Thx for taking the time to clear this up and test it. I adjusted the PR description accordingly

/lgtm
/approve

**Comment by sbueringer** [comment]
@cannonpalms Can you please rebase?

**Comment by cannonpalms** [comment]
@sbueringer Done.

**Review by chrischdi — COMMENTED** [review]
/lgtm

pending ci

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve
/hold cancel
