### PR TITLE
🌱 [capd] Ensure Loadbalancer IP is not empty

### LINKED ISSUE #4396: [capd] Reconciliation of DockerClusters fails when there is a stopped ha-proxy container.
The root cause here is that I had a stopped ha proxy container that was preventing a new one from being created.
During creation of the loadbalancer helper we check if the ha-proxy container exists which is where we pick up stopped containers https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/docker/util.go#L108

cc @fabriziopandini going to create an issue from this comment.

_Originally posted by @ashish-amarnath in https://github.com/kubernetes-sigs/cluster-api/pull/4385#discussion_r603557227_

### PR DESCRIPTION
**Pull request by ashish-amarnath**
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

**What this PR does / why we need it**:

DockerCluster reconciliation tries to lookup IP of the loadbalancer container. In the process, it looks at all containers in the system by running `docker ps -a ` filtering using the name of the cluster. This picks up even those containers that were stopped. The stopped containers will not have any IP addresses associated with them. This results in an error in the DockerCluster controller like

```
[manager] E0329 14:51:58.051663      10 controller.go:302] controller-runtime/manager/controller/dockercluster "msg"="Reconciler error" "error"="DockerCluster.infrastructure.cluster.x-k8s.io \"my-cluster\" is invalid: spec.controlPlaneEndpoint.host: Required value" "name"="my-cluster" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="DockerCluster" 
```

This change adds a filter to the `docker ps -a` command to pick up only those containers that are running, and also returns an error if the LB has no IP addresses associated with it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4396

### CODE REVIEW

**Comment by ashish-amarnath** [comment]
not sure how to kick the netlify checks

File: test/infrastructure/docker/docker/types/node.go [hunk 1]
```diff
@@ -83,6 +83,9 @@ func (n *Node) IP(ctx context.Context) (ipv4 string, ipv6 string, err error) {
 	if len(ips) != 2 {
 		return "", "", errors.Errorf("container addresses should have 2 values, got %d values", len(ips))
 	}
+	if ips[0] == "" && ips[1] == "" {
```
Comment (MarcelMue) [inline test/infrastructure/docker/docker/types/node.go:86]: This change seems unrelated to the LB container change to me. Am I missing something obvious?

Comment (sbueringer) [reply test/infrastructure/docker/docker/types/node.go:86]: In case a change here was intended. Do we want to fail if:
* both are empty
* one of them are empty

Comment (ashish-amarnath) [reply test/infrastructure/docker/docker/types/node.go:86]: @MarcelMue This change is related to the LB container.
During DockerCluster reconciliation:
1. In the [reconcileNormal](https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/controllers/dockercluster_controller.go#L144) method we try to look up the IP of the LB of the previously provisioned LB by calling the [LoadBalancer.IP](https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/docker/loadbalancer.go#L135)
2. [LoadBalancer.IP](https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/docker/loadbalancer.go#L135) in turn calls the [Node.IP](https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/docker/types/node.go#L69) function by calling [s.container.IP()](https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/docker/loadbalancer.go#L136)

Comment (ashish-amarnath) [reply test/infrastructure/docker/docker/types/node.go:86]: @sbueringer the IPs returned here are IPv4 (ips[0]) and IPv6(ips[1] addresses. Till we decide that only one of those is what we will support, returning an error if both are empty seems reasonable. WDYT?

Comment (ashish-amarnath) [reply test/infrastructure/docker/docker/types/node.go:86]: On thinking about this further, returning this error from the `Node.IP()` may not be the correct thing. IMO, this check should be performed in the `LoadBalancer.IP` function.

Comment (sbueringer) [reply test/infrastructure/docker/docker/types/node.go]: @ashish-amarnath Sounds okay to me. I don't have the necessary context to know if we expect both of them to be set or just one of them.

**Comment by fabriziopandini** [comment]
@ashish-amarnath changes lgtm to me but I have two concerns:
- What is the use case that lead to having a stopped load balancer container, this should never happen
- What is the expected behaviour in case a stopped load balancer container; I understand that we are not considering it as an existing load balancer, but if I'm not wrong, by ignoring it we ends up in trying to create a new one and this will fail because a container with the same name already exists...

**Comment by ashish-amarnath** [comment]
@fabriziopandini 
I am not entirely sure how I ended up with a stopped LB container for my cluster. But the error message I saw in the controller when this happened wasn't indicative of the reason. Specifically, this is the error I observed:
```
[manager] E0329 14:51:58.051663      10 controller.go:302] controller-runtime/manager/controller/dockercluster "msg"="Reconciler error" "error"="DockerCluster.infrastructure.cluster.x-k8s.io \"my-cluster\" is invalid: spec.controlPlaneEndpoint.host: Required value" "name"="my-cluster" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="DockerCluster" 
```

Your concerns are valid. First, I agree that this should not happen commonly. But in case this happens, at the very least the needs to be more meaningful than indicating that there was something wrong with the spec that was applied and accepted by the validation. Second, if this were a real provider, then in the case of the LB being stopped, killed, or deleted, the expectation would be that a new one will be spun up in its place as part of reconciling the infrastructure that makes up the cluster. That said, I also understand that this is not a real provider for production.
About reconciliation of the LB failing bc a container of the same name exists, I think that should be remediated too. This can be done by removing stopped containers with the same name. Happy to address that in this PR if you agree 🙂
WDYT?

**Comment by fabriziopandini** [comment]
TBH, I'm a little bit concerned that automatically remediation of stopped containers would hide the root cause of the problem and in the end introduce more instability to the system due to the load balancer going away and being recreated in an unpredictable way (also in a real production system, you can't really trust a load balancer that suddently goes away without reasons).

However I agree we should report a better error message, but this should be done without ignoring stopped containers.

**Comment by sbueringer** [comment]
I agree with @fabriziopandini . Let's try to first improve error reporting / logging. If we then know the root cause, we can decide if an automatic remediation is the right way to resolve it.

**Comment by ashish-amarnath** [comment]
@fabriziopandini Considering that this is not a real provider but one to catch problems, I agree that this change will be papering over real issues. I will remove the filtering change and keep the error check which could give us the meaningful error message that we are looking for.

File: test/infrastructure/docker/docker/loadbalancer.go [hunk 2]
```diff
@@ -45,6 +45,9 @@ func NewLoadBalancer(name string) (*LoadBalancer, error) {
 		return nil, errors.New("name is required when creating a docker.LoadBalancer")
 	}
 
+	// look for the container that is hosting the loadbalancer for the cluster.
+	// filter based on the lablel and the roles regardless of whether or not it is running.
```
Comment (sbueringer) [inline test/infrastructure/docker/docker/loadbalancer.go:49]:
```suggestion
	// filter based on the labels and the roles regardless of whether or not it is running.
```

File: test/infrastructure/docker/docker/loadbalancer.go [hunk 3]
```diff
@@ -137,6 +140,10 @@ func (s *LoadBalancer) IP(ctx context.Context) (string, error) {
 	if err != nil {
 		return "", errors.WithStack(err)
 	}
+	if lbip4 == "" {
+		// if there is a load balancer container with the same name exists but is stopped, it may not have IP address associated with it.
+		return "", errors.Errorf("LoadBalancer IP cannot be empty: container %s does not have an associated IP address", s.containerName())
```
Comment (sbueringer) [inline test/infrastructure/docker/docker/loadbalancer.go:145]:
```suggestion
		// if there exists a load balancer container with the same name but is stopped, it may not have an IP address associated with it.
		return "", errors.Errorf("load balancer IP cannot be empty: container %s does not have an associated IP address", s.containerName())
```
nit: golang errors usually start with lower case

Comment (sbueringer) [reply test/infrastructure/docker/docker/loadbalancer.go]: @ashish-amarnath sorry for the nitpicking the space between `load` and `balancer` was intended for consistency as we're using this variant in l.99

**Comment by ashish-amarnath** [comment]
Realized we are not categorizing this as a bug
