### PR TITLE
Check if machineDeployment queue exists before using it

### LINKED ISSUE #501: machineDeployment controller races+panics on startup when a machineSet exists
Currently, the `machineDeployment` controller sometimes panics on startup when a `machineSet` already exists:

```
ERROR: logging before flag.Parse: I0913 19:43:11.940900       1 controller.go:83] Waiting for caches to sync for machine deployment controller
ERROR: logging before flag.Parse: E0913 19:43:12.533934       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:505
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go:372
/go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go:194
/go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go:66
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache/controller.go:195
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache/shared_informer.go:547
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache/shared_informer.go:389
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache/shared_informer.go:389
/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1268cd6]

goroutine 82 [running]:
sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x13ede20, 0x212c150)
	/usr/local/go/src/runtime/panic.go:505 +0x229
sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*MachineDeploymentControllerImpl).enqueue(0xc4204155e0, 0xc420446000)
	/go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go:372 +0x146
sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*MachineDeploymentControllerImpl).addMachineSet(0xc4204155e0, 0x15b0ea0, 0xc42005ec00)
	/go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go:194 +0x1aa
sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*MachineDeploymentControllerImpl).(sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.addMachineSet)-fm(0x15b0ea0, 0xc42005ec00)
	/go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go:66 +0x3e
sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc42036d390, 0xc42036d3a0, 0xc42036d3b0, 0x15b0ea0, 0xc42005ec00)
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc4202ee180)
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache/shared_informer.go:547 +0x247
sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache.(*processorListener).(sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/client-go/tools/cache/shared_informer.go:389 +0x2a
sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc42015fe20, 0xc42036dc60)
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/src/sigs.k8s.io/cluster-api/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

If I read the code correctly, this is caused by the `machineDeployment` controller adding an [EventHandler for Adds of machineSets in its `Init`](https://github.com/kubernetes-sigs/cluster-api/blob/ba672fe598bc56a7fd155cf959ca6ce6d1882cb8/pkg/controller/machinedeployment/controller.go#L66) which subsequently causes all `machineDeployments` that own a `machineSet` to get enqeued - However the queue gets created after the `Init` is called: https://github.com/kubernetes-sigs/cluster-api/blob/ba672fe598bc56a7fd155cf959ca6ce6d1882cb8/pkg/controller/machinedeployment/zz_generated.api.register.go#L59-L71

So if the initial `List` of `machineSets` is fast enough, this results in a NPE.

### PR DESCRIPTION
**Pull request by alvaroaleman**
Resolves #501

**What this PR does / why we need it**:

Avoids NPEs when starting the machineDeployment controller in a cluster that has pre-existing machineSets

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #501 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/machinedeployment/controller.go [hunk 1]
```diff
@@ -368,6 +371,12 @@ func (c *MachineDeploymentControllerImpl) enqueue(d *v1alpha1.MachineDeployment)
 		utilruntime.HandleError(fmt.Errorf("Couldn't get key for object %#v: %v", d, err))
 		return
 	}
+	if _, queueExists := c.informers.WorkerQueues["MachineDeployment"]; !queueExists {
+		glog.V(2).Infof("MachineDeployment queue does not exist, requing after %v", requeueAfterWhenQueueAbsent)
+		time.Sleep(requeueAfterWhenQueueAbsent)
+		c.enqueue(d)
```
Comment (Lion-Wei) [inline pkg/controller/machinedeployment/controller.go]: Shouldn't here have an error out after multiple attempts or timeout?

Comment (alvaroaleman) [reply pkg/controller/machinedeployment/controller.go]: The only case where this happens is during startup of the controller because init is called before the workqeue is created:

https://github.com/kubernetes-sigs/cluster-api/blob/5b128c0f9ab134087d1331be8176099201055a36/pkg/controller/machinedeployment/zz_generated.api.register.go#L59-L71

The init of this controller however registers already eventHandlers for machineSets which will subsequently try to put their owning machineDeployments in the not yet existing qeue: https://github.com/kubernetes-sigs/cluster-api/blob/5b128c0f9ab134087d1331be8176099201055a36/pkg/controller/machinedeployment/controller.go#L65-L69

Just creating the qeue before calling Init is unfortunatelly not possible because all of that happens in generated code.

Since this should only happen during the startup in just a very small timeframe I think its okay like this. WDYT?

Comment (roberthbailey) [reply pkg/controller/machinedeployment/controller.go]: @pwittrock - is this something that gets fixed with the kubebuilder change?

Comment (alvaroaleman) [reply pkg/controller/machinedeployment/controller.go]: @roberthbailey Are you fine with merging this to have the `machineDeployment` controller working again?

Comment (roberthbailey) [reply pkg/controller/machinedeployment/controller.go]: Yes, sorry for the delay.
