### PR TITLE
🌱 tilt: ensure in-tree providers always use start.sh to allow restarts

### LINKED ISSUE #10810: build failing in tilt development
### What steps did you take and what happened?

building off of main commit `54c8e46eeb4861746d6fadd9847bdea913797231` ran `make tilt-up`

binary seems to update without an issue:
```sh
1 File Changed: [exp/internal/controllers/machinepool_controller_phases.go]
Running cmd: cd .;CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build  -gcflags '' -ldflags '-extldflags "-static"' -o .tiltbuild/bin/manager main.go
```

but then in capi_controller it shows Update error:

```sh
[CMD 1/1] sh -c sh /restart.sh
/restart.sh: 25: kill: Illegal number: 
  → Failed to update container capi-controller-manager-56c9f5fcf4-8z8w7/manager: executing on container 2ec2fa498b: command "sh /restart.sh" failed with exit code: 2
Build Failed: executing on container 2ec2fa498b: command "sh /restart.sh" failed with exit code: 2
```

slack discussion here for details: https://kubernetes.slack.com/archives/C8TSNPY4T/p1714205106891389

seems like this PR introduced the issue: https://github.com/kubernetes-sigs/cluster-api/pull/10244/files

### What did you expect to happen?

deployment should restart without an issue using tilt development tools

### Cluster API version

building from `main`

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

The in-tree providers have hardcoded their provider options in `Tiltbuild`. Therefor the values we have in `tilt-prepare` do not reflect the real ones.

Since implementing #10244, when using a `tilt-settings.yaml` file without debug configuration for the in-tree providers, tilt-prepare won't adjust the cmd to use `start.sh` and because of that restarts via tilt did not work anymore.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10810

/area devtools

### CODE REVIEW

File: hack/tools/internal/tilt-prepare/main.go [hunk 1]
```diff
@@ -137,6 +143,9 @@ type tiltProviderConfig struct {
 	ApplyProviderYaml *bool    `json:"apply_provider_yaml,omitempty"`
 	KustomizeFolder   *string  `json:"kustomize_folder,omitempty"`
 	KustomizeOptions  []string `json:"kustomize_options,omitempty"`
+
+	// hardCodedProvider is used for providers hardc-oded in the Tiltfile to always set cmd for them to start.sh to allow restarts.
```
Comment (sbueringer) [inline hack/tools/internal/tilt-prepare/main.go:147]:
```suggestion
	// hardCodedProvider is used for providers hardcoded in the Tiltfile to always set cmd for them to start.sh to allow restarts.
```

**Comment by sbueringer** [comment]
Thx for fixing this!

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by chrischdi** [comment]
/hold cancel

Needs another lgtm, fixed the typo

**Comment by cahillsf** [comment]
Nice ty!

**Comment by sbueringer** [comment]
@cahillsf thx for reporting!
