### PR TITLE
🌱 gather more Docker and containerd data/logs in ci-e2e.sh

### LINKED ISSUE #4405: Multiple e2e tests are flaky because of error container is not running
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

According to [testgrid](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main&width=20&sort-by-failures=&exclude-non-failed-tests=48) `capi-e2e.When following the Cluster API quick-start [PR-Blocking] Should create a workload cluster` and a few others are failing from time to time.

I looked at the last two occurrences in the capi-quickstart test. In both cases a machine did not come up because `mkdir -p /etc/kubernetes/pki` was failing because the respective container was not running. It was retried for a while but the container didn't come up. I tried to find any other logs but couldn't find anything. Logs from the controllers aggregated and sorted for the affected node of this test: https://gist.github.com/sbueringer/e007c989c158d66dd6d3078f8c904f30 ([ProwJob](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1376713791990927360))

I think right now we don't have the necessary data/logs to find out why this happens. I would propose to gather the logs of the Docker service which is used in those tests (the dind used in the ProwJob). Maybe there's something interesting there. Are there any other Docker / kind / ... logs which we could retrieve?

What I found in the kubekins image we're using:
* /var/log/docker.log

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I assume the following test failures are related:
* same container not running logs in the capd manager: (I didn't look at all logs, but they all file basically in the same line of code in the tests)
  * capi-e2e: When testing K8S conformance [Conformance] Should create a workload cluster and run kubetest
    * https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1376575756603232256
    * https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1376468293379952640
  * capi-e2e: When testing KCP upgrade Should successfully upgrade Kubernetes, DNS, kube-proxy, and etcd in a HA cluster
    * https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1376652387720105984
  * capi-e2e: When testing KCP upgrade Should successfully upgrade Kubernetes, DNS, kube-proxy, and etcd in a HA cluster
    * https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1376529700758753280

So tl;dr apart from the MachineRemediation most of our other flaky tests are probably caused by this issue. They are usually failing in the following lines of code:
* controlplane_helpers.go:109 https://github.com/kubernetes-sigs/cluster-api/blob/7478817225e0a75acb6e14fc7b438231578073d2/test/framework/controlplane_helpers.go#L109
* controlplane_helpers.go:146 https://github.com/kubernetes-sigs/cluster-api/blob/7478817225e0a75acb6e14fc7b438231578073d2/test/framework/controlplane_helpers.go#L146
* machinedeployment_helper:120: https://github.com/kubernetes-sigs/cluster-api/blob/7478817225e0a75acb6e14fc7b438231578073d2/test/framework/machinedeployment_helpers.go#L120
* machinepool_helpers.go:85: https://github.com/kubernetes-sigs/cluster-api/blob/7478817225e0a75acb6e14fc7b438231578073d2/test/framework/machinepool_helpers.go#L85

Even if they not all have the same root cause. Fixing this error should fix most of them.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

Gathers more logs and data from Docker and containerd, to be able to fix #4405 mid-term.

Maybe a bit hacky, but I suppose it works, let's see. Should provide a lot more information. The most promising new logs are:
* containerd event logs: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4414/pull-cluster-api-e2e-main/1377189073852043264/artifacts/local/containerd-events.txt
* docker event logs: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4414/pull-cluster-api-e2e-main/1377189073852043264/artifacts/local/docker-events.txt
* docker / containerd logs: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4414/pull-cluster-api-e2e-main/1377189073852043264/artifacts/local/docker.log

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Prereq to fix #4405

### CODE REVIEW

File: scripts/ci-e2e.sh [hunk 1]
```diff
@@ -71,6 +71,38 @@ export ARTIFACTS="${ARTIFACTS:-${REPO_ROOT}/_artifacts}"
 export SKIP_RESOURCE_CLEANUP=false
 export USE_EXISTING_CLUSTER=false
 
+# Configure local output
+ARTIFACTS_LOCAL="${ARTIFACTS}/local"
```
Comment (fabriziopandini) [inline scripts/ci-e2e.sh:75]: nit
s/local/host

Comment (sbueringer) [reply scripts/ci-e2e.sh]: Done

Comment (sbueringer) [reply scripts/ci-e2e.sh]: That's what it looked like, I wasn't sure that was intended. 

@fabriziopandini which one did you mean, localhost or host?
(I'll just change it, I don't really favor one over the other)

Comment (ashish-amarnath) [reply scripts/ci-e2e.sh]: `s/string1/string2` usually means search for `string1` and replace it with `string2`.

Comment (sbueringer) [reply scripts/ci-e2e.sh]: Yeah I know, thx ;). `host` just didn't make sense to me :)

Comment (fabriziopandini) [reply scripts/ci-e2e.sh]: @sbueringer sorry for being criptic. I was looking at 
Screenshot 2021-03-31 at 17 45 26
And in that context I found `local` a little bit confusing.
So the fist thing that came to my mind was "this is the host where the test runs", so I suggested `host`...
But this is really a nit, feel free to leave as it is (`localhost` is fine) or revert to `local`

Comment (sbueringer) [reply scripts/ci-e2e.sh]: Yup local wasn't good. Then I'll keep localhost

Comment (vincepri) [reply scripts/ci-e2e.sh]: What does local, localhost, or host mean in this context?

Comment (sbueringer) [reply scripts/ci-e2e.sh]: The idea is to get logs from the host which is running the `./scripts/ci-e2e.sh` shell script. 

In CI this is the Pod of the ProwJob, but of course I can also run this script on my laptop.

The idea was to name the folder in a way so that it makes clear that these are local logs.

Comment (CecileRobertMichon) [reply scripts/ci-e2e.sh]: Can't really think of a better name, but one way to make it super clear is to add a log statement to a readme file that explains what this folder is, ie.:

```
echo "This folder contains logs from the host where the test ran" "${ARTIFACTS_LOCAL}/README" || true
```

(or something like it)

Comment (sbueringer) [reply scripts/ci-e2e.sh]: Great idea, added.

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-full-main
(error was unrelated)

**Comment by fabriziopandini** [comment]
@sbueringer do you want to go on and merge this or do you prefer to keep it open while we still investigating flakes?

**Comment by sbueringer** [comment]
> @sbueringer do you want to go on and merge this or do you prefer to keep it open while we still investigating flakes?

@fabriziopandini  I would merge this one and trial-and-error on #4416
