### PR TITLE
🐛 Fix the observedGeneration update

### LINKED ISSUE #4341: KCP observedGeneration version does not get updated after upgrade
**What steps did you take and what happened:**

When deploying CAPI/CAPV the KubeadmControlPlane `metadata.generation` gets updated to new version but the `status.observedGeneration` does not. It stays on version 1..

This means it cannot be compatible with something like kstatus, which relies on the conditions status but also to make sure these are in synch, see docs (https://pkg.go.dev/sigs.k8s.io/kustomize/kstatus#readme-concepts)[https://pkg.go.dev/sigs.k8s.io/kustomize/kstatus#readme-concepts]

**What did you expect to happen:**

Once the KubeadmControlPlane resources have been updated/reconciled, the `status.observedGeneration` should be updated and match the `metadata.generation`.

**Anything else you would like to add:**

Having this work in this way would allow us to control the order of deployments of controlplane nodes and worker nodes, specifically when doing upgrades using tools like kstatus/kustomize/flux.

**Environment:**

- Cluster-api version: v1alpha3
- CAPV: v1alpha3
- Kubernetes version: 1.20.4
- OS: Ubuntu 18.04

/kind bug
/area control plane

### PR DESCRIPTION
**Pull request by davideimola**
**What this PR does / why we need it**:
Fixes a bug where the observedGenaration is not update correctly when deploying a new generation of KubeadmControlPlane.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4341

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/ok-to-test

**Comment by vincepri** [comment]
@enxebre That should be the case with the change in this PR. `updateStatus` calls `patchKubeadmControlPlane`, which then patches the status.observedGeneration field as well.

**Review by vincepri — APPROVED** [review]
/lgtm

**Comment by enxebre** [comment]
>@enxebre That should be the case with the change in this PR. updateStatus calls patchKubeadmControlPlane, which then patches the status.observedGeneration field as well.

@vincepri mm as far as I can see that's not the case. `updateStatus` does not call patchKubeadmControlPlane and can be called independently
https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/controllers/controller.go#L170-L181
https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/controllers/status.go#L34

am I missing anything?

**Comment by davideimola** [comment]
@vincepri I think I have to increase the timeout time on the test to pass it. I do not know how much time can take to reconcile. What do you think?
I have some issues while trying to run the tests locally (gcc-5 and other stuff), do you know if it is possible to run it in Docker?

Another thing, I have made a manual test to prove the fix works. I have created a cluster with CAPI and KCP. I have tried to update the number of replicas and I have verified the observedGeneration matches the generation after the reconcile.

**Comment by enxebre** [comment]
>@enxebre Sorry for the confusion, updateStatus doesn't actually call the patch directly, but it's called in the defer right after calling updateStatus

yup, still since we have a `updateStatus` func I'd expect it to be responsible for ensuring `observedGenaration` independently from the defer structure, similar to what we do in machineSet controller. I'm good either way, just a nit :)

**Comment by fabriziopandini** [comment]
The test is failing because we exits from reconcile before calling patch.
To get this fixed it is required to patch cluster.status.InfrastructureReady; with that in place you can test ObservedGeneration being upgraded while adding finalisers or by defer patch

File: controlplane/kubeadm/controllers/controller_test.go [hunk 1]
```diff
@@ -83,6 +83,55 @@ var _ = Describe("Kubeadm Control Plane Controller", func() {
 				return err
 			}, 10*time.Second).Should(HaveOccurred())
 		})
+
+		It("should update the observed generation after a reconcile", func(t *testing.T) {
```
Comment (detiber) [inline controlplane/kubeadm/controllers/controller_test.go:87]: I don't think this should be using `t *testing.T` here:

```suggestion
		It("should update the observed generation after a reconcile", func() {
```

Below, should be using the global `Expect` rather than the `NewWithT`

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Comment by davideimola** [comment]
Ok, it was a flakyness in the test, now it might be working fine.
