### PR TITLE
🏃 Update kubeadm config on upgrade

### LINKED ISSUE #2427: [kubeadm control plane] something is weird when upgrading from 1.16 to 1.17
Using #2334 as a base, when I upgrade from 1.16 to 1.17 there is something going on in either: the load balancer is not behaving properly and causing the kubelet to fail or the kubelet is failing for some other reason. Right now I have a few error messages about CSI that's putting the kubelet in a crash loop. I need to debug further to pinpoint what's going on. But the general code in #2334 is one-by-one replacing my nodes and having them join successfully.

/kind bug

### LINKED ISSUE #2429: Refactor KubeadmControlPlane implementation for updating the kubeadm config map
/kind feature

Copied from https://github.com/kubernetes-sigs/cluster-api/pull/2334#discussion_r381360199

An alternative to using a closure here would be to extract the configmap operations into their own type. 

The resulting layers become: 
 * The `cluster` object is responsible for interacting with the apiserver (Read, Update)
 * A new struct has methods for modifications to a kubeadmconfigmap. (New is basically the `extractKubeadmConfigMapClusterStatus`, then `removeNodeFromKubeadmConfigMapClusterStatusAPIEndpoints` is a method on the type.

This keeps the layers cleanly separated. It's very similar to what you've got here but instead of a generic update function we define the specific actions we need without abstracting too early.

If the above was not clear, this is the pseudocode of what was described.
```
configMap := client.Get(configmap, ... )
kcfg := NewKubeadmConfig(configMap)
kcfg.RemoveAPIEndpoint(machine.status.noderef.name)
client.Update(kcfg)
```

Some of the benefits of this approach are that the functions acting on the kubeadm config are attached to a struct which implies context. Thus, we can avoid long names like `removeNodeFromKubeadmConfigMapClusterStatusAPIEndpoints`. The layers between each component are clean and the kubeadmconfig object need not know anything except what a kubeadmconfig is and how it's structured. It can be easily tested in isolation. The code becomes imperative without relying on descriptive function names.

### LINKED ISSUE #2448: [kubeadm control plane] Support upgrading to v1.17
The upgrade code is missing the modification of KubernetesVersion as well as the kublet config on the workload clusters before upgrading.

/kind feature
/lifecycle active
/milestone v0.3.0
/priority important-soon

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
This PR updates the kubernetes version found in the kubeadm configuration config map as well as refactors some of the kubelet upgrading to keep it outside of the reconciler

This PR intentionally includes code that is easily refactored. I do not intend to consolidate repeated code in this PR and will save that for an exercise for later.

To run a test locally with this PR, first check it out, then run

```
export FOCUS='Basic|Full` # I know, I know...but it's fine for now
make test-capd-e2e-images
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2448 
Fixes #2427 
Fixes #2429 

This is the upgraded cluster. The machine deployment was not upgraded as it's not managed buy the kubeadm control plane
```
chuckh-a02:cluster-api cha$ k get nodes
NAME                                STATUS     ROLES    AGE     VERSION
test-0-test-0-9v4p6                 NotReady   master   10m     v1.17.2
test-0-test-0-k6x4q                 NotReady   master   12m     v1.17.2
test-0-test-0-md-5c6f99b8bf-7qvsc   NotReady   <none>   17m     v1.16.3
test-0-test-0-xq7nw                 NotReady   master   8m28s   v1.17.2
```

This is a random log from one of the kubelets. It is expected since there is no CNI installed (this set of logs means it's working).
```
Feb 26 17:09:48 test-0-test-0-xq7nw kubelet[459]: E0226 17:09:48.244762     459 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Feb 26 17:09:53 test-0-test-0-xq7nw kubelet[459]: E0226 17:09:53.246961     459 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Feb 26 17:09:58 test-0-test-0-xq7nw kubelet[459]: E0226 17:09:58.248183     459 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Feb 26 17:10:03 test-0-test-0-xq7nw kubelet[459]: E0226 17:10:03.251303     459 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Feb 26 17:10:08 test-0-test-0-xq7nw kubelet[459]: E0226 17:10:08.252986     459 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Feb 26 17:10:13 test-0-test-0-xq7nw kubelet[459]: E0226 17:10:13.255484     459 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Feb 26 17:10:18 test-0-test-0-xq7nw kubelet[459]: E0226 17:10:18.257761     459 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Feb 26 17:10:23 test-0-test-0-xq7nw kubelet[459]: E0226 17:10:23.258997     459 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Feb 26 17:10:28 test-0-test-0-xq7nw kubelet[459]: E0226 17:10:28.261498     459 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
```

/cc @dlipovetsky @randomvariable 
/assign @detiber

### CODE REVIEW

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go [hunk 1]
```diff
@@ -737,8 +720,7 @@ func (r *KubeadmControlPlaneReconciler) cleanupFromGeneration(ctx context.Contex
 }
 
 func (r *KubeadmControlPlaneReconciler) generateKubeadmConfig(ctx context.Context, kcp *controlplanev1.KubeadmControlPlane, cluster *clusterv1.Cluster, spec *bootstrapv1.KubeadmConfigSpec) (*corev1.ObjectReference, error) {
-	// Since the generated KubeadmConfig should eventually have a controller ref for the Machine, we create an
-	// OwnerReference here without the Controller field set
+	// Create an owner reference without a controller reference because the owning controller is the kubeadmconfig controller
```
Comment (detiber) [inline controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]:
```suggestion
	// Create an owner reference without a controller reference because the owning controller is the machine controller
```

File: controlplane/kubeadm/internal/cluster.go [hunk 2]
```diff
@@ -183,15 +183,88 @@ func (m *ManagementCluster) RemoveMachineFromKubeadmConfigMap(ctx context.Contex
 		// Nothing to do, no node for Machine
 		return nil
 	}
+	c, err := m.getCluster(ctx, clusterKey)
+	if err != nil {
+		return err
+	}
 
-	cluster, err := m.getCluster(ctx, clusterKey)
+	configMapKey := types.NamespacedName{Name: "kubeadm-config", Namespace: metav1.NamespaceSystem}
```
Comment (detiber) [inline controlplane/kubeadm/internal/cluster.go]:
```suggestion
	configMapKey := client.ObjectKey{Name: "kubeadm-config", Namespace: metav1.NamespaceSystem}
```

File: controlplane/kubeadm/internal/cluster.go [hunk 3]
```diff
@@ -183,15 +183,88 @@ func (m *ManagementCluster) RemoveMachineFromKubeadmConfigMap(ctx context.Contex
...
+}
+
+// UpdateKubernetesVersionInKubeadmConfigMap updates the kubernetes version in the kubeadm config map.
+func (m *ManagementCluster) UpdateKubernetesVersionInKubeadmConfigMap(ctx context.Context, clusterKey types.NamespacedName, version string) error {
+	c, err := m.getCluster(ctx, clusterKey)
+	if err != nil {
+		return err
+	}
+
+	configMapKey := types.NamespacedName{Name: "kubeadm-config", Namespace: metav1.NamespaceSystem}
```
Comment (detiber) [inline controlplane/kubeadm/internal/cluster.go]:
```suggestion
	configMapKey := client.ObjectKey{Name: "kubeadm-config", Namespace: metav1.NamespaceSystem}
```

File: controlplane/kubeadm/internal/cluster.go [hunk 4]
```diff
@@ -183,15 +183,88 @@ func (m *ManagementCluster) RemoveMachineFromKubeadmConfigMap(ctx context.Contex
...
 	if err != nil {
 		return err
 	}
 
-	return cluster.updateKubeadmConfigMap(ctx, func(in *corev1.ConfigMap) (*corev1.ConfigMap, error) {
-		return removeNodeFromKubeadmConfigMapClusterStatusAPIEndpoints(in, machine.Status.NodeRef.Name)
-	})
+	// Check if the desired configmap already exists
+	desiredKubeletConfigMapName := fmt.Sprintf("kubelet-config-%d.%d", version.Major, version.Minor)
+	configMapKey := types.NamespacedName{Name: desiredKubeletConfigMapName, Namespace: metav1.NamespaceSystem}
```
Comment (detiber) [inline controlplane/kubeadm/internal/cluster.go]:
```suggestion
	configMapKey := client.ObjectKey{Name: desiredKubeletConfigMapName, Namespace: metav1.NamespaceSystem}
```

File: controlplane/kubeadm/internal/cluster.go [hunk 5]
```diff
@@ -183,15 +183,88 @@ func (m *ManagementCluster) RemoveMachineFromKubeadmConfigMap(ctx context.Contex
...
+	if err == nil {
+		// Nothing to do, the configmap already exists
+		return nil
+	}
+	if !apierrors.IsNotFound(errors.Cause(err)) {
+		return errors.Wrapf(err, "error determining if kubelet configmap %s exists", desiredKubeletConfigMapName)
+	}
+
+	previousMinorVersionKubeletConfigMapName := fmt.Sprintf("kubelet-config-%d.%d", version.Major, version.Minor-1)
+	configMapKey = types.NamespacedName{Name: previousMinorVersionKubeletConfigMapName, Namespace: metav1.NamespaceSystem}
```
Comment (detiber) [inline controlplane/kubeadm/internal/cluster.go]:
```suggestion
	configMapKey := client.ObjectKey{Name: previousMinorVersionKubeletConfigMapName, Namespace: metav1.NamespaceSystem}
```

File: cmd/clusterctl/test/e2e/go.sum [hunk 6]
```diff
@@ -234,6 +234,7 @@ github.com/kr/pretty v0.1.0/go.mod h1:dAy3ld7l9f0ibDNOQOHHMYYIIbhfbHSm3C4ZsoJORN
 github.com/kr/pty v1.1.1/go.mod h1:pFQYn66WHrOpPYNljwOMqo10TkYh1fy3cYio2l3bCsQ=
 github.com/kr/pty v1.1.5/go.mod h1:9r2w37qlBe7rQ6e1fg1S/9xpWHSnaqNdHD3WcMdbPDA=
 github.com/kr/text v0.1.0/go.mod h1:4Jbv+DJW3UT/LiOwJeYQe1efqtUx/iVham/4vfdArNI=
+github.com/lithammer/dedent v1.1.0/go.mod h1:jrXYCQtgg0nJiN+StA2KgR7w6CiQNv9Fd/Z9BP0jIOc=
```
Comment (chuckha) [inline cmd/clusterctl/test/e2e/go.sum]: why though.

go mod gonna go mod i guess

File: controlplane/kubeadm/internal/cluster.go (hunk 2 above)
Comment (chuckha) [reply controlplane/kubeadm/internal/cluster.go]: Are we standardizing on client.ObjectKey? Are you thinking about this in terms of things getting passed to the `client.Client` should be the client.ObjectKey? Is there some semantic reason to use one or the other?

Comment (detiber) [reply controlplane/kubeadm/internal/cluster.go]: I believe we've been standardizing on it, if nothing else in many cases it eliminates a need for an additional import.

Comment (chuckha) [reply controlplane/kubeadm/internal/cluster.go]: sgtm

Comment (chuckha) [reply controlplane/kubeadm/internal/cluster.go]: There are a ton of types.NamespacedName all over the place. Mind if we track this with an issue?

Comment (detiber) [reply controlplane/kubeadm/internal/cluster.go]: I suspect many of them can likely be replaced with `util.ObjectKey` as well, so I think an issue is probably warranted :joy:

Comment (chuckha) [reply controlplane/kubeadm/internal/cluster.go]: https://github.com/kubernetes-sigs/cluster-api/issues/2459

yeah, it's not a tough ticket, but it's a lot of line changes

**Comment by chuckha** [comment]
closes #2429

**Comment by chuckha** [comment]
that PARTICULAR flake irks me.

I think it's a CAPD bug and it won't survive much longer (or maybe it will be a cockroach, i don't know)
