### PR TITLE
🐛 increase ignition additionalConfig maxSize from 10 to 32 KB

### LINKED ISSUE #12168: v1.10 MaxLength validation breaks machine creation with large ignition config
### What steps did you take and what happened?

After upgrading to cluster-api v1.10.1, specifying an ignition config in **spec.ignition.containerLinuxConfig.additionalConfig** in manifests referencing one of the following crds: 
**kubeadmconfigs.bootstrap.cluster.x-k8s.io
kubeadmconfigtemplates.bootstrap.cluster.x-k8s.io
kubeadmcontrolplanes.controlplane.cluster.x-k8s.io
kubeadmcontrolplanetemplates.controlplane.cluster.x-k8s.io**

with a size above 10240 bytes will prevent machines from being created or updated. 

### What did you expect to happen?

I expect my machines to be created / updated. So the MaxLength validation should be set to sane limit. I guess this depends on a.) the cloud provider and b.) ignition spec itself.
I will try to provide a.) for kolla installed openstack with default values. 

As already discussed on cluster-api slack it would be great if we could provide large ignition configs via Secret or ConfigMap. But this should not necessarily be the scope of this issue. 

### Cluster API version

v1.10.1 for core, kubeadm-bootstrap and kubeadm-control-plane
v0.12.3 for CAPO

### Kubernetes version

v1.32.4

### Anything else you would like to add?

Logs from capi-controller-manager
```
E0508 09:58:58.505422       1 controller.go:347] "Reconciler error" err="failed to sync replicas: failed to clone bootstrap configuration from KubeadmConfigTemplate test01-dev-nsc01/test01-dev-nsc01-test01-dev-nsc01-node-muc5-b-xmk6f while creating a machine: KubeadmConfig.bootstrap.cluster.x-k8s.io \"test01-dev-nsc01-node-muc5-b-qljnw-cr6xw-ddwfw\" is invalid: spec.ignition.containerLinuxConfig.additionalConfig: Too long: may not be more than 10240 bytes" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="test01-dev-nsc01/test01-dev-nsc01-node-muc5-b-qljnw-cr6xw" namespace="test01-dev-nsc01" name="test01-dev-nsc01-node-muc5-b-qljnw-cr6xw" reconcileID="5ed0acd9-6546-4dd4-8334-dd21c1515419"
```

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by networkhell**
**What this PR does / why we need it**:
cluster-api version 1.10 introduced min/maxLength markers on API fields. This breaks machine deployments with large (> 10240 Bytes) ignition additionalConfig data. This PR increases the maxLength of the field additionalConfig to a more reasonable limit of 48 KB.

Why I chose 48 KB? The supported maximum size of "user-data" provided on instance creation depends on the cloud provider. The limits for openstack and azure cloud are ~64KB. AWS for example is limited to 16KB. The ignition config used for instance creation is created by the bootstrapper process and then merged with the user provided additionalConfig. So I decided to limit additionalConfig to 64KB(theoretical maximum)-16KB(assumed max size of bootstrapper config)=48KB.

This is by no means a perfect choice but at least a more reasonable default.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #12168

/area api

### CODE REVIEW

File: bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go [hunk 1]
```diff
@@ -442,7 +442,7 @@ type ContainerLinuxConfig struct {
 	// The data format is documented here: https://kinvolk.io/docs/flatcar-container-linux/latest/provisioning/cl-config/
 	// +optional
 	// +kubebuilder:validation:MinLength=1
-	// +kubebuilder:validation:MaxLength=10240
+	// +kubebuilder:validation:MaxLength=65535
```
Comment (fabriziopandini) [inline bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go:445]: This doesn't seem aligned with the PR title/description

**Review by fabriziopandini — COMMENTED** [review]
If this is an intermediate step towards a proper fix (allow usage of secret or a config map like we do for files), shouldn't we pick something on the lower range of the spectrum, e.g. 20 or 25K?

**Comment by fabriziopandini** [comment]
>> If this is an intermediate step towards a proper fix (allow usage of secret or a config map like we do for files), shouldn't we pick something on the lower range of the spectrum, e.g. 20 or 25K?

> Are there any technical reasons to keep these values low? I would also be fine with 32 KB but I would vote against lower values until there exist alternative ways to provide the ignition / clc config.

Yep, See https://kubernetes.slack.com/archives/C8TSNPY4T/p1747388423670069?thread_ts=1746706504.153769&cid=C8TSNPY4T for the answer and implications we brought up in the thread were we discussed ^^.

Also, let's keep in mind that everything we add to KubeadmConfig end up in cache/impacts controller memory footprint.

@sbueringer @chrischdi opinions on the field size?

**Comment by sbueringer** [comment]
I'm okay with 32kb
