### PR TITLE
⚠️ Drop usage of GetValueFromIntOrPercent in favour of GetScaledValueFromIntOrPercent

### LINKED ISSUE #4531: Drop usage of GetValueFromIntOrPercent in favour of GetScaledValueFromIntOrPercent
**What steps did you take and what happened:**
Because we rely on [1] in this func [2] a string such as "2" would be treated as a percentage for this fields.

[1] https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/util/intstr/intstr.go#L164-L168

[2] https://github.com/kubernetes-sigs/cluster-api/blob/3bc596eea96cb27e23c8f2d6c758f6bd56db67b1/controllers/mdutil/util.go#L595-L600

**What did you expect to happen:**
An input with a string such as "2" fails validation.
Drop every use of GetValueFromIntOrPercent across the base code.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by enxebre**
**What this PR does / why we need it**:
Because we rely on [1] in this func [2] a string such as "2" would be treated as a percentage for this fields.
[1] https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/util/intstr/intstr.go#L164-L168
[2] https://github.com/kubernetes-sigs/cluster-api/blob/3bc596eea96cb27e23c8f2d6c758f6bd56db67b1/controllers/mdutil/util.go#L595-L600

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4531

### CODE REVIEW

**Comment by vincepri** [comment]
This seems like a breaking change. Also, we should make sure that we're consistent in other usage as well (like KCP)

**Comment by enxebre** [comment]
>Also, we should make sure that we're consistent in other usage as well (like KCP)

Make sense. I will.

>This seems like a breaking change. 

What considerations should I take care of to make it through?

**Comment by CecileRobertMichon** [comment]
Given that the apimachinery function we were previously relying on is deprecated (https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/util/intstr/intstr.go#L164-L168), I'm in favor of this change.

I would recommend adding clear user-facing documentation however so this change does not surprise users who were previously relying on this faulty behavior (if any).

**Comment by vincepri** [comment]
/retitle ⚠️ Drop usage of GetValueFromIntOrPercent in favour of GetScaledValueFromIntOrPercent

**Comment by enxebre** [comment]
>I would recommend adding clear user-facing documentation however so this change does not surprise users who were previously relying on this faulty behavior (if any).

Updated docs, please let me know if there's any other source that needs update.

File: api/v1alpha4/machinedeployment_webhook.go [hunk 1]
```diff
@@ -92,6 +93,34 @@ func (m *MachineDeployment) validate(old *MachineDeployment) error {
 		)
 	}
 
+	if m.Spec.Strategy != nil &&
```
Comment (fabriziopandini) [inline api/v1alpha4/machinedeployment_webhook.go:96]: Should we add a unit test for this validations rules?

File: docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md [hunk 2]
```diff
@@ -245,3 +245,10 @@ with `cert-manager.io/v1`
   ```yaml
   serviceAccountName: manager
   ```
+
+## Percentage String or Int API input will fail with a string different from an integer with % appended.
+
+`MachineDeployment.Spec.Strategy.RollingUpdate.MaxSurge`, `MachineDeployment.Spec.Strategy.RollingUpdate.MaxUnavailable` and `MachineHealthCheck.Spec.MaxUnhealthy` would have previously taken a String value with an integer character in it e.g "3" as a valid input and process it as a percentage value.
+Only String values like "3%" or Int values e.g 3 are valid input values now. A string not matching the percentage format will fail, e.g "3".
```
[the remark this answers is not in the document]
Comment (vincepri) [reply docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:252]: That's probably going to convert `3` from v1alpha4 to `3%` all the time there is a conversion, because the conversion code cannot tell if it was a percentage already or not.

[the remark this answers is not in the document]
Comment (fabriziopandini) [reply docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:252]: Wha about 
if isString && !HasSuffix("%"), then add the suffix

[the remark this answers is not in the document]
Comment (enxebre) [reply docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:252]: This would also open the discussion of should "3" convert to "3%" or to 3, so I'd personally be in favour of not adding any magic.

File: api/v1alpha4/machinedeployment_webhook.go (hunk 1 above)
Comment (enxebre) [reply api/v1alpha4/machinedeployment_webhook.go:96]: done!

File: docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md [hunk 3]
```diff
@@ -245,3 +245,10 @@ with `cert-manager.io/v1`
   ```yaml
   serviceAccountName: manager
   ```
+
+## Percentage String or Int API input will fail with a string different from an integer with % appended.
+
+`MachineDeployment.Spec.Strategy.RollingUpdate.MaxSurge`, `MachineDeployment.Spec.Strategy.RollingUpdate.MaxUnavailable` and `MachineHealthCheck.Spec.MaxUnhealthy` would have previously taken a String value with an integer character in it e.g "3" as a valid input and process it as a percentage value.
```
Comment (CecileRobertMichon) [inline docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:251]: this doc is meant for infra providers & developers, I think we also need to warn users. I suggest adding a warning note (using <aside>) to https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/tasks/upgrading-clusters.md#upgrading-machines-managed-by-a-machinedeployment (I couldn't find anywhere else with actual docs on rolling updates, I think that's missing from docs)

We should also make sure to include this info in the release notes when we release 0.4

File: docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md (hunk 2 above)
[the remark this answers is not in the document]
Comment (vincepri) [reply docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:252]: `if isString && !HasSuffix("%"), then add the suffix`

As @enxebre mentioned, we wouldn't know if the "3" value is coming from an already-v1alpha4 object and convert that to a percentage on their behalf (which would be a bug)

File: docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md (hunk 3 above)
Comment (enxebre) [reply docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:251]: Added to the other doc as well.
Do we have an automated way to add release notes?

Comment (CecileRobertMichon) [reply docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:251]: Adding the ⚠️ in the PR title will automatically trigger a breaking change release note

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

File: docs/book/src/tasks/upgrading-clusters.md [hunk 4]
```diff
@@ -80,6 +80,16 @@ transparently manage `MachineSet`s and `Machine`s to allow for a seamless scalin
...
 
+`MachineDeployment`s support different strategies for rolling out changes to `Machines`:
+
+- RollingUpdate
+
+Changes are rolled out by honouring `MaxUnavailable` and `MaxSurge` values.
+Only values allowed are of type Int or Strings with an integer and percentage symbol e.g "5%".
+
+- OnDelete
+Changes are rolled out driven by the user or any entity deleting the old machines. Only when a `Machine` is fully deleted a new one will come up.
```
Comment (sbueringer) [inline docs/book/src/tasks/upgrading-clusters.md:91]:
```suggestion
Changes are rolled out driven by the user or any entity deleting the old `Machines`. Only when a `Machine` is fully deleted a new one will come up.
```

File: docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md [hunk 5]
```diff
@@ -245,3 +245,10 @@ with `cert-manager.io/v1`
   ```yaml
   serviceAccountName: manager
   ```
+
+## Percentage String or Int API input will fail with a string different from an integer with % appended.
```
Comment (sbueringer) [inline docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:249]: As this document was afaik previously mostly used to document steps for infra providers to migrate from v1alpha3 to v1alpha4. Is there something infra providers have to change for this? Or just to make sure the infra providers are aware of the change?

File: api/v1alpha4/machinedeployment_webhook.go [hunk 6]
```diff
@@ -92,6 +93,34 @@ func (m *MachineDeployment) validate(old *MachineDeployment) error {
...
+		if m.Spec.Replicas != nil {
+			total = int(*m.Spec.Replicas)
+		}
+
+		if m.Spec.Strategy.RollingUpdate.MaxSurge != nil {
+			if _, err := intstrutil.GetScaledValueFromIntOrPercent(m.Spec.Strategy.RollingUpdate.MaxSurge, total, true); err != nil {
+				allErrs = append(
+					allErrs,
+					field.Invalid(field.NewPath("spec", "strategy", "rollingUpdate", "maxSurge"),
+						m.Spec.Strategy.RollingUpdate.MaxSurge, fmt.Sprintf("invalid value: %v", err.Error())),
```
Comment (sbueringer) [inline api/v1alpha4/machinedeployment_webhook.go:108]: Looking at the *current* implementation of `GetScaledValueFromIntOrPercent` an error would read like: `invalid value: invalid value for IntOrString..`

Not sure what's more important, not relying on the exact error produced by `GetScaledValueFromIntOrPercent` or having an error text which is a bit less redundant

File: api/v1alpha4/machinedeployment_webhook_test.go [hunk 7]
```diff
@@ -86,6 +97,58 @@ func TestMachineDeploymentValidation(t *testing.T) {
...
+			selectors: map[string]string{"-123-foo": "bar"},
+			labels:    map[string]string{"-123-foo": "bar"},
+			strategy: MachineDeploymentStrategy{
+				Type: RollingUpdateMachineDeploymentStrategyType,
+				RollingUpdate: &MachineRollingUpdateDeployment{
+					MaxUnavailable: &goodMaxUnavailableInt,
+					MaxSurge:       &goodMaxSurgeInt,
+				},
+			},
+			expectErr: true,
```
Comment (sbueringer) [inline api/v1alpha4/machinedeployment_webhook_test.go:137]: Maybe I"m missing something but the combination of "should not return error" and `expectErr: true` is either not correct or not intuitive. (Same below)

File: api/v1alpha4/machinehealthcheck_webhook.go [hunk 8]
```diff
@@ -138,18 +137,11 @@ func (m *MachineHealthCheck) validate(old *MachineHealthCheck) error {
 	}
 
 	if m.Spec.MaxUnhealthy != nil {
-		if _, err := intstr.GetValueFromIntOrPercent(m.Spec.MaxUnhealthy, 0, false); err != nil {
+		if _, err := intstr.GetScaledValueFromIntOrPercent(m.Spec.MaxUnhealthy, 0, false); err != nil {
 			allErrs = append(
 				allErrs,
 				field.Invalid(field.NewPath("spec", "maxUnhealthy"), m.Spec.MaxUnhealthy, "must be either an int or a percentage"),
```
Comment (sbueringer) [inline api/v1alpha4/machinehealthcheck_webhook.go:143]: Maybe we want to make the err text consistent to the one returned in the MachineDeployment webhook

**Review by sbueringer — COMMENTED** [review]
a few nits

File: api/v1alpha4/machinedeployment_webhook.go (hunk 6 above)
Comment (enxebre) [reply api/v1alpha4/machinedeployment_webhook.go]: make sense, changed and aligned with the one in mhc.

File: api/v1alpha4/machinedeployment_webhook_test.go (hunk 7 above)
Comment (enxebre) [reply api/v1alpha4/machinedeployment_webhook_test.go]: My bad I was carrying over bad labels and therefore failing always. Fixed, thanks!

File: docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md (hunk 5 above)
Comment (enxebre) [reply docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:249]: The latter. I can drop it if folks think is not appropriate to have it in this doc.

Comment (sbueringer) [reply docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md:249]: Both options are fine for me. Just wanted to be absolutely sure that I don't miss something for CAPO.
