### PR TITLE
🐛 Fix doctoc detection in verify-doctoc.sh

### LINKED ISSUE #9114: Ensure the doctoc tool works
Cluster API uses the doctoc tool to ensure a table of contents is generated for certain markdown files. It looks like the script and the make target it calls are not working correctly - at least with the version of doctoc I installed. It seems that it is not able to run doctoc against the set of files as passed in the script.

Additionally we should increase the number of files covered by this make target. Currently those markdown files are hardcoded. The `hack/verify-doctoc.sh` script should be updated so that it generates tables of contents correctly for all proposals in the CAPI repo - i.e all the markdown files in `docs/proposals`

c/f https://github.com/kubernetes-sigs/cluster-api/pull/9112#discussion_r1283047443

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9114

### CODE REVIEW

File: hack/verify-doctoc.sh [hunk 1]
```diff
@@ -22,7 +22,7 @@ if [[ "${TRACE-0}" == "1" ]]; then
     set -o xtrace
 fi
 
-command -v doctoc || echo "doctoc is not available on your system, skipping verification" && exit 0
+command -v doctoc || (echo "doctoc is not available on your system, skipping verification" && exit 0)
```
Comment (sbueringer) [inline hack/verify-doctoc.sh:25]: Before this change, this exited even if the command exists

File: hack/verify-doctoc.sh [hunk 2]
```diff
@@ -22,7 +22,10 @@ if [[ "${TRACE-0}" == "1" ]]; then
     set -o xtrace
 fi
 
-command -v doctoc || echo "doctoc is not available on your system, skipping verification" && exit 0
+if [[ -z "$(command -v doctoc)" ]]; then
+  echo "doctoc is not available on your system, skipping verification"
+  exit 0
+fi
 
 doctoc_files="README.md \
```
Comment (killianmuldoon) [inline hack/verify-doctoc.sh:30]: The list of files here seems pretty limited - but we don't need tables of contents everywhere. should we at least add it to proposals? Not sure how else we'd like to enforce this in the book, but it's worked fine until now.

Comment (killianmuldoon) [reply hack/verify-doctoc.sh:30]: Will do

Comment (killianmuldoon) [reply hack/verify-doctoc.sh:30]: I'll open an issue and mark it as help for this.

Comment (killianmuldoon) [reply hack/verify-doctoc.sh:30]: https://github.com/kubernetes-sigs/cluster-api/issues/9114

**Review by killianmuldoon — COMMENTED** [review]
Just playing around with this and it looks like this script doesn't work at all - or at least not with the version of doctoc i've installed. I'm constantly just getting an error. 

@sbueringer did this work for you?

**Comment by sbueringer** [comment]
What error are you getting?

I think for me it works in general but the way we define the list of files is broken (aka it only does something if I use something like this withou the newlines: `doctoc_files="docs/staging-use-cases.md"`)

**Comment by sbueringer** [comment]
```
npm list -g doctoc
/home/sbuerin/.nvm/versions/node/v18.10.0/lib
└── doctoc@2.2.1
```

**Comment by sbueringer** [comment]
Working on a fix, give me a few minutes

File: hack/generate-doctoc.sh [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+    set -o xtrace
+fi
+
+if [[ -z "$(command -v doctoc)" ]]; then
+  echo "doctoc is not available on your system, skipping verification"
+  echo "Note: The doctoc module can be installed via npm (https://www.npmjs.com/package/doctoc)"
+  exit 0
+fi
+
+doctoc ./CONTRIBUTING.md docs/release/release-tasks.md docs/scope-and-objectives.md docs/staging-use-cases.md docs/proposals
```
Comment (sbueringer) [inline hack/generate-doctoc.sh:31]: Seems a lot easier than the old version. Also it doesn't hide if it does something...

**Comment by sbueringer** [comment]
Now it works.. Updated the list to include proposals + dropped some documents that don't have and don't need a toc

**Comment by sbueringer** [comment]
> Would it be better to fix this in this PR?

Absolutely. I was not aware that it doesn't work. I tested this script in CAPV and I think in CAPV it worked because I only used it for a single file

File: docs/proposals/20210526-cluster-class-and-managed-topologies.md [hunk 4]
```diff
@@ -573,7 +576,7 @@ In this cases for ServerSideApply to work properly it is required to ensure the
 type definitions, like +MapType or +MapTypeKey, see [merge strategy](https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy) for more details.
 
 Note: in order to allow the topology controller to execute templates rotation only when strictly necessary, it is necessary
-to implement specific handling of dry run operations in the templates webhooks as described in [Required Changes on providers from 1.1 to 1.2](https://cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html#required-api-changes-for-providers).
+to implement specific handling of dry run operations in the templates webhooks as described in [Required Changes on providers from 1.1 to 1.2](https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.1-to-v1.2#required-api-changes-for-providers).
```
Comment (sbueringer) [inline docs/proposals/20210526-cluster-class-and-managed-topologies.md:579]: Seems to be the first time we're touching this file since we published the v1.5 book

Comment (killianmuldoon) [inline docs/proposals/20210526-cluster-class-and-managed-topologies.md:579]: Thanks for updating this!

**Review by killianmuldoon — COMMENTED** [review]
Working and much simpler thanks!

/lgtm
/approve

File: docs/proposals/20210526-cluster-class-and-managed-topologies.md (hunk 4 above)
Comment (sbueringer) [reply docs/proposals/20210526-cluster-class-and-managed-topologies.md:579]: Had to :D

Comment (killianmuldoon) [reply docs/proposals/20210526-cluster-class-and-managed-topologies.md:579]: I did see it in the weekly run earlier, but didn't get around to fixing.
