### PR TITLE
🌱 Reenable 2 MHC unit tests

### LINKED ISSUE #9903: Remove skip from Machine health check test
### Which jobs are failing?

The node gone away test is flaky, and needs to be fixed.

### Which tests are failing?

https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go#L978

Also once this https://github.com/kubernetes-sigs/cluster-api/pull/9774 merged, this will also include a similar test.

### Since when has it been failing?

Don't know

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Label(s) to be applied

/kind failing-test
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by cahillsf**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9903

/area machinehealthcheck

### CODE REVIEW

**Comment by cahillsf** [comment]
## when a Machine's Node has gone away
failure:

```
--- FAIL: TestMachineHealthCheck_Reconcile (32.66s)
    --- FAIL: TestMachineHealthCheck_Reconcile/when_a_Machine's_Node_has_gone_away (32.65s)
        machinehealthcheck_controller_test.go:1069: 
            Timed out after 30.001s.
            Expected
                <int>: 2
            to equal
                <int>: 1
FAIL
```

unexpected remediation:
```
I0718 19:16:12.978262   82258 machinehealthcheck_controller.go:435] "Target has failed health check, marking for remediation" controller="machinehealthcheck" controllerGroup="cluster.x-k8s.io" controllerKind="MachineHealthCheck" MachineHealthCheck="test-mhc-hh6v8/test-mhc-kjj7x" namespace="test-mhc-hh6v8" name="test-mhc-kjj7x" reconcileID="c787a48f-8a18-4cd2-b355-4f929cb1c6d6" Cluster="test-mhc-hh6v8/test-cluster-fdcf2" target="test-mhc-hh6v8/test-mhc-kjj7x/test-mhc-machine-8cmcv/" reason="NodeStartupTimeout" message="Node failed to report startup in 1ms"
```

expected remediation:
```
I0718 19:16:13.417869   82258 machinehealthcheck_controller.go:435] "Target has failed health check, marking for remediation" controller="machinehealthcheck" controllerGroup="cluster.x-k8s.io" controllerKind="MachineHealthCheck" MachineHealthCheck="test-mhc-hh6v8/test-mhc-kjj7x" namespace="test-mhc-hh6v8" name="test-mhc-kjj7x" reconcileID="3b971619-b43f-4565-a9d0-41d435c91a05" Cluster="test-mhc-hh6v8/test-cluster-fdcf2" target="test-mhc-hh6v8/test-mhc-kjj7x/test-mhc-machine-g2m4k/" reason="NodeNotFound" message=""
```


## when a Machine has no Node ref for longer than the NodeStartupTimeout

Failure:
```
--- FAIL: TestMachineHealthCheck_Reconcile (33.11s)
    --- FAIL: TestMachineHealthCheck_Reconcile/when_a_Machine_has_no_Node_ref_for_longer_than_the_NodeStartupTimeout (33.10s)
        machinehealthcheck_controller_test.go:975: 
            Timed out after 30.000s.
            Expected
                <int>: 2
            to equal
                <int>: 1

```

unexpected remediation:
```
I0718 19:08:06.039675   77374 machinehealthcheck_controller.go:435] "Target has failed health check, marking for remediation" controller="machinehealthcheck" controllerGroup="cluster.x-k8s.io" controllerKind="MachineHealthCheck" MachineHealthCheck="test-mhc-8fzfd/test-mhc-swlqt" namespace="test-mhc-8fzfd" name="test-mhc-swlqt" reconcileID="38905778-daec-4868-914f-8cf25d893355" Cluster="test-mhc-8fzfd/test-cluster-twwzs" target="test-mhc-8fzfd/test-mhc-swlqt/test-mhc-machine-jvf4p/" reason="NodeStartupTimeout" message="Node failed to report startup in 1s"
```

expected remediation:
```
I0718 19:08:06.046092   77374 machinehealthcheck_controller.go:435] "Target has failed health check, marking for remediation" controller="machinehealthcheck" controllerGroup="cluster.x-k8s.io" controllerKind="MachineHealthCheck" MachineHealthCheck="test-mhc-8fzfd/test-mhc-swlqt" namespace="test-mhc-8fzfd" name="test-mhc-swlqt" reconcileID="d1bd88fe-a14a-4ced-ad3f-c1ed4a617841" Cluster="test-mhc-8fzfd/test-cluster-twwzs" target="test-mhc-8fzfd/test-mhc-swlqt/test-mhc-machine-rch4n/" reason="NodeNotFound" message=""
```

**Comment by cahillsf** [comment]
```zsh
➜ KUBEBUILDER_ASSETS="/Users/stephen.cahill/Library/Application Support/io.kubebuilder.envtest/k8s/1.30.0-darwin-arm64" go test -run ^TestMachineHealthCheck_Reconcile$/^when_a_Machine_has_no_Node_ref_for_longer_than_the_NodeStartupTimeout$ -count=50 -failfast
...
ok  	sigs.k8s.io/cluster-api/internal/controllers/machinehealthcheck	305.461s 
```

```zsh
KUBEBUILDER_ASSETS="/Users/stephen.cahill/Library/Application Support/io.kubebuilder.envtest/k8s/1.30.0-darwin-arm64" go test -run ^TestMachineHealthCheck_Reconcile$/^when_a_Machine\'s_Node_has_gone_away\$ -count=50 -failfast
...

```

File: internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go [hunk 1]
```diff
@@ -2645,7 +2640,7 @@ func newMachineHealthCheck(namespace, clusterName string) *clusterv1.MachineHeal
 				},
 			},
 			MaxUnhealthy:       &maxUnhealthy,
-			NodeStartupTimeout: &metav1.Duration{Duration: 1 * time.Millisecond},
+			NodeStartupTimeout: &metav1.Duration{Duration: 5 * time.Second},
```
Comment (sbueringer) [inline internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go:2643]: It's really hard for me to tell what impact this has, this func has ~ 20-30 usages. I would prefer if we only change this locally

**Comment by sbueringer** [comment]
@cahillsf Thx for looking into this. I'm generally fine with using 5s for these to tests. I would just prefer if we set it locally in those tests. It's really hard for me to assess the impact on all other tests using this func and if this would introduce new flakes elsewhere

File: internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go (hunk 1 above)
Comment (sbueringer) [reply internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go:2645]: @cahillsf Probably not intentional but these are still different :)

**Comment by sbueringer** [comment]
@cahillsf https://github.com/kubernetes-sigs/cluster-api/pull/10906#discussion_r1693224777 :)

File: internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go (hunk 1 above)
Comment (cahillsf) [reply internal/controllers/machinehealthcheck/machinehealthcheck_controller_test.go:2645]: ah yes, i actually made an additional unintended change instead of reverting 🙃

**Comment by cahillsf** [comment]
> @cahillsf [#10906 (comment)](https://github.com/kubernetes-sigs/cluster-api/pull/10906#discussion_r1693224777) :)

whoops 🙃 fixed when you have a chance to take another pass

**Comment by sbueringer** [comment]
Thank you!
/lgtm
/approve

**Comment by sbueringer** [comment]
@cahillsf Looks like one of them failed again (https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-mink8s-main/1820212332773511168) Do you have some time to look into it?

**Comment by sbueringer** [comment]
Looks like this one as well: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1819898507000025088

**Comment by sbueringer** [comment]
I think we don't have to revert it happens pertty infrequently. Fine to try to just increase the timeout further to see if that resolves it
