### PR TITLE
:bug: Ensure ownerReference apiVersions are always up to date

### LINKED ISSUE #7224: CAPI controllers should keep ownerRefs on the current apiVersion
I took a closer look at our ownerRefs and how they evolve (or not) after ClusterAPI upgrades. In some cases we bump the apiVersions automatically in some cases we don’t. Our cluster deletion reconciliation works independent of the apiVersion, but the Kubernetes garbage collection does not.

An Example:
* MD > MS > M is created with v1alpha3
* ownerRefs in MS and M are set with v1alpha3
* CAPI is upgraded a few times => ownerRefs stay on v1alpha3
* Eventually CAPI is upgraded to a version which doesn’t have v1alpha3
* => Kubernetes garbage collection is broken

Now let's take a look at how MachineDeployment deletion usually works:
* MD is deleted be the user
* kube-controller-manager garbage collector triggers deletion of MS when MD is gone
* MS is deleted
* kube-controller-manager garbage collector triggers deletion of Machines when MS is gone

Let's now assume the case from above. MS has an ownerRef from MD with an apiVersion that doesn't exist anymore (e.g. v1alpha3 in the example). The MD deletion now won't work anymore:
* MD is deleted
* MS still exists
  * The kube-controller-manager garbage collector is not able to “get” the MD in the old apiVersion

This seems like a bug to me and a blocker for removal of v1alpha3 apiVersions. I don't know for which resources exactly we depend on the Kubernetes garbage collection but I think we should keep all ownerRefs we set on the current apiVersion.

Proposed tasks:
* [ ] Probably makes sense to investigate if there is guidance on how to manage ownerRefs upstream
* [ ] audit all controllers/resources to figure out which ones are setting ownerRefs
* [ ] fix controllers to keep ownerRefs up-to-date (one example is the MD controller)
* [ ] broadcast this issue in office hours as it might be helpful for providers

It would be nice to have this implemented for v1.3.0 so we can consider dropping v1alpha3/v1alpha3 in the next releases.

/kind feature

### PR DESCRIPTION
**Pull request by killianmuldoon**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7224

### CODE REVIEW

File: controlplane/kubeadm/internal/controllers/helpers.go [hunk 1]
```diff
@@ -102,46 +102,45 @@ func (r *KubeadmControlPlaneReconciler) reconcileKubeconfig(ctx context.Context,
...
+	// If secret type is a CAPI-created secret ensure the owner reference is to KCP.
+	if configSecret.Type == clusterv1.ClusterSecretType {
+		log.Info("Adopting KubeConfig secret", "Secret", klog.KObj(configSecret))
+		// Remove the current controller if one exists and ensure KCP is the controller of the secret.
+		if controller != nil {
+			configSecret.SetOwnerReferences(util.RemoveOwnerRef(configSecret.OwnerReferences, *controller))
+		}
+		configSecret.SetOwnerReferences(util.EnsureOwnerRef(configSecret.OwnerReferences, *metav1.NewControllerRef(kcp, controlplanev1.GroupVersion.WithKind("KubeadmControlPlane"))))
+
+		// If the kubeconfig secret was created by v1alpha2 controllers, and thus it has the Cluster as the owner instead of KCP.
```
Comment (sbueringer) [inline controlplane/kubeadm/internal/controllers/helpers.go:134]: Q: Is this something which was already done by running v1alpha3 or v1alpha4 controllers? If yes, let's drop l.135-142.

File: exp/addons/internal/controllers/clusterresourceset_helpers.go [hunk 2]
```diff
@@ -121,7 +120,14 @@ func (r *ClusterResourceSetReconciler) getOrCreateClusterResourceSetBinding(ctx
 		}
 		clusterResourceSetBinding.Name = cluster.Name
 		clusterResourceSetBinding.Namespace = cluster.Namespace
-		clusterResourceSetBinding.OwnerReferences = ensureOwnerRefs(clusterResourceSetBinding, clusterResourceSet)
+		clusterResourceSetBinding.OwnerReferences = []metav1.OwnerReference{
+			{
+				APIVersion: addonsv1.GroupVersion.String(),
+				Kind:       clusterResourceSet.GroupVersionKind().Kind,
```
Comment (sbueringer) [inline exp/addons/internal/controllers/clusterresourceset_helpers.go:126]: nit: Let's just use "ClusterResourceSet" here? (or with a const if you want)

File: exp/addons/internal/controllers/clusterresourcesetbinding_controller.go [hunk 3]
```diff
@@ -79,33 +79,35 @@ func (r *ClusterResourceSetBindingReconciler) Reconcile(ctx context.Context, req
 		// Error reading the object - requeue the request.
 		return ctrl.Result{}, err
 	}
+	patchHelper, err := patch.NewHelper(binding, r.Client)
+	if err != nil {
+		return ctrl.Result{}, errors.Wrap(err, "failed to configure the patch helper")
+	}
+	defer func() {
+		if err = patchHelper.Patch(ctx, binding); err != nil {
+			reterr = errors.Wrap(err, "failed to patch ClusterResourceSetBinding to add spec.clusterName")
```
Comment (sbueringer) [inline exp/addons/internal/controllers/clusterresourcesetbinding_controller.go:88]:
```suggestion
			reterr = errors.Wrap(err, "failed to patch ClusterResourceSetBinding")
```
to avoid a misleading error if we change something else

File: exp/addons/internal/controllers/clusterresourcesetbinding_controller.go [hunk 4]
```diff
@@ -79,33 +79,35 @@ func (r *ClusterResourceSetBindingReconciler) Reconcile(ctx context.Context, req
...
-		if err = patchHelper.Patch(ctx, binding); err != nil {
-			return ctrl.Result{}, errors.Wrap(err, "failed to patch ClusterResourceSetBinding to add spec.clusterName")
-		}
-		// Will enter the next Reconcile
+		// Return here to ensure this change is patched before proceeding.
 		return ctrl.Result{}, nil
 	}
-	cluster, err := util.GetClusterByName(ctx, r.Client, req.Namespace, clusterName)
+	// Remove the Cluster ownerRef if one is set.
+	binding.SetOwnerReferences(util.RemoveOwnerRef(binding.OwnerReferences, metav1.OwnerReference{
```
Comment (sbueringer) [inline exp/addons/internal/controllers/clusterresourcesetbinding_controller.go:104]: It would be nice to a have a follow-up issue to try to figure out when/if we can get rid of this migration code
(one question is when, the other one is which code exactly can we get rid of after x releases and which do we have to keep forever)

(of course potentially also includes other places like the KCP controller)

File: exp/addons/internal/controllers/clusterresourcesetbinding_controller.go [hunk 5]
```diff
@@ -79,33 +79,35 @@ func (r *ClusterResourceSetBindingReconciler) Reconcile(ctx context.Context, req
...
-		})
-		if err = patchHelper.Patch(ctx, binding); err != nil {
-			return ctrl.Result{}, errors.Wrap(err, "failed to patch ClusterResourceSetBinding to add spec.clusterName")
-		}
-		// Will enter the next Reconcile
+		// Return here to ensure this change is patched before proceeding.
 		return ctrl.Result{}, nil
 	}
-	cluster, err := util.GetClusterByName(ctx, r.Client, req.Namespace, clusterName)
+	// Remove the Cluster ownerRef if one is set.
```
Comment (sbueringer) [inline exp/addons/internal/controllers/clusterresourcesetbinding_controller.go:103]: Q: why not keep this in the if? I would assume that we only have to do this for the ClusterName migration?

Or do we just feel a bit safer doing this always?

File: test/e2e/clusterctl_upgrade.go [hunk 6]
```diff
@@ -98,7 +98,7 @@ type ClusterctlUpgradeSpecInput struct {
 	ControlPlaneWaiters clusterctl.ControlPlaneWaiters
 	PreInit             func(managementClusterProxy framework.ClusterProxy)
 	PreUpgrade          func(managementClusterProxy framework.ClusterProxy)
-	PostUpgrade         func(managementClusterProxy framework.ClusterProxy)
+	PostUpgrade         func(managementClusterProxy framework.ClusterProxy, namespace, clusterName string)
```
Comment (sbueringer) [inline test/e2e/clusterctl_upgrade.go:101]:
```suggestion
	PostUpgrade         func(managementClusterProxy framework.ClusterProxy, clusterNamespace, clusterName string)
```
nit

File: test/framework/ownerreference_helpers.go [hunk 7]
```diff
@@ -37,9 +37,17 @@ import (
 	clusterctlcluster "sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster"
 	controlplanev1 "sigs.k8s.io/cluster-api/controlplane/kubeadm/api/v1beta1"
 	addonsv1 "sigs.k8s.io/cluster-api/exp/addons/api/v1beta1"
+	expv1 "sigs.k8s.io/cluster-api/exp/api/v1beta1"
 	"sigs.k8s.io/cluster-api/util/patch"
 )
 
+// ValidateOwnerReferencesOnUpdate checks that expected owner references are in place, deletes them, and verifies that expect owner references are properly rebuilt.
```
Comment (sbueringer) [inline test/framework/ownerreference_helpers.go:44]: nit: godoc contains a bit too much :)

File: test/framework/ownerreference_helpers.go [hunk 8]
```diff
@@ -89,16 +97,17 @@ func AssertOwnerReferences(namespace, kubeconfigPath string, assertFuncs ...map[
...
-		errStrings = ""
-		for _, err := range allErrs {
-			errStrings = fmt.Sprintf("%s\n%s", errStrings, err.Error())
+		err = kerrors.NewAggregate(allErrs)
+		if err != nil {
+			aggregateErrs = err.Error()
 		}
-		return kerrors.NewAggregate(allErrs)
-	}).Should(Succeed(), errStrings)
+		return err
```
Comment (sbueringer) [inline test/framework/ownerreference_helpers.go:104]: nit: Why not just return `kerrors.NewAggregate(allErrs)` (and drop aggregateErrs)? 

Gomega will print all the errors without us redundantly adding them optional description

File: util/util.go [hunk 9]
```diff
@@ -295,6 +295,7 @@ func HasOwnerRef(ownerReferences []metav1.OwnerReference, ref metav1.OwnerRefere
 }
 
 // EnsureOwnerRef makes sure the slice contains the OwnerReference.
+// Note EnsureOwnerRef will update the version of the OwnerReference if it exists with a different version.
```
Comment (sbueringer) [inline util/util.go:298]: Thank you very much for adding this comment!!

Can you please take a look at similar functions around here and add the same if it makes sense? (e.g. I was stumbling over RemoveOwnerRef)

File: test/e2e/clusterctl_upgrade_test.go [hunk 10]
```diff
@@ -158,6 +226,18 @@ var _ = Describe("When testing clusterctl upgrades using ClusterClass (v1.3=>cur
 			InitWithProvidersContract: "v1beta1",
 			InitWithKubernetesVersion: "v1.26.0",
 			WorkloadFlavor:            "topology",
+			// This check ensures that ownerReference apiVersions are updated for all types after the upgrade.
+			// TODO: Extend this test to include all ClusterClass templates when v1beta2 is released.
```
Comment (sbueringer) [inline test/e2e/clusterctl_upgrade_test.go:230]: Just thought about it again and saw your code. This will just work automatically, right?

We already validate the ownerRefs of KubeadmControlPlaneTemplate and DockerClusterTemplate. The only reason we don't validate the upgrade is that there is no way to use a ClusterClass with an old apiVersion of those.

But I think this will happen naturally. (Just like we test v1.2 / v1.3 upgrades with ClusterClass)

So fine for me to drop the TODOs for that

File: test/framework/ownerreference_helpers.go [hunk 11]
```diff
@@ -37,9 +37,17 @@ import (
...
 	addonsv1 "sigs.k8s.io/cluster-api/exp/addons/api/v1beta1"
+	expv1 "sigs.k8s.io/cluster-api/exp/api/v1beta1"
 	"sigs.k8s.io/cluster-api/util/patch"
 )
 
+// ValidateOwnerReferencesOnUpdate checks that expected owner references are in place, deletes them, and verifies that expect owner references are properly rebuilt.
+// TODO: Extend this test to include all ClusterClass templates when v1beta2 is released.
+func ValidateOwnerReferencesOnUpdate(proxy ClusterProxy, namespace string, assertFuncs ...map[string]func(reference []metav1.OwnerReference) error) {
+	// Check that the ownerReferences are as expected on the first iteration.
+	AssertOwnerReferences(namespace, proxy.GetKubeconfigPath(), assertFuncs...)
```
Comment (sbueringer) [inline test/framework/ownerreference_helpers.go:48]: Regarding test coverage:
* I went through all our CRDs and looks like we covered everything (with the expected exceptions of provider, the ipam types and the types for which we don't have old apiVersions (KubeadmControlPlaneTemplate & DockerClusterTemplate)
* Is my assumption correct that AssertOwnerReferences enforces that we assert all objects in the ownerGraph? Which is basically the same as all objects that clusterctl move would move?

Comment (sbueringer) [reply test/framework/ownerreference_helpers.go:48]: One additional thing. We could go through all usages of our ownerRef utils to double-check if we missed an ownerRef that we should keep up-to-date

**Review by fabriziopandini — COMMENTED** [review]
kudos for the great work in implementing test coverage
I'm + to get this merged as soon as all the nits are addressed, so we can have some time to look at the CI signal before the release

File: cmd/clusterctl/client/cluster/ownergraph.go [hunk 12]
```diff
@@ -64,20 +54,77 @@ func GetOwnerGraph(namespace, kubeconfigPath string) (OwnerGraph, error) {
 		return OwnerGraph{}, errors.Wrap(err, "failed to retrieve discovery types")
 	}
 
-	// Discovery the object graph for the selected types:
-	// - Nodes are defined the Kubernetes objects (Clusters, Machines etc.) identified during the discovery process.
-	// - Edges are derived by the OwnerReferences between nodes.
-	if err := graph.Discovery(namespace); err != nil {
-		return OwnerGraph{}, errors.Wrap(err, "failed to discover the object graph")
+	owners, err := discoverOwnerGraph(namespace, graph)
```
[the remark this answers is not in the document]
Comment (killianmuldoon) [reply cmd/clusterctl/client/cluster/ownergraph.go:57]: The issue with `graph.Discovery` is that it sets ownerReferences based on the object graph - so the apiVersion is not preserved if it's different from that in the objectGraph - https://github.com/kubernetes-sigs/cluster-api/blob/f2ba999757aa76b446943a9ffea14ecf8c7523e8/cmd/clusterctl/client/cluster/objectgraph.go#L213 

I'll add a note referencing this. I'm not sure it's worthwhile merging the two -  especially given one is just testing code - but I'll open a follow up issue.

File: controlplane/kubeadm/internal/controllers/controller.go [hunk 13]
```diff
@@ -888,21 +897,28 @@ func ensureCertificatesOwnerRef(ctx context.Context, ctrlclient client.Client, c
...
 		patchHelper, err := patch.NewHelper(s, ctrlclient)
 		if err != nil {
 			return errors.Wrapf(err, "failed to create patchHelper for Secret %s", secretKey)
 		}
 
-		// Remove the current controller if one exists.
-		if controller := metav1.GetControllerOf(s); controller != nil {
-			s.SetOwnerReferences(util.RemoveOwnerRef(s.OwnerReferences, *controller))
+		// If the current controller is KCP, ensure the owner reference is up to date.
+		// Note: This ensures secrets created prior to v1alpha4 are updated to have the correct owner reference apiVersion.
```
[the remark this answers is not in the document]
Comment (killianmuldoon) [reply controlplane/kubeadm/internal/controllers/controller.go:908]: Yeah - but I assume the same issue existed in v1alpha2 so I didn't want to be very specific here - can update if you prefer.

File: controlplane/kubeadm/internal/controllers/controller.go [hunk 14]
```diff
@@ -851,28 +854,34 @@ func (r *KubeadmControlPlaneReconciler) adoptOwnedSecrets(ctx context.Context, k
...
+
 		// avoid taking ownership of the bootstrap data secret
 		if currentOwner.Status.DataSecretName != nil && s.Name == *currentOwner.Status.DataSecretName {
 			continue
 		}
 
-		ss := s.DeepCopy()
-
-		ss.SetOwnerReferences(util.ReplaceOwnerRef(ss.GetOwnerReferences(), currentOwner, metav1.OwnerReference{
+		ss.SetOwnerReferences(util.EnsureOwnerRef(ss.GetOwnerReferences(), metav1.OwnerReference{
```
[the remark this answers is not in the document]
Comment (killianmuldoon) [reply controlplane/kubeadm/internal/controllers/controller.go]: This part is removed from the PR now - I'll add some comments to this in a seperate PR.

File: controlplane/kubeadm/internal/controllers/helpers.go [hunk 15]
```diff
@@ -102,46 +102,45 @@ func (r *KubeadmControlPlaneReconciler) reconcileKubeconfig(ctx context.Context,
...
 
-	// Add the KubeadmControlPlane as the controller for this secret.
-	configSecret.OwnerReferences = util.EnsureOwnerRef(configSecret.OwnerReferences,
-		*metav1.NewControllerRef(kcp, controlplanev1.GroupVersion.WithKind("KubeadmControlPlane")))
-
-	if err := patch.Patch(ctx, configSecret); err != nil {
-		return errors.Wrap(err, "failed to patch the kubeconfig secret")
+	// If secret type is a CAPI-created secret ensure the owner reference is to KCP.
+	if configSecret.Type == clusterv1.ClusterSecretType {
+		log.Info("Adopting KubeConfig secret", "Secret", klog.KObj(configSecret))
```
[the remark this answers is not in the document]
Comment (killianmuldoon) [reply controlplane/kubeadm/internal/controllers/helpers.go:128]: I've removed it now

**Comment by killianmuldoon** [comment]
/retitle :bug: Ensure ownerReference apiVersions are always up to date

File: cmd/clusterctl/client/cluster/ownergraph.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (sbueringer) [reply cmd/clusterctl/client/cluster/ownergraph.go:59]: Sounds good! I also settle for a godoc comment why we can't reuse the existing code

File: controlplane/kubeadm/internal/controllers/controller.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (sbueringer) [reply controlplane/kubeadm/internal/controllers/controller.go:902]: It's fine as is

File: controlplane/kubeadm/internal/controllers/helpers.go (hunk 1 above)
Comment (sbueringer) [reply controlplane/kubeadm/internal/controllers/helpers.go:131]: Ah I see. Sounds good. The comment just made it sound like we could rid of it, but makes sense what you're saying

**Comment by sbueringer** [comment]
Interesting

> Unexpected ownerReferences for ClusterResourceSetBinding/clusterctl-upgrade-evj198: wanted [addons.cluster.x-k8s.io/v1beta1, Kind=ClusterResourceSet], actual [cluster.x-k8s.io/v1alpha3, Kind=Cluster addons.cluster.x-k8s.io/v1beta1, Kind=ClusterResourceSet]

**Comment by killianmuldoon** [comment]
/hold cancel

Passing the full e2e tests now
