### PR TITLE
:bug: permit empty/not set providerIDList

### LINKED ISSUE #6210: MachinePool controller infrastructure reconcile fails when providerIDList is not set or empty
**What steps did you take and what happened:**
Test to reproduce the issue can be found here: https://github.com/kubernetes-sigs/cluster-api/compare/main...helio:machinepool-empty-providerIDList?expand=1

While working on https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3253#issuecomment-1050792767 I noticed an issue with the CAPI MachinePool controller and it's behaviour when a MachinePool replica count reaches zero. 
In the case of CAPA (AWS provider) this will result in the field `AWSMachinePool.spec.providerIDList` being not set. While reconciling, the MachinePool controller will detect this and fail to reconcile. The log message `failed to retrieve data from infrastructure provider for MachinePool %q in namespace %q` is printed instead. If the field is set to an empty slice, the reconcile does not continue either and instead wait for `externalReadyWait` (30s) until reconciliation is attempted next: https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/internal/controllers/machinepool_controller_phases.go#L275..L282

Further down the reconciliation there's also a reconciliation failure when `Status.Replicas == 0`. I believe this is the same case and should also result in a successful reconiliation. 

**What did you expect to happen:**
Scaling to zero is working as expected and updates the MachinePool status accordingly. 

**Anything else you would like to add:**
I'd propose to treat the behaviour of an empty `providerIDList` or an unset `providerIDList` the same and allow it instead of failing the reconciliation. I could imagine that there is still a condition to allow it only when `replicas = 0`, but I'm not sure if that's necessary. 

**Environment:**

- Cluster-api version: latest master (f8f65832c2291e1578bc1ced1a0739e8f5a3093e at this point)
- Minikube/KIND version:  KIND 0.11.1
- Kubernetes version: (use `kubectl version`): 1.21.1
- OS (e.g. from `/etc/os-release`):

/kind bug
/area provider/aws
/area operator

(I'm not so sure about those areas, sorry about that :))

### PR DESCRIPTION
**Pull request by mweibel**
**What this PR does / why we need it**:
to enable scaling a MachinePool to zero, an empty or not set
providerIDList should be considered valid.
additionally, Replicas 0 of the infrastructure MachinePool should also
be considered valid.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6210

This issue is required for kubernetes-sigs/cluster-api-provider-aws#3242 to be fixable.

### CODE REVIEW

File: test/framework/machinepool_helpers.go [hunk 1]
```diff
@@ -57,19 +57,19 @@ func GetMachinePoolsByCluster(ctx context.Context, input GetMachinePoolsByCluste
 	return mps
 }
 
-// WaitForMachinePoolNodesToExistInput is the input for WaitForMachinePoolNodesToExist.
-type WaitForMachinePoolNodesToExistInput struct {
+// WaitForMachinePoolNodesInput is the input for WaitForMachinePoolNodes.
```
Comment (killianmuldoon) [inline test/framework/machinepool_helpers.go:60]: Is there a need to change these method names as part of this change? It would be good to avoid the churn for consumers of this package if we could.

File: exp/internal/controllers/machinepool_controller_phases_test.go [hunk 2]
```diff
@@ -893,6 +893,87 @@ func TestReconcileMachinePoolInfrastructure(t *testing.T) {
 				g.Expect(m.Status.InfrastructureReady).To(BeFalse())
 			},
 		},
+		{
```
Comment (killianmuldoon) [inline exp/internal/controllers/machinepool_controller_phases_test.go:896]: Could we add additional scale to zero, scale from zero tests in this file?

**Review by killianmuldoon — COMMENTED** [review]
I'm not really familiar with the MachinePool code, just a couple of ideas below on tests. This change is breaking, but as MachinePools are in /exp I don't think that's a real issue.

File: test/framework/machinepool_helpers.go (hunk 1 above)
Comment (mweibel) [reply test/framework/machinepool_helpers.go:60]: no, there's not a real need. The name just doesn't really match in case of scaling to zero. It initially confused me when I started looking at that code, that's why I renamed it. 
I agree though, this creates churn for consumers of this package.

File: exp/internal/controllers/machinepool_controller_phases.go [hunk 3]
```diff
@@ -287,8 +284,10 @@ func (r *MachinePoolReconciler) reconcileInfrastructure(ctx context.Context, clu
 		if err != util.ErrUnstructuredFieldNotFound {
 			return ctrl.Result{}, errors.Wrapf(err, "failed to retrieve replicas from infrastructure provider for MachinePool %q in namespace %q", mp.Name, mp.Namespace)
 		}
-	} else if mp.Status.Replicas == 0 {
-		log.Info("Retrieved unset Status.Replicas from infrastructure provider")
+	}
+
+	if len(providerIDList) == 0 && mp.Status.Replicas != 0 {
+		log.Info("Retrieved empty Spec.ProviderIDList from infrastructure provider but Status.Replicas is not zero.", "replicas", mp.Status.Replicas)
```
Comment (fabriziopandini) [inline exp/internal/controllers/machinepool_controller_phases.go:290]: I'm not sure we should log this, given that I expect this being a normal condition while machine are bootstrapping

**Comment by killianmuldoon** [comment]
>@killianmuldoon which part is breaking? Which should make sure this is called out in release notes and PR description.

Correct me if I'm wrong, but I thought this was breaking behavioural change, (along with some changes in the test package that are now removed) given that it makes scaling to zero possible, and makes zero a valid value in MachinePool replicas. Given MachinePools are experimental it's not an issue, though I think it would be a good idea to add documentation for this to the migration guide.

File: exp/internal/controllers/machinepool_controller_phases_test.go (hunk 2 above)
Comment (Jont828) [reply exp/internal/controllers/machinepool_controller_phases_test.go:896]: I'm also curious what happens if you scale to zero and try to scale back up. It would be good to double check that it doesn't enter an invalid state.

File: exp/internal/controllers/machinepool_controller_phases.go [hunk 4]
```diff
@@ -274,11 +274,8 @@ func (r *MachinePoolReconciler) reconcileInfrastructure(ctx context.Context, clu
 
 	var providerIDList []string
 	// Get Spec.ProviderIDList from the infrastructure provider.
-	if err := util.UnstructuredUnmarshalField(infraConfig, &providerIDList, "spec", "providerIDList"); err != nil {
+	if err := util.UnstructuredUnmarshalField(infraConfig, &providerIDList, "spec", "providerIDList"); err != nil && !errors.Is(err, util.ErrUnstructuredFieldNotFound) {
```
Comment (Jont828) [inline exp/internal/controllers/machinepool_controller_phases.go:277]: Is there a case where we could get a `util.ErrUnstructuredFieldNotFound` from an actual error, i.e. we expect a `providerIDList`, but it gets suppressed here?

**Comment by sbueringer** [comment]
I think additionally making it possible to have `0` replicas (if I understood it correctly), is not a breaking change as it just extends the functionality.

I think otherwise almost every behavior change would be a breaking change.

File: exp/internal/controllers/machinepool_controller_phases.go (hunk 4 above)
Comment (mweibel) [reply exp/internal/controllers/machinepool_controller_phases.go:277]: Looking at the [AWS implementation](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/exp/controllers/awsmachinepool_controller.go#L273) and the [Azure implementation](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d0b9621c43faca25266182fcfdcf585079688f06/azure/scope/machinepool.go#L222), the `providerIDList` should always be set if there are any instances in the respective pool implementation. 
`providerIDList` is in both cases marked with the JSON tag `,omitempty` so an empty list will result in the field being not set. 

The `util.UnstructuredUnmarshalField()` implementation returns `util.ErrUnstructuredFieldNotFound` only in the following cases:
1. infrastructure object contains no `spec` or is not a map
2. infrastructure object contains no `spec.providerIDList` or `spec.providerIDList` is nil

Considering this, I'd say this check should be ok. #1 might be an issue but then the infrastructure provider implementation has an issue. 

Bear in mind: I'm new to this whole codebase - correct me if I'm wrong please :)

File: exp/internal/controllers/machinepool_controller_phases.go (hunk 3 above)
Comment (mweibel) [reply exp/internal/controllers/machinepool_controller_phases.go:290]: I'm not sure about this, the provider implementations ([AWS](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/exp/controllers/awsmachinepool_controller.go#L273), [Azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d0b9621c43faca25266182fcfdcf585079688f06/azure/scope/machinepool.go#L222)) usually update `status.replicas` and `providerIDList` at the same time. 

Looking at the Azure implementation specificly: during instance boot, `len(providerIDList)` would be greater zero but `Status.Replicas == 0` and therefore wouldn't enter the condition.

File: exp/internal/controllers/machinepool_controller_phases_test.go (hunk 2 above)
Comment (mweibel) [reply exp/internal/controllers/machinepool_controller_phases_test.go:899]: thanks for the idea - I added another test (see below in the file) which tests the scale up & down scenarios. 
Indeed I catched a bug with this and had to adjust the noderef reconciler slightly. When scaling to zero the last node also needs to be deleted, and one condition there prevented that.

**Comment by sbueringer** [comment]
Not an expert on MachinePools so I leave that to other folks

> I'm not sure how the usual review process here goes. I tried to respond to all feedback but didn't resolve the conversation yet because I was unsure if the respective feedback authors would consider it resolved.

My take is: After fixing findings, I usually only resolve conversations as a PR author if they are trivial fixes. In other cases I leave them open so that reviewers can confirm if the findings are resolved (by answering on the conversation or 👍 ). After I got that feedback or if I think it's resolved and I didn't get feedback for a while, I resolve the conversations.

Additional info: Afaik only PR authors and CAPI maintainers (with write or admin access to the repo) have the rights to resolve conversations. So reviewers usually can't do that.

**Comment by mweibel** [comment]
this is ready for another review @CecileRobertMichon @fabriziopandini @killianmuldoon @Jont828. Thanks :)

File: exp/internal/controllers/machinepool_controller_noderef.go [hunk 5]
```diff
@@ -68,7 +68,7 @@ func (r *MachinePoolReconciler) reconcileNodeRefs(ctx context.Context, cluster *
 	log = log.WithValues("cluster", cluster.Name)
 
 	// Check that the MachinePool has valid ProviderIDList.
-	if len(mp.Spec.ProviderIDList) == 0 {
+	if len(mp.Spec.ProviderIDList) == 0 && (mp.Spec.Replicas == nil || *mp.Spec.Replicas != 0) {
```
Comment (fabriziopandini) [inline exp/internal/controllers/machinepool_controller_noderef.go:71]: I'm not sure I fully understand `&& (mp.Spec.Replicas == nil || *mp.Spec.Replicas != 0)`.
is the intent to log the message in all the cases except when replicas are zero?

**Review by fabriziopandini — COMMENTED** [review]
I'm ok with the changes (a pending question, not blocking)
I'll defer to @CecileRobertMichon approval
/lgtm

File: exp/internal/controllers/machinepool_controller_noderef.go (hunk 5 above)
Comment (mweibel) [reply exp/internal/controllers/machinepool_controller_noderef.go:71]: yeah exactly. When ProviderIDList is non-empty and replicas > 0, this will log. That's probably still interesting information because if that stays for a while something is off with the ProviderIDList of the infra provider. 

Before the change, when scaling to zero this would log always, so I had to adjust it.

Comment (fabriziopandini) [reply exp/internal/controllers/machinepool_controller_noderef.go:71]: Thanks for clarifying

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve
