### PR TITLE
Fixed nil pointer crash in machine deployment controller

### LINKED ISSUE #614: machineDeployment controller panics when annotations of an existing deployment are edited
Steps to recreate

1. Create a MachineDeployment (as long as #599 is not in, you need to provide `Strategy` and `MinReadySeconds`)
2. Add or edit annotations

```
E1203 17:06:33.957429   62609 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/rolling.go:68
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/rolling.go:40
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go:180
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0xf8c3c1]

goroutine 191 [running]:
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x10bf400, 0x1ddc530)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*ReconcileMachineDeployment).reconcileNewMachineSet(0xc00063a1e0, 0xc0000b2c38, 0x1, 0x1, 0x0, 0xc000177c00, 0x0, 0x1)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/rolling.go:68 +0x41
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*ReconcileMachineDeployment).rolloutRolling(0xc00063a1e0, 0xc000177c00, 0xc0005d0a98, 0x1, 0x1, 0xc0003663f0, 0x0, 0x0)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/rolling.go:40 +0x136
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*ReconcileMachineDeployment).Reconcile(0xc00063a1e0, 0xc000685a09, 0x7, 0xc0008fd9c0, 0x14, 0x4, 0x0, 0x0, 0x0)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go:180 +0x580
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003326e0, 0x0)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207 +0x140
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x36
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000300b60)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000300b60, 0x3b9aca00, 0x0, 0x1ded801, 0xc000480e40)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000300b60, 0x3b9aca00, 0xc000480e40)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:156 +0x357
```

### PR DESCRIPTION
**Pull request by chrigl**
**What this PR does / why we need it**:

In case of only updated annotations or `Spec.MinReadySeconds`,
`func (r *ReconcileMachineDeployment) getNewMachineSet` returns nil as
new MachineSet.
See
https://github.com/kubernetes-sigs/cluster-api/blob/9c0f9874a7d759a8a7d714dd9073947eca53bb24/pkg/controller/machinedeployment/sync.go#L107

But the rest of the code in `rolloutRolling` expects to work on a real
newMS. So just leving `rolloutRolling` in case `newMS == nil`.
 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #614 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

File: pkg/controller/machinedeployment/rolling.go [hunk 1]
```diff
@@ -34,6 +34,9 @@ func (r *ReconcileMachineDeployment) rolloutRolling(d *v1alpha1.MachineDeploymen
 	if err != nil {
 		return err
 	}
+	if newMS == nil {
```
Comment (vincepri) [inline pkg/controller/machinedeployment/rolling.go]: Can we add a comment here explaining when `newMS` is supposed to be nil and why?

Comment (roberthbailey) [reply pkg/controller/machinedeployment/rolling.go]: Does this imply that changes to annotations / minreadyseconds are applied retroactively to the old machine set?

Comment (chrigl) [reply pkg/controller/machinedeployment/rolling.go]: Yes.
See https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/machinedeployment/sync.go#L109

Callstack:
```
(dlv) stack
0  0x00000000013e6930 in sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*ReconcileMachineDeployment).getNewMachineSet
   at /go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/sync.go:109
1  0x00000000013e6667 in sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*ReconcileMachineDeployment).getAllMachineSetsAndSyncRevision
   at /go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/sync.go:75
2  0x00000000013e3752 in sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*ReconcileMachineDeployment).rolloutRolling
   at /go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/rolling.go:33
3  0x00000000013e1bc2 in sigs.k8s.io/cluster-api/pkg/controller/machinedeployment.(*ReconcileMachineDeployment).Reconcile
   at /go/src/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go:182
```

**Comment by chrigl** [comment]
/test pull-cluster-api-test
Because "works on my machine"

**Comment by vincepri** [comment]
@chrigl It's a flaky test, which we should probably fix at some point 😄
