### PR TITLE
🐛 Machine deletion: try up to 10s to delete the Node, then move on

### LINKED ISSUE #1446: Machine deletion: try up to n times to delete the Node, then move on
**What steps did you take and what happened:**
1. Do something catastrophic such as manually deleting a CAPA cluster's ELB
1. `kubectl delete machine/foo`
1. Error in the logs (note, this is from v1alpha1, but the issue is still in v1alpha2):
```
I0814 17:10:39.243788       1 instances.go:67] [machine-actuator]/cluster.k8s.io/v1alpha1/4d95faba9cb7ee388671ac3cef6ee79b39c25f15/bf038fa5/worker-bf038fa5-nodepool-bf038fa5default-6c86565b8rvqdh "level"=2 "msg"="Looking for existing machine instance by tags"  
I0814 17:10:39.288157       1 machine_controller.go:181] Deleting node "ip-10-0-0-20.us-west-2.compute.internal" for machine "worker-bf038fa5-nodepool-bf038fa5default-6c86565b8rvqdh"
E0814 17:10:39.301721       1 machine_controller.go:183] Error deleting node "ip-10-0-0-20.us-west-2.compute.internal" for machine "worker-bf038fa5-nodepool-bf038fa5default-6c86565b8rvqdh": Delete 
https://bf038fa5-apiserver-261840232.us-west-2.elb.amazonaws.com:6443/api/v1/nodes/ip-10-0-0-20.us-west-2.compute.internal
: dial tcp: lookup bf038fa5-apiserver-261840232.us-west-2.elb.amazonaws.com
on 10.96.0.10:53: no such host
```
1. The Machine is never deleted

**What did you expect to happen:**
This error shouldn't block Machine deletion

**Anything else you would like to add:**
I think it would be reasonable to attempt to delete the Node multiple times over the span of 30-60 seconds. If the deletion fails, we can record an Event, then allow the Machine deletion to continue.

**Environment:**

- Cluster-api version: v0.1.x and v0.2.x

/kind bug

xref https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1084#issuecomment-530840269 and my next comment as well

### PR DESCRIPTION
**Pull request by tahsinrahman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1446

### CODE REVIEW

File: controllers/machine_controller.go [hunk 1]
```diff
@@ -183,9 +185,15 @@ func (r *MachineReconciler) reconcileDelete(ctx context.Context, cluster *cluste
 		}
 	} else {
 		klog.Infof("Deleting node %q for machine %q", m.Status.NodeRef.Name, m.Name)
-		if err := r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
-			klog.Errorf("Error deleting node %q for machine %q: %v", m.Status.NodeRef.Name, m.Name, err)
-			return ctrl.Result{}, err
+		err = wait.PollImmediate(time.Second*2, time.Second*10, func() (bool, error) {
```
Comment (vincepri) [inline controllers/machine_controller.go]:
```suggestion
		err = wait.PollImmediate(2*time.Second, 10*time.Second, func() (bool, error) {
```

Super nit, for readability, it'll read as "2 seconds" and "10 seconds"

File: controllers/machine_controller.go [hunk 2]
```diff
@@ -183,9 +185,15 @@ func (r *MachineReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
+			if err := r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
+				r.Log.Error(err, "Error deleting node", "node", m.Status.NodeRef.Name, "machine", m.Name)
+				return false, nil
+			}
+			return true, nil
+		})
+		if err != nil {
+			r.Log.Error(err, "Timed out deleting node, moving on", "node", m.Status.NodeRef.Name, "machine", m.Name)
```
Comment (vincepri) [inline controllers/machine_controller.go]:
```suggestion
			r.Log.Error(err, "timed out deleting Machine's node, moving on", "node", m.Status.NodeRef.Name, "machine", m.Name)
```

File: controllers/machine_controller.go [hunk 3]
```diff
@@ -183,9 +185,15 @@ func (r *MachineReconciler) reconcileDelete(ctx context.Context, cluster *cluste
 		}
 	} else {
 		klog.Infof("Deleting node %q for machine %q", m.Status.NodeRef.Name, m.Name)
-		if err := r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
-			klog.Errorf("Error deleting node %q for machine %q: %v", m.Status.NodeRef.Name, m.Name, err)
-			return ctrl.Result{}, err
+		err = wait.PollImmediate(time.Second*2, time.Second*10, func() (bool, error) {
+			if err := r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
+				r.Log.Error(err, "Error deleting node", "node", m.Status.NodeRef.Name, "machine", m.Name)
```
Comment (vincepri) [inline controllers/machine_controller.go]: Do we need to log this error given that we're retrying?

Comment (ncdc) [reply controllers/machine_controller.go]: No, we should only log once, at the end.

File: controllers/machine_controller.go (hunk 2 above)
Comment (ncdc) [inline controllers/machine_controller.go]: I had also suggested recording an event for this, so the user is aware.

File: controllers/machine_controller.go [hunk 4]
```diff
@@ -183,9 +185,15 @@ func (r *MachineReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
-			return ctrl.Result{}, err
+		waitErr := wait.PollImmediate(2*time.Second, 10*time.Second, func() (bool, error) {
+			if err = r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
+				return false, nil
+			}
+			return true, nil
+		})
+		if waitErr != nil {
+			r.Log.Error(err, "timed out deleting Machine's node, moving on", "node", m.Status.NodeRef.Name, "machine", m.Name)
+			r.recorder.Eventf(m, corev1.EventTypeWarning, "FailedDelete", "timed out deleting Machine's node: %v", err)
```
Comment (ncdc) [inline controllers/machine_controller.go]:
```suggestion
			r.recorder.Eventf(m, corev1.EventTypeWarning, "FailedDeleteNode", "error deleting Machine's node: %v", err)
```

Comment (ncdc) [reply controllers/machine_controller.go]: Also we have pkg/util/record.Warnf. I think @vincepri wants to move to using that everywhere (right?).

Comment (vincepri) [reply controllers/machine_controller.go]: Possibly, yeah

File: controllers/machine_controller.go [hunk 5]
```diff
@@ -183,9 +185,15 @@ func (r *MachineReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
-			klog.Errorf("Error deleting node %q for machine %q: %v", m.Status.NodeRef.Name, m.Name, err)
-			return ctrl.Result{}, err
+		waitErr := wait.PollImmediate(2*time.Second, 10*time.Second, func() (bool, error) {
+			if err = r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
+				return false, nil
+			}
+			return true, nil
+		})
+		if waitErr != nil {
+			r.Log.Error(err, "timed out deleting Machine's node, moving on", "node", m.Status.NodeRef.Name, "machine", m.Name)
```
Comment (detiber) [inline controllers/machine_controller.go]: Is the machine name needed here in the log message? Shouldn't the logger already be configured with the machine name using WithValues at this point?

Comment (ncdc) [reply controllers/machine_controller.go]: Should be, but there's a bug in the code :-(

https://github.com/kubernetes-sigs/cluster-api/blob/90cbdd174b1753926e26ef1393356d030139e176/controllers/machine_controller.go#L78

Comment (detiber) [reply controllers/machine_controller.go]: :grimacing:

Comment (tahsinrahman) [reply controllers/machine_controller.go]: I'm now working on https://github.com/kubernetes-sigs/cluster-api/issues/1203
lets fix this on that pr?

Comment (ncdc) [reply controllers/machine_controller.go]: SGTM. Please add a TODO in this PR to remove the machine from this line

File: controllers/machine_controller.go [hunk 6]
```diff
@@ -183,9 +185,15 @@ func (r *MachineReconciler) reconcileDelete(ctx context.Context, cluster *cluste
 		}
 	} else {
 		klog.Infof("Deleting node %q for machine %q", m.Status.NodeRef.Name, m.Name)
-		if err := r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
-			klog.Errorf("Error deleting node %q for machine %q: %v", m.Status.NodeRef.Name, m.Name, err)
-			return ctrl.Result{}, err
+		waitErr := wait.PollImmediate(2*time.Second, 10*time.Second, func() (bool, error) {
+			if err = r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
+				return false, nil
```
Comment (ncdc) [inline controllers/machine_controller.go]: Maybe we should record the error as `deleteNodeErr` and report that back to the user in the event instead of `waitErr` (I fear `waitErr` will be "timed out waiting for condition")?

Comment (tahsinrahman) [reply controllers/machine_controller.go]: yes, `waitErr` will be "timed out waiting for condition"
do you mean doing this `deleteNodeErr = r.deleteNode` ? and keeping waitErr as it is?

File: controllers/machine_controller.go [hunk 7]
```diff
@@ -183,9 +185,18 @@ func (r *MachineReconciler) reconcileDelete(ctx context.Context, cluster *cluste
 		}
 	} else {
 		klog.Infof("Deleting node %q for machine %q", m.Status.NodeRef.Name, m.Name)
-		if err := r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
-			klog.Errorf("Error deleting node %q for machine %q: %v", m.Status.NodeRef.Name, m.Name, err)
-			return ctrl.Result{}, err
+
+		var deleteNodeErr error
+		err = wait.PollImmediate(2*time.Second, 10*time.Second, func() (bool, error) {
+			if deleteNodeErr = r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
```
Comment (detiber) [inline controllers/machine_controller.go]: you are assigning to `deleteNodeErr` and then testing against `err`

File: controllers/machine_controller.go [hunk 8]
```diff
@@ -183,9 +185,18 @@ func (r *MachineReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
+				return false, nil
+			}
+			return true, nil
+		})
+		if deleteNodeErr != nil {
```
Comment (detiber) [inline controllers/machine_controller.go]: Won't this also trigger if apierrors.IsNotFound(deleteNodeErr) is true giving a false error?

File: controllers/machine_controller.go (hunk 7 above)
Comment (tahsinrahman) [reply controllers/machine_controller.go]: thanks! fixed

File: controllers/machine_controller.go (hunk 8 above)
Comment (tahsinrahman) [reply controllers/machine_controller.go]: thanks! fixed

File: controllers/machine_controller.go [hunk 9]
```diff
@@ -183,9 +185,18 @@ func (r *MachineReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
+		waitErr := wait.PollImmediate(2*time.Second, 10*time.Second, func() (bool, error) {
+			if deleteNodeErr = r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); deleteNodeErr != nil && !apierrors.IsNotFound(deleteNodeErr) {
+				return false, nil
+			}
+			return true, nil
+		})
+		if waitErr != nil {
+			// TODO: remove m.Name after #1203
+			r.Log.Error(deleteNodeErr, "timed out deleting Machine's node, moving on", "node", m.Status.NodeRef.Name, "machine", m.Name)
+			r.recorder.Eventf(m, corev1.EventTypeWarning, "FailedDeleteNode", "error deleting Machine's node: %v", deleteNodeErr)
```
Comment (ncdc) [inline controllers/machine_controller.go]: I assume the answer is "no" but it's worth asking: the if condition here is a non-nil waitErr. Is there a chance that waitErr is not nil, but deleteNodeErr is nil (since we're including deleteNodeErr in the event)?

Comment (tahsinrahman) [reply controllers/machine_controller.go]: no, if waitErr is not nil, deleteNodeErr will definitely not-nil
if deleteNodeErr is nil, then conditionFunc will return true and waitErr will be nil

**Comment by ncdc** [comment]
/lgtm
/assign @vincepri @detiber 
for final review

**Comment by vincepri** [comment]
Whoops thanks, I assumed you approved without looking :D

**Comment by ncdc** [comment]
No, mistake on my part. I meant to /approve and then assign to you.
