### PR TITLE
🐛 KCP should set a timeout when trying to connect to remote cluster

### LINKED ISSUE #2705: KCP deferred updates stall cluster deletion
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Delete a cluster

Cluster deletion stalls on KCP, which shows 1 node ready despite the lack of an underlying infrastructure object.

Attempts at debugging showed:
```
E0318 13:34:17.428638       1 kubeadm_control_plane_controller.go:175] controllers/KubeadmControlPlane "msg"="Failed to update KubeadmControlPlane Status" "error"="failed to create remote cluster client: failed to create client for Cluster default/cluster-vsphere-20200318140259: Get https://192.168.102.134:6443/api?timeout=32s: EOF" "cluster"="cluster-vsphere-20200318140259" "kubeadmControlPlane"="cluster-vsphere-20200318140259" "namespace"="default"
E0318 13:34:17.451325       1 kubeadm_control_plane_controller.go:181] controllers/KubeadmControlPlane "msg"="Failed to patch KubeadmControlPlane" "error"="kubeadmcontrolplanes.controlplane.cluster.x-k8s.io \"cluster-vsphere-20200318140259\" not found" "cluster"="cluster-vsphere-20200318140259" "kubeadmControlPlane"="cluster-vsphere-20200318140259" "namespace"="default"
E0318 13:34:17.451432       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="[failed to create remote cluster client: failed to create client for Cluster default/cluster-vsphere-20200318140259: Get https://192.168.102.134:6443/api?timeout=32s: EOF, kubeadmcontrolplanes.controlplane.cluster.x-k8s.io \"cluster-vsphere-20200318140259\" not found]"  "controller"="kubeadmcontrolplane" "request"={"Namespace":"default","Name":"cluster-vsphere-20200318140259"}
```

Believe the issue is that during reconciliation, there is a deferred cluster status update, which attempts to get node status from the workload cluster despite it no longer existing. This is compounded in CAPV because HAProxy has a long timeout, and at the time the deferred operations occur, HAProxyLoadBalancer has not yet removed the endpoints.

A timeout should be added to the `RESTConfig` for the remote cluster, and as a further optimisation, the cluster status update should be skipped in the presence of a deletion timestamp.

**What did you expect to happen:**
The cluster to be deleted

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.3.1
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

/kind bug
/priority critical-urgent

### PR DESCRIPTION
**Pull request by frapposelli**
**What this PR does / why we need it**:

Adds a restConfig timeout to 10 seconds to avoid getting stuck when deleting a self-managed cluster

Fixes #2705

### CODE REVIEW

File: controlplane/kubeadm/internal/cluster.go [hunk 1]
```diff
@@ -70,6 +71,7 @@ func (m *Management) GetWorkloadCluster(ctx context.Context, clusterKey client.O
 	// TODO(chuckha): Inject this dependency.
 	// TODO(chuckha): memoize this function. The workload client only exists as long as a reconciliation loop.
 	restConfig, err := remote.RESTConfig(ctx, m.Client, clusterKey)
+	restConfig.Timeout = 30 * time.Second
```
Comment (vincepri) [inline controlplane/kubeadm/internal/cluster.go]: Note that this timeout seems to be only used for etcd client generator, the `remote.NewClusterClient` still has no timeout set

cc @yastij @randomvariable

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go [hunk 2]
```diff
@@ -170,17 +170,22 @@ func (r *KubeadmControlPlaneReconciler) Reconcile(req ctrl.Request) (res ctrl.Re
 				reterr = nil
 			}
 		}
-		// Always attempt to update status.
-		if err := r.updateStatus(ctx, kcp, cluster); err != nil {
-			logger.Error(err, "Failed to update KubeadmControlPlane Status")
-			reterr = kerrors.NewAggregate([]error{reterr, err})
+
+		// If we don't have a DeletionTimestamp set, we try to update status
+		if kcp.ObjectMeta.DeletionTimestamp.IsZero() {
```
Comment (vincepri) [inline controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: I'd move this check inside `updateStatus` on 325-ish, right before `GetWorkloadCluster` call

**Comment by vincepri** [comment]
This should be ready to go
