### PR TITLE
📖 Remove example from --runtime-extension flag in clusterctl

### LINKED ISSUE #9796: Remove example from --runtime-extension flag in clusterctl
The `clusterctl` help text for the `--runtime-extension` options provides [an example](https://github.com/cahillsf/cluster-api/blob/aacbbc780a42363b28c232cccc87bfecd816df0b/cmd/clusterctl/cmd/init.go#L106C2-L106C2):
`Runtime extension providers and versions (e.g. test:v0.0.1) to add to the management cluster.`

Applying this option and example param results in the following error:
`Error: failed to get configuration for the RuntimeExtensionProvider with name test. Please check the provider name and/or add configuration for new providers using the .clusterctl config`

### PR DESCRIPTION
**Pull request by avaneesh634**
**What this PR does / why we need it**:
Remove example from --runtime-extension flag in clusterctl as clusterctl doesn't include any default runtime extensions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9796 

/area documentation

### CODE REVIEW

**Comment by avaneesh634** [comment]
@fabriziopandini 
@sbueringer

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

File: cmd/clusterctl/cmd/init.go [hunk 1]
```diff
@@ -105,7 +105,7 @@ func init() {
 	initCmd.PersistentFlags().StringSliceVar(&initOpts.ipamProviders, "ipam", nil,
 		"IPAM providers and versions (e.g. infoblox:v0.0.1) to add to the management cluster.")
 	initCmd.PersistentFlags().StringSliceVar(&initOpts.runtimeExtensionProviders, "runtime-extension", nil,
-		"Runtime extension providers and versions (e.g. test:v0.0.1) to add to the management cluster.")
+		"Runtime extension providers and versions to add to the management cluster; please note that the clusterctl doesn't include any default runtime extensions and thus it is required to use custom configuration files to register runtime extensions.")
```
Comment (sbueringer) [inline cmd/clusterctl/cmd/init.go:108]:
```suggestion
		"Runtime extension providers and versions to add to the management cluster; please note that clusterctl doesn't include any default runtime extensions and thus it is required to use custom configuration files to register runtime extensions.")
```

**Comment by sbueringer** [comment]
Thx!

/approve
