### PR TITLE
🐛 Carry over metadata.uid at ServerSidePatchHelper

### LINKED ISSUE #6741: Topology controller reconciliation has race conditions which may lead to not expected creation or updates on objects.
**What steps did you take and what happened:**

The topology controller has the following two race conditions at his reconciliation loop for in-place patches (template rotation is not affected) since switching to server side apply:

1. Recreates object which got deleted
  * Topology Controller reconciler starts reconciliation
  * While it is reconciling and before object X gets applied, an external application/user deletes the object
  * Topology Controller reaches the server side apply patch command, which will recreate the object while using an outdated original scope
    * The issue here is it may use outdated data depending on the not anymore existing object and thus may set wrong conditions or other values
    * It may also prevent the deletion of a ClusterClass, because e.g. it recreates the Cluster object (while only wanting to patch it)
2. Updates object which got recreated
  * Topology Controller starts reconciliation
  * While it is reconciling and before boject X gets applied, an external application/user recreates the object
  * Topology Controller reaches the server side apply patch command, which will update the object while using an outdated original scope
    * The issue here is it may use outdated data depending on the recreated object and thus may set wrong conditions or other values.

**What did you expect to happen:**

An error occurs notifying that it can't:
* update the object because it does not exist anymore (no object having the same `metadata.uid`
* update the object because it is not the same anymore (changed `metadata.uid`

**Anything else you would like to add:**

This cases got hit while implementing #6710 in integration tests.

**Environment:**

- Cluster-api version: main
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
/area topology

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

This prevents the race condition of running server side apply on an object which got:

* deleted in the meantime
* recreated in the meantime

and the topology controller won't apply using outdated information anymore.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6741

### CODE REVIEW

File: internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go [hunk 1]
```diff
@@ -193,5 +198,5 @@ func cleanupLegacyManagedFields(obj *unstructured.Unstructured, c client.Client)
 
 	obj.SetManagedFields(managedFields)
 
-	return c.Patch(context.TODO(), obj, client.MergeFrom(base))
+	return c.Patch(ctx, obj, client.MergeFrom(base))
```
Comment (chrischdi) [inline internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go:201]:
```suggestion
	return c.Patch(context.TODO(), obj, client.MergeFrom(base))
```

File: internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go [hunk 2]
```diff
@@ -135,6 +139,7 @@ func (h *serverSidePatchHelper) Patch(ctx context.Context) error {
 	log := ctrl.LoggerFrom(ctx)
 	log.V(5).Info("Patching object", "Intent", h.modified)
 
+	h.modified.SetUID(h.originalUID)
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go:142]: I assume we don't have to set it in allowedPaths (like e.g. metadata.name) as we simply don't set it before running through the diff logic

Comment (chrischdi) [reply internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go:142]: Exactly, especially we have to carry it over somewhere from the original (if not nil) to the modified, because modified is often computed.

[the remark this answers is not in the document]
Comment (sbueringer) [reply internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go:142]: I think we should be able to do this in l.67 like this
```go
		modified.SetUID(original.GetUID())
```

Alternatively we could do it in desired_state.go whenever we compute the new objects.

Might be were it rather belongs

File: internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go [hunk 3]
```diff
@@ -50,6 +50,8 @@ func NewServerSidePatchHelper(original, modified client.Object, c client.Client,
 		{"kind"},
 		{"metadata", "name"},
 		{"metadata", "namespace"},
+		// uid is optional for a server side apply intent but sets the expectation of an object getting created or a specific one updated.
+		{"metadata", "uid"},
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go:54]: Do we still need this?

**Review by sbueringer — COMMENTED** [review]
lgtm one nit
except if we want to move it to desired_state, but for me it's fine where it is

File: internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go (hunk 3 above)
Comment (chrischdi) [reply internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go:54]: Yes, it is required, otherwise it gets filters out and we would always set it to empty.

I preferred to add it here to only work on the filtered unstructured objects to have an easier nil check.

**Comment by chrischdi** [comment]
> lgtm one nit except if we want to move it to desired_state, but for me it's fine where it is

The issue with desired_state is: we don't know if we want to update (in-place -> keep uid) or recreate (template rotation -> no uid) the object.

File: internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go (hunk 3 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/structuredmerge/serversidepathhelper.go:54]: How does it get filtered out given that we use the helperOptions in filterObject only before we set the uid?

**Comment by sbueringer** [comment]
> > lgtm one nit except if we want to move it to desired_state, but for me it's fine where it is
> 
> The issue with desired_state is: we don't know if we want to update (in-place -> keep uid) or recreate (template rotation -> no uid) the object.

Ah good point / reason to keep it as is

**Comment by sbueringer** [comment]
/hold

Let's see if it is a new flake
/test pull-cluster-api-test-main

**Comment by chrischdi** [comment]
Flaky test will be fixed via #6738 

/test pull-cluster-api-test-main

**Comment by chrischdi** [comment]
We'll have to wait for #6773 to merge first. Afterwards this one should turn green.

**Comment by sbueringer** [comment]
Rebased as #6773 has been merged

**Comment by sbueringer** [comment]
/lgtm

But let's keep the hold to run the tests a few times to make sure we're not introducing flakes

**Comment by sbueringer** [comment]
Looks pretty stable

/approve
