### PR TITLE
🌱 MinReadySeconds for machinepools

### LINKED ISSUE #8952: MachinePool: MinReadySeconds does not work
### What steps did you take and what happened?

MachinePool has a MinReadySeconds field just like MachineDeployment. In MachinePools however it is not implemented.

### What did you expect to happen?

I would expect it to behave as documented:

```go
	// Minimum number of seconds for which a newly created machine instances should
	// be ready.
	// Defaults to 0 (machine instance will be considered available as soon as it
	// is ready)
	// +optional
	MinReadySeconds *int32 `json:"minReadySeconds,omitempty"`
```

### Cluster API version

main

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by Dhairya-Arora01**
**What this PR does / why we need it**: Making MinReadySeconds work in machinepools

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8952 

/area machinepool

### CODE REVIEW

File: exp/internal/controllers/machinepool_controller_noderef.go [hunk 1]
```diff
@@ -184,9 +186,11 @@ func (r *MachinePoolReconciler) getNodeReferences(ctx context.Context, c client.
 			continue
 		}
 		if node, ok := nodeRefsMap[providerID]; ok {
-			available++
 			if nodeIsReady(&node) {
 				ready++
+				if noderefutil.IsNodeAvailable(&node, *minReadySeconds, metav1.Now()) {
+					available++
+				}
```
Comment (vincepri) [inline exp/internal/controllers/machinepool_controller_noderef.go:193]: This changes the behavior, now we're defining an available node as a ready node first; is that on purpose?

Comment (Dhairya-Arora01) [reply exp/internal/controllers/machinepool_controller_noderef.go:193]: Ohh.... i think i have followed similar pattern as that of machinesets https://github.com/kubernetes-sigs/cluster-api/blob/07cd79e65f76a70e721329d7b99ea9fd8674e6a7/internal/controllers/machineset/machineset_controller.go#L889-L893

Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_noderef.go:193]: It is a change in behavior but in my opinion it is a bugfix.

MachinePool API

```go
	// The number of available replicas (ready for at least minReadySeconds) for this MachinePool.
	// +optional
	AvailableReplicas int32 `json:"availableReplicas,omitempty"`
```

MachineDeployment API

```go
	// Total number of available machines (ready for at least minReadySeconds)
	// targeted by this deployment.
	// +optional
	AvailableReplicas int32 `json:"availableReplicas"`
```
(In MachineDeployments it is actually implemented as documented)

In my opinion the AvailableReplicas fields only make sense if they are not identical to the ReadyReplicas field.

**Comment by fabriziopandini** [comment]
sgtm from my side, but it would be great if @CecileRobertMichon or @Jont828 or someone from the team could take a look

**Comment by jackfrancis** [comment]
/assign @willie-yao

Willie could you take a pass at a review?

File: exp/internal/controllers/machinepool_controller_noderef_test.go [hunk 2]
```diff
@@ -181,7 +182,7 @@ func TestMachinePoolGetNodeReference(t *testing.T) {
 		t.Run(test.name, func(t *testing.T) {
 			g := NewWithT(t)
 
-			result, err := r.getNodeReferences(ctx, client, test.providerIDList)
+			result, err := r.getNodeReferences(ctx, client, test.providerIDList, ptr.To[int32](0))
```
Comment (willie-yao) [inline exp/internal/controllers/machinepool_controller_noderef_test.go:185]: I think it would help to add a unit test case that tests the change in behavior for `available`. It doesn't seem like any of the existing test cases check for `available` besides the empty case.

Comment (willie-yao) [reply exp/internal/controllers/machinepool_controller_noderef_test.go:185]: lgtm otherwise!

**Comment by Dhairya-Arora01** [comment]
> @Dhairya-Arora01 Do you have time to adress the open finding?

@sbueringer , sorry can you take a look now....

File: exp/internal/controllers/machinepool_controller_noderef_test.go [hunk 3]
```diff
@@ -175,13 +177,23 @@ func TestMachinePoolGetNodeReference(t *testing.T) {
 				},
 			},
 		},
+		{
+			name:           "valid provider id, valid aws node, with minReadySeconds",
+			providerIDList: []string{"aws://us-east-1/id-node-1"},
+			expected: &getNodeReferencesResult{
+				references: []corev1.ObjectReference{{Name: "node-1"}},
+				available:  0,
```
Comment (willie-yao) [inline exp/internal/controllers/machinepool_controller_noderef_test.go:185]: nit: We are already checking if available = 0 in the previous test case. Is it possible to add another test case where available > 0?

File: exp/internal/controllers/machinepool_controller_noderef.go [hunk 4]
```diff
@@ -81,7 +83,7 @@ func (r *MachinePoolReconciler) reconcileNodeRefs(ctx context.Context, cluster *
 	}
 
 	// Get the Node references.
-	nodeRefsResult, err := r.getNodeReferences(ctx, clusterClient, mp.Spec.ProviderIDList)
+	nodeRefsResult, err := r.getNodeReferences(ctx, clusterClient, mp.Spec.ProviderIDList, mp.Spec.MinReadySeconds)
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_noderef.go:86]: Let's please drop this comment from the doc of this field

```go
// NOTE: No logic is implemented for this field and it currently has no behaviour.
```

File: exp/internal/controllers/machinepool_controller_noderef_test.go [hunk 5]
```diff
@@ -175,13 +177,23 @@ func TestMachinePoolGetNodeReference(t *testing.T) {
...
+			minReadySeconds: 20,
+		},
 	}
 
 	for _, test := range testCases {
 		t.Run(test.name, func(t *testing.T) {
 			g := NewWithT(t)
 
-			result, err := r.getNodeReferences(ctx, client, test.providerIDList)
+			result, err := r.getNodeReferences(ctx, client, test.providerIDList, ptr.To[int32](int32(test.minReadySeconds)))
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_noderef_test.go:196]:
```suggestion
			result, err := r.getNodeReferences(ctx, client, test.providerIDList, ptr.To(test.minReadySeconds))
```

File: exp/internal/controllers/machinepool_controller_noderef_test.go (hunk 3 above)
Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_noderef_test.go:185]: Yeah let's do that. It should be roughly the same test case, just with minReadySeconds set to 0

It looks like we never validate the available and replica fields today. Let's start doing that (and then also fix the other test cases, they are just green because we don't check available & ready)

**Comment by sbueringer** [comment]
@Dhairya-Arora01  do you have time to address the findings above?

File: exp/internal/controllers/machinepool_controller_noderef_test.go [hunk 6]
```diff
@@ -175,13 +177,33 @@ func TestMachinePoolGetNodeReference(t *testing.T) {
...
+				available:  0,
+				ready:      1,
+			},
+			minReadySeconds: 20,
+		},
+		{
+			name:           "valid provider id, valid aws node, with minReadySeconds equals 0",
+			providerIDList: []string{"aws://us-east-1/id-node-1"},
+			expected: &getNodeReferencesResult{
+				references: []corev1.ObjectReference{{Name: "node-1"}},
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_noderef_test.go:194]: As mentioned in a previous commen. Let's start validating expected.available/ready against result (somewhere ~ in l.219)

Today this test never validates the available and ready fields.

In fact. At the moment they are always 0 because we never set conditions correclty to get ready or available Nodes. Let's change that as well.

(otherwise we don't have any test coverage for ready/available)

Comment (willie-yao) [reply exp/internal/controllers/machinepool_controller_noderef_test.go:256]: I wasn't able to follow the force-pushes but I see that the test is now validating available and ready fields based on a different minReadySeconds. That looks good!!

I think the only thing missing is a test case when the NodeReady condition is false, both ready and available should be 0.

**Review by willie-yao — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve
