### PR TITLE
🐛 clusterctl to show config provider without setting env vars

### LINKED ISSUE #2876: [clusterctl] "clusterctl config provider" fails to show AWS, VSphere, and Azure info
**What steps did you take and what happened:**

Running `clusterctl config provider --infrastructure aws ` gives the following error:

`Error: failed to perform variable substitution: value for variables [AWS_B64ENCODED_CREDENTIALS] is not set. Please set the value using os environment variables or the clusterctl config file`

**What did you expect to happen:**
I expected it to run without needing any variables similar to other providers.

/kind bug
/area clusterctl

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
- the clusterctl config provider now can show the configuration without any env vars being set
- change the code path so we don't have to replace variables as part of this informational command 

**Which issue(s) this PR fixes** 
Fixes #2876 

**Release Notes:**
 - ⚠️ ComponentsClient.Get method definition changed from `func(string, string, string) (Components, error)` to `func(ComponentsOptions) (Components, error)`
 - ⚠️ NewComponents method definition changed from `func(sigs.k8s.io/cluster-api/cmd/clusterctl/client/config.Provider, string, []byte, sigs.k8s.io/cluster-api/cmd/clusterctl/client/config.Client, string, string) (*components, error)` to `func(sigs.k8s.io/cluster-api/cmd/clusterctl/client/config.Provider, sigs.k8s.io/cluster-api/cmd/clusterctl/client/config.Client, []byte, ComponentsOptions) (*components, error)`

### CODE REVIEW

**Comment by nader-ziada** [comment]
@wfernandes @JoelSpeed when you get a chance to review this, let me know what you think about which tests are missing. thanks

File: cmd/clusterctl/client/config_test.go [hunk 1]
```diff
@@ -19,11 +19,12 @@ package client
 import (
 	"fmt"
 	"io/ioutil"
-	"k8s.io/utils/pointer"
 	"os"
 	"path/filepath"
 	"testing"
 
+	"k8s.io/utils/pointer"
```
Comment (vincepri) [inline cmd/clusterctl/client/config_test.go:26]: Move this down with the other imports

File: cmd/clusterctl/client/config_test.go [hunk 2]
```diff
@@ -168,6 +169,39 @@ func Test_clusterctlClient_GetProviderComponents(t *testing.T) {
...
+		WithPaths("root", "components.yaml").
+		WithDefaultVersion("v1.0.0").
+		WithFile("v1.0.0", "components.yaml", componentsYAML("${FOO}")).
+		WithMetadata("v1.0.0", &clusterctlv1.Metadata{
+			ReleaseSeries: []clusterctlv1.ReleaseSeries{
+				{Major: 1, Minor: 0, Contract: "v1alpha3"},
+			},
+		})
+
+		// create a fake cluster, eventually adding some existing runtime objects to it
```
Comment (vincepri) [inline cmd/clusterctl/client/config_test.go:191]: Seems the file needs to be formatted

File: cmd/clusterctl/client/repository/components_client.go [hunk 3]
```diff
@@ -47,6 +48,41 @@ func newComponentsClient(provider config.Provider, repository Repository, config
 	}
 }
 
+func (f *componentsClient) GetWithValues(version, targetNamespace, watchingNamespace string) (Components, error) {
+	log := logf.Log
+
+	// if the request does not target a specific version, read from the default repository version that is derived from the repository URL, e.g. latest.
```
Comment (vincepri) [inline cmd/clusterctl/client/repository/components_client.go:54]:
```suggestion
	// If the request does not target a specific version, read from the default repository version that is derived from the repository URL, e.g. latest.
```

File: cmd/clusterctl/client/repository/components_client.go [hunk 4]
```diff
@@ -47,6 +48,41 @@ func newComponentsClient(provider config.Provider, repository Repository, config
...
+	if version == "" {
+		version = f.repository.DefaultVersion()
+	}
+
+	// retrieve the path where the path is stored
```
Comment (vincepri) [inline cmd/clusterctl/client/repository/components_client.go:59]:
```suggestion
	// Retrieve the path where the path is stored.
```

File: cmd/clusterctl/client/repository/components_client.go [hunk 5]
```diff
@@ -47,6 +48,41 @@ func newComponentsClient(provider config.Provider, repository Repository, config
...
+	path := f.repository.ComponentsPath()
+
+	// read the component YAML, reading the local override file if it exists, otherwise read from the provider repository
```
Comment (vincepri) [inline cmd/clusterctl/client/repository/components_client.go:62]:
```suggestion
	// Read the component YAML, reading the local override file if it exists, otherwise read from the provider repository.
```

File: cmd/clusterctl/client/repository/components.go [hunk 6]
```diff
@@ -193,6 +193,25 @@ func NewComponents(provider config.Provider, version string, rawyaml []byte, con
...
+//
+// It is important to notice that clusterctl applies a set of processing steps to the “raw” component YAML read
+// from the provider repositories:
+// 1. Checks for all the variables in the component YAML file without replacing the values
+// 2. Ensure all the provider components are deployed in the target namespace (apply only to namespaced objects)
+// 3. Ensure all the ClusterRoleBinding which are referencing namespaced objects have the name prefixed with the namespace name
+// 4. Set the watching namespace for the provider controller
+// 5. Adds labels to all the components in order to allow easy identification of the provider objects
+func NewComponents(provider config.Provider, version string, rawyaml []byte, configClient config.Client, targetNamespace, watchingNamespace string) (*components, error) {
+	// inspect the yaml read from the repository for variables
```
Comment (vincepri) [inline cmd/clusterctl/client/repository/components.go:209]:
```suggestion
	// Inspect the yaml read from the repository for variables.
```

File: cmd/clusterctl/client/config_test.go [hunk 7]
```diff
@@ -168,6 +169,39 @@ func Test_clusterctlClient_GetProviderComponents(t *testing.T) {
 	}
 }
 
+func Test_getComponentsByName_withEmptyVariables(t *testing.T) {
+	g := NewWithT(t)
+
+	// create a fake config with a provider named P1 and a variable named foo
```
Comment (vincepri) [inline cmd/clusterctl/client/config_test.go:175]:
```suggestion
	// Create a fake config with a provider named P1 and a variable named foo.
```

File: cmd/clusterctl/client/config_test.go (hunk 2 above)
Comment (vincepri) [inline cmd/clusterctl/client/config_test.go:191]:
```suggestion
		// Create a fake cluster, eventually adding some existing runtime objects to it.
```

File: cmd/clusterctl/client/config_test.go [hunk 8]
```diff
@@ -168,6 +169,39 @@ func Test_clusterctlClient_GetProviderComponents(t *testing.T) {
...
+		WithMetadata("v1.0.0", &clusterctlv1.Metadata{
+			ReleaseSeries: []clusterctlv1.ReleaseSeries{
+				{Major: 1, Minor: 0, Contract: "v1alpha3"},
+			},
+		})
+
+		// create a fake cluster, eventually adding some existing runtime objects to it
+	cluster1 := newFakeCluster("cluster1", config1).WithObjs()
+
+	// create a new fakeClient that allows to execute tests on the fake config, the fake repositories and the fake cluster.
```
Comment (vincepri) [inline cmd/clusterctl/client/config_test.go:194]:
```suggestion
	// Create a new fakeClient that allows to execute tests on the fake config, 
	// the fake repositories and the fake cluster.
```

File: cmd/clusterctl/client/common.go [hunk 9]
```diff
@@ -25,6 +25,37 @@ import (
...
+		return nil, err
+	}
+
+	// gets the provider configuration (that includes the location of the provider repository)
+	providerConfig, err := c.configClient.Providers().Get(name, providerType)
+	if err != nil {
+		return nil, err
+	}
+
+	// get a client for the provider repository and read the provider components;
```
Comment (vincepri) [inline cmd/clusterctl/client/common.go:43]:
```suggestion
	// Get a client for the provider repository and read the provider components;
```

File: cmd/clusterctl/client/common.go [hunk 10]
```diff
@@ -25,6 +25,37 @@ import (
...
+// getComponentsByNameAndValue is a utility method that returns components for a given provider, targetNamespace, and watchingNamespace.
+func (c *clusterctlClient) getComponentsByNameAndValue(provider string, providerType clusterctlv1.ProviderType, targetNamespace string, watchingNamespace string) (repository.Components, error) {
+
+	// parse the abbreviated syntax for name[:version]
+	name, version, err := parseProviderName(provider)
+	if err != nil {
+		return nil, err
+	}
+
+	// gets the provider configuration (that includes the location of the provider repository)
```
Comment (vincepri) [inline cmd/clusterctl/client/common.go:37]:
```suggestion
	// Gets the provider configuration (includes the location of the provider repository).
```

File: cmd/clusterctl/client/common.go [hunk 11]
```diff
@@ -25,6 +25,37 @@ import (
 	"sigs.k8s.io/cluster-api/cmd/clusterctl/client/repository"
 )
 
+// getComponentsByNameAndValue is a utility method that returns components for a given provider, targetNamespace, and watchingNamespace.
+func (c *clusterctlClient) getComponentsByNameAndValue(provider string, providerType clusterctlv1.ProviderType, targetNamespace string, watchingNamespace string) (repository.Components, error) {
+
+	// parse the abbreviated syntax for name[:version]
```
Comment (vincepri) [inline cmd/clusterctl/client/common.go:31]:
```suggestion
	// Parse the abbreviated syntax for name[:version].
```

File: cmd/clusterctl/client/common.go [hunk 12]
```diff
@@ -25,6 +25,37 @@ import (
 	"sigs.k8s.io/cluster-api/cmd/clusterctl/client/repository"
 )
 
+// getComponentsByNameAndValue is a utility method that returns components for a given provider, targetNamespace, and watchingNamespace.
```
Comment (vincepri) [inline cmd/clusterctl/client/common.go:28]:
```suggestion
// getComponentsByNameAndValue is a utility method that returns components 
// for a given provider, targetNamespace, and watchingNamespace.
```

File: cmd/clusterctl/client/repository/components.go [hunk 13]
```diff
@@ -193,21 +193,40 @@ func NewComponents(provider config.Provider, version string, rawyaml []byte, con
...
+// NewComponents returns a new objects embedding a component YAML file
+//
+// It is important to notice that clusterctl applies a set of processing steps to the “raw” component YAML read
+// from the provider repositories:
+// 1. Checks for all the variables in the component YAML file without replacing the values
+// 2. Ensure all the provider components are deployed in the target namespace (apply only to namespaced objects)
+// 3. Ensure all the ClusterRoleBinding which are referencing namespaced objects have the name prefixed with the namespace name
+// 4. Set the watching namespace for the provider controller
+// 5. Adds labels to all the components in order to allow easy identification of the provider objects
+func NewComponents(provider config.Provider, version string, rawyaml []byte, configClient config.Client, targetNamespace, watchingNamespace string) (*components, error) {
```
Comment (wfernandes) [inline cmd/clusterctl/client/repository/components.go:208]: Suggestion: I'm wondering if we could refactor and collapse the two methods `NewComponents` and `NewComponentsWithValues` into one method takes a struct like `ComponentsInput` that contains all the required arguments and one more called `replaceVariables bool`. If `replaceVariables` is set, then we call `replaceVariables(...)`.

File: cmd/clusterctl/client/repository/components_client_test.go [hunk 14]
```diff
@@ -234,7 +234,7 @@ func Test_componentsClient_Get(t *testing.T) {
 			gs := NewWithT(t)
 
 			f := newComponentsClient(tt.fields.provider, tt.fields.repository, configClient)
-			got, err := f.Get(tt.args.version, tt.args.targetNamespace, tt.args.watchingNamespace)
```
Comment (wfernandes) [inline cmd/clusterctl/client/repository/components_client_test.go:237]: Changing this means that we don't have tests for `Get`. If we share the logic this might be fine, or we can add a test specifically for the `Get` without values? WDYT?

File: cmd/clusterctl/client/repository/components_client.go [hunk 15]
```diff
@@ -47,18 +48,53 @@ func newComponentsClient(provider config.Provider, repository Repository, config
 	}
 }
 
+func (f *componentsClient) GetWithValues(version, targetNamespace, watchingNamespace string) (Components, error) {
```
Comment (wfernandes) [inline cmd/clusterctl/client/repository/components_client.go:51]: Suggestion: 
```suggestion
type ComponentsClientInput struct {
  version, targetNamespace, watchingNamespace string
  withValues bool // Feel free to choose a more appropriate name
}
func (f *componentsClient) Get(input ComponentsClientInput) (Components, error) {
}
```
Then we can pass in the `withValues` to `NewComponents`.

Comment (wfernandes) [reply cmd/clusterctl/client/repository/components_client.go:51]: I also noticed that we are missing the godoc for these methods. Maybe we can add them in here now.

File: cmd/clusterctl/client/common.go [hunk 16]
```diff
@@ -25,22 +25,55 @@ import (
 	"sigs.k8s.io/cluster-api/cmd/clusterctl/client/repository"
 )
 
-// getComponentsByName is a utility method that returns components for a given provider, targetNamespace, and watchingNamespace.
+// getComponentsByNameAndValue is a utility method that returns components
+// for a given provider, targetNamespace, and watchingNamespace.
+func (c *clusterctlClient) getComponentsByNameAndValue(provider string, providerType clusterctlv1.ProviderType, targetNamespace string, watchingNamespace string) (repository.Components, error) {
```
Comment (wfernandes) [inline cmd/clusterctl/client/common.go:30]: nit: The godoc for this is the same as `getComponentsByName`, can we differentiate them or say something like it is the same as `getComponentsByName` except for variables being filled in.

File: cmd/clusterctl/client/repository/components.go (hunk 13 above)
Comment (nader-ziada) [reply cmd/clusterctl/client/repository/components.go:208]: I tried at first adding a bool like you are suggesting, but all kinds of tests broke because these functions are called from a bunch of places at different levels, so some places call replace variables directly and other places call NewComponents. It would have been a real big refactor

File: cmd/clusterctl/client/repository/components_client.go (hunk 15 above)
Comment (nader-ziada) [reply cmd/clusterctl/client/repository/components_client.go:53]: will add godoc

File: cmd/clusterctl/client/repository/components_client_test.go (hunk 14 above)
Comment (nader-ziada) [reply cmd/clusterctl/client/repository/components_client_test.go:237]: how about I refactor the func to share the common code so I don't just duplicate the tests?

File: cmd/clusterctl/client/common.go (hunk 16 above)
Comment (nader-ziada) [reply cmd/clusterctl/client/common.go:30]: what if the user only looks at one of them? I can change it if you feel strongly about it :D

File: cmd/clusterctl/client/repository/components.go (hunk 13 above)
Comment (wfernandes) [reply cmd/clusterctl/client/repository/components.go:208]: Hmm...yes it would be a sizeable change across the layers of clusterctl from `getComponentsByName` -> `ComponentsClient.Get` -> `NewComponents`. But I'm leaning more towards that because currently the clusterctl API is subject to change regardless and I'd prefer not having extra methods in the interfaces that we may have to support in the future.

Comment (nader-ziada) [reply cmd/clusterctl/client/repository/components.go:208]: these are different methods that are used for different use cases, adding the bool won't change that, it would just make header to read

File: cmd/clusterctl/client/repository/components_client.go [hunk 17]
```diff
@@ -47,18 +48,41 @@ func newComponentsClient(provider config.Provider, repository Repository, config
...
+
+// Get returns the components from a repository without variable replacement
 func (f *componentsClient) Get(version, targetNamespace, watchingNamespace string) (Components, error) {
+
+	file, err := f.getComponentYaml(version)
+	if err != nil {
+		return nil, err
+	}
+
+	return NewComponents(f.provider, version, file, f.configClient, targetNamespace, watchingNamespace)
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/repository/components_client.go:70]: Changing the behavior of an existing method should be clearly advised to the users.
Also, get in clusterctl Get is used for upgrades 
https://github.com/kubernetes-sigs/cluster-api/blob/810240aa628cd8b2dfa655abfbe1596d0b3533f2/cmd/clusterctl/client/cluster/upgrader.go#L328
And this should be replaced with GetWithValues

File: cmd/clusterctl/client/repository/components.go (hunk 13 above)
Comment (fabriziopandini) [reply cmd/clusterctl/client/repository/components.go:208]: As per comment https://github.com/kubernetes-sigs/cluster-api/issues/2876#issuecomment-613909426, I don't see such a clear distinction between the two use cases because variable substitution could provide value to users also in `clusterctl config cluster` with the `-o yaml` option.

Said that I like the idea of avoiding duplicating methods, even if I fully understand the pain of fixing the chain of calls (I experimented also some refactoring to get rid of this, but this is invasive).

**Comment by nader-ziada** [comment]
@wfernandes @fabriziopandini added a 2nd commit with the flag approach, let me know what you think. Thanks

**Comment by nader-ziada** [comment]
The `api-apidiff` is failing because I had to change a clusterctl method signature to fix this issue @vincepri

File: cmd/clusterctl/client/repository/components_client.go [hunk 18]
```diff
@@ -47,37 +47,38 @@ func newComponentsClient(provider config.Provider, repository Repository, config
 	}
 }
 
-func (f *componentsClient) Get(version, targetNamespace, watchingNamespace string) (Components, error) {
+// Get returns the components from a repository without variable replacement
+func (f *componentsClient) Get(options ComponentsOptions) (Components, error) {
```
Comment (wfernandes) [inline cmd/clusterctl/client/repository/components_client.go:51]: I suggest removing "without variable replacement" from the godoc.

This function doesn't override the `options.SkipVariables=false`. So if `Get(options)` was called with `options.SkipVariables=true` it would I'm assuming replace the variables.

**Comment by wfernandes** [comment]
This lgtm. Handing off to @fabriziopandini for final lgtm.

File: cmd/clusterctl/client/client.go [hunk 19]
```diff
@@ -28,8 +28,8 @@ type Client interface {
 	// GetProvidersConfig returns the list of providers configured for this instance of clusterctl.
 	GetProvidersConfig() ([]Provider, error)
 
-	// GetProviderComponents returns the provider components for a given provider, targetNamespace, watchingNamespace.
-	GetProviderComponents(provider string, providerType clusterctlv1.ProviderType, targetNameSpace, watchingNamespace string) (Components, error)
+	// GetProviderComponents returns the provider components for a given provider with options including targetNamespace, watchingNamespace.
+	GetProviderComponents(provider string, providerType clusterctlv1.ProviderType, options repository.ComponentsOptions) (Components, error)
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/client.go:32]: Is it possible to define an alias for `repository.ComponentsOptions` in `cmd/clusterctl/client/alias.go` so we are not forcing to import the `repository` package to the consumer

Such alias should be used in all client the public methods

File: cmd/clusterctl/client/config.go [hunk 20]
```diff
@@ -42,8 +43,9 @@ func (c *clusterctlClient) GetProvidersConfig() ([]Provider, error) {
 	return rr, nil
 }
 
-func (c *clusterctlClient) GetProviderComponents(provider string, providerType clusterctlv1.ProviderType, targetNameSpace, watchingNamespace string) (Components, error) {
-	components, err := c.getComponentsByName(provider, providerType, targetNameSpace, watchingNamespace)
+func (c *clusterctlClient) GetProviderComponents(provider string, providerType clusterctlv1.ProviderType, options repository.ComponentsOptions) (Components, error) {
+	options.SkipVariables = true
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/config.go:47]: Given that we are exponing options, should we leave to choose if to set this flag or not to the CLI/Library consumers?

File: cmd/clusterctl/client/client.go (hunk 19 above)
Comment (nader-ziada) [reply cmd/clusterctl/client/client.go]: will add the alias

File: cmd/clusterctl/client/config.go (hunk 20 above)
Comment (nader-ziada) [reply cmd/clusterctl/client/config.go]: Maybe this can be in a follow up PR

**Comment by fabriziopandini** [comment]
- /lgtm
