### PR TITLE
:bug: Use unstructured for conversion utils tests, and fix how we set annotations

### LINKED ISSUE #4632: Update to v1alpha4 imports did not update tests
**What steps did you take and what happened:**

While updating imports I noticed there are several places where an alias of something like `clusterv1alpha1`
and `clusterv1alpha2` were both changed to import `v1alpha4`. These tests appear to be testing the
migration between these versions, but now are testing the same thing.

This happened in commit e73e3d9021e5df61ea2861be6f73698a031a63c3 and a specific instance can be found here:

https://github.com/kubernetes-sigs/cluster-api/commit/e73e3d9021e5df61ea2861be6f73698a031a63c3#diff-2c830e010d7866e116a0065e20d45b39d31e0e348a5936f13c79948b0cf63347R25

In at least several of these cases, it appears this error was already introduced when switching to `v1alpha2`.

All of these cases should be reviewed to make sure they actually are still testing what we think they are testing.

/kind bug
/area testing
/area api

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

During a rewrite of the tests for the conversion util codebase which
sets and resets the annotation to retain data when doing conversion,
opted to use unstructured objects with a generic old "Machine" type
instead of importing multiple API packages.

The switch to unstructured showed that we weren't setting annotation
properly by calling SetAnnotations, but rather we opted to change the
map coming from GetAnnotations() directly in some cases.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4632

/kind release-blocking
/milestone v0.4

### CODE REVIEW

File: util/conversion/conversion.go [hunk 1]
```diff
@@ -108,23 +108,27 @@ func MarshalData(src metav1.Object, dst metav1.Object) error {
 	if err != nil {
 		return err
 	}
+	annotations := dst.GetAnnotations()
 	if dst.GetAnnotations() == nil {
```
Comment (CecileRobertMichon) [inline util/conversion/conversion.go:112]:
```suggestion
	if annotations == nil {
```

File: util/conversion/conversion.go [hunk 2]
```diff
@@ -108,23 +108,27 @@ func MarshalData(src metav1.Object, dst metav1.Object) error {
...
-		dst.SetAnnotations(map[string]string{})
+		annotations = map[string]string{}
 	}
-	dst.GetAnnotations()[DataAnnotation] = string(data)
+	annotations[DataAnnotation] = string(data)
+	dst.SetAnnotations(annotations)
```
Comment (CecileRobertMichon) [inline util/conversion/conversion.go:116]: do we need this? if annotations is a map wouldn't it get updated as it's a reference?

File: util/conversion/conversion.go [hunk 3]
```diff
@@ -108,23 +108,27 @@ func MarshalData(src metav1.Object, dst metav1.Object) error {
...
+	data, ok := annotations[DataAnnotation]
 	if !ok {
 		return false, nil
 	}
 	if err := json.Unmarshal([]byte(data), to); err != nil {
 		return false, err
 	}
-	delete(from.GetAnnotations(), DataAnnotation)
+	delete(annotations, DataAnnotation)
+	from.SetAnnotations(annotations)
```
Comment (CecileRobertMichon) [inline util/conversion/conversion.go:131]: same question here

File: util/conversion/conversion.go (hunk 2 above)
Comment (CecileRobertMichon) [reply util/conversion/conversion.go:116]: I feel like this is the exact same bug as https://github.com/kubernetes-sigs/cluster-api/pull/4373/files#diff-e25fb86695a8022fa1611100bd244f9b4185f28629d19830e83d18b4fa2ce710R54

we only need to set it if it was nil before

Comment (vincepri) [reply util/conversion/conversion.go:116]: It works for normal objects, although for unstructured when it gets annotations, it actually does a copy https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go#L407-L410 and https://github.com/kubernetes/kubernetes/blob/e8760b95bb0a0dfb5c184fd4e5ab95da3650a040/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go#L169
