### PR TITLE
:bug: Update API endpoints if missing

### LINKED ISSUE #1359: InfrastructureReady=true prevents API endpoints from being reconciled more than once
/kind bug

**What steps did you take and what happened:**
PR #1345 introduced an interesting side-effect. Because `InfrastructureReady` is not set before API endpoints are gathered, the latter is never again parsed once the former is `true`. For example ([source](https://github.com/kubernetes-sigs/cluster-api/blob/67d897059593c3fc8c3a304b031573c516ba1dd9/controllers/cluster_controller_phases.go#L141-L162)):

```golang
	if cluster.Status.InfrastructureReady || !infraConfig.GetDeletionTimestamp().IsZero() {
		return nil
	}

	// Determine if the infrastructure provider is ready.
	ready, err := external.IsReady(infraConfig)
	if err != nil {
		return err
	} else if !ready {
		klog.V(3).Infof("Infrastructure provider for Cluster %q in namespace %q is not ready yet", cluster.Name, cluster.Namespace)
		return nil
	}
	cluster.Status.InfrastructureReady = true

	// Get and parse Status.APIEndpoint field from the infrastructure provider.
	if err := util.UnstructuredUnmarshalField(infraConfig, &cluster.Status.APIEndpoints, "status", "apiEndpoints"); err != nil {
		return errors.Wrapf(err, "failed to retrieve Status.APIEndpoints from infrastructure provider for Cluster %q in namespace %q",
			cluster.Name, cluster.Namespace)
	} else if len(cluster.Status.APIEndpoints) == 0 {
		return errors.Wrapf(err, "retrieved empty Status.APIEndpoints from infrastructure provider for Cluster %q in namespace %q",
			cluster.Name, cluster.Namespace)
	}
```

Because CAPV always sets `Cluster.InfrastructureReady` to `true`, the CAPI controller only checks for the CAPV cluster's API endpoints once since the second time `reconcileInfrastructure` is entered, `cluster.Status.InfrastructureReady` will be `true`, and thus the `Status.APIEndpoints` from the CAPV cluster will not be read again.

Line 141 should probably be changed to:

```golang
	if (cluster.Status.InfrastructureReady && len(cluster.Status.APIEndpoints) > 0) || !infraConfig.GetDeletionTimestamp().IsZero() {
```

This is a design issue introduced by the fact that previously the concept of `InfrastructureReady` also indicated the availability of an API endpoint to use for the control plane. PRs #1345 and #1350 were created to address situations where this is not the case.

cc @vincepri @chuckha @ykakarap

### PR DESCRIPTION
**Pull request by akutz**
**What this PR does / why we need it**:
This patch updates the behavior of the cluster controller's "reconcileInfrastructure" function so that the API endpoints are always reconciled if they have not been set and the infrastructure is supposed to be otherwise ready.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1359

### CODE REVIEW

**Comment by akutz** [comment]
Hi @vincepri,

I think we need to change this back to partially the way I originally filed it. This new order introduces a bug where machines cannot depend on a cluster's `InfrastructureReady` flag to indicate whether or not to create a machine. I suppose a machine controller can look at the Provider cluster's ready flag. Thoughts?

**Comment by akutz** [comment]
/reopen

I clicked the wrong button.

File: controllers/cluster_controller_phases.go [hunk 1]
```diff
@@ -138,27 +138,32 @@ func (r *ClusterReconciler) reconcileInfrastructure(ctx context.Context, cluster
...
-	cluster.Status.InfrastructureReady = true
 
 	// Get and parse Status.APIEndpoint field from the infrastructure provider.
-	if err := util.UnstructuredUnmarshalField(infraConfig, &cluster.Status.APIEndpoints, "status", "apiEndpoints"); err != nil {
-		return errors.Wrapf(err, "failed to retrieve Status.APIEndpoints from infrastructure provider for Cluster %q in namespace %q",
-			cluster.Name, cluster.Namespace)
-	} else if len(cluster.Status.APIEndpoints) == 0 {
-		return errors.Wrapf(err, "retrieved empty Status.APIEndpoints from infrastructure provider for Cluster %q in namespace %q",
-			cluster.Name, cluster.Namespace)
+	if len(cluster.Status.APIEndpoints) == 0 {
```
Comment (detiber) [inline controllers/cluster_controller_phases.go]: @akutz @vincepri Any particular reason here to only set these once? It seems like it might be better to attempt to update these every time, otherwise I'm not sure the upgrade workflow would work for a provider that does not use a load balancer.

Comment (akutz) [reply controllers/cluster_controller_phases.go]: So that's what I would do, but it's not what was done before. I was attempting minimal impact. I've been writing code that reconciles, but I've noted a lot of CAPI code is more about initialization, so I tend to stick with the practice in the repo for which I'm writing the PR.

Comment (akutz) [reply controllers/cluster_controller_phases.go]: A possible side-effect, though, is if the control-plane endpoint is taken from an API server endpoint and later the API server list changes and the certificates no longer match the kubeconfig generated originally.

Comment (vincepri) [reply controllers/cluster_controller_phases.go]: The contract around `Status.Ready` assumes immutability. Once a provider sets the value to `true` it should never go back to `false` from a Cluster API point of view. There is no such contract for the other values though, if we allow for APIEndpoints to be updated, that should be fine.

Regarding the change, I'm not sure what `a bug where machines cannot depend on a cluster's InfrastructureReady` actually means?

Comment (akutz) [reply controllers/cluster_controller_phases.go]: I need to go remind myself. I also don’t think immutability should be assumed, but okay.

FWIW, this repo’s tests fail with the other order as well. It wasn’t just CAPV.

Comment (akutz) [reply controllers/cluster_controller_phases.go]: Oh yeah, I meant that if the API endpoint check is first, and it returns an error until there are API endpoints set, then this causes an ordering bug. Because InfraReady is never set on the CAPI Cluster, and if a machine reconciler is waiting for InfraReady, then it will never reconcile, potentially never supplying the needed API endpoints.

Comment (detiber) [reply controllers/cluster_controller_phases.go]: For the kubeconfig, we likely will need to:
- Determine if we created it vs created externally (ownerref maybe)?
- If we created it and if the defined endpoint is not == apiendpoints[0], recreate it

Comment (vincepri) [reply controllers/cluster_controller_phases.go]: Infrastructure provider machines shouldn't rely on anything other than Bootstrap.Data to be available to start spinning up instances. 

Kubeadm provider does all the heavy lifting here waiting for the `InfrastructureReady` and for 
 `ControlPlaneInitialized`

Comment (detiber) [reply controllers/cluster_controller_phases.go]: @vincepri It gets tricky without a stable control plane endpoint, which is the case with CAPV today. We'll need to ensure that the API endpoints get updated and that the generated kubeconfig is updated as control plane machines are replaced, otherwise the result will be breakage.

Comment (vincepri) [reply controllers/cluster_controller_phases.go]: @detiber That sounds good to me, we can do 1, but I think we should hold on for 2 until after release, wdyt?

Comment (akutz) [reply controllers/cluster_controller_phases.go]: I think this PR fixes CAPV today, and you don’t want the API endpoint error to prevent InfraReady from being set, which was the original intent of your first change anyway.

Comment (akutz) [reply controllers/cluster_controller_phases.go]: And it's also the case that the kubeadm bootstrap provider checks for InfraReady before creating bootstrap data. If InfraReady is never set because reading API endpoints causes an error, then the bootstrap data is never generated.

**Comment by detiber** [comment]
/lgtm
let's followup with discussions around syncing APIEndpoints and the kubeconfig secret.
