### PR TITLE
🐛 Rotate MachinePool bootstrap token

### LINKED ISSUE #3359: refresh behavior of kubeadmconfig with machinepool
**What steps did you take and what happened:**

I took a critical read of the kubeadm config controller code with an eye toward machine pool after this slack thread: https://kubernetes.slack.com/archives/CEX9HENG7/p1594849365190200

I'm curious about the expected behavior of token refresh: https://github.com/kubernetes-sigs/cluster-api/blob/19afe6cc4abec48f16211617d7f8a6571f6a2997/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L243-L267

This case: https://github.com/kubernetes-sigs/cluster-api/blob/19afe6cc4abec48f16211617d7f8a6571f6a2997/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L258-L259 

Plus https://github.com/kubernetes-sigs/cluster-api/blob/19afe6cc4abec48f16211617d7f8a6571f6a2997/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L828

MachinePool and MachineDeployment both can scale up and it seems would reuse the existing kubeadmconfig/bootstrap secret/join token. Refresh works well as-is here for the most part, except if scale up occurs after token expiration/deletion by TokenCleaner

Machine maps 1:1 with KubeadmConfig, but MachinePool also maps 1:1. If scale up happens after token deletion, we don't attempt to recreate the token for machine pools -- this feels incorrect. We could simply check if the owner type is a MachinePool and recreate the token -- that seems like a fairly simply fix, if not particularly elegant. I don't see any immediate problems with that, but figured I'd open an issue for discussion.

cc @rudoi @CecileRobertMichon @devigned 

**What did you expect to happen:**

Bootstrap data should be fresh for scale up on machine pools, even after longs periods where the original join token was deleted.

/kind bug

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Each MachinePool has one KubeadmConfig which means all instances of a MachinePool share the same bootstrap data. Currently, new MachinePool replicas are unable to join the cluster after the initial bootstrap token has expired (token TTL is 15 minutes). 

This PR implements to behavior that was described in https://github.com/kubernetes-sigs/cluster-api/issues/3359#issuecomment-660154973, that is: When a KubeadmConfig is owned by a MachinePool, we create a new token if the current one is expiring in less than TTL/2 (7.5 minutes), and update the MachinePool's bootstrap data secret. If the token is not ready to be rotated, we requeue after TTL/3 (5 minutes), to ensure that we get to rotate before it expires. 

This means MachinePools will always have a fresh token ready to be used by any new replicas that need to join the cluster (Scale up, rolling upgrade, etc.).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3359 https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1000

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

TODO: unit tests

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 1]
```diff
@@ -249,6 +249,36 @@ func (r *KubeadmConfigReconciler) Reconcile(ctx context.Context, req ctrl.Reques
 			return ctrl.Result{
 				RequeueAfter: DefaultTokenTTL / 2,
 			}, nil
+		} else if (config.Spec.JoinConfiguration != nil && config.Spec.JoinConfiguration.Discovery.BootstrapToken != nil) && configOwner.IsMachinePool() {
+			// If the BootstrapToken has been generated and infrastructure is ready but the configOwner is a MachinePool,
```
Comment (CecileRobertMichon) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:253]: need to extract this stuff into a new func

Comment (CecileRobertMichon) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:235]: done

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go [hunk 2]
```diff
@@ -924,6 +924,149 @@ func TestBootstrapTokenTTLExtension(t *testing.T) {
 	}
 }
 
+func TestBootstrapTokenRotationMachinePool(t *testing.T) {
+	t.Skip("This now fails because it's using Update instead of patch, needs rework")
```
Comment (CecileRobertMichon) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller_test.go:928]: TODO: need to fix this

test is passing in release-0.3 branch, same as https://github.com/kubernetes-sigs/cluster-api/pull/3940/files#diff-ad5b3c5b9e092b1dced2a9f66a655d659462a11bd6138e7c3f9853723f924f9aL777

**Comment by CecileRobertMichon** [comment]
/hold 

still have to fix `bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:125:1: cyclomatic complexity 31 of func `(*KubeadmConfigReconciler).Reconcile` is high (> 30) (gocyclo)`

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 3]
```diff
@@ -227,28 +224,14 @@ func (r *KubeadmConfigReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
-			return ctrl.Result{
-				RequeueAfter: DefaultTokenTTL / 2,
-			}, nil
+			// If the BootstrapToken has been generated for a join and the infrastructure is not ready.
+			// This indicates the token in the join config has not been consumed and it may need a refresh.
+			return r.refreshBootstrapToken(ctx, config, cluster)
+		} else if (config.Spec.JoinConfiguration != nil && config.Spec.JoinConfiguration.Discovery.BootstrapToken != nil) && configOwner.IsMachinePool() {
+			// If the BootstrapToken has been generated and infrastructure is ready but the configOwner is a MachinePool,
+			// we rotate the token to keep it fresh for future scale ups.
+			return r.rotateMachinePoolBootstrapToken(ctx, config, cluster, scope)
```
Comment (fabriziopandini) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:234]: Background question.
If I got it right, in the case of machine pools each token expire after TTL, being replaced by a new one. What happens to a joining machine which starts joining with a token but then for any reason (e.g poor network performances) takes longer than TTL before actually running kubeadm join? is it expected to fail?

Should we make this a little bit smarter and refresh in case a machine pool is scaling, rotate only if the machine pool is idle?

Comment (vincepri) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:234]: > What happens to a joining machine which starts joining with a token but then for any reason (e.g poor network performances) takes longer than TTL before actually running kubeadm join?

If the Machine takes longer than a TTL to join it'd fail regardless if it was MachinePool or not, that could also happen in the case of simple machines, or the ones in a MachineDeployment.

> Should we make this a little bit smarter and refresh in case a machine pool is scaling, rotate only if the machine pool is idle?

IIRC, this is already the case and it's covered by `refreshBootstrapToken`. @CecileRobertMichon correct me if I'm wrong, the assumption I was making is that MachinePool flips between Ready/NotReady while it's scaling up/down.

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 4]
```diff
@@ -279,6 +262,59 @@ func (r *KubeadmConfigReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
+
+	remoteClient, err := r.remoteClientGetter(ctx, r.Client, util.ObjectKey(cluster))
+	if err != nil {
+		log.Error(err, "Error creating remote cluster client")
+		return ctrl.Result{}, err
+	}
+
+	log.Info("Refreshing token until the infrastructure has a chance to consume it")
+	err = refreshToken(ctx, remoteClient, token)
+	if err != nil {
```
Comment (vincepri) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:277]: if err := ; err != nil

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 5]
```diff
@@ -279,6 +262,59 @@ func (r *KubeadmConfigReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
+		// It would be nice to re-create the bootstrap token if the error was "not found", but we have no way to update the Machine's bootstrap data
```
Comment (vincepri) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:278]: 🤔 I'd probably remove this comment, if the token is not found we should definitely not create it again, but wait for intervention from a health check or operator

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 6]
```diff
@@ -279,6 +262,59 @@ func (r *KubeadmConfigReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
+		return ctrl.Result{}, errors.Wrapf(err, "failed to refresh bootstrap token")
+	}
+	// NB: this may not be sufficient to keep the token live if we don't see it before it expires, but when we generate a config we will set the status to "ready" which should generate an update event
```
Comment (vincepri) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:281]: Argh requeue afters 😄, I'm not sure if I follow this comment either, if we renewed the token and we requeue at half the TTL, we should be fine?

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 7]
```diff
@@ -279,6 +262,59 @@ func (r *KubeadmConfigReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
+
+		config.Spec.JoinConfiguration.Discovery.BootstrapToken.Token = token
+		log.Info("Altering JoinConfiguration.Discovery.BootstrapToken", "Token", token)
+
+		// update the bootstrap data
+		return r.joinWorker(ctx, scope)
+	}
+	return ctrl.Result{
+		RequeueAfter: DefaultTokenTTL / 3,
+	}, nil
```
Comment (vincepri) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:315]: Could we switch this return and the one from the function above to be `ctrl.Result{}, error` instead?

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 8]
```diff
@@ -279,6 +262,59 @@ func (r *KubeadmConfigReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
+		return ctrl.Result{}, err
+	}
+
+	token := config.Spec.JoinConfiguration.Discovery.BootstrapToken.Token
+	shouldRotate, err := shouldRotate(ctx, remoteClient, token)
+	if err != nil {
+		return ctrl.Result{}, err
+	}
+	if shouldRotate {
+		log.V(2).Info("creating new bootstrap token")
```
Comment (vincepri) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:301]:
```suggestion
		log.V(2).Info("Creating new bootstrap token")
```

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 9]
```diff
@@ -279,6 +262,59 @@ func (r *KubeadmConfigReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
+		token, err := createToken(ctx, remoteClient)
+		if err != nil {
+			return ctrl.Result{}, errors.Wrapf(err, "failed to create new bootstrap token")
+		}
+
+		config.Spec.JoinConfiguration.Discovery.BootstrapToken.Token = token
+		log.Info("Altering JoinConfiguration.Discovery.BootstrapToken", "Token", token)
```
Comment (vincepri) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:308]: s/Altering/Rotating? To keep in sync with the log line above

File: bootstrap/util/configowner.go [hunk 10]
```diff
@@ -76,6 +76,11 @@ func (co ConfigOwner) IsControlPlaneMachine() bool {
 	return ok
 }
 
+// IsMachinePool checks if an unstructured object is a MachinePool.
+func (co ConfigOwner) IsMachinePool() bool {
+	return co.GetKind() == "MachinePool"
```
Comment (vincepri) [inline bootstrap/util/configowner.go:81]: Didn't notice this before, but should we also check that the APIGroup matches? (not the version)

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 3 above)
Comment (fabriziopandini) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:234]: > If the Machine takes longer than a TTL to join it'd fail regardless if it was MachinePool or not, that could also happen in the case of simple machines, or the ones in a MachineDeployment.

For single machines the token TTL is extended until Machine.infrastructureReady is true, so a single machine won't fail in case of slow startup

> IIRC, this is already the case and it's covered by refreshBootstrapToken

Uhmm might be I'm missing something, but I can't find where we are testing the machine pool status

**Comment by devigned** [comment]
> the assumption I was making is that MachinePool flips between Ready/NotReady while it's scaling up/down.

@vincepri, we expect the machine pool will flip between Ready/NotReady when scaling / upgrading. I have questioned if this is overloading `Ready` or what `Ready` really means. Do we have a precise definition for what `Ready` means?

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 3 above)
Comment (CecileRobertMichon) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:234]: > IIRC, this is already the case and it's covered by refreshBootstrapToken. @CecileRobertMichon Cecile Robert-Michon FTE correct me if I'm wrong, the assumption I was making is that MachinePool flips between Ready/NotReady while it's scaling up/down.

Correct, regardless of the infrastructure type, if `!configOwner.IsInfrastructureReady()` it would go into the case above to refresh the token. The token is only rotated if the MachinePool infra is ready. This is being tested here: https://github.com/kubernetes-sigs/cluster-api/pull/3940/files#diff-ad5b3c5b9e092b1dced2a9f66a655d659462a11bd6138e7c3f9853723f924f9aR976

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 5 above)
Comment (CecileRobertMichon) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:278]: This whole function was extracted exactly as-is from https://github.com/kubernetes-sigs/cluster-api/pull/3940/files#diff-f754cabdd737c0fac3039e7eb563b50ea52fc4ff88a9d517f4067e25977acdadL233-L251. I didn't touch the pre-existing comments since I wasn't making any changes to the refresh behavior.

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 6 above)
Comment (CecileRobertMichon) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:281]: same comment as above (was taken from https://github.com/kubernetes-sigs/cluster-api/pull/3940/files#diff-f754cabdd737c0fac3039e7eb563b50ea52fc4ff88a9d517f4067e25977acdadL248)

File: bootstrap/util/configowner.go (hunk 10 above)
Comment (CecileRobertMichon) [reply bootstrap/util/configowner.go:81]: Will do

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 11]
```diff
@@ -227,28 +224,14 @@ func (r *KubeadmConfigReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
-				return ctrl.Result{}, errors.Wrapf(err, "failed to refresh bootstrap token")
-			}
-			// NB: this may not be sufficient to keep the token live if we don't see it before it expires, but when we generate a config we will set the status to "ready" which should generate an update event
-			return ctrl.Result{
-				RequeueAfter: DefaultTokenTTL / 2,
-			}, nil
+			// If the BootstrapToken has been generated for a join and the infrastructure is not ready.
+			// This indicates the token in the join config has not been consumed and it may need a refresh.
+			return r.refreshBootstrapToken(ctx, config, cluster)
+		} else if (config.Spec.JoinConfiguration != nil && config.Spec.JoinConfiguration.Discovery.BootstrapToken != nil) && configOwner.IsMachinePool() {
```
[the remark this answers is not in the document]
Comment (CecileRobertMichon) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:231]: Not sure I follow, are you suggesting a nested if/else?

**Comment by vincepri** [comment]
`Ready` is really up to the object to define, if we want MachinePool to flip while an operation is running that's completely fine and expected, we'd have to make sure that we document that properly :)

File: bootstrap/util/configowner.go (hunk 10 above)
Comment (CecileRobertMichon) [reply bootstrap/util/configowner.go:81]: Actually, wouldn't the Group already be checked by GetConfigOwner below? I can add an additional check here but all the ConfigOwners should have group `clusterv1.GroupVersion.Group` so it would be a redundant check

Comment (vincepri) [reply bootstrap/util/configowner.go:81]: Sounds good, if we're already checking it below that should be enough

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 9 above)
Comment (vincepri) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:308]: Up to you, definitely a minor comment :)

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 5 above)
Comment (vincepri) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:278]: Got it. These are a bit misleading and I'd remove them if you're ok with it

**Comment by CecileRobertMichon** [comment]
> Ready is really up to the object to define, if we want MachinePool to flip while an operation is running that's completely fine and expected, we'd have to make sure that we document that properly :)

To be clear, it's the infrastructure Ready that's flipping (depending on the infra state) not the MachinePool object itself - so in this case the MachinePool.Status.InfrastructureReady field.

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 5 above)
Comment (CecileRobertMichon) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:278]: will do

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 7 above)
Comment (CecileRobertMichon) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:312]: How do I make sure it gets reqeued before the token expiration with `ctrl.Result{}` ?

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (CecileRobertMichon) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:231]: oh nevermind, gotcha

**Comment by vincepri** [comment]
LGTM

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go (hunk 7 above)
Comment (CecileRobertMichon) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:315]: @vincepri not sure how to address this

**Review by devigned — APPROVED** [review]
lgtm
