### PR TITLE
🐛 Init images skip variables

### LINKED ISSUE #2516: clusterctl init --infrastructure aws --list-images returns an error when env variables are not defined
**What steps did you take and what happened:**
- run `clusterctl init --infrastructure aws --list-images` without setting the AWS_B64ENCODED_CREDENTIALS env var
- Get: `Error: failed to get provider components for the "aws" provider: failed to perform variable substitution: value for variables [AWS_B64ENCODED_CREDENTIALS] is not set. Please set the value using os environment variables or the clusterctl config file`

**What did you expect to happen:**
- The command to run successfully without requiring the env variables to be set

**Environment:**

- Cluster-api version: `master`
- Minikube/KIND version: `kind v0.6.1`
- Kubernetes version: (use `kubectl version`): `v1.16.7`
- OS (e.g. from `/etc/os-release`): Fedora 31

/kind bug

### PR DESCRIPTION
**Pull request by wfernandes**
**What this PR does / why we need it**:
This PR allows commands like `clusterctl init --list-images` to work without having to define variables values in the clusterctl config or environment. However, `clusterctl init` will still require variables to be defined.

I've broken the work up into separate commits which I will squash after review.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2516

### CODE REVIEW

File: cmd/clusterctl/client/init.go [hunk 1]
```diff
@@ -60,6 +60,10 @@ type InitOptions struct {
 
 	// LogUsageInstructions instructs the init command to print the usage instructions in case of first run.
 	LogUsageInstructions bool
+
+	// SkipVariables skips variable parsing in the provider components yaml.
+	// It is set to true for listing images of provider components.
+	SkipVariables bool
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/init.go:66]: @wfernandes I'm s little bit concerned about adding this field to the InitOptions struct, because this gives to the library users the possibility to do init with skip options that is something we don't want.
Have you considered instead to add an additional arg to the private method setupInstaller:

```
func (c *clusterctlClient) setupInstaller(cluster cluster.Client, options InitOptions, SkipVariables bool) (cluster.ProviderInstaller, error)
```

Comment (wfernandes) [reply cmd/clusterctl/client/init.go:66]: Good catch. I agree that it need not be exported. 
I'm not too stuck on the implementation but another suggestion is just making the `skipVariables bool` private and update the comment to say it is meant for `InitImages`.
That way if we ever do split up the `InitImages` into a separate command, it can be easily included as an InitImageOption.
Again, not too hung up on the implementation, it's just another suggestion. WDYT?

Comment (fabriziopandini) [reply cmd/clusterctl/client/init.go]: ok for me
