### PR TITLE
🐛 Delete ClusterResourceSetBinding when cluster is deleted.

### LINKED ISSUE #3357: [ClusterResourceSet] ClusterResourceSetBinding is not cleaned up
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
1. Create a Cluster and apply a label;
2. Create a CRS selecting the above Cluster and a corresponding Secret;
3. After the CRS's corresponding Secret gets applied, delete the cluster;
4. Check the ClusterResourceSetBinding:
```bash
➜  ✗ k get clusterresourcesetbinding bkp-s-1 -o yaml
apiVersion: addons.cluster.x-k8s.io/v1alpha3
kind: ClusterResourceSetBinding
metadata:
  creationTimestamp: "2020-07-16T18:20:02Z"
  generation: 2
  name: bkp-s-1
  namespace: default
  ownerReferences:
  - apiVersion: addons.cluster.x-k8s.io/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: ClusterResourceSet
    name: cluster-components
    uid: 9f3b3040-94bb-49b2-8f92-bad9fb0dcf25
  resourceVersion: "42649"
  selfLink: /apis/addons.cluster.x-k8s.io/v1alpha3/namespaces/default/clusterresourcesetbindings/bkp-s-1
  uid: 31e33402-3d56-4252-93c5-982a9308bfad
spec:
  bindings:
  - clusterResourceSetName: cluster-components
    resources:
    - applied: true
      hash: sha256:fa2042db4c7f3023976888a616c02cba1b87cf01970ddea0ae20516092255a47
      kind: Secret
      lastAppliedTime: "2020-07-16T18:20:03Z"
      name: cluster-components
```
5. Create the cluster with the same name;
6. Check the cluster, no resource in the CRS is applied

**What did you expect to happen:**
1. CRS is applied when Cluster is deleted and created back;

**Anything else you would like to add:**
ClusterResourceSetBinding persists information that should expire when the matching resource is gone.

**Environment:**

- Cluster-api version: v0.3.7
- Minikube/KIND version: kind v0.7.0 go1.13.6 darwin/amd64
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:
This PR deletes ClusterResourceSetBinding when the owner cluster is deleted.
This is not garbage collected because both Cluster and ClusterResourceSet are the owners of ClusterResourceSetBinding but when any of them is deleted, ClusterResourceSetBinding should also be deleted.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3357

### CODE REVIEW

File: exp/addons/controllers/clusterresourceset_controller_test.go [hunk 1]
```diff
@@ -192,6 +194,35 @@ apiVersion: v1`,
...
+				Name:      testCluster.Name,
+			}
+			err := testEnv.Get(ctx, clusterResourceSetBindingKey, binding)
+			if err == nil {
+				isBindingCreated = true
+			}
+		}
+
+		By("Verifying ClusterResourceSetBinding is deleted when its cluster owner reference is deleted")
+		controllerutil.AddFinalizer(testCluster, "finalizer")
```
Comment (sedefsavas) [inline exp/addons/controllers/clusterresourceset_controller_test.go:213]: When deleting the testCluster below, somehow DeletionTimestamp never becomes non-zero when it comes to clusterToClusterResourceSet(). Setting a finalizer here fixes that problem but normally it should not be needed. Still looking to understand why this is the case.

Comment (sedefsavas) [reply exp/addons/controllers/clusterresourceset_controller_test.go:213]: /hold

File: exp/addons/controllers/clusterresourceset_controller.go [hunk 2]
```diff
@@ -357,6 +357,23 @@ func (r *ClusterResourceSetReconciler) clusterToClusterResourceSet(o handler.Map
 		return nil
 	}
 
+	if !cluster.DeletionTimestamp.IsZero() {
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourceset_controller.go:360]: 2 things:
1. This mapping function should not have any side effects (i.e. deleting things)
1. This has the potential to miss deleting bindings if the cluster is deleted but the controller doesn't see it. I would recommend just enqueuing the CRS, and in the reconcile method, if you can't find the cluster, delete its bindings.

Comment (sedefsavas) [reply exp/addons/controllers/clusterresourceset_controller.go:360]: > This has the potential to miss deleting bindings if the cluster is deleted but the controller doesn't see it (offline during deletion). I would recommend just enqueuing the CRS, and in the reconcile method, if you can't find the cluster, delete its bindings.

When we reconcile CRS, if a cluster is deleted, it won't match with its label. So there is no way to know which clusters are deleted. One thing we can do is to list CRSBindings at each reconcile and check if their cluster still exist.

Comment (detiber) [reply exp/addons/controllers/clusterresourceset_controller.go:360]: Would it make sense to have a "controller" for ClusterResourceSetBindings that could handle the deletion.

Then it would remove the intermediate step of trying to map Clusters to ClusterResourceSets in order to clean up ClusterResourceSetBindings and it should be possible to filter out CRSBindings based on the ownerRefs on deletion for either a Cluster or a ClusterResourceSet

Comment (ncdc) [reply exp/addons/controllers/clusterresourceset_controller.go:360]: A separate controller would probably be easier

Comment (sedefsavas) [reply exp/addons/controllers/clusterresourceset_controller.go:360]: A separate controller makes sense but we will still need the Clusters to ClusterResourceSets mapping for applying CRS to newly created clusters.

Comment (fabriziopandini) [reply exp/addons/controllers/clusterresourceset_controller.go:360]: What about deleteting `ClusterResourceSetBindings` as part of `ClusterController.reconcileDelete`?

Comment (sedefsavas) [reply exp/addons/controllers/clusterresourceset_controller.go:360]: We may want to avoid touching core controllers for features. Is there any issues you see doing it in the CRSBinding controller?

Comment (fabriziopandini) [reply exp/addons/controllers/clusterresourceset_controller.go:360]: I don't see the issues
I was not aware of this constraint

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+			// For additional cleanup logic use finalizers.
+			return ctrl.Result{}, nil
+		}
+		// Error reading the object - requeue the request.
+		return ctrl.Result{}, err
+	}
+
+	clusterOwner := getOwnerRef(crsBinding.OwnerReferences)
+
+	cluster := &clusterv1.Cluster{}
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:85]: You should be able to use `util.GetOwnerCluster(ctx, r.Client, crsBinding.ObjectMeta)` for this.

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+	if err := r.Client.Get(ctx, types.NamespacedName{Name: clusterOwner.Name, Namespace: crsBinding.Namespace}, cluster); err != nil {
+		if apierrors.IsNotFound(err) || !cluster.DeletionTimestamp.IsZero() {
+			return r.reconcileDelete(ctx, crsBinding)
+		}
+	}
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:90]: I think these are the cases you need to consider:

1. Some error other than not-found
1. Not-found error
1. Cluster being deleted

It looks like we're swallowing 1 here, and 3 needs to be outside the `err != nil` block.

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+	return ctrl.Result{}, nil
+}
+
+// reconcileDelete handles ClusterResourceSetBinding deletion.
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:94]: I would fold this directly into Reconcile

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 6]
```diff
@@ -0,0 +1,129 @@
...
+func (r *ClusterResourceSetBindingReconciler) reconcileDelete(ctx context.Context, crsBinding *addonsv1.ClusterResourceSetBinding) (reconcile.Result, error) {
+	err := r.Client.Delete(ctx, crsBinding)
+	return ctrl.Result{}, err
+}
+
+// getOwnerRef returns the owner reference of type Cluster
+func getOwnerRef(ownerReferences []metav1.OwnerReference) *metav1.OwnerReference {
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:101]: This isn't needed if you use `util.GetOwnerCluster`.

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+		if r.Kind == "Cluster" {
+			return &r
+		}
+	}
+	return nil
+}
+
+// clusterToClusterResourceSetBinding is mapper function that maps clusters to ClusterResourceSetBinding
+func (r *ClusterResourceSetBindingReconciler) clusterToClusterResourceSetBinding(o handler.MapObject) []ctrl.Request {
+	result := []ctrl.Request{}
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:112]:
```suggestion
```

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 8]
```diff
@@ -0,0 +1,129 @@
...
+
+	crsBinding := &addonsv1.ClusterResourceSetBinding{}
+	if err := r.Client.Get(context.Background(), types.NamespacedName{Name: cluster.Name, Namespace: cluster.Namespace}, crsBinding); err != nil {
+		r.Log.Error(err, "failed to get ClusterResourceSetBinding")
+		return nil
+	}
+	name := client.ObjectKey{Namespace: crsBinding.Namespace, Name: crsBinding.Name}
+	result = append(result, ctrl.Request{NamespacedName: name})
+
+	return result
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:128]:
```suggestion
	return []reconcile.Request{
	  {
	    NamespacedName: client.ObjectKey{
	      Namespace: crsBinding.Namespace,
	      Name: crsBinding.Name,
	    },
	  },
	}
```

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 9]
```diff
@@ -0,0 +1,129 @@
...
+
+	cluster, ok := o.Object.(*clusterv1.Cluster)
+	if !ok {
+		r.Log.Error(nil, fmt.Sprintf("Expected a Cluster but got a %T", o.Object))
+		return nil
+	}
+
+	crsBinding := &addonsv1.ClusterResourceSetBinding{}
+	if err := r.Client.Get(context.Background(), types.NamespacedName{Name: cluster.Name, Namespace: cluster.Namespace}, crsBinding); err != nil {
+		r.Log.Error(err, "failed to get ClusterResourceSetBinding")
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:122]:
```suggestion
		if !apierrors.IsNotFound(err) {
			r.Log.Error(err, "failed to get ClusterResourceSetBinding")
		}
```

Because this is triggered for every cluster update, and not all clusters have bindings, we should skip logging on 404s.

File: exp/addons/controllers/clusterresourceset_controller_test.go [hunk 10]
```diff
@@ -192,6 +193,32 @@ apiVersion: v1`,
...
+			Name:      testCluster.Name,
+		}
+		for isBindingCreated == false {
+			binding = &addonsv1.ClusterResourceSetBinding{}
+
+			err := testEnv.Get(ctx, clusterResourceSetBindingKey, binding)
+			if err == nil {
+				isBindingCreated = true
+			}
+		}
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourceset_controller_test.go:211]: Would it make more sense to use Eventually here?

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 11]
```diff
@@ -0,0 +1,129 @@
...
+
+	r.scheme = mgr.GetScheme()
+	return nil
+}
+
+func (r *ClusterResourceSetBindingReconciler) Reconcile(req ctrl.Request) (_ ctrl.Result, reterr error) {
+	ctx := context.Background()
+
+	// Fetch the ClusterResourceSetBinding instance.
+	crsBinding := &addonsv1.ClusterResourceSetBinding{}
```
Comment (vincepri) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:72]:
```suggestion
	binding := &addonsv1.ClusterResourceSetBinding{}
```

To simplify

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 12]
```diff
@@ -0,0 +1,129 @@
...
+	clusterOwner := getOwnerRef(crsBinding.OwnerReferences)
+
+	cluster := &clusterv1.Cluster{}
+	if err := r.Client.Get(ctx, types.NamespacedName{Name: clusterOwner.Name, Namespace: crsBinding.Namespace}, cluster); err != nil {
+		if apierrors.IsNotFound(err) || !cluster.DeletionTimestamp.IsZero() {
+			return r.reconcileDelete(ctx, crsBinding)
+		}
+	}
+	return ctrl.Result{}, nil
+}
```
Comment (vincepri) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:92]:
```suggestion
	err := r.Client.Get(ctx, types.NamespacedName{Name: clusterOwner.Name, Namespace: crsBinding.Namespace}, cluster)
	if apierrors.IsNotFound(err) || !cluster.DeletionTimestamp.IsZero() {
		return r.reconcileDelete(ctx, crsBinding)
	}
	return ctrl.Result{}, err
```

File: exp/addons/controllers/clusterresourceset_controller_test.go (hunk 10 above)
Comment (sedefsavas) [reply exp/addons/controllers/clusterresourceset_controller_test.go:211]: I didn't use Eventually() here because, I want this to be blocking, because the next Eventually() requires CRSBinding to exist.

Comment (ncdc) [reply exp/addons/controllers/clusterresourceset_controller_test.go:211]: You can have 2 different Eventually blocks - 1 here and 1 below - can't you?

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 13]
```diff
@@ -0,0 +1,129 @@
...
+)
+
+// +kubebuilder:rbac:groups=addons.cluster.x-k8s.io,resources=*,verbs=get;list;watch;create;update;patch;delete
+
+// ClusterResourceSetBindingReconciler reconciles a ClusterResourceSetBinding object
+type ClusterResourceSetBindingReconciler struct {
+	Client client.Client
+	Log    logr.Logger
+
+	scheme *runtime.Scheme
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:47]: I believe we can remove this as it's not used anywhere

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 14]
```diff
@@ -0,0 +1,129 @@
...
+}
+
+func (r *ClusterResourceSetBindingReconciler) SetupWithManager(mgr ctrl.Manager, options controller.Options) error {
+	_, err := ctrl.NewControllerManagedBy(mgr).
+		For(&addonsv1.ClusterResourceSetBinding{}).
+		Watches(
+			&source.Kind{Type: &clusterv1.Cluster{}},
+			&handler.EnqueueRequestsFromMapFunc{ToRequests: handler.ToRequestsFunc(r.clusterToClusterResourceSetBinding)},
+		).
```
Comment (detiber) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:56]: This cluster watch should probably be configured separately similarly to what we are doing in the Machine controller to properly honor paused clusters (at least until we can use a newer version of controller-runtime that supports configuring individual predicates for a watch):
https://github.com/kubernetes-sigs/cluster-api/blob/60a6daf4b9ecb74a9111b3269e7016988a8afc00/controllers/machine_controller.go#L99-L109

As a side note, I think this applies to the ClusterResourceSet controller as well.

Comment (sedefsavas) [reply exp/addons/controllers/clusterresourcesetbinding_controller.go:56]: I tried this before, but somehow it does not trigger cluster handler. I may be missing something. clusterToClusterResourceSetBinding() never gets called. @detiber

Comment (detiber) [reply exp/addons/controllers/clusterresourcesetbinding_controller.go:56]: Ah, that is correct, the default predicates we define wont work for this use case.

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 15]
```diff
@@ -0,0 +1,115 @@
...
+
+	cluster, err := util.GetOwnerCluster(ctx, r.Client, binding.ObjectMeta)
+	// If the owner cluster is already deleted or in deletion process, delete its ClusterResourceSetBinding
+	if apierrors.IsNotFound(err) || !cluster.DeletionTimestamp.IsZero() {
+		err := r.Client.Delete(ctx, binding)
+		return ctrl.Result{}, err
+	}
+	if err != nil {
+		return ctrl.Result{}, err
+	}
```
Comment (detiber) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:87]: It might be good to refactor this a bit, it seems odd to rely on the value of cluster prior to checking for `err != nil` in the case that error is not `IsNotFound`, maybe if the logic is inversed a bit?
```suggestion
	if err != nil && !apierrors.IsNotFound(err) {
		return ctrl.Result{}, err
	}
	 if apierrors.IsNotFound(err) || !cluster.DeletionTimestamp.IsZero() {
		err := r.Client.Delete(ctx, binding)
		return ctrl.Result{}, err
	}
```

Comment (detiber) [reply exp/addons/controllers/clusterresourcesetbinding_controller.go:87]: Might be good to add a log message that we are deleting the ClusterResourceSetBinding because the Cluster no longer exists.

File: exp/addons/controllers/clusterresourcesetbinding_controller.go [hunk 16]
```diff
@@ -0,0 +1,115 @@
...
+		return nil
+	}
+	return []reconcile.Request{
+		{
+			NamespacedName: client.ObjectKey{
+				Namespace: crsBinding.Namespace,
+				Name:      crsBinding.Name,
+			},
+		},
+	}
```
Comment (detiber) [inline exp/addons/controllers/clusterresourcesetbinding_controller.go:114]: Since the ClusterResourceSetBinding name/namespace matches and we already do a check in `reconcile` for if the resource exists, ignoring `IsNotFound` errors, I think it's probably safe to skip this get all together and just return the request based on the passed in MapObject:
```suggestion
	return []reconcile.Request{
		{
			NamespacedName: client.ObjectKey{
				Namespace: o.Meta.GetNamespace(),
				Name:      o.Meta.GetName(),
			},
		},
	}
```

File: exp/addons/controllers/clusterresourceset_controller_test.go [hunk 17]
```diff
@@ -51,7 +52,6 @@ var _ = Describe("ClusterResourceSet Reconciler", func() {
 	})
 	AfterEach(func() {
 		By("Deleting the Cluster")
-		Expect(testEnv.Delete(ctx, testCluster)).To(Succeed())
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourceset_controller_test.go:54]: Remove the previous By line too?

File: exp/addons/controllers/clusterresourceset_controller_test.go [hunk 18]
```diff
@@ -147,6 +147,7 @@ apiVersion: v1`,
 				UID:        testCluster.UID,
 			})
 		}, timeout).Should(BeTrue())
+		Expect(testEnv.Delete(ctx, testCluster)).To(Succeed())
```
Comment (ncdc) [inline exp/addons/controllers/clusterresourceset_controller_test.go:150]: Add a By line before this?

**Comment by sedefsavas** [comment]
Just holding until e2e tests pass. 
/hold

**Comment by sedefsavas** [comment]
/ hold cancel
