### PR TITLE
:bug: Remove unique patch ID from TopologyReconcile conditions

### LINKED ISSUE #7337: Patch UID in error causing infinite reconcile
In the Topology Reconciler's patching logic `applyPatchesToRequest` returns an error which includes the Patch UID if the patch fails. If a patch is misspecified (i.e. always errors in this function) this error gets added to a TopologyReconciled condition on the Cluster object. The result is `infinite` reconciles i.e. no exponential backoff if this error occurs, similar to the issue in https://github.com/kubernetes-sigs/cluster-api/issues/5945.

The solution to this is to either remove the UID from the error or to log and return the error seperately, similar to https://github.com/kubernetes-sigs/cluster-api/pull/7295

https://github.com/kubernetes-sigs/cluster-api/blob/1280aca6f506f2739862a8a6ef7a4db65ed6e373/internal/controllers/topology/cluster/patches/engine.go#L293

/kind bug
/cc @sbueringer

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Stop returning a unique ID with errors from the patch engine. This ID gets turned into a condition on the object which cause infinite reconciliation of objects avoiding exponential backoff.

Fixes #7337

### CODE REVIEW

File: internal/controllers/topology/cluster/patches/engine.go [hunk 1]
```diff
@@ -290,7 +290,8 @@ func applyPatchesToRequest(ctx context.Context, req *runtimehooksv1.GeneratePatc
 
 		// If a patch doesn't have a corresponding request item, the patch is invalid.
 		if requestItem == nil {
-			return errors.Errorf("unable to find corresponding request item with uid %q for the patch", patch.UID)
+			log.V(5).Infof("Unable to find corresponding request item with uid %q for the patch", patch.UID)
+			return errors.Errorf("unable to find corresponding request item for patch")
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/patches/engine.go:294]: Wondering if we should include a hint that more details can be found in the logs with log level 5?

Regarding log level. Should this be a higher log level?

@fabriziopandini WDYT?

File: internal/controllers/topology/cluster/patches/engine.go [hunk 2]
```diff
@@ -302,29 +303,29 @@ func applyPatchesToRequest(ctx context.Context, req *runtimehooksv1.GeneratePatc
 			log.V(5).Infof("Accumulating JSON patch: %s", string(patch.Patch))
 			jsonPatch, err := jsonpatch.DecodePatch(patch.Patch)
 			if err != nil {
-				return errors.Wrapf(err, "failed to apply patch with uid %q: error decoding json patch (RFC6902): %s",
-					requestItem.UID, string(patch.Patch))
+				log.V(5).Infof("Failed to apply patch with uid %q: error decoding json patch (RFC6902): %s: %s", requestItem.UID, string(patch.Patch), err)
+				return errors.Wrap(err, "failed to apply patch: error decoding json patch (RFC6902)")
```
[the remark this answers is not in the document]
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/patches/engine.go:307]: I think it's much more constant than the uid - we can't assume it's constant, but it won't change on every reconcile in a normal case I think. It could change in some case, though so it depends on how cautious this should be.

File: internal/controllers/topology/cluster/patches/engine.go (hunk 1 above)
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/patches/engine.go:294]: Log level 5 is the highest supported according to the logging conventions. I don't think errors / conditions are the right place to be giving direct debug help, unless we do it generically across all errors? It seems like a very general piece of advice, rather than something specific to this issue.

Comment (sbueringer) [reply internal/controllers/topology/cluster/patches/engine.go:294]: (I was suggesting a higher log level given it's an error)

Comment (killianmuldoon) [reply internal/controllers/topology/cluster/patches/engine.go:294]: Ah - I misunderstood, but I get your point now. I think that's probably a good point - log level 2 is probably the correct level for this.

Comment (sbueringer) [reply internal/controllers/topology/cluster/patches/engine.go:294]: Yup, 2 also sounds fine. Definitely makes it a lot easier to find and I think it's justifiable for an error. 

I think you can also resolve the other conversation. Given that this makes it a lot easier to find the error I think this makes it less important to include the patch in the error.

File: internal/controllers/topology/cluster/patches/engine.go [hunk 3]
```diff
@@ -302,29 +303,29 @@ func applyPatchesToRequest(ctx context.Context, req *runtimehooksv1.GeneratePatc
 			log.V(5).Infof("Accumulating JSON patch: %s", string(patch.Patch))
 			jsonPatch, err := jsonpatch.DecodePatch(patch.Patch)
 			if err != nil {
-				return errors.Wrapf(err, "failed to apply patch with uid %q: error decoding json patch (RFC6902): %s",
-					requestItem.UID, string(patch.Patch))
+				log.V(2).Infof("Failed to apply patch with uid %q: error decoding json patch (RFC6902): %s: %s", requestItem.UID, string(patch.Patch), err)
+				return errors.Wrap(err, "failed to apply patch: error decoding json patch (RFC6902)")
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/patches/engine.go:307]: Q: could we keep adding the patch to the error and drop only the uid?

also lets point users to the logs + add a note why are doing this
```suggestion
				// NOTE: details about the error are not included in the error because uid changes at every reconcile.
				log.V(2).Infof("Failed to apply patch with uid %q: error decoding json patch (RFC6902): %s: %s", requestItem.UID, string(patch.Patch), err)
				return errors.Wrap(err, "failed to apply patch: error decoding json patch (RFC6902); see Cluster API controller logs for more details")
```

**Review by fabriziopandini — COMMENTED** [review]
Good catch! one nit from my side

File: internal/controllers/topology/cluster/patches/engine.go (hunk 3 above)
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/patches/engine.go:307]: There's a conversation about it here: https://github.com/kubernetes-sigs/cluster-api/pull/7345#discussion_r987979604

It comes down to if the patch were to change every reconcile (possible but probably not the most common situation) then the same problem would emerge. Here the logging is on L2 so it seems clear enough which patch is at issue. 

Instead of pointing users to the logs here a "Look at the logs" message could be added to every error condition (maybe just for TopologyReconciled). IMO this isn't something specific to this part of the code.

Alternatively reconciliation could be filtered for when the condition changes, or rate limiting would massively reduce the impact here. It seems likely this issue will recur again in future as it's a very easy mistake to make during reconcile.

Comment (sbueringer) [reply internal/controllers/topology/cluster/patches/engine.go:307]: > Instead of pointing users to the logs here a "Look at the logs" message could be added to every error condition (maybe just for TopologyReconciled). IMO this isn't something specific to this part of the code.

I think this could be possibly addressed by having a systematic troubleshooting guide like:
* use clusterctl describe
* identify the failed resource
* look at the conditions
* look at the corresponding log (if necessary)
* ...

Comment (killianmuldoon) [reply internal/controllers/topology/cluster/patches/engine.go:307]: Let me open another issue for that and take it out of this discussion if that's good with everyone?

Comment (sbueringer) [reply internal/controllers/topology/cluster/patches/engine.go:307]: That was my plan :)

Comment (fabriziopandini) [reply internal/controllers/topology/cluster/patches/engine.go:307]: I don't want to block this, but I think that adding this message won't hurt when we are omitting intentionally details from the error. We can eventually iterate later on this one.

File: internal/controllers/topology/cluster/patches/engine.go [hunk 4]
```diff
@@ -290,7 +290,8 @@ func applyPatchesToRequest(ctx context.Context, req *runtimehooksv1.GeneratePatc
 
 		// If a patch doesn't have a corresponding request item, the patch is invalid.
 		if requestItem == nil {
-			return errors.Errorf("unable to find corresponding request item with uid %q for the patch", patch.UID)
+			log.V(2).Infof("Unable to find corresponding request item with uid %q for the patch", patch.UID)
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/patches/engine.go:293]: Should this be
```suggestion
			log.Infof("Unable to find corresponding request item with uid %q for the patch", patch.UID)
```
Given that it is an error?

Same for the others

File: internal/controllers/topology/cluster/patches/engine.go (hunk 3 above)
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/patches/engine.go:307]: I'd rather not add it here TBH as it's a very general idea - we should make it very clear elsewhere what the troubleshooitng process should be instead of trying to hind at it in error conditions.

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve
