### PR TITLE
🌱 Enable IPv6 test again

### LINKED ISSUE #12449: Failing e2e tests due to networking conformance test
### Which jobs are failing?

- periodic-cluster-api-e2e-main
- periodic-cluster-api-e2e-mink8s-main
- periodic-cluster-api-e2e-latestk8s-main
- periodic-cluster-api-e2e-release-1-9
- periodic-cluster-api-e2e-mink8s-release-1-8
- periodic-cluster-api-e2e-mink8s-release-1-9
- periodic-cluster-api-e2e-mink8s-release-1-10

### Which tests are failing?

- Kubernetes e2e suite [It] [sig-network] [Feature:IPv6DualStack] Granular Checks: Services Secondary IP Family [LinuxOnly] should function for service endpoints using hostNetwork
- capi-e2e [It] When following the Cluster API quick-start with dualstack and ipv4 primary [IPv6] Should create a workload cluster
- capi-e2e [It] When following the Cluster API quick-start with dualstack and ipv4 primary [IPv6] Should create a workload cluster [IPv6]

### Since when has it been failing?

07/03

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*e2e.*&xjob=.*-provider-.*%7C.*-operator-#be8a2f23a346e4a59a6c

### Reason for failure (if possible)

Seems like the main error is that the conformance tests are failing due to an issue in the networking test. The stated error on that test is: 
[FAILED] failed dialing endpoint, did not find expected responses... 

Obviously this needs more investigation to see what the actual problem is.

### Anything else we need to know?

- https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*e2e.*&xjob=.*-provider-.*%7C.*-operator-#be8a2f23a346e4a59a6c
- https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*e2e.*&xjob=.*-provider-.*%7C.*-operator-#cc28c16a50d9dcc9866d

### Label(s) to be applied

/kind failing-test
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
xref: https://kubernetes.slack.com/archives/C7J9RP96G/p1754649416231049?thread_ts=1751991861.631429&cid=C7J9RP96G

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #12449

### CODE REVIEW

File: test/e2e/quick_start_test.go [hunk 1]
```diff
@@ -174,7 +174,7 @@ var _ = Describe("When following the Cluster API quick-start with Ignition", fun
 	})
 })
 
-var _ = Describe("When following the Cluster API quick-start with dualstack and ipv4 primary [IPv6]", Label("IPv6"), func() {
+var _ = Describe("When following the Cluster API quick-start with dualstack and ipv4 primary [PR-Blocking] [IPv6]", Label("IPv6"), func() {
```
Comment (sbueringer) [inline test/e2e/quick_start_test.go]: Changes to this file must be reverted before merge

Comment (sbueringer) [reply test/e2e/quick_start_test.go]: /hold

Comment (sbueringer) [reply test/e2e/quick_start_test.go]: Hm didn't run as part of PR blocking for some reason, anyway let's wait for e2e-main
