### PR TITLE
⚠️ Machine status.phase should be `provisioned` when there is a ProviderID and no Node yet

### LINKED ISSUE #4779: Machine "Provisioned" phase is never set and used.
**What steps did you take and what happened:**
The machine object has the following phases to indicate the status of the lifecycle.
```Pending, Provisioning, Provisioned, Running, Deleting, Deleted, Failed, Unknown```

But it looks like machine can never be on the ```Provisioned``` phase.

https://github.com/kubernetes-sigs/cluster-api/blob/e970639fd4cb56003039878e82ffbc0b2e950a9e/controllers/machine_controller_phases.go#L61-L69

https://github.com/kubernetes-sigs/cluster-api/blob/e970639fd4cb56003039878e82ffbc0b2e950a9e/controllers/machine_controller_phases.go#L279-L311

From the codes above 
1) Machine is on ```Provisioned``` state if "nodeRef is set and infrastructure is not ready".
2) nodeRef is set only when infrastructure is in ```Ready``` state. 

In conclusion there is no case where the machine stays in ```Provisioned``` phase.

I am not sure if this is intended or a bug.

I am guessing ```m.Status.InfrastructureReady && m.Status.NodeRef == nil```
might be a case where machine is in the provisioned state.

**What did you expect to happen:**
Machine goes through the ```Provisioned``` phase.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: master
- Kubernetes version: (use `kubectl version`): 1.21.0
- OS (e.g. from `/etc/os-release`): does not matter

/kind bug
/area machine

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

We're currently in a situation where the "provisioned" phase would never
show up given the sequence of events between the controllers. The
proposal expects "provisioned" to be set whenever a Machine has
a spec.providerID field populated, the infrastructure provider is
reporting ready, and there is no Node associated with the Machine.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4779 

/assign @fabriziopandini @CecileRobertMichon 
/cc @onesolpark

### CODE REVIEW

File: controllers/machine_controller_phases.go [hunk 1]
```diff
@@ -58,8 +58,8 @@ func (r *MachineReconciler) reconcilePhase(_ context.Context, m *clusterv1.Machi
 		m.Status.SetTypedPhase(clusterv1.MachinePhaseProvisioning)
 	}
 
-	// Set the phase to "provisioned" if there is a NodeRef.
-	if m.Status.NodeRef != nil {
+	// Set the phase to "provisioned" if there is a provider ID and the infrastructure is ready.
+	if m.Spec.ProviderID != nil && m.Status.InfrastructureReady {
 		m.Status.SetTypedPhase(clusterv1.MachinePhaseProvisioned)
```
Comment (CecileRobertMichon) [inline controllers/machine_controller_phases.go:63]: I think the idea in https://github.com/kubernetes-sigs/cluster-api/pull/1720 was that if the InfraMachine stops being ready, the Machine doesn't stay in Running... should this just be `if m.Spec.ProviderID != nil` ?

Comment (vincepri) [reply controllers/machine_controller_phases.go:63]: If it flips? Yeah we I can remove the latter check, and just check on ProviderID, sgtm

Comment (CecileRobertMichon) [reply controllers/machine_controller_phases.go:63]: Actually reading down the comment thread in #1720 looks like there was some discussion around phases going backwards. What the expected phase now if a Machine has been created (provider ID is set) but InfraMachine ready is false?

Comment (onesolpark) [reply controllers/machine_controller_phases.go:63]: I think if InfraMachine ready status flips it goes back to Provisioning phase, since it has the providerId.
As mentioned in #1720, assumed that phases is a one way 
and if InfraMachine flips it will be accompanied by a failurereason / failuremessage, which will put machine in failure phase.

The provisioned phase is confusing on where it stands in the lifecycle of the machine.

File: controllers/machine_controller_phases_test.go [hunk 2]
```diff
@@ -442,7 +442,7 @@ func TestReconcileMachinePhases(t *testing.T) {
 		g.Expect(machine.Status.LastUpdated.After(lastUpdated.Time)).To(BeTrue())
 	})
 
-	t.Run("Should set `Provisioned` when there is a NodeRef but infra is not ready ", func(t *testing.T) {
+	t.Run("Should set `Provisioned` when there is a ProviderID, Infrastructure is ready, and there is no Node", func(t *testing.T) {
```
Comment (CecileRobertMichon) [inline controllers/machine_controller_phases_test.go:445]:
```suggestion
	t.Run("Should set `Provisioned` when there is a ProviderID and there is no Node", func(t *testing.T) {
```
