### PR TITLE
🌱 Fix flaky test in extensionconfig_controller_test.go

### LINKED ISSUE #12311: [unit test] Timed out after 10.001s.
### Which jobs are flaking?

- periodic-cluster-api-test-mink8s-main
- periodic-cluster-api-test-release-1-10

Failure:

```
Failed
=== RUN   TestExtensionReconciler_Reconcile
I0601 22:44:22.407311   32510 feature_gate.go:385] feature gates: {map[ClusterTopology:true]}
I0601 22:44:22.407441   32510 feature_gate.go:385] feature gates: {map[ClusterTopology:true RuntimeSDK:true]}
I0601 22:44:22.408648   32510 ???:1] "http: TLS handshake error from 127.0.0.1:58002: EOF"
I0601 22:44:22.532986   32510 reflector.go:430] "Caches populated" logger="controller-runtime.cache" type="*v1beta2.ExtensionConfig" reflector="pkg/mod/k8s.io/client-go@v0.33.1/tools/cache/reflector.go:285"
    extensionconfig_controller_test.go:122: 
        Timed out after 10.001s.
        The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/cluster-api/exp/runtime/internal/controllers/extensionconfig_controller_test.go:121 with:
        Expected
            <int64>: 1
        to equal
            <int64>: 2
--- FAIL: TestExtensionReconciler_Reconcile (10.81s)
```

triage link: https://storage.googleapis.com/k8s-triage/index.html?text=The%20function%20passed%20to%20Eventually%20failed%20at%20%2Fhome%2Fprow%2Fgo%2Fsrc%2Fsigs.k8s.io%2Fcluster-api%2Fexp%2Fruntime%2Finternal%2Fcontrollers%2Fextensionconfig_controller_test.go&job=.*-cluster-api-.*&xjob=.*-provider-.*%7C.*-operator-.* 

Failure link: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-test-mink8s-main/1929305699737669632 

### Which tests are flaking?

sigs.k8s.io/cluster-api/exp/runtime/internal/controllers TestExtensionReconciler_Reconcile

### Since when has it been flaking?

first failure on triage board [19/05/2025](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-test-release-1-10/1924297096265994240)

Not sure when it started.

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-test-mink8s-main

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Label(s) to be applied

/kind flake
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by Okabe-Junya**
**What this PR does**

Fixed a flaky test - `TestExtensionReconciler_Reconcile` by adding proper sync to wait for both Paused and Discovery conditions to be set before performing assertions

**why we need it**

The `paused.EnsurePausedCondition()` function triggers multiple reconciliation cycles:

1. Sets `PausedV1Beta2Condition` and returns `requeue=true` (early return)
2. Executes discovery logic and sets `ExtensionConfigDiscoveredV1Beta2Condition`

The test assertion `g.Expect(v1beta2Conditions).To(HaveLen(2))` was executed immediately after the second reconcile call, but before the patch containing the Discovery condition was fully applied to the API server (race condition I think).

So we need to `Eventually` block to resolve this race condition

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #12311

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
/retitle 🌱 Fix flaky test in extensionconfig_controller_test.go

**Comment by mboersma** [comment]
I think this attempts to fix #12311.

**Comment by Okabe-Junya** [comment]
> I think this attempts to fix #12311.

Yes, I couldn't find time to resolve the CI error. 
I'll check it out for now. Once CI passes, I'll mark the PR as ready for review and link it to the issue :)

**Comment by Okabe-Junya** [comment]
Still occurring a CI error, but I'm not sure of the cause. 
The method seems to be implemented, and running `make lint` locally doesn't detect any errors. It appears to be a problem with type inference, but I haven't pin-pointed the exact cause yet...

```
 Error: exp/runtime/internal/controllers/extensionconfig_controller_test.go:131:39: updatedConfig.GetV1Beta2Conditions undefined (type *"sigs.k8s.io/cluster-api/api/runtime/v1beta2".ExtensionConfig has no field or method GetV1Beta2Conditions) (typecheck)
```

**Comment by sbueringer** [comment]
Did you already rebase on top of main? CI is running based on latest main + the PR

**Comment by Okabe-Junya** [comment]
> Did you already rebase on top of main? CI is running based on latest main + the PR

Yes, already rebase with fresh main...
(Will take a look this error in this weekend 🙇 )

**Comment by sbueringer** [comment]
> Yes, already rebase with fresh main...

I think something went wrong there (see 26.03.2025)

image

**Comment by Okabe-Junya** [comment]
> I think something went wrong there (see 26.03.2025)

Oh, I'm really sorry...

I had mistakenly set up the upstream configuration on my machine (just for this repo), and origin/main wasn't fetching correctly for a while.
It seems I've been working off an old main branch... 🙇 

I've rebased on the latest main now. All CIs seems to be working well :) 
Could you please review?

**Comment by sbueringer** [comment]
> Oh, I'm really sorry...

Absolutely no problem 😃

**Comment by Okabe-Junya** [comment]
Thank you!
Now, there are no blockers here, so PTAL this PR. Thanks

File: exp/runtime/internal/controllers/extensionconfig_controller_test.go [hunk 1]
```diff
@@ -119,11 +119,19 @@ func TestExtensionReconciler_Reconcile(t *testing.T) {
 			pausedCondition := conditions.Get(conf, clusterv1.PausedCondition)
 			g.Expect(pausedCondition).ToNot(BeNil())
 			g.Expect(pausedCondition.ObservedGeneration).To(Equal(conf.Generation))
-		}).WithTimeout(10 * time.Second).WithPolling(100 * time.Millisecond).Should(Succeed())
+		}).WithTimeout(15 * time.Second).WithPolling(100 * time.Millisecond).Should(Succeed())
 
 		_, err = r.Reconcile(ctx, ctrl.Request{NamespacedName: util.ObjectKey(extensionConfig)})
```
Comment (sbueringer) [inline exp/runtime/internal/controllers/extensionconfig_controller_test.go]: There should be no race condition here as described in the PR description

Patch is done synchronously, APIReader is doing a live call. I think something slightly differently is going on here

Comment (sbueringer) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go]: > The test assertion g.Expect(v1beta2Conditions).To(HaveLen(2)) was executed immediately after the second reconcile call, but before the patch containing the Discovery condition was fully applied to the API server (race condition I think).

I think this is not what fails, if I see correctly

```plain
    extensionconfig_controller_test.go:122: 
        Timed out after 10.000s.
        The function passed to Eventually failed at /home/prow/go/src/sigs.k8s.io/cluster-api/exp/runtime/internal/controllers/extensionconfig_controller_test.go:121 with:
        Expected
            <int64>: 1
        to equal
            <int64>: 2
--- FAIL: TestExtensionReconciler_Reconcile (10.90s)
}
```
> https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-test-mink8s-main/1936969045718863872

The test fails at this line:
```go
g.Expect(pausedCondition.ObservedGeneration).To(Equal(conf.Generation))
```

Comment (sbueringer) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go]: I think the following happens:
* warmup.Start(ctx) writes ExtensionConfig...caBundle (increases generation to 2)
* r.Reconcile reconciles based on generation 1 (env.GetClient uses an outdated cache)
* r.Reconcile adds the Paused condition with observedGeneration 1
* env.Get in l.118 gets the ExtensionConfig with generation 2 that still has the Paused condition with observedGeneration 1

Comment (sbueringer) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go]: I would suggest to fix this by changing `env.GetClient()` to `env.GetAPIReader() // using live client to avoid race conditions in tests` in l.72 + l.105

(+ revert the current changes in this PR)

**Comment by Okabe-Junya** [comment]
Opened another issue since It looks some GHA (lint jobs) are bit flaky...

https://github.com/kubernetes-sigs/cluster-api/issues/12434

File: exp/runtime/internal/controllers/extensionconfig_controller_test.go (hunk 1 above)
Comment (Okabe-Junya) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go]: Thank you,

I had assumed it was caused by a race condition, but your point seems much more accurate.
I’ve reverted my changes and applied a new fix.

I’d appreciate it if you could take another look, thanks!

**Comment by Okabe-Junya** [comment]
/cc sbueringer

PTAL again, thanks!

**Comment by sbueringer** [comment]
Thank you very much!

/lgtm
/approve
