### PR TITLE
⚠️ Drop unnecessary fields from contract-versioned object references

### LINKED ISSUE #6539: prepare replacing corev1.ObjectReference in v1beta2
Note: This basically a reincarnation of the original topic of #2318. Since that issue has a lot of comments already, and a lot of them are just bot commands, I wanted to start over with a summary of what was discussed at KubeCon EU 22. 

## Motivation

New uses of `corev1.ObjectReference` are [discouraged](https://github.com/kubernetes/kubernetes/pull/87459/files) since about two years now. In my opinion we should go even further and try to get rid of `corev1.ObjectReference` completely. This is technically a breaking change (but it should be discussed how severe it actually is), so we at least have to wait until `corev1beta2`. Even though it might take a while until we get there, we should start preparing for it now by either deciding on which existing types we want to use, or which custom reference types we want to add to the API.

We should also try to come up with a somewhat exhaustive lists of the types we need, and add all of the relevant types, even if they are unused for now. This avoids having multiple separate discussions when the need for a new type comes up, and makes designing a consistent API much easier. In addition, new APIs can directly choose the appropriate reference type, making adoption much simpler.

There are several reasons not to use `corev1.ObjectReference` (some also mentioned in the comment discouraging the use of it):

- We ignore both `ResourceVersion` and `FieldPath` entirely. In addition we usually do not respect `UID`. While the latter might be useful in a status, it's usually not necessary to have.
- We do not need the `Namespace` field in a lot of cases. In fact, it even requires to write a lot of code just to keep it.
Whenever resources are only allowed to reference objects in the same namespace, we have defaulting and validation code in place to insure this (I think there are few webhooks that do only this). For uses this is only apparent when applying the resources to the API, leading to a bad UX. In the code, the field is usually ignored, as the namespace matches the object anyway. In case the validating webhooks are not working, this could lead to unexpected behaviour.
- In a lot of cases we could replace `APIVersion` with `group`. This becomes especially relevant when trying to optimise for GitOps: When there is a version in the reference, that version has to be upgraded in Git whenever the API version of the referenced object changes. Since the idea of serving multiple versions is that the client can decide which version to use, we should do so, and get rid of it where we can.

## Proposal

I propose to add 6 new reference types.
In addition, we should add functions and methods to convert between them and to and from `corev1.ObjectReference`. This way the types are easier to adopt, both within cluster-api, as well as by providers and other tools.

```go
type ObjectReference struct {
	Group string `json:"group"`
	Kind string `json:"kind"`
	Name string `json:"name"`
	Namespace string `json:"namespace"`
}

// Add these for all types
func NewObjectReference(ref v1.ObjectReference) ObjectReference {}
func (ObjectReference) ToV1Reference() v1.ObjectReference

func (LocalObjectReference) ToNamespaced(namespace string) ObjectReference {}
func (ObjectReference) ToLocal() LocalObjectReference {}

type LocalObjectReference struct {
	Group string `json:"group"`
	Kind string `json:"kind" `
	Name string `json:"name"`
}

func (PinnedObjectReference) Unpin() ObjectReference {}
func (ObjectReference) Pin(uuid string) PinnedObjectReference {}

type PinnedObjectReference struct {
	Group string `json:"group"`
	Kind string `json:"kind"`
	Name string `json:"name"`
	Namespace string `json:"namespace"`
	UID types.UID `json:"uid"`
}

func (PinnedLocalObjectReference) Unpin() LocalObjectReference {}
func (LocalObjectReference) Pin(uuid string) PinnedLocalObjectReference {}

type PinnedLocalObjectReference struct {
	Group string `json:"group"`
	Kind string `json:"kind"`
	Name string `json:"name"`
	UID types.UID `json:"uid"`
}

func (VersionedLocalObjectReference) ToUnversioned() LocalObjectReference {}
func (LocalObjectReference) ToVersioned(version string) VersionedLocalObjectReference {}

type VersionedLocalObjectReference struct {
	Group string `json:"group"`
	Version string `json:"version"`
	Kind string `json:"kind" `
	Name string `json:"name"`
}
```

## Alternatives

@vincepri mentioned that he would prefer using other core types if possible, instead of implementing our own. Currently there are three other types available:

- [`LocalObjectReference`](https://pkg.go.dev/k8s.io/kubernetes@v1.24.0/pkg/apis/core#LocalObjectReference) - only with `name`
- [`TypedLocalObjectReference`](https://pkg.go.dev/k8s.io/kubernetes@v1.24.0/pkg/apis/core#TypedLocalObjectReference) - only with `name`, `apigroup` and `kind`
- [`SecretReference`](https://pkg.go.dev/k8s.io/kubernetes@v1.24.0/pkg/apis/core#SecretReference) - only with `name` and `namespace`

Only the `TypedLocalObjectReference` seems to cover our needs, as we require typed references in most cases due to the modularity of Cluster API. We might be able to use the `LocalObjectReference` in some cases, e.g. for the References to `Cluster`.

Iirc the main motivation to use `corev1` types was twofold:
1. **We should try to avoid having to maintain additional types**
   Since these types are only used as part of our API resources, and not as individual ones, I don't think it's a big deal to add them.
2. **It is confusing/impractical for users to have to deal with our custom types**
   For the aforementioned reasons I think the custom types improve user experience, and at the same time make our code more maintainable and easier to follow. Right now a lot of internal tools accept `corev1.ObjectReference`, but ignore most parameters (without documentation). By using custom types, utilities can accept structs that only contain fields that they support.
	 Using the conversion functions it is easy to get a `corev1.ObjectReference` when required, or convert from one. Users have to import our API package anyway, so they have the conversion methods and functions available if they are part of that package.

## Is replacing existing references a breaking change?

Yes. We are removing fields from the API that were present before, so it certainly is a breaking API change.

But I'd like to argue that the impact of that breaking change is so small, that we can justify to make it anyway, at least when moving to v1beta2.

First of all, the change does not remove any features. In fact, it does not change any behavior at all. All removed fields are either completely unused, made useless by validation (namespaces) or not very useful (version part of apiversion).
Replacing `apiversion` with `group` is the only thing that makes this change really noticeable as it requires a small amount of manual migration. If we stick with `apiversion` the change won't be noticed by most users when using yaml or json. 

In code you will of course have to replace object references with the new custom types. But converting to the newer API will require changing the import path, and having to change a few struct names is not that much effort. Even when `corev1.ObjectReference` is used heavily, the conversion functions make it easy to convert between them, and it can be documented which fields will be dropped, making it much clearer what is going on.

The only case where it does actually have an impact, is when users use fields of the references for their own purposes, e.g. reconciling them using a custom controller. In addition, users that explicitly set the namespace field will need to stop doing so.

/area api
/kind cleanup
/kind api-change

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6539

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold

Includes #12368 for now

**Comment by sbueringer** [comment]
/hold cancel

rebased on to main. Not entirely read for review yet though

**Comment by sbueringer** [comment]
/assign @JoelSpeed @fabriziopandini 
Ready for review :)

File: api/core/v1beta2/common_types.go [hunk 1]
```diff
@@ -353,3 +354,40 @@ func (metadata *ObjectMeta) Validate(parent *field.Path) field.ErrorList {
 	)...)
 	return allErrs
 }
+
+// ContractVersionedObjectReference is a reference to an object.
+type ContractVersionedObjectReference struct {
+	// kind of the referent.
```
Comment (fabriziopandini) [inline api/core/v1beta2/common_types.go]: nit
```suggestion
	// kind of the resource being referenced.
```
(same below, consistend with what we have for APIGroup

File: api/core/v1beta2/common_types.go [hunk 2]
```diff
@@ -353,3 +354,40 @@ func (metadata *ObjectMeta) Validate(parent *field.Path) field.ErrorList {
...
+	// +required
+	// +kubebuilder:validation:MinLength=1
+	// +kubebuilder:validation:MaxLength=253
+	// +kubebuilder:validation:Pattern=`^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`
+	Name string `json:"name"`
+
+	// apiGroup is the group for the resource being referenced.
+	// apiGroup must be fully qualified domain name.
+	// The corresponding version for this reference will be looked up from the contract
+	// labels of the corresponding CRD of the referenced object.
```
Comment (fabriziopandini) [inline api/core/v1beta2/common_types.go]: nit
```suggestion
	// labels of the corresponding CRD of the resource being referenced.
```
For consistency

File: api/core/v1beta2/common_types.go [hunk 3]
```diff
@@ -353,3 +354,40 @@ func (metadata *ObjectMeta) Validate(parent *field.Path) field.ErrorList {
 	)...)
 	return allErrs
 }
+
+// ContractVersionedObjectReference is a reference to an object.
```
Comment (fabriziopandini) [inline api/core/v1beta2/common_types.go]: nit
```suggestion
// ContractVersionedObjectReference is a reference to a resource for which the version is inferred from contract labels.
```

File: internal/contract/version.go [hunk 4]
```diff
@@ -114,19 +135,19 @@ func getLatestAPIVersionFromContract(metadata metav1.Object, currentContractVers
...
 	}
 
 	return "", "", errors.Errorf("cannot find any versions matching contract versions %q for CRD %v as contract version label(s) are either missing or empty (see https://cluster-api.sigs.k8s.io/developer/providers/contracts.html#api-version-labels)", sortedCompatibleContractVersions, metadata.GetName())
 }
 
-// GetContractVersionForVersion gets the contract version for a specific apiVersion.
-func GetContractVersionForVersion(ctx context.Context, c client.Client, gvk schema.GroupVersionKind, version string) (string, error) {
-	crdMetadata, err := util.GetGVKMetadata(ctx, c, gvk)
+// GetContractVersionForVersion gets the contract version for an apiVersion from a CRD.
+func GetContractVersionForVersion(ctx context.Context, c client.Reader, gk schema.GroupKind, version string) (string, error) {
```
Comment (fabriziopandini) [inline internal/contract/version.go:148]: What about 
```suggestion
func GetContractVersionForAPIVersion(ctx context.Context, c client.Reader, gk schema.GroupKind, apiVersion string) (string, error) {
```

File: internal/contract/version.go [hunk 5]
```diff
@@ -78,30 +80,49 @@ func UpdateReferenceAPIContract(ctx context.Context, c client.Client, ref *corev
...
+
+	return schema.GroupVersion{
+		Group:   gk.Group,
+		Version: version,
+	}.String(), nil
+}
+
+// GetLatestAPIVersionFromContract gets the latest compatible contract version and apiVersion from a CRD based on
+// the passed in currentContractVersion.
+func GetLatestAPIVersionFromContract(metadata metav1.Object, currentContractVersion string) (string, string, error) {
```
Comment (fabriziopandini) [inline internal/contract/version.go]: Should this be 
```suggestion
func GetContractAndAPIVersionFromMetadata(metadata metav1.Object, currentContractVersion string) (string, string, error) {
```

File: internal/contract/version.go [hunk 6]
```diff
@@ -142,5 +163,32 @@ func GetContractVersionForVersion(ctx context.Context, c client.Client, gvk sche
...
 	}
 
-	return "", errors.Errorf("cannot find any contract version matching version %q for CRD %v", version, crdMetadata.GetName())
+	return "", errors.Errorf("cannot find any contract version matching version %s for CRD %s", version, crdMetadata.GetName())
+}
+
+// GetGVKMetadata retrieves a CustomResourceDefinition metadata from the API server using partial object metadata.
+//
+// This function is greatly more efficient than GetCRDWithContract and should be preferred in most cases.
+func GetGVKMetadata(ctx context.Context, c client.Reader, gk schema.GroupKind) (*metav1.PartialObjectMetadata, error) {
```
Comment (fabriziopandini) [inline internal/contract/version.go]: should this be
```suggestion
func GetGKMetadata(ctx context.Context, c client.Reader, gk schema.GroupKind) (*metav1.PartialObjectMetadata, error) {
```

File: internal/contract/version.go (hunk 4 above)
Comment (fabriziopandini) [reply internal/contract/version.go:148]: Also, wondering if we should move GetObjectFromContractVersionedRef to this package and make this func and GetGVKMetadata private

File: docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md
Comment (fabriziopandini) [inline docs/book/src/developer/providers/migrations/v1.10-to-v1.11.md:1]: Q: Should we add somewhere an example of how to get a referenced object when the reference is of type ContractVersionedObjectReference

File: internal/controllers/machine/machine_controller_phases.go [hunk 7]
```diff
@@ -456,10 +447,10 @@ func hasOnCreateOwnerRefs(cluster *clusterv1.Cluster, m *clusterv1.Machine, obj
 // getControlPlaneGVKForMachine returns the Kind of the control plane in the Cluster associated with the Machine.
 // This function checks that the Machine is managed by a control plane, and then retrieves the Kind from the Cluster's
 // .spec.controlPlaneRef.
-func getControlPlaneGVKForMachine(cluster *clusterv1.Cluster, machine *clusterv1.Machine) *schema.GroupVersionKind {
+func getControlPlaneGVKForMachine(cluster *clusterv1.Cluster, machine *clusterv1.Machine) *schema.GroupKind {
```
Comment (fabriziopandini) [inline internal/controllers/machine/machine_controller_phases.go]: nit
```suggestion
func getControlPlaneGKForMachine(cluster *clusterv1.Cluster, machine *clusterv1.Machine) *schema.GroupKind {
```

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 8]
```diff
@@ -543,9 +568,8 @@ func (r *Reconciler) reconcileMachineDeployments(ctx context.Context, s *scope.S
 
 // getCurrentMachineDeployments gets the current list of MachineDeployments via the APIReader.
 func (r *Reconciler) getCurrentMachineDeployments(ctx context.Context, s *scope.Scope) (sets.Set[string], error) {
-	// TODO: We should consider using PartialObjectMetadataList here. Currently this doesn't work as our
-	// implementation for topology dryrun doesn't support PartialObjectMetadataList.
-	mdList := &clusterv1.MachineDeploymentList{}
+	mdList := &metav1.PartialObjectMetadataList{}
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/reconcile_state.go:571]: q: does this imply that we will be caching md both as MachineDeployment and PartialObjectMetadataList?

Comment (fabriziopandini) [reply internal/controllers/topology/cluster/reconcile_state.go:571]: same for mp

File: internal/contract/version.go (hunk 4 above)
Comment (sbueringer) [reply internal/contract/version.go:148]: Added a comment instead: 
```
// The passed in version is only the version part of the apiVersion, not the full apiVersion.
```

Comment (sbueringer) [reply internal/contract/version.go:148]: > Also, wondering if we should move GetObjectFromContractVersionedRef to this package

That was my initial plan, but then I saw the heavy usage everywhere in core CAPI and I thought I don't want to prevent other folks from implementing things that we do in clusterctl or our e2e test framework.

E.g. if someone copies/reimplements part of our clusterctl discovery.go code they then also have to copy all this stuff

Overall I think it's not too bad that the func is public and it avoids annoyance for other folks

>  make this func and GetGVKMetadata private

This package is already internal. We can't unexport GetContractVersionForVersion, it is used in our controllers and e2e test code

File: internal/contract/version.go (hunk 5 above)
Comment (sbueringer) [reply internal/contract/version.go]: I'll add contract, but I want to keep Latest, that's really important

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 8 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:571]: No as this is using APIReader. So this is really just a nice straightforward improvement :)

Just wasn't aware of this code when I removed clusterctl topology dryrun

**Comment by sbueringer** [comment]
Thx for the review, PTAL :)

/test pull-cluster-api-e2e-conformance-ci-latest-main
/test pull-cluster-api-e2e-conformance-main
/test pull-cluster-api-e2e-latestk8s-main
/test pull-cluster-api-e2e-main
/test pull-cluster-api-e2e-mink8s-main
/test pull-cluster-api-e2e-upgrade-1-33-1-34-main

**Comment by sbueringer** [comment]
@fabriziopandini Thx for the review, PTAL :)

/test pull-cluster-api-e2e-conformance-ci-latest-main
/test pull-cluster-api-e2e-conformance-main
/test pull-cluster-api-e2e-latestk8s-main
/test pull-cluster-api-e2e-main
/test pull-cluster-api-e2e-mink8s-main
/test pull-cluster-api-e2e-upgrade-1-33-1-34-main
