### PR TITLE
🐛 `clusterctl init --list-images` should not need an initialized cluster

### LINKED ISSUE #6986: `clusterctl init --list-images` should not need an initialized cluster
**Detailed Description**

`clusterctl init --list-images` currently requires that there exists a cluster that is already initialized. When running with a cluster that is not initialized the command throws the following error:
```
Error: action failed after 9 attempts: failed get providers: no matches for kind "Provider" in version "clusterctl.cluster.x-k8s.io/v1alpha3"
```

This seems to be a circular dependency: Having to `init` before one can list the images that are needed to init.

It would be nice if we could list the images without having to have a cluster that is already initialized.

**Anything else you would like to add:**

We try to list the providers already installed when here: https://github.com/kubernetes-sigs/cluster-api/blob/2e73a260622410cc18e6242a0f272ee3e63e252f/cmd/clusterctl/client/init.go#L193-L196

and this causes the error. Since during `InitImages` we dont ensure that the `providers` CRD is installed the list operation fails if the providers CRD is missing. 

During `InitImages` we don't install the CRD (as opposed to `Init`) and we should continue not doing it. `InitImages` is effectively a dry-run operation and should not change anything on the cluster.

/kind feature
/area clusterctl

### PR DESCRIPTION
**Pull request by aniruddha2000**
- Add ProviderCRDInstalled field in InitOptions
- In setupInstaller check if ProviderCRDInstalled is installed or not
  - If yes return normal error
  - If not return empty provider list

Signed-off-by: Aniruddha Basak <codewithaniruddha@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6986

### CODE REVIEW

File: cmd/clusterctl/client/init.go [hunk 1]
```diff
@@ -73,6 +73,9 @@ type InitOptions struct {
 	// IgnoreValidationErrors allows for skipping the validation of provider installs.
 	// NOTE this should only be used for development
 	IgnoreValidationErrors bool
+
+	// To ensure the provider CRD is installed
+	ProviderCRDInstalled bool
```
Comment (ykakarap) [inline cmd/clusterctl/client/init.go:78]:
```suggestion
	allowMissingProviderCRD bool
```

Please also adjust the usages of this variable accordingly.

File: cmd/clusterctl/client/init.go [hunk 2]
```diff
@@ -199,7 +204,11 @@ func (c *clusterctlClient) setupInstaller(cluster cluster.Client, options InitOp
 
 	providerList, err := cluster.ProviderInventory().List()
 	if err != nil {
-		return nil, err
+		if options.ProviderCRDInstalled {
+			return nil, err
+		} else {
+			return installer, nil
```
Comment (ykakarap) [inline cmd/clusterctl/client/init.go:210]: How about ignoring the error only if the error is becasue the CRD is missing. I think you can check for the errors to be [NoKindMatchError](https://pkg.go.dev/k8s.io/apimachinery@v0.25.0/pkg/api/meta#NoKindMatchError). You should be able to check for that with the `errors.Is()` function.

If the error is becasue the connection to the cluster failed or other network reasons and not necessarily the missing CRD we don't want to ignore it.

Comment (ykakarap) [reply cmd/clusterctl/client/init.go:210]: also, if we ignore the error here we should not return immediately. We should continue with the function execution.

**Review by ykakarap — COMMENTED** [review]
Doing a high level review for now. 

The overall direction is good. I will take an other look after the commets are addressed.

File: cmd/clusterctl/client/init.go [hunk 3]
```diff
@@ -101,6 +106,8 @@ func (c *clusterctlClient) Init(options InitOptions) ([]Components, error) {
 	log.Info("Fetching providers")
 	firstRun := c.addDefaultProviders(clusterClient, &options)
 
+	options.allowMissingProviderCRD = true
```
Comment (ykakarap) [inline cmd/clusterctl/client/init.go:109]: Given the name of the variable, tge right way to do it will be to set the value to `true` in `InitImages` and flip the check in `setupInstaller`.

File: cmd/clusterctl/client/init.go [hunk 4]
```diff
@@ -197,11 +204,16 @@ func (c *clusterctlClient) InitImages(options InitOptions) ([]string, error) {
...
 
+	var noKindMatchErr *meta.NoKindMatchError
 	providerList, err := cluster.ProviderInventory().List()
-	if err != nil {
+	if !errors.As(err, &noKindMatchErr) {
 		return nil, err
 	}
 
+	if providerList == nil {
+		providerList = &clusterctlv1.ProviderList{}
```
Comment (ykakarap) [inline cmd/clusterctl/client/init.go:214]: How about doing `providerList = &clusterctlv1.ProviderList{}` before you do the `cluster.ProviderInventory().List()` call. The code would be cleaner that way.

File: cmd/clusterctl/client/init.go [hunk 5]
```diff
@@ -197,11 +204,16 @@ func (c *clusterctlClient) InitImages(options InitOptions) ([]string, error) {
 func (c *clusterctlClient) setupInstaller(cluster cluster.Client, options InitOptions) (cluster.ProviderInstaller, error) {
 	installer := cluster.ProviderInstaller()
 
+	var noKindMatchErr *meta.NoKindMatchError
 	providerList, err := cluster.ProviderInventory().List()
-	if err != nil {
+	if !errors.As(err, &noKindMatchErr) {
```
Comment (ykakarap) [inline cmd/clusterctl/client/init.go:209]: `errors.As` is ment to be used to retrieve an underlying error. Have you considered using `errors.Is` instead? `errors.Is` does check for the target erorr in the chain of wrapped errors so I believe it will work in this case.

**Review by ykakarap — CHANGES_REQUESTED** [review]

File: cmd/clusterctl/client/init.go (hunk 5 above)
Comment (aniruddha2000) [reply cmd/clusterctl/client/init.go:209]: Yes, `errors.Is` is working now don't know why it was not working but now fixed 😊

File: cmd/clusterctl/client/init.go [hunk 6]
```diff
@@ -209,6 +211,15 @@ func (c *clusterctlClient) setupInstaller(cluster cluster.Client, options InitOp
...
 
+	if !options.allowMissingProviderCRD {
+		providerList, err := cluster.ProviderInventory().List()
+		if err != nil {
+			return nil, err
+		}
+
+		addOptions.providerList = providerList
+	}
+
```
Comment (aniruddha2000) [inline cmd/clusterctl/client/init.go:222]: @ykakarap I think this peace of code will only execute in the case of `Init` method. So, we don't want to be any missing CRD and it should return every possible error including missing CRD as well right? That's why skipped the `errors.Is` and returned the error directly.

```go
if !options.allowMissingProviderCRD {
    var noKindMatchErr *meta.NoKindMatchError
    providerList, err := cluster.ProviderInventory().List()
    if !errors.Is(err, noKindMatchErr) {
        return nil, err
    }

    addOptions.providerList = providerList
}
```
If I do like this it will assign a nil value of `providerList` in `addOptions.providerList` in case of missing CRD in `Init` operation and that will be a nil pointer issue.
Is there still any scope for improvement?

File: cmd/clusterctl/client/init.go [hunk 7]
```diff
@@ -73,6 +73,9 @@ type InitOptions struct {
 	// IgnoreValidationErrors allows for skipping the validation of provider installs.
 	// NOTE this should only be used for development
 	IgnoreValidationErrors bool
+
+	// allowMissingProviderCRD allows listing of images if the provider CRD is missing
```
Comment (ykakarap) [inline cmd/clusterctl/client/init.go:77]:
```suggestion
	// allowMissingProviderCRD allows listing of images if the provider CRD is missing.
```
nit For consistency.

File: cmd/clusterctl/client/init.go (hunk 6 above)
Comment (ykakarap) [reply cmd/clusterctl/client/init.go:222]: This looks good. Good job! 
I tested it locally and it is working as expected.

**Review by ykakarap — COMMENTED** [review]
This looks great. 

Can you please add some unit tests as well.

**Comment by aniruddha2000** [comment]
Sure I will add the tests for the same.

**Comment by ykakarap** [comment]
@aniruddha2000 Do have bandwidth to continue this?

**Comment by aniruddha2000** [comment]
@ykakarap yes I have added the test file as well

**Comment by ykakarap** [comment]
Thanks. I will take a look tomorrow.

File: cmd/clusterctl/client/init_test.go [hunk 8]
```diff
@@ -159,6 +160,14 @@ func Test_clusterctlClient_InitImages(t *testing.T) {
 			wantErr:              true,
 			certManagerImagesErr: errors.New("failed to get cert images"),
 		},
+		{
```
Comment (ykakarap) [inline cmd/clusterctl/client/init_test.go:163]: I took a closer look at this and turns out this test will pass even if we set `allowMissingProviderCRD` to `false`. This is becasue the test setup here uses fakeclient internally and fakeclient doent not care if a CRD is installed or not when doing operations like get or list. It might not be possible to test this just using fakeclient. 

So for now lets just drop this test (as it is not an accurate signal).

**Review by ykakarap — COMMENTED** [review]
Just one comment. LGTM otherwise.

File: cmd/clusterctl/client/init_test.go (hunk 8 above)
Comment (aniruddha2000) [reply cmd/clusterctl/client/init_test.go:163]: Yes, If that is so then we should drop the tests.

**Comment by fabriziopandini** [comment]
we need CI singal!
/ok-to-test

**Comment by ykakarap** [comment]
> we need CI singal! /ok-to-test

I didn't catch this 😅 . Thanks @fabriziopandini

**Review by ykakarap — APPROVED** [review]
/lgtm

**Comment by ykakarap** [comment]
The test signal is green.
@fabriziopandini for approval.

File: cmd/clusterctl/client/init.go [hunk 9]
```diff
@@ -73,6 +73,9 @@ type InitOptions struct {
 	// IgnoreValidationErrors allows for skipping the validation of provider installs.
 	// NOTE this should only be used for development
 	IgnoreValidationErrors bool
+
+	// allowMissingProviderCRD allows listing of images if the provider CRD is missing.
+	allowMissingProviderCRD bool
```
Comment (vincepri) [inline cmd/clusterctl/client/init.go:78]: Is there a particular reason on why we'd need this flag? Could we just always return the images regardless if the CRDs are installed or not?

Comment (vincepri) [reply cmd/clusterctl/client/init.go:78]: That would be good context to provide in the flag, wdyt?

Comment (ykakarap) [reply cmd/clusterctl/client/init.go:78]: Sounds good. @aniruddha2000 Can you please update the flag description?

Comment (aniruddha2000) [reply cmd/clusterctl/client/init.go:78]: Sure 😄

File: cmd/clusterctl/client/init.go [hunk 10]
```diff
@@ -73,6 +73,10 @@ type InitOptions struct {
 	// IgnoreValidationErrors allows for skipping the validation of provider installs.
 	// NOTE this should only be used for development
 	IgnoreValidationErrors bool
+
+	// allowMissingProviderCRD allows listing of images if the provider CRD is missing in case of --list-images but make sure provider CRD is
+	// installed in the standard init process.
```
Comment (ykakarap) [inline cmd/clusterctl/client/init.go:78]:
```suggestion
	// allowMissingProviderCRD is used to allow for a missing provider CRD when listing images.
	// It is set to false to enforce that provider CRD is available when performing the standard init operation.
```

**Review by ykakarap — COMMENTED** [review]
Just one nit. LGTM otherwise.

**Comment by dlipovetsky** [comment]
Thanks for fixing this, @aniruddha2000!

Since I can't reproduce this bug with clusterctl 1.1, I think it was introduced in 1.2. I think this merits a backport.

/cherry-pick release-1.2

File: cmd/clusterctl/client/init.go (hunk 10 above)
Comment (ykakarap) [reply cmd/clusterctl/client/init.go:78]: @aniruddha2000 Do you have time to get to this?

Comment (aniruddha2000) [reply cmd/clusterctl/client/init.go]: Sorry I was on a vacation. I pushed the changes.

**Review by ykakarap — COMMENTED** [review]
/lgtm

**Comment by dlipovetsky** [comment]
@fabriziopandini This looks ready to be approved :pray:

**Comment by fabriziopandini** [comment]
sorry for getting late at this, great work
/lgtm
/approve
