### PR TITLE
🐛 Fix e2e test issues introduced by chained upgrades

### LINKED ISSUE #12765: 2 panics occurred in webhooks
### Which jobs are failing?

capi-e2e-latestk8s-main
capi-e2e-main
capi-e2e-mink8s-main

### Which tests are failing?

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-main/1967380485474619392
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-latestk8s-main/1967389293475270656
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-mink8s-main/1967399360060723200

### Since when has it been failing?

could see failure from 12-09-2025
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-mink8s-main/1966492626114842624
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-main/1966519050062270464

### Testgrid link

_No response_

### Reason for failure (if possible)

{Expected success, but got an error:

    <errors.aggregate | len:1, cap:1>: 
    2 panics occurred in webhooks (check logs for more details)
    [
        <*errors.errorString | 0xc0014be150>{
            s: "2 panics occurred in webhooks (check logs for more details)",
        },
    ] failed [FAILED] Expected success, but got an error:
    <errors.aggregate | len:1, cap:1>: 
    2 panics occurred in webhooks (check logs for more details)
    [
        <*errors.errorString | 0xc0014be150>{
            s: "2 panics occurred in webhooks (check logs for more details)",
        },
    ]

### Anything else we need to know?

_No response_

### Label(s) to be applied

/kind failing-test
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #12765

### CODE REVIEW

File: internal/webhooks/cluster.go [hunk 1]
```diff
@@ -334,9 +334,8 @@ func (webhook *Cluster) validateTopology(ctx context.Context, oldCluster, newClu
 	allErrs = append(allErrs, validateAutoscalerAnnotationsForCluster(newCluster, clusterClass)...)
 
 	if oldCluster != nil { // On update
-		// The ClusterClass must exist to proceed with update validation. Return an error if the ClusterClass was
-		// not found.
-		if apierrors.IsNotFound(clusterClassPollErr) {
+		// Return an error if we couldn't get the ClusterClass (either because it was not found or not reconciled).
```
Comment (sbueringer) [inline internal/webhooks/cluster.go]: I think this is much saner then trying to continue to handle the update case when the ClusterClass is not reconciled (and thus `nil`)

File: test/framework/deployment_helpers.go [hunk 2]
```diff
@@ -458,7 +458,7 @@ func verifyMetrics(data []byte) error {
 	}
 
 	if len(errs) > 0 {
-		return kerrors.NewAggregate(errs)
+		return errors.Wrapf(kerrors.NewAggregate(errs), "panics occurred in Pod %s", klog.KObj(pod))
```
Comment (neolit123) [inline test/framework/deployment_helpers.go]: can be errors.WithMessage, to avoid the wrapping here.

Comment (sbueringer) [reply test/framework/deployment_helpers.go]: kk, thx Done

File: internal/webhooks/cluster.go (hunk 1 above)
Comment (sbueringer) [reply internal/webhooks/cluster.go]: Had to fix this another way

**Comment by sbueringer** [comment]
To get more data points for tomorrow

/test pull-cluster-api-e2e-blocking-main
/test pull-cluster-api-e2e-conformance-ci-latest-main
/test pull-cluster-api-e2e-conformance-main
/test pull-cluster-api-e2e-latestk8s-main
/test pull-cluster-api-e2e-main
/test pull-cluster-api-e2e-mink8s-main
/test pull-cluster-api-e2e-upgrade-1-34-1-35-main

**Comment by chrischdi** [comment]
(pending ci)

/hold

**Comment by chrischdi** [comment]
(does not need a hold)

/hold cancel

**Comment by sbueringer** [comment]
Sorry still actively debugging locally, will need more fixes
So
/hold
is fine

**Comment by sbueringer** [comment]
Hopefully this should fix the failing tests. We'll do one follow-up for the chained upgrade failure here: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/12766/pull-cluster-api-e2e-latestk8s-main/1967936372635340800

(seems like just a rare race condition)

EDIT: Figured it out and pushed another change

**Comment by sbueringer** [comment]
/override pull-cluster-api-e2e-main

Independent known flake

**Comment by sbueringer** [comment]
/assign @fabriziopandini @chrischdi 
PTAL

**Review by fabriziopandini — COMMENTED** [review]
Thanks for looking into it!
/lgtm
/approve
