### PR TITLE
:bug: Scale down checks excludes machine about to be deleted

### LINKED ISSUE #3978: KCP fails to proceed if controller loses leader election during deletion flow
**What steps did you take and what happened:**
- Have a self-managed cluster using KCP
- Start rolling out a new KCP Machine spec (any rollout operation will do)
- KCP creates a new node, and tries to scale down the old one
- While scaling down an old node, KCP moves the leader to another Machine and removes the Machine from the etcd members
- KCP manager loses leader election and crashes before it can finish scale down (the final step is deleting the machine)
- KCP reconciles again, goes for a second time in scale down, perform pre-flight checks which fail on removed etcd member (etcd and api-server pods start crashing after an etcd member is removed)

**What did you expect to happen:**
- Expected the second second reconciliation to proceed "where it left off", rather than being blocked.

**Environment:**
- Cluster-api version: v0.3.11

/kind bug
/area control-plane

### PR DESCRIPTION
**Pull request by vincepri**
**What this PR does / why we need it**:

If the KCP controller crashes (likely in a self managed scenario) while
other operations were in progress, at the next reconciliation loop the
scale down operation would be blocked if for example we were in the
middle of deleting etcd (which would also crash the api server)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3978

/milestone v0.4.0
/assign @ncdc 

We need to backport as well.

### CODE REVIEW

File: controlplane/kubeadm/controllers/scale.go [hunk 1]
```diff
@@ -92,8 +92,15 @@ func (r *KubeadmControlPlaneReconciler) scaleDownControlPlane(
...
-	if result, err := r.preflightChecks(ctx, controlPlane); err != nil || !result.IsZero() {
+	// Pick the Machine that we should scale down.
+	machineToDelete, err := selectMachineForScaleDown(controlPlane, outdatedMachines)
+	if err != nil {
+		return ctrl.Result{}, errors.Wrap(err, "failed to select machine for scale down")
+	}
+
+	// Run preflight checks ensuring the control plane is stable before proceeding with a scale up/scale down operation; if not, wait.
+	// Given that we're scaling down, we can exclude the machineToDelete from the preflight checks.
+	if result, err := r.preflightChecks(ctx, controlPlane, machineToDelete); err != nil || !result.IsZero() {
```
Comment (detiber) [inline controlplane/kubeadm/controllers/scale.go:103]: Unless I'm missing something, this is creating an assumption that machineToDelete will always return the same Machine. While I generally expect that to be the case, I'm not sure that it will always be the case, especially once https://github.com/kubernetes-sigs/cluster-api/pull/3948 is implemented. There could also be potential issues that crop up from backup/restore of resources.

I know in the past there were discussions related to continued reconciliation of the kubeadm config map (https://github.com/kubernetes-sigs/cluster-api/issues/2859), if that was supported, then it would be possible to improve re-entrancy for scale down by:
- forwarding etcd leadership
- issuing the Machine deletion
- returning

On the next reconciliation:
- etcd membership is updated (will need to be updated to remove members for Machines that are in a deleting state)
- kubeadm configmap is updated for ClusterConfiguration membership

**Comment by ncdc** [comment]
@vincepri could you please file a bug describing the behavior we ran into and what this is trying to fix?

File: controlplane/kubeadm/controllers/scale_test.go [hunk 2]
```diff
@@ -202,13 +202,53 @@ func TestKubeadmControlPlaneReconciler_scaleDownControlPlane_NoError(t *testing.
...
 	})
-	t.Run("does not deletes control plane Machine if preflight checks fails", func(t *testing.T) {
+	t.Run("deletes the oldest control plane Machine even if preflight checks fails", func(t *testing.T) {
 		g := NewWithT(t)
 
 		machines := map[string]*clusterv1.Machine{
-			"one": machine("one"),
+			"one":   machine("one"),
+			"two":   machine("two"),
+			"three": machine("three"),
```
Comment (fabriziopandini) [inline controlplane/kubeadm/controllers/scale_test.go:211]: nit: add `withTimestamp(...)` to all the machines so it is more explicitly which is the oldest one

**Review by fabriziopandini — COMMENTED** [review]
I'm +1 for this change because it makes this bit of code more reentrant by fixing a problem existing also in previous releases.
Looking forward, I really would like to see an evolution in the direction discussed in https://github.com/kubernetes-sigs/cluster-api/issues/3876, but this is clearly something out of the scope of this PR

File: controlplane/kubeadm/controllers/scale.go (hunk 1 above)
Comment (vincepri) [reply controlplane/kubeadm/controllers/scale.go:103]: Documented the above issue more in https://github.com/kubernetes-sigs/cluster-api/issues/3978

> Unless I'm missing something, this is creating an assumption that machineToDelete will always return the same Machine.

Yeah, we discussed it a bit and although the new delete-machine annotation _could_ change the result of the machine picked for scale down (and cause the same exact issue again), we could probably live with it for now.

> I know in the past there were discussions related to continued reconciliation of the kubeadm config map (#2859), if that was supported, then it would be possible to improve re-entrancy for scale down

While we already move etcd leadership today, the problem is that the controller crashed in between the removal and issuing the Machine deletion.

I do agree we need a better re-entrancy model, although it's definitely hard to do when we're in the self-managed scenario where etcd leadership can change quite a bit and affects leader election for a controller.

Comment (vincepri) [reply controlplane/kubeadm/controllers/scale.go:103]: The other solution we should implement here is that for scale up/down operations we really only need to check if 

- Is the API Server available? 
  - Is there at least one pod up? 
  - Can we connect to it through the load balancer / endpoint?
- Do we have etcd quorum?

Those are really the only two operations we should check, although I'd like to follow-up on those later, once we can create two more conditions for those and check on the specific conditions.

This PR is really a quick fix for the issue that can happen most often (note that this bug affects all of v0.3.x, not just v0.3.11) and take some time to re-evaluate which checks to perform during scale up/down.

WDYT?

Comment (detiber) [reply controlplane/kubeadm/controllers/scale.go:103]: I'm ok with proceeding with this as a quick fix, mainly wanted to make sure that we are tracking longer term fixes, thanks!

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm
