### PR TITLE
✨ MachinePools: Use NodeDeletionTimeout and default it to 10s

### LINKED ISSUE #10544: Failed to delete machinePool for unreachable cluster
### What steps did you take and what happened?

At the time to uninstall/deprovision a cluster AND the cluster is unreachable or the cluster kubeConfig secret is deleted (as it managed by controlPlaneRef) the machinePool controller raise the below errors 

```
E0501 14:52:48.526675       1 controller.go:329] "Reconciler error" err="failed to create cluster accessor: error creating http client and mapper for remote cluster \"ns-rosa-hcp/rosa-hcp-2\": error creating client for remote cluster \"ns-rosa-hcp/rosa-hcp-2\": error getting rest mapping: failed to get API group resources: unable to retrieve the complete list of server APIs: v1: Get \"https://api.mydomain.5sub.s3.devshift.org:443/api/v1?timeout=10s\": dial tcp: lookup api.mydomain.5sub.s3.devshift.org on 172.30.0.10:53: no such host" controller="machinepool" controllerGroup="cluster.x-k8s.io" controllerKind="MachinePool" MachinePool="ns-rosa-hcp/workers-ex" namespace="ns-rosa-hcp" name="workers-ex" reconcileID="55df7e9c-460a-4cf5-bc19-409c18a6d61e"


E0501 14:53:48.529773       1 controller.go:329] "Reconciler error" err="failed to create cluster accessor: error fetching REST client config for remote cluster \"ns-rosa-hcp/rosa-hcp-2\": failed to retrieve kubeconfig secret for Cluster ns-rosa-hcp/rosa-hcp-2: Secret \"rosa-hcp-2-kubeconfig\" not found" controller="machinepool" controllerGroup="cluster.x-k8s.io" controllerKind="MachinePool" MachinePool="ns-rosa-hcp/workers-ex" namespace="ns-rosa-hcp" name="workers-ex" reconcileID="bbd400ce-c773-4ffe-9ab1-f4dfccc6660e"
```

The issue is initially raised for [cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws ) issue number [4936](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4936). Failed to clean up the MachinePool CRs in gitOps workFlow using ArgoCD.

Workaround to clean the machinePool CR by removing the finalizer manually.

### What did you expect to happen?

Expect to be able to delete the machinePool CRs without the needs to clean the finalizer manually 

### Cluster API version

v1.6.3
registry.k8s.io/cluster-api/cluster-api-controller:v1.6.3

### Kubernetes version

Kubernetes Version: v1.25.7+eab9cc9

### Anything else you would like to add?

Checking the [machinePool_controller_reconcileDelete](https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/internal/controllers/machinepool_controller.go#L256) the fix could be by checking the returning error at [line-263](https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/internal/controllers/machinepool_controller.go#L263) is not as [failed to create cluster accessor](https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/remote/cluster_cache_tracker.go#L284) (same error as above logs). The changes could be as below
```
func (r *MachinePoolReconciler) reconcileDelete(ctx context.Context, cluster *clusterv1.Cluster, mp *expv1.MachinePool) error {
	if ok, err := r.reconcileDeleteExternal(ctx, mp); !ok || err != nil {
		// Return early and don't remove the finalizer if we got an error or
		// the external reconciliation deletion isn't ready.
		return err
	}

	// Check if the return error is "failed to create cluster accessor" meaninng the cluster in unreachable then deleting the machienPool.
	if err := r.reconcileDeleteNodes(ctx, cluster, mp); err != nil {
		if !strings.Contains(err.Error(), "failed to create cluster accessor") {
                         // Return early and don't remove the finalizer if we got an error.
			return err
		}
	}

	controllerutil.RemoveFinalizer(mp, expv1.MachinePoolFinalizer)
	return nil
}
```
OR if the machinePool has InfrastructureRef then the responsibility of deleting the node should be done by the InfrastructureRef CR not by the machinePool (it may raise back compatibility issue). The changes could be as below 
```
func (r *MachinePoolReconciler) reconcileDelete(ctx context.Context, cluster *clusterv1.Cluster, mp *expv1.MachinePool) error {
	if ok, err := r.reconcileDeleteExternal(ctx, mp); !ok || err != nil {
		// Return early and don't remove the finalizer if we got an error or
		// the external reconciliation deletion isn't ready.
		return err
	}

	// Check if there is an InfrastructureRef then deleting the node should be done by the InfrastructureRef.
	if mp.Spec.Template.Spec.InfrastructureRef.Name == "" {
		if err := r.reconcileDeleteNodes(ctx, cluster, mp); err != nil {
			// Return early and don't remove the finalizer if we got an error.
			return err
		}
	}

	controllerutil.RemoveFinalizer(mp, expv1.MachinePoolFinalizer)
	return nil
}
```

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by serngawy**
**What this PR does / why we need it**:
Ignore unreachable cluster while deleting machinePools 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10544

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test
/area machinepools

**Comment by chrischdi** [comment]
I think this one goes into a different direction then described in:

* https://github.com/kubernetes-sigs/cluster-api/issues/10544#issuecomment-2090384205

and

* https://github.com/kubernetes-sigs/cluster-api/issues/10544#issuecomment-2095356357

/hold

**Comment by serngawy** [comment]
@mboersma would review the PR and let me know your thoughts.

File: exp/internal/controllers/machinepool_controller.go [hunk 1]
```diff
@@ -260,7 +261,9 @@ func (r *MachinePoolReconciler) reconcileDelete(ctx context.Context, cluster *cl
 		return err
 	}
 
-	if err := r.reconcileDeleteNodes(ctx, cluster, mp); err != nil {
+	err := r.reconcileDeleteNodes(ctx, cluster, mp)
+	// Check if the return error has ClusterAccessorErrorMessage to ignore unreachable cluster.
+	if err != nil && !strings.Contains(err.Error(), remote.ClusterAccessorErrorMessage) {
```
Comment (mboersma) [inline exp/internal/controllers/machinepool_controller.go:266]: Should we implement a function like MachineReconciler's `isNodeDeleteAllowed` for MachinePool and call it before `reconcileDeleteNodes()`? I *think* that would be considered more graceful, but @chrischdi or @fabriziopandini please correct me if you had something else in mind.

Comment (chrischdi) [reply exp/internal/controllers/machinepool_controller.go:266]: I'd favor that instead of relying on string matching on an error, yes 👍

Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go:266]: okay, that is fine. But the logic for deleting the machinePool if the cluster is unreachable Should we proceed with deleting the machinePool as the machinePool.infrastructureRef already doing validation for the node deletion OR we return and don't proceed with the delete ?

Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller.go:266]: Basically we should continue. The Machine controller works like this:

* Figure out if node deletion is "allowed" (allowed is not exactly perfect wording, but basically if we should do node deletion or not
* Result is stored in isDeleteNodeAllowed
* If isDeleteNodeAllowed is true
  * Try to delete Nodes
  * If this doesn't work either immediately or after some timeout (if NodeDeletionTimeout is configured) => log the error and continue with Machine deletion

I would expect the same logic for MachinePools. I think we should also handle NodeDeletionTimeout as this is also a field within MachinePools (MachinePool.spec.template.spec.nodeDeletionTimeout).



xrefs:
* https://github.com/kubernetes-sigs/cluster-api/blob/15615f64b8c8db57afb67384d57951f42d0887d3/internal/controllers/machine/machine_controller.go#L348
* https://github.com/kubernetes-sigs/cluster-api/blob/15615f64b8c8db57afb67384d57951f42d0887d3/internal/controllers/machine/machine_controller.go#L467-L488

Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go]: would you review this, I add the logic for machine Delete timeout

File: exp/internal/controllers/machinepool_controller.go [hunk 2]
```diff
@@ -253,33 +253,52 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
-	if ok, err := r.reconcileDeleteExternal(ctx, mp); !ok || err != nil {
-		// Return early and don't remove the finalizer if we got an error or
-		// the external reconciliation deletion isn't ready.
-		return err
-	}
+func (r *MachinePoolReconciler) reconcileDelete(ctx context.Context, cluster *clusterv1.Cluster, machinepool *expv1.MachinePool) error {
+	deleteAllowed, clusterClient, err := r.isDeleteMachinePoolAllowed(ctx, cluster)
+
+	// Check for cluster allowing delete or machinePool delete timeout.
+	if deleteAllowed || r.isMachinePoolDeleteTimeoutPassed(machinepool) {
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:260]: Is this saying that if the cluster has a deletion timestamp or and the time out is met we never get through this code path and so we never delete the finaliser blocking deletion?

File: exp/internal/controllers/machinepool_controller.go [hunk 3]
```diff
@@ -253,33 +253,52 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
+func (r *MachinePoolReconciler) isDeleteMachinePoolAllowed(ctx context.Context, cluster *clusterv1.Cluster) (bool, client.Client, error) {
+	// Check if cluster is been deleted
+	if !cluster.DeletionTimestamp.IsZero() {
+		// return true when cluster is been deleted to delete external resources and skip delete nodes refs.
+		return true, nil, nil
 	}
 
-	return r.deleteRetiredNodes(ctx, clusterClient, machinepool.Status.NodeRefs, machinepool.Spec.ProviderIDList)
+	// Check if the target cluster client is reachable.
+	clusterClient, err := r.Tracker.GetClient(ctx, util.ObjectKey(cluster))
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:299]: why is a function called isMachinePoolDeleteTimeoutPassed returning a clusterClient?

File: exp/internal/controllers/machinepool_controller.go [hunk 4]
```diff
@@ -253,33 +253,52 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
-	controllerutil.RemoveFinalizer(mp, expv1.MachinePoolFinalizer)
-	return nil
+	return err
 }
 
-func (r *MachinePoolReconciler) reconcileDeleteNodes(ctx context.Context, cluster *clusterv1.Cluster, machinepool *expv1.MachinePool) error {
-	if len(machinepool.Status.NodeRefs) == 0 {
-		return nil
+// isMachinePoolDeleteTimeoutPassed check the machinePool node delete time out.
+func (r *MachinePoolReconciler) isMachinePoolDeleteTimeoutPassed(machinepool *expv1.MachinePool) bool {
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:283]: >// isMachinePoolDeleteTimeoutPassed check the machinePool node delete time out.

should this be named then `isNodeTimeoutPassed`? so we ref the specific "Node" time out and don't include the machinepool which implicit in the receiver

File: exp/internal/controllers/machinepool_controller.go [hunk 5]
```diff
@@ -253,33 +253,52 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
 
-func (r *MachinePoolReconciler) reconcileDelete(ctx context.Context, cluster *clusterv1.Cluster, mp *expv1.MachinePool) error {
-	if ok, err := r.reconcileDeleteExternal(ctx, mp); !ok || err != nil {
-		// Return early and don't remove the finalizer if we got an error or
-		// the external reconciliation deletion isn't ready.
-		return err
-	}
+func (r *MachinePoolReconciler) reconcileDelete(ctx context.Context, cluster *clusterv1.Cluster, machinepool *expv1.MachinePool) error {
+	deleteAllowed, clusterClient, err := r.isDeleteMachinePoolAllowed(ctx, cluster)
+
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:258]: how is the Node timeout check related to the PR title/issue? If not can we have a separate PR for that?

File: exp/internal/controllers/machinepool_controller.go [hunk 6]
```diff
@@ -253,33 +253,52 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
+		if ok, err := r.reconcileDeleteExternal(ctx, machinepool); !ok || err != nil {
+			// Return early and don't remove the finalizer if we got an error or
+			// the external reconciliation deletion isn't ready.
+			return err
+		}
 
-	if err := r.reconcileDeleteNodes(ctx, cluster, mp); err != nil {
-		// Return early and don't remove the finalizer if we got an error.
-		return err
+		// Delete nodes when cluster accessor available & there are nodes to delete.
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:267]: should this PR be scoped only to retrieve the cluster client and skip if not functional?

File: exp/internal/controllers/machinepool_controller.go (hunk 2 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go:260]: As I changed the logic based on the previous comment , I fix it now. It says if the machinePool delete allowed OR machinePool delete timeout pass go delete the machinePool external CRs and Nodes

File: exp/internal/controllers/machinepool_controller.go (hunk 5 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go:258]: they are related , delete the machinePool either with unreachable clusters or when the delete timeout pass.

File: exp/internal/controllers/machinepool_controller.go [hunk 7]
```diff
@@ -253,33 +253,51 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
+		return machinepool.DeletionTimestamp.Add(machinepool.Spec.Template.Spec.NodeDeletionTimeout.Duration).After(time.Now())
 	}
+	return false
+}
 
-	clusterClient, err := r.Tracker.GetClient(ctx, util.ObjectKey(cluster))
-	if err != nil {
-		return err
+// deleteMachinePoolAllowed check the cluster status and target cluster client accessor state.
+func (r *MachinePoolReconciler) deleteMachinePoolAllowed(ctx context.Context, cluster *clusterv1.Cluster, machinepool *expv1.MachinePool) (bool, client.Client, error) {
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:291]: I think this should be called isDeleteMachinePoolAllowed... consistently with the other function naming

File: exp/internal/controllers/machinepool_controller.go (hunk 4 above)
Comment (enxebre) [reply exp/internal/controllers/machinepool_controller.go:283]: Then I think it should isMachinePoolNodesTimeoutPassed or similar. Current naming implies a machinepool deletion timeout which there isn't one?

File: exp/internal/controllers/machinepool_controller.go [hunk 8]
```diff
@@ -253,33 +253,51 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
+	// Check if the machinePool is deleted
+	if !machinepool.DeletionTimestamp.IsZero() {
+		// Check if the target cluster client is reachable.
+		clusterClient, err := r.Tracker.GetClient(ctx, util.ObjectKey(cluster))
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:295]: Can you elaborate why does this determine if a machinePool deletion is allowed?

File: exp/internal/controllers/machinepool_controller.go (hunk 4 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go:283]: okay

File: exp/internal/controllers/machinepool_controller.go (hunk 8 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go:295]: when the cluster is unreachable, that makes deleting the nodes not doable. so it raise error and returning false.

File: exp/internal/controllers/machinepool_controller.go (hunk 7 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go:291]: it was originally isDeleteMachinePoolAllowed but as per comment the func returning bool, client and error so suggest was to better make it deleteMachinePoolAllowed

File: exp/internal/controllers/machinepool_controller.go [hunk 9]
```diff
@@ -253,33 +253,51 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
-		// Return early and don't remove the finalizer if we got an error or
-		// the external reconciliation deletion isn't ready.
-		return err
-	}
+func (r *MachinePoolReconciler) reconcileDelete(ctx context.Context, cluster *clusterv1.Cluster, machinepool *expv1.MachinePool) error {
+	deleteAllowed, clusterClient, err := r.deleteMachinePoolAllowed(ctx, cluster, machinepool)
+
+	// Check for cluster allowing delete or machinePool delete timeout.
+	if deleteAllowed || r.isMachinePoolNodesDeleteTimeoutPassed(machinepool) {
+		if ok, err := r.reconcileDeleteExternal(ctx, machinepool); !ok || err != nil {
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:261]: Why is reconcileDeleteExternal within this if block?
If there node timeout is infinite and clusterClient fails we block deletion for ever, is that intentional?
Can we add code comment elaborating the why for this logic? Also additional test cases with the scenarios this is trying to account for might help.

Comment (enxebre) [reply exp/internal/controllers/machinepool_controller.go:261]: wouldn't this all we need to achieve the goal don't hang forever on Node deletion?
```
	if ok, err := r.reconcileDeleteExternal(ctx, mp); !ok || err != nil {
		// Return early and don't remove the finalizer if we got an error or
		// the external reconciliation deletion isn't ready.
		return err
	}

	if !NodeDeletionTimeoutMet() {
		if err := r.reconcileDeleteNodes(ctx, cluster, mp); err != nil {
			// Return early and don't remove the finalizer if we got an error.
			return err
		}
	}

	controllerutil.RemoveFinalizer(mp, expv1.MachinePoolFinalizer)
	return nil
```

Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go:261]: well, the idea was to tie the machinePool resources (InfrastructureRef) with the delete timeout define in the machineSpec.

Comment (enxebre) [reply exp/internal/controllers/machinepool_controller.go:261]: >well, the idea was to tie the machinePool resources (InfrastructureRef) with the delete timeout define in the machineSpec.

Why? the deletion timeout is meant for the Node kube resource. The infra must be deleted before the node, otherwise stateful pods primitives are in risk of being corrupted. Then we delete the Node to signal the kas and we have the timeout in case something catastrophic happened e.g. kas lb is broken we don't block forever.

There's no timeout primitive for infra deletion today. If we think that might be needed is a different discussion we can have separately but nothing articulated so far makes me think why we'd need that.
Thanks for iterating with me!

File: exp/internal/controllers/machinepool_controller.go [hunk 10]
```diff
@@ -282,12 +287,24 @@ func (r *MachinePoolReconciler) reconcileDeleteNodes(ctx context.Context, cluste
 	return r.deleteRetiredNodes(ctx, clusterClient, machinepool.Status.NodeRefs, machinepool.Spec.ProviderIDList)
 }
 
+// isMachinePoolDeleteTimeoutPassed check the machinePool node delete time out.
+func (r *MachinePoolReconciler) isMachinePoolNodesDeleteTimeoutPassed(machinepool *expv1.MachinePool) bool {
+	if !machinepool.DeletionTimestamp.IsZero() && machinepool.Spec.Template.Spec.NodeDeletionTimeout != nil {
+		return machinepool.DeletionTimestamp.Add(machinepool.Spec.Template.Spec.NodeDeletionTimeout.Duration).After(time.Now())
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:293]: if deletiontimestamp+timeout is after Now it means the timeout has not passed and it should return false, no?
Also this func needs to account for 0s as always false.

Can we please have unit tests to cover all these cases?

Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go]: I added more unit test and checking for 0s (Not sure why 0s means continue to delete [forever](https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1beta1/machine_types.go#L131), not make sense to me should be similar to nodeDrainTimeout and nodeDetachedTimeout immediate delete.)

File: exp/internal/controllers/machinepool_controller_test.go [hunk 11]
```diff
@@ -426,6 +519,11 @@ func TestReconcileMachinePoolRequest(t *testing.T) {
 			r := &MachinePoolReconciler{
 				Client:    clientFake,
 				APIReader: clientFake,
+				Tracker:   remote.NewTestClusterCacheTracker(ctrl.LoggerFrom(context.TODO()), clientFake, clientFake, clientFake.Scheme(), client.ObjectKey{Name: testCluster.Name, Namespace: testCluster.Namespace}),
+			}
+			// Set the tracker to nil for nodeDeleteTimeout cases
+			if tc.machinePool.Name == "try-delete-forever" || tc.machinePool.Name == "deleted-timeoutNode" {
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller_test.go:525]: if checking arbitrary strings here is error prone and non starter, if needed the tracker needs to be driven by a field dedicated field in the test case. But also why do you need to do this?

File: exp/internal/controllers/machinepool_controller.go [hunk 12]
```diff
@@ -282,12 +291,26 @@ func (r *MachinePoolReconciler) reconcileDeleteNodes(ctx context.Context, cluste
 	return r.deleteRetiredNodes(ctx, clusterClient, machinepool.Status.NodeRefs, machinepool.Spec.ProviderIDList)
 }
 
+// isMachinePoolDeleteTimeoutPassed check the machinePool node delete time out.
+func (r *MachinePoolReconciler) isMachinePoolNodesDeleteTimeoutPassed(machinepool *expv1.MachinePool) bool {
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:295]: nit: given this operate against the MachinePoolReconciler and receives a machinePool, naming seems redundant i.e isNodesDeleteTimeoutPassed should be sufficient.

File: exp/internal/controllers/machinepool_controller.go [hunk 13]
```diff
@@ -282,12 +291,26 @@ func (r *MachinePoolReconciler) reconcileDeleteNodes(ctx context.Context, cluste
 	return r.deleteRetiredNodes(ctx, clusterClient, machinepool.Status.NodeRefs, machinepool.Spec.ProviderIDList)
 }
 
+// isMachinePoolDeleteTimeoutPassed check the machinePool node delete time out.
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:294]: please replace machinepool with machinePool

**Comment by enxebre** [comment]
/retitle  Let machinePools to honour NodeDeletionTimeout

I dropped some more comments, looking good to me otherwise.
After merging we can consider follow up PR to wrap only the if !r.isNodesDeleteTimeoutPassed(machinepool) { block with a isDeleteNodeAllowed that checks the if guest kas is operational

File: exp/internal/controllers/machinepool_controller_test.go (hunk 11 above)
Comment (enxebre) [reply exp/internal/controllers/machinepool_controller_test.go:525]: particularly valuable since we are moving this form experimental https://github.com/kubernetes-sigs/cluster-api/pull/10751

File: exp/internal/controllers/machinepool_controller.go (hunk 12 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go:295]: The name originally was isMachinePoolDeleteTimeoutPassed based in your previous comment I made it isMachinePoolNodesDeleteTimeoutPassed. I believe the right name  isMachinePoolDeleteTimeoutPassed

File: exp/internal/controllers/machinepool_controller_test.go (hunk 11 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller_test.go:525]: I want the unit test to raise error by setting the tracker to nil, so when it deletes node as we expect it raise error. Otherwise we don't really know if it passes the timeout or just delete it.

File: exp/internal/controllers/machinepool_controller.go (hunk 12 above)
Comment (enxebre) [reply exp/internal/controllers/machinepool_controller.go:295]: >The name originally was isMachinePoolDeleteTimeoutPassed based in your previous comment I made it isMachinePoolNodesDeleteTimeoutPassed.

Yes, thanks for bearing with me. In this iteration becomes clear the redundancy. Not a blocker to me if you want to keep it as it is.

> isMachinePoolDeleteTimeoutPassed

This is not a machinePool delete timeout. This is a timeout for Nodes deletion, which is a fraction of the machinePool deletion process.

**Comment by sbueringer** [comment]
I would also take a look once I get around to it

File: exp/internal/controllers/machinepool_controller_test.go [hunk 14]
```diff
@@ -277,8 +280,8 @@ func TestReconcileMachinePoolRequest(t *testing.T) {
 		},
 	}
 
-	time := metav1.Now()
-
+	timeNow := metav1.Now()
+	timePluse1H := metav1.Time{Time: time.Now().Add(time.Hour * 1)}
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller_test.go:284]: typo pulse?

File: exp/internal/controllers/machinepool_controller_test.go [hunk 15]
```diff
@@ -302,6 +305,7 @@ func TestReconcileMachinePoolRequest(t *testing.T) {
 	testCases := []struct {
 		machinePool expv1.MachinePool
 		expected    expected
+		withTracker bool
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller_test.go:308]: nit: I'd expect test cases to use tracker by default. So this would be something like `omitTracker` or `forceDeleteNodeFailure` that needs to be explicitly set to true by the test case.

**Comment by enxebre** [comment]
Dropped a few more nits.
/lgtm

otherwise

/assign @sbueringer

File: exp/internal/controllers/machinepool_controller.go [hunk 16]
```diff
@@ -253,41 +253,64 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
 	if err != nil {
 		return err
 	}
 
-	return r.deleteRetiredNodes(ctx, clusterClient, machinepool.Status.NodeRefs, machinepool.Spec.ProviderIDList)
+	return r.deleteRetiredNodes(ctx, clusterClient, machinePool.Status.NodeRefs, machinePool.Spec.ProviderIDList)
+}
+
+// isMachinePoolDeleteTimeoutPassed check the machinePool node delete time out.
+func (r *MachinePoolReconciler) isMachinePoolNodeDeleteTimeoutPassed(machinePool *expv1.MachinePool) bool {
```
Comment (enxebre) [inline exp/internal/controllers/machinepool_controller.go:295]: can this be unit tested

File: exp/internal/controllers/machinepool_controller_test.go (hunk 15 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller_test.go:308]: well, Instead of init the tracker and then set it to nil better to check if we need it and init it

File: exp/internal/controllers/machinepool_controller_test.go (hunk 14 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller_test.go:284]: It is the timeNow + 1h

File: exp/internal/controllers/machinepool_controller.go (hunk 16 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller.go:295]: it is already tested within the unit test cases

File: exp/internal/controllers/machinepool_controller.go [hunk 17]
```diff
@@ -253,41 +253,64 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
-	if len(machinepool.Status.NodeRefs) == 0 {
+// reconcileDeleteNodes delete the cluster nodes.
+func (r *MachinePoolReconciler) reconcileDeleteNodes(ctx context.Context, cluster *clusterv1.Cluster, machinePool *expv1.MachinePool) error {
+	if len(machinePool.Status.NodeRefs) == 0 {
 		return nil
 	}
 
+	if r.Tracker == nil {
+		return errors.New("Cannot establish cluster client to delete nodes")
+	}
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller.go:284]: I realize this is not the only place in the MachinePool controller where we check if the tracker is nil, but I'm a bit confused why we do it. The other place is in watchClusterNodes, where we just return nil if the Tracker is not set.

I assume it is simply not a valid case that the tracker is not set. Can we get rid of both checks that we have today and instead just have one in SetupWithManager (and clearly state there that this is a setup error)

File: exp/internal/controllers/machinepool_controller.go [hunk 18]
```diff
@@ -253,41 +253,64 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
 
-	return r.deleteRetiredNodes(ctx, clusterClient, machinepool.Status.NodeRefs, machinepool.Spec.ProviderIDList)
+	return r.deleteRetiredNodes(ctx, clusterClient, machinePool.Status.NodeRefs, machinePool.Spec.ProviderIDList)
+}
+
+// isMachinePoolDeleteTimeoutPassed check the machinePool node delete time out.
+func (r *MachinePoolReconciler) isMachinePoolNodeDeleteTimeoutPassed(machinePool *expv1.MachinePool) bool {
+	if !machinePool.DeletionTimestamp.IsZero() && machinePool.Spec.Template.Spec.NodeDeletionTimeout != nil {
+		if machinePool.Spec.Template.Spec.NodeDeletionTimeout.Duration.Nanoseconds() != 0 {
+			return machinePool.DeletionTimestamp.Add(machinePool.Spec.Template.Spec.NodeDeletionTimeout.Duration).After(time.Now())
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller.go:298]: Should this be Before?

File: exp/internal/controllers/machinepool_controller.go [hunk 19]
```diff
@@ -253,41 +253,64 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
-		m.Spec.Template.Spec.Bootstrap.ConfigRef,
-		&m.Spec.Template.Spec.InfrastructureRef,
+	references := []*corev1.ObjectReference{}
+	// check for external ref
+	if machinePool.Spec.Template.Spec.Bootstrap.ConfigRef != nil {
+		references = append(references, machinePool.Spec.Template.Spec.Bootstrap.ConfigRef)
+	}
+	if machinePool.Spec.Template.Spec.InfrastructureRef != (corev1.ObjectReference{}) {
+		references = append(references, &machinePool.Spec.Template.Spec.InfrastructureRef)
 	}
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller.go:314]: Why are we making infrastructureRef optional?

File: exp/internal/controllers/machinepool_controller_test.go [hunk 20]
```diff
@@ -428,6 +525,11 @@ func TestReconcileMachinePoolRequest(t *testing.T) {
 				APIReader: clientFake,
 			}
 
+			// Set the tracker.
+			if tc.withTracker {
+				r.Tracker = remote.NewTestClusterCacheTracker(ctrl.LoggerFrom(context.TODO()), clientFake, clientFake, clientFake.Scheme(), client.ObjectKey{Name: testCluster.Name, Namespace: testCluster.Namespace})
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_test.go:530]:
```suggestion
				r.Tracker = remote.NewTestClusterCacheTracker(ctrl.LoggerFrom(ctx), clientFake, clientFake, clientFake.Scheme(), client.ObjectKey{Name: testCluster.Name, Namespace: testCluster.Namespace})
```

File: exp/internal/controllers/machinepool_controller_test.go [hunk 21]
```diff
@@ -302,6 +305,7 @@ func TestReconcileMachinePoolRequest(t *testing.T) {
 	testCases := []struct {
 		machinePool expv1.MachinePool
 		expected    expected
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_test.go:307]: Let's improve these tests:
* let's add a name field and describe what these test cases are doing and use that name field in l.511 with t.Run instead of the MachinePool names
* let's please add verification that the MachinePools are actually gone or not. If I see correctly we currently only check for errors

File: exp/internal/controllers/machinepool_controller_test.go [hunk 22]
```diff
@@ -397,7 +403,61 @@ func TestReconcileMachinePoolRequest(t *testing.T) {
...
+					ClusterName: "test-cluster",
+					Replicas:    ptr.To[int32](1),
+					Template: clusterv1.MachineTemplateSpec{
+						Spec: clusterv1.MachineSpec{
+							InfrastructureRef: corev1.ObjectReference{
+								APIVersion: builder.InfrastructureGroupVersion.String(),
+								Kind:       builder.TestInfrastructureMachineTemplateKind,
+								Name:       "infra-config1",
+							},
+							NodeDeletionTimeout: &metav1.Duration{Duration: -3 * time.Hour},
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_test.go:450]: Let's please use only positive timeouts

File: exp/internal/controllers/machinepool_controller.go (hunk 18 above)
Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller.go:298]: Let's please add unit tests that specifically very this func

File: exp/internal/controllers/machinepool_controller_test.go (hunk 21 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller_test.go:307]: done

File: exp/internal/controllers/machinepool_controller_test.go (hunk 22 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller_test.go:450]: okay

File: exp/internal/controllers/machinepool_controller_test.go (hunk 20 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller_test.go:530]: done

File: exp/internal/controllers/machinepool_controller.go (hunk 17 above)
Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller.go:287]: That seems pretty strange. I think we should just setup a ClusterCacheTracker in our unit tests instead of having handling like this in our production code. But okay let's keep it as is, it won't actually happen at regula runtime, so it's not really a problem to check

File: exp/internal/controllers/machinepool_controller.go [hunk 23]
```diff
@@ -253,41 +254,67 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, cluster *clusterv
...
-		// Return early and don't remove the finalizer if we got an error.
-		return err
+	// check nodes delete timeout passed.
+	if !r.isMachinePoolNodeDeleteTimeoutPassed(machinePool) {
+		if err := r.reconcileDeleteNodes(ctx, cluster, machinePool); err != nil {
+			// Return early and don't remove the finalizer if we got an error.
+			return err
+		}
+	} else {
+		ctrl.LoggerFrom(ctx).Info("MachinePool %s NodeDeleteTimeout passed, force delete the machinePool", machinePool.Namespace, machinePool.Name)
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller.go:272]:
```suggestion
		ctrl.LoggerFrom(ctx).Info("NodeDeleteTimeout passed, skipping Node deletion")
```

No need to add the MachinePool. Controller-runtime already adds the reconciled object

(Please note: Info doesn't take a format string + args, it takes k/v pairs)

File: exp/internal/controllers/machinepool_controller.go (hunk 19 above)
Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller.go:318]: Usually I would prefer not having handling like this in production code because we are specifying invalid objects in unit tests

File: exp/internal/controllers/machinepool_controller_test.go (hunk 21 above)
Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_test.go:308]: Thx!

File: exp/internal/controllers/machinepool_controller_test.go [hunk 24]
```diff
@@ -336,82 +342,141 @@ func TestReconcileMachinePoolRequest(t *testing.T) {
...
 						},
 					},
 				},
 			},
 			expected: expected{
-				result: reconcile.Result{},
-				err:    false,
+				mpExist: false,
+				result:  reconcile.Result{},
+				err:     true,
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_test.go:433]:
```suggestion
				// Note: We expect an error here because patchHelper won't be able to patch the MachinePool after the finalizer was removed (and the MachinePool object is then gone)
				// The important part is that we verify that the MachinePool doesn't exist anymore
				err:     true,
```

File: exp/internal/controllers/machinepool_controller_test.go [hunk 25]
```diff
@@ -336,82 +342,141 @@ func TestReconcileMachinePoolRequest(t *testing.T) {
...
+							Name:       "test-node",
+						},
+					},
+				},
+			},
+			expected: expected{
+				mpExist: true,
+				result:  reconcile.Result{},
+				err:     true,
 			},
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_test.go:473]:
```suggestion
			},
			withTracker: true,
```
Otherwise we are always hitting the code path that the tracker is nil. I think that his not what we want to test here

Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_test.go:473]: Actually let's please drop the withTracker field and let's just always set the tracker. I don't see a reason why we should test the case where Tracker is not set, as this never happens at runtime

File: exp/internal/controllers/machinepool_controller_test.go [hunk 26]
```diff
@@ -336,82 +342,141 @@ func TestReconcileMachinePoolRequest(t *testing.T) {
...
 		},
 	}
 
 	for i := range testCases {
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_test.go:477]: If I understand correctly this is a bit racy:
* In some cases we will only get errors if the patchHelper fails to update the MachinePool, if the MachinePool goes away quickly enough after reconcileDelete removes the finalizer
  * => I would suggest to drop the error check
* In some cases mpExist is set to true, even though we expect the MachinePool to go away after the finalizer is removed
  * => I would recommend to change the check for mpExists to use Eventually & Consistently

```go
			if tc.expected.mpExist {
				g.Consistently(func(g Gomega) {
					g.Expect(r.Client.Get(ctx, key, &expv1.MachinePool{})).To(Succeed())
				}).WithTimeout(2 * time.Second)
			} else {
				// We expect to fail retrieve the machinePool as it is deleted
				g.Eventually(func(g Gomega) {
					g.Expect(apierrors.IsNotFound(r.Client.Get(ctx, key, &expv1.MachinePool{}))).To(BeTrue())
				}).WithTimeout(5 * time.Second)
			}
```

Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_test.go:477]: Once these changes are made, the assertions are correct, but I think the last test case doesn't succeed anymore. Looks like the MP deletion is not actually blocked with our current test setup

**Comment by sbueringer** [comment]
I think we're almost there :)

**Comment by sbueringer** [comment]
@serngawy If you got some time, if we get the findings addressed pretty soon, we'll get this merged in time for v1.8 :)

**Comment by serngawy** [comment]
> @serngawy If you got time, if we get the findings addressed pretty soon, we'll get this merged in time for v1.8 :) (just a heads up)
> 
> (Feel free to ping me in Slack for another review)

Thanks @sbueringer for the follow up. Unfortunately in PTO this week, will work on it next week.

**Comment by sbueringer** [comment]
> > @serngawy If you got time, if we get the findings addressed pretty soon, we'll get this merged in time for v1.8 :) (just a heads up)
> > (Feel free to ping me in Slack for another review)
> 
> Thanks @sbueringer for the follow up. Unfortunately in PTO this week, will work on it next week.

Enjoy your time off!

File: exp/internal/controllers/machinepool_controller_test.go (hunk 25 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller_test.go:473]: We set here the tracker to nil cause we don't want execute [delete_nodes.](https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/internal/controllers/machinepool_controller.go#L283) Otherwise the node is not retrievable and it will be ignored [ignore_nodes](https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/internal/controllers/machinepool_controller_noderef.go#L136). We want to be sure when nodeTimeout set to zero the machinePool will continues try to delete

File: exp/internal/controllers/machinepool_controller.go [hunk 27]
```diff
@@ -273,41 +274,67 @@ func (r *MachinePoolReconciler) reconcile(ctx context.Context, s *scope) (ctrl.R
...
-		// Return early and don't remove the finalizer if we got an error.
-		return err
+	// check nodes delete timeout passed.
+	if !r.isMachinePoolNodeDeleteTimeoutPassed(machinePool) {
+		if err := r.reconcileDeleteNodes(ctx, cluster, machinePool); err != nil {
+			// Return early and don't remove the finalizer if we got an error.
+			return err
+		}
+	} else {
+		ctrl.LoggerFrom(ctx).Info("NodeDeleteTimeout passed, Nodes will be deleted")
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller.go:292]: Is this correct? I was suggesting "skipping Node deletion" because we are not actually deleting the Nodes

File: exp/internal/controllers/machinepool_controller_test.go (hunk 25 above)
Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_test.go:473]: So this test tests that we are getting errors when the Tracker is not set? Which is something that never happens in reality. I would be much more comfortable with our test coverage if we would test real cases instead of something like this

Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_test.go:473]: It should be possible to create a few Nodes with some finalizers that block deletion in the fake cluster cache tracker

File: exp/internal/controllers/machinepool_controller_test.go (hunk 26 above)
Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_test.go:477]: Not sure if this is still a problem since we merged https://github.com/kubernetes-sigs/cluster-api/pull/10787

**Comment by sbueringer** [comment]
Please rebase this PR on top of main instead of merging main into this PR.

I don't remember the exact reason, but I think we run into problems when we merge PRs that have merge commits

**Comment by sbueringer** [comment]
Let's rebase onto main, address https://github.com/kubernetes-sigs/cluster-api/pull/10553#discussion_r1688387841 and then merge this PR

I'll probably to another iteration on the unit tests. I would prefer testing slightly more realistic scenarios

File: exp/internal/controllers/machinepool_controller_test.go (hunk 26 above)
Comment (serngawy) [reply exp/internal/controllers/machinepool_controller_test.go:477]: oh yes, you are right I re-based the PR.

**Comment by sbueringer** [comment]
Thank you!

/lgtm
/test pull-cluster-api-e2e-main 

/assign @chrischdi

File: exp/internal/webhooks/machinepool.go [hunk 28]
```diff
@@ -108,6 +112,11 @@ func (webhook *MachinePool) Default(ctx context.Context, obj runtime.Object) err
 		m.Spec.Template.Spec.InfrastructureRef.Namespace = m.Namespace
 	}
 
+	// Set the default value for the node deletion timeout.
+	if m.Spec.Template.Spec.NodeDeletionTimeout == nil {
+		m.Spec.Template.Spec.NodeDeletionTimeout = &metav1.Duration{Duration: defaultNodeDeletionTimeout}
+	}
```
Comment (chrischdi) [inline exp/internal/webhooks/machinepool.go:118]: Adding defaulting to 10 seconds IMHO is a change in the behaviour of the controller.

Should we mark this as feature (❇️ ) or breaking change in the tilte (✨ )?

Note: this should not get cherry-picked to older release branches.

**Review by chrischdi — COMMENTED** [review]
Can we change the title to something which better describes this change?

I think this currently not only makes "MachinePools to honour the NodeDeletionTimeout".

Am I right that this also helps deleting a MachinePool when `Bootstrap.ConfigRef` or `InfrastructureRef` is not set?

If yes the title should highlight both because it will be part of release notes.

**Comment by chrischdi** [comment]
/retitle ✨ MachinePools: Use NodeDeletionTimeout and default it to 10s

/approve
/hold cancel
