### PR TITLE
🐛 Fix panic in clusterctl describe from nil reference

### LINKED ISSUE #5226: Clusterctl describe cluster panics with invalid clusterclass definition
**What steps did you take and what happened:**
1) Create a clusterclass that includes a non-existent template name under `workers.machineDeployments[*].template.infrastructure.ref.name`
2) Create a cluster that uses the clusterClass from (1)
3) Run `clusterctl describe cluster` on the cluster from (2)
4) See panic in output

**What did you expect to happen:**
Clusterctl to handle the error gracefully

**Environment:**

- Cluster-api version: c50aa1f673e9b3ac255416eacbe69eaaee06d3ae- 

/kind bug

### PR DESCRIPTION
**Pull request by killianmuldoon**
**What this PR does / why we need it**:
This PR catches an error in clusterctl triggered by a cluster with nil infrastructure or other references. This issue was introduced by the clusterClass flow where these references are initially set to nil. This fix checks if object references are nil before running an external client Get.

Fixes #5226

### CODE REVIEW

**Comment by sbueringer** [comment]
I'm fine with the nil check and returning an error in this case, but I assume `clusterctl describe` will now return an error until the ref is set. I don't think that's the behaviour we want.

**Comment by killianmuldoon** [comment]
With this check clusterctl will return an almost empty tree, but won't throw an error i.e. 
```
NAME            READY  SEVERITY  REASON  SINCE  MESSAGE
/first-cluster                                         

```

This isn't an ideal result in the case where the cluster is misconfigured - users will still need to go to the logs to find out what's wrong there. We could add a message, but I don't know if it's necessary for a complete 'template does not exist' style misconfiguration.

**Comment by sbueringer** [comment]
Ah so clusterctl describe already ignores return errors from the `.Get` func? (Sorry didn't have time to take a closer look at the surrounding code)

File: controllers/external/util.go [hunk 1]
```diff
@@ -39,6 +39,9 @@ const (
 
 // Get uses the client and reference to get an external, unstructured object.
 func Get(ctx context.Context, c client.Client, ref *corev1.ObjectReference, namespace string) (*unstructured.Unstructured, error) {
+	if ref == nil {
+		return nil, errors.Errorf("Cannot get object - object reference not set")
```
Comment (vincepri) [inline controllers/external/util.go:43]:
```suggestion
		return nil, errors.Errorf("cannot get object from an empty reference")
```

We usually start error messages lowercase, log lines with uppercase

**Comment by killianmuldoon** [comment]
Yeah - the code is like this: 

`
	// Adds cluster infra
	if clusterInfra, err := external.Get(ctx, c, cluster.Spec.InfrastructureRef, cluster.Namespace); err == nil {
		tree.Add(cluster, clusterInfra, ObjectMetaName("ClusterInfrastructure"))
	}

	// Adds control plane
	controlPLane, err := external.Get(ctx, c, cluster.Spec.ControlPlaneRef, cluster.Namespace)
	if err == nil {
		tree.Add(cluster, controlPLane, ObjectMetaName("ControlPlane"), GroupingObject(true))
	}

`
If there's an error it just skips ahead and tries with the next objectReference. We could add a message here if the object reference isn't available.

**Comment by fabriziopandini** [comment]
> With this check clusterctl will return an almost empty tree, but won't throw an error i.e.
>
> NAME            READY  SEVERITY  REASON  SINCE  MESSAGE
> /first-cluster                                         
>
> This isn't an ideal result in the case where the cluster is misconfigured - users will still need to go to the logs to find out what's > wrong there. We could add a message, but I don't know if it's necessary for a complete 'template does not exist' style  misconfiguration.

IMO what should happen is that:
1. describe should never panic.
2. in case the references are missing because the managed topology has not been yet reconciled, it is ok to see an almost empty tree
3. in case the references are missing due to misconfiguration is it ok to see an almost empty tree, however a condition should surface the problem at Cluster level.

Currently there are no ClusterClass related conditions but it is on my TODO to open an issue for this; I'm going to add 3 as a use case to be addressed by conditions.
