### PR TITLE
:sparkles: Support e2e for WSL

### LINKED ISSUE #10103: Add support for running E2E tests on WSL
### What steps did you take and what happened?

When using `GetWorkloadCluster` as follows with the Docker provider on WSL, we are unable to reach the API server.

```
clusterProxy := input.ClusterProxy.GetWorkloadCluster(ctx, input.Namespace, input.ClusterName)
g.Expect(clusterProxy.GetClient().Get(ctx, client.ObjectKey{Name: kubesystem}, ns)).To(Succeed(), "Failed to get kube-system namespace")
```

```
<*fmt.wrapError | 0xc001c74040>:
failed to get API group resources: unable to retrieve the complete list of server APIs: v1: Get "https://172.18.0.4:6443/api/v1": dial tcp 172.18.0.4:6443: i/o timeout
{
    msg: "failed to get API group resources: unable to retrieve the complete list of server APIs: v1: Get \"https://172.18.0.4:6443/api/v1\": dial tcp 172.18.0.4:6443: i/o timeout",
    err: <*apiutil.ErrResourceDiscoveryFailed | 0xc00008e110>{
        {Group: "", Version: "v1"}: <*url.Error | 0xc001ebc000>{
            Op: "Get",
            URL: "https://172.18.0.4:6443/api/v1",
            Err: <*net.OpError | 0xc001a1c050>{
                Op: "dial",
                Net: "tcp",
                Source: nil,
                Addr: <*net.TCPAddr | 0xc0007d3dd0>{
                    IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 172, 18, 0, 4],
                    Port: 6443,
                    Zone: "",
                },
                Err: <*net.timeoutError | 0x5764c60>{},
            },
        },
    },
}
```

The API server address shown is the one we need to [fix for the kubeconfig](https://cluster-api.sigs.k8s.io/clusterctl/developers#fix-kubeconfig-when-using-docker-desktop-and-clusterctl). It seems like [this check to fix the kubeconfig](https://github.com/kubernetes-sigs/cluster-api/blob/97782fe6dfe733504283f8c46d5d9adac93a4526/test/framework/cluster_proxy.go#L292) only applies to darwin, but we might need it by default.

### What did you expect to happen?

To be able to query the workload cluster using the client we got from the Cluster proxy.

### Cluster API version

v1.6.0

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by nasusoba**
**What this PR does / why we need it**:
When running `e2e` with WSL, the API address from the Docker network could not be used to connect to the workload cluster, instead, we need to use `localhost:load-balancer-host-port`. `fixConfig` done the fix, but for now it only applies to `darwin`.

This PR add check to see if the current environment is WSL, based on the env variable `WSL_DISTRO_NAME`. If so, it will use load balancer host port to access the workload cluster.

After the fix, on WSL, the e2e will be supported.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10103

/area testing

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

**Comment by nasusoba** [comment]
need to verify if this change breaks normal Linux Docker engine (that is not `WSL`)...

**Comment by killianmuldoon** [comment]
If you can that would be good - but I think this change will run through the e2e tests in linux so we should have at least one data point

**Comment by sbueringer** [comment]
/approve

/assign @chrischdi 

Thx folks for testing!

Let's go ahead with this.

**Comment by nasusoba** [comment]
Seems that the conformance test is broken after the change...  kubetest relies on docker network [ref](https://github.com/kubernetes-sigs/cluster-api/blob/ab7b580d4f7f5446671b9a6986521befb71d9601/test/framework/kubetest/run.go#L246C1-L252C3) . Need more works to check nothing is broken for all platforms

**Comment by chrischdi** [comment]
Jep, conformance fails, so this one is a no-go currently.

**Comment by sbueringer** [comment]
What about only changing the behavior for WSL?

I wouldn't want to start messing with our Linux setup if it's not absolutely safe?

**Comment by nasusoba** [comment]
I'm able to get the conformance test run on `WSL`, but there are still two failures for kubetest, does anyone have any clue why it is failing?
```
 Apr 12 09:53:12.500: INFO: Service reachability failing with error: error running /usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig --namespace=services-7890 exec execpod-affinity9bnjm -- /bin/sh -x -c echo hostName | nc -v -t -w 2 affinity-clusterip-transition 80:
    Command stdout:
  
    stderr:
    + echo hostName
    + nc -v -t -w 2 affinity-clusterip-transition 80
    nc: connect to affinity-clusterip-transition port 80 (tcp) timed out: Operation in progress
    command terminated with exit code 1
  
    error:
    exit status 1
    Retrying...
    Apr 12 09:53:12.500: INFO: Unexpected error: 
        <*errors.errorString | 0xc001853280>: 
        service is not reachable within 2m0s timeout on endpoint affinity-clusterip-transition:80 over TCP protocol
        {
            s: "service is not reachable within 2m0s timeout on endpoint affinity-clusterip-transition:80 over TCP protocol",
        }
    [FAILED] in [It] - test/e2e/network/service.go:4024 @ 04/12/24 09:53:12.5
    Apr 12 09:53:12.500: INFO: Cleaning up the exec pod

...

 Summarizing 2 Failures:
    [FAIL] [sig-network] Services [It] should have session affinity work for NodePort service [LinuxOnly] [Conformance] [sig-network, Conformance]
    test/e2e/network/service.go:4024
    [FAIL] [sig-network] Services [It] should be able to switch session affinity for service with type clusterIP [LinuxOnly] [Conformance] [sig-network, Conformance]
    test/e2e/network/service.go:4024
  
  Ran 138 of 7407 Specs in 3604.191 seconds
  FAIL! - Suite Timeout Elapsed -- 136 Passed | 2 Failed | 1 Flaked | 0 Pending | 7269 Skipped
```

**Comment by sbueringer** [comment]
Sorry, no idea. In general if it helps, it's fine to incrementally improve (and merge) and that only these tests fail is a big step forward

**Comment by nasusoba** [comment]
@chrischdi, I have verified the change enables e2e on WSL. Please help continue with the review!

File: test/framework/cluster_proxy.go [hunk 1]
```diff
@@ -456,3 +456,13 @@ func (p *clusterProxy) Dispose(ctx context.Context) {
 		}
 	}
 }
+
+// IsEnvWSL checks if the current environment is Windows Subsystem for Linux (WSL).
+// If so, with the Docker provider, we could not access the cluster with docker network.
+func IsEnvWSL() bool {
```
Comment (chrischdi) [inline test/framework/cluster_proxy.go:462]:
```suggestion
func isEnvWSL() bool {
```

Let's not export this.

File: test/framework/cluster_proxy.go [hunk 2]
```diff
@@ -456,3 +456,13 @@ func (p *clusterProxy) Dispose(ctx context.Context) {
...
+	if distroName := os.Getenv("WSL_DISTRO_NAME"); distroName != "" {
+		return true
+	}
+
+	return false
```
Comment (chrischdi) [inline test/framework/cluster_proxy.go:467]:
```suggestion
	return os.Getenv("WSL_DISTRO_NAME") != "" 
```

File: test/framework/cluster_proxy.go (hunk 1 above)
Comment (nasusoba) [reply test/framework/cluster_proxy.go:462]: I'm using this func in pkg `kubetest`, maybe we could just remove the function and use `os.Getenv("WSL_DISTRO_NAME") != "" ` in pkg `kubetest`??

Comment (sbueringer) [reply test/framework/cluster_proxy.go:462]: +1. Sometimes copying is better than a dependency (+ exposing a public func)

**Comment by sbueringer** [comment]
/lgtm
/approve

Fine to merge (remove hold) from my side

**Review by chrischdi — COMMENTED** [review]
Also for me

/hold cancel
