### PR TITLE
🌱 Avoid KCP rollouts if only ControlPlaneComponentHealthCheckSeconds is changed

### LINKED ISSUE #13017: Unexpected rollout when using KCP and updating to v1.11
### What steps did you take and what happened?

```
make kind-cluster
export CLUSTER_TOPOLOGY=true
clusterctl init --wait-providers --core cluster-api:v1.10.8 --bootstrap kubeadm:v1.10.8 --control-plane kubeadm:v1.10.8 --infrastructure docker:v1.10.8

clusterctl-v1.10.5 generate cluster capi-quickstart --flavor development --kubernetes-version v1.32.8 --control-plane-machine-count=1 --worker-machine-count=1 > cluster.yaml

# pre-create custom KubeadmControlPlaneTemplate
cat <<EOF | kubectl create -f -
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: quick-start-control-plane
  namespace: default
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            timeoutForControlPlane: 20m
            certSANs:
            - localhost
            - 127.0.0.1
            - 0.0.0.0
            - host.docker.internal
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              v: "4"
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              v: "4"
EOF

# Use `kubectl create` to not replace the above created template
kubectl create -f cluster.yaml

# remove mhc
kubectl edit clusterclass quick-start

kubectl wait --timeout=5m --for='jsonpath={.status.conditions[?(@.type=="Ready")].status}=True' cluster/capi-quickstart

kind get kubeconfig --name capi-quickstart > quickstart.kubeconfig
kubectl apply -f test/e2e/data/cni/kindnet/kindnet.yaml --kubeconfig quickstart.kubeconfig


# This command triggers a rollout for KCP.
clusterctl upgrade apply --wait-providers --contract v1beta2
```

### What did you expect to happen?

No rollout to happen

### Cluster API version

Update from v1.10.8 to v1.11.3

### Kubernetes version

_No response_

### Anything else you would like to add?

The diff happens because the v1beta1 version of KCP (before the upgrade):

* has a value set at `spec.kubeadmConfigSpec.clusterConfiguration.apiServer.timeoutForControlPlane`

Conversion seems to lead that in v1beta2 it then detects a diff, because in the joinConfiguration there is nothing set for `.timeouts.controlPlaneComponentsHealthCheckSeconds`.

diff happening:

```
I1120 13:08:35.689312       1 controller.go:477] "Rolling out Control Plane machines: Machine capi-quickstart-shntc-8c4xj needs rollout: Machine KubeadmConfig InitConfiguration or JoinConfiguration are outdated: diff: &v1beta2.KubeadmConfigSpec{\n    ClusterConfiguration: {},\n    InitConfiguration: v1beta2.InitConfiguration{\n      BootstrapTokens: nil,\n      NodeRegistration: v1beta2.NodeRegistrationOptions{\n        Name:                  \"\",\n        CRISocket:             \"\",\n        Taints:                nil,\n-       KubeletExtraArgs:      []v1beta2.Arg{{Name: \"v\", Value: &\"4\"}},\n+       KubeletExtraArgs:      nil,\n        IgnorePreflightErrors: nil,\n        ImagePullPolicy:       \"IfNotPresent\",\n        ImagePullSerial:       nil,\n      },\n      LocalAPIEndpoint: {},\n      SkipPhases:       nil,\n      Patches:          {},\n      Timeouts: v1beta2.Timeouts{\n-       ControlPlaneComponentHealthCheckSeconds: &1200,\n+       ControlPlaneComponentHealthCheckSeconds: nil,\n        KubeletHealthCheckSeconds:               nil,\n        KubernetesAPICallSeconds:                nil,\n        ... // 3 identical fields\n      },\n    },\n    JoinConfiguration: v1beta2.JoinConfiguration{\n      NodeRegistration: v1beta2.NodeRegistrationOptions{\n        Name:                  \"\",\n        CRISocket:             \"\",\n        Taints:                nil,\n-       KubeletExtraArgs:      nil,\n+       KubeletExtraArgs:      []v1beta2.Arg{{Name: \"v\", Value: &\"4\"}},\n        IgnorePreflightErrors: nil,\n        ImagePullPolicy:       \"IfNotPresent\",\n        ImagePullSerial:       nil,\n      },\n      CACertPath: \"\",\n      Discovery:  {},\n      ... // 4 identical fields\n    },\n    Files:     {{Path: \"/etc/kubernetes/kube-apiserver-admission-pss.yaml\", Content: \"apiVersion: apiserver.config.k8s.io/v1\\nkind: AdmissionConfigurat\"...}},\n    DiskSetup: {},\n    ... // 9 identical fields\n  }" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="default/capi-quickstart-shntc" namespace="default" name="capi-quickstart-shntc" reconcileID="b267a0d5-e02c-4d65-ab36-c1009ce59c53" Cluster="default/capi-quickstart" machinesNeedingRollout=["capi-quickstart-shntc-8c4xj"]
```

Better formatted:

```
I1120 13:08:35.689312       1 controller.go:477] "Rolling out Control Plane machines: Machine capi-quickstart-shntc-8c4xj needs rollout: Machine KubeadmConfig InitConfiguration or JoinConfiguration are outdated: diff:
&v1beta2.KubeadmConfigSpec{
    ClusterConfiguration: {},
    InitConfiguration: v1beta2.InitConfiguration{
      BootstrapTokens: nil,
      NodeRegistration: v1beta2.NodeRegistrationOptions{
        Name:                  \"\",
        CRISocket:             \"\",
        Taints:                nil,
-       KubeletExtraArgs:      []v1beta2.Arg{{Name: \"v\", Value: &\"4\"}},
+       KubeletExtraArgs:      nil,
        IgnorePreflightErrors: nil,
        ImagePullPolicy:       \"IfNotPresent\",
        ImagePullSerial:       nil,
      },
      LocalAPIEndpoint: {},
      SkipPhases:       nil,
      Patches:          {},
      Timeouts: v1beta2.Timeouts{
-       ControlPlaneComponentHealthCheckSeconds: &1200,
+       ControlPlaneComponentHealthCheckSeconds: nil,
        KubeletHealthCheckSeconds:               nil,
        KubernetesAPICallSeconds:                nil,
        ... // 3 identical fields
      },
    },
    JoinConfiguration: v1beta2.JoinConfiguration{
      NodeRegistration: v1beta2.NodeRegistrationOptions{
        Name:                  \"\",
        CRISocket:             \"\",
        Taints:                nil,
-       KubeletExtraArgs:      nil,
+       KubeletExtraArgs:      []v1beta2.Arg{{Name: \"v\", Value: &\"4\"}},
        IgnorePreflightErrors: nil,
        ImagePullPolicy:       \"IfNotPresent\",
        ImagePullSerial:       nil,
      },
      CACertPath: \"\",
      Discovery:  {},
      ... // 4 identical fields
    },
    Files:     {{Path: \"/etc/kubernetes/kube-apiserver-admission-pss.yaml\", Content: \"apiVersion: apiserver.config.k8s.io/v1\
kind: AdmissionConfigurat\"...}},
    DiskSetup: {},
    ... // 9 identical fields
  }" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="default/capi-quickstart-shntc" namespace="default" name="capi-quickstart-shntc" reconcileID="b267a0d5-e02c-4d65-ab36-c1009ce59c53" Cluster="default/capi-quickstart" machinesNeedingRollout=["capi-quickstart-shntc-8c4xj"]
```

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #13017

### CODE REVIEW

File: test/e2e/clusterctl_upgrade_test.go [hunk 1]
```diff
@@ -234,7 +234,7 @@ var _ = Describe("When testing clusterctl upgrades using ClusterClass (v1.9=>cur
 })
 
 // Note: This test should be changed during "prepare main branch", it should test n-2 => current.
-var _ = Describe("When testing clusterctl upgrades using ClusterClass (v1.10=>current) [ClusterClass]", Label("ClusterClass"), func() {
+var _ = Describe("When testing clusterctl upgrades using ClusterClass (v1.10=>current) [ClusterClass] [PR-Blocking]", Label("ClusterClass"), func() {
```
Comment (sbueringer) [inline test/e2e/clusterctl_upgrade_test.go]: This part should **not** be merged
/hold

**Comment by sbueringer** [comment]
Could reproduce via:
* https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/13026/pull-cluster-api-e2e-blocking-main/1991741467353157632
* https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/13026/pull-cluster-api-e2e-blocking-main/1991741467353157632/artifacts/clusters/clusterctl-upgrade-management-g7j1qv/logs/capi-kubeadm-control-plane-system/capi-kubeadm-control-plane-controller-manager/capi-kubeadm-control-plane-controller-manager-6857ff88b7-6fbfw/manager.log

Still no idea why the diff shows the field being nil on KCP and set on the Machine KubeadmConfig though

**Comment by chrischdi** [comment]
/retest

Different flake
(fixed via https://github.com/kubernetes-sigs/cluster-api/pull/13031 )

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by chrischdi** [comment]
/lgtm

Thanks!

**Comment by sbueringer** [comment]
Independent flakes

/override pull-cluster-api-e2e-main-gke

**Comment by phoban01** [comment]
Can we get this back-ported to v1.11?

**Comment by sbueringer** [comment]
@phoban01 See https://github.com/kubernetes-sigs/cluster-api/pull/13030
