### PR TITLE
:bug: Fix cluster name conversions a2 > a3

### LINKED ISSUE #2153: ClusterName not set everywhere when converting from v1a2 > v1a3
**What steps did you take and what happened:**
Submit a v1a2 MachineDeployment to a v1a3 controller and get the error "`spec.Template.ClusterName` should be at least 1 chars".

**What did you expect to happen:**
Working MachineDeployment

**Anything else you would like to add:**
In the conversion step the `clusterName` is [set for the MachineDeployment spec](https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha2/conversion.go#L204) but not the spec in the Template.

/kind bug
/assign
/lifecycle active

### PR DESCRIPTION
**Pull request by johnharris85**
Signed-off-by: John Harris <joharris@vmware.com>

**What this PR does / why we need it**:
Adds the cluster name field to the MachineDeployment and MachineSet templates when converting from v1alpha2 > v1alpha3. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2153

### CODE REVIEW

File: api/v1alpha2/conversion.go [hunk 1]
```diff
@@ -150,6 +150,7 @@ func (src *MachineSet) ConvertTo(dstRaw conversion.Hub) error {
 	// This conversion can be overwritten when restoring the ClusterName field.
 	if name, ok := src.Labels[MachineClusterLabelName]; ok {
 		dst.Spec.ClusterName = name
+		dst.Spec.Template.Spec.ClusterName = name
```
Comment (vincepri) [inline api/v1alpha2/conversion.go]: We should probably do the same on line 162

File: api/v1alpha2/conversion.go [hunk 2]
```diff
@@ -202,6 +203,7 @@ func (src *MachineDeployment) ConvertTo(dstRaw conversion.Hub) error {
...
```
Comment (vincepri) [inline api/v1alpha2/conversion.go]: We should probably do the same on line 216

**Comment by ncdc** [comment]
Let's make sure we have a unit test that covers this?

**Comment by vincepri** [comment]
Yep, there should be already some that tests the ClusterName, we can modify those

**Comment by ncdc** [comment]
It would be nice if the tests would fail automatically if we had mismatches, rather than having to do it field by field. Could/should we adjust the tests to do a DeepEqual?

**Comment by johnharris85** [comment]
DeepEqual works with a little tweaking on the test. However looking closer it doesn't appear the restore from annotations case is currently being tested (as the test spec doesn't have any annotations so the logic is skipped). I can add tests for those additional (annotation restore) cases as well here if you want? Or in a separate PR?

**Comment by ncdc** [comment]
Let's keep your PR focused and we can change the test logic separately. Thanks!

File: api/v1alpha2/conversion.go [hunk 3]
```diff
@@ -202,6 +204,7 @@ func (src *MachineDeployment) ConvertTo(dstRaw conversion.Hub) error {
...
```
Comment (detiber) [inline api/v1alpha2/conversion.go]: This conversion will result in a changed hash for the deployment. We'll need to keep that in mind with the v1alpha3 release notes.

Comment (ncdc) [reply api/v1alpha2/conversion.go]: xref https://kubernetes.slack.com/archives/C8TSNPY4T/p1580231398178200 - conversation about whether or not a different hash induces a rolling upgrade.

also xref #1938 where we previously discussed this concern

**Comment by johnharris85** [comment]
Added the above to the existing unit tests.

**Comment by ncdc** [comment]
/hold
👀

File: api/v1alpha2/conversion.go [hunk 4]
```diff
@@ -160,6 +161,7 @@ func (src *MachineSet) ConvertTo(dstRaw conversion.Hub) error {
 
 	if restored.Spec.ClusterName != "" {
 		dst.Spec.ClusterName = restored.Spec.ClusterName
+		dst.Spec.Template.Spec.ClusterName = restored.Spec.ClusterName
```
Comment (ncdc) [inline api/v1alpha2/conversion.go]: This should not be necessary, should it? This is handled by the call to `restoreMachineSpec` 2 lines down.

File: api/v1alpha2/conversion.go [hunk 5]
```diff
@@ -212,6 +215,7 @@ func (src *MachineDeployment) ConvertTo(dstRaw conversion.Hub) error {
...
```
Comment (ncdc) [inline api/v1alpha2/conversion.go]: This should not be necessary, should it? This is handled by the call to restoreMachineSpec.

File: api/v1alpha2/conversion.go (hunk 3 above)
Comment (ncdc) [reply api/v1alpha2/conversion.go]: Recording here for posterity: we want to do #2183, and the hash is not relevant in terms of rolling updates.

File: api/v1alpha2/conversion.go (hunk 5 above)
Comment (vincepri) [reply api/v1alpha2/conversion.go]: ah that's right, I forgot we added that other function. The restore from the label is still required though
