### PR TITLE
Fixes a bug in GetClusterByName

### LINKED ISSUE #1229: GetOwnerCluster should lookup using ref name not metadata name
/kind bug

**What steps did you take and what happened:**
The function `util.GetOwnerCluster` should lookup the owning cluster by name not by metadata name.

/lifecycle active
/priority important-soon

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
This fixes a but in GetOwnerCluster and scopes down the client to exactly what this function needs. This improves testability and scope of the function.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1229 

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

/assign @ncdc @detiber

### CODE REVIEW

**Comment by vincepri** [comment]
/approve

Change looks fine to me, I’d prefer using the fake client offered by controller-runtime instead of having a new interface, wdyt?

https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/fake

File: pkg/util/util.go [hunk 1]
```diff
@@ -166,18 +166,23 @@ func GetClusterFromMetadata(ctx context.Context, c client.Client, obj metav1.Obj
 	return GetClusterByName(ctx, c, obj.Namespace, obj.Labels[clusterv1.MachineClusterLabelName])
 }
 
+// Getter can get an object from the APIServer. client.Client satisfies this interface.
+type Getter interface {
```
Comment (ncdc) [inline pkg/util/util.go]: I usually default to not exporting - would that make sense here?

**Comment by chuckha** [comment]
@vincepri that's fine

@ncdc mmm, I don't really know which way is better, I'm kinda stuck on both being ok options. Happy to go private since we don't want this interface reused anyway. But honestly if we're using the fake client as @vincepri suggested it can just be client.Client anyway.

**Comment by chuckha** [comment]
@ncdc updated!

**Comment by ncdc** [comment]
@chuckha `gofmt` please!

**Comment by xrmzju** [comment]
https://github.com/kubernetes-sigs/cluster-api/blob/62582da077611649856cb2a88ec73c957e8569f5/pkg/util/util.go#L226 same problem with func `GetOwnerMachine`

**Comment by chuckha** [comment]
@xrmzju can you file an issue for that function like #1229? Let's do one issue at a time.

**Comment by chuckha** [comment]
@ncdc updated!

**Comment by joonas** [comment]
@xrmzju @chuckha I've opened up #1234 to address `GetOwnerMachine` function.
