### PR TITLE
✨only add machinedeployment name selector when selector is empty

### LINKED ISSUE #2287: v1alpha3 conversions create all new Machines for MachineDeployments
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

- create v1alpha2 capi/capi cluster
- scale down all controllers
- apply v1alpha3 components (which scales up capi)
- everything up-converted
- got all new Machines

**What did you expect to happen:**
Conversion should be able to retain existing Machines

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I'm fairly certain this has to do with `cluster.x-k8s.io/deployment-name: my-md-name` being added to MachineDeployments as part of conversion. This label is *not* added to Machines as part of conversion, which means existing Machines are not matching the MachineDeployment's selector. 

Personally, I do not think we should be adding this new label to MachineDeployments, but I could be convinced otherwise. The alternative, though, is to somehow retrieve MachineDeployment name as part of conversion for Machines, which could get spicy.

**Environment:**

- Cluster-api version: master
- Kubernetes version: (use `kubectl version`): 1.16.2

/kind bug

### PR DESCRIPTION
**Pull request by rudoi**
**What this PR does / why we need it**:
Changes MachineDeployment reconciliation to only add MachineDeployment name as a label to selector/template when no other form of selector has been provided. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2287

### CODE REVIEW

File: controllers/machinedeployment_controller.go [hunk 1]
```diff
@@ -148,14 +148,17 @@ func (r *MachineDeploymentReconciler) reconcile(_ context.Context, cluster *clus
 
 	d.Labels[clusterv1.ClusterLabelName] = d.Spec.ClusterName
 
+	// If no selector has been provided, add label and selector for the
+	// MachineDeployment's name as a default way of providing uniqueness.
+	if len(d.Spec.Selector.MatchLabels) == 0 && len(d.Spec.Selector.MatchExpressions) == 0 {
```
Comment (detiber) [inline controllers/machinedeployment_controller.go]: Might be good to add this in the defaulting webhook instead.

@vincepri want to get your thoughts/feedback here as well.

Comment (rudoi) [reply controllers/machinedeployment_controller.go]: I actually agree with that, I temporarily forgot those existed.

File: api/v1alpha3/machinedeployment_webhook.go [hunk 2]
```diff
@@ -129,4 +137,11 @@ func PopulateDefaultsMachineDeployment(d *MachineDeployment) {
 			d.Spec.Strategy.RollingUpdate.MaxUnavailable = &ios0
 		}
 	}
+
+	// If no selector has been provided, add label and selector for the
+	// MachineDeployment's name as a default way of providing uniqueness.
+	if len(d.Spec.Selector.MatchLabels) == 0 && len(d.Spec.Selector.MatchExpressions) == 0 {
+		d.Spec.Selector.MatchLabels[MachineDeploymentLabelName] = d.Name
+		d.Spec.Template.Labels[MachineDeploymentLabelName] = d.Name
+	}
```
Comment (detiber) [inline api/v1alpha3/machinedeployment_webhook.go]: Might be good to go ahead and add a test for this in `machinedeployment_webhook.go`

File: controllers/machinedeployment_controller.go [hunk 3]
```diff
@@ -152,10 +152,6 @@ func (r *MachineDeploymentReconciler) reconcile(_ context.Context, cluster *clus
 	d.Spec.Selector.MatchLabels[clusterv1.ClusterLabelName] = d.Spec.ClusterName
 	d.Spec.Template.Labels[clusterv1.ClusterLabelName] = d.Spec.ClusterName
```
Comment (detiber) [inline controllers/machinedeployment_controller.go]: Not directly related, but might be good to track a followup item to investigate if we should move the handling of ensure the label matching for the ClusterName is present to the Defaulting webhook as well...

File: api/v1alpha3/machinedeployment_webhook.go (hunk 2 above)
Comment (rudoi) [reply api/v1alpha3/machinedeployment_webhook.go]: Agreed, will add.

File: controllers/machinedeployment_controller.go (hunk 3 above)
Comment (rudoi) [reply controllers/machinedeployment_controller.go]: tracking: https://github.com/kubernetes-sigs/cluster-api/issues/2302
marked as good first issue, let me know if that's not suitable. :D

File: api/v1alpha3/machinedeployment_webhook.go (hunk 2 above)
Comment (rudoi) [reply api/v1alpha3/machinedeployment_webhook.go]: added
