### PR TITLE
🐛  update CoreDNS ClusterRole for Kubernetes >= 1.22 and CoreDNS >= 1.8.1

### LINKED ISSUE #4927: capi-e2e-main-1-21-latest fails because of CoreDNS RBAC issues
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

After we changed our 1.21=>latest upgrade tests to CoreDNS 1.8.4 they are failing now ([testgrid](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-21-latest))

**What did you expect to happen:**
They should still work.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

CoreDNS 1.8.4 also uses EndpointSlices. Thus the ClusterRole `system:coredns` has been adapted in kubeadm (https://github.com/kubernetes/kubernetes/pull/102466/files). As we're installing the cluster with 1.21 and then just updating to 1.22 we still have the old ClusterRole. I assume we have to ensure that starting with CoreDNS 1.8.4 the ClusterRole also includes EndpointSlices. 

This problem affects all clusters installed with kubeadm < 1.22 when using CoreDNS >= 1.8.4.

Currently our jobs do not fail when the conformance test fails, but this should be fixed through #4907.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
See issue for details

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4927

### CODE REVIEW

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 1]
```diff
@@ -218,14 +251,52 @@ func (w *Workload) updateCoreDNSDeployment(ctx context.Context, info *coreDNSInf
...
+		}
+
+		updatedClusterRole := coreDNSClusterRole.DeepCopy()
+		updatedClusterRole.ResourceVersion = currentClusterRole.ResourceVersion
+
+		if !reflect.DeepEqual(currentClusterRole, updatedClusterRole) {
+			if err := w.Client.Update(ctx, updatedClusterRole); err != nil {
+				return errors.Wrapf(err, "failed to update ClusterRole %q", coreDNSClusterRoleName)
+			}
+		}
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:295]: We should probably change this code to apply the coreDNSClusterRole `Rules` field on the `currentClusterRole` and not forcing the `ResourceVersion` which effectively gets around the Update strong consistency requirement

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 2]
```diff
@@ -218,14 +251,52 @@ func (w *Workload) updateCoreDNSDeployment(ctx context.Context, info *coreDNSInf
...
+		return err
+	}
+	if targetCoreDNSVersion.LT(semver.Version{Major: 1, Minor: 8, Patch: 1}) {
+		return nil
+	}
+
+	return retry.RetryOnConflict(retry.DefaultBackoff, func() error {
+		var currentClusterRole rbacv1.ClusterRole
+		err = w.Client.Get(ctx, ctrlclient.ObjectKey{Name: coreDNSClusterRoleName, Namespace: metav1.NamespaceSystem}, &currentClusterRole)
+		if err != nil {
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:284]:
```suggestion
		if err := w.Client.Get(ctx, ctrlclient.ObjectKey{Name: coreDNSClusterRoleName, Namespace: metav1.NamespaceSystem}, &currentClusterRole)
```

Comment (vincepri) [reply controlplane/kubeadm/internal/workload_cluster_coredns.go:284]: Also put the ObjectKey outside of the Retry?

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 3]
```diff
@@ -218,14 +251,52 @@ func (w *Workload) updateCoreDNSDeployment(ctx context.Context, info *coreDNSInf
...
 		c.DNS.ImageTag = dns.ImageTag
 	}, version)
 }
 
+// updateCoreDNSClusterRole updates the CoreDNS ClusterRole when necessary.
+// CoreDNS >= 1.8.1 uses EndpointSlices. kubeadm < 1.22 doesn't include the EndpointSlice rule in the CoreDNS ClusterRole.
+// To support Kubernetes clusters >= 1.22 (which have been initialized with kubeadm < 1.22) with CoreDNS versions >= 1.8.1
+// we have to update the ClusterRole accordingly.
+func (w *Workload) updateCoreDNSClusterRole(ctx context.Context, kubernetesVersion semver.Version, info *coreDNSInfo) error {
+	// do nothing for Kubernetes < 1.22
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:267]:
```suggestion
	// Do nothing for Kubernetes < 1.22.
```

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 4]
```diff
@@ -218,14 +251,52 @@ func (w *Workload) updateCoreDNSDeployment(ctx context.Context, info *coreDNSInf
...
+	if kubernetesVersion.LT(semver.Version{Major: 1, Minor: 22, Patch: 0}) {
+		return nil
+	}
+
+	// do nothing for CoreDNS < 1.8.1
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:272]:
```suggestion
	// Do nothing for CoreDNS < 1.8.1.
```

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 5]
```diff
@@ -19,35 +19,65 @@ package internal
...
 )
 
+var (
+	// Source: https://github.com/kubernetes/kubernetes/blob/v1.22.0-beta.1/cmd/kubeadm/app/phases/addons/dns/manifests.go#L178-L207
+	coreDNSClusterRole = &rbacv1.ClusterRole{
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      coreDNSClusterRoleName,
+			Namespace: metav1.NamespaceSystem,
+		},
+		Rules: []rbacv1.PolicyRule{
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:61]: Can we simplify to only list the rules that need to be updated instead of the whole ClusterRole object? Something like `coreDNS181PolicyRules`

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-full-main
/test pull-cluster-api-e2e-workload-upgrade-1-21-latest-main

@vincepri ptal

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 6]
```diff
@@ -218,14 +245,51 @@ func (w *Workload) updateCoreDNSDeployment(ctx context.Context, info *coreDNSInf
...
+		return err
+	}
+	if targetCoreDNSVersion.LT(semver.Version{Major: 1, Minor: 8, Patch: 1}) {
+		return nil
+	}
+
+	key := ctrlclient.ObjectKey{Name: coreDNSClusterRoleName, Namespace: metav1.NamespaceSystem}
+	return retry.RetryOnConflict(retry.DefaultBackoff, func() error {
+		var currentClusterRole rbacv1.ClusterRole
+		if err = w.Client.Get(ctx, key, &currentClusterRole); err != nil {
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:278]:
```suggestion
		if err := w.Client.Get(ctx, key, &currentClusterRole); err != nil {
```

Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:278]:
```suggestion
	currentClusterRole := &rbacv1.ClusterRole{]
		if err = w.Client.Get(ctx, key, currentClusterRole); err != nil {
```

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 7]
```diff
@@ -218,14 +245,51 @@ func (w *Workload) updateCoreDNSDeployment(ctx context.Context, info *coreDNSInf
...
+			return fmt.Errorf("failed to get ClusterRole %q", coreDNSClusterRoleName)
+		}
+
+		if !reflect.DeepEqual(currentClusterRole.Rules, coreDNS181PolicyRules) {
+			updatedClusterRole := currentClusterRole.DeepCopy()
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:283]: Do we need to copy here?

Comment (sbueringer) [reply controlplane/kubeadm/internal/workload_cluster_coredns.go:283]: I think I was confusing it with something along the lines of "we have to deep copy otherwise we will change the object in the cache which could lead to strange bugs". But I assume that's not an issue here as we're using our own object.

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-workload-upgrade-1-21-latest-main
I think it's an unrelated error. Also so that one in the testgrid before. Otherwise I'll take a closer look tomorrow.

**Comment by sbueringer** [comment]
Okay looks like I got the tests green now. I also adjusted our pull image code (which was merged yesterday). So this PR now also fixes all our CI jobs which are using locally build kindest/node images.

I'll squash before merge.

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 8]
```diff
@@ -218,14 +245,50 @@ func (w *Workload) updateCoreDNSDeployment(ctx context.Context, info *coreDNSInf
...
+	}
+
+	key := ctrlclient.ObjectKey{Name: coreDNSClusterRoleName, Namespace: metav1.NamespaceSystem}
+	return retry.RetryOnConflict(retry.DefaultBackoff, func() error {
+		currentClusterRole := &rbacv1.ClusterRole{}
+		if err := w.Client.Get(ctx, key, currentClusterRole); err != nil {
+			return fmt.Errorf("failed to get ClusterRole %q", coreDNSClusterRoleName)
+		}
+
+		if !reflect.DeepEqual(currentClusterRole.Rules, coreDNS181PolicyRules) {
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:282]: Given that these are slices we might have to either sort them, or do a comparison one by one. See https://play.golang.org/p/CJaurc7dzdz

Comment (vincepri) [reply controlplane/kubeadm/internal/workload_cluster_coredns.go:282]: /hold

Comment (sbueringer) [reply controlplane/kubeadm/internal/workload_cluster_coredns.go:282]: Yeah agree. I'll take a closer look tomorrow.

Comment (sbueringer) [reply controlplane/kubeadm/internal/workload_cluster_coredns.go]: I pushed a new commit with an implementation (I'll squash after we got consensus).

I implemented it by building a map with all policies and comparing them with deep equal. While this probably needs a bit more memory (which should be negligible), I think it should be faster then recursively sorting (basically) nested arrays (although that also shouldn't be that important as we're running this code only when updating CoreDNS).

**Comment by sbueringer** [comment]
/assign @fabriziopandini 
(if you have some time, this PR fixes all our upgrade tests again)

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 9]
```diff
@@ -218,14 +245,76 @@ func (w *Workload) updateCoreDNSDeployment(ctx context.Context, info *coreDNSInf
...
+		if err := w.Client.Get(ctx, key, currentClusterRole); err != nil {
+			return fmt.Errorf("failed to get ClusterRole %q", coreDNSClusterRoleName)
+		}
+
+		if !semanticDeepEqualPolicyRules(currentClusterRole.Rules, coreDNS181PolicyRules) {
+			currentClusterRole.Rules = coreDNS181PolicyRules
+			if err := w.Client.Update(ctx, currentClusterRole); err != nil {
+				return errors.Wrapf(err, "failed to update ClusterRole %q", coreDNSClusterRoleName)
+			}
+		}
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:287]: Instead of using update, should we use `Patch` by diffing the before/after objects and apply it using strong consistency?

Comment (sbueringer) [reply controlplane/kubeadm/internal/workload_cluster_coredns.go:287]: We have a lot of other updates here, but I can implement it.

Looks like our patchHelper is  onlyable to patch: spec, metadata and status. As ClusterRole doesn't has a spec I would have to implement the diff by myself. I'll do it if you think it's worth it.

**Review by vincepri — APPROVED** [review]
/lgtm

**Comment by stmcginnis** [comment]
/lgtm

Updates look good, and really nice test coverage on the policy comparison.

**Comment by sbueringer** [comment]
Squashed and rebased onto current main branch

/test pull-cluster-api-e2e-full-main
/test pull-cluster-api-e2e-workload-upgrade-1-21-latest-main

**Comment by fabriziopandini** [comment]
@sbueringer thanks for tackling this!
/lgtm
/approve

**Comment by sbueringer** [comment]
@fabriziopandini There's still a hold from: https://github.com/kubernetes-sigs/cluster-api/pull/4937#discussion_r670516666 should we unhold and merge?
