### PR TITLE
🐛 KCP: expect timeout from target cluster load-balancer

### LINKED ISSUE #2408: Kubeadm control plane controller logs filled with timeout error
**What steps did you take and what happened:**
When deployed with CAPBM, no external load-balancer is created by the infrastructure provider. When KubeadmControlplane controller creates the first machine, it is unable to create the client towards the target cluster and fails with 
```
failed to create remote cluster client: failed to create client for Cluster default/test1: Get https://192.168.111.249:6443/api?timeout=32s: dial tcp 192.168.111.249:6443: i/o timeout
```
The controller is expecting a 404, if the load-balancer is set-up. But it is not expecting a timeout when the control plane load-balancer is self-hosted. Hence the failure. The KCP is also not updated due to the failure.

**What did you expect to happen:**
Optimally, the control plane would be able to expect a timeout, and update the KCP status without filling the logs of errors.

**Anything else you would like to add:**
This can be done by adding `!apierrors.IsTimeout(errors.Cause(err))` on line https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go#L300 and https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go#L787

However, the timeout should maybe still be an error when an external Load-balancer is deployed, so maybe a field could be added in the KCP CRD to be able to configure this ? 

**Environment:**

- Cluster-api version: v0.3.0-rc1

/kind bug

### PR DESCRIPTION
**Pull request by maelk**
**What this PR does / why we need it**:
This PR adds a condition for Kubeadm Control Plane Controller to not fail if getting a timeout from the load-balancer in case it is self-hosted in the target cluster (and does not answer while the first node is not up

**Which issue(s) this PR fixes** :
Fixes #2408

### CODE REVIEW

**Comment by maelk** [comment]
This might need to be configurable. We might want the controller to fail on timeout for external load-balancers.

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go [hunk 1]
```diff
@@ -297,7 +297,7 @@ func (r *KubeadmControlPlaneReconciler) updateStatus(ctx context.Context, kcp *c
 	kcp.Status.Replicas = replicas
 
 	remoteClient, err := r.remoteClientGetter(ctx, r.Client, util.ObjectKey(cluster), r.scheme)
-	if err != nil && !apierrors.IsNotFound(errors.Cause(err)) {
+	if err != nil && !apierrors.IsNotFound(errors.Cause(err)) && !apierrors.IsTimeout(errors.Cause(err)) {
```
Comment (detiber) [inline controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: I'm wondering if we should short-circuit the logic below in the case that we get either of these acceptable errors? It doesn't seem like it would make much sense to attempt to use the client in `getMachineNode` in the case that we see either of these errors.

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go [hunk 2]
```diff
@@ -784,7 +784,7 @@ func getMachineNode(ctx context.Context, crClient client.Client, machine *cluste
 		node,
 	)
 	if err != nil {
-		if apierrors.IsNotFound(errors.Cause(err)) {
+		if apierrors.IsNotFound(errors.Cause(err)) || apierrors.IsTimeout(errors.Cause(err)) {
```
Comment (detiber) [inline controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: If we short-circuit after attempting to retrieve the remote client, can we remove the need to check for `apierrors.IsTimeout` here? I worry that the semantics here are quite a bit different, since the `apierrors.IsNotFound` here is seeing if the api server is telling us that the node does not exist.

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go (hunk 1 above)
Comment (maelk) [reply controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: yes, I'll fix it

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go (hunk 2 above)
Comment (maelk) [reply controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: okay, I'll remove. Thank you

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go [hunk 3]
```diff
@@ -297,21 +297,23 @@ func (r *KubeadmControlPlaneReconciler) updateStatus(ctx context.Context, kcp *c
 	kcp.Status.Replicas = replicas
 
 	remoteClient, err := r.remoteClientGetter(ctx, r.Client, util.ObjectKey(cluster), r.scheme)
-	if err != nil && !apierrors.IsNotFound(errors.Cause(err)) {
+	if err != nil && !apierrors.IsNotFound(errors.Cause(err)) && !apierrors.IsTimeout(errors.Cause(err)) {
 		return errors.Wrap(err, "failed to create remote cluster client")
 	}
 
 	readyMachines := int32(0)
```
Comment (detiber) [inline controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: Please move this declaration up above the call to `r.removeClientGetter` so that the additional handling of `err` below is easier to correlate with the call to `r.removeClientGetter` above.

Comment (maelk) [reply controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: fixed, thank you

**Comment by maelk** [comment]
/hold
I'll simplify into `if err == nil`

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go [hunk 4]
```diff
@@ -295,23 +295,25 @@ func (r *KubeadmControlPlaneReconciler) updateStatus(ctx context.Context, kcp *c
 
 	replicas := int32(len(ownedMachines))
 	kcp.Status.Replicas = replicas
+	readyMachines := int32(0)
 
 	remoteClient, err := r.remoteClientGetter(ctx, r.Client, util.ObjectKey(cluster), r.scheme)
-	if err != nil && !apierrors.IsNotFound(errors.Cause(err)) {
+	if err != nil && !apierrors.IsNotFound(errors.Cause(err)) && !apierrors.IsTimeout(errors.Cause(err)) {
 		return errors.Wrap(err, "failed to create remote cluster client")
 	}
```
Comment (vincepri) [inline controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: Remove this space for readability

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go [hunk 5]
```diff
@@ -295,23 +295,25 @@ func (r *KubeadmControlPlaneReconciler) updateStatus(ctx context.Context, kcp *c
 
 	replicas := int32(len(ownedMachines))
 	kcp.Status.Replicas = replicas
+	readyMachines := int32(0)
 
 	remoteClient, err := r.remoteClientGetter(ctx, r.Client, util.ObjectKey(cluster), r.scheme)
-	if err != nil && !apierrors.IsNotFound(errors.Cause(err)) {
+	if err != nil && !apierrors.IsNotFound(errors.Cause(err)) && !apierrors.IsTimeout(errors.Cause(err)) {
```
Comment (vincepri) [inline controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: If we have only `if err != nil` here, we can use a simple `else` condition for the `range`.

Inside the `if err != nil` block we can also do
```go
if cause := errors.Cause(err); !apierrors.IsNotFound(cause) && !apierrors.IsTimeout(cause) {
...
}
```

Comment (maelk) [reply controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: done, thank you
