### PR TITLE
🐛 Fix flake in capd

### LINKED ISSUE #2223: Fix the identified flake in CAPD
**What steps did you take and what happened:**
The CAPD e2e flake that i'm seeing most is that kubeadm init can't run because docker isn't available on the system yet. This error can be reproduced by this minimal bash script:

```
#!/usr/bin/env sh

set -o xtrace

id=$(docker run --detach --tty --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules kindest/node:v1.16.3)

docker exec -it ${id} kubeadm init --ignore-preflight-errors=all
```

Now, This is exactly what capd is doing with a few more things in between. So most of the time it works since kindest/nodes are very fast to start, but sometimes it results in this error:

```
I0130 14:51:01.444642      70 version.go:251] remote version is much newer: v1.17.2; falling back to: stable-1.16
[init] Using Kubernetes version: v1.16.6
[preflight] Running pre-flight checks
[preflight] WARNING: Couldn't create the interface used for talking to the container runtime: docker is required for container runtime: exec: "docker": executable file not found in $PATH
	[WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
	[WARNING Swap]: running with swap on is not supported. Please disable swap
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: docker is required for container runtime: exec: "docker": executable file not found in $PATH
To see the stack trace of this error execute with --v=5 or higher
```

This can be fixed by waiting for a little bit, but simply running `crictl ps` on the system is a long enough pause to allow the node to start fully.  To test this, simply update the bash script to include this line before `kubeadm init`:

```
docker exec -it ${id} crictl ps
```

My plan here is to add a docker exec `crictl ps` in a loop in the docker machine controller until it passes with a very short timeout (2 seconds at most), but this should execute in well under that. In the grand scheme of things this won't be noticeable by anyone since the tests take ~100 seconds locally and ~200 seconds on prow

/kind bug
/assign
/lifecycle active
/milestone v0.3.0

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>
**What this PR does / why we need it**:
This issue fixes a common flake in the capd-e2e tests. Please see the issue for more detail.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #2223

### CODE REVIEW

**Comment by neolit123** [comment]
@chuckha i commented here trying to understand the problem better:
https://github.com/kubernetes-sigs/cluster-api/issues/2223#issuecomment-580303455

File: test/infrastructure/docker/docker/machine.go [hunk 1]
```diff
@@ -124,10 +128,22 @@ func (m *Machine) Create(role string, version *string) error {
...
-			return errors.WithStack(err)
+			if err != nil {
+				return errors.WithStack(err)
+			}
 		default:
 			return errors.Errorf("unable to create machine for role %s", role)
 		}
+		// After creating a node we need to wait a small amount of time until crictl does not return an error.
+		// This fixes an issue where we try to kubeadm init too quickly after creating the container.
+		err = wait.PollImmediate(500*time.Millisecond, 2*time.Second, func() (bool, error) {
```
Comment (neolit123) [inline test/infrastructure/docker/docker/machine.go]: my understanding is that it depends on the host machine spec so one's mileage may vary.
i guess if the same flakes are seen this can be bumped, but if i remember correctly `crictl ps` implements retries too.

/lgtm

Comment (chuckha) [reply test/infrastructure/docker/docker/machine.go]: /hold

i want to check on crictl ps implementing a retry. I'd much rather rely on that retry than my own home grown one!

Comment (detiber) [reply test/infrastructure/docker/docker/machine.go]: Would it be better to handle this in the cloud-init conversion code? For regular infra providers we are now relying on the ordering of the systemd units associated with cloud-init phases to ensure that containerd is up prior to executing the script that runs kubeadm.

Comment (chuckha) [reply test/infrastructure/docker/docker/machine.go]: interesting, this could also be implemented as a pre-command to kubeadm init as well and then we wouldn't need any code changes at all.

Comment (chuckha) [reply test/infrastructure/docker/docker/machine.go]: Because this is not using the image-builder, and because kind nodes have a different way of configuring CNI and because we don't really have cloud-init, that this makes the most amount of sense for this provider. This code is located directly after the `docker run` command is issued. I think there is an argument for refactoring into a "node ready" function that runs a series of commands to ensure the container is ready, but I think shoe-horning this code into what the image-builder is doing when we aren't using the image builder will cause some confusion down the road.

**Comment by chuckha** [comment]
@neolit123 I don't see any evidence of `crictl ps` doing a retry. The closest thing I found was a grpc dial timeout which isn't quite a retry. However, I cannot reproduce the failure with just issuing a `crictl ps` *without* retrying, but that doesn't mean much so I'm inclined to keep this code how it is. Thanks for the quick feedback & turn around.

/hold cancel

**Comment by neolit123** [comment]
> The closest thing I found was a grpc dial timeout which isn't quite a retry

indeed.

> However, I cannot reproduce the failure with just issuing a crictl ps without retrying, but that doesn't mean much so I'm inclined to keep this code how it is

from my experience this dial timeout of `crictl ps` is probably already more than 2 seconds. so it may be a case that with the current code only the first call to `crictl ps` executes.
