### PR TITLE
🐛 Add AGE column to our CRDs

### LINKED ISSUE #5159: Add AGE column to all our CRDs
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Executed: (against a kind cluster with a few resources deployed)
```bash
$ kubectl get clusterclass,kubeadmcontrolplane,dockercluster,cluster,machinedeployment,dockermachine,machine -A
NAMESPACE   NAME                                             AGE
default     clusterclass.cluster.x-k8s.io/my-cluster-class   150m

NAMESPACE   NAME                                                                 INITIALIZED   API SERVER AVAILABLE   VERSION   REPLICAS   READY   UPDATED   UNAVAILABLE
default     kubeadmcontrolplane.controlplane.cluster.x-k8s.io/my-cluster-b7xhq   true                                 v1.22.0   1                  1         1

NAMESPACE   NAME                                                             AGE
default     dockercluster.infrastructure.cluster.x-k8s.io/my-cluster-mwnr7   77m

NAMESPACE   NAME                                  PHASE
default     cluster.cluster.x-k8s.io/my-cluster   Provisioned

NAMESPACE   NAME                                                                                AGE
default     dockermachine.infrastructure.cluster.x-k8s.io/my-cluster-controlplane-vktk6-7wjkc   6m43s

NAMESPACE   NAME                                              PROVIDERID                          PHASE     VERSION
default     machine.cluster.x-k8s.io/my-cluster-b7xhq-vf767   docker:////my-cluster-b7xhq-vf767   Running   v1.22.0
```

**What did you expect to happen:**

I would have expected to see an AGE column when listing our CRDs with kubectl.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It looks like the `AGE` column is missing for all CRDs which are specifying `additionalPrinterColumns`.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by Jont828**
**What this PR does / why we need it**: This adds the AGE column to all our CRDs to make the printed output consistent with the built in K8s resources.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5159

### CODE REVIEW

File: api/v1alpha4/cluster_types.go [hunk 1]
```diff
@@ -278,6 +278,7 @@ func (v APIEndpoint) String() string {
 // +kubebuilder:resource:path=clusters,shortName=cl,scope=Namespaced,categories=cluster-api
 // +kubebuilder:storageversion
 // +kubebuilder:subresource:status
+// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
```
Comment (vincepri) [inline api/v1alpha4/cluster_types.go:281]: Does this do the right thing and show the age in terms of duration from the creationTimestamp to now?

File: .gitignore [hunk 2]
```diff
@@ -24,6 +24,7 @@ test/e2e/data/infrastructure-docker/v1alpha4/cluster-template*.yaml
 
 # VSCode
 .vscode/
+*.code-workspace
```
Comment (jackfrancis) [inline .gitignore:27]: is this change related to this particular PR?

File: api/v1alpha4/cluster_types.go (hunk 1 above)
Comment (jackfrancis) [inline api/v1alpha4/cluster_types.go:281]: following the example of other `additionalPrinterColumns` items, I think we want a `description="<insert description here"` for this new `Age` property

Comment (sbueringer) [reply api/v1alpha4/cluster_types.go:281]: I would also suspect that it prints the timestamp.

Interestingly there's an example in the official doc which is either fake or it works :)
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns

Comment (sbueringer) [reply api/v1alpha4/cluster_types.go:281]: fyi, the Age column of regular types has the following description:
```bash
CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
```
Might be a bit long to use verbatim in our case

**Comment by sbueringer** [comment]
Looks good.

Can you please also add the column to: (those are the remaining two CRDs which also already have `additionalPrinterColumns`)
* providers.clusterctl.cluster.x-k8s.io
* kubeadmcontrolplanes.controlplane.cluster.x-k8s.io

I wonder if it makes sense to add the column to all our CRDs, even when they currently don't have `additionalPrinterColumns`. Advantage would be we don't forget to add the age column when we add other columns to those CRDs. This would affect:
* clusterresourcesetbindings.addons.cluster.x-k8s.io
* clusterresourcesets.addons.cluster.x-k8s.io
* clusterclasses.cluster.x-k8s.io
* kubeadmcontrolplanetemplates.controlplane.cluster.x-k8s.io
* kubeadmconfigs.bootstrap.cluster.x-k8s.io
* kubeadmconfigtemplates.bootstrap.cluster.x-k8s.io
* CRDs in test/infrastructure/docker/config/crd/bases

**Review by fabriziopandini — COMMENTED** [review]
lgtm apart addressing comment about description (if there is agreement for it)
+1 to add AGE to all CRDs

Note: apart for ClusterClass that should be included in this PR, It will be ok to address other API types in follow up PRs given that we track the missing bits in a issue

File: api/v1alpha4/cluster_types.go (hunk 1 above)
Comment (CecileRobertMichon) [reply api/v1alpha4/cluster_types.go:281]: Thanks for the explanation here @sbueringer I was also wondering the same thing when I saw the kubebuilder example

File: .gitignore (hunk 2 above)
Comment (CecileRobertMichon) [reply .gitignore:27]: It's not but I'd say it's fine to leave it

**Comment by CecileRobertMichon** [comment]
> +1 to add AGE to all CRDs
+2 

Let's also add AGE to Docker provider CRDs (either in this PR or in a later one)

File: api/v1alpha4/cluster_types.go (hunk 1 above)
Comment (Jont828) [reply api/v1alpha4/cluster_types.go]: Gotcha, I wrote the description as 'Time duration since creation of <resource_name>". How does that sound?

Comment (sbueringer) [reply api/v1alpha4/cluster_types.go]: Sounds good to me

File: exp/addons/api/v1alpha4/clusterresourcesetbinding_types.go [hunk 3]
```diff
@@ -104,7 +104,7 @@ func (c *ClusterResourceSetBinding) DeleteBinding(clusterResourceSet *ClusterRes
 // +kubebuilder:resource:path=clusterresourcesetbindings,scope=Namespaced,categories=cluster-api
 // +kubebuilder:subresource:status
 // +kubebuilder:storageversion
-
+// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",description="Time duration since creation of ClusterResourceSetBinding"
```
Comment (sbueringer) [inline exp/addons/api/v1alpha4/clusterresourcesetbinding_types.go:107]:
```suggestion
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",description="Time duration since creation of ClusterResourceSetBinding"

```

**Comment by sbueringer** [comment]
@Jont828 Thx. There's one last additional one (`test/infrastructure/docker/exp/api/v1alpha4/dockermachinepool_types.go`)

@fabriziopandini We have two MachinePool YAMLs in `test/infrastructure/docker/config/crd/bases`. Imho we can/should delete `test/infrastructure/docker/config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinepools.yaml`.

**Comment by CecileRobertMichon** [comment]
@sbueringer Jonathan and I found the issue with the dockermachinepool kubebuilder generation when looking at this, I believe he's going to open a separate PR to fix it (the groupName kubebuilder comment is wong in groupversion_info.go). For now excluding dockermachinepools from this change because generation isn't working until we fix the above issue.

**Comment by Jont828** [comment]
Yep, as Cecile mentioned, I'm going to create a separate PR after this to fix the bug with dockermachinepools and add the age to it.

File: exp/addons/api/v1alpha4/clusterresourcesetbinding_types.go (hunk 3 above)
Comment (Jont828) [reply exp/addons/api/v1alpha4/clusterresourcesetbinding_types.go:107]: Btw is the suggested change just adding a newline? I spent like 5 min looking for a change in line 107 😅

Comment (sbueringer) [reply exp/addons/api/v1alpha4/clusterresourcesetbinding_types.go:107]: Yes it is :) The problem is that otherwise golangci-lint will complain

**Comment by Jont828** [comment]
Do all the changes look good? If so, I'll squash and get ready to merge.

**Comment by Jont828** [comment]
Np, happy to help! I just squashed everything into one commit. Hopefully everything passes and we're good to go.
