### PR TITLE
:bug: Allow using the --from flag to get a template from a github release

### LINKED ISSUE #7455: Can't use the `--from` flag to generate a cluster, from a github release asset
## What steps did you take and what happened
Trying to create a cluster manifest using the `--form` flag, with the value of a release asset URL; e.g.
```bash
clusterctl generate cluster capi-quickstart \
  --kubernetes-version ${CAPK_GUEST_K8S_VERSION} \
  --control-plane-machine-count=1 \
  --worker-machine-count=1 \
  --from "https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/releases/download/v0.1.3/cluster-template-lb.yaml" \
  > capi-quickstart.yaml
```

Getting error:
```text
Error: invalid GetFromURL operation: failed to get "/kubernetes-sigs/cluster-api-provider-kubevirt/releases/download/v0.1.3/cluster-template-lb.yaml": GET https://api.github.com/repos/kubernetes-sigs/cluster-api-provider-kubevirt/contents/v0.1.3/cluster-template-lb.yaml?ref=download: 404 No commit found for the ref download []
```

## What did you expect to happen
Should successfully generate the cluster manifest.

**Environment:**

- Cluster-api version: `v1.2.4`
- kind version: `kind v0.14.0 go1.18.4 linux/amd64`
- Kubernetes version: (use `kubectl version`): `v1.24.0`
- OS (e.g. from `/etc/os-release`): `Fedora 36`

/kind bug
 
/area clusterctl

### PR DESCRIPTION
**Pull request by nunnatsa**
Currently, `clusterctl generate cluster`'s `--from` flag only supports yaml files from github code (blob). Trying to get a template asset  from a release tag is failing.

This PR adds the option to use the `--form` also for release assets.

Fixes #7455

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

### CODE REVIEW

File: cmd/clusterctl/client/cluster/template.go [hunk 1]
```diff
@@ -181,35 +182,77 @@ func (t *templateClient) getGitHubFileContent(rURL *url.URL) ([]byte, error) {
...
-		return nil, errors.Wrapf(err, "failed to decode file %q", rURL.Path)
+		return nil, errors.Wrapf(err, "failed to decode file %q", fullPath)
 	}
 	return content, nil
 }
 
+func getGithubAssetFromRelease(ghClient *github.Client, path string, owner string, repo string, tag string, assetName string) ([]byte, error) {
+	release, _, err := ghClient.Repositories.GetReleaseByTag(ctx, owner, repo, tag)
+	if err != nil {
+		return nil, handleGithubErr(err, "failed to get release '%s' from %s%s repository", tag, owner, repo)
```
Comment (alexander-demicev) [inline cmd/clusterctl/client/cluster/template.go:233]:
```suggestion
		return nil, handleGithubErr(err, "failed to get release '%s' from %s/%s repository", tag, owner, repo)
```

File: cmd/clusterctl/client/cluster/template.go [hunk 2]
```diff
@@ -181,35 +182,77 @@ func (t *templateClient) getGitHubFileContent(rURL *url.URL) ([]byte, error) {
...
 	content, err := base64.StdEncoding.DecodeString(*fileContent.Content)
 	if err != nil {
-		return nil, errors.Wrapf(err, "failed to decode file %q", rURL.Path)
+		return nil, errors.Wrapf(err, "failed to decode file %q", fullPath)
 	}
 	return content, nil
 }
 
+func getGithubAssetFromRelease(ghClient *github.Client, path string, owner string, repo string, tag string, assetName string) ([]byte, error) {
+	release, _, err := ghClient.Repositories.GetReleaseByTag(ctx, owner, repo, tag)
```
Comment (alexander-demicev) [inline cmd/clusterctl/client/cluster/template.go:231]: should we check for a non-nil `release`?

File: cmd/clusterctl/client/cluster/template.go [hunk 3]
```diff
@@ -181,35 +182,77 @@ func (t *templateClient) getGitHubFileContent(rURL *url.URL) ([]byte, error) {
 
 	// Extract all the info from url split.
 	owner := urlSplit[0]
-	repository := urlSplit[1]
```
[the remark this answers is not in the document]
Comment (nunnatsa) [reply cmd/clusterctl/client/cluster/template.go:184]: The linter says: "Variable 'repository' collides with imported package name". Same for the `client` var below.

image

File: cmd/clusterctl/client/cluster/template.go [hunk 4]
```diff
@@ -181,35 +182,77 @@ func (t *templateClient) getGitHubFileContent(rURL *url.URL) ([]byte, error) {
...
 	}
 
 	// gets the file from GiHub
-	fileContent, _, _, err := client.Repositories.GetContents(context.TODO(), owner, repository, path, &github.RepositoryContentGetOptions{Ref: branch})
+	switch linkType {
+	case "blob": // get file from a code in a github repo
+		return getGithubFileContentFromCode(ghClient, rURL.Path, owner, repo, path, branch)
+
+	case "releases": // get a github release asset
+		tag := urlSplit[4]
```
[the remark this answers is not in the document]
Comment (nunnatsa) [reply cmd/clusterctl/client/cluster/template.go:202]: Not sure. I tend not to do that, because the meaning of the 4th and 5th path component is different in these two cases.

File: cmd/clusterctl/client/cluster/template.go (hunk 2 above)
Comment (nunnatsa) [reply cmd/clusterctl/client/cluster/template.go:231]: done

File: cmd/clusterctl/client/cluster/template.go (hunk 1 above)
Comment (nunnatsa) [reply cmd/clusterctl/client/cluster/template.go]: done

**Comment by nunnatsa** [comment]
@alexander-demicev - could you please review again, after the fixes?

File: cmd/clusterctl/client/cluster/template.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/template.go:202]: Agree with not extracting them early. Those values hold different meaning under `blob` and `releases` cases.

File: cmd/clusterctl/client/cluster/template.go [hunk 5]
```diff
@@ -181,35 +182,81 @@ func (t *templateClient) getGitHubFileContent(rURL *url.URL) ([]byte, error) {
...
+	}
+
+	if release == nil {
+		return nil, fmt.Errorf("can't find release '%s' in %s/%s repository", tag, owner, repo)
+	}
+
+	var rc io.ReadCloser
+	for _, asset := range release.Assets {
+		if asset.GetName() == assetName {
+			rc, _, err = ghClient.Repositories.DownloadReleaseAsset(ctx, owner, repo, asset.GetID(), ghClient.Client())
```
Comment (ykakarap) [inline cmd/clusterctl/client/cluster/template.go:243]: I believe you will also have to handle the redirects when working with release assets. Similar to how we handle the redirects here: 
https://github.com/nunnatsa/cluster-api/blob/fd24c247c3ae9b32fed236f544088486ec6331cf/cmd/clusterctl/client/repository/repository_github.go#L331-L344

**Review by ykakarap — CHANGES_REQUESTED** [review]

**Comment by sbueringer** [comment]
@ykakarap Can you please double check if this PR is in conflict with https://github.com/kubernetes-sigs/cluster-api/pull/7371  or if they are othogonal? (feature-wise)

File: cmd/clusterctl/client/cluster/template.go (hunk 5 above)
Comment (nunnatsa) [reply cmd/clusterctl/client/cluster/template.go:243]: > I believe you will also have to handle the redirects when working with release assets. Similar to how we handle the redirects here: https://github.com/nunnatsa/cluster-api/blob/fd24c247c3ae9b32fed236f544088486ec6331cf/cmd/clusterctl/client/repository/repository_github.go#L331-L344

Thanks @ykakarap. I'm not sure it's needed. According to the  `DownloadReleaseAsset` documentation:
> followRedirectsClient can be passed to download the asset from a redirected location. Passing http.DefaultClient is recommended unless special circumstances exist, but it's possible to pass any http.Client. **If nil is passed the redirectURL will be returned instead**.

I added unit test to check the redirect scenario. Also, This code is working with the real github, that actually responses with redirect. If you think it's a must, I'll add it, but it's not needed, I think.

**Comment by nunnatsa** [comment]
> ... if this PR is in conflict with #7371 or if they are othogonal? (feature-wise)

Thanks @sbueringer - I didn't know #7371, but I just read it. As far I can see, not only this PR is not conflicts with 7371, but it is even more important with it, because with 7371, blob github link will work, non-github link will work, but github release asset links will fail - and so #7455 is even more meaningful bug.

**Comment by ykakarap** [comment]
> @ykakarap Can you please double check if this PR is in conflict with #7371 or if they are othogonal? (feature-wise)

They are not in conflict with each other. They are complimentary. I agree with @nunnatsa that having both 7371 and this PR would be beneficial as they would cover a broader set of cases.

**Comment by sbueringer** [comment]
Sounds good! Thx for checking

File: cmd/clusterctl/client/cluster/template.go (hunk 5 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/template.go:243]: Seem to work for redirected assets as well. @fabriziopandini Do you know why we are redirecting here: https://github.com/nunnatsa/cluster-api/blob/fd24c247c3ae9b32fed236f544088486ec6331cf/cmd/clusterctl/client/repository/repository_github.go#L331-L344?

Do you know of a case that is not covered by the standard `DownloadReleaseAsset` function?

**Review by ykakarap — COMMENTED** [review]
Overall LGTM. 

This will be a nice addition :)

File: cmd/clusterctl/client/cluster/template.go [hunk 6]
```diff
@@ -181,35 +182,81 @@ func (t *templateClient) getGitHubFileContent(rURL *url.URL) ([]byte, error) {
```
[the remark this answers is not in the document]
Comment (nunnatsa) [reply cmd/clusterctl/client/cluster/template.go:184]: Thanks @ykakarap - fixed.

**Comment by nunnatsa** [comment]
Hi @fabriziopandini. What do you think about the redirect question from @ykakarap, here? https://github.com/kubernetes-sigs/cluster-api/pull/7453#discussion_r1022312482

**Comment by fabriziopandini** [comment]
> Hi @fabriziopandini. What do you think about the redirect question from @ykakarap, here? https://github.com/kubernetes-sigs/cluster-api/pull/7453#discussion_r1022312482

Sorry for the delay, answered in the thread above

**Comment by nunnatsa** [comment]
rebased (fix conflicts)

File: cmd/clusterctl/client/cluster/template.go (hunk 5 above)
Comment (nunnatsa) [reply cmd/clusterctl/client/cluster/template.go:277]: Thanks @fabriziopandini. According to the `DownloadReleaseAsset` documentation I copied above, the redirect is only returned if the followRedirectsClient parameter is empty. This is, I guess, if you want to implement the redirect logic. But if you pass the client, the function will do it for you. This is how I understand it.

Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/template.go:277]: kk, I double checked the DownloadReleaseAsset implementation and it seems that this is not necessary if we are passing a followRedirectsClient.
In a separated PR we can also eventually clean up also the bit of code @ykakarap was referencing to

**Review by Jont828 — COMMENTED** [review]
Thanks for your contribution, overall this make sense to me. I'll try to test this out locally when I get the chance, were you able to get this working by running a copy of clusterctl built off of this code?

**Comment by nunnatsa** [comment]
> were you able to get this working by running a copy of clusterctl built off of this code?

yes

**Comment by fabriziopandini** [comment]
/lgtm
ready to approve as soon as we get a final feedback from @Jont828 and @ykakarap

**Comment by ykakarap** [comment]
Did a final pass and this is good to go.

/lgtm

Great work! Thank you for adding the release asset support. 🚀

File: cmd/clusterctl/client/cluster/template.go (hunk 5 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/template.go:277]: Created a follow-up issue to track the clean up work. https://github.com/kubernetes-sigs/cluster-api/issues/7942

**Comment by sbueringer** [comment]
/approve
Given lgtms above
