### PR TITLE
🐛 clusterctl: update move to support new cluster validations

### LINKED ISSUE #5620: `clusterctl move` should move ClusterClass before Clusters
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

The current move operation treats both ClusterClass and Clusters as roots of the move graph.

With https://github.com/kubernetes-sigs/cluster-api/pull/5596 merged there is now a requirement that we have to make sure that a ClusterClass exists in the Cluster before a cluster can use it.

Ref https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main to see that the move e2e tests (self-hosted e2e tests using ClusterClass) are failing because of this.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
/area clusterctl
/area topology

/assign @ykakarap

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

This PR fixes the clusterctl move order so that any ClusterClass that are in use are moved to the target cluster before the Clusters that used them are moved.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5620

### CODE REVIEW

File: cmd/clusterctl/client/cluster/objectgraph.go [hunk 1]
```diff
@@ -118,6 +125,25 @@ func (n *node) getFilename() string {
 	return n.identity.Kind + "_" + n.identity.Namespace + "_" + n.identity.Name + ".yaml"
 }
 
+func (n *node) caputeAdditionalInformation(obj *unstructured.Unstructured) error {
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/objectgraph.go:128]:
```suggestion
func (n *node) captureAdditionalInformation(obj *unstructured.Unstructured) error {
```
nit

File: cmd/clusterctl/client/cluster/objectgraph.go [hunk 2]
```diff
@@ -136,20 +162,26 @@ func newObjectGraph(proxy Proxy, providerInventory InventoryClient) *objectGraph
 
 // addObj adds a Kubernetes object to the object graph that is generated during the move discovery phase.
 // During add, OwnerReferences are processed in order to create the dependency graph.
-func (o *objectGraph) addObj(obj *unstructured.Unstructured) {
+func (o *objectGraph) addObj(obj *unstructured.Unstructured) error {
 	// Adds the node to the Graph.
-	newNode := o.objToNode(obj)
+	newNode, err := o.objToNode(obj)
+	if err != nil {
+		return errors.Wrap(err, "failed to convert objec to node")
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/objectgraph.go:169]:
```suggestion
		return errors.Wrap(err, "failed to convert object to node")
```
nit

File: cmd/clusterctl/client/cluster/objectgraph.go [hunk 3]
```diff
@@ -205,17 +237,16 @@ func (o *objectGraph) ownerToVirtualNode(owner metav1.OwnerReference) *node {
...
 	existingNode, found := o.uidToNode[obj.GetUID()]
 	if found {
 		existingNode.markObserved()
 
-		// In order to compensate the lack of labels when adding a virtual node,
-		// it is required to re-compute the forceMove and forceMoveHierarchy field when the real node is processed.
-		// Without this, there is the risk that those fields could report false negatives depending on the discovery order.
-		o.objMetaToNode(obj, existingNode)
+		if err := o.objInfoToNode(obj, existingNode); err != nil {
+			return nil, errors.Wrap(err, "failed to add object into to node")
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/objectgraph.go:246]:
```suggestion
			return nil, errors.Wrap(err, "failed to add object info to node")
```
nit

**Review by sbueringer — COMMENTED** [review]
Only did a high-level review for now.

Q: Did I understood the move correctly:
* target cluster: create one group after another
* source cluster: deletes one group after another in reverse order

That would mean:
* target cluster: ClusterClasses are created before Cluster
* source cluster: Clusters are deleted before ClusterClasses

If I got it right, the move will still work when we introduce a webhook on the ClusterClass, which makes sure that a ClusterClass is only deleted after it's not used anymore in any Clusters.

File: cmd/clusterctl/client/cluster/objectgraph.go [hunk 4]
```diff
@@ -226,15 +257,26 @@ func (o *objectGraph) objToNode(obj *unstructured.Unstructured) *node {
...
-		tenant:     make(map[*node]empty),
-		virtual:    false,
+		owners:         make(map[*node]ownerReferenceAttributes),
+		softOwners:     make(map[*node]empty),
+		tenant:         make(map[*node]empty),
+		virtual:        false,
+		additionalInfo: make(map[string]interface{}),
+	}
+	if err := o.objInfoToNode(obj, newNode); err != nil {
+		return nil, errors.Wrap(err, "failed to add object into to node")
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/objectgraph.go:267]: what about adding kind/name of the obj in errors
(same for other errors added in this PR)

File: cmd/clusterctl/client/cluster/objectgraph.go [hunk 5]
```diff
@@ -523,6 +578,20 @@ func (o *objectGraph) setSoftOwnership() {
 			}
 		}
 	}
+
+	clusterClasses := o.getClusterClasses()
+	// ClusterClass that are used by atleast one cluster are soft owned by that cluster.
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/objectgraph.go:583]:
```suggestion
	// Cluster that uses a ClusterClass are soft owned by that ClusterClass.
```

File: cmd/clusterctl/client/cluster/objectgraph.go [hunk 6]
```diff
@@ -523,6 +578,20 @@ func (o *objectGraph) setSoftOwnership() {
...
+	for _, clusterClass := range clusterClasses {
+		for _, cluster := range clusters {
+			// if the cluster uses a managed topoloy and uses the clusterclass
+			// set the cluster as a soft owner of the clusterclass.
+			if className, ok := cluster.additionalInfo[clusterTopologyNameKey]; ok {
+				if className == clusterClass.identity.Name && clusterClass.identity.Namespace == cluster.identity.Namespace {
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/objectgraph.go:589]: Let's check also group

File: cmd/clusterctl/client/cluster/objectgraph.go (hunk 1 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/objectgraph.go:128]: type 😅

File: cmd/clusterctl/client/cluster/objectgraph.go (hunk 6 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/objectgraph.go:589]: Just for my understanding: why would we want to check the group?

Here we are making sure that the clusterclass used in the cluster spec (`cluster.spec.topology.class`) matches the clusterclass we are checking against and we are making sure that the cluster and the clusterclass belong to the same namespace because we know that this is a requirement. 
By checking groups we are saying that clusters and clusterclasses should belong to the same k8s group `cluster.x-k8s.io`. I dont see how this is a requirement to establish a soft ownership.

Am I missing something?

**Comment by ykakarap** [comment]
@sbueringer you are correct. Because of the new soft ownership between the clusters and the cluster classes that are in use we can guarantee that any ClusterClass that is in use will be moved to the target cluster before the cluster object is moved.

File: cmd/clusterctl/client/cluster/objectgraph.go (hunk 6 above)
Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/objectgraph.go:593]: No you are right.
I did not look at the code above and I did assume we were looping through all the objects, not only clusters

**Review by vincepri — APPROVED** [review]
/approve
