### PR TITLE
🐛 Fix ClusterCacheTracker memory leak

### LINKED ISSUE #9542: ClusterCacheTracker: Memory leak when kubeconfig is rotated too often, and CAPI is running on the workload cluster
### What steps did you take and what happened?

Steps to reproduce the error:
* Deploy cluster-api with AWS provider.
* Create an EKS cluster (more info [here](https://cluster-api-aws.sigs.k8s.io/topics/eks)).
* Move cluster-api components to the new workload cluster via [clusterctl move](https://cluster-api.sigs.k8s.io/clusterctl/commands/move.html#clusterctl-move) command.
* Add some `MachinePool` and `AWSManagedMachinePool` resources.
* After some running time, observe `capi-controller-manager` logs being spammed, and pod memory increasing. 

We have a `v1.27.4` EKS cluster deployed via cluster-api, and we recently upgraded from `v1.3.7` to `v1.5.2`.

Everything went fine with the upgrade. However, after a week of running, I noticed the `capi-controller-manager` pod being spammed (about 300 logs per minute) with:
```
W1010 12:56:12.276785       1 reflector.go:533] k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Node: Unauthorized
E1010 12:56:12.276815       1 reflector.go:148] k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized
W1010 12:56:12.713455       1 reflector.go:533] k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Node: Unauthorized
E1010 12:56:12.713488       1 reflector.go:148] k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized
```

and pod memory usage being high.

Restarted the pod, everything is fine again. But slowly with time, the same issue reproduces again.

### What did you expect to happen?

Pod logs that are not being spammed, and pod memory not increasing over time.  

### Cluster API version

v1.5.2

### Kubernetes version

v1.27.4-eks-2d98532

### Anything else you would like to add?

I already investigated and solved this issue, but I want to bring more context on the issue first.

When deploying EKS Kubernetes clusters via cluster-api AWS provider (CAPA), there are two `kubeconfig` secrets being set:
* `<CLUSTER_NAME>-kubeconfig`
* `<CLUSTER_NAME>-user-kubeconfig`

The `<CLUSTER_NAME>-user-kubeconfig` is meant to be used by users, while `<CLUSTER_NAME>-kubeconfig` is being used internally by CAPI, and it's rotated every `sync-period`, since it contains an expiring token to access the EKS API. More details [here](https://cluster-api-aws.sigs.k8s.io/topics/eks/creating-a-cluster#kubeconfig).

When running cluster-api in the workload cluster, this code path causes a memory leak when `<CLUSTER_NAME>-kubeconfig` is rotated frequently:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L298-L330

Notice that in this part of the code, when CAPI is running in the workload cluster, the `t.createClient` is called twice:
1. https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L298-L299
2. https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L324-L325

However, the function `t.createClient` also starts a goroutine with the `clusterAccessor` cache:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L449-L450 

Using more verbose logging, I noticed that immediately after the goroutine cache starts, there's a cluster nodes watcher registered:
```
I1010 22:05:29.890187       1 reflector.go:287] Starting reflector *v1.Node (10h52m8.919938079s) from k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231
I1010 22:05:29.902920       1 reflector.go:323] Listing and watching *v1.Node from k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231
```

I believe this is happening, because we have the following watcher already registered on the `ClusterCacheTracker`:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/exp/internal/controllers/machinepool_controller.go#L325-L331

However, looking in the `ClusterCacheTracker` code, this watcher is supposed to be started just once:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L541-L545

But, when I restart the `capi-controller-manager`, I see that the watcher registers twice for the same cluster. This is confirmed by seing this twice:
```
I1010 22:05:29.890187       1 reflector.go:287] Starting reflector *v1.Node (10h52m8.919938079s) from k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231
I1010 22:05:29.902920       1 reflector.go:323] Listing and watching *v1.Node from k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231
```

So, one of the goroutine is leaked.

This is happening because, in the initially mentioned code path, we start the cache twice. Before overwriting the cached client with the in-cluster configuration, we never stop the initial cache, and that runs continuously in the background.

I noticed that stopping the cache would also stop the goroutine that watches the nodes continuously.

This wouldn't be a memory leak problem if `kubeconfig` is not rotated frequently, since the `clusterAccessor` is never re-created. However, when the loaded `kubeconfig` expires, the `healthCheckCluster` fails, and the `clusterAccessor` is deleted:
https://github.com/kubernetes-sigs/cluster-api/blob/a82c340118994d52f009065665a5bd4c4e0d3528/controllers/remote/cluster_cache_tracker.go#L656-L668

This causes the `clusterAccessor` to be recreated on the next `Reconcile` loop, and the troublesome code path leaks another goroutine with the cluster node watcher. And this happens every time the loaded EKS cluster `kubeconfig` expires, and the `clusterAccessor` is recreated.

The log spam comes the fact that, after a long running time, we have a lot of leaked goroutines trying to list cluster nodes, with an expired `kubeconfig`.

### Label(s) to be applied

/kind bug
/area clustercachetracker

### PR DESCRIPTION
**Pull request by ionutbalutoiu**
Decouple the code that creates uncached client from the code that creates the cached client. This way, we don't start the cache until the cached client is created.

This avoids scenarios where the `ClusterCacheTracker` cache is started when only an uncached client is needed.

There is an existing code path, described in the original issue, where the `ClusterCacheTracker` cache is started when only an uncached client is needed. The cache is re-created later, and the initial cache is still running continuously in the background.

**What this PR does / why we need it**:

Fix the memory leak described in the issue https://github.com/kubernetes-sigs/cluster-api/issues/9542, when cluster `kubeconfig` is rotated frequently,

**Which issue(s) this PR fixes**:
Fixes #9542

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/area clustercachetracker

/ok-to-test

**Comment by ionutbalutoiu** [comment]
Fixed the unused context `golangci-lint` errors via the following changes:
https://github.com/kubernetes-sigs/cluster-api/compare/36c0b2c6d800d04cfc1e299fa24da540756d05a8..88e53de8cabeac51697ee29c297a427bfdd361ad

**Comment by vincepri** [comment]
/assign

Would like some time to review this PR in a bit more details

File: controllers/remote/cluster_cache_tracker.go [hunk 1]
```diff
@@ -374,26 +384,58 @@ func (t *ClusterCacheTracker) runningOnWorkloadCluster(ctx context.Context, c cl
 	return t.controllerPodMetadata.UID == pod.UID, nil
 }
 
-// createClient creates a cached client, and uncached client and a mapper based on a rest.Config.
-func (t *ClusterCacheTracker) createClient(ctx context.Context, config *rest.Config, cluster client.ObjectKey, indexes []Index) (client.Client, client.Client, *stoppableCache, error) {
+// createHTTPClientAndMapper creates a http client and a dynamic rest mapper for the given cluster, based on the rest.Config.
+func (t *ClusterCacheTracker) createHTTPClientAndMapper(config *rest.Config, cluster client.ObjectKey) (*http.Client, meta.RESTMapper, error) {
```
Comment (vincepri) [inline controllers/remote/cluster_cache_tracker.go:388]: Given that now we have this function, could we create an http client and rest mapper for each config only one and eventually use it also for the cache? Basically, `createUncachedClient` and `createCachedClient` should get those two fields as input, instead of the *rest.Config

File: controllers/remote/cluster_cache_tracker.go [hunk 2]
```diff
@@ -321,13 +325,19 @@ func (t *ClusterCacheTracker) newClusterAccessor(ctx context.Context, cluster cl
 		config.CAFile = inClusterConfig.CAFile
 		config.Host = inClusterConfig.Host
 
-		// Create a new client and overwrite the previously created client.
-		c, _, cache, err = t.createClient(ctx, config, cluster, indexes)
+		// Create a client and a cache for the cluster, using the in-cluster config.
+		c, cache, err = t.createCachedClient(ctx, config, cluster, indexes)
 		if err != nil {
 			return nil, errors.Wrap(err, "error creating client for self-hosted cluster")
 		}
```
[the remark this answers is not in the document]
Comment (ionutbalutoiu) [reply controllers/remote/cluster_cache_tracker.go:332]: I agree. I will move these outside to remove the duplicated code.

File: controllers/remote/cluster_cache_tracker.go (hunk 1 above)
Comment (ionutbalutoiu) [reply controllers/remote/cluster_cache_tracker.go:388]: Well, I believe we still need the `*rest.Config` parameter.

For the `createUncachedClient` function, we need it for `client.New` call.

And, for the `createCachedClient` function, we need it for:
* `cache.New` call.
* `client.New` call.
* `newClientWithTimeout` (since it uses uses `config.Timeout` when wrapping the client before returning it).
* `go t.healthCheckCluster` goroutine.

However, it makes sense moving the `createHTTPClientAndMapper` call outside `createUncachedClient` / `createCachedClient` and adding the `httpClient` and `mapper` as parameters to the get client functions.

Comment (ionutbalutoiu) [reply controllers/remote/cluster_cache_tracker.go:388]: Actually, I don't think that it solves anything moving the `createHTTPClientAndMapper` outside the get client functions.

We would still have to call this twice anyway:
* Before the `createUncachedClient`.
* Before `createCachedClient`. This second call is needed since the config is changed when `in-cluster` config is used, and re-using the `httpClient` and `mapper` from the `createUncachedClient` call is not what we want. 

I would let it as it is, since we cannot remove the `*rest.Config` parameter (as pointed above).

What do you think?

File: controllers/remote/cluster_cache_tracker.go [hunk 3]
```diff
@@ -321,16 +325,17 @@ func (t *ClusterCacheTracker) newClusterAccessor(ctx context.Context, cluster cl
...
-		if err != nil {
-			return nil, errors.Wrap(err, "error creating client for self-hosted cluster")
-		}
 		log.Info(fmt.Sprintf("Creating cluster accessor for cluster %q with in-cluster service %q", cluster.String(), config.Host))
 	} else {
 		log.Info(fmt.Sprintf("Creating cluster accessor for cluster %q with the regular apiserver endpoint %q", cluster.String(), config.Host))
 	}
 
+	// Create a client and a cache for the cluster.
+	c, cache, err = t.createCachedClient(ctx, config, cluster, indexes)
```
Comment (vincepri) [inline controllers/remote/cluster_cache_tracker.go:334]:
```suggestion
	c, cache, err := t.createCachedClient(ctx, config, cluster, indexes)
```

And remove the variable declaration above?

File: controllers/remote/cluster_cache_tracker.go (hunk 1 above)
Comment (vincepri) [reply controllers/remote/cluster_cache_tracker.go:383]: I'm confused. Why can't we share the `mapper` and `httpClient` across both calls? If anything, we shouldn't duplicate these inputs for the two clients for the same cluster

File: controllers/remote/cluster_cache_tracker.go [hunk 4]
```diff
@@ -374,26 +379,58 @@ func (t *ClusterCacheTracker) runningOnWorkloadCluster(ctx context.Context, c cl
...
+	})
+	if err != nil {
+		return nil, errors.Wrapf(err, "error creating uncached client for remote cluster %q", cluster.String())
+	}
+
+	return uncachedClient, nil
+}
+
+// createCachedClient creates a cached client for the given cluster, based on a rest.Config.
+func (t *ClusterCacheTracker) createCachedClient(ctx context.Context, config *rest.Config, cluster client.ObjectKey, indexes []Index) (client.Client, *stoppableCache, error) {
```
Comment (vincepri) [inline controllers/remote/cluster_cache_tracker.go:429]: Avoid returning two parameters + errors, wrap them in an output struct

Comment (vincepri) [reply controllers/remote/cluster_cache_tracker.go:429]: Example:

```golang
type cachedClientOutput struct {
  Client client.Client
  Cache *stoppableCache
}
```

File: controllers/remote/cluster_cache_tracker.go (hunk 1 above)
Comment (ionutbalutoiu) [reply controllers/remote/cluster_cache_tracker.go:383]: > I'm confused. Why can't we share the `mapper` and `httpClient` across both calls? If anything, we shouldn't duplicate these inputs for the two clients for the same cluster

We can share them, but it will only work only when `runningOnCluster` is `false`. The `uncachedClient` decides if the cached client with in-cluster config is needed.

If `runningOnCluster` is `true`, we need to create a different `mapper` and `httpClient` using the in-cluster config, and the previous `mapper` and `httpClient` cannot be re-used. I can update the code as suggested, but in the if branch with `runningOnCluster == true` I need override the `mapper` and `httpClient` using the in-cluster config.

Besides this, as mentioned above, we cannot remove `*rest.Config` parameter from `createCachedClient` function as suggested initially (it's used elsewhere besides calling `createHTTPClientAndMapper`). So, what I would do is adding two more extra parameters to the `createCachedClient` fuction, without removing any existing ones.

If you still believe it's better to re-use the `mapper` and `httpClient` from uncached client (but override them in the `runningOnCluster == true` if branch, I will make the change.

Comment (ionutbalutoiu) [reply controllers/remote/cluster_cache_tracker.go:383]: See this piece of code for reference:
https://github.com/ionutbalutoiu/cluster-api/blob/8cf7a6632195f42d43da6eebb693286444e28f70/controllers/remote/cluster_cache_tracker.go#L294-L337

File: controllers/remote/cluster_cache_tracker.go (hunk 3 above)
Comment (ionutbalutoiu) [reply controllers/remote/cluster_cache_tracker.go:334]: Agree!

File: controllers/remote/cluster_cache_tracker.go (hunk 4 above)
Comment (ionutbalutoiu) [reply controllers/remote/cluster_cache_tracker.go:429]: To stay consistent to the current codebase, I just re-used the same function signature that we have currently in `main` branch:
https://github.com/kubernetes-sigs/cluster-api/blob/83d79695ed028bd6ae6f1aaa1b5cd19eaa2ac267/controllers/remote/cluster_cache_tracker.go#L377-L378

but removing the uncached client from return values, and renaming it accordingly.

I will make this change as well.

**Comment by ionutbalutoiu** [comment]
@vincepri Implemented the following changes for your most recent code review:
https://github.com/kubernetes-sigs/cluster-api/compare/8cf7a6632195f42d43da6eebb693286444e28f70..500968845d650521109759790ce79785879b70eb

Thank-you!

File: controllers/remote/cluster_cache_tracker.go [hunk 5]
```diff
@@ -374,26 +376,63 @@ func (t *ClusterCacheTracker) runningOnWorkloadCluster(ctx context.Context, c cl
...
+	Client client.Client
+	Cache  *stoppableCache
+}
+
+// createCachedClient creates a cached client for the given cluster, based on a rest.Config.
+func (t *ClusterCacheTracker) createCachedClient(ctx context.Context, config *rest.Config, cluster client.ObjectKey, indexes []Index) (*cachedClientOutput, error) {
+	// Create a http client and a mapper for the cluster.
+	httpClient, mapper, err := t.createHTTPClientAndMapper(config, cluster)
+	if err != nil {
+		return nil, errors.Wrapf(err, "error creating client for remote cluster %q", cluster.String())
```
Comment (sbueringer) [inline controllers/remote/cluster_cache_tracker.go:435]:
```suggestion
		return nil, errors.Wrapf(err, "error creating cached client for remote cluster %q", cluster.String())
```

File: controllers/remote/cluster_cache_tracker.go [hunk 6]
```diff
@@ -417,7 +456,7 @@ func (t *ClusterCacheTracker) createClient(ctx context.Context, config *rest.Con
 
 	for _, index := range indexes {
 		if err := cache.IndexField(ctx, index.Object, index.Field, index.ExtractValue); err != nil {
-			return nil, nil, nil, errors.Wrapf(err, "error adding index for field %q to cache for remote cluster %q", index.Field, cluster.String())
+			return nil, errors.Wrapf(err, "error adding index for field %q to cache for remote cluster %q", index.Field, cluster.String())
```
Comment (sbueringer) [inline controllers/remote/cluster_cache_tracker.go:459]:
```suggestion
			return nil, errors.Wrapf(err, "error creating cached client for remote cluster %q: error adding index for field %q to cache", cluster.String(), index.Field)
```

**Review by sbueringer — COMMENTED** [review]
Some smaller findings and answered on the discussion with some more context

**Comment by sbueringer** [comment]
@ionutbalutoiu Sorry for the long delay. I sort of lost track of this PR a bit. Happy to quickly review again and merge once the open points are addressed

File: controllers/remote/cluster_cache_tracker.go [hunk 7]
```diff
@@ -374,26 +376,63 @@ func (t *ClusterCacheTracker) runningOnWorkloadCluster(ctx context.Context, c cl
...
+		HTTPClient: httpClient,
+	})
+	if err != nil {
+		return nil, errors.Wrapf(err, "error creating uncached client for remote cluster %q", cluster.String())
+	}
+
+	return uncachedClient, nil
+}
+
+type cachedClientOutput struct {
```
[the remark this answers is not in the document]
Comment (ionutbalutoiu) [reply controllers/remote/cluster_cache_tracker.go:425]: The output struct change was suggested by @vincepri in [this previous PR comment](https://github.com/kubernetes-sigs/cluster-api/pull/9543#discussion_r1395979323).

I'm fine with anything as long as it ready to be merged.

**Comment by ionutbalutoiu** [comment]
> @ionutbalutoiu Sorry for the long delay. I sort of lost track of this PR a bit. Happy to quickly review again and merge once the open points are addressed

Thank-you for taking the time to review this! I've addressed all the remaining review open items. I also did a rebase against latest `main` branch.

Please take a look at the latest PR changes and let me know if there's anything else.

File: controllers/remote/cluster_cache_tracker.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (sbueringer) [reply controllers/remote/cluster_cache_tracker.go:434]: All good :)

**Comment by sbueringer** [comment]
Thank you very much!

Let's see if we have some luck with cherry-picking

/lgtm
/approve
