### PR TITLE
:bug: fix: considers objects in kube-system for cert-manager to avoid upgrading twice

### LINKED ISSUE #11348: cert-manager is always updated
### What steps did you take and what happened?

As cert-manager was updated to version to 1.16.1 in https://github.com/kubernetes-sigs/cluster-api/pull/11322 

A few key changes in the chart make the current code make it so that cert-manager is always upgraded even if it is not necessary.

How to recreate:

1. Create a cluster with kind, or use any kubernetes cluster 
2. Run clusterctl init. This is an example command - 

```shell
clusterctl init --kubeconfig=/path-to-my-kubeconfig --core cluster-api:v1.8.4 --bootstrap kubeadm:v1.8.4 --control-plane kubeadm:v1.8.4 --infrastructure docker:v1.8.4,aws:v2.6.1,nutanix:v1.5.3 --addon helm:v0.2.5 --wait-providers
```

I got logs like this 

```
Fetching providers
Installing cert-manager version="v1.16.0"
Waiting for cert-manager to be available...
Installing provider="cluster-api" version="v1.8.4" targetNamespace="capi-system"
Installing provider="bootstrap-kubeadm" version="v1.8.4" targetNamespace="capi-kubeadm-bootstrap-system"
Installing provider="control-plane-kubeadm" version="v1.8.4" targetNamespace="capi-kubeadm-control-plane-system"
```

3. Run upgrade apply 

```
clusterctl upgrade apply --core cluster-api:v1.8.4 --bootstrap kubeadm:v1.8.4 --control-plane kubeadm:v1.8.4 --infrastructure docker:v1.8.4,aws:v2.6.1,nutanix:v1.5.3 --addon helm:v0.2.5 -v=5 --wait-providers
``` 

I observe that cert-manager is scaled down and recreated even though the same version is to be installed 

Logs from upgrade:

```
No default config file available
Potential override file searchFile="/home/fraza/.config/cluster-api/overrides/cert-manager/v1.16.0/cert-manager.yaml" provider="cert-manager" version="v1.16.0"
Fetching file="cert-manager.yaml" provider="cert-manager" type="" version="v1.16.0"
Checking if cert-manager needs upgrade...
CRD migration check passed CustomResourceDefinition={"name":"certificaterequests.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"certificates.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"challenges.acme.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"clusterissuers.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"issuers.cert-manager.io"}
CRD migration check passed CustomResourceDefinition={"name":"orders.acme.cert-manager.io"}
Deleting cert-manager version="v1.16.0"
``` 

I believe that this is happening because the leader election namespace is hard coded to `kube-system` in the upstream chart see https://github.com/cert-manager/cert-manager/issues/6716 

When we list objects that belong to the cert-manager deployment we miss these objects  (EDIT because `kube-system` isn't passed in)

https://github.com/kubernetes-sigs/cluster-api/blob/0202f9c6ec3726e775056f6290aff302b6708d4d/cmd/clusterctl/client/cluster/cert_manager.go#L244

and then when we get to this check, we determine an upgrade is needed 

https://github.com/kubernetes-sigs/cluster-api/blob/0202f9c6ec3726e775056f6290aff302b6708d4d/cmd/clusterctl/client/cluster/cert_manager.go#L377

### What did you expect to happen?

I expect cert-manager to not get recreated when the expected version is correct

### Cluster API version

$ clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"", GitTreeState:"", BuildDate:"", GoVersion:"go1.23.2", Compiler:"gc", Platform:"linux/amd64"}

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by faiq**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #11348

### CODE REVIEW

**Comment by faiq** [comment]
area/clusterctl

File: cmd/clusterctl/client/cluster/cert_manager.go [hunk 1]
```diff
@@ -236,12 +237,28 @@ func (cm *certManagerClient) PlanUpgrade(ctx context.Context) (CertManagerUpgrad
 	}, nil
 }
 
+// getFilteredCertManagerResources gets all relevant objects for a cert-manager deployment
+// it also includes objects in the kube-system namespace because leader election namespace
+// is hard coded to kube-system https://github.com/cert-manager/cert-manager/issues/6716
+// it also deletes components that are created by Kubernetes and won't be used to see if
+// new objects need to be created for a cert-manager upgrade.
```
Comment (dlipovetsky) [inline cmd/clusterctl/client/cluster/cert_manager.go:244]: nit: some wordsmithing:

```suggestion
// getFilteredCertManagerResources gets all relevant objects for a cert-manager installation.
// It also includes relevant resources in the kube-system namespace, which is used by cert-manager
// for leader election (https://github.com/cert-manager/cert-manager/issues/6716).
// It excludes resources that are related to the cert-manager installation, but not relevant
// to the cert-manager upgrade.
```

File: cmd/clusterctl/client/cluster/cert_manager.go [hunk 2]
```diff
@@ -236,12 +236,28 @@ func (cm *certManagerClient) PlanUpgrade(ctx context.Context) (CertManagerUpgrad
...
+func (cm *certManagerClient) getFilteredCertManagerResources(ctx context.Context) ([]unstructured.Unstructured, error) {
+	objs, err := cm.proxy.ListResources(ctx, map[string]string{clusterctlv1.ClusterctlCoreLabel: clusterctlv1.ClusterctlCoreLabelCertManagerValue}, certManagerNamespace, metav1.NamespaceSystem)
+	if err != nil {
+		return nil, errors.Wrap(err, "failed get cert manager components")
+	}
+	objs = slices.DeleteFunc(objs, func(obj unstructured.Unstructured) bool {
```
Comment (faiq) [inline cmd/clusterctl/client/cluster/cert_manager.go:249]: the reason we are deleting this is because when we include these created objects by the API this condition below always be true because they are created by kubernetes API.

https://github.com/kubernetes-sigs/cluster-api/blob/f8a2970e9c8516f2c3d5cad4985543314a215a6b/cmd/clusterctl/client/cluster/cert_manager.go#L377

File: cmd/clusterctl/client/cluster/cert_manager.go [hunk 3]
```diff
@@ -236,12 +236,28 @@ func (cm *certManagerClient) PlanUpgrade(ctx context.Context) (CertManagerUpgrad
...
 
+// getFilteredCertManagerResources gets all relevant objects for a cert-manager deployment
+// it also includes objects in the kube-system namespace because leader election namespace
+// is hard coded to kube-system https://github.com/cert-manager/cert-manager/issues/6716
+// it also deletes components that are created by Kubernetes and won't be used to see if
+// new objects need to be created for a cert-manager upgrade.
+func (cm *certManagerClient) getFilteredCertManagerResources(ctx context.Context) ([]unstructured.Unstructured, error) {
+	objs, err := cm.proxy.ListResources(ctx, map[string]string{clusterctlv1.ClusterctlCoreLabel: clusterctlv1.ClusterctlCoreLabelCertManagerValue}, certManagerNamespace, metav1.NamespaceSystem)
+	if err != nil {
+		return nil, errors.Wrap(err, "failed get cert manager components")
```
Comment (neolit123) [inline cmd/clusterctl/client/cluster/cert_manager.go:247]:
```suggestion
		return nil, errors.Wrap(err, "failed get cert-manager components")
```

as per the original project naming.,
https://github.com/cert-manager/cert-manager?tab=readme-ov-file#cert-manager

**Review by neolit123 — COMMENTED** [review]
one nit from me as well. 
maybe clustercuctl can eventually keep a better inventory of the cert-manager components.
but this fix seems good to me. thanks

File: cmd/clusterctl/client/cluster/cert_manager.go (hunk 1 above)
Comment (faiq) [reply cmd/clusterctl/client/cluster/cert_manager.go]: words were smith'ed thanks for the feedback

File: cmd/clusterctl/client/cluster/cert_manager.go [hunk 4]
```diff
@@ -201,12 +203,10 @@ func (cm *certManagerClient) install(ctx context.Context, version string, objs [
 // a cert-manager upgrade if necessary.
 func (cm *certManagerClient) PlanUpgrade(ctx context.Context) (CertManagerUpgradePlan, error) {
 	log := logf.Log
-
-	objs, err := cm.proxy.ListResources(ctx, map[string]string{clusterctlv1.ClusterctlCoreLabel: clusterctlv1.ClusterctlCoreLabelCertManagerValue}, certManagerNamespace)
+	objs, err := cm.getFilteredCertManagerResources(ctx)
 	if err != nil {
-		return CertManagerUpgradePlan{}, errors.Wrap(err, "failed get cert manager components")
+		return CertManagerUpgradePlan{}, err
```
Comment (dlipovetsky) [inline cmd/clusterctl/client/cluster/cert_manager.go:208]: I think we want to wrap this with some context, e.g., "failed to calculate relevant cert-manager resources."

Comment (faiq) [reply cmd/clusterctl/client/cluster/cert_manager.go:208]: the error is wrapped already by `getFilteredCertManagerResources` do you think changing the wrap text there would be helpful?

Comment (dlipovetsky) [reply cmd/clusterctl/client/cluster/cert_manager.go:208]: Ok, I see now.

Given that the context we're adding `"failed to calculate cert-manager components for upgrade"`,  I think we it makes more sense to add it here, at the call site, rather than in the `getFilteredCertManagerResources` function. That's because the `proxy.ListResources` call doesn't calculate cert-manager components, but lists them. If we want to, we wrap that error with `"failed to list resources"`.

Comment (faiq) [reply cmd/clusterctl/client/cluster/cert_manager.go:208]: makes sense to me. i'll update the pr.

Comment (dlipovetsky) [reply cmd/clusterctl/client/cluster/cert_manager.go]: Thank you! :pray:

**Comment by faiq** [comment]
I reworked this commit to remove the endpoint/endpointSlices objects in `shouldUpgrade` now all of the code for calculating the upgrade lives in there and no longer requires the caller to have advanced knowledge of what resources it should or shouldn't include.

**Comment by dlipovetsky** [comment]
The diff reads really easily now. Makes sense. Thank you for finding the root cause of this issue!

/lgtm

**Comment by dlipovetsky** [comment]
Once the PR is sorted, I think it's worth backporting to 1.8 and 1.7.

**Comment by sbueringer** [comment]
Please run pull-cluster-api-e2e-main once you're happy with the PR (I want to take a look at the clusterctl upgrade test logs)

File: cmd/clusterctl/client/cluster/cert_manager.go [hunk 5]
```diff
@@ -346,9 +345,14 @@ func (cm *certManagerClient) shouldUpgrade(desiredVersion string, objs, installO
...
-		return obj.GetKind() == "Endpoints" || obj.GetKind() == "EndpointSlice"
-	})
+	newObjs := []unstructured.Unstructured{}
+	for _, o := range objs {
+		if !(o.GetKind() == "Endpoints" || o.GetKind() == "EndpointSlice") {
+			newObjs = append(newObjs, o)
+		}
+	}
+	objs = newObjs
+
```
Comment (dlipovetsky) [inline cmd/clusterctl/client/cluster/cert_manager.go:355]: Looking at this change, I realized that we don't want to modify any slice passed by the caller. Prior to this PR, we were merely ignoring some elements in the `objs` slice, but now we modify it.

I think we can address this by referencing `newObjs`, instead of `objs`, on lines 356 and 357.

(As an aside, I think the name `relevantObjs` might be more helpful than `newObjs`).

Comment (faiq) [reply cmd/clusterctl/client/cluster/cert_manager.go:355]: thats a good point i changed the code because of side effects that i noticed in different methods when i modified the list.

Comment (faiq) [reply cmd/clusterctl/client/cluster/cert_manager.go]: in practice, i think it's fine that endpoints and endpoint slices aren't removed because they will be garbage collected.

**Comment by sbueringer** [comment]
For reference:

main branch: some upgrade test:
* clusterctl init installs 1.16.1 (& CAPI v1.8): https://storage.googleapis.com/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-main/1857336656315551744/artifacts/clusters/clusterctl-upgrade-management-7q8ifk/clusterctl-init.log
* clusterctl upgrade re-installs 1.16.1 (& CAPI v1.9): https://storage.googleapis.com/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-main/1857336656315551744/artifacts/clusters/clusterctl-upgrade-management-7q8ifk/clusterctl-upgrade.log

e2e test on this PR:
* clusterctl init installs 1.16.1 (& CAPI v1.*): https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/11351/pull-cluster-api-e2e-main/1853911582791176192/artifacts/clusters/clusterctl-upgrade-management-w00qku/clusterctl-init.log
* clusterctl upgrade detects correctly that 1.16.1 is already installed: https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/11351/pull-cluster-api-e2e-main/1853911582791176192/artifacts/clusters/clusterctl-upgrade-management-w00qku/clusterctl-upgrade.log

**Comment by sbueringer** [comment]
Feel free to cherry-pick
