### PR TITLE
:bug: Properly adopt cluster secrets on upgrade

### LINKED ISSUE #3144: KCP needs to change owner references of control plane secrets on adoption
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
* Create a v1alpha2 cluster
* Update to v1alpha3, with a KCP with an upgraded version
* All control plane secrets are deleted and recreated except for the kubeconfig
* Cluster is borked

**What did you expect to happen:**
* Control plane secrets are not replaced

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.6
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): v1.16.7
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by sethp-nr**
**What this PR does / why we need it**:

Cluster-scoped secrets in v1alpha2 were generated an owner ref that lacked the "controller=true" property.

That means that checking for a controller reference will fail to adopt any v1a2 secrets, and cause the cluster to enter a broken state on adoption post-upgrade.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3144

### CODE REVIEW

**Comment by sethp-nr** [comment]
Wanted to get this up since it's kind of a big deal. Going to put it on hold while I add a test + some docs.

/hold

File: controlplane/kubeadm/controllers/controller.go [hunk 1]
```diff
@@ -554,7 +554,7 @@ func (r *KubeadmControlPlaneReconciler) adoptOwnedSecrets(ctx context.Context, k
 
 	for i := range secrets.Items {
 		s := secrets.Items[i]
-		if !util.IsControlledBy(&s, currentOwner) {
+		if !util.PointsTo(s.GetOwnerReferences(), currentOwner) {
```
Comment (detiber) [inline controlplane/kubeadm/controllers/controller.go:557]: To avoid hitting an issue if UIDs may not match due to resources being moved to a different cluster.
```suggestion
		if !util.IsOwnedByObject(s.GetOwnerReferences(), currentOwner) {
```

**Comment by ncdc** [comment]
/retest

Thanks @sethp-nr!

/approve

**Comment by vincepri** [comment]
🎉
