### PR TITLE
🐛 Add backported rolloutStrategy to KCP v1alpha3 to fix KCP conversion

### LINKED ISSUE #5236: kcp looses rolloutStrategy field data when upgraded from v1alpha3 to v1alpha4
**What steps did you take and what happened:**
create kind cluster 
```bash 
clusterctl init # Release binary v0.3.23
```

apply kcp 

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: controlplane
  namespace: default
spec:
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  replicas: 9
  version: v1.20.8
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MaasMachineTemplate
    name: controlplane
    namespace: default
  kubeadmConfigSpec: {}
```

get kcp to verify the field data

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"controlplane.cluster.x-k8s.io/v1alpha3","kind":"KubeadmControlPlane","metadata":{"annotations":{},"name":"controlplane","namespace":"default"},"spec":{"infrastructureTemplate":{"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha3","kind":"MaasMachineTemplate","name":"controlplane","namespace":"default"},"kubeadmConfigSpec":{},"replicas":9,"rolloutStrategy":{"rollingUpdate":{"maxSurge":1},"type":"RollingUpdate"},"version":"v1.20.8"}}
  creationTimestamp: "2021-09-15T04:05:54Z"
  generation: 1
  name: controlplane
  namespace: default
  resourceVersion: "1526"
  uid: a46a0f9a-2238-4a23-ac96-f2123e324c4b
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MaasMachineTemplate
    name: controlplane
    namespace: default
  kubeadmConfigSpec: {}
  replicas: 9
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  version: v1.20.8
```

upgrade crd to v0.4.2

by 

```bash
clusterctl4 upgrade apply --contract v1alpha4  #clusterctl4 is Release 0.4.2 binary
```

**What did you expect to happen:**
I would expect kcp to still contain rolloutstrategy but 

```yaml 
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: KubeadmControlPlane
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"controlplane.cluster.x-k8s.io/v1alpha3","kind":"KubeadmControlPlane","metadata":{"annotations":{},"name":"controlplane","namespace":"default"},"spec":{"infrastructureTemplate":{"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha3","kind":"MaasMachineTemplate","name":"controlplane","namespace":"default"},"kubeadmConfigSpec":{},"replicas":9,"rolloutStrategy":{"rollingUpdate":{"maxSurge":1},"type":"RollingUpdate"},"version":"v1.20.8"}}
  creationTimestamp: "2021-09-15T04:05:54Z"
  generation: 1
  name: controlplane
  namespace: default
  resourceVersion: "1526"
  uid: a46a0f9a-2238-4a23-ac96-f2123e324c4b
spec:
  kubeadmConfigSpec: {}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
      kind: MaasMachineTemplate
      name: controlplane
      namespace: default
    metadata: {}
  replicas: 9
  version: v1.20.8
status:
  initialized: false
  ready: false
```

As `spec.infrastructureTemplate` is translated to `spec.machineTemplate` I would expect `rolloutStrategy` 
to not be removed 

**Anything else you would like to add:**
No

**Environment:**

- Cluster-api version: 0.3.23 -> 0.4.2
- Minikube/KIND version: kind v0.11.1 go1.16.4 darwin/amd64
- Kubernetes version: (use `kubectl version`): 
```json
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):  20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

/kind bug
/area api
/area controlplane

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Fixes #5236

Before this PR we didn't have rolloutStrategy in our v1alpha3 types (and the CRD) on the main branch. This lead to the following, during clusterctl upgrade:
* clusterctl upgrade
* rolloutStrategy was pruned from the v1alpha3 resource
* conversion added the default value

More details in https://github.com/kubernetes-sigs/cluster-api/issues/5236#issuecomment-919833859

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

File: test/e2e/clusterctl_upgrade.go [hunk 1]
```diff
@@ -278,7 +278,7 @@ func ClusterctlUpgradeSpec(ctx context.Context, inputGetter func() ClusterctlUpg
 
 			framework.DumpAllResources(ctx, framework.DumpAllResourcesInput{
 				Lister:    managementClusterProxy.GetClient(),
-				Namespace: managementClusterNamespace.Name,
+				Namespace: testNamespace.Name,
```
Comment (sbueringer) [inline test/e2e/clusterctl_upgrade.go:281]: Without this fix we don't get any resources from the cluster where we test the provider upgrade

**Comment by sbueringer** [comment]
/retest
Let's retest, worked locally

File: test/e2e/clusterctl_upgrade.go (hunk 1 above)
Comment (sadysnaat) [reply test/e2e/clusterctl_upgrade.go:281]: @sbueringer thanks for quick fix,

would it make sense to add test cases 
that checks the fields before and after upgrade, even for future upgrades. 
This way we can be sure we don't miss any fields across upgrades

Comment (sbueringer) [reply test/e2e/clusterctl_upgrade.go:281]: I think its hard to catch those kind of errors in our e2e tests:
* The test runs exactly as before even with the fix, because we're using the default value of rolloutStrategy. So you won't see any difference through the fix.
* We would have to change the value of this specific field to something which is not default (afaik in this case I would have to set maxSurge to 0 and also KCP replicas to 3) to catch the error
* Also it's hard to check for something which is missing (when you're not aware of it), i.e. in this case the v1alpha3 structs on main didn't have the field

So I guess we could modify our e2e test so it would catch this specific case of the error (although it's not trivial and not something we usually do in our e2e tests). But not sure how to do this for arbitrary fields which might be missing, when we're not aware of it.

Usually we test these kind of things in our conversion unit tests. But they also cannot catch this error if the structs on the current branch don't have the field.

So I'm not sure if there's an easy way to add a test for something like this. It essentially comes down to we have to keep the v1alpha3 structs between main and release-0.3 sync and then our conversion unit tests on main can catch errors in the conversion

Hope this makes sense :)

**Review by fabriziopandini — COMMENTED** [review]
Thanks for jumping on this!
/lgtm

File: test/e2e/clusterctl_upgrade.go (hunk 1 above)
Comment (sadysnaat) [reply test/e2e/clusterctl_upgrade.go:281]: Agree, keeping types in sync would have better chance to catch these errors

**Comment by vincepri** [comment]
/hold

Given that we're adding fields, shouldn't we remove this line https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/api/v1alpha3/conversion.go#L40 ?

**Comment by sbueringer** [comment]
> /hold
> 
> Given that we're adding fields, shouldn't we remove this line https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/api/v1alpha3/conversion.go#L40 ?

Good question. What happens to older v1alpha3 KCP CRDs which don't have the field yet? (in case we care about them)

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-full-main

@vincepri Done

I was thinking we might still need it given that we have v0.3.x CRDs out there which don't have the field. But now I think that's not relevant because after the v1alpha4 upgrade the v1alpha3 version of the CRD will have the field.

**Review by vincepri — APPROVED** [review]
/approve
/lgtm
