### PR TITLE
🐛  Remove generated names from error messages to reduce reconciliation

### LINKED ISSUE #5945: Reconciliation error doesn't result in exponential backoff
When an error happens during Cluster reconciliation in the topology/cluster controller it doesn't result in an exponential backoff meaning the operation is continually retried even when the configuration is completely broken. 

This makes it harder for users to understand the source of their issues, and CAPI is continually working to reconcile a completely broken config.

This was noticed when reproducing an issue with variable patching from: #5944 

/area topology
/kind bug

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Sanitize error messages in the topology controller to prevent reported errors from causing reconciliation. 

This is a Work In Progress and should not be merged.

Fixes #5945

### CODE REVIEW

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 1]
```diff
@@ -403,21 +403,21 @@ func (r *Reconciler) createMachineDeployment(ctx context.Context, cluster *clust
 		cluster: cluster,
 		desired: md.InfrastructureMachineTemplate,
 	}); err != nil {
-		return errors.Wrapf(err, "failed to create %s", tlog.KObj{Obj: md.Object})
+		return errors.Wrapf(err, "failed to create %s, %s", md.Object.Kind, err)
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/reconcile_state.go:406]: should this be:
```suggestion
		return errors.Wrapf(err, "failed to create %s", md.Object.Kind)
```
otherwise we are reporting twice error (same below)

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 2]
```diff
@@ -269,7 +269,7 @@ func (r *Reconciler) reconcileMachineHealthCheck(ctx context.Context, current, d
 
 		log.Infof("Creating %s", tlog.KObj{Obj: desired})
 		if err := r.Client.Create(ctx, desired); err != nil {
-			return errors.Wrapf(err, "failed to create %s", tlog.KObj{Obj: desired})
+			return createError(err, desired)
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/reconcile_state.go:272]: for sake of consistency, should this be
```suggestion
			errors.Wrapf(err, "failed to create %s", desired.Kind)
```
same below/in other places where we are returning createError without wrapping

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 3]
```diff
@@ -727,3 +727,24 @@ func (r *Reconciler) reconcileReferencedTemplate(ctx context.Context, in reconci
 
 	return nil
 }
+
+// CreateError removes details about the specific name of the object from the Error message. The full names include a hash
+// Cluster conditions.
+func createError(err error, obj client.Object) error {
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/reconcile_state.go:733]: q: should this func goes in the log package

what about
```suggestion
func apiErrorWithoutObjectName(err error, obj client.Object) error {
```

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 4]
```diff
@@ -727,3 +727,24 @@ func (r *Reconciler) reconcileReferencedTemplate(ctx context.Context, in reconci
...
+			}
+			out = fmt.Sprintf("%s %s: %s.", statusError.Status().Details.Kind, statusError.Status().Reason, out)
+		}
+
+		// Replace the statusError message with the constructed message.
+		statusError.ErrStatus.Message = fmt.Sprintf("failed to create %s", out)
+		return statusError
+	}
+	// If this isn't a StatusError return a more generic error with the object details.
+	return errors.Wrapf(err, "failed to create %s", tlog.KObj{Obj: obj})
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/reconcile_state.go:749]: We are using this function both for delete or delete, let's just return plain error in this case

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 5]
```diff
@@ -530,7 +530,7 @@ func (r *Reconciler) deleteMachineDeployment(ctx context.Context, cluster *clust
 	}
 	log.Infof("Deleting %s", tlog.KObj{Obj: md.Object})
 	if err := r.Client.Delete(ctx, md.Object); err != nil && !apierrors.IsNotFound(err) {
-		return errors.Wrapf(err, "failed to delete %s", tlog.KObj{Obj: md.Object})
+		return createError(err, md.Object)
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:533]: This is a delete, I assume we don't want to do this here.

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 4 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:749]: I think it's only used once for delete and that was not intentional

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 3 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:733]: I don't think it should be in the log package as it's not directly related to logs. The error is only logged at some point by controller runtime.

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 6]
```diff
@@ -727,3 +727,24 @@ func (r *Reconciler) reconcileReferencedTemplate(ctx context.Context, in reconci
 
 	return nil
 }
+
+// CreateError removes details about the specific name of the object from the Error message. The full names include a hash
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:731]: Can you please add unit tests including 1-2 cases with real StatusErrors? I have a hard time figuring out how the final error will look like

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 2 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:272]: I think we have to decide if we want to add the "failed to create" here or in the func.

I think it could be better to do it here (as we can provide additional context which is needed in some cases). But then the createError/apiErrorWithoutObjectName should focus on sanitizing the StatusError and not also wrap it with `failed to create ...`.

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 3 above)
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/reconcile_state.go:733]: I think it should live in this package unless we've got some other place it could be used. Right now it's just a single purpose function so I don't see a reason to move it.

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 2 above)
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/reconcile_state.go:272]: For now I'd prefer to keep the create specific information here - I don't think this is more than a single-use function. The additional info can be added by wrapping errors I think - e.g. where the MachineDeployment object kind is added.

Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:272]: Sure, just give it a try.

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 6 above)
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/reconcile_state.go:731]: I've added a test now to show what the output should be.

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 7]
```diff
@@ -403,21 +403,21 @@ func (r *Reconciler) createMachineDeployment(ctx context.Context, cluster *clust
 		cluster: cluster,
 		desired: md.InfrastructureMachineTemplate,
 	}); err != nil {
-		return errors.Wrapf(err, "failed to create %s", tlog.KObj{Obj: md.Object})
+		return errors.Wrapf(createErrorWithoutObjectName(err, md.InfrastructureMachineTemplate), "failed to create %s", md.Object.Kind)
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/reconcile_state.go:406]: q: Is it required to call createErrorWithoutObjectName here, given that it is already called inside reconcileReferencedTemplate?
same below

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 8]
```diff
@@ -429,7 +429,7 @@ func (r *Reconciler) createMachineDeployment(ctx context.Context, cluster *clust
 			*ownerReferenceTo(md.Object),
 		})
 		if err := r.reconcileMachineHealthCheck(ctx, nil, md.MachineHealthCheck); err != nil {
-			return errors.Wrapf(err, "failed to create %s", tlog.KObj{Obj: md.MachineHealthCheck})
+			return err
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/reconcile_state.go:432]: I think that it is fine to keep the error message here, given that the MHC name is not random anymore at this stage (it is the same name of the machine deployment already created)

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 9]
```diff
@@ -242,7 +242,7 @@ func (r *Reconciler) reconcileControlPlane(ctx context.Context, s *scope.Scope)
 
 		// Reconcile the current and desired state of the MachineHealthCheck.
 		if err := r.reconcileMachineHealthCheck(ctx, s.Current.ControlPlane.MachineHealthCheck, s.Desired.ControlPlane.MachineHealthCheck); err != nil {
-			return errors.Wrapf(err, "failed to update %s", tlog.KObj{Obj: s.Desired.ControlPlane.MachineHealthCheck})
+			return err
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:245]: I would also keep the error here, same as in https://github.com/kubernetes-sigs/cluster-api/pull/5971/files#r791625900 (below)

Although I would prefer to use "failed to reconcile" as we don't know if it's a create, update or delete afaik (would be nice if you can adjust other cases of `failed to update` when we're using it after a reconcile, too)

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 8 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:432]: Kind of agree, but as we're already producing this error inside of `reconcileMachineHealthCheck` I think we don't have to wrap it here again. (so we should just return err)

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 10]
```diff
@@ -727,3 +727,25 @@ func (r *Reconciler) reconcileReferencedTemplate(ctx context.Context, in reconci
 
 	return nil
 }
+
+// createErrorWithoutObjectName removes the name of the object from the error message. As each new Create call involves and
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:731]:
```suggestion
// createErrorWithoutObjectName removes the name of the object from the error message. As each new Create call involves an
```

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 11]
```diff
@@ -727,3 +727,25 @@ func (r *Reconciler) reconcileReferencedTemplate(ctx context.Context, in reconci
...
+// on the Cluster, the name is removed here to prevent each creation error from triggering a new reconciliation.
+func createErrorWithoutObjectName(err error, obj client.Object) error {
+	out := ""
+	var statusError *apierrors.StatusError
+	if errors.As(err, &statusError) {
+		if statusError.Status().Details != nil {
+			for _, cause := range statusError.Status().Details.Causes {
+				out = fmt.Sprintf("%s %s: %s: %s", out, cause.Type, cause.Field, cause.Message)
+			}
+			out = fmt.Sprintf("%s.%s: %s.", statusError.Status().Details.Kind, statusError.Status().Details.Group, out)
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:742]:
```suggestion
			out = fmt.Sprintf("%s.%s: %s", statusError.Status().Details.Kind, statusError.Status().Details.Group, out)
```
nit, can we please drop the trailing dot (usually error messages don't have a trailing dot)

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 12]
```diff
@@ -727,3 +727,25 @@ func (r *Reconciler) reconcileReferencedTemplate(ctx context.Context, in reconci
...
+// createErrorWithoutObjectName removes the name of the object from the error message. As each new Create call involves and
+// object with a unique generated name each error appears to be a different error. As the errors are being surfaced in a condition
+// on the Cluster, the name is removed here to prevent each creation error from triggering a new reconciliation.
+func createErrorWithoutObjectName(err error, obj client.Object) error {
+	out := ""
+	var statusError *apierrors.StatusError
+	if errors.As(err, &statusError) {
+		if statusError.Status().Details != nil {
+			for _, cause := range statusError.Status().Details.Causes {
+				out = fmt.Sprintf("%s %s: %s: %s", out, cause.Type, cause.Field, cause.Message)
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:740]: nit, looks like the first "%s" leads to a double space at the beginning. Can we maybe add those errors to a string array and then use  `strings.Join(x, " ")`?

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 13]
```diff
@@ -727,3 +727,25 @@ func (r *Reconciler) reconcileReferencedTemplate(ctx context.Context, in reconci
...
+			}
+			out = fmt.Sprintf("%s.%s: %s.", statusError.Status().Details.Kind, statusError.Status().Details.Group, out)
+		}
+
+		// Replace the statusError message with the constructed message.
+		statusError.ErrStatus.Message = fmt.Sprintf("failed to create %s", out)
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:746]:
```suggestion
		statusError.ErrStatus.Message = fmt.Sprintf("failed to create: %s", out)
```
nit, usually errors are concatenated with a colon as separator

Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:746]: Should we only add `out` if it's not empty? Currently the error would have a trailing space in that case

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 14]
```diff
@@ -727,3 +727,25 @@ func (r *Reconciler) reconcileReferencedTemplate(ctx context.Context, in reconci
 
 	return nil
 }
+
+// createErrorWithoutObjectName removes the name of the object from the error message. As each new Create call involves and
+// object with a unique generated name each error appears to be a different error. As the errors are being surfaced in a condition
+// on the Cluster, the name is removed here to prevent each creation error from triggering a new reconciliation.
+func createErrorWithoutObjectName(err error, obj client.Object) error {
+	out := ""
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:735]: nit: Can we move this var into the innermost scope where it's used?

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 7 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:406]: Looks like we can just return `err` here (as the full error is already build in the reconcile func in all cases)

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 8 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:432]: Same in l.469 and l.528 I think then we will propagate the error generated in reconcileMachineHealthCheck on all call sites of the reconcileMachineHealthCheck func

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 6 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go]: Thx!

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 13 above)
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/reconcile_state.go:746]: If out is empty at this point the error isn't going to be make any sense regardless I think - should we instead return the error on L750 if there's nothing in out?

Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go]: Yes!

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 15]
```diff
@@ -198,13 +199,13 @@ func (r *Reconciler) reconcileControlPlane(ctx context.Context, s *scope.Scope)
 		},
 		)
 		if err != nil {
-			return errors.Wrapf(err, "failed to update %s", tlog.KObj{Obj: s.Desired.ControlPlane.InfrastructureMachineTemplate})
+			return errors.Wrapf(err, "failed to reconcile %s", tlog.KObj{Obj: s.Desired.ControlPlane.InfrastructureMachineTemplate})
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:202]: Do we also only have to log the kind here?

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 16]
```diff
@@ -227,7 +228,7 @@ func (r *Reconciler) reconcileControlPlane(ctx context.Context, s *scope.Scope)
 			},
 		},
 	}); err != nil {
-		return errors.Wrapf(err, "failed to update %s", tlog.KObj{Obj: s.Desired.ControlPlane.Object})
+		return errors.Wrapf(err, "failed to reconcile %s", tlog.KObj{Obj: s.Desired.ControlPlane.Object})
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:231]: Do we also only have to log the kind here?

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 17]
```diff
@@ -460,13 +461,13 @@ func (r *Reconciler) updateMachineDeployment(ctx context.Context, cluster *clust
...
+		return errors.Wrapf(err, "failed to reconcile %s", tlog.KObj{Obj: currentMD.Object})
 	}
 
 	// Patch MachineHealthCheck for the MachineDeployment.
 	if desiredMD.MachineHealthCheck != nil || currentMD.MachineHealthCheck != nil {
 		if err := r.reconcileMachineHealthCheck(ctx, currentMD.MachineHealthCheck, desiredMD.MachineHealthCheck); err != nil {
-			return errors.Wrapf(err, "failed to update %s", tlog.KObj{Obj: desiredMD.MachineHealthCheck})
+			return errors.Wrapf(err, "failed to reconcile %s", tlog.KObj{Obj: desiredMD.MachineHealthCheck})
 		}
 	}
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:472]: Can we drop the wrapping in l.470 and l.529 too?

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 18]
```diff
@@ -727,3 +728,26 @@ func (r *Reconciler) reconcileReferencedTemplate(ctx context.Context, in reconci
...
+				out = strings.Join([]string{out, fmt.Sprintf("%s: %s: %s", cause.Type, cause.Field, cause.Message)}, "") //nolint:gocritic
+			}
+			out = fmt.Sprintf("%s.%s: %s", statusError.Status().Details.Kind, statusError.Status().Details.Group, out)
+		}
+		if len(out) > 0 {
+			// Replace the statusError message with the constructed message.
+			statusError.ErrStatus.Message = fmt.Sprintf("failed to create %s", out)
+			return statusError
+		}
+	}
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:750]:
```suggestion
	if errors.As(err, &statusError) {
		if statusError.Status().Details != nil {
			var causes []string
			for _, cause := range statusError.Status().Details.Causes {
				causes = append(causes, fmt.Sprintf("%s: %s: %s", cause.Type, cause.Field, cause.Message))
			}

			var msg string
			if len(causes) > 0 {
				msg = fmt.Sprintf("failed to create: %s.%s: %s", statusError.Status().Details.Kind, statusError.Status().Details.Group, strings.Join(causes, " "))
			} else {
				msg = fmt.Sprintf("failed to create: %s.%s", statusError.Status().Details.Kind, statusError.Status().Details.Group)
			}

			// Replace the statusError message with the constructed message.
			statusError.ErrStatus.Message = msg
			return statusError
		}
	}
```
I should have explained a bit more. I meant something like this with `strings.Join`. So strings.Join can solve the problem with leading and trailing slashes. 

I think this way we wouldn't end up with cases were we get awkward trailing spaces (like e.g. when we don't have any causes)

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 16 above)
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/reconcile_state.go:231]: Will tlog not take care of that with it's String() method?

Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:231]: tlog.Kobj logs the kind and the name, but the name is random which gives as the reconcile with random errors problem here.

So I was suggesting to use `return errors.Wrapf(err, "failed to reconcile %s", s.Desired.ControlPlane.Object.GetKind())` instead (like we do now in similar cases below)

Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:231]: We could also just drop the whole error here, given that we produce more or less the same but more precise inside of `reconcileReferencedObject`

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 15 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:202]: Same as: https://github.com/kubernetes-sigs/cluster-api/pull/5971#discussion_r791983822

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 16 above)
Comment (killianmuldoon) [reply internal/controllers/topology/cluster/reconcile_state.go:231]: I get you now - I'll just return the errors as they are from here.

**Comment by fabriziopandini** [comment]
Thanks @killianmuldoon for sorting out this problem
/lgtm

**Comment by sbueringer** [comment]
@killianmuldoon 
Thank you!
also for fixing related error propagation issues

/lgtm

**Comment by sbueringer** [comment]
/cherry-pick release-1.1

As it's a problematic bug we should include it in the v1.1 release
