### PR TITLE
🌱 Update Config generation to use inClusterConfig

### LINKED ISSUE #6286: clusterctl inside cluster in pod cannot find management cluster
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

1. Deploy Pod in cluster
2. Install vsphere provider
3. Generate configuration
clusterctl generate cluster $(TEST_CLUSTER_NAME) \
    --infrastructure vsphere \
	-n $(TEST_CLUSTER_NAME) \
    --control-plane-machine-count 1 \
    --worker-machine-count 0 > /tmp/vsphere-test-cluster.yaml

Error: management cluster not available. Cannot auto-discover target namespace. Please specify a target namespace: invalid kubeconfig file; clusterctl requires a valid kubeconfig file to connect to the management cluster: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

**What did you expect to happen:**

It is supposed to find the local capi installation

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v1.1.2
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.21.8
- OS (e.g. from `/etc/os-release`):

runner@mvm-runner-2:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by AbdullahAlShaad**
**What this PR does / why we need it**:

Currently, we cannot use clusterctl binary from inside the pod because it can not find the cluster. This PR updates config generation to use GetConfigOrDie() method from `controller-runtime` so that clusterctl can discover the cluster even kubeconfig is not provided.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6286

/area clusterctl
--> [area/clusterctl](https://github.com/kubernetes-sigs/cluster-api/issues?q=is%3Aopen+label%3Aarea%2Fclusterctl+sort%3Aupdated-desc)

### CODE REVIEW

File: cmd/clusterctl/client/cluster/proxy.go [hunk 1]
```diff
@@ -131,22 +132,7 @@ func (k *proxy) ValidateKubernetesVersion() error {
...
-		Timeout:        k.timeout.String(),
-	}
-	restConfig, err := clientcmd.NewDefaultClientConfig(*config, configOverrides).ClientConfig()
-	if err != nil {
-		if strings.HasPrefix(err.Error(), "invalid configuration:") {
-			return nil, errors.New(strings.Replace(err.Error(), "invalid configuration:", "invalid kubeconfig file; clusterctl requires a valid kubeconfig file to connect to the management cluster:", 1))
-		}
-		return nil, err
-	}
+	restConfig := ctrl.GetConfigOrDie()
```
Comment (chrischdi) [inline cmd/clusterctl/client/cluster/proxy.go:135]: I think the issue with this is, the underlying function tries to use a global kubeconfig flag, which we don't set or use.

Instead I think what we should do is use `rest.InCLusterConfig()` in the error case as fallback.

Comment (AbdullahAlShaad) [reply cmd/clusterctl/client/cluster/proxy.go]: Updated. Anyway, though it would take a lot of refactoring, wouldn't it be better to use kubeconfig flag?

File: cmd/clusterctl/client/cluster/proxy.go [hunk 2]
```diff
@@ -142,10 +142,13 @@ func (k *proxy) GetConfig() (*rest.Config, error) {
...
 	restConfig, err := clientcmd.NewDefaultClientConfig(*config, configOverrides).ClientConfig()
 	if err != nil {
-		if strings.HasPrefix(err.Error(), "invalid configuration:") {
-			return nil, errors.New(strings.Replace(err.Error(), "invalid configuration:", "invalid kubeconfig file; clusterctl requires a valid kubeconfig file to connect to the management cluster:", 1))
+		if !strings.HasPrefix(err.Error(), "invalid configuration:") {
+			return nil, err
+		}
+		restConfig, err = rest.InClusterConfig()
+		if err != nil {
+			return nil, err
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/proxy.go:150]: Let's return an error that expresses that both the kubeconfig and the in cluster config didn't work (previosu error from l.146 + something for in cluster

**Comment by sbueringer** [comment]
I think this should be okay, but would be good to get confirmation from someone more familiar with clusterctl

File: cmd/clusterctl/client/cluster/proxy.go (hunk 2 above)
Comment (AbdullahAlShaad) [reply cmd/clusterctl/client/cluster/proxy.go]: Updated the error message to "invalid kubeconfig file and failed to create inClusterConfig as well"

File: cmd/clusterctl/client/cluster/proxy.go [hunk 3]
```diff
@@ -142,10 +142,13 @@ func (k *proxy) GetConfig() (*rest.Config, error) {
 	}
 	restConfig, err := clientcmd.NewDefaultClientConfig(*config, configOverrides).ClientConfig()
 	if err != nil {
-		if strings.HasPrefix(err.Error(), "invalid configuration:") {
-			return nil, errors.New(strings.Replace(err.Error(), "invalid configuration:", "invalid kubeconfig file; clusterctl requires a valid kubeconfig file to connect to the management cluster:", 1))
+		if !strings.HasPrefix(err.Error(), "invalid configuration:") {
+			return nil, err
```
Comment (enxebre) [inline cmd/clusterctl/client/cluster/proxy.go:146]: any reason to not use controller runtime builtin GetConfig() which handles the fallback for you? i.e.
```
ctrconfig "sigs.k8s.io/controller-runtime/pkg/client/config"
restConfig, err := ctrconfig.GetConfig()
```

Comment (AbdullahAlShaad) [reply cmd/clusterctl/client/cluster/proxy.go:146]: Because GetConfig() uses a global "kubeconfig" flag which clusterctl does not set.

**Comment by sbueringer** [comment]
cc @fabriziopandini

**Comment by fabriziopandini** [comment]
/lgtm
the change is localized and it should not have side effects.

I defer to others when to merge this and if to cherry-pick (or backport). My two cents is to avoid both unless there are specific needs.

**Comment by sbueringer** [comment]
Alrighty. Let's merge it

I"ll cherry-pick into 1.8, because there is no 1.8 release yet, but not further back (otherwise folks would have to wait until December to get this change)

/approve
