### PR TITLE
🐛Delete control plane Machines at the end

### LINKED ISSUE #1351: Deleting a cluster might not work if it tries to delete all control plane machines first
/kind bug

**What steps did you take and what happened:**
1. `k delete cluster foo`
1. CAPI attempted to delete all of the cluster's children, and it happened to start with all the `Machines`. Unfortunately, it deleted all the control plane machines, and it got stuck in an endless loop of errors:

```
I0830 18:17:17.829574       1 machine_controller.go:186] Deleting node "ip-10-0-0-140.ec2.internal" for machine "test1-controlplane-2"
E0830 18:17:17.852462       1 machine_controller.go:188] Error deleting node "ip-10-0-0-140.ec2.internal" for machine "test1-controlplane-2": Delete https://test1-apiserver-xxxxxxxxx.us-east-1.elb.amazonaws.com:6443/api/v1/nodes/ip-10-0-0-140.
ec2.internal: EOF
```

**What did you expect to happen:**
Cluster deletion should succeed

**Environment:**

- Cluster-api version: commit d495192f7

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1351

### CODE REVIEW

File: controllers/cluster_controller.go [hunk 1]
```diff
@@ -258,9 +259,10 @@ func (r *ClusterReconciler) listChildren(ctx context.Context, cluster *clusterv1
...
 	lists := map[string]runtime.Object{
-		"MachineDeployment": machineDeployments,
-		"MachineSet":        machineSets,
-		"Machine":           machines,
+		"MachineDeployment":   machineDeployments,
+		"MachineSet":          machineSets,
+		"Machine":             machines,
+		"MachineControlPlane": controlplanes,
 	}
 	for name, list := range lists {
```
Comment (ncdc) [inline controllers/cluster_controller.go]: Map key sort order is not guaranteed to be consistent

Comment (vincepri) [reply controllers/cluster_controller.go]: Argh, true. Switched to a slice instead

File: controllers/cluster_controller.go [hunk 2]
```diff
@@ -257,14 +258,15 @@ func (r *ClusterReconciler) listChildren(ctx context.Context, cluster *clusterv1
...
+	lists := []runtime.Object{
+		machineDeployments,
+		machineSets,
+		machines,
+		controlplanes,
 	}
-	for name, list := range lists {
+	for _, list := range lists {
 		if err := meta.EachListItem(list, eachFunc); err != nil {
-			return nil, errors.Wrapf(err, "error finding %s children of cluster %s/%s", name, cluster.Namespace, cluster.Name)
```
Comment (ncdc) [inline controllers/cluster_controller.go]: I'd prefer not to lose the metadata about which type we're processing. You could keep the map + add a list for ordering. Range over the list, pull items from the map.

File: controllers/cluster_controller.go [hunk 3]
```diff
@@ -237,10 +237,11 @@ func (r *ClusterReconciler) listChildren(ctx context.Context, cluster *clusterv1
 		return nil, errors.Wrapf(err, "failed to list MachineSets for cluster %s/%s", cluster.Namespace, cluster.Name)
 	}
 
-	machines := &clusterv1.MachineList{}
-	if err := r.Client.List(ctx, machines, listOptions...); err != nil {
+	allMachines := &clusterv1.MachineList{}
+	if err := r.Client.List(ctx, allMachines, listOptions...); err != nil {
 		return nil, errors.Wrapf(err, "failed to list Machines for cluster %s/%s", cluster.Namespace, cluster.Name)
 	}
+	controlplanes, machines := util.SplitMachineList(allMachines)
```
Comment (ncdc) [inline controllers/cluster_controller.go]: controlPlaneMachines

File: util/util.go [hunk 4]
```diff
@@ -383,3 +383,18 @@ func HasOwner(refList []metav1.OwnerReference, apiVersion string, kinds []string
 
 	return false
 }
+
+// SplitMachineList separates the machines running the control plane from other worker nodes.
+func SplitMachineList(list *clusterv1.MachineList) (*clusterv1.MachineList, *clusterv1.MachineList) {
```
Comment (ncdc) [inline util/util.go]: This is very specific and I'd prefer not to have it in util. Could you move it into cluster_controller.go?

File: controllers/cluster_controller.go (hunk 3 above)
Comment (detiber) [reply controllers/cluster_controller.go]: Is this mainly to prevent issues when deleting the Node objects? I have a local patch that just ignores errors for deleting the node if it includes `io.EOF`.

File: util/util.go (hunk 4 above)
Comment (vincepri) [reply util/util.go]: sgtm

File: controllers/cluster_controller.go (hunk 2 above)
Comment (vincepri) [reply controllers/cluster_controller.go]: I don't think that's actually needed, the only error we return (and the ones returned from EachListItem) already contain the type information. This seems really extra

File: controllers/cluster_controller.go (hunk 3 above)
Comment (vincepri) [reply controllers/cluster_controller.go]: We might need a second patch to ignore the deletion of related nodes if all control plane machines are being deleted

File: controllers/cluster_controller.go (hunk 2 above)
Comment (ncdc) [reply controllers/cluster_controller.go]: Fair enough

File: controllers/cluster_controller.go [hunk 5]
```diff
@@ -257,16 +258,32 @@ func (r *ClusterReconciler) listChildren(ctx context.Context, cluster *clusterv1
...
-			return nil, errors.Wrapf(err, "error finding %s children of cluster %s/%s", name, cluster.Namespace, cluster.Name)
+			return nil, errors.Wrapf(err, "error finding children of cluster %s/%s", cluster.Namespace, cluster.Name)
 		}
 	}
 
 	return children, nil
 }
+
+// SplitMachineList separates the machines running the control plane from other worker nodes.
+func SplitMachineList(list *clusterv1.MachineList) (*clusterv1.MachineList, *clusterv1.MachineList) {
```
Comment (ncdc) [inline controllers/cluster_controller.go]: Doesn't technically need to be exported

Comment (vincepri) [reply controllers/cluster_controller.go]: Fixed, thx

**Comment by ncdc** [comment]
LGTM
