### PR TITLE
🐛Fix patch in MachineSet adoption

### LINKED ISSUE #1429: Machine adoption into MachineSet is ineffective
/kind bug

**What steps did you take and what happened:**

1. boostrapped a k8s-on-GCP cluster via KIND ala CAP/GCP
2. executed pivot operation that failed after cluster was moved (see https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/171) - but was mostly successful since all the CAPI+GCP objects were migrated over
3. observe that every 10m (the reconciliation period) CAPI logs that its adopting some machines into a machineset. there are only 2 worker machines in the cluster (these) and the adoption doesn't look to be successful since it keeps repeated these same messages over and over - without reporting any errors.

```
I0920 13:51:28.949677       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-ls5vt" into MachineSet "test1-md-0-76b648f67c"
I0920 13:51:28.957711       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-nljcm" into MachineSet "test1-md-0-76b648f67c"
I0920 13:51:28.983681       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-ls5vt" into MachineSet "test1-md-0-76b648f67c"
I0920 13:51:28.992862       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-nljcm" into MachineSet "test1-md-0-76b648f67c"
I0920 14:01:28.949068       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-ls5vt" into MachineSet "test1-md-0-76b648f67c"
I0920 14:01:28.958332       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-nljcm" into MachineSet "test1-md-0-76b648f67c"
I0920 14:01:28.983239       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-ls5vt" into MachineSet "test1-md-0-76b648f67c"
I0920 14:01:28.990763       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-nljcm" into MachineSet "test1-md-0-76b648f67c"
I0920 14:11:28.950398       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-ls5vt" into MachineSet "test1-md-0-76b648f67c"
I0920 14:11:28.958430       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-nljcm" into MachineSet "test1-md-0-76b648f67c"
I0920 14:11:28.982400       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-ls5vt" into MachineSet "test1-md-0-76b648f67c"
I0920 14:11:28.989778       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-nljcm" into MachineSet "test1-md-0-76b648f67c"
I0920 14:21:28.950356       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-ls5vt" into MachineSet "test1-md-0-76b648f67c"
I0920 14:21:28.957526       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-nljcm" into MachineSet "test1-md-0-76b648f67c"
I0920 14:21:28.980432       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-ls5vt" into MachineSet "test1-md-0-76b648f67c"
I0920 14:21:28.988701       1 machineset_controller.go:182] Adopted Machine "test1-md-0-76b648f67c-nljcm" into MachineSet "test1-md-0-76b648f67c"
```

**What did you expect to happen:**

adoption to succeed and for the CAPI controller to be happy again.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v1alpha2 (built from master, minus #1411 )
- Minikube/KIND version: 0.5.x
- Kubernetes version: (use `kubectl version`): 1.15.3
- OS (e.g. from `/etc/os-release`): mixed (centos, ubuntu)

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1429

### CODE REVIEW

File: controllers/machineset_controller.go [hunk 1]
```diff
@@ -386,7 +386,7 @@ func shouldExcludeMachine(machineSet *clusterv1.MachineSet, machine *clusterv1.M
 
 // adoptOrphan sets the MachineSet as a controller OwnerReference to the Machine.
 func (r *MachineSetReconciler) adoptOrphan(machineSet *clusterv1.MachineSet, machine *clusterv1.Machine) error {
-	patch := client.MergeFrom(machine)
+	patch := client.MergeFrom(machine.DeepCopy())
```
Comment (detiber) [inline controllers/machineset_controller.go]: :grimacing: Since this goes back to my patch updates I went ahead to see if I messed up any other places, and it turns out I did: https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machinedeployment_sync.go#L106

Comment (vincepri) [reply controllers/machineset_controller.go]: Great catch! Added to the PR
