### PR TITLE
🐛 test: pin conformance image to a version which includes a fix for the dualstack tests

### LINKED ISSUE #9240: Dualstack tests failing
### Which jobs are failing?

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-dualstack-and-ipv6-main

### Which tests are failing?

A number of tests are failing consistently.	 Logs etc. are available here: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-dualstack-and-ipv6-main/1692233880087564288

### Since when has it been failing?

Since August 17th

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-dualstack-and-ipv6-main

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

The dualstack tests for KIND were failing in the exact same way for a day or so - the solution in CAPI is likely the same as in KIND

Ref: https://testgrid.kubernetes.io/sig-network-kind#sig-network-kind,%20dual,%20master

### Label(s) to be applied

/kind failing-test

@kubernetes-sigs/cluster-api-release-team 
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Pins the container image used for kubernetes conformance tests in our dualstack tests to the version of commit: https://github.com/kubernetes/kubernetes/commit/18290bfdc8f

This is to include the following fixes:

- https://github.com/kubernetes/kubernetes/pull/119928
- https://github.com/kubernetes/kubernetes/pull/119966

Note: this fixes are getting cherry-picked to kubernetes `release-1.28` in:

- https://github.com/kubernetes/kubernetes/pull/119964

And the introduced changes should get dropped when we bump to a newer version than `v1.28.0` at 

https://github.com/kubernetes-sigs/cluster-api/blob/d57f454ab0185966348671a43beb46c1f6da7efd/test/e2e/config/docker.yaml#L241

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9240

### CODE REVIEW

File: test/e2e/quick_start_test.go [hunk 1]
```diff
@@ -125,6 +125,9 @@ var _ = Describe("When following the Cluster API quick-start with dualstack and
 						ClusterProxy:       proxy.GetWorkloadCluster(ctx, namespace, clusterName),
 						ArtifactsDirectory: artifactFolder,
 						ConfigFilePath:     "./data/kubetest/dualstack.yaml",
```
Comment (sbueringer) [inline test/e2e/quick_start_test.go:127]: Please also add a TODO in docker.yaml directly above "KUBERNETES_VERSION". This should be hard to miss when we change KUBERNETES_VERSION the next time

**Comment by sbueringer** [comment]
In general lgtm. Thx for taking care of this!

**Comment by sbueringer** [comment]
Thx!
/lgtm
/approve

/hold
for green CI
