### PR TITLE
:bug: [clusterctl] accept prereleases when no releases published

### LINKED ISSUE #3496: Can't install pre-release providers from repo with no "latest" release.
**What steps did you take and what happened:**

Using the [talos bootstrap provider](https://github.com/talos-systems/cluster-api-bootstrap-provider-talos), I'm seeing this when trying to install a pre-release from the repo with no "latest" release. (as in, no non-prereleases in the repo)

```
$ ./bin/clusterctl init -b "talos:v0.2.0-alpha.0" -c "-" -i "-"
Fetching providers
Error: failed to get provider components for the "talos:v0.2.0-alpha.0" provider: failed to get repository client for the BootstrapProvider with name talos: error creating the GitHub repository client: failed to get GitHub latest version: failed to find releases tagged with a valid semantic version number
```
This occurs because https://github.com/kubernetes-sigs/cluster-api/blob/38810211da3f71dd3ce61d9f1fa85a690dd98790/cmd/clusterctl/client/repository/repository_github.go#L161 gets called any time a github repository is created from the newGithubRepository function. I _think_ we should provide some way to say "don't bother looking up latest" in the newGithubRepository function if a version tag is specified.

**What did you expect to happen:**
clusterctl init -b "talos:v0.2.0-alpha.0" works as expected by installing a snazzy talos bootstrap provider of the given version.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Totally understand that this probably isn't a widespread problem, but it'll break the built in talos providers. It just doesn't line up with our release cadence on the providers and we haven't gotten to a point where we're comfortable with releasing a GA release of these.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by rsmitty**
**What this PR does / why we need it**:

This PR fixes a bug in clusterctl where, if a provider repo didn't have
*any* stable releases published, all releases were ignored and the init
failed. We now fall back to accepting prereleases if no stables are
found.

Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3496

### CODE REVIEW

File: cmd/clusterctl/client/repository/repository_github.go [hunk 1]
```diff
@@ -268,8 +269,13 @@ func (g *gitHubRepository) getLatestRelease() (string, error) {
 		}
 	}
 
+	// Fall back to looking for latest prereleases if no release has been cut or bail if we're already there
 	if latestTag == "" {
-		return "", errors.New("failed to find releases tagged with a valid semantic version number")
+		if g.acceptPrerelease {
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/repository/repository_github.go:274]: Wondering if there is a way to avoid the `acceptPrerelease` flag at repository level, because it might have side effects on subsequent calls on getLatestRelease.

What about computing both  `latestTag` and `latestPreReleaseTag` (new) during the for loop and return the latter if latestTag is null? 
Computing both values in a single call could avoid the nested call to `getLatestRelease` and thus the need of the `acceptPrerelease` flag ...

Comment (rsmitty) [reply cmd/clusterctl/client/repository/repository_github.go:274]: yeah, that's probably fair. let me revisit this AM.

Comment (rsmitty) [reply cmd/clusterctl/client/repository/repository_github.go]: @fabriziopandini yep, this is quite a bit cleaner. updated in amended commit.

**Comment by fabriziopandini** [comment]
@rsmitty thanks for picking up my suggestions!
/approve
over to @wfernandes for final lgtm

**Comment by rsmitty** [comment]
okay @wfernandes, rebased against master and added a test for the local repo as well.
