### PR TITLE
:seedling: kubetest: Remove usage of Viper, converting config files to kubetest arguments

### LINKED ISSUE #4729: Remove use of Viper in kubetest framework
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

https://github.com/kubernetes/kubernetes/pull/102598 removes Viper from the Kubernetes e2e framework, but we are using it in the e2e framework, with CAPA and CAPZ as consumers.

**What did you expect to happen:**
Not use Viper

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Should be able to do this in such a way as to not break the contract with the providers using the e2e framework

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 

/lifecycle active
/assign @randomvariable

### PR DESCRIPTION
**Pull request by randomvariable**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4729

### CODE REVIEW

**Comment by randomvariable** [comment]
Need to test it.

File: test/framework/kubetest/run.go [hunk 1]
```diff
@@ -28,6 +28,7 @@ import (
 	"strings"
 
 	"github.com/pkg/errors"
+	"gopkg.in/yaml.v3"
```
Comment (randomvariable) [inline test/framework/kubetest/run.go:31]: I'll switch this import.
Need to do a little linter that stops us accidentally importing this instead of the sigs one.

File: test/framework/kubetest/run.go [hunk 2]
```diff
@@ -164,13 +162,32 @@ func Run(ctx context.Context, input RunInput) error {
...
+
+func (c kubetestConfig) toFlags() []string {
+	return buildArgs(c, "-")
+}
+
+func parseKubetestConfig(kubetestConfigFile string) (kubetestConfig, error) {
+	conf := make(kubetestConfig)
+	data, err := os.ReadFile(kubetestConfigFile)
+	if err != nil {
+		return nil, err
```
Comment (randomvariable) [inline test/framework/kubetest/run.go:183]: I'll wrap the error with a suitable error message in the complete version

**Comment by randomvariable** [comment]
tested locally

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Comment by vincepri** [comment]
/override pull-cluster-api-test-main

Tests are passing except for the known flake.
