### PR TITLE
:seedling: MachineDeployment: fix misleading log statements and optimize logic

### LINKED ISSUE #12860: Misleading logic or log statements for `MachineDeployment` reconciler
### What steps did you take and what happened?

In the `MachineDeployment` controller which reconciles and assigns the `machineSets` on the `scope` struct, there are either misleading log statements and unnecessary many checks, or an unintentional logic.

In the function `getAndAdoptMachineSetsForDeployment` there is a [loop](https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/machinedeployment/machinedeployment_controller.go#L436-L474) going through the `machineSets`:
```go
for idx := range machineSets.Items {
	ms := &machineSets.Items[idx]
	log := log.WithValues("MachineSet", klog.KObj(ms))
	ctx := ctrl.LoggerInto(ctx, log)
	selector, err := metav1.LabelSelectorAsSelector(&md.Spec.Selector)
	if err != nil {
		log.Error(err, "Skipping MachineSet, failed to get label selector from spec selector")
		continue
	}

	// If a MachineDeployment with a nil or empty selector creeps in, it should match nothing, not everything.
	if selector.Empty() {
		log.Info("Skipping MachineSet as the selector is empty")
		continue
	}

	// ... Rest of the logic
}
```

To me there seems to be something misleading with this loop, there are two possible options as I see it:

### Option 1
The selector `metav1.LabelSelectorAsSelector(&md.Spec.Selector)` is **indeed** supposed to fetch the selector from `MachineDeployment` and the following two log statements are simply wrong and should be `MachineDeployment` instead `MachineSet`. In this case, why aren't these checks before the for-loop, the `MachineDeployment` selector property aren't changing in the loop.

**New logic:**
```go
selector, err := metav1.LabelSelectorAsSelector(&md.Spec.Selector)
if err != nil {
	log.Error(err, "Skipping MachineDeployment, failed to get label selector from spec selector")
	continue
}

// If a MachineDeployment with a nil or empty selector creeps in, it should match nothing, not everything.
if selector.Empty() {
	log.Info("Skipping MachineDeployment as the selector is empty")
	continue
}

for idx := range machineSets.Items {
	ms := &machineSets.Items[idx]
	log := log.WithValues("MachineSet", klog.KObj(ms))
	ctx := ctrl.LoggerInto(ctx, log)
	
	// ... Rest of the logic
}
```

### Option 2
The selector `metav1.LabelSelectorAsSelector(&md.Spec.Selector)` is wrong and should **not** fetch the selector from `MachineDeployment`, but rather from `MachineSet`, which by the rest of the logic in the loop would make sense.

**New logic:** (Looking awfully similar, but the **md** in `LabelSelectorAsSelector` are changed to **ms**) 
```go
for idx := range machineSets.Items {
	ms := &machineSets.Items[idx]
	log := log.WithValues("MachineSet", klog.KObj(ms))
	ctx := ctrl.LoggerInto(ctx, log)
	selector, err := metav1.LabelSelectorAsSelector(&ms.Spec.Selector)
	if err != nil {
		log.Error(err, "Skipping MachineSet, failed to get label selector from spec selector")
		continue
	}

	// If a MachineDeployment with a nil or empty selector creeps in, it should match nothing, not everything.
	if selector.Empty() {
		log.Info("Skipping MachineSet as the selector is empty")
		continue
	}

	// ... Rest of the logic
}
```

### What did you expect to happen?

Either log statements to be correct and consistent or logic to be correct.

### Cluster API version

Both in `1.10.x`, but also present in `main` branch in `1.11.x`.

### Kubernetes version

Does not matter in this case.

### Anything else you would like to add?

If needed, I can help solve it.

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by steffen-karlsson**
**What this PR does / why we need it**:
Implementing Option 1 from #12860.
Changing misleading log statement as well as unnecessary amount of lookups on `MachineDeployment`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #12860

### CODE REVIEW

File: internal/controllers/machinedeployment/machinedeployment_controller.go [hunk 1]
```diff
@@ -432,22 +432,23 @@ func (r *Reconciler) getAndAdoptMachineSetsForDeployment(ctx context.Context, s
...
+	if err != nil {
+		log.Error(err, "Skipping MachineDeployment, failed to get label selector from spec selector")
+		return err
+	}
+
+	// If a MachineDeployment with a nil or empty selector creeps in, it should match nothing, not everything.
+	if selector.Empty() {
+		log.Info("Skipping MachineDeployment as the selector is empty")
+		return nil
+	}
```
Comment (sbueringer) [inline internal/controllers/machinedeployment/machinedeployment_controller.go:442]:
```suggestion
	selector, err := metav1.LabelSelectorAsSelector(&md.Spec.Selector)
	if err != nil {
		return errors.Wrapf(err, "failed to get MachineSets: failed to compute label selector from MachineDeployment.spec.selector")
	}

	if selector.Empty() {
		return errors.New("failed to get MachineSets: label selector computed from MachineDeployment.spec.selector is empty")
	}
```

I think we should make these both errors cases with proper error messages

**Comment by sbueringer** [comment]
Thx!

/lgtm

/assign @fabriziopandini
