### PR TITLE
  🏃Add semver version validation rules to Machine type and fix KCP version validation

### LINKED ISSUE #2657: Add semver version validation rules wherever it applies
We added validation for KCP spec.version here: https://github.com/kubernetes-sigs/cluster-api/pull/2647

Similarly, we should add validation rules for other resources too, such as  Machines and MachineDeployments.

cc @vincepri

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**
This PR adds semver version validation for Machine type.
Fixes #2657

### CODE REVIEW

**Comment by vincepri** [comment]
waiting for ci to finish before lgtm

File: api/v1alpha3/machine_webhook_test.go [hunk 1]
```diff
@@ -189,3 +189,46 @@ func TestMachineClusterNameImmutable(t *testing.T) {
...
+
+			m := &Machine{
+				Spec: MachineSpec{
+					Version:   &tt.version,
+					Bootstrap: Bootstrap{ConfigRef: nil, DataSecretName: pointer.StringPtr("test")},
+				},
+			}
+
+			if tt.expectErr {
+				g.Expect(m.ValidateCreate()).NotTo(Succeed())
```
Comment (JoelSpeed) [inline api/v1alpha3/machine_webhook_test.go]: Most of the tests in this package that don't test immutability test create and update, might be good to keep it consistent here too?
```suggestion
				g.Expect(m.ValidateCreate()).NotTo(Succeed())
				g.Expect(m.ValidateUpdate(m)).NotTo(Succeed())
```

File: api/v1alpha3/machine_webhook_test.go [hunk 2]
```diff
@@ -189,3 +189,46 @@ func TestMachineClusterNameImmutable(t *testing.T) {
...
+			} else {
+				g.Expect(m.ValidateCreate()).To(Succeed())
```
Comment (JoelSpeed) [inline api/v1alpha3/machine_webhook_test.go]: As above
```suggestion
				g.Expect(m.ValidateCreate()).To(Succeed())
				g.Expect(m.ValidateUpdate(m)).To(Succeed())
```

**Comment by sedefsavas** [comment]
> Just wondering what happens if the version string is `v1` or `v1.7`, will this pass validation? Are they valid version strings in this context?

Yes, those are valid as I use semver.ParseTolerant(), if we want to limit that but still accept preceding "v", we can use both ParseTolerant() followed by Parse()

File: api/v1alpha3/machine_webhook_test.go (hunk 1 above)
Comment (sedefsavas) [reply api/v1alpha3/machine_webhook_test.go]: Good point! Added.

**Comment by JoelSpeed** [comment]
> ParseTolerant() followed by Parse()

I'm not sure how this would help? Since `v1.17` isn't a valid Kubernetes version I think we should be failing that, only versions including the patch number should be allowed IMO. 

Looking at how `ParseTolerant` and `Parse` are implemented, I think keeping the [trimming](https://github.com/blang/semver/blob/1a9109f8c4a1d669a78442f567dfe8eedf982793/semver.go#L238-L239) from `ParseTolerant` and then using `Parse` should work to enforce a pattern that is compliant with the Kubernetes releases, WDYT?

**Comment by sedefsavas** [comment]
Right, modified it accordingly. Thanks for reviewing!

File: api/v1alpha3/machine_webhook.go [hunk 3]
```diff
@@ -114,6 +116,16 @@ func (m *Machine) validate(old *Machine) error {
 		)
 	}
 
+	if m.Spec.Version != nil {
+		*m.Spec.Version = strings.TrimSpace(*m.Spec.Version)
```
Comment (JoelSpeed) [inline api/v1alpha3/machine_webhook.go]: I would suggest using a new variable for this rather than modifying the object that is being validated, just in case other validations may rely on this in the future I think modifying in place could cause unexpected behaviour
```
		version := strings.TrimSpace(*m.Spec.Version)
                version = strings.TrimPrefix(version, "v")
		_, err := semver.Parse(version)
```

File: api/v1alpha3/machine_webhook.go [hunk 4]
```diff
@@ -114,6 +116,16 @@ func (m *Machine) validate(old *Machine) error {
...
+		*m.Spec.Version = strings.TrimPrefix(*m.Spec.Version, "v")
+		_, err := semver.Parse(*m.Spec.Version)
+		if err != nil {
```
Comment (vincepri) [inline api/v1alpha3/machine_webhook.go]:
```suggestion
		if _, err := _, err := semver.Parse(*m.Spec.Version); err  != nil {
```

**Comment by vincepri** [comment]
Should we also change the validation in KCP to match what we're doing here?

File: api/v1alpha3/machine_webhook.go [hunk 5]
```diff
@@ -114,6 +116,15 @@ func (m *Machine) validate(old *Machine) error {
 		)
 	}
 
+	if m.Spec.Version != nil {
+		version := strings.TrimSpace(*m.Spec.Version)
+		version = strings.TrimPrefix(version, "v")
+
+		if _, err := semver.Parse(version); err != nil {
```
Comment (vincepri) [inline api/v1alpha3/machine_webhook.go]:
```suggestion
		if _, err := semver.Parse(strings.TrimPrefix(strings.TrimSpace(*m.Spec.Version), "v"); err != nil {
```

**Comment by vincepri** [comment]
@sedefsavas mind rebasing?
