### PR TITLE
✨ implement failure domain picking

### LINKED ISSUE #2131: Control plane failure domain handling
Some brief background. A failure domain is a component of infrastructure that can fail. In AWS and azure these can be thought of as availability zone. In Google Cloud these are simply called zones. This concept is named failure domain to also account for other types of infrastructure isolation in environments we don't and can't know about, such as a custom bare metal environment.

There is a bit of an intricate interaction between components:

1. The infrastructure provider [defines a `failureDomains` field in the Status of the InfraCluster struct](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/api/v1alpha3/awscluster_types.go#L89).
2. The infrastructure cluster controller [figures out what availability zones/failure domains exist and sets the status on the InfraCluster](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/controllers/awscluster_controller.go#L169-L181)
3. This data gets [copied into Cluster API buy the cluster controller](https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/cluster_controller_phases.go#L178-L182).
4. This data can now be used by other controllers since other other controllers will have access to the Cluster API cluster object.

In a simple case, the user creates their InfraCluster and Cluster objects and the failure domains get copied over. The kubeadm control plane controller can then take the list of failure domains on the cluster object and start assigning failure domains to machines that it creates. However, there are plenty of ways this can go wrong and edge cases we want to consider.

I firmly believe we can implement a naive solution for v1alpha3 and iterate as we go forward, but this issue can help us flesh out the edge cases that we may encounter moving forward.

# Necessary assumptions

If we make the assumption that all failure domains that the infra cluster controller sets on the infraCluster.status.failureDomains can communicate with each other, then you can stop reading here and close the issue as there won't be a problem in the cases outlined below.

If however, we cannot make that assumption, we may encounter some serious problems, theoretically, that we, at some point, not necessarily v1alpha3, will want to take into account. Below are listed the two cases that will cause problems.

## Case 1: Changing zones

A control plane of n >=3 nodes requires at *least* two reconciliations to become active. The first reconciliation will create the first node. The second reconciliation will create the remaining nodes. The list of failure domains is read from the cluster during each reconciliation loop. This means that if the list of failure domains changes between the first and second reconciliation it is possible to end up in a state where one machine exists in a failure domain that is no longer supported.

## Case 2: Updating zones after initialization

Imagine a happy case where a control plane of n=3 nodes has successfully been created and is evenly distributed across multiple failure domains. Now, something happens to the cloud and the infrastructure provider realizes the availability zones have changed which then triggers an update of the InfraCluster.status.failureDomains which then gets copied into the cluster.status.failureDomains. Now we decide to scale the control plane to n=5. We get two new nodes in two new failure domains. Scale down is an ok event since we aren't adding anything. Upgrade also breaks due to new nodes in new failure domains that don't work with old failure domains.

## Solution, the easy assumption

To see an implementation where we have made the assumption that failure domains work together, please see this PR: https://github.com/kubernetes-sigs/cluster-api/pull/2126.

## Solution, the hard assumption

We will have to manage state relative to the control plane. For example, when a control plane is spun up it captures the failure domains from the Cluster object and DOES NOT update them until either a scale to 0 event or perhaps an upgrade event which would create a new control plane in an entirely new region, however we can't assume migration would work here so this case may be hopeless and the only solution would be new cluster in the new failure domains copied manually with something like velero. 

cc @randomvariable @detiber 

/kind feature

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
This PR adds failure domain picking to the KubeadmControlPlane. There is no change to logic if failure domain is not defined. If a failure domain is defined then the KubeadmControlPlane controller will evenly distribute machines across all defined failure domains.

This is a naive approach. Please see #2131 for more details.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2131 
Related to #1756 

/assign @detiber

### CODE REVIEW

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go [hunk 1]
```diff
@@ -439,6 +459,9 @@ func (r *KubeadmControlPlaneReconciler) generateMachine(ctx context.Context, kcp
 			},
 		},
 	}
+	if fd != "" {
+		machine.Spec.FailureDomain = &fd
```
Comment (vincepri) [inline controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: Why not return `*string` from the function so we can just assign it to the Spec?

File: controlplane/kubeadm/internal/failure_domain.go [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+func (f *FailureDomainPicker) pick(failureDomains clusterv1.FailureDomains, machineList *clusterv1.MachineList) failureDomainAggregations {
+	if len(failureDomains) == 0 {
+		return failureDomainAggregations{}
+	}
+	if machineList == nil {
+		return failureDomainAggregations{}
+	}
+	aggregations := make(failureDomainAggregations, len(failureDomains))
+
+	count := map[string]int{}
```
Comment (vincepri) [inline controlplane/kubeadm/internal/failure_domain.go]:
```suggestion
	counters := map[string]int{}
```

Given that `count` is used twice as variable in the for loop a few blocks down

File: controlplane/kubeadm/internal/failure_domain.go [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+
+	// Initialize the known failure domain keys to find out if an existing machine is in an unsupported failure domain.
+	for fd := range failureDomains {
+		count[fd] = 0
+	}
+
+	// Count how many machines are in each failure domain.
+	for _, m := range machineList.Items {
+		if m.Spec.FailureDomain == nil {
```
Comment (vincepri) [inline controlplane/kubeadm/internal/failure_domain.go]: maybe do `id := m.Spec.FailureDomain` so we don't have to de-reference the variable multiple times?

File: controlplane/kubeadm/internal/failure_domain.go [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+	sort.Sort(aggregations)
+	return aggregations[0].id
+}
+
+func (f *FailureDomainPicker) pick(failureDomains clusterv1.FailureDomains, machineList *clusterv1.MachineList) failureDomainAggregations {
+	if len(failureDomains) == 0 {
+		return failureDomainAggregations{}
+	}
+	if machineList == nil {
+		return failureDomainAggregations{}
```
Comment (detiber) [inline controlplane/kubeadm/internal/failure_domain.go]: I'm wondering if it might be better to put this condition around the loop on machineList.Items instead of returning early with empty aggregations here. That way a nil MachineList would result in aggregations populated with a 0 count rather than no aggregations.

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go (hunk 1 above)
Comment (chuckha) [reply controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: What's the benefit of return `*string` over how I've done it?

File: controlplane/kubeadm/internal/failure_domain.go (hunk 4 above)
Comment (chuckha) [reply controlplane/kubeadm/internal/failure_domain.go]: I don't understand what you're suggesting, how is aggregations populated with 0 items different from no aggregations?

 But I do see a better way to structure this code that should be slightly more clear

Comment (detiber) [reply controlplane/kubeadm/internal/failure_domain.go]: It *should* allow `PickFewest` to return a failure domain ID rather than `""`.

File: controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go (hunk 1 above)
Comment (vincepri) [reply controlplane/kubeadm/controllers/kubeadm_control_plane_controller.go]: We can assign it to Spec without the check if `fd` is an empty string

**Comment by chuckha** [comment]
> @chuckha since this PR is marked as Fixing #2131, do we need another issue to track setting the Failure domain for a Machine post-creation if a provider later adds failure domain support?

This is really two issues.

One requires documentation for infrastructure providers saying that if they decide to add support for failure domains then the provider also needs to update the InfraMachines with their existing failure domain as the machine-controller in cluster-api would have no way to figure out which failure domain the machine lives in.

The second part is having the machine controller copy the infra machine failure domain into the machine.

I'll open these issues later on.

**Comment by detiber** [comment]
> This is really two issues.

> One requires documentation for infrastructure providers saying that if they decide to add support for failure domains then the provider also needs to update the InfraMachines with their existing failure domain as the machine-controller in cluster-api would have no way to figure out which failure domain the machine lives in.

> The second part is having the machine controller copy the infra machine failure domain into the machine.

> I'll open these issues later on.

sgtm, just wanted to make sure we don't drop tracking for it :)

File: controlplane/kubeadm/internal/failure_domain.go (hunk 4 above)
Comment (chuckha) [reply controlplane/kubeadm/internal/failure_domain.go]: Updated the code such that this is now how it works with a test case showing this is how it works
