### PR TITLE
🐛 internal/machine-controller fix flakes in phases test

### LINKED ISSUE #8477: TestReconcileMachinePhases is flaky
### Which jobs are flaking?

TestReconcileMachinePhases/Should_set_`Provisioned`_when_there_is_a_ProviderID_and_there_is_no_Node

### Which tests are flaking?

Part of the unit test run. Flaking on main and 1.4.

### Since when has it been flaking?

https://github.com/kubernetes-sigs/cluster-api/pull/8044 moved these tests to be based on envtest instead of the fake client. Since then there has been a number of flakes.

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-release-1-4/1643034564504850432

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Label(s) to be applied

/kind flake
/area testing

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

The test patches the status of the Machine, while the reconciliation may be already happening. This leads to inconsistent state which is not deterministic and into the Machine's status to never reach the targeted state of the test.

With this change, the test just ensures that the LastUpdated timestamp gets set to a later time.

See [this](https://storage.googleapis.com/k8s-triage/index.html?text=Timed%20out%20after%2010&job=.*-cluster-api-.*&test=sigs.k8s.io%2Fcluster-api%2Finternal&xjob=.*-provider-.*) for current flake occurency.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8477

### CODE REVIEW

File: internal/controllers/machine/machine_controller_phases_test.go [hunk 1]
```diff
@@ -281,14 +281,13 @@ func TestReconcileMachinePhases(t *testing.T) {
...
+		// We have to subtract 2 seconds, because .status.lastUpdated does not contain miliseconds.
+		preUpdate := time.Now().Add(-2 * time.Second)
 		g.Expect(env.Create(ctx, machine)).To(Succeed())
 
 		modifiedMachine := machine.DeepCopy()
 		// Set NodeRef.
 		machine.Status.NodeRef = &corev1.ObjectReference{Kind: "Node", Name: node.Name}
-		// Set the LastUpdated to be able to verify it is updated when the phase changes
-		lastUpdated := metav1.NewTime(time.Now().Add(-10 * time.Second))
-		machine.Status.LastUpdated = &lastUpdated
```
Comment (sbueringer) [inline internal/controllers/machine/machine_controller_phases_test.go:291]: Please check if we can also get rid of the other two occurences of this logic

Comment (chrischdi) [reply internal/controllers/machine/machine_controller_phases_test.go:291]: Done :-)

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by killianmuldoon** [comment]
Flake doesn't seem to occur on 1.3 - introduced by changing this test to envtest instead of the fakeclient IMO, so no need to cherry pick to that branch.
