### PR TITLE
:sparkles: e2e Test: Ensure OwnerRefs are consistently reconciled

### LINKED ISSUE #7575: Ensure owner references are correctly re-reconciled
The test in #https://github.com/kubernetes-sigs/cluster-api/pull/7569 shows that some of the ownerReferences in Cluster API are not correctly re-reconciled if they are removed for any reason. This is an umbrella issue to capture the different cases under which this can happen.

The expectation is that the ownerReference tree should look the same as on cluster creation after being re-reconciled. The following differences can be seen in #7569

1. KCP machines and standalone MachineSets can be wrongly adopted by the Cluster on re-reconcile 
    -  #7591 
3. Secret ownerReferences are not re-rereconciled correctly #6979 
    -  #7587 
    - additional bug fix in https://github.com/kubernetes-sigs/cluster-api/pull/7623
    - #7592 
4. ClusterResourceSet configmap references are not re-reconciled
   - https://github.com/kubernetes-sigs/cluster-api/pull/7590
5. KubeadmConfig and DockerMachines created by a MachineSet are initially created with two OwnerReferences: 1 for the Machine it's linked to and a second for the higher level controlling type or MachineSet.
    - #7593
7. ~~ClusterClass-owned templates are not re-reconciled with their ownerReferences~~ (There is an issue here where the ClusterClass is reconciled infrequently so it takes longer for these references to be re-reconciled. The ownerReference tree is evenually as expected in this case though, as the ClusterClass controller reconciles these references correctly.)
## ClusterClass clusters 
The ownerReference tree on creation:
owner-references-c28fk6-before

The ownerReference tree after removing and re-reconciling:
owner-references-c28fk6-after

## Non-ClusterClass clusters
The ownerReference tree on 
owner-references-mmgybv-before
creation:

The ownerReference tree after removing and re-reconciling
owner-references-mmgybv-after

/kind bug

### PR DESCRIPTION
**Pull request by killianmuldoon**
Add a new e2e test and set of helper functions to test that ownerReferences are correctly reconciled by Cluster API.

This test is designed to capture how Cluster API creates ownerReferences with a newly created Topology based Cluster using KCP + KubeadmBooststrap + Docker infrastructure.

It also tests how ownerReferences are reconciled after they've been removed and re-reconciled.

Fixes #7575

### CODE REVIEW

**Comment by killianmuldoon** [comment]
/hold

This currently contains all of the commits required to make the test pass. Let's merge it once it's green against main.

File: cmd/clusterctl/client/cluster/ownergraph.go [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+		ref.BlockOwnerDeletion = attributes.BlockOwnerDeletion
+	}
+	if attributes.Controller != nil {
+		ref.Controller = attributes.Controller
+	}
+	return ref
+}
+
+// GetOwnerGraph returns a data structure with each CAPI controlled object and its OwnerReferences.
+func GetOwnerGraph(namespace string) (OwnerGraph, error) {
```
Comment (killianmuldoon) [inline cmd/clusterctl/client/cluster/ownergraph.go:51]: I think it might be better to restructure this function so it's in the test package, even if that means a little bit of copy-past from clusterctl - opinions?

**Comment by fabriziopandini** [comment]
@killianmuldoon can we remove hold from this one?

File: test/framework/ownerreference_helpers.go [hunk 2]
```diff
@@ -0,0 +1,308 @@
...
+	machineDeploymentGVK = clusterv1.GroupVersion.WithKind(machineDeploymentKind)
+	machineSetGVK        = clusterv1.GroupVersion.WithKind(machineSetKind)
+	machineGVK           = clusterv1.GroupVersion.WithKind(machineKind)
+)
+
+// CoreTypeOwnerReferenceAssertion maps Cluster API core types to functions which return an error if the passed
+// OwnerReferences aren't as expected.
+var CoreTypeOwnerReferenceAssertion = map[string]func([]metav1.OwnerReference) error{
+	clusterClassKind: func(owners []metav1.OwnerReference) error {
+		return hasExactOwnersByGVK(owners, []schema.GroupVersionKind{})
```
Comment (fabriziopandini) [inline test/framework/ownerreference_helpers.go:112]:
```suggestion
                 // ClusterClass doesn't have ownerReferences (it is a clusterctl move-hierarchy root).
		return hasExactOwnersByGVK(owners, []schema.GroupVersionKind{})
```

File: test/framework/ownerreference_helpers.go [hunk 3]
```diff
@@ -0,0 +1,308 @@
...
+	},
+	clusterKind: func(owners []metav1.OwnerReference) error {
+		return hasExactOwnersByGVK(owners, []schema.GroupVersionKind{})
```
Comment (fabriziopandini) [inline test/framework/ownerreference_helpers.go:115]:
```suggestion
                 // Cluster doesn't have ownerReferences (it is a clusterctl move-hierarchy root).
		return hasExactOwnersByGVK(owners, []schema.GroupVersionKind{})
```

File: test/framework/ownerreference_helpers.go [hunk 4]
```diff
@@ -0,0 +1,308 @@
...
+	},
+	machineDeploymentKind: func(owners []metav1.OwnerReference) error {
+		return hasExactOwnersByGVK(owners, []schema.GroupVersionKind{clusterGVK})
```
Comment (fabriziopandini) [inline test/framework/ownerreference_helpers.go:118]:
```suggestion
                 // Machine deployments must be owned by the Cluster.
		return hasExactOwnersByGVK(owners, []schema.GroupVersionKind{clusterGVK})
```

and so on for the other kinds.

File: test/framework/ownerreference_helpers.go [hunk 5]
```diff
@@ -0,0 +1,308 @@
...
+	},
+	machineSetKind: func(owners []metav1.OwnerReference) error {
+		return hasExactOwnersByGVK(owners, []schema.GroupVersionKind{machineDeploymentGVK})
+	},
+	machineKind: func(owners []metav1.OwnerReference) error {
+		return hasOneOfExactOwnersByGVK(owners, []schema.GroupVersionKind{machineSetGVK}, []schema.GroupVersionKind{kubeadmControlPlaneGVK})
```
Comment (fabriziopandini) [inline test/framework/ownerreference_helpers.go:124]: Let's document why we are using hasOneOfExactOwnersByGVK or most specifically let's document in which case we have one owner ref, in which case the other.
Same for the other kinds

File: test/framework/ownerreference_helpers.go [hunk 6]
```diff
@@ -0,0 +1,308 @@
...
+
+func setClusterPause(ctx context.Context, cli client.Client, clusterKey types.NamespacedName, value bool) {
+	cluster := &clusterv1.Cluster{}
+	Expect(cli.Get(ctx, clusterKey, cluster)).To(Succeed())
+
+	unpausePatch := client.RawPatch(types.MergePatchType, []byte(fmt.Sprintf("{\"spec\":{\"paused\":%v}}", value)))
+	Expect(cli.Patch(ctx, cluster, unpausePatch)).To(Succeed())
+}
+
+func annotateClusterClass(ctx context.Context, cli client.Client, clusterKey types.NamespacedName) {
```
Comment (fabriziopandini) [inline test/framework/ownerreference_helpers.go:279]:
```suggestion
func forceClusterClassReconcile(ctx context.Context, cli client.Client, clusterKey types.NamespacedName) {
```
or
triggerClusterClassReconcile

File: test/framework/ownerreference_helpers.go [hunk 7]
```diff
@@ -0,0 +1,308 @@
...
+	sort.SliceStable(wantGVKs, func(i int, j int) bool {
+		return wantGVKs[i].String() > wantGVKs[j].String()
+	})
+	if !reflect.DeepEqual(wantGVKs, refGVKs) {
+		return fmt.Errorf("wanted %v, actual %v", wantGVKs, refGVKs)
+	}
+	return nil
+}
+
+func hasOneOfExactOwnersByGVK(refList []metav1.OwnerReference, possibleGVKS ...[]schema.GroupVersionKind) error {
```
Comment (fabriziopandini) [inline test/framework/ownerreference_helpers.go:250]:
```suggestion
// NOTE: we are using hasOneOfExactOwnersByGVK as a convenience approach for checking owner references on objects that
// can have different owner references depending on the cluster topology.
// In a follow-up iteration we can make improvements to check owner References according to the specific use cases vs checking generically "oneOf".
func hasOneOfExactOwnersByGVK(refList []metav1.OwnerReference, possibleGVKS ...[]schema.GroupVersionKind) error {
```

**Review by fabriziopandini — COMMENTED** [review]
looking forward to get this merged.
just nits from my side about naming and about adding more comments for keeping proper track of the extensive research work behind this PR (kudos to @killianmuldoon for this!)

**Comment by sbueringer** [comment]
I'll review once @fabriziopandini's findings are adressed

File: cmd/clusterctl/client/cluster/ownergraph.go [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+	if attributes.BlockOwnerDeletion != nil {
+		ref.BlockOwnerDeletion = attributes.BlockOwnerDeletion
+	}
+	if attributes.Controller != nil {
+		ref.Controller = attributes.Controller
+	}
+	return ref
+}
+
+// GetOwnerGraph returns a data structure with each CAPI controlled object and its OwnerReferences.
```
[the remark this answers is not in the document]
Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/ownergraph.go:51]: Please add at least the note about the intended usage of this public method, so we provide a clear guidance on what consumer should expect or request as future improvements of this API

**Comment by fabriziopandini** [comment]
great work!
only one last note about being really specific about the target use case of GetOwnerGraph, otherwise lgtm

File: cmd/clusterctl/client/cluster/ownergraph.go [hunk 9]
```diff
@@ -0,0 +1,81 @@
+/*
+Copyright 2020 The Kubernetes Authors.
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/ownergraph.go:2]:
```suggestion
Copyright 2023 The Kubernetes Authors.
```
nit

File: cmd/clusterctl/client/cluster/ownergraph.go [hunk 10]
```diff
@@ -0,0 +1,81 @@
...
+	if attributes.Controller != nil {
+		ref.Controller = attributes.Controller
+	}
+	return ref
+}
+
+// GetOwnerGraph returns a graph with all the objects considered by clusterctl move as nodes and the OwnerReference relationship between those objects as edges.
+// NOTE: this data structure is exposed to allow implementation of E2E tests verifying that CAPI can properly rebuild its
+// own owner references; there is no guarantee about the stability of this API.
+func GetOwnerGraph(namespace, kubeconfigPath string) (OwnerGraph, error) {
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/ownergraph.go:54]:
```suggestion
func GetOwnerGraph(namespace, kubeconfigPath string) (*OwnerGraph, error) {
```
nit: up to you - maybe easier to handle (and I guess a lot less copying around of data)

File: test/framework/ownerreference_helpers.go [hunk 11]
```diff
@@ -0,0 +1,335 @@
...
+func AssertOwnerReferences(namespace, kubeconfigPath string, assertFuncs ...map[string]func(reference []metav1.OwnerReference) error) {
+	allAssertFuncs := map[string]func(reference []metav1.OwnerReference) error{}
+	for _, m := range assertFuncs {
+		for k, v := range m {
+			allAssertFuncs[k] = v
+		}
+	}
+	Eventually(func() error {
+		graph, err := clusterctlcluster.GetOwnerGraph(namespace, kubeconfigPath)
+		Expect(err).To(BeNil())
```
Comment (sbueringer) [inline test/framework/ownerreference_helpers.go:78]: I assume we intentionally want to fail here if we get an error once? (and not retry with eventually)

File: test/framework/ownerreference_helpers.go [hunk 12]
```diff
@@ -0,0 +1,335 @@
...
+				continue
+			}
+			if err := allAssertFuncs[v.Object.Kind](v.Owners); err != nil {
+				allErrs = append(allErrs, errors.Wrapf(err, "Unexpected ownerReferences for %s/%s", v.Object.Kind, v.Object.Name))
+			}
+		}
+		var errStrings string
+		for _, err := range allErrs {
+			errStrings = fmt.Sprintf("%s\n%s", errStrings, err.Error())
+		}
```
Comment (sbueringer) [inline test/framework/ownerreference_helpers.go:92]: As far as I can tell this is unused

File: test/framework/ownerreference_helpers.go [hunk 13]
```diff
@@ -0,0 +1,335 @@
...
+	kubeadmConfigTemplateKind = "KubeadmConfigTemplate"
+
+	kubeadmConfigGVK = bootstrapv1.GroupVersion.WithKind(kubeadmConfigKind)
+)
+
+// KubeadmBootstrapOwnerReferenceAssertions maps KubeadmBootstrap types to functions which return an error if the passed OwnerReferences
+// aren't as expected.
+var KubeadmBootstrapOwnerReferenceAssertions = map[string]func([]metav1.OwnerReference) error{
+	kubeadmConfigKind: func(owners []metav1.OwnerReference) error {
+		// The KubeadmControlPlane must be owned by a Cluster.
```
Comment (sbueringer) [inline test/framework/ownerreference_helpers.go:214]:
```suggestion
		// The KubeadmConfig must be owned by a Cluster.
```
similar in l.218

File: test/framework/ownerreference_helpers.go [hunk 14]
```diff
@@ -0,0 +1,335 @@
...
+		return schema.GroupVersionKind{}, err
+	}
+	return schema.GroupVersionKind{Version: refGV.Version, Group: refGV.Group, Kind: ref.Kind}, nil
+}
+
+func setClusterPause(ctx context.Context, cli client.Client, clusterKey types.NamespacedName, value bool) {
+	cluster := &clusterv1.Cluster{}
+	Expect(cli.Get(ctx, clusterKey, cluster)).To(Succeed())
+
+	unpausePatch := client.RawPatch(types.MergePatchType, []byte(fmt.Sprintf("{\"spec\":{\"paused\":%v}}", value)))
```
Comment (sbueringer) [inline test/framework/ownerreference_helpers.go:302]:
```suggestion
	pausePatch := client.RawPatch(types.MergePatchType, []byte(fmt.Sprintf("{\"spec\":{\"paused\":%v}}", value)))
```
nit: maybe. It's not really always unpause, pause sounds a bit more generic

File: test/framework/ownerreference_helpers.go [hunk 15]
```diff
@@ -0,0 +1,335 @@
...
+	Expect(cli.Patch(ctx, cluster, unpausePatch)).To(Succeed())
+}
+
+func forceClusterClassReconcile(ctx context.Context, cli client.Client, clusterKey types.NamespacedName) {
```
Comment (sbueringer) [inline test/framework/ownerreference_helpers.go:306]: Q: Wouldn't it make also sense to do something for the non-ClusterClass case and thus just have one implementation modifying the cluster?

Or do we only have a delay in the ClusterClass case because of the way watches are set up?

Depending on answers, would be good to have a short comment

File: test/framework/ownerreference_helpers.go [hunk 16]
```diff
@@ -0,0 +1,335 @@
...
+		Expect(cli.Patch(ctx, class, annotationPatch)).To(Succeed())
+	}
+}
+
+func removeOwnerReferences(ctx context.Context, proxy ClusterProxy, namespace string) {
+	graph, err := clusterctlcluster.GetOwnerGraph(namespace, proxy.GetKubeconfigPath())
+	Expect(err).To(BeNil())
+	for _, object := range graph {
+		ref := object.Object
+		// Once all Clusters are paused remove the OwnerReference from all objects in the graph.
```
Comment (sbueringer) [inline test/framework/ownerreference_helpers.go:323]: nit: I think this comment better fits in l. 58

Otherwise we describe inside of this func how it is used by the parent func. (which is a bit confusing to me as we don't pause anything in this func / or we also don't wait for something to be paused)

**Review by sbueringer — COMMENTED** [review]
Very nice work!!

File: cmd/clusterctl/client/cluster/ownergraph.go (hunk 9 above)
Comment (sbueringer) [reply cmd/clusterctl/client/cluster/ownergraph.go:2]: Same in test/framework/ownerreference_helpers.go

File: test/e2e/quick_start_test.go [hunk 17]
```diff
@@ -75,3 +77,48 @@ var _ = Describe("When following the Cluster API quick-start with Ignition", fun
 		}
 	})
 })
+
+var _ = Describe("When following the Cluster API quick-start check owner references are correctly reconciled and rereconciled if deleted", func() {
```
Comment (sbueringer) [inline test/e2e/quick_start_test.go:81]: What about integrating the new validation in the existing tests we already have?
(similar for the next test)

Comment (killianmuldoon) [reply test/e2e/quick_start_test.go:81]: I was thinking about letting them run in the CI / periodic for a while to understand the tests better and then following up on this - WDYT?

Comment (sbueringer) [reply test/e2e/quick_start_test.go:81]: Sounds very reasonable, please just track it in an issue.

I really try to keep the number of tests down, but given that quickstart runs on every PR it makes a lot of sense to check for stability in the periodics

File: test/framework/ownerreference_helpers.go (hunk 11 above)
Comment (killianmuldoon) [reply test/framework/ownerreference_helpers.go:78]: Yeah - actually this is running retries within the func so this is unnecessary.

File: test/framework/ownerreference_helpers.go (hunk 12 above)
Comment (killianmuldoon) [reply test/framework/ownerreference_helpers.go]: Used now.

File: cmd/clusterctl/client/cluster/ownergraph.go (hunk 10 above)
Comment (killianmuldoon) [reply cmd/clusterctl/client/cluster/ownergraph.go:54]: I don't think it would make it easier to handle really, and given this is a test func I think it's alright as is. No strong feelings though if you want to change it.

File: test/framework/ownerreference_helpers.go (hunk 15 above)
Comment (killianmuldoon) [reply test/framework/ownerreference_helpers.go:306]: Yeah - this is down to the way ClusterClass ownerReferences for templates are re-reconciled. CC controller doesn't watch the templates, so it's down to the sync period here.

File: cmd/clusterctl/client/cluster/ownergraph.go (hunk 10 above)
Comment (sbueringer) [reply cmd/clusterctl/client/cluster/ownergraph.go:54]: No, up to you, all good :0

**Comment by sbueringer** [comment]
Thx!

/lgtm
/pull-cluster-api-e2e-full-main 
(a final one after the last changes)

File: test/framework/ownerreference_helpers.go (hunk 11 above)
Comment (killianmuldoon) [reply test/framework/ownerreference_helpers.go:81]: Looks like the test is flaky if Eventually isn't included because of different order / speed of the reconcilers.

**Comment by sbueringer** [comment]
@killianmuldoon Maybe dropping the eventually is causing the errors?

**Comment by killianmuldoon** [comment]
Yup - https://github.com/kubernetes-sigs/cluster-api/pull/7606#discussion_r1082653541

Re-running with Eventually added back in now.

**Comment by killianmuldoon** [comment]
@sbueringer all green :slightly_smiling_face:

**Comment by sbueringer** [comment]
Perfect! Thx

/lgtm
/approve

**Comment by fabriziopandini** [comment]
/lgtm
/approve

Yay! 🥳
