### PR TITLE
🐛 Wait for all descendants when deleting a cluster

### LINKED ISSUE #1643: machine remains undeleted while cluster has been deleted
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
-  create a cluster, and create machines use machineset, everything goes ok.
-  delete the cluster 
-  find out that still remains machine in deleting state, the log says ”can not find cluster <clusterName>“ from [machine controller](https://github.com/kubernetes-sigs/cluster-api/blob/bad33a82c9ea5fbef94216103bac48515beea32b/controllers/machine_controller.go#L124)

**What did you expect to happen:**
all resources under the cluster be deleted successfully

**Anything else you would like to add:**
the root cause of this bug is that cluster controller try to [delete it's child in background](https://github.com/kubernetes-sigs/cluster-api/blob/bad33a82c9ea5fbef94216103bac48515beea32b/controllers/cluster_controller.go#L172) (in this case, only the machinSet, machines are the child of the machineSet) and list it's child 5 seconds later, if not exist anymore, cluster controller will proceed to delete it infra resource. on the other way, the machineSet controllers uses the kubernetes garbage collector to delete the machine resources, if we delete the machineset in `Background`
 propagationPolicy , the machineset resource will be deleted immediately. so the next time cluster controller list it's children, the machineset will not be found any more. but the machine deleting in background may still be processed by the machine controller, and need get the cluster obj in it's reconcile func, thus the finalizer will not be successfully removed.

**Solutions**
i try the `Foreground ` propagationPolicy and this case solved, but i'm not sure if it is a proper solution.

**Notes**
Here is a Column describes the resources's ownerRef and finalizer in cluster-api and it's provider

  | ownerRef Name | ownerRef Set By | Finalizer Name | Finalizer Set By
-- | -- | -- | -- | --
cluster | / | / | cluster.cluster.x-k8s.io | cluster-controller
infra cluster | cluster | cluster-controller | self-defined-infra-cluster-finalizer | clusterinfra-controller
machineDeployment | cluster | machineDeployment controller | / | /
machineSet(create alone) | cluster | machineSet controller | / | /
machineSet(create by machine deployment)) | machineDeployment | machineDeployment controller | / | /
machine(create alone) | cluster | machine controller | machine.cluster.x-k8s.io | machine-controller
machine(create by machineset) | machineSet | machineSet controller
machine infra | machine | machine controller | self-defined-infra-machine-finalizer | machineinfra-controller
bootstrap | machine | machine controller |   |

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:

Instead of waiting for all direct descendants to be deleted and then
allowing cluster deletion to proceed (by removing the finalizer), wait
for all descendants (both direct and indirect) to be removed before
allowing cluster deletion to proceed. There can be race conditions where
there are indirect descendants (machines belonging to a machine set)
that still exist, and they need the cluster to remain so they can be
deleted properly.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1643 

Alternative to #1644

### CODE REVIEW

**Comment by ncdc** [comment]
If y'all are 👍 on this, I'll see about adding some unit tests

File: controllers/cluster_controller.go [hunk 1]
```diff
@@ -231,30 +239,46 @@ func (r *ClusterReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
+	machines           clusterv1.MachineList
+}
+
+// empty returns true if all the lists are empty.
+func (c *clusterDescendants) empty() bool {
+	return len(c.machineDeployments.Items) == 0 && len(c.machineSets.Items) == 0 && len(c.machines.Items) == 0
+}
+
+// listAllClusterDescendants returns a list of all MachineDeployments, MachineSets, and Machines for the cluster.
+func (r *ClusterReconciler) listAllClusterDescendants(ctx context.Context, cluster *clusterv1.Cluster) (clusterDescendants, error) {
```
Comment (vincepri) [inline controllers/cluster_controller.go]:
```suggestion
func (r *ClusterReconciler) listDescendants(ctx context.Context, cluster *clusterv1.Cluster) (clusterDescendants, error) {
```

Given that this is the cluster reconciler, `cluster` can probably be omitted from the name

File: controllers/cluster_controller.go [hunk 2]
```diff
@@ -231,30 +239,46 @@ func (r *ClusterReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
-		return nil, errors.Wrapf(err, "failed to list Machines for cluster %s/%s", cluster.Namespace, cluster.Name)
+	if err := r.Client.List(ctx, &descendants.machines, listOptions...); err != nil {
+		return descendants, errors.Wrapf(err, "failed to list Machines for cluster %s/%s", cluster.Namespace, cluster.Name)
 	}
-	controlPlaneMachines, machines := splitMachineList(allMachines)
+
+	return descendants, nil
+}
+
+func (r *ClusterReconciler) extractDirectClusterDescendants(input clusterDescendants, cluster *clusterv1.Cluster) ([]runtime.Object, error) {
```
Comment (vincepri) [inline controllers/cluster_controller.go]:
```suggestion
func (r *ClusterReconciler) filterOwnedDescendants(input clusterDescendants, cluster *clusterv1.Cluster) ([]runtime.Object, error) {
```

?

Comment (vincepri) [reply controllers/cluster_controller.go]: Let's also add a godoc for this method

File: controllers/cluster_controller.go [hunk 3]
```diff
@@ -231,30 +239,46 @@ func (r *ClusterReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
+	logger := r.Log.WithValues("cluster", cluster.Name, "namespace", cluster.Namespace)
+
+	// Split machines into control plane and worker machines so we make sure we delete control plane machines last
+	controlPlaneMachines, machines := splitMachineList(&input.machines)
 
 	var children []runtime.Object
```
Comment (vincepri) [inline controllers/cluster_controller.go]:
```suggestion
	var ownedDescendants []runtime.Object
```

**Comment by ncdc** [comment]
WDYT of the overall approach? @detiber @liztio @vincepri @xrmzju?

File: controllers/cluster_controller.go (hunk 2 above)
Comment (detiber) [reply controllers/cluster_controller.go]: Should this be a method on clusterDescendants?

**Comment by vincepri** [comment]
I'm +1, seems pretty straightforward, the review I did is mostly nits. The logic looks good

File: controllers/cluster_controller.go [hunk 4]
```diff
@@ -231,30 +239,46 @@ func (r *ClusterReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
-	controlPlaneMachines, machines := splitMachineList(allMachines)
+
+	return descendants, nil
+}
+
+func (r *ClusterReconciler) extractDirectClusterDescendants(input clusterDescendants, cluster *clusterv1.Cluster) ([]runtime.Object, error) {
+	logger := r.Log.WithValues("cluster", cluster.Name, "namespace", cluster.Namespace)
+
+	// Split machines into control plane and worker machines so we make sure we delete control plane machines last
+	controlPlaneMachines, machines := splitMachineList(&input.machines)
```
Comment (detiber) [inline controllers/cluster_controller.go]: Maybe split these within clusterDescendants as well instead of here?

File: controllers/cluster_controller.go (hunk 2 above)
Comment (vincepri) [reply controllers/cluster_controller.go]: probably yeah

File: controllers/cluster_controller.go [hunk 5]
```diff
@@ -231,30 +239,46 @@ func (r *ClusterReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
+	if err := r.Client.List(ctx, &descendants.machines, listOptions...); err != nil {
+		return descendants, errors.Wrapf(err, "failed to list Machines for cluster %s/%s", cluster.Namespace, cluster.Name)
 	}
-	controlPlaneMachines, machines := splitMachineList(allMachines)
+
+	return descendants, nil
+}
+
+func (r *ClusterReconciler) extractDirectClusterDescendants(input clusterDescendants, cluster *clusterv1.Cluster) ([]runtime.Object, error) {
+	logger := r.Log.WithValues("cluster", cluster.Name, "namespace", cluster.Namespace)
```
Comment (ncdc) [inline controllers/cluster_controller.go]: How much do y'all care about logging an error if we couldn't create the `meta.Accessor`?

File: controllers/cluster_controller.go [hunk 6]
```diff
@@ -231,30 +239,46 @@ func (r *ClusterReconciler) reconcileDelete(ctx context.Context, cluster *cluste
 	return ctrl.Result{}, nil
 }
 
-// listChildren returns a list of MachineDeployments, MachineSets, and Machines than have an owner reference to cluster
-func (r *ClusterReconciler) listChildren(ctx context.Context, cluster *clusterv1.Cluster) ([]runtime.Object, error) {
-	logger := r.Log.WithValues("cluster", cluster.Name, "namespace", cluster.Namespace)
+type clusterDescendants struct {
+	machineDeployments clusterv1.MachineDeploymentList
```
Comment (ncdc) [inline controllers/cluster_controller.go]: Should these lists be pointers or is it ok for them not to be?

File: controllers/cluster_controller.go (hunk 5 above)
Comment (vincepri) [reply controllers/cluster_controller.go]: I'm fine removing it

File: controllers/cluster_controller.go (hunk 6 above)
Comment (vincepri) [reply controllers/cluster_controller.go]: They don't have to be afaict

File: controllers/cluster_controller.go [hunk 7]
```diff
@@ -231,59 +239,81 @@ func (r *ClusterReconciler) reconcileDelete(ctx context.Context, cluster *cluste
...
-func (r *ClusterReconciler) listChildren(ctx context.Context, cluster *clusterv1.Cluster) ([]runtime.Object, error) {
-	logger := r.Log.WithValues("cluster", cluster.Name, "namespace", cluster.Namespace)
+type clusterDescendants struct {
+	machineDeployments   clusterv1.MachineDeploymentList
+	machineSets          clusterv1.MachineSetList
+	controlPlaneMachines clusterv1.MachineList
+	workerMachines       clusterv1.MachineList
+}
+
+// isEmpty returns true if all the lists are isEmpty.
```
Comment (vincepri) [inline controllers/cluster_controller.go]:
```suggestion
// isEmpty returns true if all the lists are empty.
```

Comment (ncdc) [reply controllers/cluster_controller.go]: Thanks, my find and replace was too aggressive.

**Comment by ncdc** [comment]
/hold

Would like @xrmzju to review

File: controllers/cluster_controller.go [hunk 8]
```diff
@@ -199,8 +205,10 @@ func (r *ClusterReconciler) reconcileDelete(ctx context.Context, cluster *cluste
 		if len(errs) > 0 {
 			return ctrl.Result{}, kerrors.NewAggregate(errs)
 		}
+	}
 
-		// Requeue so we can check the next time to see if there are still any children left.
+	if !descendants.isEmpty() {
```
Comment (xrmzju) [inline controllers/cluster_controller.go]: should we log here to find out which descendant has not been deleted yet?

**Comment by xrmzju** [comment]
LGTM expect a little log suggestion

File: controllers/cluster_controller.go (hunk 8 above)
Comment (ncdc) [reply controllers/cluster_controller.go]: I added some logging - PTAL!

**Comment by ncdc** [comment]
If this looks ok, I will squash. @vincepri

**Comment by vincepri** [comment]
go for it, lgtm
