### PR TITLE
:bug: add finalizer to kcp in first reconcile to avoid race condition with delete

### LINKED ISSUE #3198: KCP deleted without deleting the CP Machine
When cluster delete happens before KCP controller able to add finalizer, the KCP object is deleted without deleting the CP Machine.

Seen this with capz. what happened is, the first time when kcp reconcile doing init, before the finalizer is added, it's trying to get remote cluster status before calling patchHelper, but since first CP node is not up yet, the call to remote cluster stuck and timeout after 30 seconds. 

During this 30 seconds, when delete cluster request come, kcp object does not have finalizer yet, so it was deleted without waiting for CP Machine to be deleted. Then the Cluster object is also deleted and CP machine object left behind not cleaned up. 

So either we patch finalizer first before getting remote cluster status, or we use foregroundDelete to delete kcp, because the machine have ownerref set correctly, so even without finalizer the kcp object should still be available. 

Let me know what do you guys think. I can have a fix. @vincepri  

**What did you expect to happen:**

**Anything else you would like to add:**
kcp log:
```
I0612 06:12:59.113011       1 controller.go:192] controllers/KubeadmControlPlane "msg"="Reconcile KubeadmControlPlane" "cluster"="xgr52" "kubeadmControlPlane"="xgr52-cp" "namespace"="cluster-5ee31604cb45680ec615dd0b" 
I0612 06:13:05.351425       1 controller.go:250] controllers/KubeadmControlPlane "msg"="Initializing control plane" "cluster"="xgr52" "kubeadmControlPlane"="xgr52-cp" "namespace"="cluster-5ee31604cb45680ec615dd0b" "Desired"=1 "Existing"=0
E0612 06:13:35.634203       1 controller.go:160] controllers/KubeadmControlPlane "msg"="Failed to update KubeadmControlPlane Status" "error"="failed to create remote cluster client: failed to create client for workload cluster cluster-5ee31604cb45680ec615dd0b/xgr52: Get https://xgr52-7dbad68a.centralus.cloudapp.azure.com:6443/api?timeout=30s: dial tcp 52.154.155.142:6443: i/o timeout" "cluster"="xgr52" "kubeadmControlPlane"="xgr52-cp" "namespace"="cluster-5ee31604cb45680ec615dd0b" 
E0612 06:13:35.813173       1 controller.go:166] controllers/KubeadmControlPlane "msg"="Failed to patch KubeadmControlPlane" "error"="kubeadmcontrolplanes.controlplane.cluster.x-k8s.io \"xgr52-cp\" not found" "cluster"="xgr52" "kubeadmControlPlane"="xgr52-cp" "namespace"="cluster-5ee31604cb45680ec615dd0b" 
E0612 06:13:35.813562       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="[failed to create remote cluster client: failed to create client for workload cluster cluster-5ee31604cb45680ec615dd0b/xgr52: Get https://xgr52-7dbad68a.centralus.cloudapp.azure.com:6443/api?timeout=30s: dial tcp 52.154.155.142:6443: i/o timeout, kubeadmcontrolplanes.controlplane.cluster.x-k8s.io \"xgr52-cp\" not found]"  "controller"="kubeadmcontrolplane" "request"={"Namespace":"cluster-5ee31604cb45680ec615dd0b","Name":"xgr52-cp"}
```

capi log:
```
E0612 06:13:07.862684       1 machine_controller.go:226] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="Infrastructure provider for Machine \"xgr52-cp-httdv\" in namespace \"cluster-5ee31604cb45680ec615dd0b\" is not ready, requeuing: requeue in 30s" "cluster"="xgr52" "machine"="xgr52-cp-httdv" "namespace"="cluster-5ee31604cb45680ec615dd0b" 
I0612 06:13:12.262613       1 cluster_controller.go:282] controllers/Cluster "msg"="Cluster still has descendants - need to requeue" "cluster"="xgr52" "namespace"="cluster-5ee31604cb45680ec615dd0b" "controlPlaneRef"="xgr52-cp"
I0612 06:13:12.949862       1 machine_controller.go:263] controllers/Machine "msg"="Deleting Kubernetes Node associated with Machine is not allowed" "cluster"="xgr52" "machine"="xgr52-cp-httdv" "namespace"="cluster-5ee31604cb45680ec615dd0b" "cause"={} "node"=null
I0612 06:13:13.296689       1 cluster_controller.go:306] controllers/Cluster "msg"="Cluster still has descendants - need to requeue" "cluster"="xgr52" "namespace"="cluster-5ee31604cb45680ec615dd0b" "infrastructureRef"="xgr52"
I0612 06:13:13.564824       1 cluster_controller.go:306] controllers/Cluster "msg"="Cluster still has descendants - need to requeue" "cluster"="xgr52" "namespace"="cluster-5ee31604cb45680ec615dd0b" "infrastructureRef"="xgr52"
I0612 06:13:13.655777       1 machine_controller.go:263] controllers/Machine "msg"="Deleting Kubernetes Node associated with Machine is not allowed" "cluster"="xgr52" "machine"="xgr52-cp-httdv" "namespace"="cluster-5ee31604cb45680ec615dd0b" "cause"={} "node"=null
.....
I0612 06:16:49.643898       1 machine_controller.go:263] controllers/Machine "msg"="Deleting Kubernetes Node associated with Machine is not allowed" "cluster"="xgr52" "machine"="xgr52-cp-httdv" "namespace"="cluster-5ee31604cb45680ec615dd0b" "cause"={} "node"=null
E0612 06:17:30.564624       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to get cluster \"xgr52\" for machine \"xgr52-cp-httdv\" in namespace \"cluster-5ee31604cb45680ec615dd0b\": Cluster.cluster.x-k8s.io \"xgr52\" not found"  "controller"="machine" "request"={"Namespace":"cluster-5ee31604cb45680ec615dd0b","Name":"xgr52-cp-httdv"}
```

**Environment:**

- Cluster-api version: 0.3.6
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by jzhoucliqr**
This fix add finalizer to kcp and force requeue for the first reconciliation, before kcp init,  to avoid race condition between kcp init and kcp delete. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #3198

### CODE REVIEW

File: controlplane/kubeadm/controllers/controller.go [hunk 1]
```diff
@@ -153,6 +153,18 @@ func (r *KubeadmControlPlaneReconciler) Reconcile(req ctrl.Request) (res ctrl.Re
...
+	// Add finalizer first if not exist to avoid the race condition between init and delete
+	if !util.FinalizerExists(kcp, controlplanev1.KubeadmControlPlaneFinalizer) {
+		controllerutil.AddFinalizer(kcp, controlplanev1.KubeadmControlPlaneFinalizer)
+
+		if err := patchHelper.Patch(ctx, kcp); err != nil {
+			logger.Error(err, "Failed to patch KubeadmControlPlane to add finalizer")
+			return ctrl.Result{}, err
+		}
+
+		return ctrl.Result{RequeueAfter: 1 * time.Second}, nil
```
Comment (vincepri) [inline controlplane/kubeadm/controllers/controller.go:165]:
```suggestion
		return ctrl.Result{Requeue: true}, nil
```

**Comment by vincepri** [comment]
We should probably remove https://github.com/kubernetes-sigs/cluster-api/pull/3199/files#diff-b9435e3ca04d94ed2d00d8754ddae768R218 now that we're setting the finalizer here

File: util/util.go [hunk 2]
```diff
@@ -644,3 +644,14 @@ func ManagerDelegatingClientFunc(cache cache.Cache, config *rest.Config, options
...
+// FinalizerExists check if the given finalizer exists in the object o
+func FinalizerExists(o metav1.Object, finalizer string) bool {
+	f := o.GetFinalizers()
+	for _, e := range f {
+		if e == finalizer {
+			return true
+		}
+	}
+	return false
+}
```
Comment (detiber) [inline util/util.go:657]: I really wish we could leverage `controllerutil.ContainsFinalizer` here rather than having to add a helper for this here. @vincepri is it worth backporting https://github.com/kubernetes-sigs/controller-runtime/commit/b999e72d531f70cdf877468514b1bf11a8badfd4#diff-4c146d38c03cf55e321de9ad53af4452 to controller-runtime v0.5.x for that purpose?

Comment (vincepri) [reply util/util.go:657]: We can, I can cut a release today if you're able to backport it to `release-0.5`

Comment (detiber) [reply util/util.go:657]: https://github.com/kubernetes-sigs/controller-runtime/pull/1000

Comment (vincepri) [reply util/util.go:657]: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.5.6

**Comment by fabriziopandini** [comment]
/approve
@vincepri @detiber 
IMO setting finalizers as a first thing is potentially a good design pattern. Should we open an issue to align all the other controllers to this approach?

**Comment by detiber** [comment]
> IMO setting finalizers as a first thing is potentially a good design pattern. Should we open an issue to align all the other controllers to this approach?

+1 from me, surprised there haven't been more complaints about similar race conditions with the other controllers yet :)

**Comment by vincepri** [comment]
Sounds fair, if there is enough repetition everywhere, we should provide a generic utility? It can definitely come later though, no reason to do this in v0.3.7
