### PR TITLE
:bug: Add wait-resource-versions-{become,remain}-stable intervals to e2e config

### LINKED ISSUE #13262: "Check resourceVersions are stable" fails in high-latency environments and can't be tuned.
### What steps did you take and what happened?

CAPZ runs the `ClusterctlUpgradeSpec` to validate upgrades of CAPZ:
https://github.com/kubernetes-sigs/cluster-api/blob/79465fdc269cdc729173135d378cd6045abb1dd6/test/e2e/clusterctl_upgrade.go#L193

Since the check to verify resource versions was added in #12546, CAPZ's tests have been flaking with a mysterious error at the "Check resourceVersions are stable" step as described in https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/6058.

I found out that the test would only fail when the management cluster in the test is running in the `australiaeast` region which is much further away from our Prow cluster running the e2e tests than the other regions where we test.

For clusters in that region, the `Eventually` block that gathers resource versions for the cluster's objects was spending its entire 1-minute budget gathering an initial view of the objects and therefore not even attempting a second look like the test assumes will always happen.
https://github.com/kubernetes-sigs/cluster-api/blob/79465fdc269cdc729173135d378cd6045abb1dd6/test/framework/resourceversion_helpers.go#L41-L42

Even with https://github.com/kubernetes-sigs/cluster-api/pull/12848 ported onto CAPI v1.11.5, I still see this flake in CAPZ.

### What did you expect to happen?

The test is resilient to higher latency or allows the timeouts to be adjusted.

### Cluster API version

v1.11.5

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by nojnhuh**
**What this PR does / why we need it**:

The default wait intervals used during clusterctl upgrade tests to check for the stability of resource versions do not work when there is high latency between the test binary and the management clusters. This PR makes those timeouts configurable via new `wait-resource-versions-become-stable` and `wait-resource-versions-remain-stable` interval configurations.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #13262

/area e2e-testing

### CODE REVIEW

**Comment by nojnhuh** [comment]
I would also like for this to be backported to release-1.11 and release-1.12 if that's appropriate so we can consume this changes from CAPZ where I'm seeing test flakes this should fix.

**Comment by sbueringer** [comment]
/assign

Will take a look soon

File: test/framework/resourceversion_helpers.go [hunk 1]
```diff
@@ -32,12 +31,23 @@ import (
...
+// ValidateResourceVersionStableWaitIntervals holds wait interval configuration
+// for [ValidateResourceVersionStableWaitIntervals].
+type ValidateResourceVersionStableWaitIntervals struct {
+	WaitToBecomeStable []any
+	WaitToRemainStable []any
+}
+
 // ValidateResourceVersionStable checks that resourceVersions are stable.
-func ValidateResourceVersionStable(ctx context.Context, proxy ClusterProxy, namespace string, ownerGraphFilterFunction clusterctlcluster.GetOwnerGraphFilterFunction) {
+func ValidateResourceVersionStable(ctx context.Context, proxy ClusterProxy, namespace string, ownerGraphFilterFunction clusterctlcluster.GetOwnerGraphFilterFunction, intervals ValidateResourceVersionStableWaitIntervals) {
```
Comment (sbueringer) [inline test/framework/resourceversion_helpers.go]: I would prefer if we add one input struct that has one field for each interval (e.g. compare with ApplyClusterTemplateAndWaitInput)

Let's also move all other parameters except ctx to the input struct

File: test/e2e/cluster_upgrade_runtimesdk.go [hunk 2]
```diff
@@ -104,7 +104,7 @@ type ClusterUpgradeWithRuntimeSDKSpecInput struct {
 
 	// Allows injecting a function to be run after the cluster is upgraded.
 	// If not specified, this is a no-op.
-	PostUpgrade func(managementClusterProxy framework.ClusterProxy, workloadClusterNamespace, workloadClusterName string)
+	PostUpgrade func(spec string, managementClusterProxy framework.ClusterProxy, workloadClusterNamespace, workloadClusterName string)
```
Comment (sbueringer) [inline test/e2e/cluster_upgrade_runtimesdk.go]: Can we avoid this breaking change? (to make it less disruptive for a backport)

I think we can just hard-code the spec name in test/e2e/cluster_upgrade_runtimesdk_test.go?

(I realize that the change to ValidateResourceVersionStable is also breaking, but it at least only affects folks using ValidateResourceVersionStable)

File: test/e2e/quick_start.go [hunk 3]
```diff
@@ -92,7 +92,7 @@ type QuickStartSpecInput struct {
 
 	// Allows to inject a function to be run after machines are provisioned.
 	// If not specified, this is a no-op.
-	PostMachinesProvisioned func(managementClusterProxy framework.ClusterProxy, workloadClusterNamespace, workloadClusterName string)
+	PostMachinesProvisioned func(spec string, managementClusterProxy framework.ClusterProxy, workloadClusterNamespace, workloadClusterName string)
```
Comment (sbueringer) [inline test/e2e/quick_start.go]: Same here

File: test/framework/resourceversion_helpers.go (hunk 1 above)
Comment (nojnhuh) [reply test/framework/resourceversion_helpers.go]: Done

File: test/e2e/cluster_upgrade_runtimesdk.go (hunk 2 above)
Comment (nojnhuh) [reply test/e2e/cluster_upgrade_runtimesdk.go]: Yeah that works. I was trying to avoid defining that spec name in two different places but I can see the benefit of keeping this API the same.

**Comment by sbueringer** [comment]
Thank you very much!!

/lgtm
/approve

**Comment by sbueringer** [comment]
Feel free to open a PR for release-1.11

**Comment by nojnhuh** [comment]
> Feel free to open a PR for release-1.11

Done: #13331
