### PR TITLE
🐛  Fix Matchers bug on ignored paths and add tests

### LINKED ISSUE #5563: EqualObject Matcher ignores additional fields
Expected internal/matchers.EqualObject to return false when the compared object has more fields than the original object. Currently if the original object has more fields than the actual the objects are returned as equal. 

This is unexpected behaviour for those using the EqualObject matcher in tests.

Unit tests will be added to the matcher to ensure it's functioning as expected.

/kind bug
/area testing

/cc @sbueringer

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

This PR changes the logic inside the matchers to ensure that any difference in fields between the actual and original object - in either direction - is considered significant for establishing whether the objects are Equal. Previously the matcher did no consider fields in the original object that are not present in the modified object when matching.

This PR also adds unit tests to show the intended usage of the matcher in these, and other cases.

Note: This change significantly modifies the behaviour of the matcher library compared to the mergepatch library used in topology/internal. These changes make #5316 more difficult and less desirable.

Fixes #5563 

/area testing

### CODE REVIEW

**Comment by killianmuldoon** [comment]
@sbueringer Can you let me know if this fixes the issues you encountered?

File: internal/matchers/matchers.go [hunk 1]
```diff
@@ -20,8 +20,11 @@ import (
 	"bytes"
 	"encoding/json"
 	"fmt"
+	"log"
 	"reflect"
 
+	"github.com/davecgh/go-spew/spew"
+
```
Comment (sbueringer) [inline internal/matchers/matchers.go:27]: nit: remove empty line + goimports

File: internal/matchers/matchers.go [hunk 2]
```diff
@@ -126,20 +129,17 @@ func (m *Matcher) calculateDiff(actual interface{}) ([]byte, error) {
...
-	originalWithModifiedJSON, err := jsonpatch.MergePatch(originalJSON, actualJSON)
-	if err != nil {
-		return nil, err
-	}
-	rawDiff, err := jsonpatch.CreateMergePatch(originalJSON, originalWithModifiedJSON)
+	diff, err := jsonpatch.CreateMergePatch(originalJSON, actualJSON)
 	if err != nil {
 		return nil, err
 	}
+	log.Print(spew.Sdump(diff))
```
Comment (sbueringer) [inline internal/matchers/matchers.go:136]: probably leftover from debugging (same in l.142)

File: internal/matchers/matchers.go [hunk 3]
```diff
@@ -126,20 +129,17 @@ func (m *Matcher) calculateDiff(actual interface{}) ([]byte, error) {
...
 
-	// Filter the diff according to the rules attached to the Matcher.
-	diff, err := filterDiff(rawDiff, m.options.allowPaths, m.options.ignorePaths)
+	diff, err = filterDiff(diff, m.options.allowPaths, m.options.ignorePaths)
```
Comment (sbueringer) [inline internal/matchers/matchers.go:138]: nit: Not sure if the comment was deleted intentionally

File: internal/matchers/matchers_test.go [hunk 4]
```diff
@@ -0,0 +1,427 @@
...
+						"generation":      "foo",
+						"managedFields":   "foo",
+					},
+				},
+			},
+			options: []MatchOption{IgnoreAutogeneratedMetadata},
+			want:    true,
+		},
+		{
+			name: "Unequal labels and annotations",
```
Comment (sbueringer) [inline internal/matchers/matchers_test.go:313]: nit: add something about Ignore fields to the name

**Review by sbueringer — COMMENTED** [review]
Thx for the very quick fix!!

Worked on my PR. A few nits, otherwise lgtm

File: internal/matchers/matchers.go (hunk 1 above)
Comment (killianmuldoon) [reply internal/matchers/matchers.go:27]: I'm not sure why but my Goimports on Goland always leaves PRs in this state - I need to get to the bottom of it.

Comment (sbueringer) [reply internal/matchers/matchers.go:27]: The problem I had a while back was that when imports very added automatically when coding (e.g. just using the package) it added them like this. 

Since a while / a few versions that problem is gone (on my machine :))

Comment (sbueringer) [reply internal/matchers/matchers.go:27]: The problem with goimports is that it just doesn't enforce order across blocks. It will split blocks but it will never merge them.

Comment (sbueringer) [reply internal/matchers/matchers.go:27]: I've been tracking this issue for a while: https://github.com/golang/go/issues/20818

File: internal/matchers/matchers.go [hunk 5]
```diff
@@ -126,20 +129,17 @@ func (m *Matcher) calculateDiff(actual interface{}) ([]byte, error) {
 	}
 
 	// Use a mergePatch to produce a diff between the two objects.
-	originalWithModifiedJSON, err := jsonpatch.MergePatch(originalJSON, actualJSON)
-	if err != nil {
-		return nil, err
-	}
-	rawDiff, err := jsonpatch.CreateMergePatch(originalJSON, originalWithModifiedJSON)
```
Comment (fabriziopandini) [inline internal/matchers/matchers.go:133]: Sorry I did not noticed this before, this is two-ways merge, but we need a plain merge patch like proposed in this change. Good catch

**Comment by sbueringer** [comment]
@killianmuldoon Thank you very much! lgtm +/- squash

**Review by vincepri — COMMENTED** [review]
LGTM pending squash

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve
