### PR TITLE
🐛 ipam: fix gateway being required for IPAddress

### LINKED ISSUE #8536: IPAddress.spec.gateway should be optional for IPv6 and maybe for IPv4
Due to a sluggish implementation of the validation of IPAddress resources, the .spec.gateway field is currently required.

While this does make sense for IPv4, where you almost always provide a gateway when using DHCP (which the IPAM contract is essentially replacing), it does not for IPv6, which supports other methods like Router Advertising to configure a gateway.

We currently have two implementations, one making it completely optional, the other only for IPv6.
https://github.com/kubernetes-sigs/cluster-api/pull/8506 (entirely optional)
https://github.com/kubernetes-sigs/cluster-api/pull/8525 (ipv6 optional)

I'm in favor of making it optional for ipv6, but keep requiring it for ipv4.

For context: https://github.com/telekom/cluster-api-ipam-provider-in-cluster/issues/70

cc @fabriziopandini @sbueringer

### PR DESCRIPTION
**Pull request by schrej**
**What this PR does / why we need it**:
The validating webhook for IPAddress ensures that `.spec.gateway` is a valid IP address. This check fails if the field is empty, making it a required field. Since it is defined as `omitempty` it should be optional.

This PR wraps it with an is-empty check to allow the field to be empty.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
related to telekom/cluster-api-ipam-provider-in-cluster#70
Fixes #8536

### CODE REVIEW

File: exp/ipam/internal/webhooks/ipaddress.go [hunk 1]
```diff
@@ -123,14 +123,16 @@ func (webhook *IPAddress) validate(ctx context.Context, ip *ipamv1.IPAddress) er
...
-	if err != nil {
-		allErrs = append(allErrs,
-			field.Invalid(
-				specPath.Child("gateway"),
-				ip.Spec.Gateway,
-				"not a valid IP address",
-			))
+	if ip.Spec.Gateway != "" {
+		_, err = netip.ParseAddr(ip.Spec.Gateway)
+		if err != nil {
```
Comment (vincepri) [inline exp/ipam/internal/webhooks/ipaddress.go:128]: While we're here
```suggestion
		if _, err := netip.ParseAddr(ip.Spec.Gateway)
```

**Comment by schrej** [comment]
there is an alternative implementation here, that makes gateway required for ipv4, and allows it to be optional with ipv6: #8525 
We should decide which one we want to use.

/hold

**Comment by sbueringer** [comment]
@schrej can you maybe open an issue for discussion? Then we can close/open PRs according to consensus

File: exp/ipam/internal/webhooks/ipaddress.go [hunk 2]
```diff
@@ -123,14 +123,15 @@ func (webhook *IPAddress) validate(ctx context.Context, ip *ipamv1.IPAddress) er
...
 
-	_, err = netip.ParseAddr(ip.Spec.Gateway)
-	if err != nil {
-		allErrs = append(allErrs,
-			field.Invalid(
-				specPath.Child("gateway"),
-				ip.Spec.Gateway,
-				"not a valid IP address",
-			))
+	if ip.Spec.Gateway != "" {
```
Comment (sbueringer) [inline exp/ipam/internal/webhooks/ipaddress.go:126]: While our webhook now tolerates an empty gateway it's still a required field in the OpenAPI schema.
I think we need the following there:
```go
	// Gateway is the network gateway of the network the address is from.
	// +optional
	Gateway string `json:"gateway,omitempty"`
```

**Comment by sbueringer** [comment]
/lgtm

Maybe you want to do a quick manual test somewhere to see if it works as expected (as we don't have e2e test coverage with IPAM)

**Comment by schrej** [comment]
> > Maybe you want to do a quick manual test somewhere to see if it works as expected (as we don't have e2e test coverage with IPAM)
> 
> Maybe a stupid question - really don't know much about the IPAM implementations - how difficult would it be to set up an e2e test for this API? Could we create a simplified provider or use an existing one?

Depends on what's considered end-to-end for this API at this level. Imo we need to ensure that the two IPAM resources work as expected/defined, so IPAM and infra providers can rely on it.

If we want to include the apiserver in the scope, we could use envtest - but I don't know if and how webhooks can be tested with that. For now we have unit tests for what those webhooks do.
I don't see benefit in having a simplified provider (or using an existing one) since CAPI doesn't implement any behaviour for those resources. It just specifies how the resources look like, and we describe how they are supposed to be used. But it's on ipam providers to implement and test that.

The ipam providers should of course have e2e tests with these resources (we currently do not, since envtest doesn't run webhooks). Same goes for infra providers that want to support the contract.

**Review by vincepri — APPROVED** [review]
/approve

Based on the discussion in the related issue

**Comment by christianang** [comment]
I'd be interested in this being backported to release 1.4 if we could.
