### PR TITLE
🐛  Fixes issue with Windows, paths can't be escaped

### LINKED ISSUE #3487: Clusterctl incorrectly encodes Windows file paths for local repository
**What steps did you take and what happened:**

_Note: I originally produced this with the TKG cli, but investigation shows it's an issue within clusterctl itself._

The issue is that a recent [Windows 10 update](https://support.microsoft.com/en-us/help/4467268/url-encoded-unc-paths-not-url-decoded-in-windows-10-version-1803-later) changes the Windows URI pathing behavior: _"In Windows 10, version 1803 and later versions of Windows, URLs (such as SharePoint document libraries) can't be referenced by Universal Naming Convention (UNC) paths that contain URI encoding characters."_

This is an issue occurs if the user on Windows has a space in the username like `C:\Users\Gene Hynson\...` or `C:\Users\test space\...`

To reproduce this issue on Windows 10 1803+, provide a local providers URL to clusterctl with a space in the path like: `file:///C:/Users/test space/some/path/to/file.yaml`. Notice it becomes encoded as `file:///C:/Users/test%20space/some/path/to/file.yaml` and Windows fails to resolve this path. 

Error message: 
```
failed to read "cluster-template-definition-dev.yaml" from provider's repository "infrastructure-vsphere": failed to read file "C:\\Users\\test%20space\\.tkg\\providers\\infrastructure-vsphere\\v0.7.0\\cluster-template-definition-dev.yaml" from local release v0.7.0
```

**What did you expect to happen:**

clusterctl should not encode the path (at least for Windows). 

Expected: When local providers URL is provided to clusterctl and there is a space in the path like: `file:///C:/Users/test space/some/path/to/file.yaml` clusterctl should not encode this path and Windows should be able to resolve it. 

**Anything else you would like to add:**

- Line of code causing this issue (I think): https://github.com/kubernetes-sigs/cluster-api/blob/4e90523fa94618a4cbddbd9fec98ab052873bc89/cmd/clusterctl/client/repository/repository_local.go#L147
- Exception is thrown here: https://github.com/kubernetes-sigs/cluster-api/blob/4e90523fa94618a4cbddbd9fec98ab052873bc89/cmd/clusterctl/client/repository/repository_local.go#L98-L101
- Go Playground reproducing the issue: https://play.golang.org/p/O7dpNE9L_ye
- Microsoft article about this change in Windows 10: https://support.microsoft.com/en-us/help/4467268/url-encoded-unc-paths-not-url-decoded-in-windows-10-version-1803-later
- Relevant issue: https://github.com/kubernetes-sigs/cluster-api/issues/3416

**Environment:**

- Cluster-api version: 0.3.8
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`): Windows 10

/kind bug
/area clusterctl

### PR DESCRIPTION
**Pull request by genehynson**
Authored-by: Gene Hynson <ghynson@vmware.com>

**What this PR does / why we need it**:
- This PR removes the `url.EscapedPath()` step from Windows local repositories. On Windows 10 versions >= 1803, Windows will no longer decode file paths. This causes a failure when clusterctl tries to read the providers if your Windows username has a space in it (e.g. `C:\Users\Gene Hynson\...`):

**Which issue(s) this PR fixes**:

Fixes #3487 

**Testing**

I'm not exactly sure what's the best way to add automated tests for this change, since it would require setting `runtime.GOOS`. If anyone has suggestions, I'm all ears!

In terms of manual tests, I tested this on the latest version of Windows and on Mac - it works fine.

### CODE REVIEW

File: cmd/clusterctl/client/repository/repository_local.go [hunk 1]
```diff
@@ -144,10 +144,14 @@ func newLocalRepository(providerConfig config.Provider, configVariablesClient co
...
 	// in case of windows, we should take care of removing the additional / which is required by the URI standard
 	// for windows local paths. see https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/ for more details
-	path := url.EscapedPath()
+	path := url.Path
 	if runtime.GOOS == "windows" {
 		path = strings.TrimPrefix(path, "/")
 		path = filepath.FromSlash(path)
+	} else {
+		// Windows 10 update 1803 stops decoding file paths
+		// https://support.microsoft.com/en-us/help/4467268/url-encoded-unc-paths-not-url-decoded-in-windows-10-version-1803-later
```
Comment (neolit123) [inline cmd/clusterctl/client/repository/repository_local.go:153]: ideally, the note about Windows should be in the Windows branch above, indicating that escaping is not required for older versions and not supported in 1803 and later, linking to the page about the UNC change.

the "in case of windows..." note should be moved in the Windows branch as well.

File: cmd/clusterctl/client/repository/repository_local.go [hunk 2]
```diff
@@ -144,10 +144,14 @@ func newLocalRepository(providerConfig config.Provider, configVariablesClient co
...
+		path = url.EscapedPath()
```
Comment (neolit123) [inline cmd/clusterctl/client/repository/repository_local.go:154]: there could be a comment here on why the path is escaped for other OSes.

**Review by neolit123 — COMMENTED** [review]
thanks for the PR
/ok-to-test

**Comment by neolit123** [comment]
given the OS is detected on runtime the IsAbs logic could be extracted to a helper function that accepts the OS as a parameter and this could be unit tested. currently the unit tests don't seem to handle Windows paths.

potentially a separate PR.

File: cmd/clusterctl/client/repository/repository_local.go (hunk 2 above)
Comment (genehynson) [reply cmd/clusterctl/client/repository/repository_local.go:154]: Honestly...we could probably remove `url.EscapedPath()` altogether. Looking at the blame, it was introduced in this commit for adding Windows support: https://github.com/kubernetes-sigs/cluster-api/commit/737e36921121d12504bd78a66f8d86c72c5daba5

I don't believe escaping file paths is a requirement for other OSes. Thoughts?

Comment (neolit123) [reply cmd/clusterctl/client/repository/repository_local.go:154]: it was already present here before that commit:
https://github.com/kubernetes-sigs/cluster-api/commit/737e36921121d12504bd78a66f8d86c72c5daba5#diff-88fbf51cc189eba2daf622ffc4a215d0L134

Comment (neolit123) [reply cmd/clusterctl/client/repository/repository_local.go:154]: /cc @fabriziopandini 
do you recall why EscapedPath was required when preparing "basepath"?

Comment (genehynson) [reply cmd/clusterctl/client/repository/repository_local.go:154]: Ah, yup. Introduced here: https://github.com/kubernetes-sigs/cluster-api/commit/b5b9f79af96db9f186a2a0132044b91cd0f11473#diff-88bc45b90b0324f78a6bea9e5c59aa26R138

Comment (fabriziopandini) [reply cmd/clusterctl/client/repository/repository_local.go:154]: TBH I don't recall.
I'm fine in removing it if tests report green signal on both OSes (unfortunately there is no CI signal for windows :-))

File: cmd/clusterctl/client/repository/repository_local.go (hunk 1 above)
Comment (genehynson) [reply cmd/clusterctl/client/repository/repository_local.go]: Moved both comments within `if` block

File: cmd/clusterctl/client/repository/repository_local.go (hunk 2 above)
Comment (genehynson) [reply cmd/clusterctl/client/repository/repository_local.go]: Ok, I removed it. Manually tested on Windows and it works.

**Comment by neolit123** [comment]
thanks for the update.
leaving the LGTM to another set of eyes as i have no context on the original idea behind the EscapedPath()

/kind cleanup bug
/approve
/priority important-longterm
