### PR TITLE
:bug: Remove message from Runtime SDK FailureResponses

### LINKED ISSUE #6921: Ensure errors from Runtime Extensions are sanitized before becoming conditions
Currently we are returning errors from our runtime extensions on failure and, as with other types of errors in reconciliation, surfacing them in the TopologyReconciled condition on the Cluster object.

As these errors are created by an external process they are currently arbitrary and may violate Runtime SDK's assumptions around [idempotence](https://main.cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-extensions.html#idempotence) - even though each successful call might be idempotent, failures may be unique. 

This could happen if any data in the error message changes per reconcile, or regulalarly. Examples could include:  timecodes, resource UIDs and tracing IDs, but this issue could be triggered by any idempotent error message.  

This is an issue because changing the error message on a condition causes another reconciliation. If the error returned from the extension contains non-deterministic information, it will reconcile again each time a new error is applied, avoiding exponential backoff. 

A similar issue surfaced in the Cluster topology controller https://github.com/kubernetes-sigs/cluster-api/issues/5945 and was fixed by ensuring the object name, the definitive source of the issue in that case, was stripped from error messages. In the case of runtime extensions we can't assume anything about the error, so we probably need to simply return a pre-formatted error from the reconciler in all cases.

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Remove the Message returned from the Runtime extension from the error returned by CallExtension and Discovery. This message may be unique and could cause too many reconciliation loops as in #5945

Fixes #6921

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/hold 

Just investigating if this has any impact on the e2e tests where we compare the blocking condition.

**Comment by killianmuldoon** [comment]
/unhold
/area runtime-sdk
The test is running fine on my machine and in the CI.

File: internal/runtime/client/client.go [hunk 1]
```diff
@@ -364,8 +366,9 @@ func (c *client) CallExtension(ctx context.Context, hook runtimecatalog.Hook, fo
 
 	// If the received response is a failure then return an error.
 	if response.GetStatus() == runtimehooksv1.ResponseStatusFailure {
-		log.Error(err, "extension handler returned a failure response")
-		return errors.Errorf("failed to call extension handler %q: got failure response with message %q", name, response.GetMessage())
+		log.Error(err, "extension handler returned a failure response with message: %v", response.GetMessage())
```
Comment (sbueringer) [inline internal/runtime/client/client.go:369]:
```suggestion
		log.Error(err, fmt.Sprintf("failed to call extension handler %q: got failure response with message %v", name, response.GetMessage()))
```
to be consitent with the error message and the other log above
I think it's good if the error message contains the name of the handler
previous version would have panic'ed IIRC because only a key of a k/v pair was set

Comment (sbueringer) [reply internal/runtime/client/client.go:369]: As we use log.Error here. Should we also use it in l.145?

**Comment by killianmuldoon** [comment]
> We might to eventually categorised the errors to provide a more meaningful message without triggering extra loops.
Also I wonder if it should be the consumer setting the condition doing the discrimination and setting the error message it.


This is hard because these errors are currently returned by the user. The issue with Message as it is is that they're fully defined by the Runtime Extension. Even if we had fixed errors that could us e.g. errors.Cause() we couldn't be certain they'd be used without some additional validation (which would mean failing due to non-conforming error messages which seems like bad UX 😆) 

If you have any ideas on this though it would be great to hear them.

File: internal/runtime/client/client.go (hunk 1 above)
Comment (killianmuldoon) [reply internal/runtime/client/client.go]: I think we should use log.Info in both - here the error isn't actually picking anything up - I think it's always nil.

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

/cherry-pick release-1.2

If in future we will reconsider this because user find it complex to investigate problems, we should make sure to document that error message should be idempotent
