### PR TITLE
🐛 Don't return error if cannot find default config

### LINKED ISSUE #2947: clusterctl init returns config file not found error in clean environment
**What steps did you take and what happened:**
1. In your environment, ensure that you do not have `$HOME/.cluster-api/clusterctl*`. This is the default path location that clusterctl looks at for its config.
1. Run `clusterctl init`

See the following error:
```
Error: failed to initialize the configuration reader: Config File "clusterctl" Not Found in "[/Users/wfernandes/.cluster-api]"
```

**What did you expect to happen:**
Expected `clusterctl init` to succeed without having to create an empty `$HOME/.cluster-api/clusterctl.yaml` for example.

**Anything else you would like to add:**
This is important for user experience.
This is where we need to fix it. 
Suggestion: Perhaps check if the `path` is empty and if the error is `viper.ConfigFileNotFoundError`, then ignore it.

https://github.com/kubernetes-sigs/cluster-api/blob/ba3bd5c095e0c7af6d39ff62a6bd77b8609722fe/cmd/clusterctl/client/config/reader_viper.go#L64-L68

**Environment:**

- Cluster-api version: Current master. At the time ba3bd5c095e0c7af6d39ff62a6bd77b8609722fe

/kind bug
/help
/good-first-issue
/area clusterctl

### PR DESCRIPTION
**Pull request by wfernandes**
**What this PR does / why we need it**:
If clusterctl default config under $HOME/.cluster-api/clusterctl.yaml
doesn't exist, commands like clusterctl init should still work. 
However, it should still return errors if the contents of the config file is unparsable.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2947

### CODE REVIEW

File: cmd/clusterctl/client/config/reader_viper.go [hunk 1]
```diff
@@ -61,8 +61,11 @@ func (v *viperReader) Init(path string) error {
 	viper.AllowEmptyEnv(true)
 	viper.AutomaticEnv()
 
-	if err := viper.ReadInConfig(); err != nil {
-		return err
+	err := viper.ReadInConfig()
+	if err != nil {
+		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
+			return err
+		}
```
Comment (wfernandes) [inline cmd/clusterctl/client/config/reader_viper.go:68]: I did it this way because I still want to return errors from `viper.ReadInConfig()`. There may be other errors regarding parsing the config or even if viper supports the config extension.
Ideally, I could've done a  `os.Stat(viper.ConfigFileUsed())` but I believe there is a behavioral bug for this since it could return `""`.

Comment (neolit123) [reply cmd/clusterctl/client/config/reader_viper.go:68]: i think a comment on top will be useful for future readers.

File: cmd/clusterctl/client/config/reader_viper_test.go [hunk 2]
```diff
@@ -26,28 +26,52 @@ import (
...
+
 	dir, err := ioutil.TempDir("", "clusterctl")
 	g.Expect(err).NotTo(HaveOccurred())
 	defer os.RemoveAll(dir)
 
 	configFile := filepath.Join(dir, ".clusterctl.yaml")
 	g.Expect(ioutil.WriteFile(configFile, []byte("bar: bar"), 0640)).To(Succeed())
+
+	configFileBadContents := filepath.Join(dir, ".clusterctl-bad.yaml")
+	g.Expect(ioutil.WriteFile(configFileBadContents, []byte("asdasd&*(^"), 0640)).To(Succeed())
```
Comment (neolit123) [inline cmd/clusterctl/client/config/reader_viper_test.go:48]: potentially use something more common like `foo` instead of `asdasd`?

File: cmd/clusterctl/client/config/reader_viper.go [hunk 3]
```diff
@@ -61,8 +61,15 @@ func (v *viperReader) Init(path string) error {
 	viper.AllowEmptyEnv(true)
 	viper.AutomaticEnv()
 
-	if err := viper.ReadInConfig(); err != nil {
-		return err
+	err := viper.ReadInConfig()
+	if err != nil {
+		// ConfigFileNotFoundError is returned if it cannot find the default
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/config/reader_viper.go:66]: Have you considered to make `os.Stat(path)` inside the `if path != "" { }`?

Comment (wfernandes) [reply cmd/clusterctl/client/config/reader_viper.go:66]: I think we can do that. I'll refactor that.

Comment (wfernandes) [reply cmd/clusterctl/client/config/reader_viper.go]: So I added the `os.Stat` check inside the `if path != "" {}`. 
I also added another commit that specifically checks all the supported extensions of the default config file and skips reading in the config if that doesn't exist. I think that may be more readable/understandable than having the special handling of `ConfigFileNotFoundError`.
If the second commit looks better let me know and I can squash them.

File: cmd/clusterctl/client/config/reader_viper_test.go [hunk 4]
```diff
@@ -26,28 +26,54 @@ import (
...
+	// Change HOME dir and do not specify config file
+	// (.cluster-api/clusterctl) in it.
+	origHomeDir := os.Getenv("HOME")
+	clusterctlHomeDir, err := ioutil.TempDir("", "clusterctl-default")
+	g.Expect(err).NotTo(HaveOccurred())
+	defer os.RemoveAll(clusterctlHomeDir)
+	os.Setenv("HOME", clusterctlHomeDir)
+	defer func() {
+		os.Setenv("HOME", origHomeDir)
+	}()
```
Comment (vincepri) [inline cmd/clusterctl/client/config/reader_viper_test.go:40]: I wonder if we should be actually doing this, it could have some side-effects that we don't know about

Comment (jdef) [reply cmd/clusterctl/client/config/reader_viper_test.go:40]: agree. even a global var that can be overridden/restored later would be nicer:
```go
// reader_viper.go
var homeDirFunc = homedir.HomeDir
...
    viper.AddConfigPath(filepath.Join(homeDirFunc(), ...
```

```go
// reader_viper_test.go
oem := homeDirFunc
defer func() { homeDirFunc = oem }()  // restore original global var
homeDirFunc = someTestFixture
.. // run test case
```
of course, globals like this smell too. maybe instead of a global, define a homeDirFunc in the `viperReader` struct with a default initialized value of `homedir.HomeDir` and override that in the test case.

Comment (wfernandes) [reply cmd/clusterctl/client/config/reader_viper_test.go:40]: Yeah..I was trying to find a way to write a test for this that didn't require me to make huge api changes all over the place. I think we can do the options pattern here. Thanks for the suggestions!

File: cmd/clusterctl/client/config/reader_viper.go (hunk 3 above)
Comment (wfernandes) [reply cmd/clusterctl/client/config/reader_viper.go]: Because I had to make another change, I just went ahead and squashed the commits. Let me know if this looks better.

File: cmd/clusterctl/client/config/reader_viper.go [hunk 5]
```diff
@@ -82,3 +114,19 @@ func (v *viperReader) Set(key, value string) {
...
+
+// checkDefaultConfig checks the existence of the default config
+func (v *viperReader) checkDefaultConfig() bool {
+	var defaultConfigExists bool
+	for _, path := range v.configPaths {
+		for _, ext := range viper.SupportedExts {
+			f := fmt.Sprintf("%s%s.%s", path, ConfigName, ext)
+			_, err := os.Stat(f)
+			if err == nil {
+				defaultConfigExists = true
```
Comment (jdef) [inline cmd/clusterctl/client/config/reader_viper.go:126]: nit: maybe just `return true` here instead, for simplicity since you're inside nested loops (and ditch defaultConfigExists)?

File: cmd/clusterctl/client/config/reader_viper.go (hunk 3 above)
Comment (jdef) [reply cmd/clusterctl/client/config/reader_viper.go]: LGTM
