### PR TITLE
:bug: update TopologyReconciled condition on cluster deletion

### LINKED ISSUE #7926: Topology controller should reset TopologyReconciled when deleting
**What steps did you take and what happened:**
When a cluster is deleted, after calling the delete hook, then the topology controller stops to reconcile a cluster. However, during this process, it never resets the TopologyReconciled, which will continue to represent the latest state before deletion.

I found this looking at a cluster stuck in deletion, where the TopologyReconciled was reporting an error, but this was a red herring that took some time to figure it out.

**What did you expect to happen:**
TopologyReconciled condition to be reset while the cluster is being deleted/After the hook is called.

/kind bug
/area topology
/triage accepted
/help

### PR DESCRIPTION
**Pull request by cahillsf**
**What this PR does / why we need it**:
Sets `TopologyReconciled` status condition to `False` on cluster deletion 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7926

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

**Comment by cahillsf** [comment]
sounds good, thanks @killianmuldoon.  Do you think this current fix does what's required?  

I believe it should address the behavior described and `False` seems like the correct condition to set based on the [description of a False status](https://github.com/kubernetes-sigs/cluster-api/blob/01f619f712a6743e28e27923389ae6c1fdffa6cb/api/v1beta1/condition_consts.go#L272-L274) as, on recognizing the `DeletionTimestamp`, the topology cluster controller stops reconciling and leaves the other controllers to perform the deletion ([src link](https://github.com/kubernetes-sigs/cluster-api/blob/01f619f712a6743e28e27923389ae6c1fdffa6cb/internal/controllers/topology/cluster/cluster_controller.go#L167-L171)).

If you agree, then I will add a test and move it out of draft.

**Comment by killianmuldoon** [comment]
I think you're right that  marking as False with Severity Info and the reason being the cluster being deleted is the correct condition in this case.

File: internal/controllers/topology/cluster/cluster_controller.go [hunk 1]
```diff
@@ -388,6 +389,24 @@ func (r *Reconciler) reconcileDelete(ctx context.Context, cluster *clusterv1.Clu
 			}
 		}
 	}
+	patchHelper, err := patch.NewHelper(cluster, r.Client)
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/cluster_controller.go:392]: Wondering if we can benefit of the deferred patch helper in the main reconcile method...

What if we move 

https://github.com/kubernetes-sigs/cluster-api/blob/282fa77eaaa6d1040dfc3f0d1e53aca21f0c6e25/internal/controllers/topology/cluster/cluster_controller.go#L168-L172

Down after the defer?
This will probably require also to make reconcileConditions no-op in case the cluster is deleted, or even better we should move the logic to set the condition while deleting from here to reconcileConditions

Opinions?

Comment (cahillsf) [reply internal/controllers/topology/cluster/cluster_controller.go:392]: 👋 based on [this comment](https://github.com/kubernetes-sigs/cluster-api/blob/282fa77eaaa6d1040dfc3f0d1e53aca21f0c6e25/internal/controllers/topology/cluster/cluster_controller.go#L168):
> // In case the object is deleted, the managed topology stops to reconcile;
 
I assumed that the idea was to prevent [the reconcile method](https://github.com/kubernetes-sigs/cluster-api/blob/282fa77eaaa6d1040dfc3f0d1e53aca21f0c6e25/internal/controllers/topology/cluster/cluster_controller.go#L200-L201) from being called once the `DeletionTimestamp` is recognized.  

If the logic is moved to `reconcileConditions` then the normal reconciliation loop will run when the Cluster object has been deleted.  Is that okay?

Comment (cahillsf) [reply internal/controllers/topology/cluster/cluster_controller.go:392]: hey @fabriziopandini wanted to bump this and see if you have any feedback on my most recent comment

Comment (ykakarap) [reply internal/controllers/topology/cluster/cluster_controller.go:392]: I believe what @fabriziopandini Is suggesting is to move the entire if block 
```golang
        // In case the object is deleted, the managed topology stops to reconcile;
	// (the other controllers will take care of deletion).
	if !cluster.ObjectMeta.DeletionTimestamp.IsZero() {
		return r.reconcileDelete(ctx, cluster)
	}
```
below the defer block but still keep it above the call to `reconcile()` so that if the the cluster is deleted it only calls `reconcileDelete` and not `reconcile`. 
The defer block will be triggered after `reconcileDelete` returns and inside the defer block the `reconcileConditions` should handle setting the `TopologyReconciled` condition depending on if the cluster is deleted or not.

Comment (cahillsf) [reply internal/controllers/topology/cluster/cluster_controller.go]: sounds good, thanks @ykakarap.  i just pushed up these changes -- let me know if you have additional feedback

File: internal/controllers/topology/cluster/conditions.go [hunk 2]
```diff
@@ -43,6 +43,20 @@ func (r *Reconciler) reconcileConditions(s *scope.Scope, cluster *clusterv1.Clus
 //     In such a case, since some of the component's spec would be adrift from the topology the
 //     topology cannot be considered fully reconciled.
 func (r *Reconciler) reconcileTopologyReconciledCondition(s *scope.Scope, cluster *clusterv1.Cluster, reconcileErr error) error {
+
+	// Mark TopologyReconciled as false due to cluster deletion
```
Comment (ykakarap) [inline internal/controllers/topology/cluster/conditions.go:47]:
```suggestion
	// Mark TopologyReconciled as false due to cluster deletion.
```
nit

**Review by ykakarap — COMMENTED** [review]
Overall LGTM. 

There are lint issues in this PR. 
The linter job has not been triggered for this PR as it needs approval from a maintainer to trigger it, @killianmuldoon can you approve the job?

In the mean time @cahillsf, you can run `make lint` locally and fix the reported issues.

LGTM pending lint fix.

**Comment by ykakarap** [comment]
Thank you! 

/lgtm

**Review by vincepri — APPROVED** [review]

**Comment by vincepri** [comment]
/hold

can you squash commits?

**Comment by cahillsf** [comment]
hey @vincepri 👋 thanks for taking a look -- seeing some inconsistent messaging in the test results, `tide` is indicating:
> Pending — Not mergeable. Job pull-cluster-api-build-main has not succeeded.

But that job (`pull-cluster-api-build-main`) is indicating [success](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/8422/pull-cluster-api-build-main/1658543744082776064):
> pull-cluster-api-build-main — Job succeeded.

Am I missing something or is this unexpected behavior?

---
Also seeing `1 workflow awaiting approval` is this something you can approve?

**Comment by ykakarap** [comment]
One of the maintainers will have to approve the job. @sbueringer, can you help with this?

**Review by killianmuldoon — COMMENTED** [review]
/area clusterclass
