### PR TITLE
🐛  Add unlock mechanism to the kubeadm bootstrap provider

### LINKED ISSUE #5814: A deleted Machine can block cluster initialization indefinitely (flake)
**What steps did you take and what happened:**
- We found a cluster that was stuck initializing the first control plane.
- The kubeadmConfig for the machine was in a loop with `"A control plane is already being initialized, requeing until control plane is ready"`
- Looking at the configMap holding the init lock for that cluster, we found a machine that no longer exists. 

The theory is the lock failed to release [here](https://github.com/kubernetes-sigs/cluster-api/blob/v0.3.23/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L360-L362) and the machine + kubeadm config was removed before the next reconcile which left the outdated configMap lock behind.

**What did you expect to happen:**
- the lock will eventually get released if the machine owning it no longer exists

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.23
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by killianmuldoon**
This fix adds logic to the Kubeadm bootstrapper that allows it to release the lock on reconciliation of control plane machines if the machine currently holding the lock can not be found. 

Previously if the machine to get the lock was deleted for any reason the cluster control plane was stuck indefinitely in 'Initializing'. 

Fixes #5814 (speculatively)

### CODE REVIEW

File: bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go [hunk 1]
```diff
@@ -62,16 +62,25 @@ func (c *ControlPlaneInitMutex) Lock(ctx context.Context, cluster *clusterv1.Clu
...
 			return true
 		}
+
+		// If the machine that created the lock can not be found unlock the mutex.
+		err = c.client.Get(ctx, client.ObjectKey{
+			Namespace: cluster.Namespace,
+			Name:      info.MachineName,
+		}, &clusterv1.Machine{})
+		if apierrors.IsNotFound(err) {
+			c.Unlock(ctx, cluster)
```
Comment (killianmuldoon) [inline bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go:82]: The one issue here is whether or not Unlocking (even an invalid lock) is outside the remit of a Lock() function. In that case we could have validation of the lock somewhere else.

Comment (fabriziopandini) [reply bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go:82]: I'm fine to have this here because, in the end, it is just an enhanced strategy to try to get the lock.
But let's wait for others opinions as well

File: bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go [hunk 2]
```diff
@@ -62,16 +62,25 @@ func (c *ControlPlaneInitMutex) Lock(ctx context.Context, cluster *clusterv1.Clu
...
 		if info.MachineName == machine.Name {
 			return true
 		}
+
+		// If the machine that created the lock can not be found unlock the mutex.
+		err = c.client.Get(ctx, client.ObjectKey{
+			Namespace: cluster.Namespace,
+			Name:      info.MachineName,
+		}, &clusterv1.Machine{})
+		if apierrors.IsNotFound(err) {
```
Comment (vincepri) [inline bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go:81]:
```suggestion
		if err := c.client.Get(ctx, client.ObjectKey{
			Namespace: cluster.Namespace,
			Name:      info.MachineName,
		}, &clusterv1.Machine{}); apierrors.IsNotFound(err) {
```

Let's also handle the else if err != nil case?

File: bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go (hunk 1 above)
Comment (vincepri) [reply bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go:82]: +1

File: bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go (hunk 2 above)
Comment (killianmuldoon) [reply bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go:81]: I don't think we want to block on any other type of error - but we could log if there's some issue.

Comment (vincepri) [reply bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go]: Yeah, that's what I was thinking earlier, a different branch that returns false and logs

Comment (killianmuldoon) [reply bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go]: The new version always logs the error and unlocks only if the err is apierrors not found.

**Review by vincepri — APPROVED** [review]
/lgtm

**Comment by killianmuldoon** [comment]
Had to add a function to the log test as it was giving a null pointer when calling Error.

File: bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go [hunk 3]
```diff
@@ -305,6 +395,18 @@ func (l *logtests) Info(level int, msg string, keysAndValues ...interface{}) {
 		data: data,
 	})
 }
+
+func (l *logtests) Error(err error, msg string, keysAndValues ...interface{}) {
```
Comment (killianmuldoon) [inline bootstrap/kubeadm/internal/locking/control_plane_init_mutex_test.go:399]: Had to add a function to the log test as it was giving a null pointer when calling Error.

**Comment by fabriziopandini** [comment]
/lgtm
@vincepri @CecileRobertMichon for a final pass

File: bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go [hunk 4]
```diff
@@ -62,16 +62,27 @@ func (c *ControlPlaneInitMutex) Lock(ctx context.Context, cluster *clusterv1.Clu
...
 			return false
 		}
-		// the machine requesting the lock is the machine that created the lock, therefore the lock is acquired
+		// The machine requesting the lock is the machine that created the lock, therefore the lock is acquired.
 		if info.MachineName == machine.Name {
 			return true
 		}
+
+		// If the machine that created the lock can not be found unlock the mutex.
+		if err = c.client.Get(ctx, client.ObjectKey{
```
Comment (vincepri) [inline bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go:77]:
```suggestion
		if err := c.client.Get(ctx, client.ObjectKey{
```

Comment (vincepri) [reply bootstrap/kubeadm/internal/locking/control_plane_init_mutex.go:77]: To make sure not to leak the error outside of the `if` scope

**Review by vincepri — APPROVED** [review]
/approve
/lgtm
