### PR TITLE
🐛 clusterctl: fix goproxy to also return versions for major > 1

### LINKED ISSUE #7700: goproxyClient doesn't list version >=v2
**What steps did you take and what happened:**

```console
$ clusterctl upgrade apply --infrastructure capa-system/aws:v2.0.2 -v 10
No default config file available
Checking cert-manager version...
Cert-manager is already up to date
Performing upgrade...
Fetching File="metadata.yaml" Provider="cluster-api" Type="CoreProvider" Version="v1.3.0"
Fetching File="metadata.yaml" Provider="aws" Type="InfrastructureProvider" Version="v1.5.2"
Error: invalid target version: version v2.0.2 for the provider capa-system/infrastructure-aws does not match any release series
````

**What did you expect to happen:**

```
...
Fetching File="metadata.yaml" Provider="aws" Type="InfrastructureProvider" Version="v2.0.2"
...
```

**Anything else you would like to add:**

It worked when I disabled goproxy with `export GOPROXY=off`.

I suspect that `goproxyClient` used from `cmd/clusterctl/client/repository/repository_github.go` (presumably to avoid hitting the GH rate limiter) does work well when the version of the component is v2 (like the latest version of the aws provider)

**Environment:**

- Cluster-api version: v1.3.0
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
/area clusterctl
/area upgrades
/area artifacts
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

This PR fixes the goproxy client to also list versions of go modules > v1.
The previously used goproxy endpoint only lists versions of major v1.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7700

**Additional info**:

The goproxy client will not provide the correct results for go based provider which do not follow go module semantical versioning (e.g. tagging v2.0.0 but not setting go.mod to `/v2`. [xref](https://github.com/kubernetes-sigs/cluster-api/issues/7700#issuecomment-1340759006). If this is considered as a no-go, I would propose to remove the goproxy implementation instead of fixing it. Such providers are always able to set `GOPROXY=off` to allow clusterctl to directly use the github api.

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
/lgtm

Should we also fix the code in https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/tools/mdbook/releaselink/releaselink.go ?

We should probably dedupe these two and favor less copying around, wdyt?

**Comment by chrischdi** [comment]
> /lgtm
> 
> Should we also fix the code in https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/tools/mdbook/releaselink/releaselink.go ?
> 
> We should probably dedupe these two and favor less copying around, wdyt?

Great point. Did already forget that we've "stolen" that from there :-)
Also adjusted the parameter for aws to show the latest version in the doc.

I moved it to `internal/goproxy` for now. Happy to get better recommendations 👍 
I also added it as separate commit for now to better show the diff to the first commit. Will squash later on.

File: internal/goproxy/goproxy_test.go [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+			false,
+		},
+	}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			ctx := context.Background()
+
+			got, err := clientGoproxy.GetVersions(ctx, tt.gomodulePath)
+			if (err != nil) != tt.wantErr {
+				t.Errorf("Client.GetVersions() error = %v, wantErr %v", err, tt.wantErr)
```
Comment (ykakarap) [inline internal/goproxy/goproxy_test.go:98]: How about using gomega assertions? 
We use gomega everywhere else in the project. It would be nice to have consistency.

(Same comment at other places in the file).

File: internal/goproxy/goproxy.go [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+)
+
+// Client is a client to query versions from a goproxy instance.
+type Client struct {
+	scheme string
+	host   string
+}
+
+// NewGoproxyClient returns a new goproxyClient instance.
+func NewGoproxyClient(scheme, host string) *Client {
```
Comment (ykakarap) [inline internal/goproxy/goproxy.go:52]:
```suggestion
func NewClient(scheme, host string) *Client {
```
nit: Since the package is already called `goproxy` it new function will read `goproxy.NewClient()`.

File: hack/tools/mdbook/releaselink/releaselink.go [hunk 3]
```diff
@@ -58,36 +56,22 @@ func (l ReleaseLink) Process(input *plugin.Input) error {
 		versionRange := semver.MustParseRange(tags.Get("version"))
 		includePrereleases := tags.Get("prereleases") == "true"
 
-		repo, err := vcs.RepoRootForImportPath(gomodule, false)
+		scheme, host, err := goproxy.GetSchemeAndHost(os.Getenv("GOPROXY"))
```
Comment (ykakarap) [inline hack/tools/mdbook/releaselink/releaselink.go:59]: Since now we are reading from `GOPROXY` env variable we should account for `scheme` and `host` being empty strings. 

If `GOPROXY` envvar is set to `direct` or `off` we will get an empty `scheme` and `host` and the code below will fail.

**Review by ykakarap — CHANGES_REQUESTED** [review]
The changes to support >v1 versions looks good.

There is an edge case where this might now work. Example when a go modules jumps from v1 to v3 then the current code will not list the v3 versions as it will stop immediately after v2 is not found. This is a very rare case and I dont know think why someone might want to jump a major version. But, I thought I would point this out anyway. 

FYI: This is a breaking change in clusterctl's library but given our [compatibility notice](https://github.com/kubernetes-sigs/cluster-api/tree/main/cmd/clusterctl#compatibility-notice) for clusterctl we should be fine and no further action is needed.

File: hack/tools/mdbook/releaselink/releaselink.go (hunk 3 above)
Comment (chrischdi) [reply hack/tools/mdbook/releaselink/releaselink.go:59]: Added returning an error when one of scheme or host is empty to fail.

**Comment by chrischdi** [comment]
Thanks for reviewiewing.

> The changes to support >v1 versions looks good.
> 
> There is an edge case where this might now work. Example when a go modules jumps from v1 to v3 then the current code will not list the v3 versions as it will stop immediately after v2 is not found. This is a very rare case and I dont know think why someone might want to jump a major version. But, I thought I would point this out anyway.

Yes great point! That's why I mentioned it in the office hours and also added the note at the PR description 👍

**Comment by chrischdi** [comment]
Squashed both commits to a single one.

**Review by killianmuldoon — COMMENTED** [review]
Looks good - just a couple nits

**Comment by fabriziopandini** [comment]
Thanks @chrischdi for quicky jumping on this issue!
/lgtm
/approve
