### PR TITLE
:seedling: Move command and arg handling of manager.yaml to tilt-prepare

### LINKED ISSUE #6202: The provided example to enable feature gates via extra_args in Tilt does not work
**What steps did you take and what happened:**
Enabling the ClusterClass feature-gate in the tilt-settings.json file via the described way via [extra_args](https://cluster-api.sigs.k8s.io/developer/tilt.html#tilt-settingsjson-fields).
While trying to deploy the ClusterClass resource the admission webhook denies the request with following:
```
Error from server (spec: Forbidden: can be set only if the ClusterTopology feature flag is enabled): error when creating "/tmp/docker-clusterclass.yaml": admission webhook "validation.dockerclustertemplate.infrastructure.cluster.x-k8s.io" denied the request: spec: Forbidden: can be set only if the ClusterTopology feature flag is enabled
```

**What did you expect to happen:**
That the feature-flag is enabled and the deployment works.

**Anything else you would like to add:**
The feature-gates arg is [hard-coded](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/config/manager/manager.yaml#L22) in the providers and by that will end up as the last arg because the ones coming from Tilt are [added before](https://github.com/kubernetes-sigs/cluster-api/blob/main/Tiltfile#L260) to the ENTRYPOINT of the docker image of the manager. AFAIU the only way to use feature-gates is by settings those via [kustomize_substitutions](https://cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html#enabling-experimental-features-on-tilt). So using feature-gates as an example here is a bit misleading.

A solution might be to change the extra_args example to something other than the hard coded ones (`--feature-gates`, `--metrics-bind-addr`, `--leader-elect`) with a note that those are actually hard-coded. See: https://kubernetes.slack.com/archives/C8TSNPY4T/p1645705512971069?thread_ts=1645705141.237239&cid=C8TSNPY4T

**Environment:**

- Cluster-api version: latest
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
 
<sub>Johannes Frey <[johannes.frey@daimler.com](mailto:johannes.frey@daimler.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

### PR DESCRIPTION
**Pull request by johannesfrey**
**What this PR does / why we need it**:
Move the calculation of command and args of the manager deployment image to tilt-prepare and clean up the Tiltfile accordingly. This solves the issue that some extra_args given by the user won't be respected in the current solution. See: https://github.com/kubernetes-sigs/cluster-api/issues/6202

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6202

Signed-off-by: Johannes Frey <johannes.frey@daimler.com>
<sub>Johannes Frey <[johannes.frey@daimler.com](mailto:johannes.frey@daimler.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

### CODE REVIEW

File: Tiltfile [hunk 1]
```diff
@@ -232,13 +232,7 @@ def enable_provider(name, debug):
     links = []
 
     if debug_port != 0:
-        # Add delve when debugging. Delve will always listen on the pod side on port 30000.
-        entrypoint = ["sh", "/start.sh", "/dlv", "--listen=:" + str(30000), "--accept-multiclient", "--api-version=2", "--headless=true", "exec", "--", "/manager"]
         port_forwards.append(port_forward(debug_port, 30000))
```
Comment (johannesfrey) [inline Tiltfile:235]: Should me make this actually configurable?

File: hack/tools/tilt-prepare/main.go [hunk 2]
```diff
@@ -470,16 +515,53 @@ func writeIfChanged(prefix string, path string, yaml []byte) error {
...
+		for j, container := range d.Spec.Template.Spec.Containers {
+			if container.Name != "manager" {
+				// as defined in clusterctl Provider Contract "Controllers & Watching namespace"
+				continue
+			}
+
+			cmd := []string{"sh", "/start.sh", "/dlv", "--accept-multiclient", "--api-version=2", "--headless=true", "exec"}
+
+			if debugConfig.Port > 0 {
+				cmd = append(cmd, "--listen=:30000")
```
Comment (johannesfrey) [inline hack/tools/tilt-prepare/main.go:552]: Should me make this actually configurable? Same for profile and metrics port.

File: hack/tools/tilt-prepare/main.go [hunk 3]
```diff
@@ -193,12 +227,19 @@ func tiltResources(ctx context.Context) error {
 		if len(pValues) == 3 && pValues[2] == "debug" {
```
Comment (johannesfrey) [inline hack/tools/tilt-prepare/main.go:227]: Should we drop the debug handling here as well as the `:debug` in the Tiltfile and make it conditional on the existence of the debug field in the given tilt-settings file/struct that is being read by this PR?

File: hack/tools/tilt-prepare/main.go [hunk 4]
```diff
@@ -470,16 +515,53 @@ func writeIfChanged(prefix string, path string, yaml []byte) error {
...
 }
 
-// prepareDeploymentForDebug alter controller deployments for working nicely with delve debugger;
-// most specifically, liveness and readiness probes are dropper and leader election turned off.
-func prepareDeploymentForDebug(prefix string, objs []unstructured.Unstructured) error {
+// prepareDeploymentCommandAndArgs sets the default Command and Args for the manager container.
+// extraArgs comes from the extra_args field in the tilt-settings file and are appended to the pre-existing ones.
+// This has the affect that if there are args already set in the manager Deployment the given ones via extra_args will
+// take precedence.
+func prepareDeploymentCommandAndArgs(prefix string, objs []unstructured.Unstructured, extraArgs extraArgs) error {
```
Comment (johannesfrey) [inline hack/tools/tilt-prepare/main.go:522]: Should the call to `prepareDeploymentForDebug` and `prepareDeploymentForObservability` move inside this new func?

File: hack/tools/tilt-prepare/main.go [hunk 5]
```diff
@@ -72,8 +75,23 @@ var (
...
+	Continue     *bool `json:"continue"`
+	Port         int   `json:"port"`
+	ProfilerPort int   `json:"profiler_port"`
+	MetricsPort  int   `json:"metrics_port"`
+}
+
+type extraArgs []string
+
+type tiltSettings struct {
+	Debug     map[string]*debugConfig `json:"debug,omitempty"`
```
Comment (johannesfrey) [inline hack/tools/tilt-prepare/main.go:91]: Make provider keys real types vs map[string]? Potential downside of former: We have to hard-code and keep up with all external providers?!

File: Tiltfile (hunk 1 above)
Comment (sbueringer) [reply Tiltfile:235]: I think the "local" port has to be configurable as it is today. I think it's fine to hard-code the "server-side" port (as it is today)

File: Tiltfile [hunk 6]
```diff
@@ -248,21 +242,13 @@ def enable_provider(name, debug):
 
     if profiler_port != 0:
         port_forwards.append(port_forward(profiler_port, 6060))
-        entrypoint.extend(["--profiler-address", ":6060"])
         links.append(link("http://localhost:" + str(profiler_port) + "/debug/pprof", "profiler"))
 
-    # Set up an image build for the provider. The live update configuration syncs the output from the local_resource
-    # build into the container.
```
Comment (sbueringer) [inline Tiltfile:255]: nit: I think we want to keep the comment as it actually belong to the docker-build below

File: hack/tools/tilt-prepare/main.go (hunk 5 above)
Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go:91]: We can't keep up with external providers as some of them are not public and should still be supported :)

So I think a string as key is totally fine.

File: hack/tools/tilt-prepare/main.go [hunk 7]
```diff
@@ -72,8 +75,23 @@ var (
...
+type debugConfig struct {
+	Continue     *bool `json:"continue"`
+	Port         int   `json:"port"`
+	ProfilerPort int   `json:"profiler_port"`
+	MetricsPort  int   `json:"metrics_port"`
+}
+
+type extraArgs []string
+
+type tiltSettings struct {
```
Comment (sbueringer) [inline hack/tools/tilt-prepare/main.go:90]: nit: let's "topology-sort" the structs, i.e. let's move debugConfig and extraArgs below tiltSettings

File: hack/tools/tilt-prepare/main.go [hunk 8]
```diff
@@ -72,8 +75,23 @@ var (
...
 	providersBuildsFlag  = pflag.StringSlice("providers", []string{}, "list of providers to be installed; each value should be in the form name:path[:debug]")
 	allowK8SContextsFlag = pflag.StringSlice("allow-k8s-contexts", []string{}, "Specifies that Tilt is allowed to run against the specified k8s context name; Kind is automatically allowed")
+	tiltSettingsFileFlag = pflag.String("tilt-settings-file", "", "Path to a tilt-settings.(json|yaml) file")
 )
 
+type debugConfig struct {
+	Continue     *bool `json:"continue"`
+	Port         int   `json:"port"`
+	ProfilerPort int   `json:"profiler_port"`
+	MetricsPort  int   `json:"metrics_port"`
```
Comment (sbueringer) [inline hack/tools/tilt-prepare/main.go:85]: I would suggest making them all pointers to signal that they are optional, and then we can just check for nil to detect if they are set or not

File: hack/tools/tilt-prepare/main.go [hunk 9]
```diff
@@ -106,13 +124,29 @@ func main() {
 
 	ctx := ctrl.SetupSignalHandler()
 
+	f, err := os.Open(*tiltSettingsFileFlag)
```
Comment (sbueringer) [inline hack/tools/tilt-prepare/main.go:127]: nit: let's move l.127-141 into a separate func like `readTiltSettings`.

File: hack/tools/tilt-prepare/main.go (hunk 3 above)
Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go:227]: Yes.
This comes down to handling the configuration directly here instead of partially parsing it in the Tiltfile and then handing information over. So just handling the config here is a lot better.

File: hack/tools/tilt-prepare/main.go [hunk 10]
```diff
@@ -193,12 +227,19 @@ func tiltResources(ctx context.Context) error {
 		if len(pValues) == 3 && pValues[2] == "debug" {
 			debug = true
 		}
-		tasks[name] = providerTask(fmt.Sprintf("%s/config/default", path), fmt.Sprintf("%s.provider.yaml", name), debug)
+		setDebugConfigDefaults(ts.Debug[name])
```
Comment (sbueringer) [inline hack/tools/tilt-prepare/main.go:230]: Let's call this func in the new readTiltSettings func

File: hack/tools/tilt-prepare/main.go [hunk 11]
```diff
@@ -72,8 +75,23 @@ var (
...
+	Port         int   `json:"port"`
+	ProfilerPort int   `json:"profiler_port"`
+	MetricsPort  int   `json:"metrics_port"`
+}
+
+type extraArgs []string
+
+type tiltSettings struct {
+	Debug     map[string]*debugConfig `json:"debug,omitempty"`
+	ExtraArgs map[string]extraArgs    `json:"extra_args,omitempty"`
```
Comment (sbueringer) [inline hack/tools/tilt-prepare/main.go:92]: Additional note: I wonder if *debugConfig should be `debugConfig` we can always take the pointer of a map entry if we want to hand it over to funcs as a pointer
(I think I would do this consistently for debugConfig and extraArgs)

File: hack/tools/tilt-prepare/main.go (hunk 4 above)
Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go:522]: In my opinion we're at a point were it would be better if we have just one func which modifies the Deployment (but let's keep the updateDeployment util)

File: hack/tools/tilt-prepare/main.go (hunk 2 above)
Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go:552]: I think we don't have to. Making it configurable would just make it more complex. We only have to live with the dependency between the Tiltfile and tilt-prepare. But I would prefer that.

**Review by sbueringer — COMMENTED** [review]
I think this goes into the right direction.

Added a few answers / nits.

I would take a closer look at the command / args logic once it's "unified" in a single func.

File: hack/tools/tilt-prepare/main.go (hunk 11 above)
Comment (johannesfrey) [reply hack/tools/tilt-prepare/main.go:92]: AFAIK you cannot take a pointer to an element of a map in go (`cannot take the address of ...`). So if we going to set defaults in the structs inside the map those should be pointers. I'm also for consistency but a pointer to a string slice here also feels kinda weird :thinking:

Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go:92]: Okay, let's tackle the other things first, then I'll take a closer look what we can do here :).

It just seems strange to me that debugConfig is a pointer here, given that the map entry just shouldn't exist if there's no debugConfig for a specific provider. I get why the fields of debugConfig are pointers (and I agree) but I don't think debugConfig as map value should be a pointer.

File: hack/tools/tilt-prepare/main.go [hunk 12]
```diff
@@ -470,62 +526,68 @@ func writeIfChanged(prefix string, path string, yaml []byte) error {
...
-					args = append(args, "--metrics-bind-addr=0.0.0.0:8080")
+					finalArgs = append(finalArgs, "--metrics-bind-addr=0.0.0.0:8080")
 					continue
 				}
-				args = append(args, a)
+				finalArgs = append(finalArgs, a)
 			}
-			container.Args = args
 
-			container.Ports = append(container.Ports, corev1.ContainerPort{
```
Comment (johannesfrey) [inline hack/tools/tilt-prepare/main.go:524]: Don't delete Ports...

File: hack/tools/tilt-prepare/main.go (hunk 11 above)
Comment (johannesfrey) [reply hack/tools/tilt-prepare/main.go]: I changed it so that debugConfig is not a pointer anymore.

File: hack/tools/tilt-prepare/main.go (hunk 4 above)
Comment (johannesfrey) [reply hack/tools/tilt-prepare/main.go]: I put everything into one func.

File: hack/tools/tilt-prepare/main.go (hunk 11 above)
Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go]: Let's resolve for now

File: hack/tools/tilt-prepare/main.go [hunk 13]
```diff
@@ -470,62 +527,73 @@ func writeIfChanged(prefix string, path string, yaml []byte) error {
...
-			container.ReadinessProbe = nil
+			cmd := []string{"sh", "/start.sh", "/manager"}
+			args := append(container.Args, []string(ts.ExtraArgs[name])...)
 
-			// Drop leader election.
-			debugArgs := make([]string, 0, len(container.Args))
-			for _, a := range container.Args {
-				if a == "--leader-elect" || a == "--leader-elect=true" {
-					continue
+			// alter controller deployments for working nicely with delve debugger;
```
Comment (johannesfrey) [inline hack/tools/tilt-prepare/main.go:546]:
```suggestion
			// alter controller deployment for working nicely with delve debugger;
```

File: hack/tools/tilt-prepare/main.go [hunk 14]
```diff
@@ -70,10 +73,25 @@ var (
...
-	providersBuildsFlag  = pflag.StringSlice("providers", []string{}, "list of providers to be installed; each value should be in the form name:path[:debug]")
+	providersBuildsFlag  = pflag.StringSlice("providers", []string{}, "list of providers to be installed; each value should be in the form name:path")
 	allowK8SContextsFlag = pflag.StringSlice("allow-k8s-contexts", []string{}, "Specifies that Tilt is allowed to run against the specified k8s context name; Kind is automatically allowed")
+	tiltSettingsFileFlag = pflag.String("tilt-settings-file", "", "Path to a tilt-settings.(json|yaml) file")
 )
 
+type tiltSettings struct {
+	Debug     map[string]debugConfig `json:"debug,omitempty"`
+	ExtraArgs map[string]extraArgs   `json:"extra_args,omitempty"`
+}
```
Comment (fabriziopandini) [inline hack/tools/tilt-prepare/main.go:84]: I'm fine with this as a first iteration, but let's open an issue about reading more information from the tilt file and dropping corresponding flags:
- allow-k8s-contexts
- cert-manager
- kustomize_build_arg 
- providers

File: hack/tools/tilt-prepare/main.go [hunk 15]
```diff
@@ -184,21 +227,43 @@ func tiltResources(ctx context.Context) error {
...
+			return errors.Errorf("[resources] failed to parse --provider flag %s: value should be in the form of name:path", p)
 		}
 		name := pValues[0]
 		path := pValues[1]
-		debug := false
-		if len(pValues) == 3 && pValues[2] == "debug" {
-			debug = true
-		}
-		tasks[name] = providerTask(fmt.Sprintf("%s/config/default", path), fmt.Sprintf("%s.provider.yaml", name), debug)
+		tasks[name] = providerTask(name, fmt.Sprintf("%s/config/default", path), setDebugDefaults(ts))
```
Comment (fabriziopandini) [inline hack/tools/tilt-prepare/main.go:235]: What about moving the call to `setDebugDefaults` into `readTiltSettings`, so the latter returns a ready-to-use object?

**Review by fabriziopandini — COMMENTED** [review]
@johannesfrey thanks for this PR, it is a nice cleanup and enables more in the future!

File: hack/tools/tilt-prepare/main.go (hunk 15 above)
Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go:235]: +1

File: hack/tools/tilt-prepare/main.go (hunk 14 above)
Comment (johannesfrey) [reply hack/tools/tilt-prepare/main.go:84]: Sure, I will open an issue for this.

File: hack/tools/tilt-prepare/main.go (hunk 15 above)
Comment (johannesfrey) [reply hack/tools/tilt-prepare/main.go]: Absolutely. Changed it accordingly.

File: hack/tools/tilt-prepare/main.go (hunk 14 above)
Comment (johannesfrey) [reply hack/tools/tilt-prepare/main.go:84]: See: https://github.com/kubernetes-sigs/cluster-api/issues/6246

Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go:84]: I wonder if we should additionally either hard-code tools, or set `kustomize,envsubst` as default value. 

I'm not sure it has value that this is configurable from the outside. We always need kustomize and envsubst when we want to deploy a provider (which is always).

If we assume that other folks might want to build additional tools, we can keep the flag and just set a default value.

Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go:84]: Just an idea for another follow-up. Now that we're going into the direction of having a fully specified config file, should we add an example tilt settings file which we can refer to in the documentation?

I always found it very useful for golangci-lint: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml

Looking at our tilt documentation we now have a lot of configuration fields, and I think a well-documented example could be very useful.

(I can open a PR and take my local tilt-settings + documentation comments as basis)

WDYT?

Comment (johannesfrey) [reply hack/tools/tilt-prepare/main.go:84]: Yes, it looks like `tools_arg` is hard-coded to `kustomize,envsubst` in the Tiltfile, as it is not read anywhere there via e.g. `settings.get`. The only way to set this is if you call tilt-prepare directly.

Comment (johannesfrey) [reply hack/tools/tilt-prepare/main.go:84]: > Just an idea for another follow-up. Now that we're going into the direction of having a fully specified config file, should we add an example tilt settings file which we can refer to in the documentation?
> 
> I always found it very useful for golangci-lint: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
> 
> Looking at our tilt documentation we now have a lot of configuration fields, and I think a well-documented example could be very useful.
> 
> (I can open a PR and take my local tilt-settings + documentation comments as basis)
> 
> WDYT?

Sounds good :+1:

File: hack/tools/tilt-prepare/main.go [hunk 16]
```diff
@@ -106,19 +124,73 @@ func main() {
...
+	return setDebugDefaults(ts), nil
+}
+
+// setDebugDefaults sets default values for debug related fields in tiltSettings.
+func setDebugDefaults(ts tiltSettings) tiltSettings {
+	for k := range ts.Debug {
+		if _, ok := ts.Debug[k]; !ok {
+			continue
+		}
+
```
Comment (sbueringer) [inline hack/tools/tilt-prepare/main.go:173]:
```suggestion
```

nit, I think this can never happen. When we loop over the keys of a map they will always exist in the map

File: hack/tools/tilt-prepare/main.go [hunk 17]
```diff
@@ -106,19 +124,73 @@ func main() {
...
+		return tiltSettings{}, errors.Wrap(err, fmt.Sprintf("failed to open tilt-settings file for path: %s", path))
+	}
+	defer f.Close()
+
+	data, err := io.ReadAll(f)
+	if err != nil {
+		return tiltSettings{}, errors.Wrap(err, "failed to read tilt-settings content")
+	}
+
+	ts := tiltSettings{}
```
Comment (sbueringer) [inline hack/tools/tilt-prepare/main.go:159]: Have we considered making this a pointer?

Then we can just return nil in the other return statements and also pass it to `setDebugDefaults` so the call to `setDebugDefaults` won't copy the struct. (and setDebugDefaults doesn't need a return value, cf. `PopulateDefaultsMachineDeployment`)

**Review by sbueringer — COMMENTED** [review]
Thank you very much!

Last round of nits from my side.

I also tested it locally with essentially all possible configurations enabled and it works as expected!

File: hack/tools/tilt-prepare/main.go (hunk 17 above)
Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go]: Thx!

**Comment by fabriziopandini** [comment]
yay!
/lgtm
/approve
