### PR TITLE
🐛 Bump to docker v24.0.5-0.20230714235725-36e9e796c6fc

### LINKED ISSUE #9037: CAPD does not work when compiled with Go 1.20.6
I had a Docker update on 13.07 which updated to Docker 24.0.4. I realized today that CAPD doesn't work anymore with that

Basically the exec is broken:

```bash
{"ts":1689947751414.039,"caller":"controller/controller.go:324","msg":"Reconciler error","controller":"dockermachine","controllerGroup":"infrastructure.cluster.x-k8s.io","controllerKind":"DockerMachine","DockerMachine":{"name":"capi-quickstart-control-plane-5w5mn","namespace":"default"},"namespace":"default","name":"capi-quickstart-control-plane-5w5mn","reconcileID":"dfd6131e-27c0-4533-b92f-010233980f40","err":"failed to update DockerCluster.loadbalancer configuration: failed to create directory /usr/local/etc/haproxy/haproxy.cfg: error attaching to container exec: http: invalid Host header"}
```

I found some similar reports:
* https://github.com/nektos/act/issues/1908
* https://github.com/moby/moby/issues/45935

I would suggest like described there to bump to github.com/docker/docker v24.0.5-0.20230714235725-36e9e796c6fc+incompatible to fix the issue.

I think it would be also good to backport this to all release branches. Otherwise I would expect that CAPD will just stop working as soon as folks update Docker.

As soon as Docker v24.0.5 is released we should bump to the release

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9037

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

File: hack/tools/tilt-prepare/main.go [hunk 1]
```diff
@@ -604,12 +602,7 @@ func cleanupChartTask(path string) taskFunction {
 
 				helmChartVersion := helmChart.Version
 				if helmChartVersion == "" {
-					// If helmChart.Version is not set lookup the latest version.
-					helmChartVersion, err = resolveLatestHelmChartVersion(ctx, helmChart.Repo, helmChart.Name)
-					if err != nil {
-						return err
-					}
-					klog.Infof("[%s] resolved latest Helm Chart version to %q\n", prefix, helmChartVersion)
+					return errors.New("Helm Chart version must be set")
```
Comment (sbueringer) [inline hack/tools/tilt-prepare/main.go:605]: I had to get rid of the helm dependency as it's not compatible with the new docker/docker version (because they both depend on incompatible versions of oras.land/oras-go

We previously used this code to pull latest Helm Chart versions. But we stopped using that to have a stable dev environment.

I think it's fine to drop this code as we don't want to go back to a dev-env that can break any day when new Helm Charts are released.

**Review by vincepri — APPROVED** [review]
/approve

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by killianmuldoon** [comment]
I can do the cherry-picks for 1.5 and 1.4 - wondering if we should cherry-pick to 1.3 given we won't have another release until after next tuesday. That would leave the final release on a commit :thinking:

**Comment by sbueringer** [comment]
@killianmuldoon I think it's okay. Rather a commit that works vs what we currently have.

Would be great if you can open the cherry-picks

File: hack/tools/tilt-prepare/main.go (hunk 1 above)
Comment (CecileRobertMichon) [reply hack/tools/tilt-prepare/main.go:605]: @Jont828 fyi

**Comment by CecileRobertMichon** [comment]
belated lgtm

/lgtm

File: hack/tools/tilt-prepare/main.go (hunk 1 above)
Comment (Jont828) [reply hack/tools/tilt-prepare/main.go:605]: @sbueringer So just to clarify, would that break using the visualizer app with Tilt, or would we still be good to use it as we are now?

Comment (sbueringer) [reply hack/tools/tilt-prepare/main.go:605]: This does not break the visualizer app.

The consequence is just that we always have to set a helm chart version in our kustomization.yamls. But we already do this everywhere for our own sanity, e.g. https://github.com/kubernetes-sigs/cluster-api/blob/e5db021e59d38f916684c2bd8f374dde7805cf9e/hack/observability/visualizer/kustomization.yaml#L10

Before this PR we could have left the version unset and tilt-prepare would have automatically pulled latest

Comment (mboersma) [reply hack/tools/tilt-prepare/main.go:605]: CAPZ has deeper integration with Helm, and it's not possible to remove those imports.

@sbueringer do you have any ideas about how to work around this `no export data for "oras.land/oras-go/pkg/auth/docker"` problem caused by importing both Docker and Helm? I've been trying a variety of approaches but no luck so far, and it's preventing CAPZ from adopting CAPI v1.4.5 and v1.5.0.
