### PR TITLE
🐛 Machine controller should expect bootstrap data only in secret

### LINKED ISSUE #2363: bootstrap.DataSecretName isn't reconciled if bootstrap.Data is set
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
- apply v1alpha3 yaml to v1alpha2 cluster
- machines generally look okay
- CAPA controller upset because `dataSecretName` is not being set, so it's continuously reconciling AWSMachines, etc

**What did you expect to happen:**
1. CABPK controller converts all bootstrapDatas to secrets (this does happen)
2. CAPI controller keeps (or removes?) bootstrap.Data in Machine objects and sets the bootstrap.DataSecretName appropriately (this does not happen)
3. CAPA controller sees the new DataSecretName and happily reconciles

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Conversely, we could tell CAPA controller to continue to respect bootstrap.Data, but that seems backwards as we're trying to deprecate that field. 

I think we may want to do something with the early return here:
https://github.com/kubernetes-sigs/cluster-api/blob/27a6031a1d6aa1a310c905b7d1afa331ab1cfd2d/controllers/machine_controller_phases.go#L165-L169

**Environment:**

- Cluster-api version: master
- Minikube/KIND version: 0.7.0
- Kubernetes version: (use `kubectl version`): 1.16.2
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

/kind bug

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

This PR changes the machine controller behavior when looking at external bootstrap resources. In particular, it only considers the bootstrap resource ready if `DataSecretName` is set.

It also makes sure to wipe out any plaintext data that we might have stored.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2363

### CODE REVIEW

**Comment by vincepri** [comment]
Found a few other issues with unstructured objects and timestamps, and an issue where the bootstrap config could be causing an NPE if there was no reference

**Comment by vincepri** [comment]
@rudoi @detiber ptal

**Comment by detiber** [comment]
lgtm

**Comment by rudoi** [comment]
/lgtm
thanks for this!

File: controllers/cluster_controller.go [hunk 1]
```diff
@@ -247,7 +247,7 @@ func (r *ClusterReconciler) reconcileDelete(ctx context.Context, cluster *cluste
 				continue
 			}
 
-			if !accessor.GetDeletionTimestamp().IsZero() {
+			if accessor.GetDeletionTimestamp() != nil && !accessor.GetDeletionTimestamp().IsZero() {
```
Comment (ncdc) [inline controllers/cluster_controller.go]: Technically don't need a nil check here, as a nil metav1.Time returns the proper true value for IsZero

Comment (ncdc) [reply controllers/cluster_controller.go]: Ditto for the other similar changes

Comment (vincepri) [reply controllers/cluster_controller.go]: That's true for typed objects, but when using unstructured https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/unstructured/unstructured.go#L360

Comment (ncdc) [reply controllers/cluster_controller.go]: It's the same for unstructured (don't need a nil check) unless I'm missing something? https://github.com/kubernetes/apimachinery/blob/2373d029717c4d169463414a6127cd1d0d12680e/pkg/apis/meta/v1/time.go#L61-L63

Comment (vincepri) [reply controllers/cluster_controller.go]: The metav1.Time type behaves properly, it's the `GetDeletionTimestamp` method that returns nil https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/unstructured/unstructured.go#L363-L365

Comment (ncdc) [reply controllers/cluster_controller.go]: Still fine: it return's a `(*metav1.Time)(nil)`: https://play.golang.org/p/3G463erHe4z
