### PR TITLE
🐛 patch managed fields after `clusterctl move` so that it does not own all fields

### LINKED ISSUE #7473: clusterctl move takes ownership of all fields
As the title says when using clusterctl move, clusterctl owns all fields after the move.

Steps to reproduce
* Create a mgmt cluster (Cluster A)
* Deploy a workload cluster (Cluster B)
* Make the workload cluster (Cluster B) a mgmt cluster
* clusterctl move from Cluster A to Cluster B

```yaml
$ kubectl --kubeconfig self-hosted.kubeconfig get cluster docker-cluster-self-hosted --show-managed-fields -o yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  managedFields:
  - apiVersion: cluster.x-k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:cluster.x-k8s.io/cluster-name: {}
          f:topology.cluster.x-k8s.io/owned: {}
      f:spec:
        f:controlPlaneRef: {}
        f:infrastructureRef: {}
    manager: capi-topology
    operation: Apply
    time: "2022-10-31T18:03:17Z"
  - apiVersion: cluster.x-k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:finalizers:
          .: {}
          v:"cluster.cluster.x-k8s.io": {}
        f:labels:
          .: {}
          f:cluster.x-k8s.io/cluster-name: {}
          f:topology.cluster.x-k8s.io/owned: {}
      f:spec:
        .: {}
        f:clusterNetwork:
          .: {}
          f:pods:
            .: {}
            f:cidrBlocks: {}
          f:serviceDomain: {}
          f:services:
            .: {}
            f:cidrBlocks: {}
        f:controlPlaneEndpoint:
          .: {}
          f:host: {}
          f:port: {}
        f:controlPlaneRef: {}
        f:infrastructureRef: {}
        f:paused: {}
...
    manager: clusterctl
    operation: Update
    time: "2022-10-31T18:03:16Z"
  name: docker-cluster-self-hosted
```

The consequence of that issue is that
* From now on `kubectl apply` or other clients (e.g. the Cluster topology controller) won't be able to remove fields without explicitly taking ownership first by setting fields to a different value.
* Similarly `kubectl apply  --server-side=true` won't be able to change field values except if `--force-conflicts` is used.

I think we have to fix this. My suggestion is to modify `clusterctl move` so that the managed fields are not changed during the move.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

This PR patches the managed fields so that clusterctl does not own all the fields in the object.
Note: The last step of `move` is unpausing the cluster. So clusterctl still ownes the `.spec.paused` field on the Clusters and the `cluster.x-k8s.io/paused` annotation on the ClusterClasses. 
So if someone tries to unpause the cluster using SSA it will throw a conflict. 
```
❯ k --kubeconfig docker-cluster-one.kubeconfig apply -f cluster-unpuase.yaml --server-side=true
error: Apply failed with 1 conflict: conflict with "clusterctl" using cluster.x-k8s.io/v1beta1: .spec.paused
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
```

TODO: 
- [ ] Unit ( out unit tests in move use fake client which do not have managed fields to begin with so I am not sure how to unit test this where the test is meaningful)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7473

### CODE REVIEW

File: cmd/clusterctl/client/cluster/mover.go [hunk 1]
```diff
@@ -17,6 +17,7 @@ limitations under the License.
 package cluster
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/mover.go:18]: @ykakarap 
Regarding

> Note: The last step of move is unpausing the cluster. So clusterctl still ownes the .spec.paused field on the Clusters > and the cluster.x-k8s.io/paused annotation on the ClusterClasses.
> So if someone tries to unpause the cluster using SSA it will throw a conflict.

Let's change the code in setClusterPause

```go
	patchValue := "true"
	if !value {
		patchValue = "null"
	}
	patch := client.RawPatch(types.MergePatchType, []byte(fmt.Sprintf("{\"spec\":{\"paused\":%s}}", patchValue)))
```

This way we unset the paused field which does the same semantically but by unsetting clusterctl also drops the ownership of the field.

Comment (sbueringer) [reply cmd/clusterctl/client/cluster/mover.go:18]: I didn't see any ownership of the annotation in ClusterClass after move

**Comment by sbueringer** [comment]
> Unit ( out unit tests in move use fake client which do not have managed fields to begin with so I am not sure how to unit test this where the test is meaningful)

Can we do this by extending our self_hosted e2e test instead?

Basically we should check e.g. the Cluster & ClusterClass that clusterctl doesn't own any fields (after "Moving the cluster to self hosted")

I would be totally fine with doing this in a follow-up PR to get this bugfix in time for the next v1.3 beta and v1.2.5

File: cmd/clusterctl/client/cluster/mover.go (hunk 1 above)
Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/mover.go:18]: I don't think this is necessary, or at least not for the PR we are going to backport (that should be minimal)
If people want to patch this field using SSA they can force an override

File: cmd/clusterctl/client/cluster/mover.go [hunk 2]
```diff
@@ -1189,3 +1195,17 @@ func (o *objectMover) checkTargetProviders(toInventory InventoryClient) error {
 
 	return kerrors.NewAggregate(errList)
 }
+
+// patchTopologyManagedFields patches the managed fields of obj.
+// Without patching the managed fields, clusterctl would be the owner of the fields
+// which would lead to co-ownership and also additional machine rollouts.
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/mover.go:1201]:
```suggestion
// which would lead to co-ownership preventing other controllers using SSA from deleting fields.
```

**Comment by fabriziopandini** [comment]
Only one nit from my side
+1 to test this by extending our self_hosted e2e test in a follow up PR (unit testing this with fake client isn't possible)

File: cmd/clusterctl/client/cluster/mover.go (hunk 1 above)
Comment (sbueringer) [reply cmd/clusterctl/client/cluster/mover.go:18]: The problem is they have to do it whenever they want to set the pause field with SSA. which I guess will be default sooner or later with kubectl.

If we don't fix it now every Cluster moved from now on will still have clusterctl as owner of the paused field.

**Comment by ykakarap** [comment]
+1 to covering this in E2E tests.

File: cmd/clusterctl/client/cluster/mover.go (hunk 1 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/mover.go:18]: +1 to address this in the current PR.

**Comment by ykakarap** [comment]
Opened an issue to track the E2E work: https://github.com/kubernetes-sigs/cluster-api/issues/7510

**Comment by sbueringer** [comment]
/cherry-pick release-1.2
(bugfix)
