### PR TITLE
⚠️   clusterctl init: wait for deployments to be ready

### LINKED ISSUE #4474: clusterctl doesn't wait for deployments to be available
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

```
➜  ~ clusterctl init --infrastructure azure
Fetching providers
Installing cert-manager Version="v1.1.0"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.15" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.15" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.15" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-azure" Version="v0.4.13" TargetNamespace="capz-system"

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl config cluster [name] --kubernetes-version [version] | kubectl apply -f -

➜  ~ kubectl get pods -A
NAMESPACE                           NAME                                                             READY   STATUS              RESTARTS   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-59fcb99846-26shx       2/2     Running             0          106s
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-d6598bf4-wx6ss     2/2     Running             0          99s
capi-system                         capi-controller-manager-886c77fc7-hqq8l                          2/2     Running             0          110s
capi-webhook-system                 capi-controller-manager-575f7b6c8-mqrlh                          0/2     ContainerCreating   0          2m37s
capi-webhook-system                 capi-kubeadm-bootstrap-controller-manager-7fb76bc9b9-ncn7h       0/2     ContainerCreating   0          109s
capi-webhook-system                 capi-kubeadm-control-plane-controller-manager-6769d967bc-bk2hf   0/2     ContainerCreating   0          104s
capi-webhook-system                 capz-controller-manager-7fd987564d-64t75                         0/2     ContainerCreating   0          90s
capz-system                         capz-controller-manager-69bc66d65c-jl779                         0/2     ContainerCreating   0          14s
capz-system                         capz-nmi-xdhr4                                                   0/1     ContainerCreating   0          14s
cert-manager                        cert-manager-86cb5dcfdd-5hk86                                    1/1     Running             0          3m12s
cert-manager                        cert-manager-cainjector-84cf775b89-nxncz                         1/1     Running             1          3m12s
cert-manager                        cert-manager-webhook-5d5dc765f6-wwjpv                            1/1     Running             1          3m11s
kube-system                         coredns-74ff55c5b-6kjs4                                          1/1     Running             0          4m18s
kube-system                         coredns-74ff55c5b-spd6g                                          1/1     Running             0          4m18s
kube-system                         etcd-kind-control-plane                                          1/1     Running             0          4m24s
kube-system                         kindnet-pbg66                                                    1/1     Running             0          4m18s
kube-system                         kube-apiserver-kind-control-plane                                1/1     Running             0          4m24s
kube-system                         kube-controller-manager-kind-control-plane                       1/1     Running             0          4m24s
kube-system                         kube-proxy-m9n69                                                 1/1     Running             0          4m18s
kube-system                         kube-scheduler-kind-control-plane                                1/1     Running             0          4m24s
local-path-storage                  local-path-provisioner-78776bfc44-zfhv6                          1/1     Running             0          4m18s
➜  ~ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.15", GitCommit:"b900c6f89f3d433c32db1aa269f77f004a83cc4f", GitTreeState:"clean", BuildDate:"2021-03-30T16:14:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
➜  ~ k get deploy -A
NAMESPACE                           NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager       1/1     1            1           2m39s
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager   1/1     1            1           2m32s
capi-system                         capi-controller-manager                         1/1     1            1           2m43s
capi-webhook-system                 capi-controller-manager                         0/1     1            0           3m30s
capi-webhook-system                 capi-kubeadm-bootstrap-controller-manager       1/1     1            1           2m42s
capi-webhook-system                 capi-kubeadm-control-plane-controller-manager   1/1     1            1           2m37s
capi-webhook-system                 capz-controller-manager                         0/1     1            0           2m23s
capz-system                         capz-controller-manager                         0/1     1            0           67s
cert-manager                        cert-manager                                    1/1     1            1           4m5s
cert-manager                        cert-manager-cainjector                         1/1     1            1           4m5s
cert-manager                        cert-manager-webhook                            1/1     1            1           4m4s
kube-system                         coredns                                         2/2     2            2           5m24s
local-path-storage                  local-path-provisioner                          1/1     1            1           5m19s
```

**What did you expect to happen:** I would expect clusterctl init not to return until all CAPI provider deployments are Available. I need to check but I'm pretty sure this was the case with previous versions of clusterctl, has there been a regression? This is with clusterctl `v0.3.15`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:
`clusterctl init` should wait for the cluster to be 'ready' before exiting.
This includes:
- [x] All the CAP* deployments should be ready
- [ ] ~All the CAP* services should be ready~ (NOT implementing this - kind of addressed in https://github.com/kubernetes-sigs/cluster-api/pull/4989)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4474

### CODE REVIEW

File: cmd/clusterctl/client/cluster/installer.go [hunk 1]
```diff
@@ -82,6 +95,12 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
 	inventoryObject := components.InventoryObject()
 
 	log.V(1).Info("Creating objects", "Provider", components.ManifestLabel(), "Version", components.Version(), "TargetNamespace", components.TargetNamespace())
+	// log.Info("Installing the follow objects:")
+	// for _, obj := range components.Objs() {
+	// 	if obj.GroupVersionKind().Kind == "Deployment" {
+	// 		log.Info(fmt.Sprintf("-------\nname: %v\ngvk: %+v\nnamespace: %v\n", obj.GetName(), obj.GroupVersionKind(), obj.GetNamespace()))
+	// 	}
+	// }
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/installer.go:103]: Left over?

File: cmd/clusterctl/client/cluster/installer.go [hunk 2]
```diff
@@ -90,6 +109,58 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
...
+// waitForReady waits till the installed components are ready.
+func (i *providerInstaller) waitForReady() error {
+	log := logf.Log
+	log.Info("Waiting for providers to be available...")
+
+	if err := i.waitDeploymentsReady(); err != nil {
+		return err
+	}
+
+	// check for services too?
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/installer.go:121]: If this could provide an additional protection from deployment being started but web hooks not yet ready to answer, I'm +1 (Probably worth to dig into controller runtime startup sequence before committing to it)

File: cmd/clusterctl/client/cluster/installer.go [hunk 3]
```diff
@@ -90,6 +109,58 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
...
+
+	return nil
+}
+
+// waitDeploymentsReady waits till the installed deployments are ready.
+func (i *providerInstaller) waitDeploymentsReady() error {
+	for _, components := range i.installQueue {
+		for _, obj := range components.Objs() {
+			if obj.GroupVersionKind().Kind == "Deployment" {
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/installer.go:130]: According to https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#controllers--watching-namespace we can eventually check for the container named manager in order to better identify the controller.

File: cmd/clusterctl/client/cluster/installer.go [hunk 4]
```diff
@@ -90,6 +109,58 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
...
+				if err := i.waitDeploymentReady(obj); err != nil {
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/installer.go:131]: Not sure if the optimisation is worth, but what about doing this in parallel (makes sense if this provides significant reduction in the overall wait time)

File: cmd/clusterctl/client/cluster/installer.go [hunk 5]
```diff
@@ -90,6 +109,58 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
...
+					return err
+				}
+			}
+		}
+	}
+	return nil
+}
+
+func (i *providerInstaller) waitDeploymentReady(deployment unstructured.Unstructured) error {
+	err := wait.Poll(500*time.Millisecond, 30*time.Second, func() (bool, error) {
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/installer.go:141]: Wondering if we should make the timeout configurable (we saw similar request for other timeouts from users working on slow environments)

**Review by fabriziopandini — COMMENTED** [review]
@ykakarap thanks for getting started this effort!

Given that this could be considered a behaviour/breaking change, IMO we should start making waiting optional adding a --wait (-w) flag which should be false by default.
WDYT?

File: cmd/clusterctl/client/cluster/installer.go (hunk 4 above)
Comment (sbueringer) [reply cmd/clusterctl/client/cluster/installer.go:131]: I think it the reduction will be < 1-2 sec. We have to wait until all deployments are ready anyway and checking them shouldn't take long.

Comment (ykakarap) [reply cmd/clusterctl/client/cluster/installer.go:131]: I thought about doing parallelizing it didnt do it because of the following reasons:
* We anyway have to wait if at least one deployment is still pending.
* If you think about it while processing this sequentially, while you are waiting for one deployment you are technically also waiting for the other deployments (waiting to check status).
  * If the other deployments are ready before we check for them the very first call we would make to check the status would return "Ready" and we can continue immediately (to Stefan's point).
* With the above 2 points having the wait be sequential will also make the code more readable without any significant loss in time.

File: cmd/clusterctl/client/cluster/installer.go (hunk 1 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/installer.go:103]: This is still a WIP PR. 
I will do a full clean up later. :)

File: cmd/clusterctl/client/cluster/installer.go (hunk 5 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/installer.go:141]: +1

File: cmd/clusterctl/client/cluster/installer.go (hunk 4 above)
Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/installer.go:131]: Thanks for context!

File: cmd/clusterctl/client/cluster/installer.go [hunk 6]
```diff
@@ -47,6 +57,12 @@ type ProviderInstaller interface {
 	Images() []string
 }
 
+// InstallOptions defines the options used to configure installation.
+type InstallOptions struct {
```
Comment (ykakarap) [inline cmd/clusterctl/client/cluster/installer.go:61]: There are 2 ways we could have done this:
**Option 1:**
 Define `InstallOptions`, as done in this PR, and pass that as an argument to the installer's `Install()` function.
 
 **Option 2:**
Add `waitProviders` and `waitProvidersTimeout` to the `providerInstaller` struct and add functions to set these properties.  This would mean we will have to modify the `ProviderInstaller` interface to add a new function that would look like `SetProviderWait(WaitOptions)`.

We will have to modify the interface in both the cases. I went with option 1 in this PR (smaller change to the interface). Looking for feedback on preference of option to go with. 
Thanks.

File: cmd/clusterctl/client/cluster/installer.go (hunk 2 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/installer.go]: With https://github.com/kubernetes-sigs/cluster-api/pull/4989 and https://github.com/kubernetes-sigs/controller-runtime/pull/1598 merged the deployment is considered ready only after the services are also ready.
Therefore checking to see if deployments are ready is enough. 

A quick check for this :
```shell 
❯ ./bin/clusterctl init --wait-providers=true -i docker && ./bin/clusterctl generate cluster capi-quickstart --flavor development --kubernetes-version v1.21.2 --control-plane-machine-count=1 --worker-machine-count=3 | k apply -f -
Fetching providers
Installing cert-manager Version="v1.4.0"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.4.0" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.4.0" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.4.0" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-docker" Version="v0.4.0" TargetNamespace="capd-system"
Waiting for providers to be available...

Your management cluster has been initialized successfully!

You can now create your first workload cluster by running the following:

  clusterctl generate cluster [name] --kubernetes-version [version] | kubectl apply -f -

cluster.cluster.x-k8s.io/capi-quickstart created
dockercluster.infrastructure.cluster.x-k8s.io/capi-quickstart created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/capi-quickstart-control-plane created
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/capi-quickstart-control-plane created
dockermachinetemplate.infrastructure.cluster.x-k8s.io/capi-quickstart-md-0 created
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/capi-quickstart-md-0 created
machinedeployment.cluster.x-k8s.io/capi-quickstart-md-0 created
```
shows that waiting for deployments is a good enough check.

Comment (sbueringer) [reply cmd/clusterctl/client/cluster/installer.go]: @ykakarap I agree that taking a look at the service won't significantly improve it. But actually the sequence should be something like:

1. CAPI controllers are deployed
2. reconciler and webhooks in CAPI controllers start
3. Pod and thus Deployments are ready after webhooks answers a net.DialTimeout successfully (i.e. they are up)
4. The kube-controller-manager adds the Pod IP to the endpoints of the service
5. kube-proxy reconciles the service (e.g. adjusts iptables to handle the new service IP => pod IP mapping correctly)

So after this PR we wait until after 3. By looking at the service we could also make sure 4 has completed, but 5 is only safe after either:
* pinging the webhook (which is imho not that easy to implement in clusterctl)
* (probably) waiting a few seconds after the Pod is ready

Imho it's fine to not add additional handling to this PR. One easy option we have if we still get user reports with this error is to add `minReadySeconds` in our controller deployments (which would have to be done by all providers)

Comment (ykakarap) [reply cmd/clusterctl/client/cluster/installer.go]: Thanks @sbueringer, for that detailed sequence of operations.
Very informational 😃

Comment (sbueringer) [reply cmd/clusterctl/client/cluster/installer.go]: Who know, when we'll need it :) (hopefully never)

File: cmd/clusterctl/client/cluster/installer.go [hunk 7]
```diff
@@ -90,6 +111,63 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
...
+		return nil
+	}
+
+	log := logf.Log
+	log.Info("Waiting for providers to be available...")
+
+	return i.waitManagerDeploymentsReady(opts)
+}
+
+// waitDeploymentsReady waits till the installed deployments are ready.
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/installer.go:128]:
```suggestion
// waitManagerDeploymentsReady waits till the installed deployments are ready.
```

File: cmd/clusterctl/client/cluster/installer.go [hunk 8]
```diff
@@ -90,6 +111,63 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
...
+				if err := i.waitDeploymentReady(obj, opts); err != nil {
+					return err
+				}
+			}
+		}
+	}
+	return nil
+}
+
+func (i *providerInstaller) waitDeploymentReady(deployment unstructured.Unstructured, opts InstallOptions) error {
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/installer.go:142]:
```suggestion
func (i *providerInstaller) waitDeploymentReady(deployment unstructured.Unstructured, timeout time.Duration) error {
```
I think I would only pass the timeout here (because it's just what we need and thus it's easier to see what the func uses)

File: cmd/clusterctl/client/cluster/installer.go [hunk 9]
```diff
@@ -90,6 +111,63 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
...
+		}
+		for _, c := range dep.Status.Conditions {
+			if c.Type == appsv1.DeploymentAvailable && c.Status == corev1.ConditionTrue {
+				return true, nil
+			}
+		}
+		return false, nil
+	})
+	if err == wait.ErrWaitTimeout {
+		log.Info(fmt.Sprintf("Timedout waiting for provider deployment %q to be ready", deployment.GetName()))
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/installer.go:165]:
```suggestion
		log.Info(fmt.Sprintf("Timed out waiting for provider deployment %q to be ready", deployment.GetName()))
```

File: cmd/clusterctl/client/cluster/installer.go [hunk 10]
```diff
@@ -90,6 +111,63 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
...
+			return false, err
+		}
+		for _, c := range dep.Status.Conditions {
+			if c.Type == appsv1.DeploymentAvailable && c.Status == corev1.ConditionTrue {
+				return true, nil
+			}
+		}
+		return false, nil
+	})
+	if err == wait.ErrWaitTimeout {
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/installer.go:164]: I wonder if we should instead do something like:
```go
if err != nil {
    return errors.Wrap(err, fmt.Sprintf("failed to wait until Deployment %s/%s is ready", deployment.GetNamespace(), deployment.GetName()))
}
return nil
```

Advantages:
* We get a nice user-facing error message (independent of what exactly fails)
* I assume (but I'm not 100% sure) when we add a log here and return an error an upper layer will (hopefully) also log the error to the user and then we would have the error twice.

File: cmd/clusterctl/client/init.go [hunk 11]
```diff
@@ -58,6 +59,12 @@ type InitOptions struct {
 	// LogUsageInstructions instructs the init command to print the usage instructions in case of first run.
 	LogUsageInstructions bool
 
+	// WaitProviders instructs the init command to wait till the providers are installed.
+	WaitProviders bool
+
+	// WaitProviderTimeout sets the timeout per provider wait installation
```
Comment (sbueringer) [inline cmd/clusterctl/client/init.go:65]:
```suggestion
	// WaitProvidersTimeout sets the timeout per provider wait installation.
```

File: cmd/clusterctl/cmd/init.go [hunk 12]
```diff
@@ -100,6 +103,10 @@ func init() {
 		"Control plane providers and versions (e.g. kubeadm:v0.3.0) to add to the management cluster. If unspecified, the Kubeadm control plane provider's latest release is used.")
 	initCmd.Flags().StringVar(&initOpts.targetNamespace, "target-namespace", "",
 		"The target namespace where the providers should be deployed. If unspecified, the provider components' default namespace is used.")
+	initCmd.Flags().BoolVar(&initOpts.waitProviders, "wait-providers", false,
+		"Wait for providers to be installed.")
+	initCmd.Flags().IntVar(&initOpts.waitProvidersTimeout, "wait-providers-timeout", 30,
```
Comment (sbueringer) [inline cmd/clusterctl/cmd/init.go:108]:
```suggestion
	initCmd.Flags().DurationVar(&initOpts.waitProvidersTimeout, "wait-providers-timeout", "30s",
```

File: cmd/clusterctl/internal/util/objs.go [hunk 13]
```diff
@@ -173,3 +174,20 @@ func fixContainersImage(containers []corev1.Container, alterImageFunc func(image
...
+		var dep appsv1.Deployment
+		if err := runtime.DefaultUnstructuredConverter.FromUnstructured(obj.UnstructuredContent(), &dep); err != nil {
+			return false
+		}
+		for _, c := range dep.Spec.Template.Spec.Containers {
+			if c.Name == controllerContainerName {
+				return true
+			}
+		}
+		return false
```
Comment (sbueringer) [inline cmd/clusterctl/internal/util/objs.go:190]:
```suggestion
```
nit (if you want)

File: cmd/clusterctl/client/cluster/installer.go (hunk 6 above)
Comment (sbueringer) [reply cmd/clusterctl/client/cluster/installer.go:61]: I think Option 1 is fine. Seems to also be a frequently used pattern around here. It also makes it easier to add new options in the future.

File: cmd/clusterctl/client/cluster/installer.go [hunk 14]
```diff
@@ -90,6 +111,63 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
 	return providerInventory.Create(inventoryObject)
 }
 
+// waitForReady waits till the installed components are ready.
+func (i *providerInstaller) waitForReady(opts InstallOptions) error {
+	// If we dont have to wait for providers to be installed
+	// return early.
+	if !opts.WaitProviders {
+		return nil
+	}
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/installer.go:120]: What about moving this into Install so we can avoid to have `waitForReady` as a wrapper for `waitManagerDeploymentsReady`

File: cmd/clusterctl/client/cluster/installer.go (hunk 7 above)
Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/installer.go:128]: I would suggest to use waitForProvidersReady, because it provides sense of what we are achieving without surfacing how we are doing this (which might change in the future)

File: cmd/clusterctl/cmd/init.go (hunk 12 above)
Comment (fabriziopandini) [reply cmd/clusterctl/cmd/init.go:108]: Let set this to 5minutes, so we account for slow machines/network

File: cmd/clusterctl/internal/util/objs.go [hunk 15]
```diff
@@ -173,3 +174,20 @@ func fixContainersImage(containers []corev1.Container, alterImageFunc func(image
 	}
 	return nil
 }
+
+// IsManagerDeployment return true if obj represents a manager deployment.
+func IsManagerDeployment(obj unstructured.Unstructured) bool {
```
Comment (fabriziopandini) [inline cmd/clusterctl/internal/util/objs.go:179]:
```suggestion
func IsDeploymentWithManager(obj unstructured.Unstructured) bool {
```

File: cmd/clusterctl/internal/util/objs.go [hunk 16]
```diff
@@ -173,3 +174,20 @@ func fixContainersImage(containers []corev1.Container, alterImageFunc func(image
 	}
 	return nil
 }
+
+// IsManagerDeployment return true if obj represents a manager deployment.
```
Comment (fabriziopandini) [inline cmd/clusterctl/internal/util/objs.go:178]:
```suggestion
// IsDeploymentWithManager return true if obj is a deployment containing a pod with named manager, that according to the clusterctl contract, identifies the provider's controller.
```

**Review by fabriziopandini — COMMENTED** [review]
Thanks for updating, lgtm apart a couple of nits

File: cmd/clusterctl/client/cluster/installer.go (hunk 2 above)
Comment (dlipovetsky) [reply cmd/clusterctl/client/cluster/installer.go]: Another thank-you for that sequence @sbueringer!

I've hit this issue regularly. I _do_ want `clusterctl` to tell me whether the controllers/webhooks have "deployed successfully," because that tells me that it's at least _possible_ for webhook requests to succeed. But that does not _guarantee_ that webhooks requests will succeed. So clients should still be built with the assumption that webhook requests may not succeed, or that kube-apiserver may suffer some other "internal error."

Comment (sbueringer) [reply cmd/clusterctl/client/cluster/installer.go]: Yup, I guess the only really 100% reliable solution is to retry the apply in case the webhooks are either not yet or currently not available.

Comment (dlipovetsky) [reply cmd/clusterctl/client/cluster/installer.go]: Agreed. Internal server errors happen, and users must be prepared. But users shouldn't be waiting for controllers or webhooks about which they know nothing. That's where this PR is useful: it helps clusterctl tell users whether the controllers/webhooks deployed successfully once, even if for a moment.

File: cmd/clusterctl/client/cluster/installer.go [hunk 17]
```diff
@@ -35,7 +45,7 @@ type ProviderInstaller interface {
 	Add(repository.Components)
 
 	// Install performs the installation of the providers ready in the install queue.
-	Install() ([]repository.Components, error)
+	Install(InstallOptions) ([]repository.Components, error)
```
Comment (CecileRobertMichon) [inline cmd/clusterctl/client/cluster/installer.go:48]: this is technically a breaking change from a clusterctl library perspective. @fabriziopandini should the commit have the ⚠️ prefix?

Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/installer.go:48]: We are not currently providing any compatibility guarantees on cluserctl used as a library, but I agree we should put a warning on this change, good catch.

File: cmd/clusterctl/client/cluster/installer.go (hunk 7 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/installer.go:128]: I am going to rename the `waitForReady` function to `waitForProvidersReady` function which will then call `waitManagerDeploymentsReady`. This way the sense of what we are trying to achieve is clear and also the implementation has the flexibility to change in the future.

File: cmd/clusterctl/client/cluster/installer.go (hunk 10 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/installer.go:164]: Here is why i chose to not error out if waiting for deployments timed out:  
The primary goal of `clusterctl init` is to install the providers which, at this point, it finished successfully. I wasn't convinced that throwing an error here is the correct UX as we just timeout waiting for the providers to be ready. Technically, installation was a success. Hence, I was just looking to just throw a warning message to the user that we timed out waiting for the deployments.

That being said, since the wait feature is optional and behind flag it might be fine to throw an error if we timed out waiting for the providers. 

Which of these is better UX? 

Thoughts?

@fabriziopandini @vincepri

File: cmd/clusterctl/client/init.go (hunk 11 above)
Comment (ykakarap) [reply cmd/clusterctl/client/init.go:65]: I will add the period at the end but I think the variable should be `WaitProviderTimeout` (singular) since the timeout defined here per provider. I will refactor the variable to match the comment (make it singular).

File: cmd/clusterctl/client/cluster/installer.go (hunk 14 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/installer.go:120]: Based on the comment you had previously about having a `waitForProvidersReady` function I think it would be nice if we rename the `waitForReady` function to `waitForProvidersReady` and have it call `waitManagerDeploymentsReady`. This way the install function reads well and our intentions of what want to do are clear without surfacing how we are doing it which, as you previously mentioned, can change.

This will be address as part of https://github.com/kubernetes-sigs/cluster-api/pull/4934#discussion_r683776625

WDYT?

File: cmd/clusterctl/client/cluster/installer.go (hunk 10 above)
Comment (sbueringer) [reply cmd/clusterctl/client/cluster/installer.go:164]: I misread your code, so my arguments don't exactly make sense :)

Imho the `clusterctl init` is not successful when the deployments are not getting ready. But let's see what others think.

File: cmd/clusterctl/client/cluster/installer.go (hunk 7 above)
Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/installer.go:128]: ok, fine for me

File: cmd/clusterctl/client/cluster/installer.go (hunk 6 above)
Comment (pshail) [reply cmd/clusterctl/client/cluster/installer.go:61]: Not sure if the following option/suggestion is feasible
- Keep Install function as per the original interface 
- Define new InstallWithOptions that takes the install option struct there by reducing breaking change impact
And eventually one can deprecate out Install() if need be

File: cmd/clusterctl/client/cluster/installer.go (hunk 10 above)
Comment (ykakarap) [reply cmd/clusterctl/client/cluster/installer.go:164]: Got it. I will refactor to error out. 🙂

File: cmd/clusterctl/client/cluster/installer.go (hunk 6 above)
Comment (sbueringer) [reply cmd/clusterctl/client/cluster/installer.go:60]: This should work. But I think given https://github.com/kubernetes-sigs/cluster-api/pull/4934/files#r683272400 we don't want to invest the effort and go with the current implementation.

File: cmd/clusterctl/client/cluster/installer.go [hunk 18]
```diff
@@ -90,6 +110,57 @@ func installComponentsAndUpdateInventory(components repository.Components, provi
...
+	}
+
+	log := logf.Log
+	log.Info("Waiting for providers to be available...")
+
+	return i.waitManagerDeploymentsReady(opts)
+}
+
+// waitDeploymentsReady waits till the installed deployments are ready.
+func (i *providerInstaller) waitManagerDeploymentsReady(opts InstallOptions) error {
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/installer.go:128]:
```suggestion
// waitManagerDeploymentsReady waits till the installed deployments are ready.
func (i *providerInstaller) waitManagerDeploymentsReady(opts InstallOptions) error {
```
nit

File: cmd/clusterctl/client/cluster/installer.go [hunk 19]
```diff
@@ -72,6 +87,11 @@ func (i *providerInstaller) Install() ([]repository.Components, error) {
 
 		ret = append(ret, components)
 	}
+
+	if err := i.waitForProvidersReady(opts); err != nil {
+		return ret, err
+	}
+
 	return ret, nil
```
Comment (sbueringer) [inline cmd/clusterctl/client/cluster/installer.go:95]:
```suggestion
	return ret, i.waitForProvidersReady(opts)
```
nit (if you want)

**Review by vincepri — APPROVED** [review]
/approve
