### PR TITLE
:warning: E2E test now resolve CNI_RESOURCES without using env variables

### LINKED ISSUE #3797: E2E tests break with long CNI spec
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/991

Tests fail with `failed to execute kustomize: : fork/exec /home/prow/go/bin/kustomize: argument list too long` after updating the Calico CNI to v1.16 (from v1.12). The latest Calico spec is longer than previous ones as a bunch of CRDs were added.

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/991/pull-cluster-api-provider-azure-e2e/1316110882949828608/build-log.txt

This is the line that fails: https://github.com/kubernetes-sigs/cluster-api/blob/bf845fa2d035dd38cbfb04355ed0550137d6f7f2/test/framework/config.go#L327

This is not currently an issue for CAPD because it uses kindnet which has a relatively short spec but will be an issue for any provider trying to apply Calico v3.15+ (CAPZ, CAPA, etc) using the E2E framework. 

Note: we've had similar issues with Tilt in the past and this was the workaround: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/829

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by fabriziopandini**
This PR makes the E2E framework to resolve CNI_RESOURCES without using env variables, thus avoiding problems when the CNI manifest is too long.

As a consequence of this change the call to `SetCNIEnvVar` should be now replaced by one (or more) calls to `createRepositoryInput.RegisterClusterResourceSetConfigMapTransformation`

Fixes #3797 
/assign @CecileRobertMichon 

/hold

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@fabriziopandini were you able to test this with the longer calico manifest?

File: test/framework/clusterctl/e2e_config.go [hunk 1]
```diff
@@ -66,15 +70,11 @@ func LoadE2EConfig(ctx context.Context, input LoadE2EConfigInput) *E2EConfig {
 
 // SetCNIEnvVar read CNI from cniManifestPath and sets an environmental variable that keeps CNI resources.
 // A ClusterResourceSet can be used to apply CNI using this environmental variable.
+//
+// Deprecated: CNI manifest will be now automatically embedded into cluster templates during create repository.
+// The new approach does not uses env variables so we can avoid https://github.com/kubernetes-sigs/cluster-api/issues/3797;
+// This func is preserved for avoiding to break users in the v0.3 series, but it is now a noop.
 func SetCNIEnvVar(cniManifestPath string, cniEnvVar string) {
```
Comment (CecileRobertMichon) [inline test/framework/clusterctl/e2e_config.go:77]: should we make this PR has "breaking" since this is now a no-op?

Comment (fabriziopandini) [reply test/framework/clusterctl/e2e_config.go:77]: makes sense, done + updated PR comment

**Review by CecileRobertMichon — APPROVED** [review]
lgtm

This doesn't look to be breaking for other providers using CNI with CRS but assigning a few others to confirm 👀 
/assign @sedefsavas @richardcase @cpanato 

thanks for figuring out the root cause @fabriziopandini!

File: test/framework/clusterctl/e2e_config.go [hunk 2]
```diff
@@ -39,6 +38,11 @@ import (
 	"sigs.k8s.io/yaml"
 )
 
+const (
+	CNIPath      = "CNI"
+	CNIResources = "CNI_RESOURCES"
```
Comment (sedefsavas) [inline test/framework/clusterctl/e2e_config.go:43]: If we define these here, I think we will limit the CNIs to only 1 per e2e tests. 

Previously, to use a different CNI, these parameters were being changed and by setting the changed parameters to CRS as data was working fine.
CAPZ is using multiple CNIs. cc @CecileRobertMichon

Comment (CecileRobertMichon) [reply test/framework/clusterctl/e2e_config.go:43]: Ooh great catch @sedefsavas. That's true, we do that for IPv6 https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/test/e2e/e2e_suite_test.go#L171 (and actually have a different CNIPath defined for that and rely on the `SetCNIEnvVar` function).

**Comment by CecileRobertMichon** [comment]
/hold

based on @sedefsavas's comment above

File: test/framework/clusterctl/e2e_config.go (hunk 2 above)
Comment (fabriziopandini) [reply test/framework/clusterctl/e2e_config.go]: Good catch, I was not aware of the multiple CNI use case.
I have proposed a solution to solve this use case, and potentially enabling also other File transformations will be required in the future.

**Comment by fabriziopandini** [comment]
@CecileRobertMichon @sedefsavas I have proposed a solution that allows managing multiple CNI without requiring env variables.

/test pull-cluster-api-e2e-full-release-0-3

File: test/e2e/e2e_suite_test.go [hunk 3]
```diff
@@ -159,17 +159,23 @@ func loadE2EConfig(configPath string) *clusterctl.E2EConfig {
...
 		RepositoryFolder: repositoryFolder,
-	})
+	}
+
+	// Ensuring a CNI file is defined in the config and register a FileTransformation to inject the referenced file as in place of the CNI_RESOURCES envSubst variable.
+	Expect(config.Variables).To(HaveKey(CNIPath), "Missing %s variable in the config", CNIPath)
+	cniPAth := config.GetVariable(CNIPath)
+	Expect(cniPAth).To(BeAnExistingFile(), "The %s variable should resolve to an existing file", CNIPath)
+
+	createRepositoryInput.RegisterClusterResourceSetConfigMapTransformation(cniPAth, CNIResources)
```
Comment (sedefsavas) [inline test/e2e/e2e_suite_test.go:176]: Just to understand, will `createClusterctlLocalRepository ` be called multiple times for adding different CNIs?

Comment (fabriziopandini) [reply test/e2e/e2e_suite_test.go:176]: No, there will be only one call to createClusterctlLocalRepository as of today.
However, inside this func you have to register one ClusterResourceSetConfigMapTransformation for each CNI you want to support.

**Comment by sedefsavas** [comment]
This lgtm now.
MachinPool test failed but may be a flake.


/test pull-cluster-api-e2e-full-release-0-3

File: test/e2e/e2e_suite_test.go [hunk 4]
```diff
@@ -159,18 +159,23 @@ func loadE2EConfig(configPath string) *clusterctl.E2EConfig {
...
-	clusterctlConfig := clusterctl.CreateRepository(context.TODO(), clusterctl.CreateRepositoryInput{
+	createRepositoryInput := clusterctl.CreateRepositoryInput{
 		E2EConfig:        config,
 		RepositoryFolder: repositoryFolder,
-	})
+	}
+
+	// Ensuring a CNI file is defined in the config and register a FileTransformation to inject the referenced file as in place of the CNI_RESOURCES envSubst variable.
+	Expect(config.Variables).To(HaveKey(CNIPath), "Missing %s variable in the config", CNIPath)
+	cniPAth := config.GetVariable(CNIPath)
```
Comment (CecileRobertMichon) [inline test/e2e/e2e_suite_test.go:173]:
```suggestion
	cniPath := config.GetVariable(CNIPath)
```

File: test/e2e/e2e_suite_test.go [hunk 5]
```diff
@@ -159,18 +159,23 @@ func loadE2EConfig(configPath string) *clusterctl.E2EConfig {
...
+	Expect(cniPAth).To(BeAnExistingFile(), "The %s variable should resolve to an existing file", CNIPath)
```
Comment (CecileRobertMichon) [inline test/e2e/e2e_suite_test.go:174]:
```suggestion
	Expect(cniPath).To(BeAnExistingFile(), "The %s variable should resolve to an existing file", CNIPath)
```

File: test/e2e/e2e_suite_test.go [hunk 6]
```diff
@@ -159,18 +159,23 @@ func loadE2EConfig(configPath string) *clusterctl.E2EConfig {
...
+
+	createRepositoryInput.RegisterClusterResourceSetConfigMapTransformation(cniPAth, CNIResources)
```
Comment (CecileRobertMichon) [inline test/e2e/e2e_suite_test.go:176]:
```suggestion
	createRepositoryInput.RegisterClusterResourceSetConfigMapTransformation(cniPath, CNIResources)
```

**Comment by CecileRobertMichon** [comment]
I updated my Calico PR to use your branch and applied the changes to verify everything works as expected with two CNIs https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/991/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R37

**Comment by fabriziopandini** [comment]
kk, I will wait for test results in CAPZ before addressing the nits

**Comment by CecileRobertMichon** [comment]
CAPZ e2e passed 🎉

**Comment by fabriziopandini** [comment]
@CecileRobertMichon thanks for validating this change on CAPZ!
comment addresses and squashed

**Comment by CecileRobertMichon** [comment]
thanks for fixing it :) 

/lgtm
/approve
/hold cancel
