### PR TITLE
Do not delete NodeRef for last control plane node

### LINKED ISSUE #1105: clusterctl delete cluster appears to hang on 0.1.4
/kind bug

**What steps did you take and what happened:**
`clusterctl delete cluster` hangs indefinitely waiting for a machine to be deleted

```shell
0702 16:23:02.071499   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:23:02.074064   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 2 milliseconds
I0702 16:23:12.074585   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:23:12.078698   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 3 milliseconds
I0702 16:23:22.074569   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:23:22.077669   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 2 milliseconds
I0702 16:23:32.074524   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:23:32.077266   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 2 milliseconds
I0702 16:23:42.074591   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:23:42.077924   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 3 milliseconds
I0702 16:23:52.074538   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:23:52.077611   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 2 milliseconds
I0702 16:24:02.074546   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:24:02.078224   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 3 milliseconds
I0702 16:24:12.074576   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:24:12.077736   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 3 milliseconds
I0702 16:24:22.074522   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:24:22.077215   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 2 milliseconds
I0702 16:24:32.074529   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:24:32.077148   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 2 milliseconds
I0702 16:24:42.074562   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:24:42.077514   21340 round_trippers.go:438] GET https://localhost:41079/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines 200 OK in 2 milliseconds
I0702 16:24:52.074539   21340 clusterclient.go:870] Waiting for Machines to be deleted...
I0702 16:24:52.077985   21340 round_trippers.go:4
```

**What did you expect to happen:**
For `clusterctl delete cluster` to not hang.

**Anything else you would like to add:**
The CAPV manager log has the following, ad infinitum:

```shell
E0702 21:24:09.444342       1 machine_controller.go:186] Error deleting node "kutz-controlplane-1" for machine "kutz-controlplane-1": Delete https://192.168.5.175:6443/api/v1/nodes/kutz-controlplane-1: dial tcp 192.168.5.175:6443: i/o timeout
```

Based on the log message, the error appears to be occurring [here](https://github.com/kubernetes-sigs/cluster-api/blob/bf950adfea7c117e58ca30770d02067d8e43d3c7/pkg/controller/machine/machine_controller.go#L183-L189):

```golang
		klog.Infof("Reconciling machine %q triggers delete", name)
		if err := r.actuator.Delete(ctx, cluster, m); err != nil {
			if requeueErr, ok := errors.Cause(err).(controllerError.HasRequeueAfterError); ok {
				klog.Infof("Actuator returned requeue-after error: %v", requeueErr)
				return reconcile.Result{Requeue: true, RequeueAfter: requeueErr.GetRequeueAfter()}, nil
			}


			klog.Errorf("Failed to delete machine %q: %v", name, err)
			return reconcile.Result{}, err
		}


		if m.Status.NodeRef != nil {
			klog.Infof("Deleting node %q for machine %q", m.Status.NodeRef.Name, m.Name)
			if err := r.deleteNode(ctx, cluster, m.Status.NodeRef.Name); err != nil && !apierrors.IsNotFound(err) {
				klog.Errorf("Error deleting node %q for machine %q: %v", m.Status.NodeRef.Name, name, err)
				return reconcile.Result{}, err
			}
		}
```

Since this is an attempt to delete a single-node cluster that is the initial target cluster deployed by `clusterctl create cluster`, I think what is happening is an ordering issue.

The nodeRef will never be successfully deleted since the target cluster is already offline since the machine actuator's `delete` call removed the backend VM.

Thus all we see in the manager log is one timeout after another:

```shell
I0702 21:23:39.422211       1 machine_controller.go:115] Reconciling Machine "kutz-controlplane-1"
I0702 21:23:39.422268       1 machine_controller.go:172] Reconciling machine "kutz-controlplane-1" triggers delete
I0702 21:23:39.427235       1 actuator.go:140] default-logger/cluster.k8s.io/v1alpha1/default/kutz/kutz-controlplane-1 "level"=2 "msg"="deleting machine"  
I0702 21:23:39.429579       1 util.go:183] default-logger/cluster.k8s.io/v1alpha1/default/kutz/kutz-controlplane-1/task-216212 "level"=4 "msg"="task found"  "description-id"="VirtualMachine.destroy" "state"="success"
I0702 21:23:39.429609       1 util.go:192] default-logger/cluster.k8s.io/v1alpha1/default/kutz/kutz-controlplane-1/task-216212 "level"=4 "msg"="task is a success"  "description-id"="VirtualMachine.destroy"
I0702 21:23:39.432616       1 machine_context.go:270] default-logger/cluster.k8s.io/v1alpha1/default/kutz/kutz-controlplane-1/task-216212 "level"=6 "msg"="generated json patch for object"  "json-patch"="[\n  {\n    \"op\": \"remove\",\n    \"path\": \"/spec/providerSpec/value/machineRef\"\n  }\n]"
I0702 21:23:39.438498       1 round_trippers.go:438] PATCH https://10.96.0.1:443/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines/kutz-controlplane-1 200 OK in 5 milliseconds
I0702 21:23:39.438676       1 machine_context.go:277] default-logger/cluster.k8s.io/v1alpha1/default/kutz/kutz-controlplane-1/task-216212 "level"=6 "msg"="patch object success"  
I0702 21:23:39.442169       1 round_trippers.go:438] POST https://10.96.0.1:443/api/v1/namespaces/default/events 201 Created in 3 milliseconds
I0702 21:23:39.442733       1 round_trippers.go:438] PUT https://10.96.0.1:443/apis/cluster.k8s.io/v1alpha1/namespaces/default/machines/kutz-controlplane-1/status 200 OK in 3 milliseconds
I0702 21:23:39.442874       1 machine_context.go:300] default-logger/cluster.k8s.io/v1alpha1/default/kutz/kutz-controlplane-1/task-216212 "level"=6 "msg"="patch status success"  
I0702 21:23:39.442914       1 machine_controller.go:184] Deleting node "kutz-controlplane-1" for machine "kutz-controlplane-1"
I0702 21:23:39.445721       1 round_trippers.go:438] PATCH https://10.96.0.1:443/api/v1/namespaces/default/events/kutz-controlplane-1.15adb404d3cde107 200 OK in 2 milliseconds
I0702 21:23:39.447453       1 round_trippers.go:438] POST https://10.96.0.1:443/api/v1/namespaces/default/events 201 Created in 1 milliseconds
I0702 21:23:43.506845       1 round_trippers.go:438] GET https://192.168.5.175:6443/api/v1/nodes  in 30000 milliseconds
E0702 21:23:43.507034       1 actuator.go:152] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/kutz "msg"="unable to list nodes for target cluster" "error"="Get https://192.168.5.175:6443/api/v1/nodes: dial tcp 192.168.5.175:6443: i/o timeout"  
I0702 21:23:43.515226       1 round_trippers.go:438] PUT https://10.96.0.1:443/apis/cluster.k8s.io/v1alpha1/namespaces/default/clusters/kutz/status 200 OK in 5 milliseconds
I0702 21:23:43.516064       1 cluster_context.go:361] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/kutz "level"=6 "msg"="patch status success"  
I0702 21:23:43.516164       1 cluster_controller.go:143] Actuator returned requeue-after error: requeue in: 20s
I0702 21:23:43.519861       1 round_trippers.go:438] PATCH https://10.96.0.1:443/api/v1/namespaces/default/events/kutz.15adb403a46284ca 200 OK in 3 milliseconds
I0702 21:23:43.523229       1 round_trippers.go:438] PATCH https://10.96.0.1:443/api/v1/namespaces/default/events/kutz.15adb403a462b481 200 OK in 2 milliseconds
I0702 21:24:03.516480       1 cluster_controller.go:91] Running reconcile Cluster for "kutz"
I0702 21:24:03.516536       1 cluster_controller.go:140] reconciling cluster object kutz triggers idempotent reconcile.
I0702 21:24:03.518804       1 actuator.go:82] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/kutz "level"=6 "msg"="reconciling cluster"  
I0702 21:24:03.518862       1 certificates.go:73] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/kutz "level"=6 "msg"="reconciling certificates"  
I0702 21:24:09.444164       1 round_trippers.go:438] DELETE https://192.168.5.175:6443/api/v1/nodes/kutz-controlplane-1  in 30000 milliseconds
E0702 21:24:09.444342       1 machine_controller.go:186] Error deleting node "kutz-controlplane-1" for machine "kutz-controlplane-1": Delete https://192.168.5.175:6443/api/v1/nodes/kutz-controlplane-1: dial tcp 192.168.5.175:6443: i/o timeout
I0702 21:24:10.444776       1 machine_controller.go:115] Reconciling Machine "kutz-controlplane-1"
I0702 21:24:10.444883       1 machine_controller.go:172] Reconciling machine "kutz-controlplane-1" triggers delete
I0702 21:24:10.452061       1 actuator.go:140] default-logger/cluster.k8s.io/v1alpha1/default/kutz/kutz-controlplane-1 "level"=2 "msg"="deleting machine"  
I0702 21:24:10.454649       1 util.go:55] default-logger/cluster.k8s.io/v1alpha1/default/kutz/kutz-controlplane-1 "level"=6 "msg"="finding vm by instance UUID"  "instance-uuid"="7dd88196-9d0f-11e9-a430-0242ac110002"
I0702 21:24:10.458275       1 machine_controller.go:184] Deleting node "kutz-controlplane-1" for machine "kutz-controlplane-1"
I0702 21:24:10.462010       1 round_trippers.go:438] PATCH https://10.96.0.1:443/api/v1/namespaces/default/events/kutz-controlplane-1.15adb40e5699f56c 200 OK in 3 milliseconds
I0702 21:24:33.520791       1 round_trippers.go:438] GET https://192.168.5.175:6443/api/v1/nodes  in 30000 milliseconds
E0702 21:24:33.520896       1 actuator.go:152] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/kutz "msg"="unable to list nodes for target cluster" "error"="Get https://192.168.5.175:6443/api/v1/nodes: dial tcp 192.168.5.175:6443: i/o timeout"  
I0702 21:24:33.527657       1 round_trippers.go:438] PUT https://10.96.0.1:443/apis/cluster.k8s.io/v1alpha1/namespaces/default/clusters/kutz/status 200 OK in 5 milliseconds
I0702 21:24:33.528414       1 cluster_context.go:361] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/kutz "level"=6 "msg"="patch status success"  
I0702 21:24:33.528460       1 cluster_controller.go:143] Actuator returned requeue-after error: requeue in: 20s
I0702 21:24:33.532025       1 round_trippers.go:438] PATCH https://10.96.0.1:443/api/v1/namespaces/default/events/kutz.15adb403a46284ca 200 OK in 3 milliseconds
I0702 21:24:33.535348       1 round_trippers.go:438] PATCH https://10.96.0.1:443/api/v1/namespaces/default/events/kutz.15adb403a462b481 200 OK in 3 milliseconds
I0702 21:24:40.460207       1 round_trippers.go:438] DELETE https://192.168.5.175:6443/api/v1/nodes/kutz-controlplane-1  in 30000 milliseconds
E0702 21:24:40.460303       1 machine_controller.go:186] Error deleting node "kutz-controlplane-1" for machine "kutz-controlplane-1": Delete https://192.168.5.175:6443/api/v1/nodes/kutz-controlplane-1: dial tcp 192.168.5.175:6443: i/o timeout
```

**Environment:**
CAPV `master`

- Cluster-api version:
0.1.4

- Minikube/KIND version:
Kind 0.3.0

- Kubernetes version: (use `kubectl version`):
1.13.6

- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04.2 LTS

cc @ncdc (since you appear to be having the same issue according to [this Slack comment](https://kubernetes.slack.com/archives/C8TSNPY4T/p1562103056148100?thread_ts=1562102887.147000&cid=C8TSNPY4T)

### PR DESCRIPTION
**Pull request by akutz**
**What this PR does / why we need it**:
This patch fixes a bug that occurs when the NodeRef is deleted for the last control plane node in a cluster. A timeout error would occur because the last machine would have already been deleted, and the cluster would no longer be active to receive the delete node request.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1105 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
* Fixes bug when deleting NodeRef for last control plane member in a cluster
```

### CODE REVIEW

File: pkg/controller/machine/machine_controller.go [hunk 1]
```diff
@@ -305,3 +341,35 @@ func (r *ReconcileMachine) deleteNode(ctx context.Context, cluster *clusterv1.Cl
...
+		}
+		return nil, errors.Wrapf(err, "Failed to list machines")
+	}
+
+	machines := make([]*clusterv1.Machine, len(mlist.Items))
+	for i := range mlist.Items {
+		machines[i] = &mlist.Items[i]
+	}
+
+	return machines, nil
```
Comment (vincepri) [inline pkg/controller/machine/machine_controller.go]: Can we return `mlist.Items`?

File: pkg/controller/machine/machine_controller.go [hunk 2]
```diff
@@ -305,3 +341,35 @@ func (r *ReconcileMachine) deleteNode(ctx context.Context, cluster *clusterv1.Cl
...
+	mlist := &clusterv1.MachineList{}
+	listOptions := &client.ListOptions{
+		Namespace: machine.Namespace,
+		LabelSelector: labels.Set(map[string]string{
+			clusterv1.MachineClusterLabelName: clusterName,
+		}).AsSelector(),
+	}
+
+	if err := r.Client.List(ctx, listOptions, mlist); err != nil {
+		if apierrors.IsNotFound(err) {
```
Comment (vincepri) [inline pkg/controller/machine/machine_controller.go]: Does `List` return IsNotFound if there are no machines?

File: pkg/controller/machine/machine_controller.go [hunk 3]
```diff
@@ -305,3 +341,35 @@ func (r *ReconcileMachine) deleteNode(ctx context.Context, cluster *clusterv1.Cl
...
+// cluster as the provided Machine
+func (r *ReconcileMachine) getMachines(ctx context.Context, machine *clusterv1.Machine) ([]*clusterv1.Machine, error) {
+	clusterName := machine.Labels[clusterv1.MachineClusterLabelName]
+	if clusterName == "" {
+		klog.Infof("Machine %q in namespace %q doesn't specify %q label, assuming nil cluster", machine.Name, machine.Namespace, clusterv1.MachineClusterLabelName)
+		return nil, nil
+	}
+
+	mlist := &clusterv1.MachineList{}
+	listOptions := &client.ListOptions{
```
Comment (ncdc) [inline pkg/controller/machine/machine_controller.go]: Instead of doing this, there are helper functions if you want to use them: `client.InNamespace(ns)` and `client.MatchinLabels(map)`.

File: pkg/controller/machine/machine_controller.go [hunk 4]
```diff
@@ -305,3 +341,35 @@ func (r *ReconcileMachine) deleteNode(ctx context.Context, cluster *clusterv1.Cl
 
 	return corev1Remote.Nodes().Delete(name, &metav1.DeleteOptions{})
 }
+
+// getMachines returns all of the Machine objects that belong to the same
+// cluster as the provided Machine
+func (r *ReconcileMachine) getMachines(ctx context.Context, machine *clusterv1.Machine) ([]*clusterv1.Machine, error) {
+	clusterName := machine.Labels[clusterv1.MachineClusterLabelName]
+	if clusterName == "" {
+		klog.Infof("Machine %q in namespace %q doesn't specify %q label, assuming nil cluster", machine.Name, machine.Namespace, clusterv1.MachineClusterLabelName)
```
Comment (vincepri) [inline pkg/controller/machine/machine_controller.go]: We should remove this log line, as it's already logged out when getting the Cluster reference

File: pkg/controller/machine/machine_controller.go [hunk 5]
```diff
@@ -278,6 +286,34 @@ func (r *ReconcileMachine) isDeleteAllowed(machine *clusterv1.Machine) bool {
...
+
+	// If this machine is a control plane node then only delete the NodeRef
+	// if there is another control plane node (besides this machine) left.
+	if util.IsControlPlaneMachine(machine) {
+		return len(controlPlaneMachines) > 1, nil
+	}
+
+	// Otherwise it's okay to delete the NodeRef if there's a single control
+	// plane node left.
+	return len(controlPlaneMachines) > 0, nil
```
Comment (vincepri) [inline pkg/controller/machine/machine_controller.go]: Shouldn't this return false?

File: pkg/controller/machine/machine_controller.go (hunk 2 above)
Comment (ncdc) [reply pkg/controller/machine/machine_controller.go]: client-go does not (it returns an empty list.Items). I don't know about controller-runtime's client, but I would expect an empty list instead of not-found.

File: pkg/controller/machine/machine_controller.go (hunk 1 above)
Comment (ncdc) [reply pkg/controller/machine/machine_controller.go]: `util.GetControlPlaneMachines` needs the pointers

File: pkg/controller/machine/machine_controller.go (hunk 5 above)
Comment (detiber) [reply pkg/controller/machine/machine_controller.go]: If there are no controlPlane machines (externally managed control plane), then this would return false even when it isn't an issue.

Comment (ncdc) [reply pkg/controller/machine/machine_controller.go]: Scenario:

- The machine we're deleting is not a control plane machine
- If there is at least 1 control plane machine, it's ok to delete the node for this non-control plane machine

Right?

File: pkg/controller/machine/machine_controller.go [hunk 6]
```diff
@@ -278,6 +286,34 @@ func (r *ReconcileMachine) isDeleteAllowed(machine *clusterv1.Machine) bool {
...
+	if err != nil {
+		return false, err
+	}
+
+	controlPlaneMachines := util.GetControlPlaneMachines(machines)
+
+	// If this machine is a control plane node then only delete the NodeRef
+	// if there is another control plane node (besides this machine) left.
+	if util.IsControlPlaneMachine(machine) {
+		return len(controlPlaneMachines) > 1, nil
```
Comment (detiber) [inline pkg/controller/machine/machine_controller.go]: There is likely also going to be an issue with deleting nodes in the case that the user starts with a 3 node controlplane and deletes 2 of the controlplane machines, since etcd will no longer have quorum.

Comment (ncdc) [reply pkg/controller/machine/machine_controller.go]: Do any of the providers handle removing members from etcd today?

File: pkg/controller/machine/machine_controller.go (hunk 5 above)
Comment (vincepri) [reply pkg/controller/machine/machine_controller.go]: Makes sense, I misread the if condition above

File: pkg/controller/machine/machine_controller.go (hunk 2 above)
Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: I just did this in case. I wasn't sure, so this seemed like an okay check.

File: pkg/controller/machine/machine_controller.go (hunk 5 above)
Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: That was my thinking. At first I assumed that the last machine would always be a control plane machine, but then I realized it may not be. So that's why the number of required control plane machines differs based on whether the provided machine is a control plane machine.

File: pkg/controller/machine/machine_controller.go (hunk 6 above)
Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: Hmm. I don't know enough here to respond to this. Based solely on things from the Kubernetes angle, if the API server is there to respond, it seems the call should occur.

File: pkg/controller/machine/machine_controller.go [hunk 7]
```diff
@@ -347,22 +346,14 @@ func (r *ReconcileMachine) deleteNode(ctx context.Context, cluster *clusterv1.Cl
...
-		}).AsSelector(),
-	}
+	lbls := map[string]string{clusterv1.MachineClusterLabelName: clusterName}
+	listOptions := client.InNamespace(machine.Namespace).MatchingLabels(lbls)
 
 	if err := r.Client.List(ctx, listOptions, mlist); err != nil {
-		if apierrors.IsNotFound(err) {
-			return nil, nil
-		}
 		return nil, errors.Wrapf(err, "Failed to list machines")
```
Comment (vincepri) [inline pkg/controller/machine/machine_controller.go]: Error messages should start with lowercase

File: pkg/controller/machine/machine_controller.go [hunk 8]
```diff
@@ -180,7 +180,14 @@ func (r *ReconcileMachine) Reconcile(request reconcile.Request) (reconcile.Resul
...
 		}
 
-		if m.Status.NodeRef != nil {
+		okToDeleteNode, err := r.isDeleteNodeAllowed(context.Background(), m)
+		if err != nil {
+			klog.Errorf("IsDeleteNodeAllowed check failed for machine %q: %v", name, err)
+			return reconcile.Result{}, err
+		}
+		if !okToDeleteNode {
+			klog.Infof("Deleting node is not allowed for machine %q", name)
```
Comment (akutz) [inline pkg/controller/machine/machine_controller.go]: Hi @vincepri / @ncdc / @detiber,

I'm wondering if I shouldn't omit the log here and move it to `isDeleteNodeAllowed` in order to log the reason the node was not deleted. I followed the pattern from above, but maybe here it's worth adding this detail?

File: pkg/controller/machine/machine_controller.go (hunk 6 above)
Comment (detiber) [reply pkg/controller/machine/machine_controller.go]: @ncdc I'm not aware of any, which is why it was called out in the upgrade doc.

File: pkg/controller/machine/machine_controller.go [hunk 9]
```diff
@@ -305,3 +340,27 @@ func (r *ReconcileMachine) deleteNode(ctx context.Context, cluster *clusterv1.Cl
...
+
+// getMachines returns all of the Machine objects that belong to the same
+// cluster as the provided Machine
+func (r *ReconcileMachine) getMachines(ctx context.Context, machine *clusterv1.Machine) ([]*clusterv1.Machine, error) {
+	clusterName := machine.Labels[clusterv1.MachineClusterLabelName]
+	if clusterName == "" {
+		return nil, nil
+	}
+
+	mlist := &clusterv1.MachineList{}
```
Comment (ncdc) [inline pkg/controller/machine/machine_controller.go]: We try to avoid abbreviations in names - could this be named `machineList`?

File: pkg/controller/machine/machine_controller.go [hunk 10]
```diff
@@ -305,3 +340,27 @@ func (r *ReconcileMachine) deleteNode(ctx context.Context, cluster *clusterv1.Cl
...
+	lbls := map[string]string{clusterv1.MachineClusterLabelName: clusterName}
```
Comment (ncdc) [inline pkg/controller/machine/machine_controller.go]: Can this be `labels` or `labelSelector`?

File: pkg/controller/machine/machine_controller.go (hunk 6 above)
Comment (ncdc) [reply pkg/controller/machine/machine_controller.go]: Can we proceed with this PR despite the lack of etcd member removal? That will have to come in a control plane manager of some sort, I'd say.

File: pkg/controller/machine/machine_controller.go (hunk 8 above)
Comment (ncdc) [reply pkg/controller/machine/machine_controller.go]: +1 for moving

File: pkg/controller/machine/machine_controller.go (hunk 10 above)
Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: Hi @ncdc,

Could be :) FWIW, I copied this from the controller-api package. Their convention was `lbls`. Happy to make it whatever you want though.

File: pkg/controller/machine/machine_controller.go (hunk 9 above)
Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: Hi @ncdc,

Could be :) FWIW, I copied this from the controller-api package. Their convention for item lists was `Xlist`. Happy to make it whatever you want though.

File: pkg/controller/machine/machine_controller.go (hunk 6 above)
Comment (detiber) [reply pkg/controller/machine/machine_controller.go]: Sure, lets proceed.

File: pkg/controller/machine/machine_controller.go (hunk 8 above)
Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: Hi @ncdc,

I just refactored things a bit to improve the logging per this feedback. Please take a look.

**Comment by ncdc** [comment]
LGTM - @detiber?

File: pkg/controller/machine/machine_controller.go [hunk 11]
```diff
@@ -180,7 +180,17 @@ func (r *ReconcileMachine) Reconcile(request reconcile.Request) (reconcile.Resul
 			return reconcile.Result{}, err
 		}
 
-		if m.Status.NodeRef != nil {
+		if err := r.isDeleteNodeAllowed(context.Background(), m); err != nil {
+			switch err {
+			case errNilNodeRef:
+				klog.Infof("Deleting node is not allowed for machine %q: %v", m.Name, err)
+			case errNoControlPlaneNodes, errLastControlPlaneNode:
+				klog.Infof("Deleting node %q is not allowed for machine %q: %v", m.Status.NodeRef.Name, m.Name, err)
```
Comment (vincepri) [inline pkg/controller/machine/machine_controller.go]: Nit: raise V to at least 2-3 for these lines

File: pkg/controller/machine/machine_controller.go [hunk 12]
```diff
@@ -278,6 +288,45 @@ func (r *ReconcileMachine) isDeleteAllowed(machine *clusterv1.Machine) bool {
...
+var (
+	errNilNodeRef           = errors.New("noderef is nil")
+	errLastControlPlaneNode = errors.New("last control plane member")
+	errNoControlPlaneNodes  = errors.New("no control plane members")
+)
+
+// isDeleteNodeAllowed returns nil only if the Machine's NodeRef is not nil
+// and if the Machine is not the last control plane node in the cluster.
+func (r *ReconcileMachine) isDeleteNodeAllowed(ctx context.Context, machine *clusterv1.Machine) error {
+
```
Comment (vincepri) [inline pkg/controller/machine/machine_controller.go]: Nit: extra space

File: pkg/controller/machine/machine_controller.go [hunk 13]
```diff
@@ -305,3 +354,27 @@ func (r *ReconcileMachine) deleteNode(ctx context.Context, cluster *clusterv1.Cl
 
 	return corev1Remote.Nodes().Delete(name, &metav1.DeleteOptions{})
 }
+
+// getMachines returns all of the Machine objects that belong to the same
+// cluster as the provided Machine
+func (r *ReconcileMachine) getMachines(ctx context.Context, machine *clusterv1.Machine) ([]*clusterv1.Machine, error) {
```
Comment (vincepri) [inline pkg/controller/machine/machine_controller.go]: We could pass Cluster in here and rename this method to something like `getMachinesForCluster`

File: pkg/controller/machine/machine_controller.go (hunk 12 above)
Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: It's a preference thing. I prefer to leave a space when the first line is a comment. If the project style is to not do this, I will remove it.

File: pkg/controller/machine/machine_controller.go (hunk 13 above)
Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: True, but it doesn't really feel strictly necessary. If you feel strongly, I'll make the change.

Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: It will also require additional refactoring for other functions and be anti-pattern to the other functions that simply accept a machine. I think this should stay as is.

Comment (vincepri) [reply pkg/controller/machine/machine_controller.go]: Nah it's fine, it feels weird to get machines from a Machine, but we can refactor later

Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: Hi @vincepri,

There's a function for getting the cluster for a machine, but that would just involve an additional, unnecessary round-trip to the API server. This seems more efficient.

Comment (ncdc) [reply pkg/controller/machine/machine_controller.go]: We could change this to `getMachinesInCluster(namespace, name string) ([]*clusterv1.Machine, error)` and make the caller pass in the cluster namespace and name. WDYT?

Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: Honestly? I think this is a bug that causes a pretty bad failure, and I’d like to see the fix merged sooner than later. If possible, I’d prefer to revisit this later.

**Comment by akutz** [comment]
Darnit @ncdc, ya had to go and lgtm it :) I just pushed your recommended change :)

File: pkg/controller/machine/machine_controller.go [hunk 14]
```diff
@@ -305,3 +353,26 @@ func (r *ReconcileMachine) deleteNode(ctx context.Context, cluster *clusterv1.Cl
 
 	return corev1Remote.Nodes().Delete(name, &metav1.DeleteOptions{})
 }
+
+// getMachinesInCluster returns all of the Machine objects that belong to the
+// same cluster as the provided Machine
+func (r *ReconcileMachine) getMachinesInCluster(ctx context.Context, namespace, name string) ([]*clusterv1.Machine, error) {
+	if name == "" {
+		return nil, nil
```
Comment (ncdc) [inline pkg/controller/machine/machine_controller.go]: Return an error if either namespace or name is empty?

Comment (akutz) [reply pkg/controller/machine/machine_controller.go]: This is the same behavior as before, so I just kept with that. Is there an existing error we should use?

Comment (ncdc) [reply pkg/controller/machine/machine_controller.go]: Sorry, had this code mixed up with all the other places in CAPI where we return errors if cluster is missing 😄. I think this is ok. It just means it'll hit the `errNoControlPlaneNodes` branch.
