### PR TITLE
🐛  Allow KCP to Update when CoreDNS version doesn't change

### LINKED ISSUE #5952: Failing tests for 0.4 and 1.0
The following E2E tests for 0.4 seems to be constantly failing:

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-0.4#capi-e2e-release-0-4-1-22-1-23
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-0.4#capi-e2e-release-0-4-1-23-latest

/kind failing-test
/milestone v0.4
/kind release-blocking
/area testing

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

This change allows KCP to perform an upgrade when the version of CoreDNS is not increased. This will allow older branches to stay on the same CoreDNS version when performing upgrade e2e tests for later versions of Kubernetes.

Fixes #5952

### CODE REVIEW

**Comment by killianmuldoon** [comment]
@sbueringer I wasn't able to run the e2e this is supposed to fix properly locally - can we run them here?

File: controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go [hunk 1]
```diff
@@ -500,7 +500,7 @@ func (in *KubeadmControlPlane) validateCoreDNSVersion(prev *KubeadmControlPlane)
 		)
 		return allErrs
 	}
-
+	// Note: This check allows an "upgrade" in the case where the versions are equal.
 	if err := migration.ValidUpMigration(fromVersion.String(), toVersion.String()); err != nil {
```
Comment (sbueringer) [inline controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go:504]: Based on the log messages I don't think that's true:
https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-workload-upgrade-1-23-latest-release-1-0/1483442872060481536/artifacts/clusters/bootstrap/controllers/capi-kubeadm-control-plane-controller-manager/capi-kubeadm-control-plane-controller-manager-744575bddc-qwdqp/manager.log

Comment (sbueringer) [reply controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go:504]: Would be nice if you could adjust the error message in l.509:
```go
fmt.Sprintf("cannot migrate CoreDNS from '%v' to '%v': %v", fromVersion, toVersion, err),
```
Feels way easier to read like that to me :)

File: controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go [hunk 2]
```diff
@@ -744,6 +744,11 @@ func TestKubeadmControlPlaneValidateUpdate(t *testing.T) {
 			before:    before,
 			kcp:       dnsBuildTag,
 		},
+		{
+			name:   "should succeed when using the same CoreDNS version",
```
Comment (fabriziopandini) [inline controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook_test.go:748]: I think we need a test for "should succeed when using the same CoreDNS version - not supported", e.g with CoreDNS v99.99.99

File: controlplane/kubeadm/internal/workload_cluster_coredns.go [hunk 3]
```diff
@@ -412,10 +412,9 @@ func validateCoreDNSImageTag(fromTag, toTag string) error {
 	if err != nil {
 		return errors.Wrapf(err, "failed to parse CoreDNS target version %q", toTag)
 	}
-	// make sure that the version we're upgrading to is greater than the current one,
-	// or if they're the same version, the raw tags should be different (e.g. allow from `v1.17.4-somevendor.0` to `v1.17.4-somevendor.1`).
-	if x := from.Compare(to); x > 0 || (x == 0 && fromTag == toTag) {
-		return fmt.Errorf("toVersion %q must be greater than fromVersion %q", toTag, fromTag)
+	// make sure that the version we're upgrading to is greater than or equal to the current version.
+	if to.LT(from) {
```
Comment (fabriziopandini) [inline controlplane/kubeadm/internal/workload_cluster_coredns.go:416]: TBH I'm not sure that we need this change given that this func is not called if version are equal https://github.com/kubernetes-sigs/cluster-api/blob/5b9922a817cfab8c8b9125a5a035d81702361e6a/controlplane/kubeadm/internal/workload_cluster_coredns.go#L128-L131

File: controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go (hunk 1 above)
Comment (fabriziopandini) [reply controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go:504]: Agreed
The behavior of ValidUpMigration is kind of subtle because it handles fromVersion==ToVersion but only if the version is known (I got this digging into the code; also the inner error in the failing jobs is "start version '1.8.6' not supported").

So, if I got it right, what we want to do here is to support upgrading the kubernetes version of Clusters created with unsupported CoreDNS version, but without changing the CoreDNS version.

In order to achieve this, IMO the simplest option is to not call ValidUpMigration if fromVersion==ToVersion; eventually in a follow-up PR we can work on a better error message the return the maximum CoreDNS version a KCP release supports (by looking at migration.ValidVersions), but let's keep this out of the table for now so we have a minimal fix that can be backported

Comment (fabriziopandini) [reply controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go:504]: Another thing we should consider, it to prevent users from creating clusters with unsupported CoreDNS versions; this will make things less clear and enforce the up limit of our version support matrix, but I think we should discuss this with the community first

File: controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go [hunk 4]
```diff
@@ -500,7 +500,11 @@ func (in *KubeadmControlPlane) validateCoreDNSVersion(prev *KubeadmControlPlane)
 		)
 		return allErrs
 	}
-
+	// If the versions are equal return here without error.
+	// This allows an upgrades where the version of CoreDNS in use is not supported by the migration tool.
```
Comment (sbueringer) [inline controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go:504]:
```suggestion
	// This allows upgrades where the version of CoreDNS in use is not supported by the migration tool.
```
nit

**Comment by killianmuldoon** [comment]
I've tested this locally and it looks like it's solving the base issue in our e2e upgrades.

**Comment by sbueringer** [comment]
@killianmuldoon 
WDYT about creating the cherry-pick PRs for v0.4 and v1.0 manually already. We can then confirm on those PRs via:
```
/test pull-cluster-api-e2e-workload-upgrade-1-23-latest-release-0-4
/test pull-cluster-api-e2e-workload-upgrade-1-23-latest-release-1-0
```

File: controlplane/kubeadm/internal/workload_cluster_coredns_test.go [hunk 5]
```diff
@@ -496,12 +496,6 @@ func TestValidateCoreDNSImageTag(t *testing.T) {
 			fromVer: "1.6.5_foobar.1",
 			toVer:   "1.6.5_foobar.2",
 		},
-		{
-			name:            "fromVer is equal to toVer",
-			fromVer:         "1.6.5_foobar.1",
-			toVer:           "1.6.5_foobar.1",
-			expectErrSubStr: "must be greater",
-		},
 		{
```
Comment (sbueringer) [inline controlplane/kubeadm/internal/workload_cluster_coredns_test.go:499]: @killianmuldoon 
Should we revert this change?

Apart from that nit, lgtm

**Comment by sbueringer** [comment]
@fabriziopandini I checked the test results and logs on the v0.4 and v1.0 PR, everything looks fine.

I think we should be able to merge this PR and the cherry-picks.

**Comment by fabriziopandini** [comment]
Great work @sbueringer and @killianmuldoon!
/lgtm
/approve
