### PR TITLE
:seedling: Make dev cluster networking configurable

### LINKED ISSUE #9000: Config requiring docker network that supports ipv6 which is not a default setting
### What steps did you take and what happened?

While following the rapid iterative deployment with tilt tutorial (https://cluster-api.sigs.k8s.io/developer/tilt.html), an issue was run into with the preconfigured cluster script `./hack/kind-install-for-capd.sh` as shown below
```
Creating cluster "capi-test" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) :frame_with_picture:
 ✓ Preparing nodes :package:
 ✗ Writing configuration :scroll:
Deleted nodes: ["capi-test-control-plane"]
ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get IPv6 address for node capi-test-control-plane

```
Work around used:
editing the /hack/kind-install-for-capd.sh file and removing 
```
networking:
  ipFamily: dual
```
from the script

### What did you expect to happen?

I expected the preconfigured script to work without editing out the networking section. 
Is this a common workaround? Or are there other ways to configure docker to use IPv6 correctly?

### Cluster API version

v1.4.4

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by chaunceyjiang**
**What this PR does / why we need it**:
Fixed KIND Config requiring docker networking with ipv6 support.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9000

### CODE REVIEW

**Comment by sbueringer** [comment]
Not sure if I would label this as a bugfix. Maybe others?

File: hack/kind-install-for-capd.sh [hunk 1]
```diff
@@ -31,7 +31,8 @@ if [[ "${TRACE-0}" == "1" ]]; then
 fi
 
 KIND_CLUSTER_NAME=${CAPI_KIND_CLUSTER_NAME:-"capi-test"}
-
+# See: https://kind.sigs.k8s.io/docs/user/configuration/#ip-family
+KIND_NETWORK_IPFAMILY=${KIND_NETWORK_IPFAMILY:-"dual"}
```
Comment (killianmuldoon) [inline hack/kind-install-for-capd.sh:35]: /lgtm
/approve

Thanks for adding this option!

**Comment by killianmuldoon** [comment]
/retitle :seedling Make dev cluster networking configurable

**Comment by killianmuldoon** [comment]
@sbueringer  - WDYT of the new title?

**Comment by sbueringer** [comment]
Sounds good / better
