### PR TITLE
[clusterctl] Fix ensure namespace function in clusterclient

### LINKED ISSUE #1208: [clusterctl] Do not fail ensureNamespace if user does not have permissions to create ns
Currently in case of users (without permissions to create namespaces) try to create clusters in existing namespace, ensureNamespace function fails due to missing permissions. That's because ensureNamespace tries to create namespace first and only then checks an error. I suppose, there should be another logic: first check if namespace exists and only if not - try to create namespace.

### PR DESCRIPTION
**Pull request by eromanova**
Is needed to avoid possible tracebacks due to auth permission (if user does not have permission to create or get namespaces)

Fixes #1208

### CODE REVIEW

File: cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go [hunk 1]
```diff
@@ -128,13 +128,19 @@ func (c *client) EnsureNamespace(namespaceName string) error {
 		return errors.Wrap(err, "error creating core clientset")
 	}
 
+	namespaces, err := clientset.CoreV1().Namespaces().List(metav1.ListOptions{})
```
Comment (ncdc) [inline cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go]: Please use `Get` instead of `List` to check for a single namespace. You can use `apierrors.IsNotFound(err)` to distinguish between a 404 not found and other errors.

File: cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go [hunk 2]
```diff
@@ -128,13 +128,19 @@ func (c *client) EnsureNamespace(namespaceName string) error {
...
+			return nil
+		}
+	}
 	namespace := apiv1.Namespace{
 		ObjectMeta: metav1.ObjectMeta{
 			Name: namespaceName,
 		},
 	}
 	_, err = clientset.CoreV1().Namespaces().Create(&namespace)
-	if err != nil && !apierrors.IsAlreadyExists(err) {
```
Comment (ncdc) [inline cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go]: I would leave in the check for existence. There is a slim chance that the Get call could return a 404 not found, then something else creates the namespace, and then this line tries to create it.

File: cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go (hunk 1 above)
Comment (detiber) [inline cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go]: Any particular reason to use `List` here instead of `Get`?

This is also missing a `if err != nil` check. It might be good to test the error against `apierrors.IsForbidden` to see if the user is also missing permissions to List or Get Namespaces, in which case we can likely emit a warning to the user.

**Comment by eromanova** [comment]
@detiber @ncdc Thank you for your comments, guys. The reason I used List instead of Get is possible missing Get permissions for user. But such case when user does not have permissions to List, but can Get namespaces should also be handled. I've made changes to this PR according to your comments, please take a look one more time. What do you think about this approach?

File: cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go [hunk 3]
```diff
@@ -128,6 +128,25 @@ func (c *client) EnsureNamespace(namespaceName string) error {
 		return errors.Wrap(err, "error creating core clientset")
 	}
 
+	_, err = clientset.CoreV1().Namespaces().Get(namespaceName, metav1.GetOptions{})
+	if err != nil {
+		if apierrors.IsAlreadyExists(err) {
```
Comment (ncdc) [inline cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go]: You won't get this error from a Get call

**Comment by ncdc** [comment]
@eromanova I'm curious to know when/where you ran into a situation where you couldn't list or get namespaces? Is that common?

**Comment by eromanova** [comment]
@ncdc I'm not so sure that it is a common case. But I had to deal with that in my environment (strong restrictions for user, only list namespaces permissions). I guess, the absence of one of these permissions is not the reason to fail ensureNamespace.

File: cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go [hunk 4]
```diff
@@ -128,14 +128,31 @@ func (c *client) EnsureNamespace(namespaceName string) error {
...
 
-	namespace := apiv1.Namespace{
-		ObjectMeta: metav1.ObjectMeta{
-			Name: namespaceName,
-		},
-	}
-	_, err = clientset.CoreV1().Namespaces().Create(&namespace)
-	if err != nil && !apierrors.IsAlreadyExists(err) {
-		return err
+	_, err = clientset.CoreV1().Namespaces().Get(namespaceName, metav1.GetOptions{})
```
Comment (ncdc) [inline cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go]: How about restructuring it like this?

```go
// Happy path - return quickly
if err == nil {
  return nil
}

if apierrors.IsForbidden(err) {
  // get was forbidden. see if list works

  namespaces, err := clientset.CoreV1().Namespaces().List(metav1.ListOptions{})
  if apierrors.IsForbidden(err) {
    // either return err, which means we halt work
    // or return nil, and either things will be ok (user has permissions to create CAPI resources but they can't check for namespace existence), or things won't (they can't create CAPI resources, or the namespace doesn't exist)
  }
  if err != nil {
    return err
  }
  // check the list
}

if !apierrors.IsNotFound(err) {
  // err is not Forbidden or NotFound - return it
  return err
}

// try to create
// ...

**Comment by vincepri** [comment]
@eromanova Did you have a chance to look at @ncdc's feedback?

File: cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go (hunk 4 above)
Comment (eromanova) [reply cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go]: @ncdc I'm sorry for long delay. Thank you so much for the proposal. Could you please take a look again.

**Comment by eromanova** [comment]
@vincepri I'm sorry it's been so long. I updated this PR, could you please take a look. Thanks in advance.
