### PR TITLE
🌱 Reconcile control plane resources in ClusterClass

### LINKED ISSUE #5049: Implement reconcile ControlPlane for managed topologies
**Detailed Description**

This is part of the activities for the implementation of the [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md). 

The ClusterTopologyReconciler, after reading the cluster class, the current cluster and computing the desired state, is required to reconcile current and desired state.

This issue is about implementing reconcile current and desired state for the cluster object and for the referenced infrastructure machine template, if required.

This should take care of:
- If the control plane requires an infrastructure machine template
   - Create the desired infrastructure machine template if it  does not exists.
   - Check that there are no incompatible changes between the current and the desired infrastructure machine template (see https://github.com/kubernetes-sigs/cluster-api/pull/4985)
   - Compute the diff between current and the desired infrastructure object using `newMergePatchHelper` (see https://github.com/kubernetes-sigs/cluster-api/pull/5034)
   - If there are diffs, apply create a new infrastructure machine template and update references in the desired control plane object (template rotation)

- Create the desired ControlPlane object if the current ControlPlane does not exists.
- Check that there are no incompatible changes between the current and the desired ControlPlane object (see https://github.com/kubernetes-sigs/cluster-api/pull/4985)
- Compute the diff between current and the desired ControlPlane object using `newMergePatchHelper` (see https://github.com/kubernetes-sigs/cluster-api/pull/5034)
- If there are diffs, apply them to the current ControlPlane object

**Anything else you would like to add:**

NOTE: Given how  reading the cluster class, the current cluster and computing the desired state are implemented it is possible to do following assumptions:
- Cluster class and related templates have been read and are all in the clusterTopologyClass struct.
- Current state of the cluster has been successfully read; please not that, at the first reconciliation, the current state is empty (with the exception of Cluster).
- The desired state has been fully computed and it is in the clusterTopologyState struct.

NOTE: The func must provide logs at different level to allow debug

/kind feature

### PR DESCRIPTION
**Pull request by killianmuldoon**
**What this PR does / why we need it**:
Implement the Control Plane reconcilition logic for the ClusterClass controller. This is built on top of #5072 right now, so only the final commit is relevant to the PR.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5049

### CODE REVIEW

File: controllers/topology/reconcile_state.go [hunk 1]
```diff
@@ -56,6 +58,69 @@ func (r *ClusterReconciler) reconcileInfrastructureCluster(ctx context.Context,
...
+// classRequiresInfrastructureMachineTemplate assesses whether or not a given cluster requires an InfrastructureMachineTemplate as part of the Cluster ControlPlane
+// TODO: Make this method used more widely across the code to check for this specific condition. There's a possible issue with using get here - getControlPlaneState uses a class passed to it.
+func (r *ClusterReconciler) classRequiresInfrastructureMachineTemplate(_ context.Context, desired *clusterTopologyState) (bool, error) {
+	if 2 == 1 {
+		return false, errors.New("mock error for linting")
+	}
+	// This is the basic check to see if an InfrastructureMachineTemplate reconciliation is needed.
+	return desired.controlPlane.infrastructureMachineTemplate != nil, nil
+
+	// TODO: Find out if it's worth the additional complexity to rewrite the check in this way.
```
Comment (killianmuldoon) [inline controllers/topology/reconcile_state.go:115]: This is something I'd like pointers on - the check as is - using only the existence of the Infrastructure in the desired state - may not be sufficient to cover edge cases, but checking the single source of truth - the clusterClass - for this value either means passing the class down the code or else running a client.Get in the middle of the reconcile function which complicates the error states and testing significantly.

Comment (sbueringer) [reply controllers/topology/reconcile_state.go:115]: What edge cases do we have?

I would have assumed it's the responsibility of the `computeControlPlane` part to set `infrastructureMachineTemplate` correctly so we don't have to double check in reconcile. 

I think we shouldn't call `getClass` again in any case. In my opinion there are just too many things which could have changed in the mean time to handle that correctly. I think it gets really really complicated if part of our reconcile code is based on a later version of our resources.

Comment (ykakarap) [reply controllers/topology/reconcile_state.go:115]: +1 to what @sbueringer said. 
Given that we are already using `class.clusterClass.Spec.ControlPlane.MachineInfrastructure != nil` everywhere as a check to see if we need an infra template in the control plane and the documentation for the field also suggests 
https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha4/clusterclass_types.go#L63-L70
the same thing I think it is fine to have a simple check instead of getting the cluster class again from the api server (could potentially bring an updated version of the cluster class).


> I think it gets really really complicated if part of our reconcile code is potentially based on a later version of relevant resources.

+1

File: controllers/topology/reconcile_state.go [hunk 2]
```diff
@@ -34,24 +39,88 @@ func (r *ClusterReconciler) reconcileState(ctx context.Context, current, desired
...
+
+	// If the ControlPlane requires an InfrastructureMachineTemplate
+	// TODO: Check to ensure this is in the clusterclass - make this a common function.
+	// There's a possible issue with using get here - getControlPlaneState uses a class passed to it.
+	// This function also adds a side effect as it's a network call to an outside component - makes testing much more difficult.
+	if ok, err := r.classRequiresInfrastructureMachineTemplate(ctx, desired); err == nil && ok {
+		cpInfraRef, err := getNestedRef(desired.controlPlane.object, "spec", "machineTemplate", "infrastructureRef")
+		if err != nil {
+			return errors.Wrapf(err, "failed to update the %s object,", desired.controlPlane.infrastructureMachineTemplate.GetKind())
+		}
```
Comment (ykakarap) [inline controllers/topology/reconcile_state.go:76]:
```suggestion
		cpInfraRef := objToRef(desired.controlPlane.infrastructureMachineTemplate)
```

File: controllers/topology/reconcile_state.go [hunk 3]
```diff
@@ -34,24 +39,88 @@ func (r *ClusterReconciler) reconcileState(ctx context.Context, current, desired
...
+
+		// Create or update the MachineInfrastructureTemplate fo the control plane.
```
Comment (ykakarap) [inline controllers/topology/reconcile_state.go:78]:
```suggestion
      // Create or update the MachineInfrastructureTemplate of the control plane.
```

Comment (ykakarap) [inline controllers/topology/reconcile_state.go:78]:
```suggestion
		// Create or update the MachineInfrastructureTemplate of the control plane.
```

File: controllers/topology/reconcile_state.go (hunk 2 above)
Comment (ykakarap) [reply controllers/topology/reconcile_state.go:76]: At this point the the infra ref in the desired control plane object is already set to the infra machine template that is in `desired` state : https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/topology/desired_state.go#L124-L128

File: controllers/topology/reconcile_state.go [hunk 4]
```diff
@@ -34,24 +39,88 @@ func (r *ClusterReconciler) reconcileState(ctx context.Context, current, desired
...
+			templateNamer: func() string {
+				return names.SimpleNameGenerator.GenerateName(fmt.Sprintf("%s-infrastructure", desired.controlPlane.infrastructureMachineTemplate.GetName()))
+			},
+		},
+		)
+		if err != nil {
+			return errors.Wrapf(err, "failed to update the %s object", desired.controlPlane.infrastructureMachineTemplate.GetKind())
+		}
+	}
+	// Create or update a ControlPlaneObject for the controlPlaneTopologyState.
```
Comment (ykakarap) [inline controllers/topology/reconcile_state.go:95]: Since the cpInfraRef can be potentailly changed (if changes were detected in the template we are creating a new template) we should make sure to update the machine infraRef in the contorl plane object here with
```
setNestedRef(desired.controlPlane.object, cpInfraRef, "spec", "machineTemplate", "infrastructureRef")
```

Comment (ykakarap) [reply controllers/topology/reconcile_state.go:95]: Context: `getNestedRef` does not get the pointer to the underlying ref in the object. It seems to create a new ObjectReference and set the values accordingly. So, if I am not wrong, updating the values in `cpInfraRef` will not updated the values in the controlPlaneObject. The ref needs to be updated manually.

File: controllers/topology/reconcile_state.go (hunk 1 above)
Comment (fabriziopandini) [reply controllers/topology/reconcile_state.go:115]: What about having

```
func (c *controlPlaneTopologyClass) HasInfrastructureMachine() bool {
	return c.infrastructureMachineTemplate != nil
}
```
So our code can be changed into 

```
func foo(class *clusterTopologyClass)  {
	if class.controlPlane.HasInfrastructureMachine() {
		// do something
	}
}
```

File: controllers/topology/reconcile_state.go [hunk 5]
```diff
@@ -56,6 +58,69 @@ func (r *ClusterReconciler) reconcileInfrastructureCluster(ctx context.Context,
...
+// updating the cluster where needed.
+func (r *ClusterReconciler) reconcileControlPlane(ctx context.Context, current, desired *clusterTopologyState) error {
+	log := ctrl.LoggerFrom(ctx)
+	// Set a default nil return function for the cleanup operation.
+	cleanup := func() error { return nil }
+
+	// If the ControlPlane requires an InfrastructureMachineTemplate
+	// TODO: Check to ensure this is in the clusterclass - make this a common function.
+	// There's a possible issue with using get here - getControlPlaneState uses a class passed to it.
+	// This function also adds a side effect as it's a network call to an outside component - makes testing much more difficult.
```
[the remark this answers is not in the document]
Comment (killianmuldoon) [reply controllers/topology/reconcile_state.go:71]: As pointed out by @sbueringer above, this could result in getting a different version of the class than what the desired state is based off of because it's another API server query at another point in time. This changes the reconcile from an isolated operation to one that has some possibly mutating dependency underneath it.

[the remark this answers is not in the document]
Comment (fabriziopandini) [reply controllers/topology/reconcile_state.go:71]: I agree if we are going to read the class again, but this should not happen because all the information are already there, right?

[the remark this answers is not in the document]
Comment (killianmuldoon) [reply controllers/topology/reconcile_state.go:71]: I don't think the class information is in either the desired or current state - so I think here it would have to be passed down the function chain in order to get access to it. Am I missing somewhere we can get access to the class?

[the remark this answers is not in the document]
Comment (sbueringer) [reply controllers/topology/reconcile_state.go:71]: If we need the class, we should pass it down. That's fine.

File: controllers/topology/reconcile_state.go (hunk 1 above)
Comment (killianmuldoon) [reply controllers/topology/reconcile_state.go]: I've updated the way this was done to bring the controlPlaneTopologyClass down the call chain and implemented a check like this. I'm still not really happy with the solution so it definitely bears further discussion.

File: controllers/topology/reconcile_state.go (hunk 2 above)
Comment (killianmuldoon) [reply controllers/topology/reconcile_state.go:76]: I've left this the same for the time being - but I think there's an overall question between this and the controlPlane.MachineInfrastructure check around how much  trust we're actually putting into the desired objects as sources of truth.

File: controllers/topology/reconcile_state.go (hunk 3 above)
Comment (killianmuldoon) [reply controllers/topology/reconcile_state.go]: 👍

File: controllers/topology/reconcile_state.go (hunk 4 above)
Comment (killianmuldoon) [reply controllers/topology/reconcile_state.go]: Thanks for catching this! It's a tough one to test for, so I've ended up checking if the resulting reference has a name like those resulting from TemplateRotation. If you see a better way to go about this please let me know.

File: controllers/topology/reconcile_state.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (killianmuldoon) [reply controllers/topology/reconcile_state.go:71]: I've made changes to bring the class down the full call chain, but I think this needs further discussion.

File: controllers/topology/util.go [hunk 6]
```diff
@@ -39,6 +39,11 @@ func infrastructureMachineTemplateNamePrefix(clusterName, machineDeploymentTopol
 	return fmt.Sprintf("%s-%s-infra-", clusterName, machineDeploymentTopologyName)
 }
 
+// infrastructureMachineTemplateNamePrefix calculates the name prefix for a InfrastructureMachineTemplate.
+func controlPlaneinfrastructureMachineTemplateNamePrefix(clusterName, controlPlaneName string) string {
+	return fmt.Sprintf("%s-%s-infra-", clusterName, controlPlaneName)
+}
```
Comment (fabriziopandini) [inline controllers/topology/util.go:45]:
```suggestion
// infrastructureMachineTemplateNamePrefix calculates the name prefix for a InfrastructureMachineTemplate.
func controlPlaneinfrastructureMachineTemplateNamePrefix(clusterName string) string {
	return fmt.Sprintf("%s-controlplane-", clusterName)
}
```

The same function should be used in compute

File: controllers/topology/reconcile_state.go [hunk 7]
```diff
@@ -20,6 +20,8 @@ import (
 	"context"
 	"fmt"
 
+	"k8s.io/apiserver/pkg/storage/names"
+
```
Comment (vincepri) [inline controllers/topology/reconcile_state.go:24]:
```suggestion
```

File: controllers/topology/reconcile_state.go [hunk 8]
```diff
@@ -55,6 +60,57 @@ func (r *ClusterReconciler) reconcileInfrastructureCluster(ctx context.Context,
...
+	// There's a possible issue with using get here - getControlPlaneState uses a class passed to it.
+	// This function also adds a side effect as it's a network call to an outside component - makes testing much more difficult.
+	if class.HasInfrastructureMachine() {
+		cpInfraRef, err := getNestedRef(desired.controlPlane.object, "spec", "machineTemplate", "infrastructureRef")
+		if err != nil {
+			return errors.Wrapf(err, "failed to update the %s object,", desired.controlPlane.infrastructureMachineTemplate.GetKind())
+		}
+
+		// Create or update the MachineInfrastructureTemplate of the control plane.
+		log.Info("updating", desired.controlPlane.infrastructureMachineTemplate.GroupVersionKind().String(), desired.controlPlane.infrastructureMachineTemplate.GetName())
```
Comment (vincepri) [inline controllers/topology/reconcile_state.go:81]:
```suggestion
		log.Info("Updating", desired.controlPlane.infrastructureMachineTemplate.GroupVersionKind().String(), desired.controlPlane.infrastructureMachineTemplate.GetName())
```

File: controllers/topology/reconcile_state.go [hunk 9]
```diff
@@ -295,7 +351,7 @@ func (r *ClusterReconciler) reconcileReferencedTemplate(ctx context.Context, in
 		// Create the new template.
 
 		// NOTE: it is required to assign a new name, because during compute the desired object name is enforced to be equal to the current one.
-		newName := in.templateNamer()
+		newName := names.SimpleNameGenerator.GenerateName(in.templateNamer())
 		in.desired.SetName(newName)
 
 		log.Info(fmt.Sprintf("rotating %s from %s to %s", in.desired.GroupVersionKind(), in.current.GetName(), newName))
```
Comment (vincepri) [inline controllers/topology/reconcile_state.go:357]:
```suggestion
		log.Info("Rotating template", "gvk", in.desired.GroupVersionKind(), "current", , in.current.GetName(), "desired", newName))
```

File: controllers/topology/util.go [hunk 10]
```diff
@@ -39,6 +39,11 @@ func infrastructureMachineTemplateNamePrefix(clusterName, machineDeploymentTopol
 	return fmt.Sprintf("%s-%s-infra-", clusterName, machineDeploymentTopologyName)
 }
 
+// infrastructureMachineTemplateNamePrefix calculates the name prefix for a InfrastructureMachineTemplate.
+func controlPlaneinfrastructureMachineTemplateNamePrefix(clusterName string) string {
```
Comment (vincepri) [inline controllers/topology/util.go:43]:
```suggestion
func controlPlaneInfrastructureMachineTemplateNamePrefix(clusterName string) string {
```

File: controllers/topology/reconcile_state_test.go [hunk 11]
```diff
@@ -203,6 +205,314 @@ func TestReconcileInfrastructureCluster(t *testing.T) {
...
+		{
+			name:    "Should create desired ControlPlane if the current does not exist",
+			class:   ccWithoutControlPlaneInfrastructure,
+			current: nil,
+			desired: &controlPlaneTopologyState{object: controlPlane1, infrastructureMachineTemplate: infrastructureMachineTemplate},
+			want:    &controlPlaneTopologyState{object: controlPlane1, infrastructureMachineTemplate: infrastructureMachineTemplate},
+			wantErr: false,
+		},
+		{
+			name:    "Fail on updating ControlPlaneObject with incompatible changes",
```
Comment (ykakarap) [inline controllers/topology/reconcile_state_test.go:253]: nit: may be add a word or 2 about change makes it incompatible.

**Review by vincepri — APPROVED** [review]
/approve
/lgtm
/retitle 🌱 Reconcile control plane resources in ClusterClass
