### PR TITLE
🐛 Fix webhook service references when the namespace is changed

### LINKED ISSUE #5010: clusterctl does not set target namespace in WebhookConfigurations/CRDs
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

When running `clusterctl-v0.4.0 init --infrastructure docker --target-namespace custom-target` the namespace in the WebhookConfigurations and CRDs is not updated accordingly.

**What did you expect to happen:**
`webhooks[].clientConfig.service.namespace ` should have been updated in all WebhookConfigurations (similar in CRDs).

**Anything else you would like to add:**
This suggests the feature is not heavily used :)

Probably that’s the code were it could/should be done: https://github.com/kubernetes-sigs/cluster-api/blob/ff43603648aeba6c8a139a4d59b1f1bcde58aa5b/cmd/clusterctl/client/repository/components.go#L296-L310

There is already a implementation here (credits to @asalkeld) (except that we don't have to handle WebhookConfigurations v1beta1): https://github.com/asalkeld/cluster-api/blob/2c4a1d21f772cb261f9b8a9d177415293ec801d4/cmd/clusterctl/client/repository/components.go#L319-L403

Action Items (AI):
* Adjust the code to also adjust the namespace in the WebhookConfigurations/CRDs (https://github.com/kubernetes-sigs/cluster-api/blob/ff43603648aeba6c8a139a4d59b1f1bcde58aa5b/cmd/clusterctl/client/repository/components.go#L296-L310)
* Improve unit test coverage
* Manual test with --target-namespace set (~ quick-start with --target-namespace)

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by asalkeld**
**What this PR does / why we need it**:
Currently when you deploy to a single namespace the webhooks do not have the correct namespaces specified. 
This PR fixes all the references.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5010

### CODE REVIEW

File: cmd/clusterctl/client/repository/components.go [hunk 1]
```diff
@@ -292,9 +301,73 @@ func addNamespaceIfMissing(objs []unstructured.Unstructured, targetNamespace str
 	return objs
 }
 
+func fixWebHookTargetNamespace(o unstructured.Unstructured, targetNamespace string) (unstructured.Unstructured, error) {
```
Comment (sbueringer) [inline cmd/clusterctl/client/repository/components.go:304]: Can you move this func below fixTargetNamespace? (just easier to read top-down imho)

Comment (sbueringer) [inline cmd/clusterctl/client/repository/components.go:304]: Can you move this func below fixTargetNamespace? (just easier to read top-down imho)

File: cmd/clusterctl/client/repository/components.go [hunk 2]
```diff
@@ -304,9 +377,16 @@ func fixTargetNamespace(objs []unstructured.Unstructured, targetNamespace string
 		if util.IsResourceNamespaced(o.GetKind()) {
 			o.SetNamespace(targetNamespace)
 		}
```
Comment (sbueringer) [inline cmd/clusterctl/client/repository/components.go:379]:
```suggestion
		}

```
nit

File: cmd/clusterctl/client/repository/components.go [hunk 3]
```diff
@@ -292,9 +301,73 @@ func addNamespaceIfMissing(objs []unstructured.Unstructured, targetNamespace str
 	return objs
 }
 
+func fixWebHookTargetNamespace(o unstructured.Unstructured, targetNamespace string) (unstructured.Unstructured, error) {
+	if o.GetKind() == mutatingWebhookConfigurationKind || o.GetKind() == validatingWebhookConfigurationKind {
```
Comment (sbueringer) [inline cmd/clusterctl/client/repository/components.go:305]: Could it be that we also have this annotation on the CRDs?

File: cmd/clusterctl/client/repository/components.go (hunk 1 above)
Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go:304]: I think we should rename the func because it also fixes CRDs

File: cmd/clusterctl/client/repository/components.go [hunk 4]
```diff
@@ -292,9 +301,73 @@ func addNamespaceIfMissing(objs []unstructured.Unstructured, targetNamespace str
...
+		}
+
+		whs := []admissionregistrationv1.MutatingWebhook{}
+		for _, w := range b.Webhooks {
+			if w.ClientConfig.Service != nil {
+				w.ClientConfig.Service.Namespace = targetNamespace
+			}
+			whs = append(whs, w)
+		}
+		b.Webhooks = whs
```
Comment (sbueringer) [inline cmd/clusterctl/client/repository/components.go:330]:
```suggestion
		for _, w := range b.Webhooks {
			if w.ClientConfig.Service != nil {
				w.ClientConfig.Service.Namespace = targetNamespace
			}
		}
```
That should also work (same for ValidatingWebhook)

File: cmd/clusterctl/client/repository/components_test.go [hunk 5]
```diff
@@ -182,12 +202,136 @@ func Test_fixTargetNamespace(t *testing.T) {
...
+			},
+		},
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
 			g := NewWithT(t)
 
-			got := fixTargetNamespace(tt.args.objs, tt.args.targetNamespace)
+			got, err := fixTargetNamespace(tt.objs, tt.targetNamespace)
+			g.Expect(err).To(Succeed())
```
Comment (sbueringer) [inline cmd/clusterctl/client/repository/components_test.go:334]:
```suggestion
			g.Expect(err).ToNot(HaveOccurred())
```
nit: We usually use that one when we just validate an `err`. We use `Succeed` when there's a function call in `Expect()`

**Review by sbueringer — COMMENTED** [review]
@asalkeld Thank you very much for taking care of this!!

File: cmd/clusterctl/client/repository/components.go (hunk 1 above)
Comment (asalkeld) [reply cmd/clusterctl/client/repository/components.go:304]: sure, can move it. My idea behind the name was it fixes the webhook references in the crd.. but if you have a name i'll happily change it.

File: cmd/clusterctl/client/repository/components.go (hunk 3 above)
Comment (asalkeld) [reply cmd/clusterctl/client/repository/components.go:305]: great catch, yes it looks like it. I'll fix straight away..

**Comment by asalkeld** [comment]
@sbueringer thanks for the review, I believe I have fixed everything your raised.

File: cmd/clusterctl/client/repository/components.go (hunk 1 above)
Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go]: @asalkeld

Ah, of course, wasn't thinking about that. The func also updates the injected secret references not only the webhooks. 

One idea I would have is `fixTargetNamespaceClusterWideResources` (so this includes CRDS, WebhookConfigurations and all the fields we have to patch inside them: secret ref + webhooks)

Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go]: Ah let's keep it. I think yours is good. Mine is not entirely correct because it only fixes CRDs/Webhooks. Let's just count the secret ref overall as a part of a webhook (which it is of course because we need the secret for the webhook) and we're good ;)

**Comment by sbueringer** [comment]
Looks perfect, thx!

/lgtm

/retest
(for flakes)

/assign @fabriziopandini

File: cmd/clusterctl/client/repository/components.go [hunk 6]
```diff
@@ -304,9 +315,71 @@ func fixTargetNamespace(objs []unstructured.Unstructured, targetNamespace string
...
+		objs[i] = o
+	}
+	return objs, nil
+}
+
+func fixWebHookNamespaceReferences(o unstructured.Unstructured, targetNamespace string) (unstructured.Unstructured, error) {
+	annotations := o.GetAnnotations()
+	secretNamespacedName, ok := annotations["cert-manager.io/inject-ca-from"]
+	if ok {
+		secretName := strings.Split(secretNamespacedName, "/")[1]
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/repository/components.go:335]: Let's raise an error if split doesn't return 2 parts (the secret name is misconfigured)

File: cmd/clusterctl/client/repository/template.go [hunk 7]
```diff
@@ -124,7 +124,10 @@ func NewTemplate(input TemplateInput) (Template, error) {
 	// Ensures all the template components are deployed in the target namespace (applies only to namespaced objects)
 	// This is required in order to ensure a cluster and all the related objects are in a single namespace, that is a requirement for
 	// the clusterctl move operation (and also for many controller reconciliation loops).
-	objs = fixTargetNamespace(objs, input.TargetNamespace)
+	objs, err = fixTargetNamespace(objs, input.TargetNamespace)
+	if err != nil {
+		return nil, errors.Wrap(err, "failed fixTargetNamespace")
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/repository/template.go:129]: nit
```suggestion
		return nil, errors.Wrap(err, "failed to set the TargetNamespace in the template")
```

File: cmd/clusterctl/client/repository/components.go [hunk 8]
```diff
@@ -227,7 +233,10 @@ func NewComponents(input ComponentsInput) (Components, error) {
 	objs = addNamespaceIfMissing(objs, input.Options.TargetNamespace)
 
 	// fix Namespace name in all the objects
-	objs = fixTargetNamespace(objs, input.Options.TargetNamespace)
+	objs, err = fixTargetNamespace(objs, input.Options.TargetNamespace)
+	if err != nil {
+		return nil, errors.Wrap(err, "failed to fix TargetNamespace")
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/repository/components.go:238]: nit
```suggestion
		return nil, errors.Wrap(err, "failed to set the TargetNamespace on the components")
```

**Review by fabriziopandini — COMMENTED** [review]
@asalkeld thanks for picking up this work! really appreciated
lgtm apart a couple of nits

**Comment by asalkeld** [comment]
@fabriziopandini thanks for the review, I have made the changes you requested.

**Comment by vincepri** [comment]
@asalkeld Can you resolve the outdated / fixed conversations above?

**Review by alexander-demichev — APPROVED** [review]
thanks!

**Comment by sbueringer** [comment]
/lgtm
(including Fabrizios findings)

**Review by vincepri — APPROVED** [review]
/approve
