### PR TITLE
🐛 Fixes default control, worker machine counts overriding user specified values

### LINKED ISSUE #2560: clusterctl: Replica count env vars are not used
**What steps did you take and what happened:**
1. Use the following [cluster-template.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/6687035717d67c8da78f9cee225096a98ee1ac8b/templates/cluster-template.yaml)
1. Move this file to the appropriate location in the overrides directory 
    - `/Users/wfernandes/.cluster-api/overrides/infrastructure-aws/v0.5.0/cluster-template-kcp.yaml`
1. Set the aws provider url in `~/.cluster-api/clusterctl.yaml` 
    - ```
        name: "aws"
        url: "/Users/wfernandes/.cluster-api/overrides/infrastructure-aws/v0.5.0/infrastructure-components.yaml"
        type: "InfrastructureProvider"
       ```
1. After setting all the required env vars including `CONTROL_PLANE_MACHINE_COUNT` and `WORKER_MACHINE_COUNT`, run `clusterctl config cluster kcp-test --flavor kcp`.
1. Notice that the values of the `replicas` are `1` and `0` respectively. Which are the defaults of the flags `--control-plane-machine-count` and `--worker-machine-count`.
1. If the flags are used, then the `replicas` are set correctly.

**What did you expect to happen:**
Expected that the `COUNT` env var values to be used.

/kind bug
/area clusterctl

### PR DESCRIPTION
**Pull request by gab-satchi**
**What this PR does / why we need it**:
Replica counts set by the user through ENV vars or config file isn't being used as the flag options take precedence. The flags for control and worker counts default to 1 and 0 respectively and were overriding any values set as ENV vars. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2560

### CODE REVIEW

File: cmd/clusterctl/client/config.go [hunk 1]
```diff
@@ -305,13 +305,19 @@ func (c *clusterctlClient) templateOptionsToVariables(options GetClusterTemplate
 	if options.ControlPlaneMachineCount < 1 {
 		return errors.Errorf("invalid ControlPlaneMachineCount. Please use a number greater or equal than 1")
 	}
-	c.configClient.Variables().Set("CONTROL_PLANE_MACHINE_COUNT", strconv.Itoa(options.ControlPlaneMachineCount))
+	// set CONTROL_PLANE_MACHINE_COUNT if it isn't set already
+	if _, err := c.configClient.Variables().Get("CONTROL_PLANE_MACHINE_COUNT"); err != nil {
```
Comment (CecileRobertMichon) [inline cmd/clusterctl/client/config.go]: shouldn't this be checking `options.ControlPlaneMachineCount` like above for KubernetesVersion?

Comment (gab-satchi) [reply cmd/clusterctl/client/config.go]: do you mean checking that it isn't empty like we do for KubernetesVersion? The `options.ControlPlaneMachineCount` defaults to 1 so it will always be set.

File: cmd/clusterctl/client/config.go [hunk 2]
```diff
@@ -302,16 +302,30 @@ func (c *clusterctlClient) templateOptionsToVariables(options GetClusterTemplate
 	}
 
 	// the ControlPlaneMachineCount, if valid, can be used in templates using the ${ CONTROL_PLANE_MACHINE_COUNT } variable.
-	if options.ControlPlaneMachineCount < 1 {
-		return errors.Errorf("invalid ControlPlaneMachineCount. Please use a number greater or equal than 1")
+	if options.ControlPlaneMachineCount == nil {
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/config.go]: I'm wondering if we can validate ControlPlaneMachineCount also when the values comes from env variables.
What about something like 
```

//Check if set through env variable and default to 1 otherwise
if options.ControlPlaneMachineCount == nil {
	if value, err := c.configClient.Variables().Get("CONTROL_PLANE_MACHINE_COUNT"); err != nil {
		options.ControlPlaneMachineCount = utilpointer.Int32Ptr(1)
	} else {
		options.ControlPlaneMachineCount = utilpointer.Int32Ptr(value)
	}
} 

if *options.ControlPlaneMachineCount < 1 {
	return errors.Errorf("invalid ControlPlaneMachineCount. Please use a number greater or equal than 1")
}
c.configClient.Variables().Set("CONTROL_PLANE_MACHINE_COUNT", strconv.Itoa(*options.ControlPlaneMachineCount))
```

Comment (gab-satchi) [reply cmd/clusterctl/client/config.go]: sounds good. will update

**Comment by fabriziopandini** [comment]
Looks great @gab-satchi, thanks!
/lgtm

**Comment by fabriziopandini** [comment]
@vincepri over to you for a final pass

File: cmd/clusterctl/client/config.go [hunk 3]
```diff
@@ -17,6 +17,7 @@ limitations under the License.
 package client
 
 import (
+	utilpointer "k8s.io/utils/pointer"
```
Comment (vincepri) [inline cmd/clusterctl/client/config.go]: Do we need this rename alias?

File: cmd/clusterctl/client/config.go [hunk 4]
```diff
@@ -302,16 +303,40 @@ func (c *clusterctlClient) templateOptionsToVariables(options GetClusterTemplate
 	}
 
 	// the ControlPlaneMachineCount, if valid, can be used in templates using the ${ CONTROL_PLANE_MACHINE_COUNT } variable.
-	if options.ControlPlaneMachineCount < 1 {
+	if options.ControlPlaneMachineCount == nil {
+		//Check if set through env variable and default to 1 otherwise
```
Comment (vincepri) [inline cmd/clusterctl/client/config.go]:
```suggestion
		// Check if set through env variable and default to 1 otherwise
```

File: cmd/clusterctl/client/config.go [hunk 5]
```diff
@@ -302,16 +303,40 @@ func (c *clusterctlClient) templateOptionsToVariables(options GetClusterTemplate
...
+	if *options.ControlPlaneMachineCount < 1 {
 		return errors.Errorf("invalid ControlPlaneMachineCount. Please use a number greater or equal than 1")
 	}
-	c.configClient.Variables().Set("CONTROL_PLANE_MACHINE_COUNT", strconv.Itoa(options.ControlPlaneMachineCount))
+	c.configClient.Variables().Set("CONTROL_PLANE_MACHINE_COUNT", strconv.Itoa(int(*options.ControlPlaneMachineCount)))
 
 	// the WorkerMachineCount, if valid, can be used in templates using the ${ WORKER_MACHINE_COUNT } variable.
-	if options.WorkerMachineCount < 0 {
+	if options.WorkerMachineCount == nil {
+		//Check if set through env variable and default to 0 otherwise
```
Comment (vincepri) [inline cmd/clusterctl/client/config.go]:
```suggestion
		// Check if set through env variable and default to 0 otherwise
```

File: cmd/clusterctl/client/config.go [hunk 6]
```diff
@@ -302,16 +303,40 @@ func (c *clusterctlClient) templateOptionsToVariables(options GetClusterTemplate
 	}
 
 	// the ControlPlaneMachineCount, if valid, can be used in templates using the ${ CONTROL_PLANE_MACHINE_COUNT } variable.
-	if options.ControlPlaneMachineCount < 1 {
+	if options.ControlPlaneMachineCount == nil {
+		//Check if set through env variable and default to 1 otherwise
+		if v, err := c.configClient.Variables().Get("CONTROL_PLANE_MACHINE_COUNT"); err != nil {
+			options.ControlPlaneMachineCount = utilpointer.Int32Ptr(1)
+		} else {
+			i, err := strconv.Atoi(v)
```
Comment (vincepri) [inline cmd/clusterctl/client/config.go]: Minor: If we switch `ControlPlaneMachineCount` and `WorkerMachineCount` to be `*int64` instead, we can use https://golang.org/pkg/strconv/#ParseInt instead of `Atoi`

File: cmd/clusterctl/client/config.go [hunk 7]
```diff
@@ -302,16 +303,40 @@ func (c *clusterctlClient) templateOptionsToVariables(options GetClusterTemplate
...
+			if err != nil {
+				return errors.Errorf("invalid value for CONTROL_PLANE_MACHINE_COUNT set")
+			}
+			options.ControlPlaneMachineCount = utilpointer.Int32Ptr(int32(i))
```
Comment (vincepri) [inline cmd/clusterctl/client/config.go]: If we do the above suggestion, we can just set the value with `&i`

File: cmd/clusterctl/client/config.go [hunk 8]
```diff
@@ -302,16 +303,40 @@ func (c *clusterctlClient) templateOptionsToVariables(options GetClusterTemplate
...
+		}
+	}
+	if *options.ControlPlaneMachineCount < 1 {
 		return errors.Errorf("invalid ControlPlaneMachineCount. Please use a number greater or equal than 1")
 	}
-	c.configClient.Variables().Set("CONTROL_PLANE_MACHINE_COUNT", strconv.Itoa(options.ControlPlaneMachineCount))
+	c.configClient.Variables().Set("CONTROL_PLANE_MACHINE_COUNT", strconv.Itoa(int(*options.ControlPlaneMachineCount)))
```
Comment (vincepri) [inline cmd/clusterctl/client/config.go]: https://golang.org/pkg/strconv/#FormatInt

File: cmd/clusterctl/client/config.go [hunk 9]
```diff
@@ -302,16 +303,40 @@ func (c *clusterctlClient) templateOptionsToVariables(options GetClusterTemplate
...
+	if options.WorkerMachineCount == nil {
+		//Check if set through env variable and default to 0 otherwise
+		if v, err := c.configClient.Variables().Get("WORKER_MACHINE_COUNT"); err != nil {
+			options.WorkerMachineCount = utilpointer.Int32Ptr(0)
+		} else {
+			i, err := strconv.Atoi(v)
+			if err != nil {
+				return errors.Errorf("invalid value for WORKER_MACHINE_COUNT set")
+			}
+			options.WorkerMachineCount = utilpointer.Int32Ptr(int32(i))
```
Comment (vincepri) [inline cmd/clusterctl/client/config.go]: Same comments as above re:*int64

File: cmd/clusterctl/client/config.go [hunk 10]
```diff
@@ -76,10 +77,10 @@ type GetClusterTemplateOptions struct {
 	KubernetesVersion string
 
 	// ControlPlaneMachineCount defines the number of control plane machines to be added to the workload cluster.
```
Comment (vincepri) [inline cmd/clusterctl/client/config.go]: We should update this comment giving users directions on how to set these values with environment variables, and what's the default in case they aren't set

**Comment by vincepri** [comment]
@fabriziopandini over to your for final lgtm

/milestone v0.3.4

**Comment by wfernandes** [comment]
Reviewing...
/assign
