### PR TITLE
 🐛 Indicate in KCP conditions, when template cloning fails

### LINKED ISSUE #3540: KCP conditions need to indicate when it fails to clone linked templates
**What steps did you take and what happened:**

Spun up a cluster with a bad public ssh key.  
Saw no activity.
Eventually looking in:
```
:~$ kubectl -n capi-kubeadm-control-plane-system logs deploy/capi-kubeadm-control-plane-controller-manager -c manager
```

It was clear that it was an SSH key missing issue.  Since that admission controller denied the request, new machines not getting created, resulting in a starvation scenario during cluster bootstrapping, that isnt detectable via the `conditions` api.

**What did you expect to happen:**

I would be able to see this in the conditions of one of the api objects (`kubeadm get cluster --all-namespaces |grep -i conditions -A 10` might show something ? or maybe another one of the conditions ?)

**Anything else you would like to add:**

**Environment:**

- Cluster-api version: 0.3.8
/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by shysank**
**What this PR does / why we need it**:
Adds a new condition (~~ControlPlaneInitialized~~ MachinesCreatedCondition) to indicate failures during control plane initialization, specifically during:
1. Infrastructure reference resource creation
2. Bootstrap config resource creation
3. Machine resource creation
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3540

### CODE REVIEW

File: controlplane/kubeadm/controllers/helpers.go [hunk 1]
```diff
@@ -141,18 +142,24 @@ func (r *KubeadmControlPlaneReconciler) cloneConfigsAndGenerateMachine(ctx conte
 	})
 	if err != nil {
 		// Safe to return early here since no resources have been created yet.
+		conditions.MarkFalse(kcp, controlplanev1.ControlPlaneInitializedCondition, controlplanev1.InfrastructureResourceCreationFailedReason,
```
Comment (ncdc) [inline controlplane/kubeadm/controllers/helpers.go:145]: This method (`cloneConfigsAndGenerateMachine`) is called for both init and join, so we can't use a single `ControlPlaneInitializedCondition` here. I think we're going to need to think about this some more and how we report cloning failures. cc @fabriziopandini 

Also, see #3798 for a discussion on ControlPlaneInitialized

File: controlplane/kubeadm/controllers/helpers_test.go [hunk 2]
```diff
@@ -277,6 +277,73 @@ func TestCloneConfigsAndGenerateMachine(t *testing.T) {
...
+				Namespace:  cluster.Namespace,
+			},
+			Version: "v1.16.6",
+		},
+	}
+
+	fakeClient := newFakeClient(g, cluster.DeepCopy(), kcp.DeepCopy(), genericMachineTemplate.DeepCopy())
+
+	r := &KubeadmControlPlaneReconciler{
+		Client:   fakeClient,
```
Comment (ncdc) [inline controlplane/kubeadm/controllers/helpers_test.go:327]: Do we want to be creating new unit tests using the fake client?

Comment (vincepri) [reply controlplane/kubeadm/controllers/helpers_test.go:327]: If we can avoid it no, but KCP doesn't have testenv setup yet (or can't use it most of the time)

**Comment by ncdc** [comment]
Raising a review comment here - this PR needs to be about indicating when KCP is unable to create an InfraMachine from its template, or a BootstrapConfig from its template. It needs to be broader than solely control plane init.

File: controlplane/kubeadm/controllers/helpers.go (hunk 1 above)
Comment (shysank) [reply controlplane/kubeadm/controllers/helpers.go:145]: Can we return an error wrapped with Condition data, and give the responsibility up the stack to mark the conditions? Something like [this](https://gist.github.com/shysank/80d83ce12a48a7db6051bcc44c43d2cc).

Comment (ncdc) [reply controlplane/kubeadm/controllers/helpers.go:145]: I would prefer not to do this if we can avoid it. We recently worked to remove our RequeueAfterError, which is somewhat similar to this concept.

Comment (shysank) [reply controlplane/kubeadm/controllers/helpers.go:145]: Just want to get a discussion going. Apologies for not getting on this earlier. So, based on @ncdc's comments, and #3798 , it looks like `ControlPlaneInitializedCondition` is not the right condition to be used here because:
1. `cloneConfigsAndGenerateMachine ` is used for both kcp init, and scale up
2. `ControlPlaneInitializedCondition` has to do more with kubeadm creating `kubeadm-config` config map for cluster configuration.

I think there are two ways we can report cloning failures:

1. Use existing conditions with the message being the error returned from  `cloneConfigsAndGenerateMachine`. Eg. `Available` condition in case of kcp init. `ResizedCondition` in case of scale up (which is also used in cluster upgrade)
  **+**: 
    -  No change in API

   **-**:
    - Maybe not a very good ux experience, since the user has to parse the error message to find out if it's a cloning 
       error
     - Old condition may get overwritten. Eg. Scale up condition message that informs about the difference in number 
            in replicas  
  

2. Add a new condition, something like `MachineSpecNotGeneratedCondition` to report errors while cloning the templates. 
  **+**: 
    - Better ux, easy to parse, old conditions are left alone

   **-**:
    - API change
  
Sorry if I'm being a bit verbose, they are mostly for my understanding :) Please let me know wdyt @ncdc  @vincepri @fabriziopandini

Comment (ncdc) [reply controlplane/kubeadm/controllers/helpers.go:145]: I prefer option 2. Not sure about that name though. Would we want 1 condition for the infra cloning, 1 for bootstrap cloning, and 1 for machine creation? Or 1 that applies for all 3?

Comment (shysank) [reply controlplane/kubeadm/controllers/helpers.go:145]: I thought we could use 1 condition, and use different reasons for each one. I can't think of a good name though. Maybe `TemplatesCloned`? Or just keep it simple, and have a 1 to 1 mapping with 3 conditions as `InfraTemplateCloned`, ``BootstrapTemplateCloned`, and `MachineCreated`?

Comment (ncdc) [reply controlplane/kubeadm/controllers/helpers.go:145]: Maybe we could do just 1, and call it `MachinesCreated`. If it's false and an error severity, the reasons/messages can include the relevant information (such as "error cloning bootstrap template: <details>", "error clone infrastructure template: <details>", "error creating machine"). The reason I'm thinking it should be `MachinesCreated` (plural) is that we don't expose individual conditions for each replica, but we frequently do have multiple replicas, so this hopefully covers all the cases.

Comment (shysank) [reply controlplane/kubeadm/controllers/helpers.go:145]: Yeah that makes sense. Also, to confirm, we don't want to include errors that may occur during cleanup because it doesn't add any value in ux, right?

Comment (ncdc) [reply controlplane/kubeadm/controllers/helpers.go:145]: So basically one of these?
- clone infra, fail to clone bootstrap, cleanup (which fails)
- clone infra, clone bootstrap, fail to create machine, cleanup (which fails)

Maybe we can hold off putting that in conditions?

Comment (shysank) [reply controlplane/kubeadm/controllers/helpers.go:145]: Yeah, it doesn't give any useful information for the user to take action on. I think we can hold it off for later.

**Comment by shysank** [comment]
@ncdc I've made the changes based on the discussion, PTAL.

File: controlplane/kubeadm/controllers/controller.go [hunk 3]
```diff
@@ -213,6 +213,7 @@ func patchKubeadmControlPlane(ctx context.Context, patchHelper *patch.Helper, kc
 			controlplanev1.MachinesReadyCondition,
 			controlplanev1.AvailableCondition,
 			controlplanev1.CertificatesAvailableCondition,
+			controlplanev1.MachinesCreatedCondition,
```
Comment (vincepri) [inline controlplane/kubeadm/controllers/controller.go:216]: I'm ok having this in the summary, wdyt @fabriziopandini ?

**Review by vincepri — APPROVED** [review]
/lgtm

File: controlplane/kubeadm/controllers/controller.go (hunk 3 above)
Comment (fabriziopandini) [reply controlplane/kubeadm/controllers/controller.go:216]: I agree! IMO this should go a the top of the list because it should have priority over other conditions

File: controlplane/kubeadm/controllers/status.go [hunk 4]
```diff
@@ -72,6 +72,9 @@ func (r *KubeadmControlPlaneReconciler) updateStatus(ctx context.Context, kcp *c
 	// We are scaling down
 	case replicas > desiredReplicas:
 		conditions.MarkFalse(kcp, controlplanev1.ResizedCondition, controlplanev1.ScalingDownReason, clusterv1.ConditionSeverityWarning, "Scaling down control plane to %d replicas (actual %d)", desiredReplicas, replicas)
+
+		// This means that there was no error in generating the desired number of machine objects
+		conditions.MarkTrue(kcp, controlplanev1.MachinesCreatedCondition)
```
[the remark this answers is not in the document]
Comment (shysank) [reply controlplane/kubeadm/controllers/status.go:77]: Yeah I did, but since this condition encapsulates all of the machines' status, I didn't do that. Eg. if `cloneConfigsAndGenerateMachine ` succeeds for the first machine, and fails somewhere else after that, `MachinesCreatedCondition` will be set to true which will be misleading.  Does that make sense?

[the remark this answers is not in the document]
Comment (fabriziopandini) [reply controlplane/kubeadm/controllers/status.go:77]: +1, thanks for the explanation!
