### PR TITLE
✨ Reconcile MachineDeployment topologies

### LINKED ISSUE #5064: Implement reconcile MachineDeployments for managed topologies
**Detailed Description**

This is part of the activities for the implementation of the [ClusterClass proposal](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/202105256-cluster-class-and-managed-topologies.md). 

The ClusterTopologyReconciler, after reading the cluster class, the current cluster and computing the desired state, is required to reconcile current and desired state.

This issue is about implementing reconcile current and desired state for the MachineDeployments object.

The operation could be divided into two steps:

1. Comparing desired MachineDeployments and current MachineDeployments and identify
    a. desired MachineDeployments that does not exists yet
    b. desired MachineDeployments that already exists as a current Machine deployments
    c. current MachineDeployments that does not exists as desired

2. Handle the three above use cases, executing create & update (reconcile) or delete MachineDeployment

create & update (reconcile) MachineDeployment is similar to what already discussed in https://github.com/kubernetes-sigs/cluster-api/issues/5036 or in https://github.com/kubernetes-sigs/cluster-api/issues/5049, with the difference that it is required to reconcile the BootstrapConfigTemplate and the InfrastructureMachineTemplate before reconciling the MachineDeployment (Note: both BootstrapConfigTemplate and the InfrastructureMachineTemplate should handle template rotation similarly to what discussed in https://github.com/kubernetes-sigs/cluster-api/issues/5049)

delete MachineDeployment instead is straight forward (it should delete the machine deployment only, this will trigger template deletion as well).

**Anything else you would like to add:**

NOTE: Given how  reading the cluster class, the current cluster and computing the desired state are implemented it is possible to do following assumptions:
- Cluster class and related templates have been read and are all in the clusterTopologyClass struct.
- Current state of the cluster has been successfully read; please not that, at the first reconciliation, the current state is empty (with the exception of Cluster).
- The desired state has been fully computed and it is in the clusterTopologyState struct.

NOTE: The func must provide logs at different level to allow debug

/kind feature

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Still pretty WIP and contains Fabrizio's reconcile cluster PR for now.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5064

### CODE REVIEW

File: controllers/clustertopology_controller_sync.go [hunk 1]
```diff
@@ -99,3 +108,193 @@ func checkReferencedObjectsAreStrictlyCompatible(current, desired client.Object)
...
+func (r *ClusterTopologyReconciler) updateMachineDeployment(ctx context.Context, clusterName string, currentMD, desiredMD machineDeploymentTopologyState) error {
+	log := ctrl.LoggerFrom(ctx)
+
+	// Check if the current and desired InfrastructureMachineTemplate are compatible.
+	if err := checkReferencedObjectsAreCompatible(currentMD.infrastructureMachineTemplate, desiredMD.infrastructureMachineTemplate); err != nil {
+		return err
+	}
+	// Check if the current and desired BoostrapTemplate are compatible.
+	// NOTE: this should never happen (webhooks prevent it), but checking for extra safety.
+	if currentMD.bootstrapTemplate.GetNamespace() != desiredMD.bootstrapTemplate.GetNamespace() {
```
Comment (fabriziopandini) [inline controllers/clustertopology_controller_sync.go:192]: This check is already included in `checkReferencedObjectsAreCompatible`

File: controllers/clustertopology_controller_sync.go [hunk 2]
```diff
@@ -99,3 +108,193 @@ func checkReferencedObjectsAreStrictlyCompatible(current, desired client.Object)
...
+		return errors.Errorf("invalid operation: it is not possible to change namespace from %s to %s", currentMD.bootstrapTemplate.GetNamespace(), desiredMD.bootstrapTemplate.GetNamespace())
+	}
+
+	if err := r.rotateInfrastructureMachineTemplateIfNecessary(ctx, clusterName, currentMD, desiredMD); err != nil {
```
Comment (fabriziopandini) [inline controllers/clustertopology_controller_sync.go:196]: See discussion https://github.com/kubernetes-sigs/cluster-api/pull/5052#discussion_r686063018 given that a function for template rotation could be shared across a couple of PRs.

In case of template rotation, It is also required to delete old template after the reference on the machine deployment gets updated (see the proposed solution on the discussion above)

File: controllers/clustertopology_controller_sync.go [hunk 3]
```diff
@@ -99,3 +108,193 @@ func checkReferencedObjectsAreStrictlyCompatible(current, desired client.Object)
...
+// reconcileMachineDeployments reconciles the desired state of the MachineDeployment objects.
+func (r *ClusterTopologyReconciler) reconcileMachineDeployments(ctx context.Context, current, desired *clusterTopologyState) error {
+	currentMachineDeployments, err := getMachineDeploymentsByID(current.machineDeployments)
+	if err != nil {
+		return err
+	}
+	desiredMachineDeployments, err := getMachineDeploymentsByID(desired.machineDeployments)
+	if err != nil {
+		return err
+	}
```
Comment (fabriziopandini) [inline controllers/clustertopology_controller_sync.go:121]: nit: I will move this into calculateMachineDeploymentDiff, given that those variable are used only there

File: controllers/clustertopology_controller_sync.go [hunk 4]
```diff
@@ -99,3 +108,193 @@ func checkReferencedObjectsAreStrictlyCompatible(current, desired client.Object)
...
+
+	toCreate, toUpdate, toDelete := calculateMachineDeploymentDiff(currentMachineDeployments, desiredMachineDeployments)
```
Comment (fabriziopandini) [inline controllers/clustertopology_controller_sync.go:123]: Currently in the WIP for the other reconcile PR we are using reconcile for addressing both create and update.
If we are going to split Create and Update here, this will make a little bit complex to a shared utility for template rotation, which is kind of nice.

File: controllers/clustertopology_controller_sync.go (hunk 3 above)
Comment (sbueringer) [reply controllers/clustertopology_controller_sync.go:121]: I did that, but then I saw that I also need them below in the for loops. I could move them but then I have to change the returned data structures. It's relatively simple for create/delete but for update I would have to return a tuple of current/desired MD.

File: controllers/clustertopology_controller_sync.go (hunk 4 above)
Comment (sbueringer) [reply controllers/clustertopology_controller_sync.go:123]: Yup will merge those and use your util func

File: controllers/clustertopology_controller_sync.go (hunk 1 above)
Comment (sbueringer) [reply controllers/clustertopology_controller_sync.go:192]: It is but I only need the namespace comparison and not everything else which is compared in `checkReferencedObjectsAreCompatible` in this case. (I also commented accordingly on your PR)

File: controllers/clustertopology_controller_sync.go (hunk 2 above)
Comment (sbueringer) [reply controllers/clustertopology_controller_sync.go:196]: Yup. I align to your variant

File: controllers/clustertopology_controller_sync.go [hunk 5]
```diff
@@ -99,3 +108,193 @@ func checkReferencedObjectsAreStrictlyCompatible(current, desired client.Object)
...
+	for md := range current {
+		if _, ok := desired[md]; !ok {
+			toDelete = append(toDelete, md)
+		}
+	}
+
+	return toCreate, toUpdate, toDelete
+}
+
+func getMachineDeploymentsByID(mds []machineDeploymentTopologyState) (map[string]machineDeploymentTopologyState, error) {
```
[the remark this answers is not in the document]
Comment (sbueringer) [reply controllers/clustertopology_controller_sync.go:289]: Sgtm. I also wasn't sure what I should call the key

File: controllers/clustertopology_controller_sync.go (hunk 3 above)
Comment (sbueringer) [reply controllers/clustertopology_controller_sync.go:121]: I'll resolve it as it's solved by using a map in clusterTopologyState

File: controllers/clustertopology_controller_sync.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (sbueringer) [reply controllers/clustertopology_controller_sync.go:289]: func will be droped as we're now using a map in clusterTopologyState

**Comment by sbueringer** [comment]
Implementation is done. So open for review if somebody already wants. But I'll add the unit tests tomorrow and might find some issues, so no rush.

File: controllers/topology/reconcile_state.go [hunk 6]
```diff
@@ -62,17 +66,158 @@ func (r *ClusterReconciler) reconcileCluster(ctx context.Context, current, desir
...
+// updateMachineDeployment updates a MachineDeployment. Also rotates the corresponding Templates if necessary.
+func (r *ClusterReconciler) updateMachineDeployment(ctx context.Context, clusterName string, currentMD, desiredMD machineDeploymentTopologyState) error {
+	log := ctrl.LoggerFrom(ctx)
+
+	cleanupOldInfrastructureTemplate, err := r.reconcileReferencedTemplate(ctx, reconcileReferencedTemplateInput{
+		ref:     &desiredMD.object.Spec.Template.Spec.InfrastructureRef,
+		current: currentMD.infrastructureMachineTemplate,
+		desired: desiredMD.infrastructureMachineTemplate,
+		templateNamer: func() string {
+			// TODO: FIXME: Move the name generation into a shared func after #5070 has been merged
```
Comment (sbueringer) [inline controllers/topology/reconcile_state.go:144]: Open TODO after #5070 has been merged

File: controllers/topology/reconcile_state.go [hunk 7]
```diff
@@ -62,17 +66,158 @@ func (r *ClusterReconciler) reconcileCluster(ctx context.Context, current, desir
...
+	if err != nil {
+		return errors.Wrapf(err, "failed to update the %s %s", currentMD.object.GroupVersionKind(), currentMD.object.Name)
+	}
+
+	cleanupOldBootstrapTemplate, err := r.reconcileReferencedTemplate(ctx, reconcileReferencedTemplateInput{
+		ref:     desiredMD.object.Spec.Template.Spec.Bootstrap.ConfigRef,
+		current: currentMD.bootstrapTemplate,
+		desired: desiredMD.bootstrapTemplate,
+		templateNamer: func() string {
+			// TODO: FIXME: Move the name generation into a shared func after #5070 has been merged
```
Comment (sbueringer) [inline controllers/topology/reconcile_state.go:158]: Open TODO after #5070 has been merged

File: controllers/topology/reconcile_state.go [hunk 8]
```diff
@@ -62,17 +66,158 @@ func (r *ClusterReconciler) reconcileCluster(ctx context.Context, current, desir
...
+			return names.SimpleNameGenerator.GenerateName(fmt.Sprintf("%s-%s-bootstrap-", clusterName, desiredMD.object.Name))
+		},
+		compatibilityChecker: checkReferencedObjectsAreInTheSameNamespace,
+	})
+	if err != nil {
+		return errors.Wrapf(err, "failed to update the %s %s", currentMD.object.GroupVersionKind(), currentMD.object.Name)
+	}
+
+	// Check differences between current and desired MachineDeployment, and eventually patch the current object.
+	// TODO @fabrizio Do we also need the DeepCopy here?
```
Comment (sbueringer) [inline controllers/topology/reconcile_state.go:168]: @fabrizio Do we also need the DeepCopy here?

File: controllers/topology/reconcile_state.go [hunk 9]
```diff
@@ -62,17 +66,158 @@ func (r *ClusterReconciler) reconcileCluster(ctx context.Context, current, desir
...
+	patchHelper, err := newMergePatchHelper(currentMD.object, desiredMD.object, r.Client)
+	if err != nil {
+		return errors.Wrapf(err, "failed to create patch helper for %s %s", currentMD.object.GroupVersionKind(), currentMD.object.Name)
+	}
+	if patchHelper.HasChanges() {
+		log.Info("updating", currentMD.object.GroupVersionKind(), currentMD.object.GetName())
+		// TODO @fabrizio I see a few {"metadata":{"creationTimestamp":null}} patches in unit tests, I think it will also be there
+		// in "reality", any follow-up tasks?
```
Comment (sbueringer) [inline controllers/topology/reconcile_state.go:176]: @fabrizio I see a few `{"metadata":{"creationTimestamp":null}}` patches in unit tests, I think it will also be there in "reality", any follow-up tasks?

File: controllers/topology/reconcile_state.go [hunk 10]
```diff
@@ -62,17 +66,158 @@ func (r *ClusterReconciler) reconcileCluster(ctx context.Context, current, desir
 	// Check differences between current and desired state, and eventually patch the current object.
 	patchHelper, err := newMergePatchHelper(current.cluster, desired.cluster, r.Client)
 	if err != nil {
-		return errors.Wrap(err, "failed to create patch helper for the Cluster object")
+		return errors.Wrapf(err, "failed to create patch helper for %s %s", current.cluster.GroupVersionKind(), current.cluster.Name)
```
Comment (fabriziopandini) [inline controllers/topology/reconcile_state.go:69]:
```suggestion
		return errors.Wrapf(err, "failed to create patch helper for %s/%s", current.cluster.GroupVersionKind(), current.cluster.Name)
```
as per https://github.com/kubernetes-sigs/cluster-api/issues/5067#issuecomment-896857120 (same for the other error messages)

File: controllers/topology/reconcile_state.go [hunk 11]
```diff
@@ -96,40 +241,121 @@ func (r *ClusterReconciler) reconcileReferencedObject(ctx context.Context, curre
...
+// they are of the same GroupKind and in the same namespace.
+func checkReferencedObjectsAreCompatible(current, desired client.Object) error {
+	currentGK := current.GetObjectKind().GroupVersionKind().GroupKind()
+	desiredGK := desired.GetObjectKind().GroupVersionKind().GroupKind()
+
+	if currentGK.String() != desiredGK.String() {
+		return errors.Errorf("invalid operation: it is not possible to change the GroupKind of %s %s from %s to %s",
+			current.GetObjectKind().GroupVersionKind(), current.GetName(), currentGK, desiredGK)
+	}
+
```
Comment (fabriziopandini) [inline controllers/topology/reconcile_state.go:349]:
```suggestion
```

File: controllers/topology/reconcile_state.go [hunk 12]
```diff
@@ -62,17 +66,158 @@ func (r *ClusterReconciler) reconcileCluster(ctx context.Context, current, desir
...
+	patchHelper, err := newMergePatchHelper(currentMD.object, desiredMD.object, r.Client)
+	if err != nil {
+		return errors.Wrapf(err, "failed to create patch helper for %s %s", currentMD.object.GroupVersionKind(), currentMD.object.Name)
+	}
+	if patchHelper.HasChanges() {
+		log.Info("updating", currentMD.object.GroupVersionKind().String(), currentMD.object.GetName())
+		// TODO @fabrizio I see a few {"metadata":{"creationTimestamp":null}} patches in unit tests, I think it will also be there
+		// in "reality", any follow-up tasks?
+		if err := patchHelper.Patch(ctx); err != nil {
+			return errors.Wrapf(err, "failed to update the %s %s", currentMD.object.GroupVersionKind(), currentMD.object.Kind)
```
Comment (fabriziopandini) [inline controllers/topology/reconcile_state.go:178]: nit
```suggestion
			return errors.Wrapf(err, "failed to update %s %s", currentMD.object.GroupVersionKind(), currentMD.object.Kind)
```
(same for other error messages)

File: controllers/topology/reconcile_state_test.go [hunk 13]
```diff
@@ -203,6 +203,259 @@ func TestReconcileInfrastructureCluster(t *testing.T) {
...
+			wantErr:                                   false,
+		},
+		{
+			name:    "Should fail update MachineDeployment because of changed InfrastructureMachineTemplate kind",
+			current: []machineDeploymentTopologyState{md5},
+			desired: []machineDeploymentTopologyState{md5WithChangedInfrastructureMachineTemplateKind},
+			wantErr: true,
+		},
+		{
+			name:    "Should fail update MachineDeployment because of changed BootstrapTemplate namespace",
```
Comment (fabriziopandini) [inline controllers/topology/reconcile_state_test.go:307]: Note, this should never happen due to webhooks, I would remove this test

File: controllers/topology/reconcile_state_test.go [hunk 14]
```diff
@@ -203,6 +203,259 @@ func TestReconcileInfrastructureCluster(t *testing.T) {
...
+		},
+		{
+			name:    "No-op if current MachineDeployment is equal to desired",
+			current: []machineDeploymentTopologyState{md1},
+			desired: []machineDeploymentTopologyState{md1},
+			want:    []machineDeploymentTopologyState{md1},
+			wantErr: false,
+		},
+		{
+			name:    "Should update MachineDeployment with InfrastructureMachineTemplate rotation",
```
Comment (fabriziopandini) [inline controllers/topology/reconcile_state_test.go:276]: Let's have a similar test for bootstrap template

File: controllers/topology/reconcile_state_test.go [hunk 15]
```diff
@@ -203,6 +203,259 @@ func TestReconcileInfrastructureCluster(t *testing.T) {
...
+			name:    "Should update MachineDeployment with InfrastructureMachineTemplate and BootstrapTemplate rotation",
+			current: []machineDeploymentTopologyState{md4},
+			desired: []machineDeploymentTopologyState{md4WithRotatedTemplates},
+			want:    []machineDeploymentTopologyState{md4WithRotatedTemplates},
+			wantInfrastructureMachineTemplateRotation: map[string]bool{"md-4": true},
+			wantBootstrapTemplateRotation:             map[string]bool{"md-4": true},
+			wantErr:                                   false,
+		},
+		{
+			name:    "Should fail update MachineDeployment because of changed InfrastructureMachineTemplate kind",
```
Comment (fabriziopandini) [inline controllers/topology/reconcile_state_test.go:301]: Let's have a similar test for Bootstrap template (should pass)

File: controllers/topology/reconcile_state.go (hunk 8 above)
Comment (fabriziopandini) [reply controllers/topology/reconcile_state.go:168]: I have to this a little bit more about this and open a separated issue if required (in case we should modify the helper),

File: controllers/topology/reconcile_state.go (hunk 9 above)
Comment (fabriziopandini) [reply controllers/topology/reconcile_state.go:176]: This should not happen.
Could you kindly check if by chance you are setting creationTimestamp during in the desired objects (in your case with the objects builders) or if you are altering the desired objects via fakeClient calls (and eventually re-use them in different test cases)?.

File: controllers/topology/reconcile_state.go (hunk 8 above)
Comment (sbueringer) [reply controllers/topology/reconcile_state.go:168]: I'm also not sure why we need it in the other cases to be honest :)

File: controllers/topology/reconcile_state.go (hunk 10 above)
Comment (sbueringer) [reply controllers/topology/reconcile_state.go:69]: Ah, I didn't take the `gvk/name` format literally :) But sounds like a good idea. Will update accordingly

File: controllers/topology/reconcile_state_test.go (hunk 13 above)
Comment (sbueringer) [reply controllers/topology/reconcile_state_test.go:307]: My reasoning was that when we implement the check in our "prod" code (event though this situation shouldn't happen) it would also be good to have it not untested. In case you still want to delete it, let me know, it would be fine for me.

File: controllers/topology/reconcile_state_test.go (hunk 14 above)
Comment (sbueringer) [reply controllers/topology/reconcile_state_test.go:276]: Imho I already have one directly below (`"Should update MachineDeployment with BootstrapTemplate rotation"`)

(don't ask my why gofmt formats the next test case that so differently :))

File: controllers/topology/reconcile_state.go (hunk 9 above)
Comment (sbueringer) [reply controllers/topology/reconcile_state.go:176]: I tested it in isolation and the problem is definitely there (but I think we need a separate issue).
Variable content during `newMergePatchHelper`
```
originalJSON:
{"kind":"MachineDeployment","apiVersion":"cluster.x-k8s.io/v1alpha4","metadata":{"name":"md-8-delete","namespace":"default","resourceVersion":"999","creationTimestamp":null},"spec":{"clusterName":"","selector":{},"template":{"metadata":{},"spec":{"clusterName":"","bootstrap":{"configRef":{"kind":"FakeBoostrapTemplate","namespace":"default","name":"bootstrap-config-8-delete","apiVersion":"bootstrap.cluster.x-k8s.io/v1alpha4"}},"infrastructureRef":{"kind":"FakeInfrastructureMachineTemplate","namespace":"default","name":"infrastructure-machine-8-delete","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha4"}}}},"status":{}}

modifiedJSON:
{"kind":"MachineDeployment","apiVersion":"cluster.x-k8s.io/v1alpha4","metadata":{"name":"md-8-update","namespace":"default","creationTimestamp":null},"spec":{"clusterName":"","selector":{},"template":{"metadata":{},"spec":{"clusterName":"","bootstrap":{"configRef":{"kind":"FakeBoostrapTemplate","namespace":"default","name":"cluster-1-md-8-update-bootstrap-cpqw8","apiVersion":"bootstrap.cluster.x-k8s.io/v1alpha4"}},"infrastructureRef":{"kind":"FakeInfrastructureMachineTemplate","namespace":"default","name":"cluster-1-md-8-update-infra-h9ctm","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha4"}}}},"status":{}}

originalWithModifiedJSON:
{"apiVersion":"cluster.x-k8s.io/v1alpha4","kind":"MachineDeployment","metadata":{"name":"md-8-update","namespace":"default","resourceVersion":"999"},"spec":{"clusterName":"","selector":{},"template":{"metadata":{},"spec":{"bootstrap":{"configRef":{"apiVersion":"bootstrap.cluster.x-k8s.io/v1alpha4","kind":"FakeBoostrapTemplate","name":"cluster-1-md-8-update-bootstrap-cpqw8","namespace":"default"}},"clusterName":"","infrastructureRef":{"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha4","kind":"FakeInfrastructureMachineTemplate","name":"cluster-1-md-8-update-infra-h9ctm","namespace":"default"}}}},"status":{}}

data:
{"metadata":{"creationTimestamp":null,"name":"md-8-update"},"spec":{"template":{"spec":{"bootstrap":{"configRef":{"name":"cluster-1-md-8-update-bootstrap-cpqw8"}},"infrastructureRef":{"name":"cluster-1-md-8-update-infra-h9ctm"}}}}}
```

So my interpretation:
* creationTimestamp is nil in the marshalled JSON (both for current and desired)
* originalWithModifiedJSON creationTimestamp is dropped there
* as a result the merge patch from originalJSON to originalWithModifiedJSON contains the creationTimestamp

Note: CreationTimestamp is not a pointer `CreationTimestamp Time `json:"creationTimestamp,omitempty" protobuf:"bytes,8,opt,name=creationTimestamp"` (also not in the debugger), it's just marshalled as nil.

**Comment by sbueringer** [comment]
@fabriziopandini PTAL (findings either fixed (aka resolved) or answered)

File: controllers/topology/reconcile_state_test.go (hunk 13 above)
Comment (fabriziopandini) [reply controllers/topology/reconcile_state_test.go:333]: it is ok to have the test

**Comment by fabriziopandini** [comment]
lgtm pending rebase after #5070 is merged

File: controllers/topology/reconcile_state.go (hunk 9 above)
Comment (sbueringer) [reply controllers/topology/reconcile_state.go]: We debugged it locally. This only occurs when creationTimestamp is not set. But we're only using the patchHelper when we want to patch an already existing object => tl;dr not a problem we have in reality

File: controllers/topology/object_builders_test.go [hunk 16]
```diff
@@ -500,27 +500,27 @@ func (f *fakeControlPlane) Obj() *unstructured.Unstructured {
...
 type fakeMachineDeployment struct {
-	namespace              string
-	name                   string
-	bootstrapTemplate      *unstructured.Unstructured
-	infrastructureTemplate *unstructured.Unstructured
-	labels                 map[string]string
+	namespace                     string
+	name                          string
+	bootstrapTemplate             *unstructured.Unstructured
+	infrastructureMachineTemplate *unstructured.Unstructured
```
Comment (vincepri) [inline controllers/topology/object_builders_test.go:506]: Why rename this? Given that's in a MachineDeployment seems pretty straightforward?

File: controllers/topology/reconcile_state.go [hunk 17]
```diff
@@ -62,17 +65,153 @@ func (r *ClusterReconciler) reconcileCluster(ctx context.Context, current, desir
...
+	}
+	return nil
+}
+
+// calculateMachineDeploymentDiff compares two maps of machineDeploymentTopologyState and calculates which
+// MachineDeployments should be created, updated or deleted.
+func calculateMachineDeploymentDiff(current, desired map[string]machineDeploymentTopologyState) ([]string, []string, []string) {
+	toCreate := []string{}
+	toUpdate := []string{}
+	toDelete := []string{}
```
Comment (vincepri) [inline controllers/topology/reconcile_state.go:196]: Could we return a struct here instead?

File: controllers/topology/object_builders_test.go (hunk 16 above)
Comment (sbueringer) [reply controllers/topology/object_builders_test.go:506]: I kept it that way when I merged my variant of it with the one previously merged on master.

Mainly because it seemed like a good idea to me to keep it consistent with what we already have with `fakeControlPlaneTemplate`. (field as well as the With func)

File: controllers/topology/reconcile_state.go (hunk 17 above)
Comment (sbueringer) [reply controllers/topology/reconcile_state.go]: Done

File: controllers/topology/object_builders_test.go (hunk 16 above)
Comment (vincepri) [reply controllers/topology/object_builders_test.go:506]: Seems redundant when reading it, might make sense to keep it simple?

Comment (sbueringer) [reply controllers/topology/object_builders_test.go]: Makes sense, done

**Review by vincepri — APPROVED** [review]
/approve
/lgtm
