### PR TITLE
🐛 Retrieve only non-deleted Machines

### LINKED ISSUE #1352: Deleting all machines fails because it can't delete Nodes
/kind bug

**What steps did you take and what happened:**
1. `k delete ma --all`
1. It gets in an endless error loop:

```
I0830 18:17:17.829574       1 machine_controller.go:186] Deleting node "ip-10-0-0-140.ec2.internal" for machine "test1-controlplane-2"
E0830 18:17:17.852462       1 machine_controller.go:188] Error deleting node "ip-10-0-0-140.ec2.internal" for machine "test1-controlplane-2": Delete https://test1-apiserver-xxxxxxxxx.us-east-1.elb.amazonaws.com:6443/api/v1/nodes/ip-10-0-0-140.
ec2.internal: EOF
```

**What did you expect to happen:**
All machines get deleted

**Environment:**

- Cluster-api version: commit d495192f7

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1352

### CODE REVIEW

**Comment by vincepri** [comment]
We're already returning false if it's the last control plane or there are none https://github.com/kubernetes-sigs/cluster-api/blob/32c774a6f7d6b51ee14d26f5521d15a3f45b426f/controllers/machine_controller.go#L221

**Comment by ncdc** [comment]
/hold
want to check something real quick

File: controllers/machine_controller.go [hunk 1]
```diff
@@ -276,7 +276,10 @@ func (r *MachineReconciler) getMachinesInCluster(ctx context.Context, namespace,
 
 	machines := make([]*clusterv1.Machine, len(machineList.Items))
```
Comment (ncdc) [inline controllers/machine_controller.go]: With this change, we'll still have a slice whose length = `len(machineList.Items)`, but if we encounter a deleted Machine, we'll end up with at least one `nil` entry in the slice. I think we'll end up getting NPEs down the road in `util.GetControlPlaneMachines()`.

It's probably safer to do `var machines []*clusterv1.machine` along with `append` instead of an index-based assignment.

WDYT?

Comment (vincepri) [reply controllers/machine_controller.go]: Fixed! Great catch there

**Comment by ncdc** [comment]
Fix/squash commits then LGTM

**Comment by vincepri** [comment]
@ncdc Done
