### PR TITLE
🐛[KCP] fix for machine selection logic during scale down

### LINKED ISSUE #2760: [KCP]: Error in machine selection logic during scale down
**What steps did you take and what happened:**
1) make test-capd-e2e-full
2) I see that 3 node cluster came up, and after kcp upgrade step in the e2e test, replacement machine is created. scaleDownControlPlane() fails to find a machine to delete. Seeing this error: 
`failed to pick control plane Machine to mark for deletion`

**What did you expect to happen:**
I would expect it to pick one of the machines that has the old version and remove it.

**Anything else you would like to add:**
The reason this is happening is when there are multiple failure domains:
KCP scaleDownControlPlane() finds a failure domain with most machines, then among the machines that has UpgradeReplacementCreatedAnnotation, it tries to find a machine that is in that failure domain. But this is not necessarily the case always.

```
fd := controlPlane.FailureDomainWithMostMachines()
machinesInFailureDomain := selectedMachines.Filter(machinefilters.InFailureDomains(fd))
```

Say we have machines with following failure domains: {Machine1: fd1, Machine2: fd2, Machine3: fd2}. 
upgradeControlPlane() calls scaleDownControlPlane() with ownedMachines={Machine1: fd1, Machine2: fd2, Machine3: fd2}  and selectedMachines={Machine1: fd1}

In scaleDownControlPlane(), fd will be calculated as fd2 and among selectedMachines, it will try to find a machine that has fd2.

Example unit test for this: https://github.com/sedefsavas/cluster-api/pull/5
This is this reason https://github.com/kubernetes-sigs/cluster-api/pull/2758 failing.

/kind bug

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:
Select the failure domain with most machines in a smaller set of machines instead of all controlplane machines.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2760

### CODE REVIEW

**Comment by sedefsavas** [comment]
wrong repo sorry
/close

**Comment by sedefsavas** [comment]
@vincepri @wfernandes @detiber 
This PR fixes e2e issues. Can we target to add this to the next release?

File: controlplane/kubeadm/controllers/controller_test.go [hunk 1]
```diff
@@ -1685,8 +1692,11 @@ func TestKubeadmControlPlaneReconciler_scaleDownControlPlane_NoError(t *testing.
 		Machines: machines,
 	}
 
-	_, err := r.scaleDownControlPlane(context.Background(), cluster, kcp, machines, machines, controlPlane)
-	g.Expect(err).ToNot(HaveOccurred())
+	ml := clusterv1.MachineList{}
+	ml.Items = []clusterv1.Machine{*machines["two"]}
+	mll := internal.NewFilterableMachineCollectionFromMachineList(&ml)
+	_, err := r.scaleDownControlPlane(context.Background(), cluster, kcp, machines, mll, controlPlane)
+	g.Expect(err).To(HaveOccurred())
```
Comment (JoelSpeed) [inline controlplane/kubeadm/controllers/controller_test.go]: This expectation is now inconsistent with the test title which says `NoError`, perhaps we should keep the existing test as a NoError and make this a new test that expects an error, WDYT?

**Comment by wfernandes** [comment]
Currently reviewing and running tests locally.

**Comment by wfernandes** [comment]
After running `make test-capd-e2e`, the `Basic create` test was the only one that ran and it passed on my machine. 

The `Full upgrade` test didn't run.

I'm guessing this is intended behavior for now since we have yet to add the other component upgrades (coredns, etcd, kube-proxy) as part of the `Full upgrade` test as discussed in https://github.com/kubernetes-sigs/cluster-api/issues/2753

**Comment by wfernandes** [comment]
@detiber @vincepri for approval.
