### PR TITLE
🐛 Relax minLength for bootstrap.dataSecretName to 0

### LINKED ISSUE #12161: v1.10 `MinLength` validation breaks managed MPs
### What steps did you take and what happened?

The new validations added in #11949 cause errors for CAPZ deploying managed MachinePool clusters.

The `dataSecretName` is not used in our managed MP case, so historically we have set it to an empty string in our templates and in documentation. This now triggers an error:

```
spec.template.spec.bootstrap.dataSecretName in body should be at least 1 chars long
```

See kubernetes-sigs/cluster-api-provider-azure#5589 for more details

### What did you expect to happen?

Expected backward compatibility with previous behavior: i.e., no errors with an empty `dataSecretName`.

### Cluster API version

v1.10.1

### Kubernetes version

_No response_

### Anything else you would like to add?

We are trying to work around this by setting `dataSecretName` to "unused," but even if that works, it's fragile and hacky. Could we consider reverting this validation? I know we had to relax another validation in #12107.

### Label(s) to be applied

/kind bug

### PR DESCRIPTION
**Pull request by mboersma**
**What this PR does / why we need it**:

Changes the validation for Machine spec's `bootstrap.dataSecretName` to `// +kubebuilder:validation:MinLength=0`. This allows an empty string, which is an existing use case for managed MachinePools.

**Which issue(s) this PR fixes**:

Fixes #12161

/area bootstrap

### CODE REVIEW

**Comment by nawazkh** [comment]
Thank you for this! 
/lgtm

File: bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go [hunk 1]
```diff
@@ -458,7 +458,7 @@ type KubeadmConfigStatus struct {
 
 	// dataSecretName is the name of the secret that stores the bootstrap data script.
 	// +optional
-	// +kubebuilder:validation:MinLength=1
+	// +kubebuilder:validation:MinLength=0
```
Comment (sbueringer) [inline bootstrap/kubeadm/api/v1beta1/kubeadmconfig_types.go:461]: Just to double check. Do you really need this here as well?

I thought you are setting dataSecretName: "" *instead* of referencing a bootstrap object

**Comment by sbueringer** [comment]
@mboersma One question

File: api/v1beta2/machine_types.go [hunk 2]
```diff
@@ -696,7 +696,7 @@ type Bootstrap struct {
 	// dataSecretName is the name of the secret that stores the bootstrap data script.
 	// If nil, the Machine should remain in the Pending state.
 	// +optional
-	// +kubebuilder:validation:MinLength=1
+	// +kubebuilder:validation:MinLength=0
```
Comment (enxebre) [inline api/v1beta2/machine_types.go:699]: consider make this not a pointer in v1beta2 based on the outcome of https://github.com/kubernetes-sigs/cluster-api/pull/12153#discussion_r2077940571

Comment (sbueringer) [reply api/v1beta2/machine_types.go:699]: I think that should not be part of this PR

**Comment by fabriziopandini** [comment]
What is the use case for setting dataSecretName to ""?
TBH It doesn't seems a clean API to me

**Comment by mboersma** [comment]
> What is the use case for setting dataSecretName to ""?

In an Azure managed MachinePool, for example, `spec.template.spec.bootstrap.dataSecretName` is not actually used, so our templates and tests and docs set it to an empty string in that case. 

Now with CAPI v1.10.x, we see this error:
```
spec.template.spec.bootstrap.dataSecretName in body should be at least 1 chars long
```
We've had couple customers report it already, even though we haven't finished integrating CAPI v1.10.1 yet because of this.

We can work around it in CAPZ by setting the `dataSecretName` to "unused" everywhere, but this seems more backward-compatible (intentionally or otherwise).

**Comment by richardcase** [comment]
> In an Azure managed MachinePool, for example, `spec.template.spec.bootstrap.dataSecretName` is not actually used, so our templates and tests and docs set it to an empty string in that case.

This is a similar situation for AWS MacheinePopls

**Comment by sbueringer** [comment]
In my opinion this is another reason why we should stop reusing the MachineSpec struct between MD and MP.

We would be able to clean this up for MD without breaking MP if we wouldn't reuse the struct

**Review by damdo — COMMENTED** [review]
/lgtm

Is there a specific approver for this, or is it you @sbueringer ?

**Comment by sbueringer** [comment]
I would like to wait for a response from Fabrizio

**Comment by sbueringer** [comment]
cc @fabriziopandini ^^

**Comment by fabriziopandini** [comment]
I'm ok in unblocking this fix for v1beta1/v1.10, but I would like we seek for a better solution for v1beta2
/approve

**Comment by tamalsaha** [comment]
Thanks! Can we get v1.10.2?

**Comment by chrischdi** [comment]
> Thanks! Can we get v1.10.2?

It first needs a PR to cherry-pick it to release-1.10 branch.

If I'm right and plans do not change, v1.10.2 is planned to be released on 20th may.

https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/releases/release-1.11.md

**Comment by tamalsaha** [comment]
I see. An earlier patch release will be much appreciated as capz/capg/capa all are blocked on this pr.

**Comment by sbueringer** [comment]
Can someone open a manual cherry-pick for release-1.10 please?

**Comment by sbueringer** [comment]
> I'm ok in unblocking this fix for v1beta1/v1.10, but I would like we seek for a better solution for v1beta2 /approve

@richardcase @mboersma Can one of you please open an issue for that? 

I'll then link it accordingly in the v1beta2 & "Graduate MachinePool" umbrella issues.

**Comment by richardcase** [comment]
> I'm ok in unblocking this fix for v1beta1/v1.10, but I would like we seek for a better solution for v1beta2

I'll add it to the list tracking issue for v1beta2 machinepools

**Comment by damdo** [comment]
Here is the backport PR @sbueringer https://github.com/kubernetes-sigs/cluster-api/pull/12180
