### PR TITLE
🌱 Propagate timeout fields from MachineSet to Machine during Machine deletion

### LINKED ISSUE #10588: MachineSet Inplace update does not work during machine deletion
### What steps did you take and what happened?

There are values on a machine spec that impact how a machine is deleted.  These values can not be modified inplace from the MachineDeployment or MachineSet once a machine is in the process of being deleted. This can result in machines that cannot be torn down successfully.

Here's an example scenario.

1. Make a MachineDeployment with the default nodeDrainTimeout of 0s (which blocks indefinitely if a machine's node can't be drained)
2. Scale down the MachineDeployment in a way that causes a PDB to block a machine's node drain
3. Machine will get stuck in deletion forever

The scenario above is expected and not a bug. However if I add a 4th step here to try and unblock the machine teardown by setting nodeDrainTimeout to something like `5m`, the Machine will still be wedged forever despite `nodeDrainTimeout` being an inplace update field now #8111 

This means once a machine is being torn down, trying to modify any fields that influence how the machine is torn down (like nodeDrainTimeout) will not be applied in place.

### What did you expect to happen?

modifying nodeDrainTimeout on a machineDeployment should update the MachineSet and all machines in place... This inplace update doesn't occur when the machines are being deleted though.

### Cluster API version

main branch

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by davidvossel**
Fixes #10588 
/area machine

**What this PR does / why we need it**:

Machine's default to nodeDrainTimeout: 0s, which blocks indefinitely if a pod can't be evicted.  We can't change the nodeDrainTimeout in-place from the MachineDeployment or MachineSet after a machine is marked for deletion.

This results in a machine that wedged forever but can't be updated using the top level objects that own the machine. 

To fix this, this PR allows fields related to machine deletion to be updated in place even when the machine is marked for deletion. 

NOTE - I did not add unit tests yet for this PR. I want confirmation this is an acceptable approve before investing time into testing.

### CODE REVIEW

**Comment by enxebre** [comment]
Thanks @davidvossel change makes sense to me. Smoother deletion is actually one of the supporting use cases for inplace propagation. Let's include some unit tests.

See related https://github.com/kubernetes-sigs/cluster-api/issues/5880
https://github.com/kubernetes-sigs/cluster-api/issues/9285

**Comment by davidvossel** [comment]
> Let's include some unit tests.

@enxebre i extended the existing unit test to cover the case of updating a deleting machine.

File: internal/controllers/machineset/machineset_controller.go [hunk 1]
```diff
@@ -362,8 +362,21 @@ func (r *Reconciler) syncMachines(ctx context.Context, machineSet *clusterv1.Mac
...
+			patch := client.MergeFrom(m.DeepCopy())
+
+			// Set all other in-place mutable fields that impact the ability to tear down existing machines.
+			m.Spec.NodeDrainTimeout = machineSet.Spec.Template.Spec.NodeDrainTimeout
+			m.Spec.NodeDeletionTimeout = machineSet.Spec.Template.Spec.NodeDeletionTimeout
+			m.Spec.NodeVolumeDetachTimeout = machineSet.Spec.Template.Spec.NodeVolumeDetachTimeout
+
+			err := r.Client.Patch(ctx, m, patch)
+			if err != nil {
+				log.Error(err, "failed to update Machine", "Machine", klog.KObj(m))
```
Comment (enxebre) [inline internal/controllers/machineset/machineset_controller.go:377]: nit: can we use upper case here for log.Error(... according to https://github.com/kubernetes-sigs/cluster-api/pull/10613 cc @sbueringer

Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:377]: A better reference: https://cluster-api.sigs.k8s.io/developer/logging.html#log-messages :)

Comment (davidvossel) [reply internal/controllers/machineset/machineset_controller.go]: yep, no problem, done!

File: internal/controllers/machineset/machineset_controller.go [hunk 2]
```diff
@@ -362,8 +362,21 @@ func (r *Reconciler) syncMachines(ctx context.Context, machineSet *clusterv1.Mac
 	log := ctrl.LoggerFrom(ctx)
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:362]: Just trying to think through various cases where Machines belonging to MachineSets are deleted

1. MD is deleted

The following happens:
* MD goes away
* ownerRef triggers MS deletion
* MS goes away
* ownerRef triggers Machine deletion

=> Not relevant for this scenario, because the MS will already be gone when the deletionTimestamp is set on the Machines. In this case folks would have to modify the timestamps on each Machine individually.

I recently had a discussion with @vincepri, that we should maybe consider changing our MD deletion flow. Basically adding a finalizer on MD & MS, so MD & MS stick around until all Machines are gone. If we would do this,  the MS => Machine propagation of the timeouts implemented here would help for this case as well

2. MD is scaled down to 0

The following happens:
* MD scales down MS to 0
* MS deletes Machine

=> This PR helps in this case because the timeouts are then propagated from MS to Machine


3. MD rollout 

The following happens:
* Someone updates the MD (e.g. bump the Kubernetes version)
* MD creates a new MS and scales it up
* In parallel MD scales down the old MS to 0

=> In this scenario the current PR won't help, because the MD controller does not propagate the timeouts from MD to all MS (only to the new/current one, not to the old ones)

I see how this PR addresses scenario 3. Wondering if we want to solve this problem more holistically. (maybe I also missed some cases, not sure)

File: internal/controllers/machineset/machineset_controller.go [hunk 3]
```diff
@@ -362,8 +362,21 @@ func (r *Reconciler) syncMachines(ctx context.Context, machineSet *clusterv1.Mac
...
 	for i := range machines {
 		m := machines[i]
-		// If the machine is already being deleted, we don't need to update it.
+		// If the machine is already being deleted, we only need to sync
+		// the subset of fields that impact tearing down a machine
 		if !m.DeletionTimestamp.IsZero() {
+			patch := client.MergeFrom(m.DeepCopy())
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller.go:368]: Let's please use the patchHelper here (see e.g. l.1010), it's doing basically the same here, but I would prefer using it so we can profit from error handling & potential improvements here as well (e.g. logging etc.)

File: internal/controllers/machineset/machineset_controller_test.go [hunk 4]
```diff
@@ -1347,6 +1348,30 @@ func TestMachineSetReconciler_syncMachines(t *testing.T) {
...
 	}, 5*time.Second).Should(Succeed())
+
+	// Verify in-place mutable fields are updated on the deleting machine
+	ms.Spec.Template.Spec.NodeDrainTimeout = duration11s
+	ms.Spec.Template.Spec.NodeDeletionTimeout = duration11s
+	ms.Spec.Template.Spec.NodeVolumeDetachTimeout = duration11s
+	g.Expect(reconciler.syncMachines(ctx, ms, []*clusterv1.Machine{updatedInPlaceMutatingMachine, deletingMachine})).To(Succeed())
+	updatedDeletingMachine := deletingMachine.DeepCopy()
+
+	g.Eventually(func(g Gomega) {
```
Comment (sbueringer) [inline internal/controllers/machineset/machineset_controller_test.go:1359]: Eventually shouldn't be required here (syncMachines does synchronous calls and GetAPIReader() reads without cache)

File: internal/controllers/machineset/machineset_controller.go (hunk 3 above)
Comment (davidvossel) [reply internal/controllers/machineset/machineset_controller.go]: fixed

File: internal/controllers/machineset/machineset_controller_test.go (hunk 4 above)
Comment (davidvossel) [reply internal/controllers/machineset/machineset_controller_test.go]: fixed

File: internal/controllers/machineset/machineset_controller.go (hunk 2 above)
Comment (davidvossel) [reply internal/controllers/machineset/machineset_controller.go:362]: Here's what's going on... the use case is subtle, but an easy one to get trapped by.

* a MS is created with the default node drain timeout of (wait forever).
* The MS needs to scale down to zero (but not be deleted). The intent it to bring this MS back online at some point.
* The user discovers that the default node drain timeout is blocking the scale down to zero. The user likely only encounters this drain block the first time they scale down to zero because there are typically other nodes available during normal scale down operations which allows PDB to be satisfied.

The outcome is that the user is now trapped. They can't gracefully scale the MS down to zero because the default node drain timeout can't be updated on the machines. So the user is either forced to take some manual action to tear down the machines or delete the MS.

By allowing the node drain timeout to be modified while the machines are marked for deletion, we give the user a path to unblock themselves using the top level api (either MS or MD) rather than mutating individual machines or performing some other manual operation.

Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:362]: Yup got it, and makes sense. I was just saying that there are various cases with MD+MS where a MS is scaled down to zero. The implementation only coverd one of them. But it's fine for me to consider addressing the others in separate PRs. Would be probably just good to open an issue so we can track that (I can do that)

**Review by chrischdi — COMMENTED** [review]
Could we update the PR title to more reflect what is happening?

E.g.

`🌱 Allow inplace update of fields related to deletion during MachineSet scale to 0`

(as of that lgtm)

**Comment by sbueringer** [comment]
I renamed slightly differently. The scenarios are not entirely distinct and this is also part of fixing the other cases

**Comment by sbueringer** [comment]
Thx folks!

/hold cancel

I'll open the follow-up issue tomorrow

File: internal/controllers/machineset/machineset_controller.go (hunk 2 above)
Comment (sbueringer) [reply internal/controllers/machineset/machineset_controller.go:362]: Here's the follow-up issue: https://github.com/kubernetes-sigs/cluster-api/issues/10753

**Comment by sbueringer** [comment]
> Thx folks!
> 
> /hold cancel
> 
> I'll open the follow-up issue tomorrow

Here's the follow-up issue: https://github.com/kubernetes-sigs/cluster-api/issues/10753
