### PR TITLE
✨Improve error message for yaml unmarshal

### LINKED ISSUE #2495: clusterctl: improve error message when parsing templates fails
**What steps did you take and what happened:**
call `clusterctl config cluster` with an invalid template or a variable that makes your template an invalid yaml

You get an error: like 
```
Error: failed to parse yaml: failed to unmarshal yaml fragment: "apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3\nkind: HAProxyLoadBalancer\nmetadata:\n labels:\n  cluster.x-k8s.io/cluster-name: vsphere-quickstart\n name: vsphere-quickstart\n namespace: default\nspec:\n user:\n  authorizedKeys:\n  - ssh-rsa AAAA...\n  name: capv\n virtualMachineConfiguration:\n  cloneMode: linkedClone\n  datacenter: Datacenter\n  datastore: ssd01\n  diskGiB: 25\n  folder: TKG\n  memoryMiB: 8192\n  network:\n   devices:\n   - dhcp4: true\n    networkName: VM Network\n  numCPUs: 2\n  resourcePool: */Resources\n  server: vcenter.lab\n  template: capv-haproxy-v0.5.3-77-g224e0ef6\n": error converting YAML to JSON: yaml: line 25: did not find expected alphabetic or numeric character
````

Which is hard to debug, mostly because:

- the YAML is divided into documents (split by ---)
- then documents are processed one by one
- the error message `line 25: did not find expected alphabetic or numeric character is referred to the fragment, not to the whole YAML file`;

**What did you expect to happen:**
A bettor error management, that at least makes it easy to identify what document the error refers to.

E.g. failed to parse the 6th document in the provider yaml ...

**Anything else you would like to add:**
The func to be fixed is https://github.com/kubernetes-sigs/cluster-api/blob/308f931d5f0c457d6253efedffe7e860126c0744/cmd/clusterctl/pkg/internal/util/yaml.go#L56

**Environment:**

- Cluster-api version:v0.3.0-rc.2

/kind bug
/help
/area clusterctl

### PR DESCRIPTION
**Pull request by wfernandes**
**What this PR does / why we need it**:
Improves yaml unmarshal error messaging to focus on the document within a yaml file.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2495

### CODE REVIEW

File: cmd/clusterctl/internal/util/yaml.go [hunk 1]
```diff
@@ -103,3 +106,27 @@ func FromUnstructured(objs []unstructured.Unstructured) ([]byte, error) {
 
 	return JoinYaml(ret...), nil
 }
+
+func ordinalize(n int) string {
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/yaml.go]: wanna move this to `util` package?

Comment (fabriziopandini) [reply cmd/clusterctl/internal/util/yaml.go]: +1

Comment (wfernandes) [reply cmd/clusterctl/internal/util/yaml.go]: I can move this to util package.

If we find other uses for the go-humanize library, I don't mind pulling it in. 
Usually, I tend to not pull in other dependencies unless absolutely necessary. Since this "ordinalize" functionality is being used only here, I prefer not pulling in the library. 
That said, again, if there are other places in the CAPI that could use the go-humanize, I don't mind pulling it in.

Comment (wfernandes) [reply cmd/clusterctl/internal/util/yaml.go]: @vincepri Just to clarify, you are suggesting to move this to `cluster-api/util` package. Correct?

File: util/util_test.go [hunk 2]
```diff
@@ -647,3 +647,15 @@ func TestClusterToObjectsMapper(t *testing.T) {
...
+func TestOrdinalize(t *testing.T) {
+	g := NewWithT(t)
+
+	input := []int{0, 1, 2, 43, 4, 5, 106, 207, 1008, -109, -0}
+	expected := []string{"0th", "1st", "2nd", "43rd", "4th", "5th", "106th", "207th", "1008th", "-109th", "0th"}
+
+	g.Expect(len(input)).To(Equal(len(expected)))
+	for i, in := range input {
+		g.Expect(Ordinalize(in)).To(Equal(expected[i]))
+	}
```
Comment (JoelSpeed) [inline util/util_test.go]: On potential improvement for this test case would be to use the testCases struct and then `t.Run` pattern used in a lot of these tests. The benefit of this is that all test cases will get run no matter if one fails, at the moment, I think this test would fail early as soon as one of the cases fails. Very minor though as this is such a small method/test case, feel free to ignore

**Comment by vincepri** [comment]
@wfernandes are you able to finish off the comments? it'd be nice to get this improvement in before v0.3.3 is released on friday

**Comment by wfernandes** [comment]
@vincepri Yes. I'll get it done asap.
