### PR TITLE
:sparkles: Support for upgrades to Kubernetes 1.18

### LINKED ISSUE #2793: Ensure GetNodesClusterRoleName ClusterRole and ClusterRoleBindings exist when upgrading to Kubernetes v1.18
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
When upgrading to Kubernetes v1.18, nodes now need an additional 

**What did you expect to happen:**
When upgrading to Kubernetes 1.18, node bootstrapping requires additional permissions.
These are created by kubeadm when 1.18 is initialised, but upgrading requires remediation.

There are two ways to do this:
* Execute `kubeadm init phase bootstrap-token` 
* Create the roles defined in https://github.com/kubernetes/kubernetes/commit/b117a928a6c3f650931bdac02a41fca6680548c4 when upgrading to 1.18

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.3.2
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): 1.18.0
- OS (e.g. from `/etc/os-release`): N/A

/kind bug

### PR DESCRIPTION
**Pull request by randomvariable**
**What this PR does / why we need it**:
Adds the cluster roles for Kubernetes 1.18.

In addition, the following changes for e2e have been made:
* Default to 1.18 for all tests
* Change the self-hosted test to 1.16, as we want to ensure 1.16 as the minimum supported version
* Change the e2e upgrade test to upgrade from 1.16 through to 1.18 (so we can continue to test CoreDNS and etcd upgrades).
* Fixed NPE during etcd leadership move. Happened once, suspect during leader election.

Did initially try updating the CAPD tests before noticing the top-level e2e tests, but didn't realise the helper was in the framework already. CAPD e2e needs a bit of refactoring, so have left it out at present.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2793

### CODE REVIEW

File: test/e2e/kcp_upgrade.go [hunk 1]
```diff
@@ -92,20 +92,34 @@ func KCPUpgradeSpec(ctx context.Context, inputGetter func() KCPUpgradeSpecInput)
...
 			WaitForDNSUpgrade:           input.E2EConfig.GetIntervals(specName, "wait-machine-upgrade"),
 			WaitForEtcdUpgrade:          input.E2EConfig.GetIntervals(specName, "wait-machine-upgrade"),
 		})
 
+		By("Upgrading Kubernetes & kube-proxy to 1.18, CoreDNS to 1.6.7, and etcd to 3.4.3")
+		framework.UpgradeControlPlaneAndWaitForUpgrade(ctx, framework.UpgradeControlPlaneAndWaitForUpgradeInput{
+			ClusterProxy: input.BootstrapClusterProxy,
+			Cluster:      cluster,
+			ControlPlane: controlPlane,
+			//Valid image tags for v1.18.2
```
Comment (vincepri) [inline test/e2e/kcp_upgrade.go:114]:
```suggestion
			// Valid image tags for v1.18.2
```

**Comment by vincepri** [comment]
Code changes LGTM, waiting for CI signal

**Comment by randomvariable** [comment]
:( taking a look

File: controlplane/kubeadm/controllers/controller.go [hunk 2]
```diff
@@ -254,6 +254,12 @@ func (r *KubeadmControlPlaneReconciler) reconcile(ctx context.Context, cluster *
 		return ctrl.Result{Requeue: true}, nil
 	}
 
+	// Ensure kubeadm role bindings for v1.18+
+	if err := workloadCluster.AllowBoostrapTokensToGetNodes(ctx); err != nil {
```
Comment (ncdc) [inline controlplane/kubeadm/controllers/controller.go:258]: Do we need to do this before L224?

Comment (randomvariable) [reply controlplane/kubeadm/controllers/controller.go:258]: The role is only used for worker nodes, but doesn't hurt.

Comment (ncdc) [reply controlplane/kubeadm/controllers/controller.go:258]: So not all joins but specifically only non-CP joins?

Comment (neolit123) [reply controlplane/kubeadm/controllers/controller.go]: all joining nodes that use a kubeadm 1.18+ binary needs this rbac to be set in the cluster.

File: test/e2e/kcp_upgrade.go [hunk 3]
```diff
@@ -92,20 +92,34 @@ func KCPUpgradeSpec(ctx context.Context, inputGetter func() KCPUpgradeSpecInput)
...
 			EtcdImageTag:                "3.4.3-0",
-			DNSImageTag:                 "1.6.6",
+			DNSImageTag:                 "1.6.5",
 			KubernetesUpgradeVersion:    "v1.17.2",
 			WaitForMachinesToBeUpgraded: input.E2EConfig.GetIntervals(specName, "wait-machine-upgrade"),
 			WaitForDNSUpgrade:           input.E2EConfig.GetIntervals(specName, "wait-machine-upgrade"),
 			WaitForEtcdUpgrade:          input.E2EConfig.GetIntervals(specName, "wait-machine-upgrade"),
 		})
 
+		By("Upgrading Kubernetes & kube-proxy to 1.18, CoreDNS to 1.6.7, and etcd to 3.4.3")
```
Comment (fabriziopandini) [inline test/e2e/kcp_upgrade.go:109]: Is it required to do the upgrade twice?
an upgrade is a time expensive operation and this will impact all the PRs...

File: test/e2e/kcp_upgrade.go [hunk 4]
```diff
@@ -82,7 +82,7 @@ func KCPUpgradeSpec(ctx context.Context, inputGetter func() KCPUpgradeSpecInput)
 				Flavor:                   clusterctl.DefaultFlavor,
 				Namespace:                namespace.Name,
 				ClusterName:              fmt.Sprintf("cluster-%s", util.RandomString(6)),
-				KubernetesVersion:        input.E2EConfig.GetKubernetesVersion(),
+				KubernetesVersion:        "v1.16.4",
```
Comment (fabriziopandini) [inline test/e2e/kcp_upgrade.go:85]: What about introducing a new "MINIMUM_KUBERNETES_VERSION" variable?

File: test/e2e/self_hosted.go [hunk 5]
```diff
@@ -79,14 +79,16 @@ func SelfHostedSpec(ctx context.Context, inputGetter func() SelfHostedSpecInput)
...
+				LogFolder:              filepath.Join(input.ArtifactFolder, "clusters", input.BootstrapClusterProxy.GetName()),
+				ClusterctlConfigPath:   input.ClusterctlConfigPath,
+				KubeconfigPath:         input.BootstrapClusterProxy.GetKubeconfigPath(),
+				InfrastructureProvider: clusterctl.DefaultInfrastructureProvider,
+				Flavor:                 clusterctl.DefaultFlavor,
+				Namespace:              namespace.Name,
+				ClusterName:            fmt.Sprintf("cluster-%s", util.RandomString(6)),
+				// Self hosted should test the minimum supported Kubernetes version.
+				// v1.16.4 is the latest 1.16 series kindest/node version
+				KubernetesVersion:        "v1.16.4",
```
Comment (fabriziopandini) [inline test/e2e/self_hosted.go:91]: What about introducing a new "MINIMUM_KUBERNETES_VERSION" variable?

File: test/e2e/kcp_upgrade.go [hunk 6]
```diff
@@ -92,20 +92,34 @@ func KCPUpgradeSpec(ctx context.Context, inputGetter func() KCPUpgradeSpecInput)
...
+		By("Upgrading Kubernetes & kube-proxy to 1.17, CoreDNS to 1.6.5, and etcd to 3.4.3")
 		framework.UpgradeControlPlaneAndWaitForUpgrade(ctx, framework.UpgradeControlPlaneAndWaitForUpgradeInput{
 			ClusterProxy: input.BootstrapClusterProxy,
 			Cluster:      cluster,
 			ControlPlane: controlPlane,
-			//Valid image tags for v1.17.2
+			// Valid image tags for v1.17.2
 			EtcdImageTag:                "3.4.3-0",
-			DNSImageTag:                 "1.6.6",
+			DNSImageTag:                 "1.6.5",
```
Comment (fabriziopandini) [inline test/e2e/kcp_upgrade.go:102]: @sedefsavas what do you think about having variables for EtcdImageTag, DNSImageTag as well?
This will improve test re-usability

File: test/e2e/kcp_upgrade.go [hunk 7]
```diff
@@ -92,20 +92,34 @@ func KCPUpgradeSpec(ctx context.Context, inputGetter func() KCPUpgradeSpecInput)
...
 			WaitForEtcdUpgrade:          input.E2EConfig.GetIntervals(specName, "wait-machine-upgrade"),
 		})
 
+		By("Upgrading Kubernetes & kube-proxy to 1.18, CoreDNS to 1.6.7, and etcd to 3.4.3")
+		framework.UpgradeControlPlaneAndWaitForUpgrade(ctx, framework.UpgradeControlPlaneAndWaitForUpgradeInput{
+			ClusterProxy: input.BootstrapClusterProxy,
+			Cluster:      cluster,
+			ControlPlane: controlPlane,
+			// Valid image tags for v1.18.2
+			EtcdImageTag:                "3.4.3-0",
```
Comment (fabriziopandini) [inline test/e2e/kcp_upgrade.go:115]: If I'm not wrong, having hard coded EtcdImageTag and DNSImageTag can lead to problems in future when KubernetesVersion changes
@sedefsavas ^^?

File: test/e2e/kcp_upgrade.go (hunk 3 above)
Comment (randomvariable) [reply test/e2e/kcp_upgrade.go:109]: I would have thought we would want to exercise etcd and coredns upgrades, but there wasn't a change from 1.17 to 1.18 for etcd.

File: controlplane/kubeadm/internal/workload_cluster_rbac.go [hunk 8]
```diff
@@ -0,0 +1,150 @@
...
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      roleName,
+			Namespace: metav1.NamespaceSystem,
+		},
+		Rules: []rbacv1.PolicyRule{
+			{
+				Verbs:         []string{"get"},
+				APIGroups:     []string{""},
+				Resources:     []string{"configmaps"},
+				ResourceNames: []string{roleName},
```
Comment (ncdc) [inline controlplane/kubeadm/internal/workload_cluster_rbac.go:146]: Can't use roleName here (kubeadm:kubelet-config-x.y). Have to use the resource name without the kubeadm: prefix.

Comment (ncdc) [reply controlplane/kubeadm/internal/workload_cluster_rbac.go:146]: The kubeadm code has `configMapRBACName()` for the role name and `kubeadmconstants.GetKubeletConfigMapName()` for the resource name. They look very similar but they're different.

Comment (randomvariable) [reply controlplane/kubeadm/internal/workload_cluster_rbac.go]: After much head scratching I found out the same about exactly the same time as you commented :(

File: test/e2e/kcp_upgrade.go (hunk 3 above)
Comment (sedefsavas) [reply test/e2e/kcp_upgrade.go]: Since upgrade takes too long, one of the upgrades we can do ControlPlaneMachineCount=1.
It is a test scenario we want to add anyways.

**Comment by vincepri** [comment]
Reviewing

File: Makefile [hunk 9]
```diff
@@ -201,6 +219,9 @@ lint-full: $(GOLANGCI_LINT) ## Run slower linters to detect possible issues
 	cd $(E2E_FRAMEWORK_DIR); $(GOLANGCI_LINT) run -v --fast=false
 	cd $(CAPD_DIR); $(GOLANGCI_LINT) run -v --fast=false
 
+apidiff: $(GO_APIDIFF) ## Check for API differences
+	$(GO_APIDIFF) $(shell git rev-parse origin/master) --print-compatible
```
Comment (vincepri) [inline Makefile:223]: `go-apidiff` wasn't added here originally because it doesn't work on dirty trees and it could be confusing when used in development

File: Makefile [hunk 10]
```diff
@@ -529,6 +550,10 @@ clean-book: ## Remove all generated GitBook files
 clean-bindata: ## Remove bindata generated folder
 	rm -rf $(GOBINDATA_CLUSTERCTL_DIR)/manifest
 
+.PHONY: clean-manifests ## Reset manifests in config directories back to master
+clean-manifests:
+	git checkout master config bootstrap/kubeadm/config controlplane/kubeadm/config test/infrastructure/docker/config
```
Comment (vincepri) [inline Makefile:555]: Should this only be used during e2e running in CI?

File: controlplane/kubeadm/controllers/controller.go [hunk 11]
```diff
@@ -254,6 +254,11 @@ func (r *KubeadmControlPlaneReconciler) reconcile(ctx context.Context, cluster *
 		return ctrl.Result{Requeue: true}, nil
 	}
 
+	// Ensure kubeadm role bindings for v1.18+
```
Comment (vincepri) [inline controlplane/kubeadm/controllers/controller.go:257]: Should we expand this comment to add more color, specifically reasons why this is needed?

File: controlplane/kubeadm/internal/workload_cluster_etcd.go [hunk 12]
```diff
@@ -249,6 +249,9 @@ func (w *Workload) ForwardEtcdLeadership(ctx context.Context, machine *clusterv1
 	if leaderCandidate == nil {
 		return errors.New("leader candidate cannot be nil")
 	}
+	if leaderCandidate.Status.NodeRef == nil {
+		return errors.New("leader has no node reference")
+	}
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_etcd.go:254]: Do we have a test for this? It seems a like a race condition between scale up and scale down, where the newest node doesn't have a reference yet

File: controlplane/kubeadm/internal/workload_cluster_rbac.go [hunk 13]
```diff
@@ -0,0 +1,163 @@
...
+)
+
+// EnsureResource creates a resoutce if the target resource doesn't exist. If the resource exists already, this function will ignore the resource instead.
+func (w *Workload) EnsureResource(ctx context.Context, obj runtime.Object, testObj runtime.Object) error {
+	key, err := ctrlclient.ObjectKeyFromObject(obj)
+	if err != nil {
+		return errors.Wrap(err, "unable to derive key for resource")
+	}
+	err = w.Client.Get(ctx, key, testObj)
+	if err != nil && !apierrors.IsNotFound(err) {
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_rbac.go:57]:
```suggestion
	if err := w.Client.Get(ctx, key, testObj); err != nil && !apierrors.IsNotFound(err) {
```

File: controlplane/kubeadm/internal/workload_cluster_rbac.go [hunk 14]
```diff
@@ -0,0 +1,163 @@
...
+		return errors.Wrapf(err, "failed to determine if resource %s/%s already exists", key.Namespace, key.Name)
+	} else if err == nil {
+		// If object already exists, nothing left to do
+		return nil
+	}
+	if err := w.Client.Create(ctx, obj); err != nil {
+		if !apierrors.IsAlreadyExists(err) {
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_rbac.go:64]: Is this just to be extra safe?

File: controlplane/kubeadm/internal/workload_cluster_rbac.go [hunk 15]
```diff
@@ -0,0 +1,163 @@
...
+
+	// KubeletConfigMapRolePrefix defines base kubelet configuration ConfigMap role prefix.
+	KubeletConfigMapRolePrefix = "kubeadm:"
+
+	// KubeletConfigMapName defines base kubelet configuration ConfigMap name.
+	KubeletConfigMapName = "kubelet-config-%d.%d"
+)
+
+// EnsureResource creates a resoutce if the target resource doesn't exist. If the resource exists already, this function will ignore the resource instead.
+func (w *Workload) EnsureResource(ctx context.Context, obj runtime.Object, testObj runtime.Object) error {
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster_rbac.go:51]: Why do we need a second object in this function? Could we `DeepCopy()` the first one?

File: Makefile (hunk 10 above)
Comment (randomvariable) [reply Makefile:555]: You need it locally if you want to build all the images and restore all the yaml's back to their original state. Not needed in CI because we're going to throw away the tree at the end.

File: Makefile (hunk 9 above)
Comment (randomvariable) [reply Makefile:223]: Yeah, I found out the hard way. Would still like a way to run it locally.
Was *surprising* to see it.

File: controlplane/kubeadm/internal/workload_cluster_etcd.go (hunk 12 above)
Comment (randomvariable) [reply controlplane/kubeadm/internal/workload_cluster_etcd.go:254]: We have a test for it, but it was passing. Very Volkswagen. Trying to find out why.

File: controlplane/kubeadm/internal/workload_cluster_rbac.go (hunk 14 above)
Comment (randomvariable) [reply controlplane/kubeadm/internal/workload_cluster_rbac.go:63]: Yup, though granted the chance of it happening is slim to nil.

File: controlplane/kubeadm/internal/workload_cluster_rbac.go (hunk 15 above)
Comment (randomvariable) [reply controlplane/kubeadm/internal/workload_cluster_rbac.go:51]: Yes to the latter.

File: Makefile (hunk 10 above)
Comment (randomvariable) [reply Makefile:555]: Ah, got it. Test machine node ref is nil, but not the leader candidate.

File: controlplane/kubeadm/internal/workload_cluster_etcd.go (hunk 12 above)
Comment (randomvariable) [reply controlplane/kubeadm/internal/workload_cluster_etcd.go:254]: Test added

File: controlplane/kubeadm/controllers/controller.go (hunk 11 above)
Comment (randomvariable) [reply controlplane/kubeadm/controllers/controller.go:257]: Added link to k/k commit

File: Makefile (hunk 10 above)
Comment (vincepri) [reply Makefile:555]: Got it, what if a user locally isn't on master and had changes to those files?

File: Makefile (hunk 9 above)
Comment (vincepri) [reply Makefile:223]: Maybe let's remove the doc string so it doesn't show up in help?

File: Makefile (hunk 10 above)
Comment (randomvariable) [reply Makefile:555]: Ummmmmmm...I'll stick a pause and massive warning. Having something is better than manual clean up and accidentally filing a PR. I know @ncdc wants to change it so it doesn't even have this behaviour, and we use a temp dir in CAPV to avoid this issue.

File: test/e2e/kcp_upgrade.go (hunk 3 above)
Comment (randomvariable) [reply test/e2e/kcp_upgrade.go]: I'm not opposed. @vincepri any thoughts.
I think I might want do any of these optimisations in another PR.
