### PR TITLE
🐛 clusterctl: fix Certificate target namespace

### LINKED ISSUE #5369: Incorrect dns names in serving certificates in case of using custom target namespace
**What steps did you take and what happened:**
Initiate cluster api with my-namespace as target namespace: clusterctl init --target-namespace my-namespace

**What did you expect to happen:**
the capi-serving-cert certificate should contain dns names: 
  `capi-webhook-service.my-namespace.svc`
  `capi-webhook-service.my-namespace.svc.cluster.local`
 
Instead it contained:
  `capi-webhook-service.capi-system.svc`
  `capi-webhook-service.capi-system.svc.cluster.local` 

This causes problems when the custom resources are not in the provider's namespace.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.4.3
- KIND version: v0.11.1 go1.16.4 linux/amd64
- Kubernetes version: (use `kubectl version`): v1.22.1
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Bueringer <buringerst@vmware.com>

**What this PR does / why we need it**:

I think it's a bad way to fix the bug, as it depends on a specific dnsName format. Unfortunately, I don't have a better idea. Suggestions for other solutions welcome.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5369

### CODE REVIEW

File: cmd/clusterctl/client/repository/components.go [hunk 1]
```diff
@@ -42,16 +42,12 @@ const (
 	clusterRoleKind                    = "ClusterRole"
 	clusterRoleBindingKind             = "ClusterRoleBinding"
 	roleBindingKind                    = "RoleBinding"
+	certificateKind                    = "Certificate"
 	mutatingWebhookConfigurationKind   = "MutatingWebhookConfiguration"
 	validatingWebhookConfigurationKind = "ValidatingWebhookConfiguration"
 	customResourceDefinitionKind       = "CustomResourceDefinition"
 )
 
-const (
```
Comment (sbueringer) [inline cmd/clusterctl/client/repository/components.go:50]: Unused and doesn't make sense anymore. I suppose it's fine to delete it? (I can add it again if necessary)

File: cmd/clusterctl/client/repository/components.go [hunk 2]
```diff
@@ -439,6 +444,39 @@ func fixCRDWebhookNamespaceReference(o unstructured.Unstructured, targetNamespac
...
+	// - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
+	for i, dnsName := range dnsNames {
+		dnsNameSplit := strings.Split(dnsName, ".")
+		// Skip this dnsName if the dnsName doesn't have at least 3 segments.
+		if len(dnsNameSplit) < 3 {
+			continue
+		}
+
+		dnsNameSplit[1] = targetNamespace
+		dnsNames[i] = strings.Join(dnsNameSplit, ".")
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/repository/components.go:470]: could this be a simple replace of ".capi-system." with ".target-namespace."?

Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go:470]: The question is where do I get the source namespace from. If it's fine to take it from the Certificate itself it would be easy to do.

Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go:470]: And it's save as long as the namespace name is not part of the service name (which it isn't in our cases)

Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go]: I pushed a new version with replace. Please let me know if you prefer that one (then I'll squash).

File: cmd/clusterctl/client/repository/components.go [hunk 3]
```diff
@@ -439,6 +446,32 @@ func fixCRDWebhookNamespaceReference(o unstructured.Unstructured, targetNamespac
...
+	if !ok {
+		return o, nil
+	}
+
+	// Iterate through dnsNames and adjust the namespace.
+	// The dnsNames slice usually looks like this:
+	// - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
+	// - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
+	for i, dnsName := range dnsNames {
+		dnsNames[i] = strings.Replace(dnsName, originalNamespace, targetNamespace, 1)
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/repository/components.go:465]: this is ok if we assume original namespace is never used as a substring in other places. To makes it bullet proof we need to prepend/append a dot

Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go:465]: Sounds good.

Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go]: Done, ptal

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Comment by fabriziopandini** [comment]
@vincepri @CecileRobertMichon potential last minute fix to be added to the release
Also candidate for backport

File: cmd/clusterctl/client/repository/components.go [hunk 4]
```diff
@@ -439,6 +446,32 @@ func fixCRDWebhookNamespaceReference(o unstructured.Unstructured, targetNamespac
 	return o, errors.Errorf("failed to patch %s CustomResourceDefinition", version)
 }
 
+// fixCertificate fixes the dnsNames of cert-manager Certificates.
+func fixCertificate(o unstructured.Unstructured, originalNamespace, targetNamespace string) (unstructured.Unstructured, error) {
```
Comment (vincepri) [inline cmd/clusterctl/client/repository/components.go:450]: Can we add some more context on why this is needed here?

File: cmd/clusterctl/client/repository/components.go [hunk 5]
```diff
@@ -439,6 +446,32 @@ func fixCRDWebhookNamespaceReference(o unstructured.Unstructured, targetNamespac
...
+	dnsNames, ok, err := unstructured.NestedStringSlice(o.UnstructuredContent(), "spec", "dnsNames")
+	if err != nil {
+		return o, errors.Wrapf(err, "failed to get .spec.dnsNames from Certificate %s/%s", o.GetNamespace(), o.GetName())
+	}
+	// Return if we don't find .spec.dnsNames.
+	if !ok {
+		return o, nil
+	}
```
Comment (vincepri) [inline cmd/clusterctl/client/repository/components.go:458]: If there are no dnsNames, shoudn't we return an error?

Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go:458]: We can. I just wanted to be conservative here to not break the default case (without target namespace).

I'm not sure if we have providers out there which are not using dnsNames (not sure if they would work)

File: cmd/clusterctl/client/repository/components.go (hunk 4 above)
Comment (sbueringer) [reply cmd/clusterctl/client/repository/components.go]: Done

**Review by vincepri — APPROVED** [review]
/approve
/lgtm
/cherrypick release-0.4
