### PR TITLE
🐛 Fixing failed to install kind for e2e tests

### LINKED ISSUE #12316: Failed to install kind for e2e tests: syntax error
### Which jobs are flaking?

[capi-e2e-mink8s-release-1.10](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-1.10#capi-e2e-mink8s-release-1-10)

### Which tests are flaking?

Test environment initialization failed when attempting to install `kind`.

### Since when has it been flaking?

6/2/2025

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-mink8s-release-1-10/1929617003924951040

### Reason for failure (if possible)

```
Docker in Docker enabled, initializing...
================================================================================
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.all.forwarding = 1
Starting Docker: docker.
Waiting for docker to be ready, sleeping for 1 seconds.
================================================================================
Done setting up docker in docker.
+ WRAPPED_COMMAND_PID=[2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-mink8s-release-1-10/1929617003924951040#1:build-log.txt%3A2)37
+ wait 237
+ ./scripts/ci-e2e.sh
kind not found, installing
/home/prow/go/bin/kind: line 1: syntax error near unexpected token `newline'
/home/prow/go/bin/kind: line 1: `<!DOCTYPE html>'
+ EXIT_VALUE=2
+ set +o xtrace
Cleaning up after docker in docker.
================================================================================
Waiting [3](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-e2e-mink8s-release-1-10/1929617003924951040#1:build-log.txt%3A3)0 seconds for pods stopped with terminationGracePeriod:30
Cleaning up after docker
Waiting for docker to stop for 30 seconds
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
================================================================================
Done cleaning up after docker in docker.
```

### Anything else we need to know?

It seems possible that `curl` got an error document back rather than expected binary payload. If so, that would be out of our control, but perhaps we could retry the operation?

### Label(s) to be applied

/kind flake

### PR DESCRIPTION
**Pull request by PatrickLaabs**
**What this PR does / why we need it**:
This Pull Request adds a retry-mechanism for the script `./hack/ensure-kind.sh`.

I added a max retry attempt of 5. 

As seen in the issue #12316 the curl of the kind binary fails. The overall curl command is correct, so the guess is, that the URL did not correctly provided the binary to download at that specific time.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #12316

### CODE REVIEW

File: hack/ensure-kind.sh [hunk 1]
```diff
@@ -43,12 +43,32 @@ verify_kind_version() {
...
         mkdir -p "${GOPATH_BIN}"
       fi
-      curl -sLo "${GOPATH_BIN}/kind" "https://github.com/kubernetes-sigs/kind/releases/download/${MINIMUM_KIND_VERSION}/kind-${goos}-${goarch}"
+      
+      # Download the kind binary with retry logic.
+      # Retries up to $max_retries times in case of network or server errors.
+      # The '-f' flag in curl ensures it fails on HTTP errors.
+      max_retries=5
+      retry_count=0
+      until curl -sfLo "${GOPATH_BIN}/kind" "https://github.com/kubernetes-sigs/kind/releases/download/${MINIMUM_KIND_VERSION}/kind-${goos}-${goarch}"; do
```
Comment (sbueringer) [inline hack/ensure-kind.sh]: Should we try to use the curl retry flags intead? https://everything.curl.dev/usingcurl/downloads/retry.html

I don't know which error we're currently hitting so we might also want to use `--retry-all-errors`

Comment (PatrickLaabs) [reply hack/ensure-kind.sh]: Ah! I didn't knew about this one.
Shall we go with this one:
```
curl --retry 5 --retry-all-errors -sLo "${GOPATH_BIN}/kind" "https://github.com/kubernetes-sigs/kind/releases/download/${MINIMUM_KIND_VERSION}/kind-${goos}-${goarch}"
```
?

Comment (sbueringer) [reply hack/ensure-kind.sh]: Sounds good, thx!

**Comment by sbueringer** [comment]
Thank you! Can you please squash and update the commit message to reflect the new implementation?

**Comment by chrischdi** [comment]
The commit message seems to still not match :-) otherwise lgtm.

Thanks!

**Comment by PatrickLaabs** [comment]
> The commit message seems to still not match :-) otherwise lgtm.
> 
> Thanks!

Yes, you were right. I missed that one - thanks for the reminder 👍

**Comment by sbueringer** [comment]
Thx!

/approve
