### PR TITLE
🐛  pass the cluster in to the get targets

### LINKED ISSUE #4361: MHC E2E tests are failing
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main has been failing since March 11th with:

```
Summarizing 2 Failures:
[Fail] When testing unhealthy machines remediation [It] Should successfully trigger machine deployment remediation 
/home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/machinehealthcheck_helpers.go:159
[Fail] When testing unhealthy machines remediation [It] Should successfully trigger KCP remediation 
/home/prow/go/src/sigs.k8s.io/cluster-api/test/framework/machinehealthcheck_helpers.go:159
```

possibly related to https://github.com/kubernetes-sigs/cluster-api/pull/3752

CAPZ tests (using nightly CAPI build) are also failing https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-capi-e2e-main, so this is not Docker specific. 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
- the e2e tests for mhc are failing for not being able to get the cluster using the remote client, but we already have the cluster in the calling func 
- 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4361

### CODE REVIEW

File: controllers/machinehealthcheck_targets.go [hunk 1]
```diff
@@ -185,11 +185,6 @@ func (r *MachineHealthCheckReconciler) getTargetsFromMHC(ctx context.Context, lo
 		return nil, nil
 	}
 
-	var cluster clusterv1.Cluster
-	if err := clusterClient.Get(ctx, client.ObjectKey{Namespace: mhc.Namespace, Name: mhc.Spec.ClusterName}, &cluster); err != nil {
-		return nil, errors.Wrapf(err, "error getting Cluster %s/%s for MachineHealthCheck %s", mhc.Namespace, mhc.Spec.ClusterName, mhc.Name)
-	}
```
Comment (vincepri) [inline controllers/machinehealthcheck_targets.go:191]: Shouldn't this client be `r.Client` and not the target Cluster client?

Comment (vincepri) [reply controllers/machinehealthcheck_targets.go:191]: Regardless of this, +1 passing the object in if we already have it

**Comment by fabriziopandini** [comment]
Uhh, it seems that https://github.com/kubernetes-sigs/cluster-api/pull/4354 introduced a regression 

> Panic: interface conversion: *framework.clusterProxy is not e2e.ClusterProxy: missing method ApplyWithArgs

cc @shysank

File: test/e2e/kcp_adoption.go [hunk 2]
```diff
@@ -52,7 +52,7 @@ type KCPAdoptionSpecInput struct {
 type ClusterProxy interface {
 	framework.ClusterProxy
 
-	ApplyWithArgs(context.Context, []byte, ...string) error
+	Apply(context.Context, []byte, ...string) error
```
Comment (sbueringer) [inline test/e2e/kcp_adoption.go:55]: This change seems to be unrelated, was it intended?

File: controllers/machinehealthcheck_targets.go (hunk 1 above)
Comment (sbueringer) [reply controllers/machinehealthcheck_targets.go:191]: Not sure if I got it correctly:
* the issue was that we were trying to get the cluster from the target cluster instead of the management cluster
* but we still need the clusterClient (as target cluster client) in l.211

File: test/e2e/kcp_adoption.go (hunk 2 above)
Comment (nader-ziada) [reply test/e2e/kcp_adoption.go:55]: a previous PR changed this, so was getting a panic, check Fabrizio comment above

**Comment by nader-ziada** [comment]
the e2e tests all passed, once #4371 merges, will rebase and this will be good to go

File: test/e2e/kcp_adoption.go (hunk 2 above)
Comment (sbueringer) [reply test/e2e/kcp_adoption.go:55]: Ah I see it now, didn't see the the connection the first time.

**Comment by nader-ziada** [comment]
failed on a time out, will try again

/test pull-cluster-api-e2e-full-main

**Comment by sbueringer** [comment]
Probably just stating the obvious but:
Timeout again. Looks to me like one of the machines does not come up because of a timeout when trying to create the DockerMachine:
```bash
E0324 20:21:46.852841       1 controller.go:302] controller-runtime/manager/controller/dockermachine "msg"="Reconciler error" "error"="failed to create worker DockerMachine: timed out waiting for the condition" "name"="k8s-conformance-nu20ky-md-0-njj9v" "namespace"="k8s-conformance-23gfsn" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="DockerMachine" 
I0324 20:21:48.423611       1 machine.go:357] controller-runtime/manager/controller/dockermachine "msg"="Setting Kubernetes node providerID" "name"="machine-pool-3h8bin-control-plane-q6gcw" "namespace"="machine-pool-2t0lry" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="DockerMachine" 
I0324 20:21:49.146323       1 machine.go:312] controller-runtime/manager/controller/dockermachine "msg"="Failed running command" "name"="k8s-conformance-nu20ky-md-0-njj9v" "namespace"="k8s-conformance-23gfsn" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="DockerMachine" "bootstrap data"="<user-data>==" "command"={"Cmd":"mkdir","Args":["-p","/run/kubeadm"],"Stdin":""} "stderr"="Error response from daemon: Container 317b0f95e3f6073f59a914837e124548924b45abd0545e909c2b68fc3f47318f is not running\n" "stdout"=""
````
(https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4367/pull-cluster-api-e2e-full-main/1374815742700032000/artifacts/clusters/bootstrap/controllers/capi-controller-manager/capi-controller-manager-7c6fc9fcbf-6dnxx/manager.log)

I'm not that familiar (yet) with CAPD and its e2e test but looks to me like we don't have enough logs (at the moment) to find out why we get those timeouts. 

/test pull-cluster-api-e2e-full-main

**Comment by nader-ziada** [comment]
@CecileRobertMichon ready for a a look
