### PR TITLE
:bug: Improve handling of patching and updates in MachineSet and MachineDeployment controllers

### LINKED ISSUE #1349: Deleting a Cluster does not delete related MachineDeployments
/kind bug

**What steps did you take and what happened:**
Deleting a Cluster does not clean up related MachineDeployments

**What did you expect to happen:**
Any MachineDeployments related to a Cluster be deleted when the Cluster is deleted

**Additional Information**
It appears that we were previously only patching Status for MachineDeployments, so the OwnerRef change was never committed back to the API Server. However, because of the lack of guarantees around how the patch semantics work with the controller-runtime client, we also need to be careful not to assume that we can just patch the resource or status for an object and have other pending changes not be overwritten.

**Environment:**

- Cluster-api version: latest from master

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:

Improves handling of patch and update semantics used by MachineSet and MachineDeployment controllers

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1349

### CODE REVIEW

File: controllers/cluster_controller_phases.go [hunk 1]
```diff
@@ -90,7 +90,7 @@ func (r *ClusterReconciler) reconcileExternal(ctx context.Context, cluster *clus
 
 	if !util.HasOwnerRef(obj.GetOwnerReferences(), ownerRef) {
 		obj.SetOwnerReferences(util.EnsureOwnerRef(obj.GetOwnerReferences(), ownerRef))
-		if err := r.Patch(ctx, obj, objPatch); err != nil {
+		if err := r.Client.Patch(ctx, obj, objPatch); err != nil {
```
Comment (ncdc) [inline controllers/cluster_controller_phases.go]: I think I remember a comment from the other day about doing this. If we're embedding, there is no need to make this change. If we want to require that it look like this, then we should move the embedded type to a proper field.

File: controllers/machinedeployment_controller.go [hunk 2]
```diff
@@ -111,7 +111,7 @@ func (r *MachineDeploymentReconciler) reconcile(ctx context.Context, d *clusterv
 		if d.Status.ObservedGeneration < d.Generation {
 			patch := client.MergeFrom(d.DeepCopy())
 			d.Status.ObservedGeneration = d.Generation
-			if err := r.Status().Patch(ctx, d, patch); err != nil {
+			if err := r.Client.Status().Patch(ctx, d.DeepCopy(), patch); err != nil {
```
Comment (ncdc) [inline controllers/machinedeployment_controller.go]: Could you please add a comment indicating why we're operating on a copy?

Comment (ncdc) [reply controllers/machinedeployment_controller.go]: Also, would it be better to avoid doing the DeepCopy twice (it's also on line 112)?

File: controllers/machinedeployment_sync.go [hunk 3]
```diff
@@ -341,7 +342,7 @@ func (r *MachineDeploymentReconciler) syncDeploymentStatus(allMSs []*clusterv1.M
 
 	patch := client.MergeFrom(d.DeepCopy())
 	d.Status = newStatus
-	return r.Status().Patch(context.Background(), d, patch)
+	return r.Status().Patch(context.Background(), d.DeepCopy(), patch)
```
Comment (ncdc) [inline controllers/machinedeployment_sync.go]: Would it be better to avoid doing the DeepCopy twice?

File: controllers/machinedeployment_sync.go [hunk 4]
```diff
@@ -413,7 +414,7 @@ func (r *MachineDeploymentReconciler) scaleMachineSetOperation(ms *clusterv1.Mac
 		*(ms.Spec.Replicas) = newScale
 		mdutil.SetReplicasAnnotations(ms, *(deployment.Spec.Replicas), *(deployment.Spec.Replicas)+mdutil.MaxSurge(*deployment))
 
-		err = r.Patch(context.Background(), ms, patch)
+		err = r.Client.Patch(context.Background(), ms, patch)
```
Comment (ncdc) [inline controllers/machinedeployment_sync.go]: Does this need to operate on a copy too?

File: controllers/machineset_controller.go [hunk 5]
```diff
@@ -386,9 +386,10 @@ func shouldExcludeMachine(machineSet *clusterv1.MachineSet, machine *clusterv1.M
 
 // adoptOrphan sets the MachineSet as a controller OwnerReference to the Machine.
 func (r *MachineSetReconciler) adoptOrphan(machineSet *clusterv1.MachineSet, machine *clusterv1.Machine) error {
+	patch := client.MergeFrom(machine)
```
Comment (ncdc) [inline controllers/machineset_controller.go]: deepcopy?

File: controllers/cluster_controller_phases.go (hunk 1 above)
Comment (detiber) [reply controllers/cluster_controller_phases.go]: I went with it to be more explicit and align with our other uses. It also helps with discoverability when searching the code for uses of Patch/Update :)

Comment (ncdc) [reply controllers/cluster_controller_phases.go]: I'm going to file an issue to make it a proper field.

File: controllers/machinedeployment_controller.go (hunk 2 above)
Comment (detiber) [reply controllers/machinedeployment_controller.go]: Will add a comment, but we need to deep copy twice, otherwise the if we try to use the same deep copy as the patch the patch will result in a noop.

File: controllers/machinedeployment_sync.go (hunk 3 above)
Comment (detiber) [reply controllers/machinedeployment_sync.go]: I don't think we can, will add a comment as to why.

File: controllers/machinedeployment_sync.go (hunk 4 above)
Comment (detiber) [reply controllers/machinedeployment_sync.go]: In this case, I don't think so, because we only update the Spec of the MachineSet from within the MachineDeployment controller.

File: controllers/machineset_controller.go (hunk 5 above)
Comment (detiber) [reply controllers/machineset_controller.go]: Not needed in this case, since we only update the Metadata of Machines in the MachineSet controller.

File: controllers/machinedeployment_controller.go (hunk 2 above)
Comment (vincepri) [reply controllers/machinedeployment_controller.go]: Can't we use the patch helper here and in the other places instead of issuing individual patches?

Comment (detiber) [reply controllers/machinedeployment_controller.go]: > Can't we use the patch helper here and in the other places instead of issuing individual patches?

Yes, but without massive refactoring it will be doing much more work than is needed since each individual place we are issuing patches or updates now do not update both status and non-status.

File: controllers/machinedeployment_controller.go [hunk 6]
```diff
@@ -111,7 +111,8 @@ func (r *MachineDeploymentReconciler) reconcile(ctx context.Context, d *clusterv
 		if d.Status.ObservedGeneration < d.Generation {
 			patch := client.MergeFrom(d.DeepCopy())
 			d.Status.ObservedGeneration = d.Generation
-			if err := r.Client.Status().Patch(ctx, d, patch); err != nil {
+			// Patch using a deep copy to avoid overwriting any unexpcted Spec/Metadata changes from the returned result
```
Comment (ncdc) [inline controllers/machinedeployment_controller.go]:
```suggestion
			// Patch using a deep copy to avoid overwriting any unexpected Spec/Metadata changes from the returned result
```

File: controllers/machinedeployment_controller.go [hunk 7]
```diff
@@ -111,7 +111,8 @@ func (r *MachineDeploymentReconciler) reconcile(ctx context.Context, d *clusterv
...
+			if err := r.Client.Status().Patch(ctx, d.DeepCopy(), patch); err != nil {
```
Comment (ncdc) [inline controllers/machinedeployment_controller.go]: Looking at this in more detail now - is this deep copy necessary, given that we return immediately following this?

Comment (detiber) [reply controllers/machinedeployment_controller.go]: @ncdc yes, you are correct, and we also shouldn't be requeueing the request if it has an empty label selector, either.
