### PR TITLE
:bug: requeue KCP object if ControlPlaneComponentsHealthyCondition is not yet true

### LINKED ISSUE #8786: Test flaking with Timed out waiting for 1 nodes to be created for MachineDeployment
### Which jobs are flaking?

e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1665614080297144320

### Which tests are flaking?

periodic-cluster-api-e2e-main
periodic-cluster-api-e2e-ipv6-main
periodic-cluster-api-e2e-dualstack-ipv6-main
periodic-cluster-api-e2e-dualstack-ipv6-main
periodic-cluster-api-e2e-ipv6-main

All failing at Should create a workload cluster

### Since when has it been flaking?

01-06-2023
https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#295d4f44852a6339ba54

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main

### Reason for failure (if possible)

To be analyzed.

### Anything else we need to know?

_No response_

### Label(s) to be applied

/kind flake

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

When the cluster is in the state that:
* The KCP in general is ready and
* All its conditions exist and are true, except the `ControlPlaneComponentsHealthyCondition` and
* KCP reconciles and has a no-op

Then the controller does reach the end of the `reconcile` function and does a `return ctrl.Result{}, nil`.

At the time of the relevant workload pods (etcd, kube-apiserver, kube-controller-manager, kube-scheduler) getting ready and reporting their ready state inside the workload cluster, no new additional event gets injected for the KCP object.

The KCP controller has to wait for an different change to the watched objects, or to reach the resync period to mark the condition to true.

This delays provisioning when the preflight checks for MachineSets are active, which also leads to flaky tests due to reaching the timeout of the test before reaching the resync period.

This PR solves this delay by ensuring to requeue in this special case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #8786

### CODE REVIEW

File: controlplane/kubeadm/internal/controllers/controller.go [hunk 1]
```diff
@@ -222,11 +222,22 @@ func (r *KubeadmControlPlaneReconciler) Reconcile(ctx context.Context, req ctrl.
...
-		// TODO: remove this as soon as we have a proper remote cluster cache in place.
-		// Make KCP to requeue in case status is not ready, so we can check for node status without waiting for a full resync (by default 10 minutes).
-		// Only requeue if we are not going in exponential backoff due to error, or if we are not already re-queueing, or if the object has a deletion timestamp.
-		if reterr == nil && !res.Requeue && res.RequeueAfter <= 0 && kcp.ObjectMeta.DeletionTimestamp.IsZero() {
-			if !kcp.Status.Ready {
+		if reterr == nil && kcp.ObjectMeta.DeletionTimestamp.IsZero() {
+			// TODO: remove this as soon as we have a proper remote cluster cache in place.
+			// Make KCP to requeue in case status is not ready, so we can check for node status without waiting for a full resync (by default 10 minutes).
+			// Only requeue if we are not going in exponential backoff due to error, or if we are not already re-queueing, or if the object has a deletion timestamp.
+			if !res.Requeue && res.RequeueAfter <= 0 {
```
Comment (killianmuldoon) [inline controlplane/kubeadm/internal/controllers/controller.go:229]: If I understand right we could fix this by having KCP watch nodes in the same way the the MachineSet controller does. It's probably not necessary to make this change now - but maybe we should update the comment here to make that clear.

Comment (chrischdi) [reply controlplane/kubeadm/internal/controllers/controller.go:229]: it's the below case which is new. I noted:

```
			// The alternative solution to this requeue would be watching the relevant pods inside each workload
			// cluster which would be very expensive.
```

But happy to add better wording there 🙂

File: controlplane/kubeadm/internal/controllers/controller.go [hunk 2]
```diff
@@ -222,11 +222,22 @@ func (r *KubeadmControlPlaneReconciler) Reconcile(ctx context.Context, req ctrl.
...
+				if !kcp.Status.Ready {
+					res = ctrl.Result{RequeueAfter: 20 * time.Second}
+				}
+			}
+
+			// Make sure KCP gets requeued if ControlPlaneComponentsHealthyCondition is still false.
+			// Otherwise KCP would only get requeued when KCP or the Cluster gets a change or via reaching the resyncperiod.
+			// That would lead to a delay in provisioning MachineDeployments when preflight checks are enabled.
+			// The alternative solution to this requeue would be watching the relevant pods inside each workload
+			// cluster which would be very expensive.
```
Comment (killianmuldoon) [inline controlplane/kubeadm/internal/controllers/controller.go:239]:
```suggestion
			// Requeue if ControlPlaneComponentsHealthyCondition is still false. Otherwise this condition can lead to a delay in provisioning MachineDeployments when MachineSet preflight checks are enabled.
			// The alternative solution to this requeue would be watching the relevant pods inside each workload cluster which would be very expensive.
```

File: controlplane/kubeadm/internal/controllers/controller.go (hunk 1 above)
Comment (killianmuldoon) [reply controlplane/kubeadm/internal/controllers/controller.go:229]: I mean this for the older comment - will add a suggestion.

Comment (killianmuldoon) [inline controlplane/kubeadm/internal/controllers/controller.go:229]: Should this also be `res.IsZero()` ?

File: controlplane/kubeadm/internal/controllers/controller.go [hunk 3]
```diff
@@ -222,11 +222,22 @@ func (r *KubeadmControlPlaneReconciler) Reconcile(ctx context.Context, req ctrl.
...
 
-		// TODO: remove this as soon as we have a proper remote cluster cache in place.
-		// Make KCP to requeue in case status is not ready, so we can check for node status without waiting for a full resync (by default 10 minutes).
-		// Only requeue if we are not going in exponential backoff due to error, or if we are not already re-queueing, or if the object has a deletion timestamp.
-		if reterr == nil && !res.Requeue && res.RequeueAfter <= 0 && kcp.ObjectMeta.DeletionTimestamp.IsZero() {
-			if !kcp.Status.Ready {
+		if reterr == nil && kcp.ObjectMeta.DeletionTimestamp.IsZero() {
+			// TODO: remove this as soon as we have a proper remote cluster cache in place.
+			// Make KCP to requeue in case status is not ready, so we can check for node status without waiting for a full resync (by default 10 minutes).
+			// Only requeue if we are not going in exponential backoff due to error, or if we are not already re-queueing, or if the object has a deletion timestamp.
```
Comment (killianmuldoon) [inline controlplane/kubeadm/internal/controllers/controller.go:228]:
```suggestion
			// Make KCP requeue in case node status is not ready, so we can check for node status without waiting for a full resync (by default 10 minutes). Only requeue if there is no error, Requeue or RequeueAfter and the object does not have a deletion timestamp.
			// The alternative solution would be to watch the control plane nodes in the Cluster - similar to how the MachineSet and MachineHealthCheck controllers watch the nodes under their control.
```

File: controlplane/kubeadm/internal/controllers/controller.go (hunk 1 above)
Comment (sbueringer) [reply controlplane/kubeadm/internal/controllers/controller.go:229]: Or one step further. we can move the res.IsZero check up to the reterr == nil check

Comment (sbueringer) [reply controlplane/kubeadm/internal/controllers/controller.go:229]: We would have to watch pods not nodes which I don't like: https://github.com/kubernetes-sigs/cluster-api/issues/8786#issuecomment-1645474641

Comment (killianmuldoon) [reply controlplane/kubeadm/internal/controllers/controller.go:229]: Let's also move the relevant part of the comments i.e. `Only requeue if there is no error, Requeue or RequeueAfter and the object does not have a deletion timestamp.` up above the condition.

**Comment by chrischdi** [comment]
Updated the comments + moved the `IsZero` up. I hope I did catch all suggestions of it 👍

**Review by killianmuldoon — COMMENTED** [review]
Thanks!

/lgtm

**Comment by sbueringer** [comment]
Thx!!

/approve

**Comment by sbueringer** [comment]
Let's see if it's cherry-pick'able in 1.4 and 1.3 as well
