### PR TITLE
🐛 Fix for TestServerSideApplyWithDefaulting

### LINKED ISSUE #10305: TestServerSideApplyWithDefaulting with error "KubeadmConfigTemplate.bootstrap.cluster.x-k8s.io "kct" not found"
### Which jobs are flaking?

- periodic-cluster-api-test-mink8s-main
- periodic-cluster-api-test-main
- periodic-cluster-api-test-release-1-6

### Which tests are flaking?

sigs.k8s.io/cluster-api/internal/controllers/topology/cluster/structuredmerge TestServerSideApplyWithDefaulting/no_spec_changes,_only_take_ownership_of_defaulted_fields_if_modified_is_defaulted

### Since when has it been flaking?

started before 12-03-2024

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#58dbd17da89b07beb438

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Label(s) to be applied

/kind flake
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
possibly Fixes #10305

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
@fabriziopandini @chrischdi if this looks ok, can we merge this before today's release? I have run tests multiple times on this PR, I haven't seen any failure yet.

File: internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go [hunk 1]
```diff
@@ -653,7 +653,7 @@ func TestServerSideApplyWithDefaulting(t *testing.T) {
 
 			// Enable the new defaulting logic (i.e. simulate the Cluster API update).
 			// The webhook will default the users field to `[{Name: "default-user"}]`.
-			g.Expect(env.Create(ctx, mutatingWebhookConfiguration)).To(Succeed())
+			g.Expect(env.CreateAndWait(ctx, mutatingWebhookConfiguration)).To(Succeed())
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go:656]: Sorry but this doesn't make sense.

The test is failing in l.683 because the KubeadmConfigTemplate doesn't exist in the local cache. Here we are waiting for MutatingWebhookConfiguration.

It probably fixes the issue by accident but I would prefer waiting for the right object (which is kct)

Comment (sbueringer) [reply internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go:656]: Let's add the following instead in l.652
```go
			// Let's wait until the initial KubeadmConfigTemplate is visible in the local cache. Otherwise the test fails below.
			g.Eventually(ctx, func(g Gomega) {
				g.Expect(env.Get(ctx, client.ObjectKeyFromObject(kct), &bootstrapv1.KubeadmConfigTemplate{})).To(Succeed())
			}, 5*time.Second).Should(Succeed())
```

Comment (adilGhaffarDev) [reply internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go:661]: I have added the wait for kct too.

Comment (sbueringer) [reply internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go:661]: Let's get rid of the CreateAndWait in l.661. We absolutely don't depend on mutatingWebhookConfiguration showing up in the local client cache

Comment (adilGhaffarDev) [reply internal/controllers/topology/cluster/structuredmerge/serversidepathhelper_test.go]: done

**Comment by sbueringer** [comment]
/approve

Feel free to cherry-pick if needed

**Comment by adilGhaffarDev** [comment]
same failure is happening in release 1-5: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-release-1-5/1773266012418871296
