### PR TITLE
:bug:  Include machinepools in descendant count

### LINKED ISSUE #4296: MachinePool not deleted on Cluster delete
**What steps did you take and what happened:**
Created a cluster with machine pool. Waited for successful creation (great stuff!), then deleted cluster. All resources properly deleted (including cluster) with the exception of the machine pool resource, which is orphaned and not cleaned up by the cluster controller due to missing Cluster resource (log message repeated):

```
E0311 12:11:38.317717       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="failed to get cluster \"jimmi-aws-cluster\" for machinepool \"jimmi-aws-cluster-mp-0\" in namespace \"default\": Cluster.cluster.x-k8s.io \"jimmi-aws-cluster\" not found" "controller"="machinepool" "name"="jimmi-aws-cluster-mp-0" "namespace"="default"
```

**What did you expect to happen:**
Machine pool deleted before cluster is deleted.

**Anything else you would like to add:**

**Environment:**

- Cluster-api version: v0.3.14
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.20.2
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by jimmidyson**
**What this PR does / why we need it**:

Without this, machinepool descendeants are ignored in descendant count deletion logic and can be orphaned and unable to delete without manually deleting the finalizer.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4296

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
This is candidate for backporting too

/lgtm
/assign @vincepri @CecileRobertMichon

File: controllers/cluster_controller.go [hunk 1]
```diff
@@ -326,7 +326,8 @@ func (c *clusterDescendants) length() int {
 	return len(c.machineDeployments.Items) +
 		len(c.machineSets.Items) +
 		len(c.controlPlaneMachines.Items) +
-		len(c.workerMachines.Items)
+		len(c.workerMachines.Items) +
+		len(c.machinePools.Items)
```
Comment (CecileRobertMichon) [inline controllers/cluster_controller.go:330]: is there a unit test we can add to validate this?

Comment (jimmidyson) [reply controllers/cluster_controller.go:330]: Yeah can do, didn't notice any existing ones but I'm happy to add one.

Comment (jimmidyson) [reply controllers/cluster_controller.go:330]: Added a simple unit test.

**Comment by jimmidyson** [comment]
@fabriziopandini Yes I agree - I'd like to see this backported - this bug is affecting us in v0.3.x so a new v0.3.15 release including this fix would be really appreciated if at all possible.

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

@jimmidyson please open a backport PR against the release-0.3 branch. Thanks for catching and fixing this!

**Comment by jimmidyson** [comment]
@CecileRobertMichon Backported in https://github.com/kubernetes-sigs/cluster-api/pull/4299 :smile:
