### PR TITLE
🐛  clusterctl: use newest release series of same contract

### LINKED ISSUE #4889: clusterctl installs wrong version of CAPV
**What steps did you take and what happened:**
I created a new kind cluster and ran `clusterctl init --infrastructure vsphere` and the output of the CAPV controller showed it installed manager 0.6.6.

**What did you expect to happen:**
I expected 0.7.8 to be installed.

**Anything else you would like to add:**
We fixed this using `clusterctl init --infrastructure vsphere:v0.7.8`.

**Environment:**

- Cluster-api version: `clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.20", GitCommit:"ea9dc4bdc2a9938325aab3817ece3e654873aaab", GitTreeState:"clean", BuildDate:"2021-06-30T22:21:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}`
- Minikube/KIND version: `kind v0.11.1 go1.16.4 darwin/amd64`
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-03-11T06:23:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): macOS 10.15

CC @randomvariable 

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by ykakarap**
Some providers have multiple releases with the same
contract. clusterctl should default to using release
for the given contract.

**What this PR does / why we need it**:
Used the latest release series of a provider if multiple releases use the same contract.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4889

### CODE REVIEW

**Comment by ykakarap** [comment]
/assign @CecileRobertMichon 

After this is merged, I will open a PR to backport this fix to the release-0.3 branch.

**Review by fabriziopandini — COMMENTED** [review]
@ykakarap can we get a unit test for this?

**Comment by sbueringer** [comment]
lgtm except @fabriziopandini's comment

File: cmd/clusterctl/api/v1alpha3/metadata_type.go [hunk 1]
```diff
@@ -46,6 +46,16 @@ type ReleaseSeries struct {
 	Contract string `json:"contract,omitempty"`
 }
 
+func (rs ReleaseSeries) newer(release ReleaseSeries) bool {
+	if rs.Major > release.Major {
```
Comment (CecileRobertMichon) [inline cmd/clusterctl/api/v1alpha3/metadata_type.go:50]: Can we use the semver library for the comparison? Might be better than duplicating logic here

Comment (ykakarap) [reply cmd/clusterctl/api/v1alpha3/metadata_type.go:50]: sure :)

File: cmd/clusterctl/api/v1alpha3/metadata_type.go [hunk 2]
```diff
@@ -62,12 +69,19 @@ func (m *Metadata) GetReleaseSeriesForVersion(version *version.Version) *Release
...
 		if contract == releaseSeries.Contract {
-			return &releaseSeries
+			if releaseSeries.newer(rs) {
+				rs = releaseSeries
+			}
 		}
 	}
-
-	return nil
+	if rs.Contract == "" {
```
Comment (CecileRobertMichon) [inline cmd/clusterctl/api/v1alpha3/metadata_type.go:83]: can this ever happen? The only case this could happen is if the passed in contract string is also `""` so that case that check should move up to the top so we don't wast time iterating through all the release series when contract is empty

Comment (CecileRobertMichon) [reply cmd/clusterctl/api/v1alpha3/metadata_type.go:83]: Oh nvm, this is to cover the "contract not found" case. To make this logic easier to read, could you either 1) add a small comment that says `// return nil if no release series matching the contract was found`, or 2) add a `found` variable that is set to true when `contract == releaseSeries.Contract` and change this to `if !found` ?

File: cmd/clusterctl/api/v1alpha3/metadata_type_test.go [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+			expectedReleaseSeries: &rsMultiplePerContract[0],
+		},
+		{
+			name:                  "Should get the newest release series with matching contract",
+			contract:              "v1alpha4",
+			releaseSeries:         rsMultiplePerContract,
+			expectedReleaseSeries: &rsMultiplePerContract[1],
+		},
+		{
+			name:                  "Should return nil is release series with matching contract found",
```
Comment (CecileRobertMichon) [inline cmd/clusterctl/api/v1alpha3/metadata_type_test.go:55]:
```suggestion
			name:                  "Should return nil if no release series with matching contract is found",
```

File: cmd/clusterctl/api/v1alpha3/metadata_type.go (hunk 2 above)
Comment (ykakarap) [reply cmd/clusterctl/api/v1alpha3/metadata_type.go:83]: > can this ever happen?
yes, it can. If there are not release series that match the given contract then `rs` is never set to anything and `rs.Contract` will remain the zero value (empty string). 

I realize it is a little uncommon to check like this but this essentially to check if we did or did not find a release series with a matching contract. I do it this way because the return type and `m.ReleaseSeries` types do not match (pointer vs struct).

Comment (ykakarap) [reply cmd/clusterctl/api/v1alpha3/metadata_type.go]: > Oh nvm, this is to cover the "contract not found" case.

yes :) 

Updated the PR. Went with option 2.

File: cmd/clusterctl/api/v1alpha3/metadata_type_test.go (hunk 3 above)
Comment (ykakarap) [reply cmd/clusterctl/api/v1alpha3/metadata_type_test.go]: so many typos 😅

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

Thanks @ykakarap! Are you also taking care of the backport to release-0.3?

**Comment by ykakarap** [comment]
> Are you also taking care of the backport to release-0.3? 

Yes, I will open a PR to backport it :)

**Comment by ykakarap** [comment]
Backport to release-0.3 PR: https://github.com/kubernetes-sigs/cluster-api/pull/4923
