### PR TITLE
🐛 Fix TestReconcileMachinePoolScaleToFromZero flakes

### LINKED ISSUE #8993: TestReconcileMachinePoolScaleToFromZero is flaky
This unit test has been flaky for some time now and the flake needs investigation.

Link to the flakes: 
- https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#7cc32c63e433b1623bf8
- https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#a4368a09373db948f1f9

/kind flake

### PR DESCRIPTION
**Pull request by loktev-d**
**What this PR does / why we need it**:
I've managed to reproduce the flakes on my local machine, it seems that the test flakes due to some random cache sync delays when creating a node with envtest, CAPI Testing documentation recommends using `CreateAndWait` for such cases.

**Which issue(s) this PR fixes**:
Fixes #8993 

/area machinepool

### CODE REVIEW

File: exp/internal/controllers/machinepool_controller_phases_test.go [hunk 1]
```diff
@@ -1780,7 +1780,7 @@ func TestReconcileMachinePoolScaleToFromZero(t *testing.T) {
 				},
 			},
 		}
-		g.Expect(env.Create(ctx, node)).To(Succeed())
+		g.Expect(env.CreateAndWait(ctx, node)).To(Succeed())
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_phases_test.go:1783]: Nice catch!

Please also adjust the other occurences for `g.Expect(env.Create(ctx, node)).To(Succeed())` in this file.

While they probably don't lead to a flaky test right now, I think it's fine to also use CreateAndWait there

Comment (loktev-d) [reply exp/internal/controllers/machinepool_controller_phases_test.go:1783]: @sbueringer Should we replace `env.Cleanup` with `env.CleanupAndWait` as well for that matter?

Comment (loktev-d) [reply exp/internal/controllers/machinepool_controller_phases_test.go:1783]: @sbueringer Done

**Comment by loktev-d** [comment]
Also removed namespace from cleanup because envtest does not support namespace deletion and the test was failing.

**Comment by Jont828** [comment]
/lgtm

I think we want to keep running the flaky test several times once you squash to ensure that we have a consistent green signal.

**Comment by sbueringer** [comment]
> Also removed namespace from cleanup because envtest does not support namespace deletion and the test was failing.

In general envtest supports deleting Namespaces. Do you know why exactly it fails?

**Comment by sbueringer** [comment]
Sorry my bad, I was wrong. I thought it works, because we are doing it in similar tests. But they are probably using the fake client and not envtest. Makes sense that namespaces are getting stuck in Terminating when there is no controller-manager running removing the Kubernetes finalizer.

/lgtm

Can you please squash the commits? I'll merge afterwards

**Comment by sbueringer** [comment]
> I think we want to keep running the flaky test several times once you squash to ensure that we have a consistent green signal.

I think we're fine. Tests are green and while we don't 100% know if it resolves the flake, the PR is definitely an improvement and we can check in CI after merge if the flake still occurs.

**Comment by loktev-d** [comment]
@sbueringer Done
