### PR TITLE
🌱 Add retry in test framework when getting manifest YAMLs

### LINKED ISSUE #13322: [e2e] FAILING: failed to get component source YAML
### Which jobs are failing?

periodic-cluster-api-e2e-upgrade-1-31-1-32-release-1-11
periodic-cluster-api-e2e-conformance-ci-latest-release-1-11
periodic-cluster-api-e2e-conformance-ci-latest-main
periodic-cluster-api-e2e-conformance-ci-latest-release-1-12
periodic-cluster-api-e2e-upgrade-1-32-1-33-release-1-12

### Which tests are failing?

<span>
  | capi-e2e [SynchronizedBeforeSuite]
-- | --

</span>

### Since when has it been failing?

Feb 4 2026

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?text=failed%20to%20get%20component%20source%20YAML%20from%20URL&job=.*cluster-api&xjob=.*-provider-

### Reason for failure (if possible)

failed to get component source YAML from URL: failed to get https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.10.10/bootstrap-components.yaml: got status code 502

Loading this file from browser works fine

### Anything else we need to know?

Loading this file from browser works fine

### Label(s) to be applied

/kind failing-test
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Tries to improve the behavior to fix #13322

### CODE REVIEW

File: test/framework/clusterctl/repository.go [hunk 1]
```diff
@@ -228,21 +231,37 @@ func getComponentSourceFromURL(ctx context.Context, source ProviderVersionSource
...
-		if resp.StatusCode != http.StatusOK {
-			return nil, errors.Errorf("failed to get %s: got status code %d", source.Value, resp.StatusCode)
-		}
-		defer resp.Body.Close()
-		buf, err = io.ReadAll(resp.Body)
+		var getErr error
+		err := wait.ExponentialBackoff(wait.Backoff{
+			Steps:    5,
+			Duration: 100 * time.Millisecond,
+			Factor:   1.0,
```
Comment (fabriziopandini) [inline test/framework/clusterctl/repository.go]: I will make Factor 4.0 (which is ok in a an E2E test, and gives some more tolerance to GitHub flakiness)

Comment (sbueringer) [reply test/framework/clusterctl/repository.go]: Done
