### PR TITLE
🌱  include deamonsets in list images in clusterctl

### LINKED ISSUE #4382: clusterctl list images should include daemonsets
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

```
$ clusterctl init --infrastructure azure:v0.4.12 --list-images
gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
quay.io/jetstack/cert-manager-cainjector:v0.16.1
quay.io/jetstack/cert-manager-controller:v0.16.1
quay.io/jetstack/cert-manager-webhook:v0.16.1
us.gcr.io/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller:v0.4.12
us.gcr.io/k8s-artifacts-prod/cluster-api/cluster-api-controller:v0.3.14
us.gcr.io/k8s-artifacts-prod/cluster-api/kubeadm-bootstrap-controller:v0.3.14
us.gcr.io/k8s-artifacts-prod/cluster-api/kubeadm-control-plane-controller:v0.3.14
```

**What did you expect to happen:**
The image `mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.6.3` should also be present.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Let me know if https://github.com/kubernetes-sigs/cluster-api-provider-azure is a better place to open this issue.
Im new to the codebase but couldn't find how the list of images is populated.

**Environment:**

```
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.14", GitCommit:"5a09f69fa8c4892eb45a61d8d701140eeeaa5ba8", GitTreeState:"clean", BuildDate:"2021-02-06T03:08:57Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
```

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by ludusrusso**
**What this PR does / why we need it**:
This PR adds deamonsets in list images in clusterctl.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4382

/cc @fabriziopandini

### CODE REVIEW

File: cmd/clusterctl/internal/util/objs.go [hunk 1]
```diff
@@ -105,42 +119,93 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
...
 		}
-
-		// Convert Unstructured into a typed object
-		d := &appsv1.Deployment{}
-		if err := scheme.Scheme.Convert(o, d, nil); err != nil {
+		err = fixDaemonSetImage(o, alterImageFunc)
+		if err != nil {
 			return nil, err
 		}
+		objs[i] = *o
```
Comment (ludusrusso) [inline cmd/clusterctl/internal/util/objs.go:130]: I'm not sure how to properly abstract deamonset and image here. This code works but requires some code dupliation. @fabriziopandini what do you think?

Comment (fabriziopandini) [reply cmd/clusterctl/internal/util/objs.go:130]: What about extracting the bits  that are modifying Containers/InitContainers? Both of them are working on []Containers and they are the same for DaemonSet & Deployments (that's means that they are repeated 4 times now...)

File: cmd/clusterctl/internal/util/objs_test.go [hunk 2]
```diff
@@ -126,6 +126,39 @@ func Test_inspectImages(t *testing.T) {
 			want:    []string{"gcr.io/k8s-staging-cluster-api/cluster-api-controller:master", "gcr.io/k8s-staging-cluster-api/cluster-api-controller:init"},
 			wantErr: false,
 		},
+		{
+			name: "controller with init container",
```
Comment (fabriziopandini) [inline cmd/clusterctl/internal/util/objs_test.go:130]:
```suggestion
			name: "controller with daemonSet",
```

File: cmd/clusterctl/internal/util/objs.go (hunk 1 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go:131]: What do you think now?

**Review by davideimola — APPROVED** [review]
LGTM

File: cmd/clusterctl/internal/util/objs.go [hunk 3]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
...
+	// Convert Unstructured into a typed object
+	d := &appsv1.DaemonSet{}
+	if err := scheme.Scheme.Convert(o, d, nil); err != nil {
+		return err
+	}
+
+	var err error
+	d.Spec.Template.Spec, err = fixPodSpecImages(d.Spec.Template.Spec, alterImageFunc)
+	if err != nil {
+		return errors.Wrapf(err, "failed to fix containers in deamonSet %s", d.Name)
```
Comment (enxebre) [inline cmd/clusterctl/internal/util/objs.go:174]: curious do we have a convention on using `"github.com/pkg/errors"` rather than core support e.g `fmt.Errorf("%w", err)`?

Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go:174]: I've also noticed this and I think that maybe this project started before go 1.13 and introduction of error wrapping in the library. Maybe @fabriziopandini can explain this better.

Anyway this is used in the whole project. Maybe we can open an issue to migrate from `github.com/pkg/errors` to the standard library, what do you think?

Comment (enxebre) [reply cmd/clusterctl/internal/util/objs.go:174]: sgtm if we confirm there's no particular reason to use it.

Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go:174]: Anyway I think it could be a little bit hard to achieve such a massive refactoring :D But in case I can work on it!

**Comment by fabriziopandini** [comment]
@ludusrusso please squash commits, otherwise lgtm for me

**Comment by ludusrusso** [comment]
> @ludusrusso please squash commits, otherwise lgtm for me

Done! Also rebased to master!

File: cmd/clusterctl/internal/util/objs.go [hunk 4]
```diff
@@ -37,19 +39,32 @@ func InspectImages(objs []unstructured.Unstructured) ([]string, error) {
 
 	for i := range objs {
 		o := objs[i]
+
+		if o.GetKind() != deploymentKind && o.GetKind() != daemonSetKind {
+			continue
+		}
```
[the remark this answers is not in the document]
Comment (vincepri) [reply cmd/clusterctl/internal/util/objs.go:45]: Could we use a switch case instead?

File: cmd/clusterctl/internal/util/objs.go [hunk 5]
```diff
@@ -37,19 +39,32 @@ func InspectImages(objs []unstructured.Unstructured) ([]string, error) {
...
-			for _, c := range d.Spec.Template.Spec.Containers {
-				images = append(images, c.Image)
+			podSpec = d.Spec.Template.Spec
+		} else if o.GetKind() == daemonSetKind {
+			d := &appsv1.DaemonSet{}
+			if err := scheme.Scheme.Convert(&o, d, nil); err != nil {
+				return nil, err
 			}
+			podSpec = d.Spec.Template.Spec
+		}
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:60]: These `if` branches can be used to validate the above as well, if we use a switch case, the `default` case could be to `continue`

File: cmd/clusterctl/internal/util/objs.go [hunk 6]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
 	// look for resources of kind Deployment and alter the image
 	for i := range objs {
 		o := &objs[i]
-		if o.GetKind() != deploymentKind {
-			continue
+		err := fixDeploymentImages(o, alterImageFunc)
+		if err != nil {
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:124]:
```suggestion
		if err := fixDeploymentImages(o, alterImageFunc); err != nil {
```

File: cmd/clusterctl/internal/util/objs.go [hunk 7]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
...
+			return nil, err
 		}
-
-		// Convert Unstructured into a typed object
-		d := &appsv1.Deployment{}
-		if err := scheme.Scheme.Convert(o, d, nil); err != nil {
+		err = fixDaemonSetImages(o, alterImageFunc)
+		if err != nil {
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:128]:
```suggestion
		if err := fixDaemonSetImages(o, alterImageFunc); err != nil {
```

Usually we try to avoid shadowing other variables

File: cmd/clusterctl/internal/util/objs.go [hunk 8]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
 	// look for resources of kind Deployment and alter the image
 	for i := range objs {
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:121]: I cannot comment on 2 lines above here, but could we pass `objs` as `[]*unstructured.Unstructured` to remove the deref of pointers?

File: cmd/clusterctl/internal/util/objs.go [hunk 9]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
...
 		}
-
-		// Convert Unstructured into a typed object
-		d := &appsv1.Deployment{}
-		if err := scheme.Scheme.Convert(o, d, nil); err != nil {
+		err = fixDaemonSetImages(o, alterImageFunc)
+		if err != nil {
 			return nil, err
 		}
+		objs[i] = *o
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:131]: Is this necessary? We're already working on the pointer here, and the map inside the object is always going to be a pointer as well

File: cmd/clusterctl/internal/util/objs.go [hunk 10]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
 	// look for resources of kind Deployment and alter the image
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:120]: I might have completely missed it, but where is this function called? I see changes to this function, but cannot see where we're calling it

File: cmd/clusterctl/internal/util/objs.go [hunk 11]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
...
-		// Convert Unstructured into a typed object
-		d := &appsv1.Deployment{}
-		if err := scheme.Scheme.Convert(o, d, nil); err != nil {
+		err = fixDaemonSetImages(o, alterImageFunc)
+		if err != nil {
 			return nil, err
 		}
+		objs[i] = *o
+	}
+	return objs, nil
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:133]: Do we need to return `objs` here? Seems like we're doing in place updates of the slice?

File: cmd/clusterctl/internal/util/objs.go [hunk 12]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
...
+	d.Spec.Template.Spec, err = fixPodSpecImages(d.Spec.Template.Spec, alterImageFunc)
+	if err != nil {
+		return errors.Wrapf(err, "failed to fix containers in deployment %s", d.Name)
+	}
+
+	// Convert typed object back to Unstructured
+	if err := scheme.Scheme.Convert(d, o, nil); err != nil {
+		return err
+	}
+	return nil
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:157]:
```suggestion
	return scheme.Scheme.Convert(d, o, nil)
```

File: cmd/clusterctl/internal/util/objs.go (hunk 3 above)
Comment (vincepri) [reply cmd/clusterctl/internal/util/objs.go:174]: We've standardized on pkg/errors because of its easier interface and the ability to wrap and unwrap errors in a chain fashion. For now, we have no intention to switch.

File: cmd/clusterctl/internal/util/objs.go [hunk 13]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
...
+	var err error
+	d.Spec.Template.Spec, err = fixPodSpecImages(d.Spec.Template.Spec, alterImageFunc)
+	if err != nil {
+		return errors.Wrapf(err, "failed to fix containers in deamonSet %s", d.Name)
+	}
+	// Convert typed object back to Unstructured
+	if err := scheme.Scheme.Convert(d, o, nil); err != nil {
+		return err
+	}
+	return nil
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:180]:
```suggestion
	return scheme.Scheme.Convert(d, o, nil)
```

File: cmd/clusterctl/internal/util/objs.go [hunk 14]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
...
+	}
+	podSpec.InitContainers, err = fixContainersImage(podSpec.InitContainers, alterImageFunc)
+	if err != nil {
+		return podSpec, errors.Wrapf(err, "failed to fix init containers")
+	}
+	return podSpec, nil
+}
+
+func fixContainersImage(containers []v1.Container, alterImageFunc func(image string) (string, error)) ([]v1.Container, error) {
+	for j := range containers {
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:197]:
```suggestion
func fixContainersImage(containers []*v1.Container, alterImageFunc func(image string) (string, error)) ([]v1.Container, error) {
	for j := range containers {
```

Any reason this isn't a pointer?

File: cmd/clusterctl/internal/util/objs.go [hunk 15]
```diff
@@ -105,42 +120,87 @@ func FixImages(objs []unstructured.Unstructured, alterImageFunc func(image strin
...
+		return errors.Wrapf(err, "failed to fix containers in deamonSet %s", d.Name)
+	}
+	// Convert typed object back to Unstructured
+	if err := scheme.Scheme.Convert(d, o, nil); err != nil {
+		return err
+	}
+	return nil
+}
+
+func fixPodSpecImages(podSpec v1.PodSpec, alterImageFunc func(image string) (string, error)) (v1.PodSpec, error) {
```
Comment (vincepri) [inline cmd/clusterctl/internal/util/objs.go:183]: Could we rename the `v1` package to `corev1`?

**Review by vincepri — CHANGES_REQUESTED** [review]

File: cmd/clusterctl/internal/util/objs.go (hunk 9 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go:131]: No than's not required!

File: cmd/clusterctl/internal/util/objs.go (hunk 8 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go:121]: What do you mean exactly?

File: cmd/clusterctl/internal/util/objs.go (hunk 14 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go:197]: If I do this, then I need to map containers with pointers here, and I don't like it too much

```
	podSpec.Containers, err = fixContainersImage(podSpec.Containers, alterImageFunc)
	if err != nil {
		return podSpec, errors.Wrapf(err, "failed to fix containers")
	}
	podSpec.InitContainers, err = fixContainersImage(podSpec.InitContainers, alterImageFunc)
	if err != nil {
		return podSpec, errors.Wrapf(err, "failed to fix init containers")
	}
```

In general I like to pass data by value if it's not required

Anyway since it's and array I do not need to pass back the value

File: cmd/clusterctl/internal/util/objs.go (hunk 15 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go:183]: ok

File: cmd/clusterctl/internal/util/objs.go (hunk 14 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go]: I've refactored this to avoid passing back data, what do you think?

File: cmd/clusterctl/internal/util/objs.go (hunk 8 above)
Comment (vincepri) [reply cmd/clusterctl/internal/util/objs.go:120]: In the function definition, we're passing `objs` as a slice of non pointer unstructured objects, could we switch to use pointers instead?

File: cmd/clusterctl/internal/util/objs.go (hunk 14 above)
Comment (vincepri) [reply cmd/clusterctl/internal/util/objs.go]: Looks great now, thank you!

File: cmd/clusterctl/internal/util/objs.go (hunk 10 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go]: This is called in cert_manager.go and components.go

File: cmd/clusterctl/internal/util/objs.go (hunk 11 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go:128]: I think that this is not required but it's part of the function interface!

File: cmd/clusterctl/internal/util/objs.go (hunk 14 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go]: > @ludusrusso: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-cluster-api-test-main	[8481b9f](https://github.com/kubernetes-sigs/cluster-api/commit/8481b9fda3298d6eddb15e504ae9383ddc86ebd6)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4455/pull-cluster-api-test-main/1382012990940778496)	`/test pull-cluster-api-test-main`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=cluster-api&pr=4455). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Aludusrusso). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/cluster-api/issues?q=is:issue+is:open) when you hit one in your PR.

@vincepri is this the flaky test or I've broke something?

File: cmd/clusterctl/internal/util/objs.go (hunk 8 above)
Comment (ludusrusso) [reply cmd/clusterctl/internal/util/objs.go:120]: If I do this I'll brake the function interface and lot's of stuff that works with `[]unstructured.Unstructured` like this

https://github.com/kubernetes-sigs/cluster-api/blob/aaea64e524bfcc8d0cd429b2baa4e6956dd8d0bc/cmd/clusterctl/client/cluster/cert_manager.go#L353-L368

**Comment by ludusrusso** [comment]
> @ludusrusso: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-cluster-api-test-main	[8481b9f](https://github.com/kubernetes-sigs/cluster-api/commit/8481b9fda3298d6eddb15e504ae9383ddc86ebd6)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/4455/pull-cluster-api-test-main/1382012990940778496)	`/test pull-cluster-api-test-main`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=cluster-api&pr=4455). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Aludusrusso). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/cluster-api/issues?q=is:issue+is:open) when you hit one in your PR.

@vincepri did I broke something or it's the flaky test?

File: cmd/clusterctl/internal/util/objs.go (hunk 8 above)
Comment (vincepri) [reply cmd/clusterctl/internal/util/objs.go:120]: I see, let's leave it for now then

File: cmd/clusterctl/internal/util/objs.go (hunk 11 above)
Comment (vincepri) [reply cmd/clusterctl/internal/util/objs.go:128]: cc @fabriziopandini We might want to revisit ^
