### PR TITLE
⚠️ ClusterConfigration.Networking.* fields are now optional

### LINKED ISSUE #1769: [cabpk] Patch fail first time a new config is generated
/kind bug

**What steps did you take and what happened:**
Create a new Machine with a KubeadmConfig, the first time the config is patched, the reconciler fails with the following validation error.

> E0909 02:00:09.747522       1 kubeadmconfig_controller.go:143] reconciler "msg"="failed to patch config" "error"="KubeadmConfig.bootstrap.cluster.x-k8s.io \"test1-controlplane-0\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"bootstrap.cluster.x-k8s.io/v1alpha2\", \"kind\":\"KubeadmConfig\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-09-09T01:59:36Z\", \"generation\":2, \"name\":\"test1-controlplane-0\", \"namespace\":\"default\", \"ownerReferences\":[]interface {}{map[string]interface {}{\"apiVersion\":\"cluster.x-k8s.io/v1alpha2\", \"kind\":\"Machine\", \"name\":\"test1-controlplane-0\", \"uid\":\"664e6ba6-901d-43c8-988e-21b833c71392\"}}, \"resourceVersion\":\"598\", \"uid\":\"ca7cd586-dfa3-44d4-b65d-b8fb931600c9\"}, \"spec\":map[string]interface {}{\"clusterConfiguration\":map[string]interface {}{\"apiServer\":map[string]interface {}{\"extraArgs\":map[string]interface {}{\"cloud-provider\":\"gce\"}}, \"clusterName\":\"test1\", \"controlPlaneEndpoint\":\"34.102.137.26:443\", \"controllerManager\":map[string]interface {}{\"extraArgs\":map[string]interface {}{\"allocate-node-cidrs\":\"true\", \"cloud-provider\":\"gce\", \"cluster-cidr\":\"192.168.0.0/16\", \"service-cluster-ip-range\":\"10.96.0.0/12\"}}, \"kubernetesVersion\":\"v1.15.3\", \"networking\":map[string]interface {}{\"podSubnet\":\"192.168.0.0/16\"}}, \"initConfiguration\":map[string]interface {}{\"nodeRegistration\":map[string]interface {}{\"kubeletExtraArgs\":map[string]interface {}{\"cloud-provider\":\"gce\"}, \"name\":\"{{ ds.meta_data[\\\"local_hostname\\\"] }}\"}}}}: validation failure list:\nspec.clusterConfiguration.networking.dnsDomain in body is required\nspec.clusterConfiguration.networking.serviceSubnet in body is required" "kubeadmconfig"={"Namespace":"default","Name":"test1-controlplane-0"} "machine-name"="test1-controlplane-0"
E0909 02:00:09.747915       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="KubeadmConfig.bootstrap.cluster.x-k8s.io \"test1-controlplane-0\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"bootstrap.cluster.x-k8s.io/v1alpha2\", \"kind\":\"KubeadmConfig\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-09-09T01:59:36Z\", \"generation\":2, \"name\":\"test1-controlplane-0\", \"namespace\":\"default\", \"ownerReferences\":[]interface {}{map[string]interface {}{\"apiVersion\":\"cluster.x-k8s.io/v1alpha2\", \"kind\":\"Machine\", \"name\":\"test1-controlplane-0\", \"uid\":\"664e6ba6-901d-43c8-988e-21b833c71392\"}}, \"resourceVersion\":\"598\", \"uid\":\"ca7cd586-dfa3-44d4-b65d-b8fb931600c9\"}, \"spec\":map[string]interface {}{\"clusterConfiguration\":map[string]interface {}{\"apiServer\":map[string]interface {}{\"extraArgs\":map[string]interface {}{\"cloud-provider\":\"gce\"}}, \"clusterName\":\"test1\", \"controlPlaneEndpoint\":\"34.102.137.26:443\", \"controllerManager\":map[string]interface {}{\"extraArgs\":map[string]interface {}{\"allocate-node-cidrs\":\"true\", \"cloud-provider\":\"gce\", \"cluster-cidr\":\"192.168.0.0/16\", \"service-cluster-ip-range\":\"10.96.0.0/12\"}}, \"kubernetesVersion\":\"v1.15.3\", \"networking\":map[string]interface {}{\"podSubnet\":\"192.168.0.0/16\"}}, \"initConfiguration\":map[string]interface {}{\"nodeRegistration\":map[string]interface {}{\"kubeletExtraArgs\":map[string]interface {}{\"cloud-provider\":\"gce\"}, \"name\":\"{{ ds.meta_data[\\\"local_hostname\\\"] }}\"}}}}: validation failure list:\nspec.clusterConfiguration.networking.dnsDomain in body is required\nspec.clusterConfiguration.networking.serviceSubnet in body is required"  "controller"="kubeadmconfig" "request"={"Namespace":"default","Name":"test1-controlplane-0"}

**What did you expect to happen:**
Patch should succeed without errors.

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
Same as https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/287, but for CAPI types.

This fixes the long-standing issue of seeing patches failing for the first control plane instance. After a little investigation, it seems that the issue was primarily "fixed" because after the first try, there are no more patches to the KubeadmConfig for a control plane.

While the Spec fails to patch, the Status doesn't and it gets updated with the generated bootstrap data. Things flow as you'd expect, but any configuration in ClusterConfiguration.Networking is lost. In v1alpha2, you can see that there is a discrepancy between what's generated and stored under `KubeadmConfig.Status.BootstrapData` and what's in the Spec.

While the generated bootstrap data has Networking fields set (which is the most important bit), the Spec doesn't.

Fixes #1769

### CODE REVIEW

File: bootstrap/kubeadm/types/v1beta1/types.go [hunk 1]
```diff
@@ -227,11 +227,14 @@ type NodeRegistrationOptions struct {
 // Networking contains elements describing cluster's networking configuration
 type Networking struct {
 	// ServiceSubnet is the subnet used by k8s services. Defaults to "10.96.0.0/12".
-	ServiceSubnet string `json:"serviceSubnet"`
+	// +optional
+	ServiceSubnet string `json:"serviceSubnet,omitempty"`
 	// PodSubnet is the subnet used by pods.
-	PodSubnet string `json:"podSubnet"`
+	// +optional
```
Comment (ncdc) [inline bootstrap/kubeadm/types/v1beta1/types.go]: It looks like kubeadm will default ServiceSubnet and DNSDomain but not PodSubnet. Should we keep this one as required?

**Comment by vincepri** [comment]
Done!
