### PR TITLE
 🐛  Fix for watch info matching in cluster cache tracker

### LINKED ISSUE #3184: CAPI controller logging endless "Starting EventSource" messages
**What steps did you take and what happened:**
- Create a MachineHealthCheck for my cluster
- See that you get an endless stream of these log lines
```
[capi-controller-manager-789f85c5fb-2trbn manager] I0611 20:37:07.646250     182 controller.go:138] controller-runtime/controller "msg"="Starting EventSource"  "controller"="machinehealthcheck" "source"={}
```

**What did you expect to happen:**
Not see that

**Anything else you would like to add:**
I did a `git bisect` already and it was introduced by https://github.com/kubernetes-sigs/cluster-api/commit/f31f0cea32d03b158b381ffb330c5b61b87cd82d / #3129.

I'm not sure if there are any bugs here other the overwhelming amount of logs.

**Environment:**

- Cluster-api version: master
- Minikube/KIND version: 0.8.1
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T20:58:41Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Ubuntu

/kind bug
/area health

### PR DESCRIPTION
**Pull request by JoelSpeed**
**What this PR does / why we need it**:

The cluster cache tracker tries to deduplicate watch requests by matching the watchinput kind, watcher and eventhandler to the watches that it has already started.

However, this comparison was failing for real world event handlers because Go was not matching the inputs. Switching to reflect.DeepEqual helps with the equality of the watcher and kind, but still fails for eventHandlers because they will embed functions and DeepEqual will always return false for non-nil functions.

As a solution/workaround, we replace the eventHandler with a string representation of itself which will identify the struct type and should give pointers to the functions embedded within it. I'm hoping this should be sufficiently unique to identify a particular codepath calling Watch, when combined with the watcher.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3184 
Related to #3197

### CODE REVIEW

**Comment by JoelSpeed** [comment]
CC @benmoss @vincepri I've opened this as a draft for now to seek feedback on the approach taken here. The alternative that I could think of involved requiring the WatchInput to have a non empty ID string that would identify the watch being called that is expected to be consistent every time the codepath is called and not matching on the eventHandler at all

**Comment by JoelSpeed** [comment]
I have manually tested this based on the setup described in https://github.com/kubernetes-sigs/cluster-api/issues/3184#issuecomment-644274106 and it is no longer hot looping on watches so I think this resolves the immediate issue

File: controllers/remote/cluster_cache.go [hunk 1]
```diff
@@ -111,9 +112,15 @@ type Watcher interface {
...
 type watchInfo struct {
-	watcher      Watcher
-	kind         runtime.Object
-	eventHandler handler.EventHandler
+	watcher Watcher
+	kind    runtime.Object
+
+	// Copmaring the eventHandler as an interface doesn't work because reflect.DeepEqual
+	// will assert functions are false if they are non-nil.
+	// So print it to a string using "%#v" and keep that as a for of unique identifier.
```
Comment (elmiko) [inline controllers/remote/cluster_cache.go:120]: s/for/form/

File: controllers/remote/cluster_cache.go [hunk 2]
```diff
@@ -159,7 +170,7 @@ func (m *ClusterCacheTracker) Watch(ctx context.Context, input WatchInput) error
 	wi := watchInfo{
 		watcher:      input.Watcher,
 		kind:         input.Kind,
```
Comment (vincepri) [inline controllers/remote/cluster_cache.go:172]: Kind here is also an interface and we have no control over what it contains, it's technically possible to pass `&corev1.Node{}` and `&corev1.Node{ObjectMeta:{Name:"x"}}` in here. What about changing this to be GVK instead? We can use the runtime.Scheme from the Manager when we create the tracker to safely determine it.

File: controllers/remote/cluster_cache.go [hunk 3]
```diff
@@ -111,9 +112,15 @@ type Watcher interface {
...
-	eventHandler handler.EventHandler
+	watcher Watcher
+	kind    runtime.Object
+
+	// Copmaring the eventHandler as an interface doesn't work because reflect.DeepEqual
+	// will assert functions are false if they are non-nil.
+	// So print it to a string using "%#v" and keep that as a for of unique identifier.
+	// Eg "&handler.EnqueueRequestsFromMapFunc{ToRequests:(handler.ToRequestsFunc)(0x271afb0)}"
+	// In combination with the watcher, this should be enough to identify unique watches.
+	eventHandler string
```
Comment (vincepri) [inline controllers/remote/cluster_cache.go:123]:
```suggestion
	eventHandlerHash string
```

Or signature?

File: controllers/remote/cluster_cache.go [hunk 4]
```diff
@@ -159,7 +170,7 @@ func (m *ClusterCacheTracker) Watch(ctx context.Context, input WatchInput) error
 	wi := watchInfo{
 		watcher:      input.Watcher,
 		kind:         input.Kind,
-		eventHandler: input.EventHandler,
+		eventHandler: fmt.Sprintf("%#v", input.EventHandler),
```
Comment (vincepri) [inline controllers/remote/cluster_cache.go:173]: Can we make this a method so we can change it easily later?

File: controllers/remote/cluster_cache_tracker_test.go [hunk 5]
```diff
@@ -203,11 +208,19 @@ var _ = Describe("ClusterCache Tracker suite", func() {
...
+
 				Expect(cct.Watch(ctx, WatchInput{
 					Cluster:      input.clusterKey,
 					Watcher:      input.watcher,
-					Kind:         input.kind,
-					EventHandler: input.eventHandler,
+					Kind:         kind,
+					EventHandler: eventHandler,
 					Predicates:   input.predicates,
 				})).To(Succeed())
```
Comment (vincepri) [inline controllers/remote/cluster_cache_tracker_test.go:225]: Should we also assert that the number of watches remains stable?

**Comment by vincepri** [comment]
This PR fixes also #3197

File: controllers/remote/cluster_cache.go (hunk 3 above)
Comment (JoelSpeed) [reply controllers/remote/cluster_cache.go]: Went with eventHandlerSignature

File: controllers/remote/cluster_cache_tracker_test.go (hunk 5 above)
Comment (JoelSpeed) [reply controllers/remote/cluster_cache_tracker_test.go:229]: In the assertWatch a couple of lines below it asserts that there is the expected number of watches, which in this case will be 1, so we are already doing that

**Comment by JoelSpeed** [comment]
@vincepri Ready for another review, all your comments addressed

File: controllers/remote/cluster_cache_tracker_test.go (hunk 5 above)
Comment (vincepri) [reply controllers/remote/cluster_cache_tracker_test.go:229]: github diff was hiding it, thanks!

**Comment by vincepri** [comment]
@JoelSpeed is this rebased on master? I wonder if we still need to investigate the failing tests

**Comment by JoelSpeed** [comment]
@vincepri It is now rebased on master 😉  Let's see what the tests do

File: controllers/remote/cluster_cache.go [hunk 6]
```diff
@@ -111,9 +113,45 @@ type Watcher interface {
...
+		return schema.GroupVersionKind{}, fmt.Errorf("no group-version-kinds associated with type %T", obj)
+	}
+	if len(gvks) > 1 {
+		// this should only trigger for things like metav1.XYZ --
+		// normal versioned types should be fine
+		return schema.GroupVersionKind{}, fmt.Errorf(
+			"multiple group-version-kinds associated with type %T, refusing to guess at one", obj)
+	}
+	return gvks[0], nil
 }
```
Comment (vincepri) [inline controllers/remote/cluster_cache.go:155]: We can probably use https://github.com/kubernetes-sigs/controller-runtime/blob/c4893e0b992fb1e6e7da29acd692a0cdf9d7aec9/pkg/client/apiutil/apimachinery.go#L50-L69 instead

**Comment by vincepri** [comment]
Just one comment, rest LGTM — mostly need to squash commits

File: controllers/remote/cluster_cache.go (hunk 6 above)
Comment (JoelSpeed) [reply controllers/remote/cluster_cache.go:155]: Yeah we could, it's identical, except the error message "cannot create a new informer for the unversioned type %T", if that's acceptable then I'll put it to that and squash everything down

Comment (vincepri) [reply controllers/remote/cluster_cache.go:155]: That's probably fine, seems needs to be fixed upstream given that it's in the `apiutil` package. This function is also used in any of the controller runtime Client methods, so if it fails here it'd fail there as well

**Comment by vincepri** [comment]
@JoelSpeed mind trying to incorporate this patch to see if we resolve some of the flakes? 

```patch
diff --git a/Makefile b/Makefile
index 65bef75b8..5144bfc81 100644
--- a/Makefile
+++ b/Makefile
@@ -112,7 +112,7 @@ help:  ## Display this help
 
 .PHONY: test
 test: ## Run tests
-       source ./scripts/fetch_ext_bins.sh; fetch_tools; setup_envs; go test -v ./...
+       source ./scripts/fetch_ext_bins.sh; fetch_tools; setup_envs; go test -v ./... $(TEST_ARGS)
 
 .PHONY: docker-build-e2e
 docker-build-e2e: ## Rebuild all Cluster API provider images to be used in the e2e tests
diff --git a/scripts/ci-test.sh b/scripts/ci-test.sh
index 1909363f6..fcb1c12fe 100755
--- a/scripts/ci-test.sh
+++ b/scripts/ci-test.sh
@@ -25,7 +25,7 @@ cd "${REPO_ROOT}" || exit 1
 source "${REPO_ROOT}/hack/ensure-go.sh"
 
 echo "*** Testing Cluster API ***"
-make test
+TEST_ARGS="-p=2" make test
 
 echo -e "\n*** Testing Cluster API Provider Docker ***\n"
 # Docker provider
```

It should make things a little slower in CI, although because we're resource constrained that's probably better.

**Comment by JoelSpeed** [comment]
Added, let's see what that does

**Comment by vincepri** [comment]
Tests are slower, went from ~3m to ~8m — we can try to use either p=3 or p=4 to limit to 3/4 CPUs and see what happens

**Comment by vincepri** [comment]
That said, I'd take slower and non-flaky CI tests over fast one that fail over and over

**Comment by vincepri** [comment]
Seems it's still failing on MachineHealthCheck, let's merge this in without the -p flag and let's tackle the tests separately

**Comment by vincepri** [comment]
I might be more inclined to move these tests to the e2e, although I think they're there already

**Comment by JoelSpeed** [comment]
Are there particular tests known to be flaking or is it all over?

**Comment by vincepri** [comment]
From the little investigation I've done over the last few days, it seems it's mostly failing on MHC DescribeTable tests, see https://github.com/kubernetes-sigs/cluster-api/issues/3197#issuecomment-644827375 for more context. It might be worth to rewrite these and avoid reusing the same names, although I'm not 100% sure if that would fix the issue; technically we're faking Kubernetes Nodes in envtest where there are no nodes, so it might just be that these tests should be moved to e2e instead and removed from there

**Comment by fabriziopandini** [comment]
Agreed. Let's merge this and tacke flaky tests separately
/lgtm
/test pull-cluster-api-test
