### PR TITLE
Fix ProviderID handling of scheme://oneSegment

### LINKED ISSUE #1120: noderefutil.ProviderID doesn't handle scheme://id correctly
/kind bug

**What steps did you take and what happened:**
`noderefutil.NewProviderID("scheme://id123").Id()` returns `.`

**What did you expect to happen:**
`id123`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
Fix noderefutil.ProviderID handling of single-segment provider ids.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1120

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Single-segment provider IDs are now handled correctly.
```

### CODE REVIEW

File: pkg/controller/noderefutil/providerid_test.go [hunk 1]
```diff
@@ -17,32 +17,62 @@ limitations under the License.
...
+		expectedID string
+	} {
+		{
+			name: "one segment",
+			input: "aws://instance-id",
+			expectedID: "instance-id",
+		},
+		{
+			name: "multiple segments",
+			input: "aws://one/two/three/instance-id",
```
Comment (detiber) [inline pkg/controller/noderefutil/providerid_test.go]: How about a test case with empty segments as well? Such as `aws:////instance-id`?

Comment (ncdc) [reply pkg/controller/noderefutil/providerid_test.go]: Sure, we should reject that, right?

Comment (ncdc) [reply pkg/controller/noderefutil/providerid_test.go]: Added it to the errors test

Comment (detiber) [reply pkg/controller/noderefutil/providerid_test.go]: No, it should be accepted, it is one of the allowed values by the cloud provider

Comment (ncdc) [reply pkg/controller/noderefutil/providerid_test.go]: ok, will fix

Comment (detiber) [reply pkg/controller/noderefutil/providerid_test.go]: For the common case back from aws specifically, we should expect to see something similar to `aws:///us-east-1a/instance-id`, but `aws:////instance-id` is also acceptable.

**Comment by ncdc** [comment]
@detiber how's this look?

File: pkg/controller/noderefutil/providerid.go [hunk 2]
```diff
@@ -39,13 +41,27 @@ func NewProviderID(id string) (*ProviderID, error) {
...
-	parsed, err := url.Parse(id)
-	if err != nil {
-		return nil, err
+	/*
+		- must start with at least one non-colon
+		- followed by ://
+		- followed by any number of characters
+		- must end with a non-slash
+	*/
+	re := regexp.MustCompile("^[^:]+://.*[^/]$")
```
Comment (chuckha) [inline pkg/controller/noderefutil/providerid.go]: is there some regex we can import from k8s that would do this parsing for us so we don't have to maintain this regex?

File: pkg/controller/noderefutil/providerid_test.go [hunk 3]
```diff
@@ -17,61 +17,109 @@ limitations under the License.
...
+				t.Fatalf("Expected error %v, got %v", test.err, err)
+			}
+		})
+
 	}
 }
 
 func TestProviderIDEquals(t *testing.T) {
-	input1 := "aws:////instance-id1"
+	input1 := "aws://instance-id1"
```
Comment (chuckha) [inline pkg/controller/noderefutil/providerid_test.go]: could tablify this test, i think having multiple equals examples would be helpful here

could also add a separate TestFunction for testing inequality, but that is extra credit and super not necessary

File: pkg/controller/noderefutil/providerid.go (hunk 2 above)
Comment (ncdc) [reply pkg/controller/noderefutil/providerid.go]: I did a quick search but I didn't find anything.

If we don't want a regex, we can loosen this a bit:
1. require the index of `://` be > 0
1. require the index of the last slash be after `://` and not the last character

Comment (vincepri) [reply pkg/controller/noderefutil/providerid.go]: +1 on keeping the regex for validation purposes, the `regexp.MustCompile` can be as a global variable and only parsed once.

Comment (ncdc) [reply pkg/controller/noderefutil/providerid.go]: Moved to a package var

Comment (chuckha) [reply pkg/controller/noderefutil/providerid.go]: i prefer the regex as well, i was just hoping someone else had already defined it

**Comment by vincepri** [comment]
/assign @detiber @chuckha 
for final lgtm

**Comment by vincepri** [comment]
@ncdc We should backport to `release-0.1`

**Comment by ncdc** [comment]
Yeah

**Comment by ncdc** [comment]
Backport is #1123
