### PR TITLE
🌱 Test BYO certificates

### LINKED ISSUE #9568: Test and document bring-your-own-cert use cases for KCP
Cluster API should clearly document and test bring-your-own-cert use cases for KCP. A change in v1.5 requiring generated certs to have the `cluster.x-k8s.io/cluster-name=${CLUSTER_NAME}` label is not fully documented.

https://github.com/kubernetes-sigs/cluster-api/pull/9080 added documentation for the kubeconfig -  but it should be updated to make clear that this also applies to all other secrets generated for KCP. This change should be backported to `release-1.5`.

We should also add a test - an integration test if possible showing the failing and non-failing cases - so we can prevent regressions in this behaviour in future.

h/t @lentzi90 for reporting this. [Reference slack thread.](https://kubernetes.slack.com/archives/C8TSNPY4T/p1697632695206969).

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

This adds an integration test for BYO CA certificate. It is practically a copy of TestReconcileInitializeControlPlane but with a custom CA and a check to verify that the generated kubeconfig is really using this CA.

To make the test environment behave similar to the real world, it now also has a cache that picks up objects based on labels. For this reason it was also necessary to add labels in a few places.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9568 (it was closed already when we added the docs)

/area testing

### CODE REVIEW

**Comment by lentzi90** [comment]
Finally got around to add the CA verfification now.
/cc @fabriziopandini

File: exp/runtime/internal/controllers/extensionconfig_controller_test.go [hunk 1]
```diff
@@ -408,6 +409,9 @@ func fakeCASecret(namespace, name string, caData []byte) *corev1.Secret {
 		ObjectMeta: metav1.ObjectMeta{
 			Name:      name,
 			Namespace: namespace,
+			Labels: map[string]string{
```
Comment (fabriziopandini) [inline exp/runtime/internal/controllers/extensionconfig_controller_test.go:412]: I think this is not necessary anymore as soon as we merge https://github.com/kubernetes-sigs/cluster-api/pull/10633

cc @sbueringer @chrischdi

**Review by fabriziopandini — COMMENTED** [review]
overal lgtm. I will just wait for https://github.com/kubernetes-sigs/cluster-api/pull/10633 to merge first

File: exp/runtime/internal/controllers/extensionconfig_controller_test.go (hunk 1 above)
Comment (sbueringer) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go:412]: If this was only introduced because otherwise we got not found => yes

Let's definitely revert (after #10633 merges it should work without). This secret *should not* require the cluster-name label (also the secret should not correspond to any cluster)

Comment (lentzi90) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go:412]: Makes sense! I will wait for it to merge, then rebase and remove this. :slightly_smiling_face:

Comment (sbueringer) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go:412]: @lentzi90 PR is merged

Comment (lentzi90) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go:412]: Thanks!
@adilGhaffarDev or @Sunnatillo does anyone of you want to take this over? It may be some time until I can get back to it since I'm on parental leave :innocent:

Comment (sbueringer) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go:412]: No worries! Enjoy!

Comment (adilGhaffarDev) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go:412]: I can address the comments and push the changes.

Comment (adilGhaffarDev) [reply exp/runtime/internal/controllers/extensionconfig_controller_test.go]: pushed the changes, please check.

**Comment by sbueringer** [comment]
I think this also requires changes to another test, see: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/10681/pull-cluster-api-test-main/1812731035935313920

**Comment by lentzi90** [comment]
The extension config controller test made me realize that my naive solution to add the cache directly to the test environment was probably not the best idea. Somehow I didn't realize that different controllers have different cache behavior.

To improve the situation I now made it so that each test suite can have its own cache options. I took inspiration from https://github.com/kubernetes-sigs/cluster-api/pull/11201 to implement it. It is in a separate commit for now so it can be easily reverted if there is some issue with it that I didn't realize.
I have only modified/added the cache for the kubeadm control plane controller suite and the addons controller suite. If you know about more places where it should be, please let me know! Also if I misunderstood how it should be configured for these two controllers.

**Comment by lentzi90** [comment]
Now that v1.9 is out, perhaps there is time to check this again
@fabriziopandini @sbueringer

**Comment by sbueringer** [comment]
Cache configuration looks good to me. Maybe let's only adjust the test suites already modified in the current PR and defer sync'ing all of them with their corresponding manager config's to a follow-up

File: internal/test/envtest/environment.go [hunk 2]
```diff
@@ -117,12 +118,13 @@ func init() {
...
 type RunInput struct {
-	M                   *testing.M
-	ManagerUncachedObjs []client.Object
-	SetupIndexes        func(ctx context.Context, mgr ctrl.Manager)
-	SetupReconcilers    func(ctx context.Context, mgr ctrl.Manager)
-	SetupEnv            func(e *Environment)
-	MinK8sVersion       string
+	M                    *testing.M
+	ManagerUncachedObjs  []client.Object
+	CacheOptionsModifier func(*cache.Options)
```
[the remark this answers is not in the document]
Comment (lentzi90) [reply internal/test/envtest/environment.go]: Good point, fixed!

File: exp/addons/internal/controllers/clusterresourceset_controller_test.go [hunk 3]
```diff
@@ -432,6 +432,9 @@ metadata:
 			ObjectMeta: metav1.ObjectMeta{
 				Name:      newSecretName,
```
Comment (sbueringer) [inline exp/addons/internal/controllers/clusterresourceset_controller_test.go:433]: This one can also be reverted

Comment (lentzi90) [reply exp/addons/internal/controllers/clusterresourceset_controller_test.go]: Sorry I missed it.

Comment (sbueringer) [reply exp/addons/internal/controllers/clusterresourceset_controller_test.go]: No problem

**Comment by lentzi90** [comment]
Thank you!

> Can you please either open an issue or a follow-up PR to sync up all the cache configs in tests? (I think we only have to check all usages of envtest.Run)

Will do!
