### PR TITLE
🌱 Sets InfraReady condition for MachinePool for incorrect external reference

### LINKED ISSUE #4311: MachinePool reporting `Ready` as true if infrastructure ref isn't found
**What steps did you take and what happened:**
I have a typo for the **infrastructureRef** on a **MachinePool** so:

1. Created a `MachinePool` using an infrastructure ref for CAPA:

```
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: "wkp-mgmt01-pool-0"
spec:
  clusterName: "wkp-mgmt01"
  replicas: 2
  failureDomains:
    - eu-west-2c
  template:
    spec:
      clusterName: "wkp-mgmt01"
      bootstrap:
        dataSecretName: ""
      infrastructureRef:
        name: "wpk-mgmt01-pool-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSManagedMachinePoolyaml
```
2.  Due to a typo the infrastructure ref name (`wpk-mgmt01-pool-0`) is incorrect and there is no match
3. If i have a wait on the `Ready` condition of the `MachinePool` is showing ready is true:
image
4. And then if i describe the MachinePool you set the ready condition is true and the phase is provisioning:
image

**What did you expect to happen:**
I would expect the ready condition on the MachinePool to be false and an event written indicating that infrastructure ref can't be found.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.3.14
- Minikube/KIND version: 0.10.0
- Kubernetes version: (use `kubectl version`): 1.18
- OS (e.g. from `/etc/os-release`): Linux

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
This patch sets the `InfrastructureReadyCondition` as `false` if the external reference set on the MachinePool object is incorrect/does not exist. 

**Which issue(s) this PR fixes**:
Fixes #4311

### CODE REVIEW

**Comment by srm09** [comment]
@fabriziopandini This one specifically fixes the MachinePool issue mentioned in #4311 
Maybe we ought to make this check for other controllers as well, where it makes sense.

File: api/v1alpha4/condition_consts.go [hunk 1]
```diff
@@ -35,6 +35,9 @@ const (
 
 	// DeletedReason (Severity=Info) documents an condition not in Status=True because the underlying object was deleted.
 	DeletedReason = "Deleted"
+
+	// IncorrectExternalRefReason (Severity=Error) documents a CAPI object with an incorrect external object reference.
+	IncorrectExternalRefReason = "IncorrectExternalRef"
```
Comment (vincepri) [inline api/v1alpha4/condition_consts.go:40]: Is this the first time we're using this kind of condition? cc @fabriziopandini 

How do we propagate this change elsewhere as well?

File: exp/controllers/machinepool_controller_phases.go [hunk 2]
```diff
@@ -232,12 +232,16 @@ func (r *MachinePoolReconciler) reconcileInfrastructure(ctx context.Context, clu
 	// Call generic external reconciler.
 	infraReconcileResult, err := r.reconcileExternal(ctx, cluster, mp, &mp.Spec.Template.Spec.InfrastructureRef)
 	if err != nil {
-		if mp.Status.InfrastructureReady && strings.Contains(err.Error(), "could not find") {
-			// Infra object went missing after the machine pool was up and running
-			log.Error(err, "MachinePool infrastructure reference has been deleted after being ready, setting failure state")
-			mp.Status.FailureReason = capierrors.MachinePoolStatusErrorPtr(capierrors.InvalidConfigurationMachinePoolError)
-			mp.Status.FailureMessage = pointer.StringPtr(fmt.Sprintf("MachinePool infrastructure resource %v with name %q has been deleted after being ready",
-				mp.Spec.Template.Spec.InfrastructureRef.GroupVersionKind(), mp.Spec.Template.Spec.InfrastructureRef.Name))
+		if strings.Contains(err.Error(), "could not find") {
```
Comment (vincepri) [inline exp/controllers/machinepool_controller_phases.go:235]:
```suggestion
		if apierrors.IsNotFound(errors.Cause(err)) {
```

File: exp/controllers/machinepool_controller_phases.go [hunk 3]
```diff
@@ -232,12 +232,16 @@ func (r *MachinePoolReconciler) reconcileInfrastructure(ctx context.Context, clu
...
+			log.Error(err, "MachinePool infrastructure reference could not be found")
+			if mp.Status.InfrastructureReady {
+				// Infra object went missing after the machine pool was up and running
+				log.Error(err, "MachinePool infrastructure reference has been deleted after being ready, setting failure state")
+				mp.Status.FailureReason = capierrors.MachinePoolStatusErrorPtr(capierrors.InvalidConfigurationMachinePoolError)
+				mp.Status.FailureMessage = pointer.StringPtr(fmt.Sprintf("MachinePool infrastructure resource %v with name %q has been deleted after being ready",
+					mp.Spec.Template.Spec.InfrastructureRef.GroupVersionKind(), mp.Spec.Template.Spec.InfrastructureRef.Name))
+			}
```
Comment (vincepri) [inline exp/controllers/machinepool_controller_phases.go:243]: Do we want to se both failuremessage + reason, and the condition here?

File: exp/controllers/machinepool_controller_phases.go [hunk 4]
```diff
@@ -232,12 +232,16 @@ func (r *MachinePoolReconciler) reconcileInfrastructure(ctx context.Context, clu
...
 	infraReconcileResult, err := r.reconcileExternal(ctx, cluster, mp, &mp.Spec.Template.Spec.InfrastructureRef)
 	if err != nil {
-		if mp.Status.InfrastructureReady && strings.Contains(err.Error(), "could not find") {
-			// Infra object went missing after the machine pool was up and running
-			log.Error(err, "MachinePool infrastructure reference has been deleted after being ready, setting failure state")
-			mp.Status.FailureReason = capierrors.MachinePoolStatusErrorPtr(capierrors.InvalidConfigurationMachinePoolError)
-			mp.Status.FailureMessage = pointer.StringPtr(fmt.Sprintf("MachinePool infrastructure resource %v with name %q has been deleted after being ready",
-				mp.Spec.Template.Spec.InfrastructureRef.GroupVersionKind(), mp.Spec.Template.Spec.InfrastructureRef.Name))
+		if strings.Contains(err.Error(), "could not find") {
+			log.Error(err, "MachinePool infrastructure reference could not be found")
```
Comment (vincepri) [inline exp/controllers/machinepool_controller_phases.go:236]:
```suggestion
			log.Error(err, "infrastructure reference could not be found")
```

File: api/v1alpha4/condition_consts.go (hunk 1 above)
Comment (srm09) [reply api/v1alpha4/condition_consts.go:40]: AFAIK this is the first time we are exposing this reason in a condition. It seems like this failure case could occur in other controllers as well, and we might need to add the logic where it makes sense.

File: exp/controllers/machinepool_controller_phases.go (hunk 2 above)
Comment (srm09) [reply exp/controllers/machinepool_controller_phases.go:235]: Thanks, I was thinking that I had seen this some place in the codebase.

File: exp/controllers/machinepool_controller_phases.go (hunk 3 above)
Comment (srm09) [reply exp/controllers/machinepool_controller_phases.go:243]: As mentioned in the issue, if the enduser/operator is waiting on the `ReadyCondition` to check the status of the object, setting this condition will make sure that the error condition is bubbled up.
