### PR TITLE
🐛 Fix a bug that fails to write the version state file

### LINKED ISSUE #3573: Error: unable to verify clusterctl version: unable to write version state file
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

I ran the `clusterctl version` command after upgrading clusterctl to v0.3.9 and encountered the following error: 
```
$ clusterctl version -v=10
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.9", GitCommit:"e1f67d8ceb1d5b30ef967035f7a0d1b1ee088b37", GitTreeState:"clean", BuildDate:"2020-09-01T02:45:38Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"darwin/amd64"}
No default config file available
Error: unable to verify clusterctl version: unable to write version state file: open /Users/ksuda/.cluster-api/version.yaml: no such file or directory
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.glob..func9
        /workspace/cmd/clusterctl/cmd/root.go:58
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:857
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.Execute
        /workspace/cmd/clusterctl/cmd/root.go:69
main.main
        /workspace/cmd/clusterctl/main.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

**What did you expect to happen:**

I expect the execution of `clusterctl version` command to finish successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

It looks like the error is due to the absence of the `$HOME/.cluster-api` directory.

**Environment:**

- Cluster-api version: v0.3.9
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**:

This PR fixes a bug that fails to write the version state file. Since v0.3.9, clusterctl has added the ability to check for the latest version, but an error occurs because the directory where the version state file will be created does not exist.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3573

### CODE REVIEW

**Comment by superbrothers** [comment]
It seems that a test unrelated to this PR have failed.

File: cmd/clusterctl/cmd/version_checker.go [hunk 1]
```diff
@@ -166,13 +166,15 @@ func (v *versionChecker) getLatestRelease() (*ReleaseInfo, error) {
...
 
-func writeStateFile(filepath string, vs *VersionState) error {
+func writeStateFile(path string, vs *VersionState) error {
 	vsb, err := yaml.Marshal(vs)
 	if err != nil {
 		return err
 	}
-	err = ioutil.WriteFile(filepath, vsb, 0600)
-	if err != nil {
+	if err = os.MkdirAll(filepath.Dir(path), os.ModePerm); err != nil {
```
Comment (vincepri) [inline cmd/clusterctl/cmd/version_checker.go:174]:
```suggestion
	if err := os.MkdirAll(filepath.Dir(path), os.ModePerm); err != nil {
```

Comment (vincepri) [reply cmd/clusterctl/cmd/version_checker.go:174]: This is a minor nit, feel free to merge
