### PR TITLE
:bug: Clean up ControlPlaneInitialized handling

### LINKED ISSUE #2260: Cluster reconciler should not use control plane machines to determine status.controlPlaneInitialized when spec.controlPlaneRef is set
reconcileControlPlaneInitialized should return early if spec.controlPlaneRef is set; otherwise, we have 2 things competing to set this field.

/kind bug
/milestone v0.3.0
/area control-plane
/priority important-soon

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
- Do not attempt to double reconcile Cluster.Status.ControlPlaneInitialized
  when Cluster.Spec.ControlPlaneRef is set

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2260

### CODE REVIEW

File: controllers/cluster_controller.go [hunk 1]
```diff
@@ -429,6 +429,12 @@ func splitMachineList(list *clusterv1.MachineList) (*clusterv1.MachineList, *clu
 func (r *ClusterReconciler) reconcileControlPlaneInitialized(ctx context.Context, cluster *clusterv1.Cluster) error {
 	logger := r.Log.WithValues("cluster", cluster.Name, "namespace", cluster.Namespace)
 
+	// Do not reconcile the ControlPlaneInitialized if using a ControlPlane provider, that is done
```
Comment (chuckha) [inline controllers/cluster_controller.go]: Nit: What do you think about something like "Skip checking if the control plane is initialized when using a control plane provider"?

Comment (detiber) [reply controllers/cluster_controller.go]: Done!

**Comment by ncdc** [comment]
:teamwork:
/area control-plane
/milestone v0.3.0
