### PR TITLE
🐛 Improve to get error stack trace for machine reconcile

### LINKED ISSUE #6721: Improve to get error stack trace for machine reconcile
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
we may need more error message about the machine reconcile

**Environment:**

- Cluster-api version:
- minikube/kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by ruifaling**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6721

### CODE REVIEW

File: internal/controllers/machine/machine_controller.go [hunk 1]
```diff
@@ -525,7 +525,7 @@ func (r *Reconciler) drainNode(ctx context.Context, cluster *clusterv1.Cluster,
 			log.Error(err, "Could not find node from noderef, it may have already been deleted")
 			return ctrl.Result{}, nil
 		}
-		return ctrl.Result{}, errors.Errorf("unable to get node %q: %v", nodeName, err)
+		return ctrl.Result{}, errors.Wrap("unable to get node %q: %v", nodeName, err)
```
Comment (killianmuldoon) [inline internal/controllers/machine/machine_controller.go:528]:
```suggestion
		return ctrl.Result{}, errors.Wrapf(err, "unable to get node %q: %v", nodeName)
```

File: internal/controllers/machine/machine_controller.go [hunk 2]
```diff
@@ -560,7 +560,7 @@ func (r *Reconciler) drainNode(ctx context.Context, cluster *clusterv1.Cluster,
 	if err := kubedrain.RunCordonOrUncordon(drainer, node, true); err != nil {
 		// Machine will be re-reconciled after a cordon failure.
 		log.Error(err, "Cordon failed")
-		return ctrl.Result{}, errors.Errorf("unable to cordon node %s: %v", node.Name, err)
+		return ctrl.Result{}, errors.Wrap("unable to cordon node %s: %v", node.Name, err)
```
Comment (killianmuldoon) [inline internal/controllers/machine/machine_controller.go:563]:
```suggestion
		return ctrl.Result{}, errors.Wrapf(err, "unable to cordon node %s: %v", node.Name)
```

**Review by killianmuldoon — CHANGES_REQUESTED** [review]
I think the function signature should be fixed up - but I'm +1 for this change.

File: internal/controllers/machine/machine_controller.go [hunk 3]
```diff
@@ -525,7 +525,8 @@ func (r *Reconciler) drainNode(ctx context.Context, cluster *clusterv1.Cluster,
 			log.Error(err, "Could not find node from noderef, it may have already been deleted")
 			return ctrl.Result{}, nil
 		}
-		return ctrl.Result{}, errors.Errorf("unable to get node %q: %v", nodeName, err)
+		return ctrl.Result{}, errors.Wrapf(err, "unable to get node %q: %v", nodeName )
```
Comment (killianmuldoon) [inline internal/controllers/machine/machine_controller.go:528]:
```suggestion
		return ctrl.Result{}, errors.Wrapf(err, "unable to get node %q", nodeName )
```

My fault this time 🙂. The suggestion was off.

File: internal/controllers/machine/machine_controller.go [hunk 4]
```diff
@@ -560,7 +561,7 @@ func (r *Reconciler) drainNode(ctx context.Context, cluster *clusterv1.Cluster,
 	if err := kubedrain.RunCordonOrUncordon(drainer, node, true); err != nil {
 		// Machine will be re-reconciled after a cordon failure.
 		log.Error(err, "Cordon failed")
-		return ctrl.Result{}, errors.Errorf("unable to cordon node %s: %v", node.Name, err)
+		return ctrl.Result{}, errors.Wrapf(err, "unable to cordon node %s: %v", node.Name)
```
Comment (killianmuldoon) [inline internal/controllers/machine/machine_controller.go:564]:
```suggestion
return ctrl.Result{}, errors.Wrapf(err, "unable to get node %q", nodeName )```

Comment (sbueringer) [reply internal/controllers/machine/machine_controller.go:564]: Looks like to many \`

Comment (killianmuldoon) [reply internal/controllers/machine/machine_controller.go]: No line break 🙂

File: internal/controllers/machine/machine_controller.go [hunk 5]
```diff
@@ -525,7 +525,8 @@ func (r *Reconciler) drainNode(ctx context.Context, cluster *clusterv1.Cluster,
 			log.Error(err, "Could not find node from noderef, it may have already been deleted")
 			return ctrl.Result{}, nil
 		}
-		return ctrl.Result{}, errors.Errorf("unable to get node %q: %v", nodeName, err)
```
Comment (sbueringer) [inline internal/controllers/machine/machine_controller.go:528]: I think we have to make sure that those error messages don't change on every reconcile. Otherwise we get a lot of updates on the Machine CR

Comment (killianmuldoon) [reply internal/controllers/machine/machine_controller.go:528]: Is this a change in this PR? We were already returning the error string, just not correctly wrapped.

Comment (sbueringer) [reply internal/controllers/machine/machine_controller.go:528]: Oh my bad, missed it

Comment (ruifaling) [reply internal/controllers/machine/machine_controller.go:528]: sorry to waste your time ,I think I'd better close it and firstly fix my develop env

Comment (killianmuldoon) [reply internal/controllers/machine/machine_controller.go:528]: It's a good point though and it can be easily missed, and a pretty major bug if it gets through. We should probably have some sort of sanitizer for errors which end up in our conditions right? I wonder is it possible to do that in a generic way? The main thing is to avoid adding object names where we know they're variable - or at least that's the issue I recall having before.

**Comment by ruifaling** [comment]
@sbueringer  @killianmuldoon  I have committed again ,and conducted a golint check before submitting. Now all the checks have passed. Please check again,thank you!

File: internal/controllers/machine/machine_controller.go (hunk 5 above)
Comment (sbueringer) [reply internal/controllers/machine/machine_controller.go:528]: Hard to say if there's a good way. But the nodeName is definitely not variable here :)

**Comment by sbueringer** [comment]
Thx!

/approve

File: internal/controllers/machine/machine_controller.go (hunk 5 above)
Comment (ruifaling) [reply internal/controllers/machine/machine_controller.go:528]: > Hard to say if there's a good way. But the nodeName is definitely not variable here :)
> 
> I was just wondering about the error, but as you said if there's an issue it wouldn't be a new one

I don't quite understand what you mean

Comment (sbueringer) [reply internal/controllers/machine/machine_controller.go:528]: I am saying that when the reconciler reconciles a single machine the nodeName will be the same every time.
So that won't lead to different errors / different conditions on the Machine / infinite reconciles.

I know know how the `err` looks like and if it's the same every time. But we included the error message already before this PR so this PR won't introduce a bug. If there is a bug it was already there before

Comment (ruifaling) [reply internal/controllers/machine/machine_controller.go:528]: Yes, errs may be the same until the error is fixed.Other errs in reconciles can be the same, right?

**Review by killianmuldoon — APPROVED** [review]
/lgtm
