### PR TITLE
🐛 E2E framework: support 'file' scheme in component source

### LINKED ISSUE #4275: E2E framework: file:// scheme not supported
**What steps did you take and what happened:**
In e2e test config file i specified provider with following component source:
```
  versions:
  - name: v0.3.0
    type: url
    value: "file://relative/path/to/components.yaml"
```

After i started E2E test i got an error:
```
  Failed to generate the manifest for "provider" / "v0.3.0"
  Unexpected error:
      <*url.Error | 0xc0004a1140>: {
          Op: "Get",
          URL: "file://relative/path/to/components.yaml"",
          Err: {
              what: "unsupported protocol scheme",
              str: "file",
          },
      }
      Get file://relative/path/to/components.yaml": unsupported protocol scheme "file"
  occurred
```

**What did you expect to happen:**
Components from this file would be installed.

**Environment:**

- Cluster-api version: 0.3.14
- KIND version: kind v0.9.0
- Kubernetes version: (use `kubectl version`): v1.19.1

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by GrigoriyMikhalkin**
Fixes #4275

Adds support for `file` scheme with absolute paths in component source.

In mentioned issue following example of component source is given:
```
  versions:
  - name: v0.3.0
    type: url
    value: "file://relative/path/to/components.yaml"
```
It still wouldn't work, because it uses relative path. I think it should be left that way, because [RFC8089 states](https://tools.ietf.org/html/rfc8089#section-2) that only `path-absolute` should be permitted for`file` scheme.

### CODE REVIEW

File: test/framework/clusterctl/repository.go [hunk 1]
```diff
@@ -168,3 +168,33 @@ func YAMLForComponentSource(ctx context.Context, source ProviderVersionSource) (
...
+		return nil, err
+	}
+
+	switch u.Scheme {
+	case fileURIScheme:
+		buf, err = ioutil.ReadFile(u.Path)
+		if err != nil {
+			return nil, err
+		}
+	default:
```
Comment (JoelSpeed) [inline test/framework/clusterctl/repository.go:187]: Would it be better to be explicit and return an error for when there is an unknown scheme? This would mean users would have a better idea of what's going wrong compared with a `http.Get` error which may be cryptic? 

If it were me I would do something like:

```
switch strings.ToLower(u.Scheme){
case "file":
  ...
case "http", "https":
 ...
default:
  return nil, fmt.Errorf("unknown scheme for component source %q: allowed values are file, http, https", u.Scheme)
}
```

WDYT?

I guess this does leave a question open if the user doesn't specify the scheme, how do we handle this, http?

**Review by JoelSpeed — COMMENTED** [review]
I think this looks great, have added a suggestion for improving the UX though, let me know what you think

File: test/framework/clusterctl/repository.go [hunk 2]
```diff
@@ -168,3 +168,33 @@ func YAMLForComponentSource(ctx context.Context, source ProviderVersionSource) (
...
+	var buf []byte
+
+	u, err := url.Parse(source.Value)
+	if err != nil {
+		return nil, err
+	}
+
+	switch u.Scheme {
+	case fileURIScheme:
+		buf, err = ioutil.ReadFile(u.Path)
```
Comment (fabriziopandini) [inline test/framework/clusterctl/repository.go:183]: In the test framework we are making all the relative path are processed starting from the config file path 

https://github.com/kubernetes-sigs/cluster-api/blob/57c6d549ec1ffabf93b460e51efdeca856d97c1f/test/framework/clusterctl/e2e_config.go#L281

Should we do the same for relative urls of type file?

File: test/framework/clusterctl/repository.go (hunk 1 above)
Comment (ashish-amarnath) [reply test/framework/clusterctl/repository.go:187]: We can follow the way `--file` flag to `kubectl apply` takes input.
By default, it interprets the value passed to that flag as a file, and if the value is a url then (with `http://` or `https://` prefix), then use the http URL.

Comment (JoelSpeed) [reply test/framework/clusterctl/repository.go:187]: Being consistent would be great, but would that be a breaking change to the existing functionality? 
Has anyone tried doing this and not putting a scheme and seen the result? Perhaps if we can verify what the current behaviour is that will help to determine what should be done here

File: test/framework/clusterctl/repository.go (hunk 2 above)
Comment (GrigoriyMikhalkin) [reply test/framework/clusterctl/repository.go:183]: I think that would be very convenient. But in this case, i suppose, documentation also needs to be updated, to notify user of that behavior. Also, what the syntax would for relative paths? Does `file://./path/ti/file` looks ok?

File: test/framework/clusterctl/repository.go (hunk 1 above)
Comment (GrigoriyMikhalkin) [reply test/framework/clusterctl/repository.go:187]: @JoelSpeed Just checked, if no scheme is provided, `http.Get` returns error `"unsupported protocol scheme \"\""`. So i guess, interpreting value without scheme as flag would be ok.

Comment (GrigoriyMikhalkin) [reply test/framework/clusterctl/repository.go]: @JoelSpeed Updated code, now empty scheme interpreted as file.

File: test/framework/clusterctl/repository.go [hunk 3]
```diff
@@ -168,3 +170,35 @@ func YAMLForComponentSource(ctx context.Context, source ProviderVersionSource) (
...
+// getComponentSourceFromURL fetches contents of component source YAML file from provided URL source.
+func getComponentSourceFromURL(source ProviderVersionSource) ([]byte, error) {
+	var buf []byte
+
+	u, err := url.Parse(source.Value)
+	if err != nil {
+		return nil, err
+	}
+
+	switch u.Scheme {
```
Comment (JoelSpeed) [inline test/framework/clusterctl/repository.go:183]: Will `u.Scheme` always be lower case? What happens if I gave the path as `HTTPS://github.com...`? Do we need to account for this?

If `url.Parse` handles this for use and lower cases them might be worth a quick note here for future readers

Comment (GrigoriyMikhalkin) [reply test/framework/clusterctl/repository.go:183]: Yep, `url.Parse` lower cases it: https://play.golang.org/p/TgabtcSjt7L. Will add comment here.

File: test/framework/clusterctl/repository.go (hunk 2 above)
Comment (fabriziopandini) [reply test/framework/clusterctl/repository.go:186]: now that file: is optional I think this makes even more sense.
wrt to the syntax, we should rely on conventions already implemented in filepath.IsAbs, but given if this turns out to be complicated, fell free to drop the idea given this is a nit and there are already other ways to use relative paths

Comment (GrigoriyMikhalkin) [reply test/framework/clusterctl/repository.go:186]: Added support for relative paths.

File: test/framework/clusterctl/repository.go (hunk 1 above)
Comment (ashish-amarnath) [reply test/framework/clusterctl/repository.go]: That's what I expected, thanks for confirming.

**Review by JoelSpeed — COMMENTED** [review]
/lgtm
