### PR TITLE
🐛  bugfix write-to flag should only run filepath.Clean when the output file is not "" or -

### LINKED ISSUE #7970: Without the --write-to option, the "clusterctl generate cluster" command fails.
**What steps did you take and what happened:**
In clsuterctl built from latest source code for master branch, fail output yaml-template to stdout when running `clsuterctl generate cluster`.

```
$ kind create cluster
$ make clusterctl

$ ./bin/clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0-rc.0.350-7527262d765cd5", GitCommit:"7527262d765cd5b5ad74538ce50660b23c7cf999", GitTreeState:"clean", BuildDate:"2023-01-23T01:13:33Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

$ ./bin/clusterctl generate cluster test-cl  --kubernetes-version v1.26.0 --from test/infrastructure/docker/templates/cluster-template-development.yaml
Error: failed to write to destination file: open .: is a directory
```

`--write-to` option, output to any file works fine.
```
$ ./bin/clusterctl generate cluster test-cl  --kubernetes-version v1.26.0 --from test/infrastructure/docker/templates/cluster-template-development.yaml --write-to /work/cl.yaml
```

**What did you expect to happen:**
Since this command worked fine in previous versions, we hope the same result in the latest version.

**Anything else you would like to add:**
The output flag is added in the following PR.
- https://github.com/kubernetes-sigs/cluster-api/pull/7828

If this flag is not specified, the return value of `filepath.Clean()` is "."(dot), but it appears that this is not handled.
- [https://github.com/kubernetes-sigs/cluster-api/commit/8961830d924fd5793f72d8bc6f529452030a5b4e#diff-9ba3861cc0ad513df514[…]72235715e82126528bR41-R43](https://github.com/kubernetes-sigs/cluster-api/commit/8961830d924fd5793f72d8bc6f529452030a5b4e#diff-9ba3861cc0ad513df5140d091a627a6e4e03bc4688c9dc72235715e82126528bR41-R43)
- https://pkg.go.dev/path/filepath#Clean

**Environment:**
- clusterctl version: GitVersion:"v1.3.0-rc.0.350-7527262d765cd5"
- kind version: v0.17.0

/kind bug
/area clusterctl

### PR DESCRIPTION
**Pull request by Rohitrajak1807**
**What this PR does / why we need it**:
If this flag is not specified, the return value of filepath.Clean() is "."(dot), but it appears that this was not handled. It now functions as expected.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7970

### CODE REVIEW

File: cmd/clusterctl/cmd/util.go [hunk 1]
```diff
@@ -38,15 +38,14 @@ func printYamlOutput(printer client.YamlPrinter, outputFile string) error {
 	if err != nil {
 		return err
 	}
-	outputFile = filepath.Clean(strings.TrimSpace(outputFile))
```
Comment (stmcginnis) [inline cmd/clusterctl/cmd/util.go:41]: For the `if outputFile == ""` check below, I think it may be safer to keep the `strings.TrimSpace(outputFile)` here, then only do the `filePath.Clean()` below after the check.

Comment (Rohitrajak1807) [reply cmd/clusterctl/cmd/util.go:41]: done

**Comment by stmcginnis** [comment]
/lgtm

Thanks, looks great!

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve
/ok-to-test
