### PR TITLE
🐛 Provide a better error message for WaitForControlPlaneToBeReady function

### LINKED ISSUE #5552: Test framework Gomega errors are not helpful
**What steps did you take and what happened:**
I have a failing E2E test in CAPO. I do not yet know what the error is. The reported error is:

```
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-openstack/test/e2e/suites/e2e/e2e_test.go:230
Timed out after 1800.001s.
Expected
    <bool>: false
to be true
/root/go/pkg/mod/sigs.k8s.io/cluster-api/test@v0.4.3/framework/controlplane_helpers.go:167
```

From this I do not know:
* Which cluster failed
* What was expected to be true

**What did you expect to happen:**
I would like this error message to contain enough context to see at a glance what it means, and ideally to contain additional context which might indicate what the error might be.

For example:

```
Expected
  Kind: KubeadmControlPlane
  Name: <the name of the object I'm interested in>
  Spec:
    <full spec>
  Status:
    Ready: false
    FailureMessage: <quite possibly what I'm looking for>
    <rest of the status>
to match: Status.Ready = True
```

**Anything else you would like to add:**
I haven't tried it yet, but I expect that the above is something like what you'd get from:

```golang
Eventually(func() (*controlplanev1.KubeadmControlPlane, error) {
}, intervals...).Should(MatchFields(IgnoreExtras, Fields{
  "Status": MatchFields(IgnoreExtras, Fields{
    "Ready": BeTrue(),
  }),
}))
```

/kind bug
/area testing

### PR DESCRIPTION
**Pull request by pydctw**
**What this PR does / why we need it**:
Current error message for WaitForControlPlaneToBeReady function doesn't give enough information for framework consumers when test fails.
```
Expected
    <bool>: false
to be true
/root/go/pkg/mod/sigs.k8s.io/cluster-api/test@v0.4.3/framework/controlplane_helpers.go:167
```

This PR improves the error message and provides more info. See an example output with the change.
```
  {
    "kind": "KubeadmControlPlane",
    "metadata": {
      "name": "test-kcp",
      "creationTimestamp": null
    },
    "spec": {
      "version": "1.21",
      "machineTemplate": {
        "metadata": {},
        "infrastructureRef": {}
      },
      "kubeadmConfigSpec": {}
    },
    "status": {
      "replicas": 0,
      "updatedReplicas": 0,
      "readyReplicas": 0,
      "unavailableReplicas": 0,
      "initialized": false,
      "ready": false,
      "failureReason": "something happened!"
    }
  }
  
  Expected
      <string>: KubeadmControlPlane
  to match fields: {
  .Status.Ready:
  	Expected
  	    <bool>: false
  	to be true
  }
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5552

### CODE REVIEW

File: test/framework/controlplane_helpers.go [hunk 1]
```diff
@@ -154,17 +155,22 @@ type WaitForControlPlaneToBeReadyInput struct {
...
-		controlplane := &controlplanev1.KubeadmControlPlane{}
+	controlplane := &controlplanev1.KubeadmControlPlane{}
+	Eventually(func() (controlplanev1.KubeadmControlPlane, error) {
 		key := client.ObjectKey{
 			Namespace: input.ControlPlane.GetNamespace(),
 			Name:      input.ControlPlane.GetName(),
 		}
 		if err := input.Getter.Get(ctx, key, controlplane); err != nil {
-			return false, err
+			log.Logf("Failed to list the KCP: %+v", err)
```
Comment (sbueringer) [inline test/framework/controlplane_helpers.go:165]: I assume we intentionally print the err with field names? (just asking because usually we just use %v)

I assume we have to log the error here at all because the `Should` doesn't detect the error anymore, right?

There is probably no way to valid both return parameters (i.e. also err != nil )?

File: test/framework/controlplane_helpers.go [hunk 2]
```diff
@@ -154,17 +155,22 @@ type WaitForControlPlaneToBeReadyInput struct {
...
+			return *controlplane, err
 		}
-		return controlplane.Status.Ready, nil
-	}, intervals...).Should(BeTrue())
+		return *controlplane, nil
+	}, intervals...).Should(MatchFields(IgnoreExtras, Fields{
+		"Status": MatchFields(IgnoreExtras, Fields{
+			"Ready": BeTrue(),
+		}),
+	}), "KCP\n"+PrettyPrint(controlplane)+"\n")
```
Comment (sbueringer) [inline test/framework/controlplane_helpers.go:173]: I now I proposed it, but looking at the output the "KCP" prefix looks a bit redundant as the kind is also part of the printed KCP (not sure about the new lines).

WDYT about dropping "KCP"?

**Review by sbueringer — COMMENTED** [review]
Thx, look good! Just a few ideas for minor optimizations.

File: test/framework/controlplane_helpers.go (hunk 1 above)
Comment (pydctw) [reply test/framework/controlplane_helpers.go:165]: > I assume we intentionally print the err with field names? (just asking because usually we just use %v)
Good point. I saws other log statements in the file (for ex, (here](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/framework/controlplane_helpers.go#L98), [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/framework/controlplane_helpers.go#L52)) uses`+%v` and tried to follow the convention. Should we change other log statements with `%v`?

> I assume we have to log the error here at all because the `Should` doesn't check the error, right?
Yes. `Should` makes an assertion against the first argument. 

> There is probably no way to validate both return parameters (i.e. also err != nil )?
I don't think so.

File: test/framework/controlplane_helpers.go (hunk 2 above)
Comment (pydctw) [reply test/framework/controlplane_helpers.go:173]: I was also debating about it. Will drop KCP text in the beginning.

File: test/framework/controlplane_helpers.go (hunk 1 above)
Comment (sbueringer) [reply test/framework/controlplane_helpers.go:165]: Sounds good. I'm not sure about `%+v`. I wasn't aware we're using it in other cases too :). I'm fine with leaving it as is.

@fabriziopandini opinions?

Comment (ykakarap) [reply test/framework/controlplane_helpers.go]: `Eventaully` can actually handle functions that return multiple values. It runs the assertion on the first returned value and checks that all other returned values are zero-valued. In this case it is inherently checking for err to be nil and the expectation will fail otherwise. 
From [gomega docs](https://onsi.github.io/gomega/#:~:text=If%20multple%20values%20are%20returned%20by%20the%20function%2C%20Eventually%20will%20pass%20the%20first%20value%20to%20the%20matcher%20and%20require%20that%20all%20others%20are%20zero-valued.%20This%20allows%20you%20to%20pass%20Eventually%20a%20function%20that%20returns%20a%20value%20and%20an%20error%20-%20a%20common%20pattern%20in%20Go.):
>If multple values are returned by the function, Eventually will pass the first value to the matcher and require that all others are zero-valued. This allows you to pass Eventually a function that returns a value and an error - a common pattern in Go.

Comment (sbueringer) [reply test/framework/controlplane_helpers.go]: Sounds nice. The question for us is probably would it validate kcp and the error and print both results, or would it only print KCP because it returns after KCP validation fails.

Comment (ykakarap) [reply test/framework/controlplane_helpers.go]: I dont think we would want to log the error as this assertion is asynchronous and we are okay with it failing to get the KCP object a few times. Although it would be nice to wrap the error with a message so that if the eventual assertion fails (error is not nil) we get the message in the logs. (I believe it will print the final error if it is not nil)

Comment (sbueringer) [reply test/framework/controlplane_helpers.go]: But current state of the PR is fine for me, don't want to block it because of that. But we might want to open an issue to possibly improve our Eventually's

Comment (pydctw) [reply test/framework/controlplane_helpers.go]: Thinking about it, I agree with @ykakarap that we don't need to log the error here because it is `Eventually`.

> I believe it will print the final error if it is not nil
That will be the case.

Should we also remove the error log messages from other Eventually functions in the file? It doesn't need to be part of this PR but just wondering.

Comment (sbueringer) [reply test/framework/controlplane_helpers.go]: If we're sure the error is logged when the eventually fails with a incorrect KCP && err != nil => I think yes

Comment (ykakarap) [reply test/framework/controlplane_helpers.go]: >If we're sure the error is logged when the eventually fails with a incorrect KCP && err != nil => I think yes

Yes, only if the final error is logged if it is not nil.

Comment (ykakarap) [reply test/framework/controlplane_helpers.go]: I ran a test and here is how t will show up if the error is not nil. 
Timed out after 900.000s.
```
  KCP
  {
    "metadata": {
      "creationTimestamp": null
    },
    "spec": {
      "version": "",
      "machineTemplate": {
        "metadata": {},
        "infrastructureRef": {}
      },
      "kubeadmConfigSpec": {}
    },
    "status": {
      "replicas": 0,
      "updatedReplicas": 0,
      "readyReplicas": 0,
      "unavailableReplicas": 0,
      "initialized": false,
      "ready": false
    }
  }
  
  Error: Unexpected non-nil/non-zero extra argument at index 1:
        <*errors.fundamental>: this is a sample error message that should show up
```

**Comment by ykakarap** [comment]
/lgtm 
Thanks for this improvement @pydctw :)

File: test/framework/controlplane_helpers.go [hunk 3]
```diff
@@ -154,17 +155,22 @@ type WaitForControlPlaneToBeReadyInput struct {
...
-		controlplane := &controlplanev1.KubeadmControlPlane{}
+	controlplane := &controlplanev1.KubeadmControlPlane{}
+	Eventually(func() (controlplanev1.KubeadmControlPlane, error) {
 		key := client.ObjectKey{
 			Namespace: input.ControlPlane.GetNamespace(),
 			Name:      input.ControlPlane.GetName(),
 		}
 		if err := input.Getter.Get(ctx, key, controlplane); err != nil {
-			return false, err
+			log.Logf("Failed to list the KCP: %v", err)
```
Comment (ykakarap) [inline test/framework/controlplane_helpers.go:165]: As already discussed, since the error is logged if it is non-nil at the end we should not be logging this anymore. 
however, please be sure to wrap the error returned with a message to provide some more context about the error.

**Review by ykakarap — CHANGES_REQUESTED** [review]

File: test/framework/controlplane_helpers.go (hunk 1 above)
Comment (pydctw) [reply test/framework/controlplane_helpers.go]: Thanks @ykakarap for testing this. I've wrapped the error and the output will look like below.
```
  Error: Unexpected non-nil/non-zero extra argument at index 1:
  	<*errors.errorString>: &errors.errorString{s:"failed to get KCP: this is a sample error message that should show up"}
```

File: test/framework/controlplane_helpers.go (hunk 3 above)
Comment (pydctw) [reply test/framework/controlplane_helpers.go]: done

File: test/framework/controlplane_helpers.go [hunk 4]
```diff
@@ -154,17 +156,21 @@ type WaitForControlPlaneToBeReadyInput struct {
...
-		controlplane := &controlplanev1.KubeadmControlPlane{}
+	controlplane := &controlplanev1.KubeadmControlPlane{}
+	Eventually(func() (controlplanev1.KubeadmControlPlane, error) {
 		key := client.ObjectKey{
 			Namespace: input.ControlPlane.GetNamespace(),
 			Name:      input.ControlPlane.GetName(),
 		}
 		if err := input.Getter.Get(ctx, key, controlplane); err != nil {
-			return false, err
+			return *controlplane, fmt.Errorf("failed to get KCP: %v", err)
```
Comment (sbueringer) [inline test/framework/controlplane_helpers.go:166]:
```suggestion
			return *controlplane, errors.Wrapf(err, "failed to get KCP")
```
nit, Sorry last one :). We usually use errors.Wrapf to wrap errors.

Comment (mdbooth) [reply test/framework/controlplane_helpers.go:166]: The Gomega docs suggest that this error is actually ignored: https://onsi.github.io/gomega/#making-asynchronous-assertions

```
If multple values are returned by the function, Eventually will pass the first value to the matcher and require that all others are zero-valued. This allows you to pass Eventually a function that returns a value and an error - a common pattern in Go.
```

So I think you might as well just return an unwrapped error here. The interesting error message is with the PrettyPrint on line 173.

If we wanted to see this error message I think we might have to log it?

File: test/framework/controlplane_helpers.go [hunk 5]
```diff
@@ -154,17 +156,21 @@ type WaitForControlPlaneToBeReadyInput struct {
...
 		}
-		return controlplane.Status.Ready, nil
-	}, intervals...).Should(BeTrue())
+		return *controlplane, nil
+	}, intervals...).Should(MatchFields(IgnoreExtras, Fields{
+		"Status": MatchFields(IgnoreExtras, Fields{
+			"Ready": BeTrue(),
+		}),
+	}), PrettyPrint(controlplane)+"\n")
```
Comment (mdbooth) [inline test/framework/controlplane_helpers.go:173]: This could do with a wrapper explaining what it means (see above: this is the real error message). Maybe something like `"control plane failed to become ready: %s\n", PrettyPrint(...)`?

**Review by mdbooth — COMMENTED** [review]
Thanks for doing this!

File: test/framework/controlplane_helpers.go (hunk 4 above)
Comment (sbueringer) [reply test/framework/controlplane_helpers.go:166]: Please see: https://github.com/kubernetes-sigs/cluster-api/pull/5601#discussion_r745114767 ++
It looks to me like it prints the error

Comment (pydctw) [reply test/framework/controlplane_helpers.go]: Done. Thanks for the reviews. 

The output will log an error when `err != nil`.
```
  Error: Unexpected non-nil/non-zero extra argument at index 1:
  	<*errors.withStack>: failed to get KCP: this is a sample error message that should show up
```

**Comment by ykakarap** [comment]
/lgtm

Thanks for doing this @pydctw :)
