### PR TITLE
Use kubenet instead of weavenet for GCP provider

### LINKED ISSUE #83: Weave assigns conflicting IPs to Pods
_From @maisem on March 9, 2018 3:41_

cc @medinatiger @jessicaochen @rsdcastro 

Weave is assigning conflicting IPs to Pods and they also seem to be from different cidrs.
```
$ k get po --all-namespaces -o wide 
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE       IP           NODE
default       clusterapi-58c564d46b-bdc9g                2/2       Running   0          4m        10.32.0.3    gce-master-test1
default       etcd-clusterapi-0                          1/1       Running   0          4m        10.32.0.2    gce-master-test1
kube-system   etcd-gce-master-test1                      1/1       Running   0          4m        10.128.0.2   gce-master-test1
kube-system   kube-apiserver-gce-master-test1            1/1       Running   0          4m        10.128.0.2   gce-master-test1
kube-system   kube-controller-manager-gce-master-test1   1/1       Running   0          4m        10.128.0.2   gce-master-test1
kube-system   kube-dns-545bc4bfd4-g8mm4                  3/3       Running   0          5m        10.32.0.4    gce-master-test1
kube-system   kube-proxy-j8jpq                           1/1       Running   0          1m        10.128.0.3   gce-node-hwdx7
kube-system   kube-proxy-jtczr                           1/1       Running   0          5m        10.128.0.2   gce-master-test1
kube-system   kube-scheduler-gce-master-test1            1/1       Running   0          4m        10.128.0.2   gce-master-test1
kube-system   weave-net-7hkzx                            2/2       Running   0          1m        10.128.0.3   gce-node-hwdx7
kube-system   weave-net-hzgd8                            2/2       Running   1          5m        10.128.0.2   gce-master-test1

```

```
$ k get no
NAME               STATUS    ROLES     AGE       VERSION
gce-master-test1   Ready     master    5m        v1.8.3
gce-node-hwdx7     Ready     <none>    56s       v1.8.3
```

Repro steps:
```
1. ./generate-yaml.sh
1. ./gcp-deployer create -c cluster.yaml -m machines.yaml
```

_Copied from original issue: kubernetes/kube-deploy#645_

### PR DESCRIPTION
**Pull request by kcoronado**
**What this PR does / why we need it**:
This PR modifies the GCP provider to create clusters that use kubenet instead of weave. Clusters are not being created successfully (create commands would complete and spin up a master, but no nodes), so this change will spin up a working master and node(s).

Specific changes:

- Add the default service account to new master VM instances which is needed for the Kubernetes GCE cloud provider code.
- Allow IP forwarding to enable pod to pod communication.
- Add a function to the startup scripts to prevent docker from starting on installation so we can configure DOCKER_OPTS and then start it manually. This is needed to prevent it from messing with the IP tables.
- Create and set bridge-nf-call-iptables to 1 to pass the kubeadm preflight check. Everything would get set up fine with ignoring the warnings, but this workaround makes sure we don't accidentally ignore important warnings/errors in the future.
- Remove --pod-cidr flag from KUBELET_NETWORK_ARGS to fix issue with assigning conflicting IPs to pods.
- Update machines.yaml.template to use the kubenet configs in machine_setup_configs.yaml.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
#81 
Fixes #83, #115

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

File: cloud/google/serviceaccount.go [hunk 1]
```diff
@@ -65,6 +65,10 @@ func (gce *GCEClient) CreateMachineControllerServiceAccount(cluster *clusterv1.C
 		if err != nil {
 			return fmt.Errorf("couldn't grant permissions to service account: %v", err)
 		}
+		err = run("gcloud", "projects", "add-iam-policy-binding", project, "--member=serviceAccount:"+email, "--role=roles/iam.serviceAccountActor")
```
Comment (jessicaochen) [inline cloud/google/serviceaccount.go]: I need a bit of context. Why does the machine controller service account need to impersonate other accounts?

File: cloud/google/machineactuator.go [hunk 2]
```diff
@@ -285,9 +290,17 @@ func (gce *GCEClient) Create(cluster *clusterv1.Cluster, machine *clusterv1.Mach
 				Items: metadataItems,
 			},
 			Tags: &compute.Tags{
-				Items: []string{"https-server"},
+				Items: tags,
 			},
 			Labels: labels,
+			ServiceAccounts: []*compute.ServiceAccount{
```
Comment (jessicaochen) [inline cloud/google/machineactuator.go]: Need some context, why do we need a specified service account now?

File: cloud/google/machineactuator.go [hunk 3]
```diff
@@ -256,10 +256,15 @@ func (gce *GCEClient) Create(cluster *clusterv1.Cluster, machine *clusterv1.Mach
 		if gce.machineClient == nil {
 			labels[BootstrapLabelKey] = "true"
 		}
+		tags := []string{"https-server"}
+		if !util.IsMaster(machine) {
+			tags = append(tags, fmt.Sprintf("%s-worker", cluster.Name))
```
Comment (jessicaochen) [inline cloud/google/machineactuator.go]: What uses this %s-worker tag?

File: cloud/google/machineactuator.go (hunk 2 above)
Comment (kcoronado) [reply cloud/google/machineactuator.go]: There was some error in the API server when spinning up the cluster that said it couldn't fetch the initial token and that it couldn't find the default service account. I don't remember the error message exactly, but it was preventing the API server from starting. I think @mkjelland was working on replacing this default service account with something more specific, though.

File: cloud/google/serviceaccount.go (hunk 1 above)
Comment (kcoronado) [reply cloud/google/serviceaccount.go]: Once we got the master set up, there was an error message in the machine controller saying it needed access to the default service account when it was trying to create the node, so I added it here.

File: cloud/google/machineactuator.go (hunk 3 above)
Comment (kcoronado) [reply cloud/google/machineactuator.go]: Both nodes and masters get tags applied via GCE. They both get the https-server tag but only nodes get %s-worker. The master startup script creates a cloud-config file where it specifies the node-tags as %s-worker, but that doesn't add the tag to the master. I think the cloud-config is just for GCP to know how to create the firewall rules and maybe do some other networking things. I'm not 100% sure.

**Comment by pipejakob** [comment]
To expand on @jessicaochen's questions, this PR's title and description state one objective, without much context: switching the network provider from weave-net to kubenet. Looking at the diff, though, the actual changes are at least:

* Add dynamic tags to GCE worker instances
* Enable IpForwarding on all GCE instances
* Add a ServiceAccount to all GCE instances
* Grant impersonation permissions to GCE machine-controller service account
* Fix cluster creation after https://github.com/kubernetes-sigs/cluster-api/pull/104 broke it
* ... many more subtle changes?

There is a lot bundled up in this single PR! I think it would make the changes much easier to reason about if they were broken up into smaller, single-purpose diffs with clear rationales for *why* the changes are desirable.

It also sounds like the very first PR should probably contain just the changes needed to fix any regressions introduced by https://github.com/kubernetes-sigs/cluster-api/pull/104, which probably does not require changing the network provider at all. Does that sound reasonable?

File: gcp-deployer/machine_setup_configs.yaml [hunk 4]
```diff
@@ -179,10 +23,23 @@ items:
...
           apt-transport-https \
           cloud-utils \
           prips
+
+      function install_configure_docker () {
+          # prevent docker from auto-starting
+          echo "exit 101" > /usr/sbin/policy-rc.d
+          chmod +x /usr/sbin/policy-rc.d
+          trap "rm /usr/sbin/policy-rc.d" RETURN
+          apt install -y docker.io
```
Comment (pipejakob) [inline gcp-deployer/machine_setup_configs.yaml]: Unless there's an alias I didn't notice, this looks broken. Shouldn't the command be `apt-get`, not `apt`?

File: cloud/google/machineactuator.go (hunk 2 above)
Comment (krousey) [reply cloud/google/machineactuator.go]: I don't think every node needs this account. Just the masters since they are the ones that will be making GCE API calls.

Comment (krousey) [reply cloud/google/machineactuator.go]: I think we need the service account because the controller manager will be using the GCE api to handle load balancers and pod CIDR routing.

File: cloud/google/serviceaccount.go (hunk 1 above)
Comment (krousey) [reply cloud/google/serviceaccount.go]: I am also confused by this. Why does the machine controller service account need to be able to impersonate other service accounts? Shouldn't it just need the appropriate scopes to do what it needs and that's it? Or is this the permission that lets it create instances with service accounts?

Also, `iam.serviceAccountActor` has been deprecated. https://cloud.google.com/iam/docs/service-accounts#the_service_account_actor_role

File: gcp-deployer/machine_setup_configs.yaml [hunk 5]
```diff
@@ -179,10 +23,23 @@ items:
       apt-get install -y \
           socat \
           ebtables \
-          docker.io \
           apt-transport-https \
           cloud-utils \
           prips
+
+      function install_configure_docker () {
```
Comment (krousey) [inline gcp-deployer/machine_setup_configs.yaml]: Wouldn't similar changes be required for the nodes?

**Comment by kcoronado** [comment]
@pipejakob turns out cluster creation was not *as* broken as I thought it was using weavenet. It creates the master and says it creates the node, but the node doesn't exist. The command runs to completion though. I double checked what was happening before #104 was merged and this is the same functionality as before, so there weren't any regressions (I'll update the description). I must have just messed things up myself when I was testing it.

In terms of all the changes, I agree there are several things going on. I can split out the dynamic tags for GCE workers since that's adding load balancing functionality, and this doesn't prevent the cluster from starting successfully. I don't think it makes as much sense to break the rest of the changes up since they're all changes needed to fix errors when starting a cluster with kubenet. I listed the error/reason for most of the changes in the first commit in this PR, but I could move them to the PR description for better visibility. Would that work?

File: cloud/google/machineactuator.go (hunk 3 above)
Comment (kcoronado) [reply cloud/google/machineactuator.go]: I'll add the tag to the master. This change will be moved to a new PR though.

File: gcp-deployer/machine_setup_configs.yaml (hunk 5 above)
Comment (kcoronado) [reply gcp-deployer/machine_setup_configs.yaml]: I added the change in for nodes.

File: cloud/google/machineactuator.go [hunk 6]
```diff
@@ -266,10 +266,21 @@ func (gce *GCEClient) Create(cluster *clusterv1.Cluster, machine *clusterv1.Mach
 		if gce.machineClient == nil {
 			labels[BootstrapLabelKey] = "true"
 		}
+		serviceAccounts := []*compute.ServiceAccount{nil}
+		if util.IsMaster(machine) {
```
Comment (jessicaochen) [inline cloud/google/machineactuator.go]: I assuming that the service account is needed for the machine controller. The assumption here is that the machine controller only runs on the master. Could we call out that assumption in a comment.

Comment (krousey) [reply cloud/google/machineactuator.go]: It's actually needed for kubernetes' cloud provider specific code. K8s needs to be about to read compute API for faster node deletion, create advanced routes for pod CIDRs on nodes,  etc...

**Comment by krousey** [comment]
lgtm from me after you add the comment @jessicaochen wanted.

**Comment by kcoronado** [comment]
rebuilt everything and created a cluster successfully. 
/hold cancel
