### PR TITLE
🐛 Fix MachinePool nodeRef UID mismatch after K8s upgrade

### LINKED ISSUE #12388: Node UID in MachinePool nodeRef mismatch post Kubernetes upgrade
### What steps did you take and what happened?

When a K8s upgrade is performed on a Managed cluster, new nodes will come up with new UIDs. However, the MachinePool controller has an early return condition that only validates the count of NodeRefs but doesn't check if the UIDs are still valid. This leads to MachinePools retaining stale NodeRef UIDs after upgrades, causing UID mismatches that persist until manual intervention.

### What did you expect to happen?

Expected the MachinePool nodeRef to contain correct Node UIDs even after Kubernetes upgrade.

### Cluster API version

Cluster API - v1.9.4

### Kubernetes version

Kubernetes version - v1.30 & v1.31

### Anything else you would like to add?

Created AKS cluster
Cluster-API-Provider-Azure version - v1.18.0

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
**What this PR does / why we need it**:
When a K8s upgrade is performed on a Managed cluster, new nodes will come up with new UIDs. However, the MachinePool controller has an early return condition that only validates the count of NodeRefs but doesn't check if the UIDs are still valid. This leads to MachinePools retaining stale NodeRef UIDs after upgrades, causing UID mismatches that persist until manual intervention.
This PR adds UID validation logic before the early return condition.
- A new name-to-node map with the name nodeNameMap is created.
- We iterate over the mp.Status.NodeRefs and using the above map, get each each Node.
- If the Node doesn't exists or the fetched Node's UID is not matching to the UID in NodeRef, we break and continue with further reconciliation. This will set the correct nodeRef in the Machine Pool.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #12388

### CODE REVIEW

File: exp/internal/controllers/machinepool_controller_noderef.go [hunk 1]
```diff
@@ -70,8 +70,33 @@ func (r *MachinePoolReconciler) reconcileNodeRefs(ctx context.Context, s *scope)
 		readyReplicas = mp.Status.Deprecated.V1Beta1.ReadyReplicas
 	}
 	if ptr.Deref(mp.Status.Replicas, 0) == readyReplicas && len(mp.Status.NodeRefs) == int(readyReplicas) {
-		v1beta1conditions.MarkTrue(mp, clusterv1.ReplicasReadyV1Beta1Condition)
-		return ctrl.Result{}, nil
+		// Validate that the UIDs in NodeRefs are still valid
+		if s.nodeRefMap != nil {
+			// Create a name-to-node mapping for efficient lookup
+			nodeNameMap := make(map[string]*corev1.Node)
```
Comment (mboersma) [inline exp/internal/controllers/machinepool_controller_noderef.go]:
```suggestion
			nodeNameMap := make(map[string]*corev1.Node, len(s.nodeRefMap))
```

**Review by mboersma — COMMENTED** [review]
It seems reasonable to add this additional verification in general, but I wonder if this problem has been seen in providers other than CAPZ.

**Comment by sbueringer** [comment]
> It seems reasonable to add this additional verification in general, but I wonder if this problem has been seen in providers other than CAPZ.

cc @richardcase @justinsb

**Comment by MadJlzz** [comment]
Is it possible that because of such mismatch, after a scale with kubectl downgrading the number of replicas from 3 to 2 instances - capi decides to drain and delete ALL of the nodes of the machine pool? This happened to me this morning. I am using the following versions

```
> kg bootstrapproviders,controlplaneproviders,coreproviders,infrastructureproviders -A
NAMESPACE                  NAME                                                  INSTALLEDVERSION   READY
kubeadm-bootstrap-system   bootstrapprovider.operator.cluster.x-k8s.io/kubeadm   v1.9.5             True

NAMESPACE                      NAME                                                     INSTALLEDVERSION   READY
kubeadm-control-plane-system   controlplaneprovider.operator.cluster.x-k8s.io/kubeadm   v1.9.5             True

NAMESPACE     NAME                                                 INSTALLEDVERSION   READY
capi-system   coreprovider.operator.cluster.x-k8s.io/cluster-api   v1.9.5             True

NAMESPACE     NAME                                                     INSTALLEDVERSION   READY
capz-system   infrastructureprovider.operator.cluster.x-k8s.io/azure   v1.17.4            True
```

**Comment by AndiDog** [comment]
> > It seems reasonable to add this additional verification in general, but I wonder if this problem has been seen in providers other than CAPZ.
> 
> cc @richardcase @justinsb

I haven't seen this with CAPA on recently upgraded EC2-only (non-EKS) clusters. But worker nodes typically roll on Kubernetes upgrade due to the changed machine image, and I guess then this wouldn't be an issue since it's not expected that any old nodes remain. I wouldn't know why existing `Node` objects would be recreated with CAPZ, setting a new UID? Any source/issue for that?

File: exp/internal/controllers/machinepool_controller_noderef.go (hunk 1 above)
Comment (jayesh-srivastava) [reply exp/internal/controllers/machinepool_controller_noderef.go]: I have addressed this suggestion.

File: exp/internal/controllers/machinepool_controller_noderef.go [hunk 2]
```diff
@@ -70,8 +70,33 @@ func (r *MachinePoolReconciler) reconcileNodeRefs(ctx context.Context, s *scope)
...
+			for _, node := range s.nodeRefMap {
+				nodeNameMap[node.Name] = node
+			}
+
+			validNodeRefs := true
+			for _, nodeRef := range mp.Status.NodeRefs {
+				foundNode, exists := nodeNameMap[nodeRef.Name]
+
+				// If node not found or UID doesn't match, mark as invalid
+				if !exists || foundNode.UID != nodeRef.UID {
```
Comment (richardcase) [inline exp/internal/controllers/machinepool_controller_noderef.go]: It might be good to have a higher verbosity log entry if the node names are the same but the UIDs are different.

**Review by richardcase — COMMENTED** [review]
Looks good to me @jayesh-srivastava . Just the one comment/suggestion

File: exp/internal/controllers/machinepool_controller_noderef.go (hunk 2 above)
Comment (jayesh-srivastava) [reply exp/internal/controllers/machinepool_controller_noderef.go]: Addressed.

**Comment by sbueringer** [comment]
/assign @richardcase @mboersma 

lgtm from your side?

**Comment by richardcase** [comment]
From my side:

/lgtm

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve
