### PR TITLE
🌱 Enhance E2E Tests to Filter Out Extra Provider-Specific Metadata

### LINKED ISSUE #10714: Provider E2E Tests Using capie2e.ClusterClassRolloutSpec Fail Due to Extra Provider-Specific Labels
### What steps did you take and what happened?

1. Using capie2e.ClusterClassRolloutSpec to run E2E Tests for CAPV
2. As CAPV will add extra labels like `"node.cluster.x-k8s.io/esxi-host": "10.2.32.5"` by code [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/controllers/vspheremachine_controller.go#L376), the E2E Tests failed with error below
```
      <map[string]string | len:5>: {
          "topology.cluster.x-k8s.io/owned": "",
          "cluster.x-k8s.io/cluster-name": "clusterclass-rollout-gnfvcg",
          "cluster.x-k8s.io/control-plane": "",
          "cluster.x-k8s.io/control-plane-name": "clusterclass-rollout-gnfvcg-cp-vngr8",
          "node.cluster.x-k8s.io/esxi-host": "10.2.32.5",
      }
  to be equivalent to
      <e2e.unionMap | len:4>: {
          "topology.cluster.x-k8s.io/owned": "",
          "cluster.x-k8s.io/cluster-name": "clusterclass-rollout-gnfvcg",
          "cluster.x-k8s.io/control-plane": "",
          "cluster.x-k8s.io/control-plane-name": "clusterclass-rollout-gnfvcg-cp-vngr8",
      }
  In [It
```
3. The failing test is due to  [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/clusterclass_rollout.go#L459-L470) as it checks if they are equal.
4. Here is a test failure in CAPV https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3023

### What did you expect to happen?

Test passes.

### Cluster API version

v1.7.1

### Kubernetes version

_No response_

### Anything else you would like to add?

Same situation for annotation check

### Label(s) to be applied

/kind bug
/area testing
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by zhanggbj**
**What this PR does / why we need it**:

Introduced a new field FilterMetadataBeforeValidation in E2E tests
to allow filtering out labels and annotations of Machines,
InfraMachines, BootstrapConfigs, and Nodes before validation.
This feature enables the exclusion of additional infrastructure
provider-specific labels that could otherwise cause test failures.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10714

### CODE REVIEW

File: test/e2e/clusterclass_rollout.go [hunk 1]
```diff
@@ -75,6 +75,9 @@ type ClusterClassRolloutSpecInput struct {
 	// Allows to inject a function to be run after test namespace is created.
 	// If not specified, this is a no-op.
 	PostNamespaceCreated func(managementClusterProxy framework.ClusterProxy, workloadClusterNamespace string)
+
+	// ProviderSpecificLabels represents a set of labels specific to the provider.
+	ProviderSpecificLabels map[string]string
```
Comment (sbueringer) [inline test/e2e/clusterclass_rollout.go:80]: I was wondering if we should add a func like this
```
ValidateObjectMetadata func(obj client.Object) (clusterv1.ObjectMeta, error)
```

The idea is that folks can set this func and then validate metadata + return an updated version of ObjectMetadata (labels/annotaitons) that can then pass the core CAPI validation.

Basically the CAPV func would check:
* if the object is a Machine, does the Machine have the right label
  * If no => return an error
  * If yes => return a modified version of ObjectMeta without the additional label

This allows us a lot of flexibility for all label & annotation validation. (including that we don't have to specifcy correct label values up-front)

Comment (sbueringer) [reply test/e2e/clusterclass_rollout.go:80]: @chrischdi @fabriziopandini WDYT?

Comment (sbueringer) [reply test/e2e/clusterclass_rollout.go:80]: @zhanggbj Talked about it with Christian and Fabrizio.

We would prefer adding a field like this:
```go
	// FilterMetadataBeforeValidation allows filtering out labels and annotations of Machines, InfraMachines,
	// BootstrapConfigs and Nodes before we validate them.
	// This can be e.g. used to filter out additional infrastructure provider specific labels that would
	// otherwise lead to a failed test.
	FilterMetadataBeforeValidation func(object client.Object) clusterv1.ObjectMeta
```

This would then be roughly used like this

```go
				machineMetadata := clusterv1.ObjectMeta{Labels: machine.Labels, Annotations: machine.Annotations}
				if input.FilterMetadataBeforeValidation != nil {
					machineMetadata = input.FilterMetadataBeforeValidation(machine)
				}

				// MachineDeployment MachineSet Machine.metadata
				g.Expect(machineMetadata.Labels).To(BeEquivalentTo(
					union(
						map[string]string{
							clusterv1.ClusterNameLabel:                          cluster.Name,
							clusterv1.ClusterTopologyOwnedLabel:                 "",
							clusterv1.ClusterTopologyMachineDeploymentNameLabel: mdTopology.Name,
							clusterv1.MachineDeploymentNameLabel:                machineDeployment.Name,
							clusterv1.MachineSetNameLabel:                       machineSet.Name,
							clusterv1.MachineDeploymentUniqueLabel:              machineTemplateHash,
						},
						machineSet.Spec.Template.Labels,
					),
				))
				g.Expect(machineMetadata.Annotations).To(BeEquivalentTo(
					machineSet.Spec.Template.Annotations,
				))
```

Comment (zhanggbj) [reply test/e2e/clusterclass_rollout.go]: Hi @sbueringer, thanks for providing the suggestions!

I just updated assertControlPlaneMachines and assertMachineSetsMachines to ensure I understand the concept correctly. If there are no issues, I'll proceed with updating the other objects in https://github.com/kubernetes-sigs/cluster-api/blob/main/test/e2e/clusterclass_rollout.go#L311-L323.  Thanks!

File: test/e2e/clusterclass_rollout.go [hunk 2]
```diff
@@ -430,13 +436,17 @@ func assertControlPlane(g Gomega, clusterClassObjects clusterClassObjects, clust
...
 		// ControlPlane Machine.metadata
-		g.Expect(machine.Labels).To(BeEquivalentTo(
+		machineMetadata := clusterv1.ObjectMeta{Labels: machine.Labels, Annotations: machine.Annotations}
+		if filterMetadataBeforeValidation != nil {
+			machineMetadata = filterMetadataBeforeValidation(machine)
+		}
+		g.Expect(machineMetadata.Labels).To(BeEquivalentTo(
 			union(
 				map[string]string{
 					clusterv1.ClusterNameLabel:             cluster.Name,
```
Comment (sbueringer) [inline test/e2e/clusterclass_rollout.go:452]: l.462 should be
```go
				machineMetadata.Annotations,
```

File: test/e2e/clusterclass_rollout.go [hunk 3]
```diff
@@ -142,7 +148,7 @@ func ClusterClassRolloutSpec(ctx context.Context, inputGetter func() ClusterClas
 			WaitForMachineDeployments:    input.E2EConfig.GetIntervals(specName, "wait-worker-nodes"),
 			WaitForMachinePools:          input.E2EConfig.GetIntervals(specName, "wait-machine-pool-nodes"),
 		}, clusterResources)
```
Comment (sbueringer) [inline test/e2e/clusterclass_rollout.go:150]: Sorry just realized this later. Can we add this in l.120
```go
		if input.FilterMetadataBeforeValidation == nil {
			input.FilterMetadataBeforeValidation = func(obj client.Object) clusterv1.ObjectMeta {
				return clusterv1.ObjectMeta{Labels: obj.GetLabels(), Annotations: obj.GetAnnotations()}
			}
		}
```

Then we can stop handling the nil case below and just use something like this everywhere

```go
				machineMetadata := filterMetadataBeforeValidation(machine)
```

File: test/e2e/clusterclass_rollout.go (hunk 1 above)
Comment (sbueringer) [reply test/e2e/clusterclass_rollout.go]: Overall look goods (please see comments below). You already got all objects covered that we would use this func for. Currently we only think we have use cases for these

File: test/e2e/clusterclass_rollout.go (hunk 3 above)
Comment (zhanggbj) [reply test/e2e/clusterclass_rollout.go:150]: Looks great! Fixed it.

File: test/e2e/clusterclass_rollout.go (hunk 2 above)
Comment (zhanggbj) [reply test/e2e/clusterclass_rollout.go:452]: Fixed it.

**Comment by sbueringer** [comment]
Thank you!!

/lgtm
/approve
