### PR TITLE
🐛  Make MHC ClusterClass authoritative on paths

### LINKED ISSUE #5948: ClusterClass: MHC reconciliation is not authoritative
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**
I expect the MHC reconciliation to be authoritative (similar to the reconciliation of other resources).

Example:

I add one field after another to the MHC config in the ClusterClass:
```yaml
      maxUnhealthy: 50%
      unhealthyRange: "[1-2]"
      nodeStartupTimeout: "0"
      unhealthyConditions:
      - type: Ready
        status: Unknown
        timeout: 300s
      - type: Ready
        status: "False"
        timeout: 300s
      remediationTemplate:
        apiVersion: abc/v1beta1
        kind: ABCRemediation
        name: default
        namespace: default
```
The fields are correctly propagated/reconciled to the MHC.

Then I drop one of the fields (except unhealthyConditions). 
I now expect the topology controller to try to remove the field 
(and the webhook would set the default value again).

Instead the field just stays set to the value I previously had in the ClusterClass.

**Anything else you would like to add:**
In other cases this is implemented by tracking the managed fields.

**Environment:**

- Cluster-api version: main

/kind bug
/area topology
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Fixes #5948

### CODE REVIEW

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 1]
```diff
@@ -291,7 +291,7 @@ func (r *Reconciler) reconcileMachineHealthCheck(ctx context.Context, current, d
 	ctx, log = log.WithObject(current).Into(ctx)
 
 	// Check differences between current and desired MachineHealthChecks, and patch if required.
-	patchHelper, err := mergepatch.NewHelper(current, desired, r.Client)
+	patchHelper, err := mergepatch.NewHelper(current, desired, r.Client, mergepatch.AuthoritativePaths{contract.Path{"spec"}})
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/reconcile_state.go:294]: nit: let's explain why we are doing this
```suggestion
	// NOTE: we want to be authoritative on the entire spec because the users are
	// expected to change MHC fields from the ClusterClass only.
	patchHelper, err := mergepatch.NewHelper(current, desired, r.Client, mergepatch.AuthoritativePaths{contract.Path{"spec"}})
```

Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:294]: Just to surface it here too.

> It kind of works. So the patch helper unsets the field correctly. Unfortunately, because of the diff between the MHC in the ClusterClass (fields unset) and the defaulted fields in the MHC it permanently tries to patch the MHC
> https://kubernetes.slack.com/archives/C8TSNPY4T/p1642505125061200?thread_ts=1642501392.050900&cid=C8TSNPY4T

Comment (sbueringer) [reply internal/controllers/topology/cluster/reconcile_state.go:294]: I'll continue further discussion on the issue

**Comment by killianmuldoon** [comment]
The latest version now calls the defaulting method as a last step in its computation. This means there should never be a field set during defaulting which is unset on a desired MHC. The Cluster Topology controller is still authoritative on the whole "spec" of the object.

**Comment by sbueringer** [comment]
@killianmuldoon  
Overall looks good. But maybe we should inline the mhcBuilder now? It makes it very hard to assess if the test is correct in its current state.

**Comment by killianmuldoon** [comment]
I can do it in this PR and if not one pre-release. It's on my list 😄

**Comment by sbueringer** [comment]
> I can do it in this PR and if not one pre-release. It's on my list 😄 . It'll take a couple of days though I think, given other priorities.

Okay then let's do that as follow-up

**Comment by sbueringer** [comment]
Tested the scenario from the issue and a few more locally with this PR and everything behaves as expected now!

/lgtm

**Comment by fabriziopandini** [comment]
@killianmuldoon thanks for sorting out this detail
It is a small thing but it makes the user experience much more intuitive.
/lgtm
/approve
