### PR TITLE
🌱 CAPD: disable image garbage collection in kubelet to align with kind

### LINKED ISSUE #11856: [e2e test flake] Failed to run clusterctl move...failed calling webhook
### Which jobs are flaking?

periodic-cluster-api-e2e-main
periodic-cluster-api-e2e-mink8s-main
periodic-cluster-api-e2e-mink8s-release-1-9

(so far...every day seems to be a new job)

### Which tests are flaking?

capi-e2e [It] When testing Cluster API working on single-node self-hosted clusters using ClusterClass [ClusterClass] Should pivot the bootstrap cluster to a self-hosted cluster [ClusterClass]
capi-e2e [It] When testing clusterctl upgrades using ClusterClass (v1.9=>current) on K8S latest ci mgmt cluster [ClusterClass] Should create a management cluster and then upgrade all the providers [ClusterClass]
capi-e2e [It] When testing Cluster API working on self-hosted clusters using ClusterClass with a HA control plane [ClusterClass] Should pivot the bootstrap cluster to a self-hosted cluster

Two of these are failures in clusterctl moves, one is in an attempt to scale a machine deployment.

### Since when has it been flaking?

2/15/2024

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?text=failed%20to%20call%20webhook&job=.*cluster-api.*(test%7Ce2e)*&xjob=.*-provider-.*

### Reason for failure (if possible)

```
Failed to run clusterctl move
Expected success, but got an error:
    <errors.aggregate | len:2, cap:2>: 
    [action failed after 10 attempts: error creating "addons.cluster.x-k8s.io/v1beta1, Kind=ClusterResourceSet" self-hosted-gdy22l/self-hosted-b8ee9c-crs-0: Internal error occurred: failed calling webhook "validation.clusterresourceset.addons.cluster.x-k8s.io": failed to call webhook: Post "https://capi-webhook-service.capi-system.svc:443/validate-addons-cluster-x-k8s-io-v1beta1-clusterresourceset?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority, action failed after 10 attempts: error creating "cluster.x-k8s.io/v1beta1, Kind=ClusterClass" self-hosted-gdy22l/quick-start: Internal error occurred: failed calling webhook "validation.clusterclass.cluster.x-k8s.io": failed to call webhook: Post "https://capi-webhook-service.capi-system.svc:443/validate-cluster-x-k8s-io-v1beta1-clusterclass?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority]
```
```
Failed to scale machine deployment topology md-0
Expected success, but got an error:
    <*errors.withStack | 0xc001809830>: 
    failed to patch Cluster clusterctl-upgrade/clusterctl-upgrade-workload-kmb46o: Internal error occurred: failed calling webhook "validation.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://capi-webhook-service.capi-system.svc:443/validate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority
    {
```
```
[FAILED] Failed to run clusterctl move
Expected success, but got an error:
    <errors.aggregate | len:1, cap:1>: 
    action failed after 10 attempts: error adding delete-for-move annotation from "bootstrap.cluster.x-k8s.io/v1beta1, Kind=KubeadmConfig" self-hosted-ftu63g/self-hosted-43qx90-md-0-mwnng-mbk5w-jqntj: Internal error occurred: failed calling webhook "default.kubeadmconfig.bootstrap.cluster.x-k8s.io": failed to call webhook: Post "https://capi-kubeadm-bootstrap-webhook-service.capi-kubeadm-bootstrap-system.svc:443/mutate-bootstrap-cluster-x-k8s-io-v1beta1-kubeadmconfig?timeout=10s": dial tcp 10.128.51.31:443: connect: connection refused
```

### Anything else we need to know?

_No response_

### Label(s) to be applied

/kind flake
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Aligns with the configuration of kind nodes ([xref](https://github.com/kubernetes-sigs/kind/blob/79581e49b2c419a6a6dea57079670f4857811cbc/pkg/cluster/internal/kubeadm/config.go#L443-L447))

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #11856

/area provider/infrastructure-docker

### CODE REVIEW

File: test/infrastructure/docker/internal/provisioning/cloudinit/writefiles.go [hunk 1]
```diff
@@ -133,9 +133,17 @@ func fixNodeRegistration(nodeRegistration *bootstrapv1.NodeRegistrationOptions,
 		nodeRegistration.KubeletExtraArgs = map[string]string{}
 	}
 
+	// Disable disk resource management by default.
+	// The kubelet will see the host disk that the inner container runtime
+	// is ultimately backed by and attempt to recover disk space. We don't want that.
+	// See https://github.com/kubernetes-sigs/cluster-api/issues/11856 for more details.
+	if _, ok := nodeRegistration.KubeletExtraArgs[""]; !ok {
```
Comment (sbueringer) [inline test/infrastructure/docker/internal/provisioning/cloudinit/writefiles.go:140]:
```suggestion
	if _, ok := nodeRegistration.KubeletExtraArgs["image-gc-high-threshold"]; !ok {
```
I think?

Comment (sbueringer) [reply test/infrastructure/docker/internal/provisioning/cloudinit/writefiles.go:140]: Maybe worth a `defaultExtraArg` func at this point  (we have this same logic a bunch of times below)

**Comment by chrischdi** [comment]
> Strange error: [prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/11904/pull-cluster-api-e2e-latestk8s-main/1894730572488511488](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/11904/pull-cluster-api-e2e-latestk8s-main/1894730572488511488)

lol

**Comment by chrischdi** [comment]
This one should be now good to go :-)

**Comment by sbueringer** [comment]
Thank you very much!

/lgtm
/approve
