### PR TITLE
🐛 Update MachinePool bootstrap dataSecretName when bootstrap config changes

### LINKED ISSUE #6563: MachinePool does not automatically rollout changes to the bootstrap.configRef
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

I changed the bootstrap.configRef in a MachinePool and the MachinePool didn't rollout the change.

**What did you expect to happen:**

I expected the MachinePool to rollout the changes just like the MachineDeployment does.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Some more details:

Initial MachinePool
```yaml
spec:
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
          name: k8s-upgrade-and-conformance-uiq8gp-mp-0-config-cgroupfs
          namespace: k8s-upgrade-and-conformance-hf25m6
        dataSecretName: k8s-upgrade-and-conformance-uiq8gp-mp-0-config-cgroupfs
```
I updated `.spec.template.spec.bootstrap.configRef` to `k8s-upgrade-and-conformance-uiq8gp-mp-0-config` and the change was not rolled out.

The cause of this is that the dataSecretName is only set by the MachinePool controller if it is empty. If I remove the dataSecretName from the MachinePool the MachinePool controller picks up the data secret of the new BootstrapConfig and the change is rolled out.

In my opinion we should update the dataSecretName when the bootstrap configref is changed. Maybe even if the ref stays the same and only the dataSecretName in the status of the referenced resource is updated, this would probably be easier to implement as we just have to always propagate the dataSecretName of the referenced BootstrapConfig.

Notes:
* xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1653424783728609?thread_ts=1653424336.790119&cid=C8TSNPY4T
* This should not affect MachinePool bootstrap token rotation as neither the bootstrap configref nor the dataSecretName is changed in this case.
* This should not affect the case where only the dataSecretName is set and the bootstrap configref is not.

**Environment:**

- Cluster-api version: latest

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by Jont828**
…nges

**What this PR does / why we need it**:  Update MachinePool bootstrap dataSecretName when bootstrap config changes. Before, we would return early whenever the dataSecretName was set which means there's no way to update it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6563

### CODE REVIEW

File: exp/internal/controllers/machinepool_controller_phases.go [hunk 1]
```diff
@@ -197,48 +197,51 @@ func (r *MachinePoolReconciler) reconcileBootstrap(ctx context.Context, cluster
...
+		m.Status.BootstrapReady = true
+		conditions.MarkTrue(m, clusterv1.BootstrapReadyCondition)
+		return ctrl.Result{}, nil
 	}
 
-	m.Spec.Template.Spec.Bootstrap.DataSecretName = pointer.String(secretName)
-	m.Status.BootstrapReady = true
-	return ctrl.Result{}, nil
+	// Return error if neither ConfigRef nor DataSecretName are set.
+	return ctrl.Result{}, errors.Errorf("neither .spec.bootstrap.configRef nor .spec.bootstrap.dataSecretName are set for MachinePool %q in namespace %q", m.Name, m.Namespace)
```
Comment (Jont828) [inline exp/internal/controllers/machinepool_controller_phases.go:244]: @sbueringer Is this what you had in mind? It's not too difficult to update the `dataSecretName` when the `configRef != nil`, but this refactor introduces a bit of an edge case where I'm not sure how to proceed when both are nil. In fact I believe that should be an impossible case based on the webhook.

Comment (CecileRobertMichon) [reply exp/internal/controllers/machinepool_controller_phases.go:244]: correct, this should never happen because the webhook disallows it: https://github.com/kubernetes-sigs/cluster-api/blob/main/exp/api/v1beta1/machinepool_webhook.go#L107

Comment (Jont828) [reply exp/internal/controllers/machinepool_controller_phases.go:244]: Do you think we should just return an error like this then? It seems a bit awkward since it's an impossible case. Alternatively I could try to refactor some more.

Comment (CecileRobertMichon) [reply exp/internal/controllers/machinepool_controller_phases.go:244]: I think we can return an error but add a comment above that this should never happen and point to the webhook validation

File: exp/internal/controllers/machinepool_controller_phases.go [hunk 2]
```diff
@@ -197,48 +197,52 @@ func (r *MachinePoolReconciler) reconcileBootstrap(ctx context.Context, cluster
...
 
-	// Report a summary of current status of the bootstrap object defined for this machine pool.
-	conditions.SetMirror(m, clusterv1.BootstrapReadyCondition,
-		conditions.UnstructuredGetter(bootstrapConfig),
-		conditions.WithFallbackValue(ready, clusterv1.WaitingForDataSecretFallbackReason, clusterv1.ConditionSeverityInfo, ""),
-	)
+		if !ready {
+			log.V(2).Info("Bootstrap provider is not ready, requeuing")
+			m.Status.BootstrapReady = ready
+			return ctrl.Result{RequeueAfter: externalReadyWait}, nil
```
Comment (sbueringer) [inline exp/internal/controllers/machinepool_controller_phases.go:221]: @CecileRobertMichon @Jont828 I think it's a bit unrelated but while we're here. I think this requeu is not required because we're adding a watch for BootstrapConfigs in reconcileExternal. This means we automatically get a reconcile if the BootstrapConfig changes.

Or maybe I'm missing something

Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_phases.go:221]: Hm but it's the same for InfrastructureReady. Maybe we can open an issue for a follow-up PR?

Comment (Jont828) [reply exp/internal/controllers/machinepool_controller_phases.go:221]: @sbueringer My understanding was that we mainly wanted to break out of the reconcile loop without an error if we couldn't proceed in this case. Do you mean that we don't want to return a `ctrl.Result{}` here?

Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_phases.go:221]: I mean that we should return `return ctrl.Result{}, nil`

There is no reason to requeue if we get a reconcile triggered as soon as BootstrapConfig changes.

But let's keep this change out of this PR

File: exp/internal/controllers/machinepool_controller_phases.go [hunk 3]
```diff
@@ -197,48 +197,52 @@ func (r *MachinePoolReconciler) reconcileBootstrap(ctx context.Context, cluster
...
+	if m.Spec.Template.Spec.Bootstrap.DataSecretName != nil {
+		m.Status.BootstrapReady = true
+		conditions.MarkTrue(m, clusterv1.BootstrapReadyCondition)
+		return ctrl.Result{}, nil
 	}
 
-	m.Spec.Template.Spec.Bootstrap.DataSecretName = pointer.String(secretName)
-	m.Status.BootstrapReady = true
-	return ctrl.Result{}, nil
+	// This should never happen because the MachinePool webhook would not allow neither ConfigRef nor DataSecretName to be set.]
```
Comment (CecileRobertMichon) [inline exp/internal/controllers/machinepool_controller_phases.go:244]:
```suggestion
	// This should never happen because the MachinePool webhook would not allow neither ConfigRef nor DataSecretName to be set.
```

File: exp/internal/controllers/machinepool_controller_phases.go (hunk 2 above)
Comment (sbueringer) [reply exp/internal/controllers/machinepool_controller_phases.go:221]: Opened an issue: https://github.com/kubernetes-sigs/cluster-api/issues/8735

**Comment by sbueringer** [comment]
lgtm pending https://github.com/kubernetes-sigs/cluster-api/pull/8667#discussion_r1202789116

**Comment by Jont828** [comment]
Done

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Thank you very much!

/approve
