### PR TITLE
:bug: controlplane: Normalise image name for kube-proxy, and validate Kubernetes versions

### LINKED ISSUE #2689: Support variants of image tags in KCP for kube-proxy, coredns etc...
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Setting kcp.spec.version to 1.17.3 results in a kube-proxy daemonset being applied with a "1.17.3" tag.

**What did you expect to happen:**
Tag being "v1.17.3"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is currently occuring due to the reconciliation of the kube-proxy daemonset due to upgrades.

There are additional issues when dealing with version numbers that may be semver compliant, e.g. "v1.17.3+build1", but do not contain OCI compatible characters for tags.

Finally, the KCP controller should account for independent build tags for different components, e.g. API server could be at build1, and kube-proxy is at build2.

**Environment:**

- Cluster-api version: 0.3.0
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

/kind bug
/lifecycle active

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:
Normalises the image name for kube-proxy to support build suffixes for versioning.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2689 

Marking as WIP as smoke tests are conducted.

### CODE REVIEW

File: util/util.go [hunk 1]
```diff
@@ -51,6 +52,8 @@ var (
 	rnd                          = rand.New(rand.NewSource(time.Now().UnixNano()))
 	ErrNoCluster                 = fmt.Errorf("no %q label present", clusterv1.ClusterLabelName)
 	ErrUnstructuredFieldNotFound = fmt.Errorf("field not found")
+	// taken from k8s.io/cmd/kubeadm/app/util
+	kubeReleaseRegex = regexp.MustCompile(`^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([-0-9a-zA-Z_\.+]*)?$`)
```
Comment (vincepri) [inline util/util.go]: Can we use this regex in OpenAPI validation on the k8s version field so we can ensure proper inputs?

File: util/util.go [hunk 2]
```diff
@@ -64,6 +67,8 @@ func RandomString(n int) string {
 
 // ModifyImageTag takes an imageName (e.g., registry/repo:tag), and returns an image name with updated tag
 func ModifyImageTag(imageName, tagName string) (string, error) {
+	normalisedTagName := KubernetesVersionToImageTag(NormalizedBuildVersion(tagName))
```
Comment (vincepri) [inline util/util.go]: This changes the behavior of the exported `util.ModifyImageTag` which unfortunately makes our API incompatible with the previous version.

We can possibly make another function call this one instead of changing it

File: util/util.go [hunk 3]
```diff
@@ -99,6 +104,31 @@ func GetMachinesForCluster(ctx context.Context, c client.Client, cluster *cluste
...
+
+// KubernetesVersionToImageTag is helper function that replaces all
+// non-allowed symbols in tag strings with underscores.
+// Image tag can only contain lowercase and uppercase letters, digits,
+// underscores, periods and dashes.
+// Current usage is for CI images where all of symbols except '+' are valid,
+// but function is for generic usage where input can't be always pre-validated.
+// Taken from k8s.io/cmd/kubeadm/app/util
+func KubernetesVersionToImageTag(version string) string {
+	allowed := regexp.MustCompile(`[^-a-zA-Z0-9_\.]`)
```
Comment (vincepri) [inline util/util.go]: This can be also a global variable like the other one

File: util/util.go [hunk 4]
```diff
@@ -99,6 +104,31 @@ func GetMachinesForCluster(ctx context.Context, c client.Client, cluster *cluste
 	return &machines, nil
 }
 
+// Internal helper: returns normalized build version (with "v" prefix if needed)
+// If input doesn't match known version pattern, returns empty string.
+// Taken from k8s.io/cmd/kubeadm/app/util
+func NormalizedBuildVersion(version string) string {
```
Comment (vincepri) [inline util/util.go]: this seems exposed, did you want to make it private?

File: util/util.go (hunk 1 above)
Comment (fabriziopandini) [reply util/util.go]: Wouldnt this be a duplicated of the code implemented in the validation webhook?

File: util/util.go (hunk 3 above)
Comment (vincepri) [reply util/util.go]: @sedefsavas We might want to add some validation in place for fields with `imageTag` to be compliant with the above regex, we could use `kubebuilder:validation:Pattern` https://book.kubebuilder.io/reference/markers/crd-validation.html

File: controlplane/kubeadm/internal/workload_cluster.go [hunk 5]
```diff
@@ -589,7 +589,7 @@ func (w *Workload) UpdateKubeProxyImageInfo(ctx context.Context, kcp *controlpla
 	if len(ds.Spec.Template.Spec.Containers) == 0 {
 		return nil
 	}
-	newImageName, err := util.ModifyImageTag(ds.Spec.Template.Spec.Containers[0].Image, kcp.Spec.Version)
+	newImageName, err := util.ModifyImageTag(ds.Spec.Template.Spec.Containers[0].Image, util.NormalizedKubernetesBuildVersion(kcp.Spec.Version))
```
Comment (vincepri) [inline controlplane/kubeadm/internal/workload_cluster.go]: While we're at it, can we find the actual container like we do in https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/internal/workload_cluster_coredns.go#L276-L283

Comment (randomvariable) [reply controlplane/kubeadm/internal/workload_cluster.go]: Yup. Totally reasonable.

File: util/util.go (hunk 4 above)
Comment (randomvariable) [reply util/util.go]: Changing comment. Note that this was direct copied from kubeadm, and then being modified.

File: controlplane/kubeadm/internal/workload_cluster_test.go [hunk 6]
```diff
@@ -126,57 +161,92 @@ func TestUpdateKubeProxyImageInfo(t *testing.T) {
...
+				t.Fatalf("expected no error, got %s", err)
+			}
+			if proxyImage != tt.expectImage {
+				t.Fatalf("expected proxy image %s, got %s", tt.expectImage, proxyImage)
+			}
 		})
 	}
 }
+
+func (w *Workload) getProxyImageInfo(ctx context.Context) (string, error) {
```
Comment (wfernandes) [inline controlplane/kubeadm/internal/workload_cluster_test.go]: Is this method just for tests? 
If so, I recommend using the `fakeClient` to get the object information required for assertions.
If this is going to be used in other methods then maybe move it to `workload_cluster.go`.

File: util/util.go [hunk 7]
```diff
@@ -75,14 +81,31 @@ func ModifyImageTag(imageName, tagName string) (string, error) {
...
 
 	return reference.FamiliarString(reference.TagNameOnly(namedTagged)), nil
 }
 
+func KubernetesVersionIsValid(version string) bool {
+	return kubeReleaseRegex.MatchString(version)
+}
+
+func ImageTagIsValid(tagName string) bool {
+	return !ociTagAllowedChars.MatchString(tagName)
```
Comment (neolit123) [inline util/util.go]: FYI: i've been proposing in the future to block user supplied tags if they are not semver on kubeadm runtime.
this would not matter as much for immutable upgrades, but would matter if we attempt to handle vendor specific metadata in mutable upgrades.

Comment (neolit123) [reply util/util.go]: cc @rosti

File: util/util.go [hunk 8]
```diff
@@ -75,14 +81,31 @@ func ModifyImageTag(imageName, tagName string) (string, error) {
...
-	namedTagged, err := reference.WithTag(namedRef, tagName)
+	namedTagged, err := reference.WithTag(namedRef, normalisedTagName)
 	if err != nil {
 		return "", errors.Wrap(err, "failed to update image tag")
 	}
 
 	return reference.FamiliarString(reference.TagNameOnly(namedTagged)), nil
 }
 
+func KubernetesVersionIsValid(version string) bool {
```
Comment (vincepri) [inline util/util.go]: Add godoc comment pls

File: util/util.go [hunk 9]
```diff
@@ -75,14 +81,31 @@ func ModifyImageTag(imageName, tagName string) (string, error) {
...
+	return kubeReleaseRegex.MatchString(version)
+}
+
+func ImageTagIsValid(tagName string) bool {
```
Comment (vincepri) [inline util/util.go]: Godoc comment here as well

File: util/util.go [hunk 10]
```diff
@@ -75,14 +81,31 @@ func ModifyImageTag(imageName, tagName string) (string, error) {
...
+	return !ociTagAllowedChars.MatchString(tagName)
+}
+
+func ImageNameIsValid(imageName string) (bool, error) {
```
Comment (vincepri) [inline util/util.go]: godoc

File: controlplane/kubeadm/internal/workload_cluster_test.go (hunk 6 above)
Comment (vincepri) [reply controlplane/kubeadm/internal/workload_cluster_test.go]: might want to rewrite it as a function

File: util/util.go (hunk 7 above)
Comment (vincepri) [reply util/util.go]: which tags are you referring to?

Comment (randomvariable) [reply util/util.go]: semver's not strictly compatible with OCI, so would need to be careful with that. Can we cross that bridge when we come to it?

File: controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go [hunk 11]
```diff
@@ -221,6 +221,21 @@ func TestKubeadmControlPlaneValidateUpdate(t *testing.T) {
 			ImageTag: "v9.1.1",
 		},
 	}
+
+	etcdLocalImageBuildTag := before.DeepCopy()
+	etcdLocalImageBuildTag.Spec.KubeadmConfigSpec.ClusterConfiguration.Etcd.Local = &kubeadmv1beta1.LocalEtcd{
+		ImageMeta: kubeadmv1beta1.ImageMeta{
+			ImageTag: "v9.1.1_invalidBuild1",
```
Comment (wfernandes) [inline controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go]: nit: Remove `invalid` from here since this is a valid example. Got a little confused for a sec. 🙂

File: util/util.go (hunk 7 above)
Comment (neolit123) [reply util/util.go]: i'm referring to the kubeadm tags for etcd and coredns, just commented over the OCI tag logic, which is not fully related.

File: util/util.go (hunk 3 above)
Comment (randomvariable) [reply util/util.go]: image tags are in the kubeadm types, so we can't do much here atm. have added a comment in the webhook.

File: controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go (hunk 11 above)
Comment (randomvariable) [reply controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook_test.go]: Oops

File: util/util.go (hunk 7 above)
Comment (vincepri) [reply util/util.go]: adding validation seems 👍, what kind of validation seems to be seen given that what @randomvariable mentioned stands unfortunately

File: controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go [hunk 12]
```diff
@@ -50,6 +52,8 @@ func (in *KubeadmControlPlane) Default() {
 	if in.Spec.InfrastructureTemplate.Namespace == "" {
 		in.Spec.InfrastructureTemplate.Namespace = in.Namespace
 	}
+
+	in.Spec.Version = util.NormalizedKubernetesBuildVersion(in.Spec.Version)
```
Comment (vincepri) [inline controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go]: Do we actually want to change user input prefixing the `v` rather than allowing users to learn?

Comment (randomvariable) [reply controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go]: Hah, fair point

**Comment by vincepri** [comment]
@randomvariable +1 to remove wip?

**Comment by randomvariable** [comment]
I think so

File: controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go [hunk 13]
```diff
@@ -242,26 +262,50 @@ func (in *KubeadmControlPlane) validateEtcd(prev *KubeadmControlPlane) (allErrs
...
-				field.NewPath("spec", "kubeadmConfigSpec", "initConfiguration", "etcd", "local"),
-				"cannot have both local and external etcd at the same time",
+				field.NewPath("spec", "kubeadmConfigSpec", "clusterConfiguration", "etcd", "local"),
+				"cannot have both external and local etcd",
 			),
 		)
 	}
 
+	// update validations
+	if prev != nil {
```
Comment (ncdc) [inline controlplane/kubeadm/api/v1alpha3/kubeadm_control_plane_webhook.go]: We don't have any code anywhere that calls validateEtcd with a non-nil `prev`

File: controlplane/kubeadm/internal/workload_cluster.go [hunk 14]
```diff
@@ -578,28 +578,50 @@ func firstNodeNotMatchingName(name string, nodes []corev1.Node) *corev1.Node {
...
 			return errors.Wrap(err, "error patching kube-proxy DaemonSet")
 		}
 	}
 	return nil
 }
+
+func findKubeProxyContainer(ds *appsv1.DaemonSet) *corev1.Container {
+	containers := ds.Spec.Template.Spec.Containers
+	for _, c := range containers {
+		c := c
```
Comment (ncdc) [inline controlplane/kubeadm/internal/workload_cluster.go]: I'd rather do `for i := range containers` and `c := containers[i]` than shadow redeclare `c` this way.

File: controlplane/kubeadm/internal/workload_cluster.go [hunk 15]
```diff
@@ -578,28 +578,50 @@ func firstNodeNotMatchingName(name string, nodes []corev1.Node) *corev1.Node {
...
 	}
 
-	if ds.Spec.Template.Spec.Containers[0].Image != newImageName {
+	if container.Image != newImageName {
 		patch := client.MergeFrom(ds.DeepCopy())
-		ds.Spec.Template.Spec.Containers[0].Image = newImageName
+		patchKubeProxyImage(ds, newImageName)
 		if err := w.Client.Patch(ctx, ds, patch); err != nil {
 			return errors.Wrap(err, "error patching kube-proxy DaemonSet")
 		}
```
Comment (wfernandes) [inline controlplane/kubeadm/internal/workload_cluster.go]: Should we use `patch.NewHelper` to be consistent with other places?

Comment (vincepri) [reply controlplane/kubeadm/internal/workload_cluster.go]: Let's file an issue and tackle this separately

File: controlplane/kubeadm/internal/workload_cluster.go (hunk 14 above)
Comment (wfernandes) [reply controlplane/kubeadm/internal/workload_cluster.go]: Agree. I think it's a bit more readable. Also could we do this within the if condition? Seems like an unnecessary operation `if c.Name != kubeProxyKey`

**Comment by ncdc** [comment]
I'm good with this, thanks!
/lgtm
