### PR TITLE
🐛fix: clean up isDeleteReady logic

### LINKED ISSUE #1297: Machine deletes when Infra object could still exist
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I noticed Machines were deleting before their associated AWSMachines were gone. 

**What did you expect to happen:**
Machine controller waits until both bootstrap obj and infra obj are gone.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This is due to early return in `isDeleteReady`.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by rudoi**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1297 

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ncdc** [comment]
/hold

I have some comments & I don't want this to merge yet...

**Comment by ncdc** [comment]
First, thanks for tackling this!

I'd like to try to clean up this logic so it's easier to read and understand. Maybe something like this:

```go
func (r *MachineReconciler) isDeleteReady(ctx context.Context, m *clusterv1.Machine) error {
  bootstrapConfigReady := r.isBootstrapConfigDeleteReady(ctx, m.Namespace, m.Spec.Bootstrap.ConfigRef)

  infraReady := r.isInfrastructureDeleteReady(ctx, m.Namespace, m.Spec.InfrastructureRef)

  if !bootstrapConfigReady || !infraReady {
    // return requeue after error
  }
  
  return nil
}
```

And then each of the 2 new ready functions can look similar to what we have now, such as
```go
func (r *MachineReconciler) isBootstrapConfigDeleteReady(ctx context.Context, namespace string, ref *corev1.ObjectReference) bool {
  if ref == nil {
    return true
  }

  _, err := external.Get(r.Client, *ref, namespace)
  if apierrors.IsNotFound(err) {
    return true
  }
  if err != nil {
    // log the error if desirable
    return false
  }

  // still exists, log if desirable
  return false
}
```

WDYT?

**Comment by rudoi** [comment]
@ncdc perfectly reasonable, and easy enough. SGTM

File: controllers/machine_controller.go [hunk 1]
```diff
@@ -249,32 +248,33 @@ func (r *MachineReconciler) getMachinesInCluster(ctx context.Context, namespace,
...
+	if !bootstrapConfigReady || !infraReady {
 		return errors.Wrapf(&capierrors.RequeueAfterError{RequeueAfter: 10 * time.Second},
-			"delete is not ready, Infrastructure configuration still exists")
+			"delete is not ready, Bootstrap configuration or Infrastructure configuration still exists")
 	}
 
 	return nil
 }
 
+func (r *MachineReconciler) isExternalDeleteReady(ctx context.Context, namespace string, ref *corev1.ObjectReference) bool {
```
Comment (rudoi) [inline controllers/machine_controller.go]: @ncdc how do you feel about having one function for both refs like this rather than `isBootstrapConfigDeleteReady`, etc?

**Comment by ncdc** [comment]
/hold cancel

How hard would it be to add a unit test for this?

**Comment by rudoi** [comment]
> How hard would it be to add a unit test for this?

Cursory glance over the test setup that exists today - may not be that hard. I'll timebox it and see where I get.

**Comment by rudoi** [comment]
@ncdc curious for your thoughts: `fake.NewFakeClient`'s client doesn't seem to care about finalizers. Because the reconcile function tries to delete the infra and bootstrap objects, I'm having a hard time getting a reconcile unit test to return a requeue, because these objects are always properly deleted. 

I'd be happy to try and throw together some unit tests for the helper functions?

**Comment by vincepri** [comment]
@rudoi Are you talking about unit testing just `isDeleteReady` with the fake Client and assert against that?

**Comment by rudoi** [comment]
> @rudoi Are you talking about unit testing just `isDeleteReady` with the fake Client and assert against that?

Yeah, just pushed up a test to show what I mean.

**Comment by detiber** [comment]
/lgtm
/hold
holding for @ncdc to have a chance to look prior to merging.

File: controllers/machine_controller.go [hunk 2]
```diff
@@ -249,32 +248,33 @@ func (r *MachineReconciler) getMachinesInCluster(ctx context.Context, namespace,
...
+	if ref == nil {
+		return true
+	}
+
+	_, err := external.Get(r.Client, ref, namespace)
+	if apierrors.IsNotFound(err) {
+		return true
+	}
+	if err != nil {
```
Comment (ncdc) [inline controllers/machine_controller.go]: If we're not logging anything here, I think we can remove this `if` and simply return `false`, can't we?

**Comment by vincepri** [comment]
I've been working on https://github.com/kubernetes-sigs/cluster-api/issues/1290 for the Machine controller, which deletes most of this logic and replaces it with deletion requests

File: controllers/machine_controller.go (hunk 2 above)
Comment (rudoi) [reply controllers/machine_controller.go]: yep this is correct

Comment (rudoi) [reply controllers/machine_controller.go]: fixed

File: controllers/machine_controller.go [hunk 3]
```diff
@@ -249,32 +248,30 @@ func (r *MachineReconciler) getMachinesInCluster(ctx context.Context, namespace,
...
+	bootstrapConfigReady := r.isExternalDeleteReady(ctx, m.Namespace, m.Spec.Bootstrap.ConfigRef)
+	infraReady := r.isExternalDeleteReady(ctx, m.Namespace, &m.Spec.InfrastructureRef)
 
-	if _, err := external.Get(r.Client, &m.Spec.InfrastructureRef, m.Namespace); err != nil && !apierrors.IsNotFound(err) {
-		return errors.Wrapf(err, "failed to get %s %q for Machine %q in namespace %q",
-			path.Join(m.Spec.InfrastructureRef.APIVersion, m.Spec.InfrastructureRef.Kind),
-			m.Spec.InfrastructureRef.Name, m.Name, m.Namespace)
-	} else if err == nil {
+	if !bootstrapConfigReady || !infraReady {
 		return errors.Wrapf(&capierrors.RequeueAfterError{RequeueAfter: 10 * time.Second},
```
Comment (detiber) [inline controllers/machine_controller.go]: Aren't we adding watches for these types already? If so, we shouldn't need to requeue here.

Comment (ncdc) [reply controllers/machine_controller.go]: Yes, we do add watches dynamically for bootstrap and infra resources.
