### PR TITLE
🐛 handle error in case ownerRef is not set on crs binding

### LINKED ISSUE #5961: Crash on startup from ClusterResourceSetBindingController
Using backup and restore on a workload cluster with a ClusterResourceSet and ClusterResourceSetBinding which resulted in a crash on startup in the ClusterResourceSetBinding controller. The issue is a nil pointer exception due to insufficient nil checking around **https://github.com/kubernetes-sigs/cluster-api/blob/f072182406e60b1c3b6325b95e9521c1725a3d75/exp/addons/internal/controllers/clusterresourcesetbinding_controller.go#L85** 

Both cluster and error can be nil from the GetOwnerCluster function but this is not caught by our checks.

/good-first-issue

/kind bug

### PR DESCRIPTION
**Pull request by AartiJivrajani**
**What this PR does / why we need it**:
In case of a backup, the CRS Binding does have a Cluster set in the `ownerRef`. This leads to a nil pointer exception. 
This PR adds a check around the presence of this `ownerRef`. 

**Which issue(s) this PR fixes**:
Fixes #5961

### CODE REVIEW

File: exp/addons/internal/controllers/clusterresourcesetbinding_controller.go [hunk 1]
```diff
@@ -80,7 +80,12 @@ func (r *ClusterResourceSetBindingReconciler) Reconcile(ctx context.Context, req
 	if err != nil && !apierrors.IsNotFound(err) {
 		return ctrl.Result{}, err
 	}
-
+	// On a backup, the clusterResourceSetBinding will not have an ownerRef set
+	if err == nil {
```
Comment (killianmuldoon) [inline exp/addons/internal/controllers/clusterresourcesetbinding_controller.go:84]: Should this be if cluster == nil ?

File: exp/addons/internal/controllers/clusterresourcesetbinding_controller.go [hunk 2]
```diff
@@ -80,7 +80,12 @@ func (r *ClusterResourceSetBindingReconciler) Reconcile(ctx context.Context, req
 	if err != nil && !apierrors.IsNotFound(err) {
 		return ctrl.Result{}, err
 	}
-
+	// On a backup, the clusterResourceSetBinding will not have an ownerRef set
```
Comment (killianmuldoon) [inline exp/addons/internal/controllers/clusterresourcesetbinding_controller.go:83]: nit 
No need to specify this is a check for the backup case - it's a check we should be doing in all cases.

File: exp/addons/internal/controllers/clusterresourcesetbinding_controller.go [hunk 3]
```diff
@@ -80,7 +80,12 @@ func (r *ClusterResourceSetBindingReconciler) Reconcile(ctx context.Context, req
...
+	if err == nil {
+		log.Info("ownerRef not found for the clusterResourceSetBinding")
```
Comment (killianmuldoon) [inline exp/addons/internal/controllers/clusterresourcesetbinding_controller.go:85]:
```suggestion
		log.Info("ownerRef not found for the ClusterResourceSetBinding")
```

**Review by killianmuldoon — COMMENTED** [review]
Thanks for the PR @AartiJivrajani! I've taken a quick look and I'll come back to it on Monday.

File: exp/addons/internal/controllers/clusterresourcesetbinding_controller.go (hunk 1 above)
Comment (AartiJivrajani) [reply exp/addons/internal/controllers/clusterresourcesetbinding_controller.go]: You are right @killianmuldoon. My bad. 
When the ownerRef is not set, `cluster` and `err` would both be `nil`.

File: exp/addons/internal/controllers/clusterresourcesetbinding_controller.go [hunk 4]
```diff
@@ -80,7 +80,11 @@ func (r *ClusterResourceSetBindingReconciler) Reconcile(ctx context.Context, req
 	if err != nil && !apierrors.IsNotFound(err) {
```
Comment (sbueringer) [inline exp/addons/internal/controllers/clusterresourcesetbinding_controller.go:80]: @AartiJivrajani What do you think about restructuring the whole block?
```go
	if err != nil  {
		if apierrors.IsNotFound(err) {
			// If the owner cluster is already deleted, delete its ClusterResourceSetBinding.
			log.Info("deleting ClusterResourceSetBinding because the owner Cluster no longer exists")
			return ctrl.Result{}, r.Client.Delete(ctx, binding)
		}
		return ctrl.Result{}, err
	}
	
	if cluster == nil {
		log.Info("ownerRef not found for the ClusterResourceSetBinding")
		return ctrl.Result{}, nil
	}
	
	// If the owner cluster is in the deletion process, delete its ClusterResourceSetBinding.
	if !cluster.DeletionTimestamp.IsZero() {
		log.Info("deleting ClusterResourceSetBinding because the owner Cluster is currently being deleted")
		return ctrl.Result{}, r.Client.Delete(ctx, binding)
	}

	return ctrl.Result{}, nil
```
It just seems easier to me to reason through the various states `err` and `cluster` could have when separating the handling for different values of `err` and `cluster` like this

Comment (AartiJivrajani) [reply exp/addons/internal/controllers/clusterresourcesetbinding_controller.go:80]: This improves readability a lot, thank you @sbueringer :)

**Comment by sbueringer** [comment]
@AartiJivrajani Thank you!

**Comment by killianmuldoon** [comment]
Thanks for taking this on @AartiJivrajani 

/lgtm

**Comment by killianmuldoon** [comment]
@AartiJivrajani I've noticed that there's a similar missing nil-check at **https://github.com/kubernetes-sigs/cluster-api/blob/c6e30491b05f3c6bffed4e456601d6a27439efb0/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L397** Do you want to fix it? It can be part of this PR or in a follow-up

**Comment by sbueringer** [comment]
> @AartiJivrajani I've noticed that there's a similar missing nil-check at
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/c6e30491b05f3c6bffed4e456601d6a27439efb0/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L397
> 
> ** ** Do you want to fix it? It can be part of this PR or in a follow-up

If we want to include this fix (cherry-pick) in v1.1 I would prefer a follow-up PR as the current PR already fixes an issue which can occur in production.

**Comment by AartiJivrajani** [comment]
I have created a new issue for this @sbueringer @killianmuldoon -
 https://github.com/kubernetes-sigs/cluster-api/issues/5984
