### PR TITLE
🐛 CAPD: change the haproxy entrypoint to prevent getting stopped immediately after start

### LINKED ISSUE #8641: Tests failing with "No Control Plane machines came into existence."
### Which jobs are flaking?

Various

### Which tests are flaking?

Various

### Since when has it been flaking?

Months

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-mink8s-main/1656055608303947776

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

This type of failure - the workload cluster not coming up at all - is present across many tests and across all e2e jobs in 1.3, 1.4 and main.

Examples from the triage page:
- https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#a30173b03e60e562ff81
- https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-.*&xjob=.*-provider-.*#74fda7668369e3377cf4

### Label(s) to be applied

/kind flake

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

For more context see #8641.

We came to the conclusion that we can drop the `-sf 7` arguments when starting haproxy.
This seem to be able to exit the haproxy process immediately after start, resulting in not-running lb container and by that in flaky tests.

Kudos to @killianmuldoon for testing the updated arguments to see if config updating still works.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Tries to fix #8641

### CODE REVIEW

**Comment by chrischdi** [comment]
Reproduced different issue

/test pull-cluster-api-e2e-full-main
/test pull-cluster-api-e2e-informing-main

File: test/infrastructure/docker/internal/docker/kind_manager.go [hunk 1]
```diff
@@ -113,6 +114,7 @@ func (m *Manager) CreateExternalLoadBalancerNode(ctx context.Context, name, imag
 		ClusterName:  clusterName,
 		Role:         constants.ExternalLoadBalancerNodeRoleValue,
 		PortMappings: portMappings,
+		EntryPoint:   []string{"haproxy", "-sf", "7", "-W", "-db", "-f", "/usr/local/etc/haproxy/haproxy.cfg"},
```
Comment (killianmuldoon) [inline test/infrastructure/docker/internal/docker/kind_manager.go:117]:
```suggestion
		EntryPoint:   []string{"haproxy", "-W", "-db", "-f", "/usr/local/etc/haproxy/haproxy.cfg"},
```

WDYT about trying this? AFAICT it's working fine on my machine in upgrade tests. When the config is updated haproxy logs are showing workers being spun up and down correctly to take new machines into account.

If we do this we should change the []string{} to a var at the top of the file, but apart from that I'd be happy to merge this change to assess the impact.

**Comment by chrischdi** [comment]
* Rebased
* changed according review
* adjusted title
* adjusted description of the PR to be more friendly for future readers

**Comment by killianmuldoon** [comment]
/hold

For e2e-full

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by killianmuldoon** [comment]
We should hold the cherry-picks until we have some signal that this works - but I'd prefer to have them in the queue as a reminder.
