### PR TITLE
:bug: skip templating step if `describe` flag is used

### LINKED ISSUE #6316: generate provider command should not substitute variables when --describe is used
**What steps did you take and what happened:**

Running the below command I got an error about variable substitution:

```bash
> clusterctl generate provider --infrastructure aws --describe
Error: failed to perform variable substitution: value for variables [AWS_B64ENCODED_CREDENTIALS] is not set. Please set the value using os environment variables or the clusterctl config file
```

**What did you expect to happen:**

Following the clusterctl [documentation](https://cluster-api.sigs.k8s.io/clusterctl/commands/init.html?highlight=--describe#how-can-i-known-which-variables-a-provider-requires) it looks like the command should skip the substitution and output the required variables:

```bash
> AWS_B64ENCODED_CREDENTIALS="This should not be needed" clusterctl generate provider --infrastructure aws --describe
Name:               aws
Type:               InfrastructureProvider
URL:                https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/
Version:            v1.3.0
File:               infrastructure-components.yaml
TargetNamespace:    capa-system
Variables:
  - AUTO_CONTROLLER_IDENTITY_CREATOR
  - AWS_B64ENCODED_CREDENTIALS
  - AWS_CONTROLLER_IAM_ROLE
  - CAPA_EKS
  - CAPA_EKS_ADD_ROLES
  - CAPA_EKS_IAM
  - CAPA_LOGLEVEL
  - EVENT_BRIDGE_INSTANCE_STATE
  - EXP_EKS_FARGATE
  - EXP_MACHINE_POOL
  - K8S_CP_LABEL
Images:
  - k8s.gcr.io/cluster-api-aws/cluster-api-aws-controller:v1.3.0

``` 

**Anything else you would like to add:**

I opened the issue in the `cluster-api-provider-aws` repo first.
It was triaged and I was asked to move it here, original issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3307

I would be more than happy to open a PR myself if we think this is worth solving.

**Environment:**

- Cluster-api-provider-aws version: v1.3.0
- Kubernetes version: (use `kubectl version`): None 
- OS (e.g. from `/etc/os-release`):  Archlinux

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by LucaLanziani**
**What this PR does / why we need it**:

The describe flag is used to show the provider's available environment variables, clusterctl should not interpolate the config when used.

**Which issue(s) this PR fixes**:

Fixes #6316

### CODE REVIEW

**Review by ykakarap — COMMENTED** [review]
/lgtm

File: cmd/clusterctl/cmd/generate_provider.go [hunk 1]
```diff
@@ -104,7 +104,7 @@ func runGenerateProviderComponents() error {
 
 	options := client.ComponentsOptions{
 		TargetNamespace:     gpo.targetNamespace,
-		SkipTemplateProcess: gpo.raw,
+		SkipTemplateProcess: gpo.raw || gpo.textOutput,
```
Comment (sbueringer) [inline cmd/clusterctl/cmd/generate_provider.go:107]: Interesting mapping from describe => textOutput :joy: (flag name => var)

Comment (LucaLanziani) [reply cmd/clusterctl/cmd/generate_provider.go:107]: Yes, I thought that myself but I wasn't sure if a rename was in scope. I can add the rename if you think it's worth it.

Comment (sbueringer) [reply cmd/clusterctl/cmd/generate_provider.go:107]: Not sure why it was named like this originally, maybe there's a reason that we don't see.

Let's see if someone else comments (@fabriziopandini @ykakarap )

Comment (ykakarap) [reply cmd/clusterctl/cmd/generate_provider.go:107]: This command predates me and I am not aware of the original reasoning behind that naming. From the git history of the file I couldn't find any historic reasons for naming it that way. My guess would be that the variable is named `textOutput` to match the associated function named `printComponentsAsText`.

Comment (LucaLanziani) [reply cmd/clusterctl/cmd/generate_provider.go:107]: Should we resolve this and, if we think a rename is needed, open an issue or do it in another PR?

Comment (sbueringer) [reply cmd/clusterctl/cmd/generate_provider.go:107]: Just resolving it is absolutely fine

**Comment by ykakarap** [comment]
@fabriziopandini for approval.

**Comment by fabriziopandini** [comment]
@LucaLanziani sorry for getting to this late
/lgtm
/approve
Given that --describe flag is defined as "Generate configuration without variable substitution."
