### PR TITLE
🌱 MD: improve replica defaulting for autoscaler

### LINKED ISSUE #7293: MachineDeployment.spec.replicas defaulting should take into account autoscaler min/max size if defined
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Kubernetes version v1.23.8
cluster-api version v1.1.5
capa version v1.2.0
cluster-autoscaler v1.20.0

I deployed an autoscaler deployment against a workload cluster in the mgmt cluster. When I apply a large requests pod in the workload cluster and the pod is in a pending status. In this scenario, the autoscaler will work. I found the replicas of MachineSet change to 2 but the count of ready is always 1. I also check the description of MachineSet, and the MachineSet controller repeatedly created and deleted the machine.

**What did you expect to happen:**
I found a workaround in this [https://github.com/kubernetes-sigs/cluster-api/issues/5442#issuecomment-1190713981](link). He told us just unset the replicas of machineDeployments. But if I unset the replicas, it will use the default value replicas=1. I want to not only setup a cluster with replicas=3 but also make the autoscaler can work. How can I do it?

The cluster YAML like this:
```
spec: 
   topology
      workers:
          machineDeployments:
          - class: my-worker
            failureDomain: us-west-2a
            name: md-0
            replicas: 3
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The action of machineset controller
21664256338_ pic

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7293

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @abhijit-dev82
Would be great if you can check if that covers your use cases (more details in https://github.com/kubernetes-sigs/cluster-api/issues/7293#issuecomment-1403488857)

File: api/v1beta1/machinedeployment_types.go [hunk 1]
```diff
@@ -67,10 +71,18 @@ type MachineDeploymentSpec struct {
 	// +kubebuilder:validation:MinLength=1
 	ClusterName string `json:"clusterName"`
 
-	// Number of desired machines. Defaults to 1.
+	// Number of desired machines.
 	// This is a pointer to distinguish between explicit zero and not specified.
+	//
+	// Defaults to:
+	// * if the DefaultReplicasAnnotation annotation is set, use the annotation value
```
Comment (enxebre) [inline api/v1beta1/machinedeployment_types.go:78]: How does the annotation help to "mprove replica defaulting for autoscaler"?

Comment (sbueringer) [reply api/v1beta1/machinedeployment_types.go:78]: Let's assume you create a new MD which should be controlled by the autoscaler with something that continuously writes the MD (ClusterClass, GitOps, kubectl apply continuously).

In this case the MD does not have the replica field set and before this PR replicas was always defaulted to 1.

If you have autoscaler running with the default annotations it's fine as the webhook automatically picks the default based on min-size.

If you run the autoscaler with different annotations the autoscaler only takes over if the (min size, max size) range includes 1. If you want to have a higher min size the autoscaler will never take control as 1 is outside of the range.

So essentially you can use the default annotation if for whatever reason the min-size, max-size annotations don't work (because autoscaler is running with a different CAPI_GROUP, or because a different autoscaler is used that might have the same limitations as the cluster-autoscaler).

File: api/v1beta1/machinedeployment_webhook.go [hunk 2]
```diff
@@ -213,3 +261,105 @@ func (m *MachineDeployment) validate(old *MachineDeployment) error {
...
+		case oldMD.Spec.Replicas == nil:
+			return int32(minSize), nil
+		// If the old MachineDeployment replicas are lower than min size => Use the min size.
+		// Note: This will result in a scale up to get into the range where autoscaler takes over.
+		case *oldMD.Spec.Replicas < int32(minSize):
+			return int32(minSize), nil
+		// If the old MachineDeployment replicas are higher than max size => Use the max size.
+		// Note: This will result in a scale down to get into the range where autoscaler takes over.
+		case *oldMD.Spec.Replicas > int32(maxSize):
+			return int32(maxSize), nil
```
Comment (elmiko) [inline api/v1beta1/machinedeployment_webhook.go:356]: it seems like we should be emitting a log message or something here so that a user would know the value is changed from the previous?

**Review by elmiko — COMMENTED** [review]
code generally looks good to me, i have a question about when we modify the replicas

File: api/v1beta1/machinedeployment_webhook.go (hunk 2 above)
Comment (sbueringer) [reply api/v1beta1/machinedeployment_webhook.go:356]: We can. But I'm not sure if a user will notice a log line in the controller.

If we want we could return a webhook warning with a future CR version (probably v0.15 and v0.16)

Comment (elmiko) [reply api/v1beta1/machinedeployment_webhook.go:356]: i'm not sure a user would notice the log line either, but i think having some sort of audit trail is nice. presumably this is the type of thing that would be found in a debrief about "why did MachineDeployment X suddenly change replica count".

> Just to clarify. The value is not directly changed, it is first unset by the client and then the default will be the max size when running defaulting after the unset (all happens in one call)

ack, i was just thinking about the cases where an old MD is being included in autoscaling.

this isn't a blocker for me if you don't think it's a high value warning.

Comment (sbueringer) [reply api/v1beta1/machinedeployment_webhook.go:356]: > i'm not sure a user would notice the log line either, but i think having some sort of audit trail is nice.

Sounds good, will add the log lines.

**Review by fabriziopandini — COMMENTED** [review]
overall lgtm for me, only a nit on the API documentation

**Comment by sbueringer** [comment]
@elmiko @fabriziopandini Should be ready for under round of reviews

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

File: api/v1beta1/machinedeployment_types.go (hunk 1 above)
Comment (enxebre) [reply api/v1beta1/machinedeployment_types.go:78]: ah I see.
In Openshift the autoscaling annotation are not consumer facing. Are gated by operators, the annotations are impl details and so they should be transitioned in backward compatible manner regardless of the autoscaler operating over openshift.io or cluster.x-k8s.io.

As for "if for whatever reason the min-size, max-size annotations don't work..." I think we should wait to hear from real scenarios.
My preference would be to drop the annotation for now until there's a clear/stronger need.

**Comment by enxebre** [comment]
Thanks @sbueringer, dropped a comment here https://github.com/kubernetes-sigs/cluster-api/pull/7990#discussion_r1095719117, no objections other wise.

File: api/v1beta1/machinedeployment_types.go (hunk 1 above)
Comment (sbueringer) [reply api/v1beta1/machinedeployment_types.go:78]: @fabriziopandini What do you think?

If I remember correctly, all the use cases we wanted to cover work with min size and max size annotations alone and we only added the default-replicas one to support folks who might run the cluster-autoscaler with non-default annotation names.

Comment (elmiko) [reply api/v1beta1/machinedeployment_types.go:78]: > As for "if for whatever reason the min-size, max-size annotations don't work..." I think we should wait to hear from real scenarios.

this makes a lot of sense to me. maybe we should wait to see if it an issue that users will face?

**Comment by abhijit-dev82** [comment]
If autoscaler is enabled as Day 1 op on a cluster node-pool with replica field already present. Will the proposed changes take care of the Autoscaler updation on MD and replica reconciliation on the same MD  not conflicting?

**Comment by sbueringer** [comment]
> If autoscaler is enabled as Day 1 op on a cluster node-pool with replica field already present. Will the proposed changes take care of the Autoscaler updation on MD and replica reconciliation on the same MD not conflicting?

Not sure if I understand the question correctly. But I'll make examples how it would work.

Manage the MD directly (after create) with the autoscaler: (I assume this is Day 1)

* Add an entry to Cluster.spec.topology with:
  * replicas not set,
  * autoscaler min/max annotations set (let's assume min-size:3 and max-size:6)
* Cluster topology controller will create the MD
  * During MD creation the MD webhook will use the min-size 3 as default value for MD replicas
* Autoscaler takes control the replica field going forward

Hand over control of an existing MD to the autoscaler: (This would be Day 2)

* Previously the MD had been created with the following values in Cluster.spec.topology:
  * replicas set (let's use 4 as an example)
  * no autocaler annotations
* Now we hand over control by changing the entry in Cluster.spec.topology to:
  * unset the replicas field
  * add autoscaler min/max annotations  (let's assume min-size:3 and max-size:5)
* Cluster topology controller will reconcile the existing MD and thus unset replicas + set annotations
  * During MD update the MD webhook will set the replica field to 4 again. As that was the previous value of the replicas field and it is inside the (min-size,max-size) range
  * If previous replicas is outside of the range, the webhook would pick either min-size or max-size.
* Autoscaler takes control the replica field going forward

**Comment by abhijit-dev82** [comment]
Apologies for the confusion , my query was on Day-2 OP.

On unsetting the replicas field, wont the cluster size shrink and hence disrupt the application running on it. And once it is removed how will the value be reverted to on removing autoscaler ?

**Comment by sbueringer** [comment]
> Apologies for the confusion , my query was on Day-2 OP.
> 
> On unsetting the replicas field, wont the cluster size shrink and hence disrupt the application running on it. And once it is removed how will the value be reverted to on removing autoscaler ?

Just to mirror it here as well. Quickly talked about it. If during unsetting the replica field the min-size/max-size annotations are set as well, there won't be a disruption as the replica field will just stay the same (as unsetting replicas + defaulting happens in one update-MD call)

File: api/v1beta1/machinedeployment_types.go (hunk 1 above)
Comment (fabriziopandini) [reply api/v1beta1/machinedeployment_types.go:78]: I'm also ok in dropping the “machinedeployment.cluster.x-k8s.io/default-replicas” for now and eventually iterate back if we have more clear requirements, let's make sure to highlight the boundaries of the current solution (default node group name, default annotations names, only K8s autoscaler)

Comment (sbueringer) [reply api/v1beta1/machinedeployment_types.go]: I dropped the default-replicas annotation

Comment (sbueringer) [reply api/v1beta1/machinedeployment_types.go]: Where do I highlight the boundaries of the current solution?

**Comment by sbueringer** [comment]
@fabriziopandini @enxebre @elmiko @abhijit-dev82 

Removed the default-replicas annotation

File: api/v1beta1/machinedeployment_webhook.go [hunk 3]
```diff
@@ -213,3 +266,116 @@ func (m *MachineDeployment) validate(old *MachineDeployment) error {
 
 	return apierrors.NewInvalid(GroupVersion.WithKind("MachineDeployment").GroupKind(), m.Name, allErrs)
 }
+
+// With the Kubernetes autoscaler it is possible to use different annotations by configuring a different
+// "Cluster API group" than "cluster.x-k8s.io" via the "CAPI_GROUP" environment variable.
+// We only handle the default group in our implementation.
+// If the autoscaler is configured to use another group, it is still possible to overwrite the
+// default value of the replicas field via the "machinedeployment.cluster.x-k8s.io/default-replicas"
```
Comment (elmiko) [inline api/v1beta1/machinedeployment_webhook.go:274]: should probably remove this reference to the default-replicas too

**Review by elmiko — COMMENTED** [review]
thanks @sbueringer , i think just one dangling reference to the default-replicas then should be good for me

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by abhijit-dev82** [comment]
As discussed we need an bug to track that adding back the "replicas" field should be allowed when the autoscaler annotations are removed.

**Comment by sbueringer** [comment]
> As discussed we need an bug to track that adding back the "replicas" field should be allowed when the autoscaler annotations are removed.

I wouldn't call it a bug, but feel free to open an issue for it.
