### PR TITLE
🐛 Fix metadata assert failure in clusterclass rollout test

### LINKED ISSUE #10839: ClusterClassRolloutSpec Fail with metadata assertion
### What steps did you take and what happened?

1. Calling ClusterClassRolloutSpec in provider, for e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/3023/pull-cluster-api-provider-vsphere-e2e-govmomi-main/1810223220360482816
2. Test fails with the following error, as it is comparing a nil map with an empty map.
```
{Timed out after 30.000s.
The function passed to Eventually failed at /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.7.0-rc.0.0.20240704170423-b08f0abe312b/e2e/clusterclass_rollout.go:583 with:
Expected
    <map[string]string | len:0>: nil
to be equivalent to
    <e2e.unionMap | len:0>: {} failed [FAILED] Timed out after 30.000s.
The function passed to Eventually failed at /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.7.0-rc.0.0.20240704170423-b08f0abe312b/e2e/clusterclass_rollout.go:583 with:
Expected
    <map[string]string | len:0>: nil
to be equivalent to
    <e2e.unionMap | len:0>: {}
In [It] at: /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.7.0-rc.0.0.20240704170423-b08f0abe312b/e2e/clusterclass_rollout.go:340 @ 07/08/24 08:16:58.078
```

### What did you expect to happen?

No such failure

### Cluster API version

v1.7.0-rc.0.0.20240704170423-b08f0abe312b

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by zhanggbj**
**What this PR does / why we need it**:
Add union() to convert a potential nil map to an empty map, otherwise the test will faile due to compare a nil map and an empty one.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10839

/area testing

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

File: test/e2e/clusterclass_rollout.go [hunk 1]
```diff
@@ -407,7 +407,7 @@ func assertControlPlane(g Gomega, clusterClassObjects clusterClassObjects, clust
 			ccControlPlaneTemplateMachineTemplateMetadata.Labels,
 		),
 	))
-	g.Expect(controlPlaneMachineTemplateMetadata.Annotations).To(BeEquivalentTo(
+	g.Expect(union(controlPlaneMachineTemplateMetadata.Annotations)).To(BeEquivalentTo(
```
Comment (sbueringer) [inline test/e2e/clusterclass_rollout.go:410]: What is the pattern behind adding this to in some places but not in others?

Comment (zhanggbj) [reply test/e2e/clusterclass_rollout.go:410]: Hey @sbueringer ,  I only added union() for the cases which are more possible to compare a `nil` and `empty` map,  when only have union() in one of `Expect` or `BeEquivalentTo` as below
```
		g.Expect(machineDeployment.Spec.Template.Annotations).To(BeEquivalentTo(
			union(
				mdTopology.Metadata.Annotations,
				mdClass.Template.Metadata.Annotations,
			),
		))
```
I think other cases are less likely to run into this situation, such as 
```
		g.Expect(infrastructureMachineTemplate.GetAnnotations()).To(BeEquivalentTo(
			union(
				map[string]string{
					clusterv1.TemplateClonedFromGroupKindAnnotation: groupKind(mdClass.Template.Infrastructure.Ref),
					clusterv1.TemplateClonedFromNameAnnotation:      mdClass.Template.Infrastructure.Ref.Name,
				},
				ccInfrastructureMachineTemplate.GetAnnotations(),   ===> We defined expected annotations, and  if infrastructureMachineTemplate.GetAnnotations() are nil or empty, that's a failure we should catch.
			),
		))
		// MachineDeployment InfrastructureMachineTemplate.spec.template.metadata
		g.Expect(infrastructureMachineTemplateTemplateMetadata.Labels).To(BeEquivalentTo(
			ccInfrastructureMachineTemplateTemplateMetadata.Labels,  ===> Usually they either have labels defined or are nil
		))
```

Comment (zhanggbj) [reply test/e2e/clusterclass_rollout.go:410]: Look great, feel free to take it over :-)

Comment (sbueringer) [reply test/e2e/clusterclass_rollout.go:410]: Opened a PR: https://github.com/kubernetes-sigs/cluster-api/pull/10851
