### PR TITLE
✨LeaderElection configuration as flags

### LINKED ISSUE #2653: KCP: expose additional LeaderElection configuration as flags
**Background**

The default leader election configuration options are:
- `LeaseDuration`: 15 seconds
- `RenewDeadline`: 10 seconds
- `RetryPeriod`: 2 seconds

These values are quite small, but reasonable for most controllers. However, when the KCP controller is facilitating an upgrade, there is a legitimate risk that API server connectivity is disrupted (see #2652). On a self-managed cluster, because of these small values, this disruption can result in the controller losing track of its leader election. This causes the controller pod to crash. 

**The Request**

We (as self-managed cluster users) would like to be able to configure these parameters. Flags seem reasonable!

/kind feature
/cc @vincepri @mytunguyen @sethp-nr

### PR DESCRIPTION
**Pull request by trutx**
**What this PR does / why we need it**:

Enables setting manager LeaderElection options via command line flags

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #2653 

I just implemented the optional settings in these two files but there's 3 other files where they could be implemented as well:

https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/main.go
https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/main.go
https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/example-provider/main.go

Do you think it makes sense to add the flags there too?

### CODE REVIEW

File: third_party/kubernetes-drain/drain.go [hunk 1]
```diff
@@ -357,7 +357,6 @@ func waitForDelete(params waitForDeleteParams) ([]corev1.Pod, error) {
 			default:
 				return false, nil
 			}
-			return false, nil
```
Comment (randomvariable) [inline third_party/kubernetes-drain/drain.go]: This seems like an unrelated change?

Comment (trutx) [reply third_party/kubernetes-drain/drain.go]: It's actually both. It's unrelated and `third_party/` is excluded from linters, but I did run my linter on it and well, for the sake of clean code I removed that line. The same change is live [here](https://github.com/kubernetes/kubectl/blob/master/pkg/drain/drain.go#L381-L388)

**Comment by detiber** [comment]
> I just implemented the optional settings in these two files but there's 3 other files where they could be implemented as well:
>
> https://github.com/kubernetes-sigs/cluster-api/blob/master/controlplane/kubeadm/main.go

Yes, I think we'd want to expose it for the KubeadmControlPlane controller manager as well

> https://github.com/kubernetes-sigs/cluster-api/blob/master/test/infrastructure/docker/main.go

Since the docker provider is mainly used for testing, I don't think there is any need to expose leader election configuration.

> https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/example-provider/main.go

Same thing here, this provider should only be used during testing, so no need to expose leader election config here.

File: third_party/kubernetes-drain/drain.go (hunk 1 above)
Comment (detiber) [reply third_party/kubernetes-drain/drain.go]: Since the code is changed upstream, could you also update the referenced hash in `third_party/kubernetes-drain/README.md` as well (and verify any other changes that might exist in the newer version)?

File: bootstrap/kubeadm/main.go [hunk 2]
```diff
@@ -75,6 +78,15 @@ func InitFlags(fs *pflag.FlagSet) {
...
 		"Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.")
 
+	fs.DurationVar(&leaseDuration, "lease-duration", 15*time.Second,
+		"Interval at which non-leader candidates will wait to force acquire leadership (e.g. 20s)")
+
+	fs.DurationVar(&renewDeadline, "renew-deadline", 10*time.Second,
+		"Duration that the acting master will retry refreshing leadership before giving up (e.g. 15s)")
+
+	fs.DurationVar(&retryPeriod, "retry-period", 2*time.Second,
+		"Duration the LeaderElector clients should wait between tries of actions (e.g. 5s)")
```
Comment (detiber) [inline bootstrap/kubeadm/main.go]: Should we add some validation to ensure that the values are sane?

Probably an issue for followup, but we are replicating a lot of the same flags and logic between the different controllers (and also expecting providers to implement similar), I'm wondering if we need to evaluate a library for providing the common functionality.

Comment (trutx) [reply bootstrap/kubeadm/main.go]: Yeah that would make more sense than having every controller implement its own subset of options. You're right that this would make for another issue with a broader scope.

Comment (trutx) [reply bootstrap/kubeadm/main.go]: Regarding validation and sanity, do you mean parsing the values to ensure they meet the type (i.e. using `time.ParseDuration()` to validate) or do you mean making sure those values make sense (i.e. setting upper and lower limits)? Or both?

In any case, if we do that for the newly added values I see no reason why we shouldn't do it with the rest of values too. Open to anything, just lmk.

File: third_party/kubernetes-drain/drain.go (hunk 1 above)
Comment (trutx) [reply third_party/kubernetes-drain/drain.go]: Done. No changes in the other files.

File: bootstrap/kubeadm/main.go [hunk 3]
```diff
@@ -75,6 +78,15 @@ func InitFlags(fs *pflag.FlagSet) {
 	fs.BoolVar(&enableLeaderElection, "enable-leader-election", false,
 		"Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.")
 
+	fs.DurationVar(&leaseDuration, "lease-duration", 15*time.Second,
+		"Interval at which non-leader candidates will wait to force acquire leadership (e.g. 20s)")
```
Comment (chuckha) [inline bootstrap/kubeadm/main.go]: The output looks a little funny:

```
chuckh-a02:kubeadm cha$ ./kubeadm --help
Usage of ./kubeadm:
*snip*
      --lease-duration duration               Interval at which non-leader candidates will wait to force acquire leadership (e.g. 20s) (default 15s)
      --retry-period duration                 Duration the LeaderElector clients should wait between tries of actions (e.g. 5s) (default 2s)
```

Maybe the description doesn't need the example since there is an example in the default value already. The  other places we list examples are when the default value is empty and therefore has no default displayed.

Perhaps the explanation could say the value needs to be a duration string? That's at least what the [go docs](https://golang.org/pkg/time/#ParseDuration) call it.

File: bootstrap/kubeadm/main.go [hunk 4]
```diff
@@ -61,6 +61,9 @@ func init() {
 var (
 	metricsAddr              string
 	enableLeaderElection     bool
+	leaseDuration            time.Duration
+	renewDeadline            time.Duration
+	retryPeriod              time.Duration
```
Comment (vincepri) [inline bootstrap/kubeadm/main.go]: should we prefix these and the relevant CLI flags with `leaderElection` to be more explicit?

File: bootstrap/kubeadm/main.go [hunk 5]
```diff
@@ -78,14 +78,14 @@ func InitFlags(fs *pflag.FlagSet) {
 	fs.BoolVar(&enableLeaderElection, "enable-leader-election", false,
 		"Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.")
 
-	fs.DurationVar(&leaseDuration, "lease-duration", 15*time.Second,
-		"Interval at which non-leader candidates will wait to force acquire leadership (e.g. 20s)")
+	fs.DurationVar(&leaderElectionLeaseDuration, "lease-duration", 15*time.Second,
```
Comment (vincepri) [inline bootstrap/kubeadm/main.go]:
```suggestion
	fs.DurationVar(&leaderElectionLeaseDuration, "leader-election-lease-duration", 15*time.Second,
```

& others as well

Comment (rudoi) [reply bootstrap/kubeadm/main.go]: dang didn't even get to make my second commit!

File: bootstrap/kubeadm/main.go (hunk 2 above)
Comment (rudoi) [reply bootstrap/kubeadm/main.go]: https://github.com/kubernetes-sigs/cluster-api/issues/2710

File: bootstrap/kubeadm/main.go (hunk 3 above)
Comment (rudoi) [reply bootstrap/kubeadm/main.go]: replaced redundant example with "duration string", don't @ me 8)

**Comment by vincepri** [comment]
LGTM pending squash

**Comment by trutx** [comment]
Back from pseudo-holidays and all the work is done. Thanks y'all :D
