### PR TITLE
🌱  Refactor MHC tests

### LINKED ISSUE #3539: Resolve unit test flake in MHC
CAPI unit tests are seeing flakes.
k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api#unit%20tests
seems to be mostly MachineHealthCheck

/kind bug

For context, this is post #3209. 

Local testing at the time under ginkgo's "run until failure" mode was not failing, so maybe a resource issue.

### PR DESCRIPTION
**Pull request by wfernandes**
**What this PR does / why we need it**:
This PR refactors some flaky MHC tests. It is moving us away from Ginkgo to vanilla Go test with envtest.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3539 

**NOTES**
- There are currently three tests that have been marked with `t.Skip`. As of now, they seem to be the most flaky (on my machine). Also there is an opportunity to refactor them using conditions. See #3026 for more info. The refactor of these tests can be done in separate PRs if not part of the work for #3026.
- There are still Ginkgo tests in the `controllers` package. We should refactor those tests as well, so that we can have more consistent tests. This can be done in subsequent PRs. IMO these are great `good-first-issue`s and helps make our test codebase more consistent!

### CODE REVIEW

File: controllers/suite_test.go [hunk 1]
```diff
@@ -45,14 +47,93 @@ const (
 )
 
 var (
-	testEnv           *helpers.TestEnvironment
-	clusterReconciler *ClusterReconciler
-	ctx               = context.Background()
+	testEnv  *helpers.TestEnvironment
+	ctx      = context.Background()
+	testEnv1 *helpers.TestEnvironment
```
Comment (wfernandes) [inline controllers/suite_test.go:52]: Since there are other ginkgo/envtest tests in this package, I've created a second testEnv for now to isolate the flakes happening in the MHC tests.

- Can we even have two envtest environments running together? 
- Should we have a separate PR to convert the other ginkgo/envtest style tests in this package to use this vanilla go test pattern?

File: controllers/suite_test.go [hunk 2]
```diff
@@ -45,14 +47,93 @@ const (
...
+		panic(fmt.Sprintf("unable to create cluster cache tracker: %v", err))
+	}
+	if err := (&remote.ClusterCacheReconciler{
+		Client:  testEnv1,
+		Log:     log.Log,
+		Tracker: tracker,
+	}).SetupWithManager(testEnv1.Manager, controller.Options{MaxConcurrentReconciles: 1}); err != nil {
+		panic(fmt.Sprintf("Failed to start ClusterCacheReconciler: %v", err))
+	}
+	// TODO: (wfernandes) Do we need these reconcilers for the MHC tests?
```
Comment (wfernandes) [inline controllers/suite_test.go:76]: I believe these reconcilers can be added if we convert the remaining ginkgo/envtest tests to use the vanilla go test pattern. I've commented these out so that we can focus on the bare minimum for what's needed for the MHC tests.

File: controllers/machinehealthcheck_controller_test.go [hunk 3]
```diff
@@ -111,841 +110,968 @@ func newInfraMachine(machine *clusterv1.Machine) (*unstructured.Unstructured, st
...
-						machine.Status = machineStatus
-						machine.Status.NodeRef = &corev1.ObjectReference{
-							Name: node.Name,
-						}
-
-						now := metav1.NewTime(time.Now())
-						machine.Status.LastUpdated = &now
-						Expect(testEnv.Status().Patch(ctx, &machine, machinePatch)).To(Succeed())
-					}
+func TestMachineHealthCheck_Reconcile(t *testing.T) {
```
Comment (wfernandes) [inline controllers/machinehealthcheck_controller_test.go:113]: This is a big diff. But essentially, I'm pulling out each `Specify` block into a separate `t.Run` subtest and isolating all the objects it requires so as to minimize shared state.

**Review by wfernandes — COMMENTED** [review]
Just left some comments to clarify some things.

File: controllers/machinehealthcheck_controller_test.go [hunk 4]
```diff
@@ -111,841 +110,1004 @@ func newInfraMachine(machine *clusterv1.Machine) (*unstructured.Unstructured, st
...
+			err := testEnv1.Get(ctx, util.ObjectKey(unhealthyMachine), machine)
+			return apierrors.IsNotFound(err) || !machine.DeletionTimestamp.IsZero()
+		}, timeout, time.Second)
+	})
 
-		Specify("when a machine is paused", func() {
-			mhc.Spec.ClusterName = cluster.Name
-			Expect(testEnv.Create(ctx, mhc)).To(Succeed())
+	t.Run("when a machine is paused", func(t *testing.T) {
+		t.Skip("skipping until made stable")
```
Comment (wfernandes) [inline controllers/machinehealthcheck_controller_test.go:860]: There are a few skipped tests. These tests are very unstable. Will review them after some other conditions related work gets merged in.

File: controllers/machinehealthcheck_targets.go [hunk 5]
```diff
@@ -228,7 +228,11 @@ func (r *MachineHealthCheckReconciler) getNodeFromMachine(clusterClient client.R
 		Name: machine.Status.NodeRef.Name,
 	}
 	err := clusterClient.Get(context.TODO(), nodeKey, node)
-	return node, err
+	// if it cannot find a node, send a nil node back...
```
Comment (wfernandes) [inline controllers/machinehealthcheck_targets.go:231]: This didn't seem correct.
`getNodeFromMachine` should return a nil node if it cannot find any node because that nil check happens in the `needRemediation` method for the healthCheckTarget.

File: controllers/suite_test.go (hunk 2 above)
Comment (wfernandes) [reply controllers/suite_test.go:75]: The way some of these tests are written, I don't see how these are "unit" tests anymore. They definitely feel like integration tests since they rely on other reconcilers to set state on certain objects like `Machine` and `MachineSet` in order for the MHC reconciler to work.

**Comment by wfernandes** [comment]
This is a seemingly big PR. I'm happy to walkthrough this PR if it helps reviewers.

File: controllers/machinehealthcheck_targets.go (hunk 5 above)
Comment (ncdc) [reply controllers/machinehealthcheck_targets.go:231]: cc @JoelSpeed

Comment (JoelSpeed) [reply controllers/machinehealthcheck_targets.go:231]: I think was a hangover from an original version where if the node wasn't found, we would see a non-nil node with no UID which would suggest the node no longer exists, this was replaced by `nodeMissing` as a field on the target struct.

I think therefore, that this change is fine :)

Comment (wfernandes) [reply controllers/machinehealthcheck_targets.go:231]: Thanks for the confirmation @JoelSpeed!

File: controllers/remote/suite_test.go [hunk 6]
```diff
@@ -41,11 +41,11 @@ var (
 	ctx     = context.Background()
 )
 
-func TestAPIs(t *testing.T) {
+func TestGinkgoSuite(t *testing.T) {
```
Comment (wfernandes) [inline controllers/remote/suite_test.go:44]: Not sure where `TestAPIs` came from but I thought this was more clear as to what is happening.

File: controllers/machinehealthcheck_controller_test.go [hunk 7]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+	}, providerID
+}
+
+func fakeNodesMachines(
+	g *WithT,
+	n int,
+	healthy bool,
+	assignNodeRef bool,
+	mhc *clusterv1.MachineHealthCheck,
+	c *clusterv1.Cluster,
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1497]: What about making an input struct assigning more expressive names to vars, see we will improve test readability. E.g.
healthy --> forceNodeUnhealthy
assignNodeRef --> skipNodeCreation (inverted, assuming default behaviour for setupMachinesAndFakeNodes is to create)

File: controllers/machinehealthcheck_controller_test.go [hunk 8]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+		machines []*clusterv1.Machine
+	)
+
+	for i := 0; i < n; i++ {
+		machine := newMachine(mhc, c)
+		infraMachine, providerID := newInfraMachine(&machine)
+		node := newNode()
+		if !healthy {
+			setNodeUnhealthy(&node)
+		}
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1511]: Move down into the if?

File: controllers/machinehealthcheck_controller_test.go [hunk 9]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+		machine.Spec.InfrastructureRef = corev1.ObjectReference{
+			APIVersion: infraMachine.GetAPIVersion(),
+			Kind:       infraMachine.GetKind(),
+			Name:       infraMachine.GetName(),
+		}
+		// TODO: Add comment on what's happening here. I think we are making
+		// the InfraMachine look like its healthy and ready.
+		infraMachinePatch := client.MergeFrom(infraMachine.DeepCopy())
+		g.Expect(unstructured.SetNestedField(infraMachine.Object, true, "status", "ready")).To(Succeed())
+		g.Expect(testEnv.Status().Patch(ctx, infraMachine, infraMachinePatch)).To(Succeed())
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1523]: Might be I'm missing something, but I find strange to create objects and then patch them (here and down in the func).
Should we instead create the objects, set fields according to the flags, and then create at the end when the objects are fully configured?

File: controllers/machinehealthcheck_controller_test.go [hunk 10]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+
+func setNodeUnhealthy(node *corev1.Node) {
+	node.Status.Conditions[0] = corev1.NodeCondition{
+		Type:               corev1.NodeReady,
+		Status:             corev1.ConditionUnknown,
+		LastTransitionTime: metav1.NewTime(time.Now().Add(-10 * time.Minute)),
+	}
+}
+
+func newInfraMachine(machine *clusterv1.Machine) (*unstructured.Unstructured, string) {
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1474]: nit: given that `newInfraMachine` is always called after `newMachine`, should we merge the two function and get `newMachine` to return both machine and infra machine?

File: controllers/machinehealthcheck_controller_test.go [hunk 11]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+			lastUp := metav1.NewTime(machine.Status.LastUpdated.Add(time.Second))
+			machine.Status.LastUpdated = &lastUp
+			g.Expect(testEnv.Status().Patch(ctx, &machine, machinePatch)).To(Succeed())
+		}
+
+		machines = append(machines, &machine)
+	}
+
+	cleanup := func() {
+		fmt.Println("Cleaning up nodes and machines")
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1571]: It seems we are not cleaning up infra machines

File: controllers/machinehealthcheck_controller_test.go [hunk 12]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+		if assignNodeRef {
+			machineStatus := machine.Status
+			node.Spec.ProviderID = providerID
+			nodeStatus := node.Status
+			g.Expect(testEnv.Create(ctx, &node)).To(Succeed())
+			fmt.Printf("node created: %s\n", node.GetName())
+
+			nodePatch := client.MergeFrom(node.DeepCopy())
+			node.Status = nodeStatus
+			g.Expect(testEnv.Status().Patch(ctx, &node, nodePatch)).To(Succeed())
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1551]: why are we setting again the node status using a patch?

File: controllers/machinehealthcheck_controller_test.go [hunk 13]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+			nodes = append(nodes, &node)
+
+			machinePatch := client.MergeFrom(machine.DeepCopy())
+			machine.Status = machineStatus
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1555]: why are we setting again machine status?

File: controllers/machinehealthcheck_controller_test.go [hunk 14]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+			machine.Status.NodeRef = &corev1.ObjectReference{
+				Name: node.Name,
+			}
+
+			// adding a second to ensure there is a difference from the
+			// original time so that the patch works.
+			lastUp := metav1.NewTime(machine.Status.LastUpdated.Add(time.Second))
+			machine.Status.LastUpdated = &lastUp
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1563]: why are we altering status.LastUpdated?

File: controllers/machinehealthcheck_controller_test.go [hunk 15]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+				"namespace":    machine.Namespace,
+			},
+			"spec": map[string]interface{}{
+				"providerID": providerID,
+			},
+		},
+	}, providerID
+}
+
+func fakeNodesMachines(
```
[the remark this answers is not in the document]
Comment (fabriziopandini) [reply controllers/machinehealthcheck_controller_test.go:1491]: second thought on this:
this func implements  a different pattern than the one in newXX or in setup, because in this case we are returning some of the objects and a cleanup func, while in both the other cases we are not returning a cleanup func.
What about dropping the cleanup parameter ad return the infrastructureMachines instead

File: controllers/machinehealthcheck_controller_test.go [hunk 16]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
 		UID:        cc.UID,
 	}
 }
+
+func setup(g *WithT) (*clusterv1.Cluster, *clusterv1.MachineHealthCheck) {
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1386]:
```suggestion
func createNamaspaceClusterAndMHC(g *WithT) (*clusterv1.Cluster, *clusterv1.MachineHealthCheck) {
```
I find kind of confusing this func creating ns and cluster, while returning the MHC without creating int.what about adding an an input parameter providing a func to mutate the mhc, so we can create it inside this func?

File: controllers/machinehealthcheck_controller_test.go [hunk 17]
```diff
@@ -46,906 +45,859 @@ import (
...
-						machine.Status.LastUpdated = &now
-						Expect(testEnv.Status().Patch(ctx, &machine, machinePatch)).To(Succeed())
-					}
+func TestMachineHealthCheck_Reconcile(t *testing.T) {
+	t.Run("it should ensure the correct cluster-name label with no existing labels exist", func(t *testing.T) {
+		g := NewWithT(t)
+		ctx := context.TODO()
+		cluster, mhc := setup(g)
+
+		mhc.Spec.ClusterName = cluster.Name
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:54]: I see this line in all tests, what about moving into setup?

File: controllers/machinehealthcheck_controller_test.go [hunk 18]
```diff
@@ -46,906 +45,859 @@ import (
...
-						machine.Status.NodeRef = &corev1.ObjectReference{
-							Name: node.Name,
-						}
-
-						now := metav1.NewTime(time.Now())
-						machine.Status.LastUpdated = &now
-						Expect(testEnv.Status().Patch(ctx, &machine, machinePatch)).To(Succeed())
-					}
+func TestMachineHealthCheck_Reconcile(t *testing.T) {
+	t.Run("it should ensure the correct cluster-name label with no existing labels exist", func(t *testing.T) {
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:49]:
```suggestion
	t.Run("it should ensure the correct cluster-name label when no existing labels exist", func(t *testing.T) {
```

File: controllers/machinehealthcheck_controller_test.go [hunk 19]
```diff
@@ -1460,3 +1382,232 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
 		UID:        cc.UID,
 	}
 }
+
+func setup(g *WithT) (*clusterv1.Cluster, *clusterv1.MachineHealthCheck) {
+	ns, err := testEnv.CreateNamespace(ctx, "test-ns")
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1387]:
```suggestion
	ns, err := testEnv.CreateNamespace(ctx, "test-mhc")
```

File: controllers/machinehealthcheck_controller_test.go [hunk 20]
```diff
@@ -46,906 +45,859 @@ import (
...
-					}
+func TestMachineHealthCheck_Reconcile(t *testing.T) {
+	t.Run("it should ensure the correct cluster-name label with no existing labels exist", func(t *testing.T) {
+		g := NewWithT(t)
+		ctx := context.TODO()
+		cluster, mhc := setup(g)
+
+		mhc.Spec.ClusterName = cluster.Name
+		mhc.Labels = map[string]string{}
+		mhc.SetGenerateName("correct-cluster-name-label-with-no-existing-labels-")
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:56]: being in a separated ns, might be that having a specific generated name for each test does not add much values. Should we drop?

**Review by fabriziopandini — COMMENTED** [review]
@wfernandes thanks for this PR! 
I made a first pass focusing on stream-lining how do we create test objects, and leaving some comments trying to make it explicit what is generated for each test, and to make consistent how do we create/cleanup.
I will make another pass on test content once we finalize ^^

File: controllers/remote/suite_test.go (hunk 6 above)
Comment (vincepri) [reply controllers/remote/suite_test.go:44]: Kubebuilder used to (probably still does) generate it like this

File: controllers/suite_test.go [hunk 21]
```diff
@@ -70,61 +57,85 @@ var _ = BeforeSuite(func(done Done) {
...
+		panic(fmt.Sprintf("Failed to stop envtest: %v", err))
 	}
-})
+
+	os.Exit(code)
+}
+
+// TestGinkgoSuite will run the ginkgo tests.
+// This will run with the testEnv setup and teardown in TestMain.
+func TestGinkgoSuite(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (wfernandes) [reply controllers/suite_test.go:130]: Yes. This runs the Ginkgo tests in this package that haven't yet been migrated to go test. I'm waiting for this PR to merge in before I incrementally start refactoring the ginkgo tests to the new style.

I found the original `TestAPIs` to be confusing so I just made it clear that this was the go test that kicks off the ginkgo suite.

File: controllers/machinehealthcheck_controller_test.go (hunk 9 above)
Comment (wfernandes) [reply controllers/machinehealthcheck_controller_test.go:1523]: TBH I didn't refactor this func and left the original behavior because I was unsure as to why we were doing some of these patches. I had added a bunch of comments asking why we were doing these things as well. 😄 

I can try refactoring this function to see if it can be improved upon further.

File: controllers/machinehealthcheck_controller_test.go (hunk 12 above)
Comment (wfernandes) [reply controllers/machinehealthcheck_controller_test.go:1551]: Yeah...I was asking myself this question as well 😄 . I didn't know if there was something interesting happening in the controllers that this needed to be set specifically for the MHC controller.

File: controllers/machinehealthcheck_controller_test.go (hunk 14 above)
Comment (wfernandes) [reply controllers/machinehealthcheck_controller_test.go:1563]: LastUpdated needs to be set on the machine so that some logic in the MHC controller (_I believe in `healthCheckTarget/needsRemediation()`_) can be tested. I tried setting this field on the machine object when it was created in the beginning but for some reason the cache wasn't getting updated. It only seemed to work when we patched it like this. Maybe I'm missing something or we just need to wait a little longer until the cache gets updated.

File: controllers/machinehealthcheck_controller_test.go (hunk 12 above)
Comment (wfernandes) [reply controllers/machinehealthcheck_controller_test.go:1551]: After looking at it some more I noticed that we are using the status client to patch the object. I'm wondering if we cannot create an object with Status fields set and we need the status client specifically to patch them in. This is just a guess.

**Comment by wfernandes** [comment]
@fabriziopandini Thanks for the feedback!

I did some of the refactors to clean up the code and make it more readable. I left some of the stuff back because I can see better opportunities of refactoring when we convert the other ginkgo tests to go testing as well. For example, the code in `suite_util_test.go`. 

Also maybe we can do some of the other refactors in separate smaller PRs since this one is already massive! WDYT?

File: controllers/machinehealthcheck_controller_test.go [hunk 22]
```diff
@@ -1383,8 +1371,10 @@ func ownerReferenceForCluster(ctx context.Context, g *WithT, c *clusterv1.Cluste
 	}
 }
 
-func setup(g *WithT) (*clusterv1.Cluster, *clusterv1.MachineHealthCheck) {
-	ns, err := testEnv.CreateNamespace(ctx, "test-ns")
+// setup creates a namespace in the test environment. It then creates a
+// Cluster and KubeconfigSecret for that cluster in said namespace.
+func setup(g *WithT) *clusterv1.Cluster {
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1376]:
```suggestion
func createNamespaceAndCluster(g *WithT) *clusterv1.Cluster {
```

File: controllers/machinehealthcheck_controller_test.go [hunk 23]
```diff
@@ -1582,25 +1551,35 @@ func fakeNodesMachines(
 	return nodes, machines, cleanup
 }
 
-func newTestMachineHealthCheck(name, namespace, cluster string, labels map[string]string) *clusterv1.MachineHealthCheck {
+func newMHCWithLabels(name, namespace, cluster string, labels map[string]string) *clusterv1.MachineHealthCheck {
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:1554]:
```suggestion
func newMachineHealthCheckWithLabels(name, namespace, cluster string, labels map[string]string) *clusterv1.MachineHealthCheck {
```
given that in all the other places we are using the full name

File: controllers/machinehealthcheck_controller_test.go (hunk 9 above)
Comment (fabriziopandini) [reply controllers/machinehealthcheck_controller_test.go:1488]: ok, good catch.
AFAIK no, you can't set the status during create (status is to be set by the controllers).

**Comment by fabriziopandini** [comment]
> Also maybe we can do some of the other refactors in separate smaller PRs since this one is already massive! WDYT?

@wfernandes ok, I leave to you the option to draw the line; I'm just focusing on this area because in the previous version it was really difficult to understand which object where to create during test setup, and as a consequence it was difficult to debug and understand tests.

File: controllers/machinehealthcheck_controller_test.go [hunk 24]
```diff
@@ -46,906 +45,847 @@ import (
...
-		},
-		Status: corev1.NodeStatus{
-			Conditions: []corev1.NodeCondition{
-				{Type: corev1.NodeReady, Status: corev1.ConditionTrue},
-			},
-		},
-	}
-	return node
-}
+func TestMachineHealthCheck_Reconcile(t *testing.T) {
```
Comment (fabriziopandini) [inline controllers/machinehealthcheck_controller_test.go:48]: nit: might be worth to consider to break down tests in more than one Test func

File: controllers/machinehealthcheck_controller_test.go (hunk 10 above)
Comment (wfernandes) [reply controllers/machinehealthcheck_controller_test.go:1446]: I left this as is because then we also have the providerID to consider.

File: controllers/machinehealthcheck_controller_test.go [hunk 25]
```diff
@@ -46,906 +45,847 @@ import (
...
-						fmt.Fprintf(GinkgoWriter, "error cannot retrieve mhc in ctx: %s\n", err)
-						return nil
-					}
-					return mhc.GetOwnerReferences()
-				}, timeout, time.Second).Should(And(
-					ContainElement(ownerReferenceForCluster(ctx, cluster)),
-					HaveLen(1),
-				))
-			})
+	t.Run("it marks unhealthy machines for remediation when all Machines are healthy", func(t *testing.T) {
```
Comment (ncdc) [inline controllers/machinehealthcheck_controller_test.go:178]: Maybe rename this "it doesn't mark anything unhealthy when all Machines are healthy"?

File: controllers/machinehealthcheck_controller_test.go [hunk 26]
```diff
@@ -46,906 +45,847 @@ import (
...
+		// Create the MachineHealthCheck instance.
+		mhc.Spec.NodeStartupTimeout = &metav1.Duration{Duration: time.Second}
+
+		g.Expect(testEnv.Create(ctx, mhc)).To(Succeed())
+		// defer cleanup for all the objects that have been created
+		defer func(do ...runtime.Object) {
+			g.Expect(testEnv.Cleanup(ctx, do...)).To(Succeed())
+		}(cluster, mhc, infraTmpl, machineSet)
+
+		// Pause the MachineSet reconciler. WHY?? I SEE WHAT IS HAPPENING BUT
```
Comment (ncdc) [inline controllers/machinehealthcheck_controller_test.go:743]: This is to delay the deletion of the Machine, which the MachineSet controller does when it sees a Machine marked unhealthy by MHC.

File: controllers/machinehealthcheck_controller_test.go [hunk 27]
```diff
@@ -1460,3 +1370,235 @@ func ownerReferenceForCluster(ctx context.Context, c *clusterv1.Cluster) metav1.
...
+		ObjectMeta: metav1.ObjectMeta{
+			GenerateName: "test-cluster-",
+			Namespace:    ns.Name,
+		},
+	}
+	g.Expect(testEnv.Create(ctx, cluster)).To(Succeed())
+	g.Eventually(func() error {
+		var cl clusterv1.Cluster
+		return testEnv.Get(ctx, util.ObjectKey(cluster), &cl)
+	}, timeout, time.Second).Should(Succeed())
```
Comment (ncdc) [inline controllers/machinehealthcheck_controller_test.go:1390]: Can we poll more frequently than once per second?

File: controllers/machinehealthcheck_controller_test.go [hunk 28]
```diff
@@ -46,906 +45,847 @@ import (
...
-					}
-					return mhc.GetLabels()
+		g.Eventually(func() []metav1.OwnerReference {
+			err := testEnv.Get(ctx, util.ObjectKey(mhc), mhc)
+			if err != nil {
+				fmt.Printf("error cannot retrieve mhc in ctx: %v", err)
+				return nil
+			}
+			return mhc.GetOwnerReferences()
+		}, timeout, time.Second).Should(And(
```
Comment (ncdc) [inline controllers/machinehealthcheck_controller_test.go:143]: Increase poll frequency?

File: controllers/machinehealthcheck_controller_test.go [hunk 29]
```diff
@@ -46,906 +45,847 @@ import (
...
+			g.Expect(testEnv.Cleanup(ctx, do...)).To(Succeed())
+		}(cluster, mhc)
+
+		g.Eventually(func() []metav1.OwnerReference {
+			err := testEnv.Get(ctx, util.ObjectKey(mhc), mhc)
+			if err != nil {
+				return nil
+			}
+			return mhc.GetOwnerReferences()
+		}, timeout, time.Second).Should(And(
```
Comment (ncdc) [inline controllers/machinehealthcheck_controller_test.go:170]: Increase poll frequency?

File: controllers/machinehealthcheck_controller_test.go [hunk 30]
```diff
@@ -46,906 +45,847 @@ import (
...
+		// Make sure the MHC status matches. We have two healthy machines and
+		// one unhealthy.
+		g.Eventually(func() *clusterv1.MachineHealthCheckStatus {
+			err := testEnv.Get(ctx, util.ObjectKey(mhc), mhc)
+			if err != nil {
+				fmt.Printf("error retrieving mhc: %v", err)
+				return nil
+			}
+			return &mhc.Status
+		}, timeout, time.Second).Should(MatchMachineHealthCheckStatus(&clusterv1.MachineHealthCheckStatus{
```
Comment (ncdc) [inline controllers/machinehealthcheck_controller_test.go:440]: Increase poll frequency? (Will stop commenting, but same comment applies to all one-second frequencies).

File: controllers/machinehealthcheck_controller_test.go (hunk 26 above)
Comment (wfernandes) [reply controllers/machinehealthcheck_controller_test.go:800]: Whoa! Thought I removed all of my ranting comments. Thanks for catching this. 😬

**Comment by wfernandes** [comment]
@ncdc Thanks for the review! I reduced the polling times to `100ms` and updated some of the comments.
As per our discussion, I also changed the function signature of `createMachinesWithNodes` to include optional function arguments to make it more readable.

File: controllers/machinehealthcheck_controller_test.go [hunk 31]
```diff
@@ -46,906 +45,911 @@ import (
...
-			delete(machineSet.Annotations, clusterv1.PausedAnnotation)
-			Expect(testEnv.Patch(ctx, machineSet, machineSetPatch)).To(Succeed())
-
-			// Make sure the Machine gets deleted.
-			Eventually(func() bool {
-				machine := unhealthyMachine.DeepCopy()
-				err := testEnv.Get(ctx, util.ObjectKey(unhealthyMachine), machine)
-				return apierrors.IsNotFound(err) || !machine.DeletionTimestamp.IsZero()
+			return len(machines.Items)
+		}, timeout, 100*time.Millisecond).Should(Equal(1))
```
Comment (wfernandes) [inline controllers/machinehealthcheck_controller_test.go:789]: So I just noticed this as I was reviewing another PR. 
I'm guessing either the comment for this block is incorrect or the logic inside the eventually is incorrect and needs to match something similar to line 684.

@ncdc or anyone confirm this?

Comment (ncdc) [reply controllers/machinehealthcheck_controller_test.go:789]: I believe the comment on 779 should be reworded to say we're waiting to make sure the MachineSet controller has created the required Machine from the MachineSet.

I think you can also copy the block from L684 to just before the block at L826

**Review by vincepri — APPROVED** [review]
/approve
/milestone v0.3.10
