### PR TITLE
:bug: Cluster FailureDomains should always be fully synced rather than additive

### LINKED ISSUE #5478: cluster status does not remove old failuredomains from status
**What steps did you take and what happened:**

Seen this with capi + capv
if we remove failure domain from infracluster vspherecluster drop the fields from status
but even after reconcile capi still retains the deleted fields in status.FailureDomains

###### capv before
```bash
 failureDomains:
  Cluster3:
    controlPlane: true
  vSAN Cluster:
    controlPlane: true
```

###### capi before
``` bash 
 failureDomains:
  Cluster3:
    controlPlane: true
  vSAN Cluster:
    controlPlane: true
```

###### capv after
``` bash
 failureDomains:
  cluster3-cp:
    controlPlane: true
  vsan-cluster-cp:
    controlPlane: true
```

###### capi after
``` bash
 failureDomains:
  Cluster3:
    controlPlane: true
  cluster3-cp:
    controlPlane: true
  vsan-cluster-cp:
    controlPlane: true
  vSAN Cluster:
    controlPlane: true
```

**What did you expect to happen:**

After failuredomains have been from infrastructure cluster I would expect capi to remove the failuredomains from
capi cluster and readjust the controlplane placement

**Anything else you would like to add:**

here is a handy snippet for utils_test.go
``` go
func TestUnstructuredUnmarshalField(t *testing.T) {
	g := NewWithT(t)

	mockInfraCluster := &unstructured.Unstructured{
		Object: map[string]interface{}{
			"status": map[string]interface{}{
				"failureDomains": clusterv1.FailureDomains{
					"az1": clusterv1.FailureDomainSpec{
						ControlPlane: true,
						Attributes: map[string]string{
							"a": "b",
						},
					},
				},
			},
		},
	}

	fd := clusterv1.FailureDomains{}

	err := UnstructuredUnmarshalField(mockInfraCluster, &fd, "status", "failureDomains")
	g.Expect(err).ToNot(HaveOccurred())
	g.Expect(fd["az1"]).ToNot(BeNil())

	mockInfraCluster = &unstructured.Unstructured{
		Object: map[string]interface{}{
			"status": map[string]interface{}{
				"failureDomains": clusterv1.FailureDomains{
					"az2": clusterv1.FailureDomainSpec{
						ControlPlane: true,
						Attributes: map[string]string{
							"a": "b",
						},
					},
					"az3": clusterv1.FailureDomainSpec{
						ControlPlane: true,
						Attributes: map[string]string{
							"a": "b",
						},
					},
				},
			},
		},
	}
	err = UnstructuredUnmarshalField(mockInfraCluster, &fd, "status", "failureDomains")
	g.Expect(err).ToNot(HaveOccurred())
	g.Expect(fd["az1"]).To(BeNil())
}
```
**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by sadysnaat**
**What this PR does / why we need it**:
reset cluster failuredomain before syncing from infrastructure cluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5478

### CODE REVIEW

File: controllers/cluster_controller_phases.go [hunk 1]
```diff
@@ -188,11 +188,14 @@ func (r *ClusterReconciler) reconcileInfrastructure(ctx context.Context, cluster
 	}
 
 	// Get and parse Status.FailureDomains from the infrastructure provider.
-	if err := util.UnstructuredUnmarshalField(infraConfig, &cluster.Status.FailureDomains, "status", "failureDomains"); err != nil && err != util.ErrUnstructuredFieldNotFound {
+	failureDomains := clusterv1.FailureDomains{}
```
[the remark this answers is not in the document]
Comment (vincepri) [reply controllers/cluster_controller_phases.go:191]: Thanks @sadysnaat! Can you fix the linter errors? After that we should be good to go

**Review by vincepri — COMMENTED** [review]
/retitle :bug: Cluster FailureDomains should always be fully synced rather than additive

**Comment by sadysnaat** [comment]
@vincepri fixed lint errors

File: controllers/cluster_controller_phases_test.go [hunk 2]
```diff
@@ -370,3 +370,186 @@ func TestClusterReconciler_reconcilePhase(t *testing.T) {
 		})
 	}
 }
+
+func TestClusterReconcilePhases_reconcileFailureDomains(t *testing.T) {
+	t.Run("reconcile infrastructure failure domain", func(t *testing.T) {
```
Comment (enxebre) [inline controllers/cluster_controller_phases_test.go:375]: Any particular reason to wrap the whole test under this `t.Run`?

Comment (sadysnaat) [reply controllers/cluster_controller_phases_test.go]: Ack removed

File: controllers/cluster_controller_phases_test.go [hunk 3]
```diff
@@ -370,3 +370,184 @@ func TestClusterReconciler_reconcilePhase(t *testing.T) {
...
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			g := NewWithT(t)
+
+			var c client.Client
+			if tt.infraRef != nil {
+				infraConfig := &unstructured.Unstructured{Object: tt.infraRef}
+				c = fake.NewClientBuilder().
```
Comment (enxebre) [inline controllers/cluster_controller_phases_test.go:536]: how about:
```
			objs := []client.Object{builder.GenericInfrastructureMachineCRD.DeepCopy(), tt.cluster}
			if tt.infraRef != nil {
				objs = append(objs, &unstructured.Unstructured{Object: tt.infraRef})
			}
			
			r := &ClusterReconciler{
				Client: fake.NewClientBuilder().WithObjects(objs...).Build(),,
			}
```

File: controllers/cluster_controller_phases_test.go [hunk 4]
```diff
@@ -370,3 +370,184 @@ func TestClusterReconciler_reconcilePhase(t *testing.T) {
...
+				"attribute2": "value2",
+			},
+		},
+	}
+
+	clusterWithnewFailureDomainDifferentAttributes := cluster.DeepCopy()
+	clusterWithnewFailureDomainDifferentAttributes.Status.FailureDomains = newFailureDomainUpdated
+
+	oldFailureDomain := clusterv1.FailureDomains{
+		"domainold": clusterv1.FailureDomainSpec{
```
Comment (enxebre) [inline controllers/cluster_controller_phases_test.go:418]: nit: consistently with the above ("newdomain") this should be "olddomain"

File: controllers/cluster_controller_phases_test.go [hunk 5]
```diff
@@ -370,3 +370,184 @@ func TestClusterReconciler_reconcilePhase(t *testing.T) {
...
+
+	newFailureDomainUpdated := clusterv1.FailureDomains{
+		"newdomain": clusterv1.FailureDomainSpec{
+			ControlPlane: false,
+			Attributes: map[string]string{
+				"attribute2": "value2",
+			},
+		},
+	}
+
```
Comment (enxebre) [inline controllers/cluster_controller_phases_test.go:413]: `clusterWithnewFailureDomainDifferentAttributes` does not satisfy camel case convention `Withnew`.

Also can we maybe be consistent with the variable naming e.g `clusterWithNewFailureDomainUpdated`

**Comment by enxebre** [comment]
Thanks @sadysnaat dropped some minor comments for readability, otherwise lgtm.

File: controllers/cluster_controller_phases_test.go (hunk 3 above)
Comment (sadysnaat) [reply controllers/cluster_controller_phases_test.go]: Ack

File: controllers/cluster_controller_phases_test.go (hunk 4 above)
Comment (sadysnaat) [reply controllers/cluster_controller_phases_test.go]: Ack

File: controllers/cluster_controller_phases_test.go (hunk 5 above)
Comment (sadysnaat) [reply controllers/cluster_controller_phases_test.go:413]: Ack

Comment (enxebre) [reply controllers/cluster_controller_phases_test.go:413]: can we change the cluster variable name (or the failuredomain variable name) to be consistent with the others and the failure domain they use?  i.e clusterWithNewFailureDomainUpdated

Comment (sadysnaat) [reply controllers/cluster_controller_phases_test.go:413]: Ack

File: controllers/cluster_controller_phases_test.go [hunk 6]
```diff
@@ -370,3 +370,178 @@ func TestClusterReconciler_reconcilePhase(t *testing.T) {
...
+		expectFailureDomains clusterv1.FailureDomains
+	}{
+		{
+			name:    "expect no failure domain if infrastructure ref is nil",
+			cluster: &clusterv1.Cluster{ObjectMeta: metav1.ObjectMeta{Name: "test-cluster", Namespace: "test-namespace"}},
+		},
+		{
+			name:    "expect no failure domain if infra config does not have failure domain",
+			cluster: cluster,
+			infraRef: map[string]interface{}{
```
Comment (enxebre) [inline controllers/cluster_controller_phases_test.go:442]: as a follow up consider to have a helper for building these unstructured infraRefs.

**Comment by enxebre** [comment]
/approve
PTAL @vincepri

File: controllers/cluster_controller_phases_test.go (hunk 6 above)
Comment (sadysnaat) [reply controllers/cluster_controller_phases_test.go]: Ack 

@enxebre  initial lint failures were due to 

https://github.com/kubernetes-sigs/cluster-api/pull/5656

fixed in this PR as well

Comment (sadysnaat) [reply controllers/cluster_controller_phases_test.go]: Removed the lint fix as pr is merged
