### PR TITLE
🐛 topology controller should avoid unnecessary rollouts during upgrades

### LINKED ISSUE #8656: ClusterClass: Avoid unnecessary rollouts when reconciling topology
**Detailed Description:**

When dealing with Kubernetes version upgrades across all the machines in a Cluster, the system is expected to enforce a sequence of operations: first the control plane Machines and then worker Machines. 

This is implemented by holding back/deferring the change of the Kubernetes version in MachineDeployments until the CP upgrade completes (and then following the order of MD).

However, when there are additional concurrent changes in addition to the Kubernetes version change (e.g change to the failureDomain or replicas fields), they are currently reconciled immediately, in an attempt to move the system to the desired state as fast as possible.

However, this leads to Machines being rolled out twice: one rollout for the initial set of changes, one for the Kubernetes version upgrade as soon as it is allowed, and this is perceived as a bug as users expect the system to minimise the number of Machine rollouts which ultimately leads to improved stability of users’ workloads.

This issue is about fixing the topology controller so both the concurrent changes and the Kubernetes version change will happen at the same time (both are deferred).

Note: changes which are not concurrent to a Kubernetes version change will continue to be applied immediately as of today.

/kind bug
/area topology

### LINKED ISSUE #8695: When `BeforeClusterUpgrade` is blocking an upgrade new MachineDeployments are being created with new version
### What steps did you take and what happened?

Steps to reproduce:
- Setup a RuntimeExtension that returns a blocking response for the `BeforeClusterUpgrade` hook
- Create a new clusterclass based cluster at version v1.25.3
- Edit the cluster and upgrade the version to v1.26.2 and add a new MachineDeployment
- New MD is created with the version v1.26.2

### What did you expect to happen?

The MachineDeployment should not be created with version v1.26.2 since the upgrade is blocked by the runtime extension.

### Cluster API version

main

### Kubernetes version

_No response_

### Anything else you would like to add?

Since none of the other components of the cluster have picked up the new version (v1.26.2), specifically since the ControlPlane has not yet picked up the new version it looks unsafe to allow creating new MachineDeployments to be created with the new version.

### Label(s) to be applied

/kind bug
/area clusterclass
/area topology
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

This PR modified the topology controller so that it modified pushing any changes to ControlPlane/MachineDeployment if it is pending an upgrade.

If a ControlPlane or MD is pending an upgrade it implies that it will be rollouts after it picks up the upgrade. Therefore it is better to hold out other changes, potentially causing rollouts, to these objects as well in the mean time to avoid unnecessary machine churn.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8656
Fixes #8695

### CODE REVIEW

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 1]
```diff
@@ -307,6 +307,18 @@ func (r *Reconciler) reconcileInfrastructureCluster(ctx context.Context, s *scop
 // reconcileControlPlane works to bring the current state of a managed topology in line with the desired state. This involves
 // updating the cluster where needed.
 func (r *Reconciler) reconcileControlPlane(ctx context.Context, s *scope.Scope) error {
+	// If the ControlPlane has defined a current or desired MachineHealthCheck attempt to reconcile it.
+	if s.Desired.ControlPlane.MachineHealthCheck != nil || s.Current.ControlPlane.MachineHealthCheck != nil {
+		// Reconcile the current and desired state of the MachineHealthCheck.
+		if err := r.reconcileMachineHealthCheck(ctx, s.Current.ControlPlane.MachineHealthCheck, s.Desired.ControlPlane.MachineHealthCheck); err != nil {
+			return err
+		}
+	}
```
Comment (ykakarap) [inline internal/controllers/topology/cluster/reconcile_state.go:316]: Refactored to not block MHC reconciliation if the control plane is pending an upgrade.

(Same for MD)

**Review by killianmuldoon — COMMENTED** [review]
/area clusterclass

File: internal/controllers/topology/cluster/conditions.go [hunk 2]
```diff
@@ -103,10 +103,10 @@ func (r *Reconciler) reconcileTopologyReconciledCondition(s *scope.Scope, cluste
 
 		switch {
 		case s.UpgradeTracker.ControlPlane.PendingUpgrade:
-			fmt.Fprintf(msgBuilder, "Control plane upgrade to %s on hold.", s.Blueprint.Topology.Version)
+			fmt.Fprintf(msgBuilder, "Control plane update to version %s changes on hold.", s.Blueprint.Topology.Version)
```
[the remark this answers is not in the document]
Comment (sbueringer) [reply internal/controllers/topology/cluster/conditions.go:106]: Same for MD. Isn't it also the same for deferred upgrade?

**Review by sbueringer — COMMENTED** [review]
Hm. I wonder if it would be better to define "upgrade is hold back" independent of the pending stuff.
Or we have to re-evaluate what pending exactly means and align to what we need.

In my opinion holding back and upgrade simply means:
* For control plane: Cluster.topology.version != desiredCP.version
* For MD: Cluster.topology.version != desiredMD.version

Maybe it's as easy as that?

File: internal/controllers/topology/cluster/conditions.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (sbueringer) [reply internal/controllers/topology/cluster/conditions.go:106]: Can we go with my suggestion. I think it's clearer

File: internal/controllers/topology/cluster/desired_state.go [hunk 3]
```diff
@@ -758,16 +758,23 @@ func computeMachineDeployment(_ context.Context, s *scope.Scope, desiredControlP
...
+	// If creating a new machine deployment mark it as pending if the control plane is not
+	// yet stable. Creating a new MD while the control plane is upgrading is unsafe.
 	if currentMDState == nil || currentMDState.Object == nil {
-		return desiredVersion, nil
+		if s.UpgradeTracker.ControlPlane.IsStartingUpgrade ||
+			s.UpgradeTracker.ControlPlane.IsUpgrading ||
+			s.UpgradeTracker.ControlPlane.IsScaling ||
+			s.UpgradeTracker.ControlPlane.IsProvisioning {
+			// TODO(ykakarap): Here we are marking as pending upgrade so that the reconciliation of this MD does not
+			// occur and therefore not create the new MD. Find a better name.
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/desired_state.go:771]: I think it would make sense to differentiate between upgrade pending and creation pending

This way we get the exact right information in the UpgradeTracker and can also write the conditions accordingly

File: internal/controllers/topology/cluster/desired_state.go [hunk 4]
```diff
@@ -776,19 +783,20 @@ func computeMachineDeploymentVersion(s *scope.Scope, machineDeploymentTopology c
...
 	if isMachineDeploymentDeferred(s.Blueprint.Topology, machineDeploymentTopology) {
-		s.UpgradeTracker.MachineDeployments.MarkDeferredUpgrade(currentMDState.Object.Name)
-		return currentVersion, nil
+		s.UpgradeTracker.MachineDeployments.MarkDeferredUpgrade(desiredMDName)
+		s.UpgradeTracker.MachineDeployments.MarkPendingUpgrade(desiredMDName)
+		return currentVersion
 	}
 
 	// Return early if we are not allowed to upgrade the machine deployment.
 	if !s.UpgradeTracker.MachineDeployments.AllowUpgrade() {
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/desired_state.go:797]: Let's refactor AllowUpgrade.
We should just store something that AfterControlPlaneUpgrade is blocking in the tracker
and then we should have a separate check which checks for the upgrade concurrency. 

It's confusing that we mix it and I always have to look up what AllowUpgrade is doing. The name is way too generic to quickly understand what's going on.

This also allows us to not create new MachineDeployments when the AfterControlPlaneUpgrade hook blocks.

File: internal/controllers/topology/cluster/desired_state.go [hunk 5]
```diff
@@ -776,19 +783,20 @@ func computeMachineDeploymentVersion(s *scope.Scope, machineDeploymentTopology c
 	// Return early if the currentVersion is already equal to the desiredVersion
 	// no further checks required.
 	if currentVersion == desiredVersion {
-		return currentVersion, nil
+		return currentVersion
 	}
 
 	// Return early if the upgrade for the MachineDeployment is deferred.
 	if isMachineDeploymentDeferred(s.Blueprint.Topology, machineDeploymentTopology) {
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/desired_state.go:790]: I think the idea was that we also block new MD creations if the upgrade is deferred

I might be misremembering though. let's talk about it again

File: internal/controllers/topology/cluster/desired_state.go [hunk 6]
```diff
@@ -797,65 +805,49 @@ func computeMachineDeploymentVersion(s *scope.Scope, machineDeploymentTopology c
 	// NOTE: this case should never happen (upgrading a MachineDeployment) before creating a CP,
 	// but we are implementing this check for extra safety.
 	if s.Current.ControlPlane == nil || s.Current.ControlPlane.Object == nil {
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/desired_state.go:807]: I think we also wanted to check this case for new MDs

File: internal/controllers/topology/cluster/desired_state.go [hunk 7]
```diff
@@ -797,65 +805,49 @@ func computeMachineDeploymentVersion(s *scope.Scope, machineDeploymentTopology c
...
-	currentCPVersion, err := contract.ControlPlane().Version().Get(s.Current.ControlPlane.Object)
-	if err != nil {
-		return "", errors.Wrap(err, "failed to get version of current control plane")
-	}
-	desiredCPVersion, err := contract.ControlPlane().Version().Get(desiredControlPlaneState.Object)
-	if err != nil {
-		return "", errors.Wrap(err, "failed to get version of desired control plane")
-	}
-	if *currentCPVersion != *desiredCPVersion {
+	if s.UpgradeTracker.ControlPlane.IsStartingUpgrade {
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/desired_state.go:834]: I think it would be a good simplification to move all those cp checks into a util func like isControlPlaneStable

**Review by sbueringer — COMMENTED** [review]
Good progress :)

Let's pair a bit on it. I think we have some good ideas on how we can optimize this further

**Review by sbueringer — COMMENTED** [review]
Good progress :)

Let's pair a bit on it. I think we have some good ideas on how we can optimize this further

Let's rebase on top of https://github.com/kubernetes-sigs/cluster-api/pull/8658

File: internal/controllers/topology/cluster/conditions.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (ykakarap) [reply internal/controllers/topology/cluster/conditions.go:106]: Missed this accidentally. Will change it.

[the remark this answers is not in the document]
Comment (sbueringer) [reply internal/controllers/topology/cluster/conditions.go:106]: I assumed something like that :)

[the remark this answers is not in the document]
Comment (fabriziopandini) [reply internal/controllers/topology/cluster/conditions.go:106]: nit, if this is something more than a temporary debug line, let's use log.

File: internal/controllers/topology/cluster/scope/upgradetracker.go [hunk 8]
```diff
@@ -181,3 +192,9 @@ func (m *MachineDeploymentUpgradeTracker) DeferredUpgradeNames() []string {
 func (m *MachineDeploymentUpgradeTracker) DeferredUpgrade() bool {
 	return len(m.deferredNames) != 0
 }
+
+// HoldReconcile returns true if the MachineDeployment reconciliation needs to be held back.
+// Example: MachineDeployment reconciliation needs to be held back if it is pending an upgrade.
+func (m *MachineDeploymentUpgradeTracker) HoldReconcile(name string) bool {
+	return m.pendingNames.Has(name)
```
Comment (fabriziopandini) [inline internal/controllers/topology/cluster/scope/upgradetracker.go:199]: q: should this be
```suggestion
	return m.pendingUpgradeNames.Has(name)
```

**Review by fabriziopandini — COMMENTED** [review]
made a first pass while the PR is still WIP, and it looks already good
just a couple of nits from my side

File: internal/controllers/topology/cluster/conditions.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (ykakarap) [reply internal/controllers/topology/cluster/conditions.go]: This does not log anything to stdout. This is for building the message for the `TopologyReconciled` condition.

File: internal/controllers/topology/cluster/scope/upgradetracker.go (hunk 8 above)
Comment (ykakarap) [reply internal/controllers/topology/cluster/scope/upgradetracker.go]: This is from old code of the PR. `HoldReconcile` is dropped in the updated version of the PR.

File: internal/controllers/topology/cluster/desired_state.go [hunk 9]
```diff
@@ -772,86 +771,72 @@ func computeMachineDeploymentVersion(s *scope.Scope, machineDeploymentTopology c
...
+	if s.UpgradeTracker.ControlPlane.IsUpgrading {
+		return false
 	}
 
 	// If control plane supports replicas, check if the control plane is in the middle of a scale operation.
-	// If the current control plane is scaling, then do not pick up the desiredVersion yet.
-	// Return the current version of the machine deployment. We will pick up the new version after the control
-	// plane is stable.
+	// If the current control plane is scaling then it is not considered stable.
 	if s.Blueprint.Topology.ControlPlane.Replicas != nil {
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/desired_state.go:819]:
```suggestion
```
nit: I think we can drop this here. This check is part of the earlier calculation if the CP is scaling or not. We don't have to consider it (aka "calculate") here again

(+ update/simplify godoc)

File: internal/controllers/topology/cluster/desired_state_test.go [hunk 10]
```diff
@@ -1718,75 +1712,53 @@ func TestComputeMachineDeployment(t *testing.T) {
...
+			controlPlaneScaling: true,
+			machineDeploymentTopology: clusterv1.MachineDeploymentTopology{
+				Name: "md-topology-1",
+			},
+			topologyVersion:     "v1.2.3",
+			expectedVersion:     "v1.2.3",
+			expectPendingCreate: true,
+		},
+		{
+			name: "should return cluster.spec.topology.version if creating a new machine deployment and if control plane is stable - not marked as pending create",
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/desired_state_test.go:1755]: I'm not sure if I understand how this and the first case make sense. Is one of the test cases incorrectly set up?

(wondering how we can create a MD without a machineDeploymentTopology)

File: internal/controllers/topology/cluster/reconcile_state.go [hunk 11]
```diff
@@ -482,9 +473,23 @@ func (r *Reconciler) reconcileMachineDeployments(ctx context.Context, s *scope.S
...
-	log := tlog.LoggerFrom(ctx).WithMachineDeployment(md.Object)
+func (r *Reconciler) createMachineDeployment(ctx context.Context, s *scope.Scope, md *scope.MachineDeploymentState) error {
+	// Do not create the MachineDeployment if it is marked as pending create.
+	// This will also block MHC creation because creating the MHC without the corresponding
+	// MachineDeployment is unnecessary.
+	mdTopologyName, ok := md.Object.Labels[clusterv1.ClusterTopologyMachineDeploymentNameLabel]
+	if !ok || mdTopologyName == "" {
+		// Note: This is only an additional safety check and should not happen. The label will always be added when computing
+		// the desired MachineDeployment.
+		return fmt.Errorf("new MachineDeployment is missing the %q label", clusterv1.ClusterTopologyMachineDeploymentNameLabel)
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state.go:484]:
```suggestion
		return errors.Errorf("new MachineDeployment is missing the %q label", clusterv1.ClusterTopologyMachineDeploymentNameLabel)
```
nit

File: internal/controllers/topology/cluster/reconcile_state_test.go [hunk 12]
```diff
@@ -669,13 +629,13 @@ func TestReconcile_callAfterClusterUpgrade(t *testing.T) {
...
-						Object: controlPlaneStableAtLowerVersion,
+						Object: controlPlaneObj,
 					},
 				},
 				HookResponseTracker: scope.NewHookResponseTracker(),
 				UpgradeTracker: func() *scope.UpgradeTracker {
 					ut := scope.NewUpgradeTracker()
-					ut.ControlPlane.PendingUpgrade = true
+					ut.ControlPlane.IsPendingUpgrade = true
 					return ut
```
Comment (sbueringer) [inline internal/controllers/topology/cluster/reconcile_state_test.go:639]: Please check if it makes sense to add a IsStartingUpgrade case

**Review by sbueringer — COMMENTED** [review]
Only nits, looks great!

File: internal/controllers/topology/cluster/desired_state_test.go [hunk 13]
```diff
@@ -1167,9 +1167,6 @@ func TestComputeControlPlaneVersion(t *testing.T) {
 				g.Expect(fakeRuntimeClient.CallAllCount(runtimehooksv1.AfterControlPlaneUpgrade) == 1).To(Equal(tt.wantHookToBeCalled))
 				g.Expect(hooks.IsPending(runtimehooksv1.AfterControlPlaneUpgrade, tt.s.Current.Cluster)).To(Equal(tt.wantIntentToCall))
 				g.Expect(err != nil).To(Equal(tt.wantErr))
-				if tt.wantHookToBeCalled && !tt.wantErr {
```
[the remark this answers is not in the document]
Comment (ykakarap) [reply internal/controllers/topology/cluster/desired_state_test.go:1170]: Good idea!

File: internal/controllers/topology/cluster/desired_state_test.go [hunk 14]
```diff
@@ -1718,75 +1712,53 @@ func TestComputeMachineDeployment(t *testing.T) {
...
-		currentControlPlane           *unstructured.Unstructured
-		desiredControlPlane           *unstructured.Unstructured
-		topologyVersion               string
-		expectedVersion               string
+		name                                 string
+		machineDeploymentTopology            clusterv1.MachineDeploymentTopology
+		currentMachineDeploymentState        *scope.MachineDeploymentState
+		upgradingMachineDeployments          []string
+		upgradeConcurrency                   int
+		controlPlaneStartingUpgrade          bool
```
[the remark this answers is not in the document]
Comment (ykakarap) [reply internal/controllers/topology/cluster/desired_state_test.go:1727]: We dont need this for the current tests because `controlPlanePendingUpgrade` is essentially covered by all other cases. `IsPendingUpgrade` is basically a result of all other checks combined and since in these tests we have all the individual checks they are already extensively covering all the cases.

File: internal/controllers/topology/cluster/desired_state_test.go (hunk 10 above)
Comment (ykakarap) [reply internal/controllers/topology/cluster/desired_state_test.go:1755]: Good catch! The first case was incorrectly setup and the second one is correctly setup. The first case still passed because md topology name in the first case would be `""` and since `expectPendingCreate: false` in the first case we are checking that `""` does not exist in the pending create set (verify it should not be marked as pending create) which it wont.

Does this answer your question?

File: internal/controllers/topology/cluster/reconcile_state.go (hunk 11 above)
Comment (ykakarap) [reply internal/controllers/topology/cluster/reconcile_state.go:484]: Fixed this. 
In the future should we always use `errors.Errorf` over `fmt.Errorf`? Is it for consistency or is there anther reasons too? (consistency is a good enough reason just curious to know if there is more to this)

File: internal/controllers/topology/cluster/reconcile_state_test.go (hunk 12 above)
Comment (ykakarap) [reply internal/controllers/topology/cluster/reconcile_state_test.go:639]: Thinking about it, it could be a valid case. It could be possible that a second upgrade was triggered right when the cluster finished the second upgrade. In that case the reconciler will pick the new upgrade (IsStratingUpgrade) and we should not call the AfterClusterUpgrade hook. 

This case is already covered in our the code, +1 to adding a test case for this as well.

File: internal/controllers/topology/cluster/desired_state_test.go (hunk 10 above)
Comment (sbueringer) [reply internal/controllers/topology/cluster/desired_state_test.go:1764]: Yup. Looks like we now have 2 identical test cases?

**Comment by sbueringer** [comment]
Thx, last nit from my side: https://github.com/kubernetes-sigs/cluster-api/pull/8628#discussion_r1214076931

File: internal/controllers/topology/cluster/desired_state_test.go (hunk 10 above)
Comment (ykakarap) [reply internal/controllers/topology/cluster/desired_state_test.go:1764]: They are not identical. In one case the control plane is stable so `expectPendingCreate` is `false` and in the second case the control plane is scaling (not stable) so `expectPendingCreate`  is `true`.

Comment (sbueringer) [reply internal/controllers/topology/cluster/desired_state_test.go:1764]: Not those 2. Those:
```go
		{
			name:                          "should return cluster.spec.topology.version if creating a new machine deployment and if control plane is stable",
			currentMachineDeploymentState: nil,
			machineDeploymentTopology: clusterv1.MachineDeploymentTopology{
				Name: "md-topology-1",
			},
			topologyVersion:     "v1.2.3",
			expectedVersion:     "v1.2.3",
			expectPendingCreate: false,
		},
```

```
		{
			name: "should return cluster.spec.topology.version if creating a new machine deployment and if control plane is stable - not marked as pending create",
			machineDeploymentTopology: clusterv1.MachineDeploymentTopology{
				Name: "md-topology-1",
			},
			topologyVersion:     "v1.2.3",
			expectedVersion:     "v1.2.3",
			expectPendingCreate: false,
		},
```

**Comment by fabriziopandini** [comment]
pending latest comment from @sbueringer, lgtm from my side

File: internal/controllers/topology/cluster/desired_state_test.go (hunk 10 above)
Comment (ykakarap) [reply internal/controllers/topology/cluster/desired_state_test.go]: Ah!  you are right.

**Comment by sbueringer** [comment]
Thank you!

/lgtm
/approve


Let's hold until we have some idea what's going on regarding #8786 (just to keep debugging as easy as possible. This PR could introduce another potential error source)

**Comment by sbueringer** [comment]
Updated the status of https://github.com/kubernetes-sigs/cluster-api/issues/8786#issuecomment-1584332219. I think we're good with merging this PR. The issue is something in KCP. So unrelated to this PR

/hold cancel
