### PR TITLE
✨ Add defaulting webhook for KubeadmConfig

### LINKED ISSUE #1770: [cabpk] Etcd data directory shouldn't be required
/kind bug

**What steps did you take and what happened:**
The following `KubeadmConfig` resource illustrates using a custom image repository for a local etcd configuration. Please note only the relevant fields are shown below:

```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
spec:
  clusterConfiguration:
    etcd:
      local:
        imageRepository: my.custom.repo.io
        imageTag: v0.0.0
```

However, when submitting this resource via `kubectl`, the following error occurs:

```shell
$ kubectl apply -f kubeadmconfig.yaml
error: error validating "kubeadmconfig.yaml": error validating data: ValidationError(KubeadmConfig.spec.clusterConfiguration.etcd.local): missing required field "dataDir" in io.x-k8s.cluster.bootstrap.v1alpha2.KubeadmConfig.spec.clusterConfiguration.etcd.local; if you choose to ignore these errors, turn validation off with --validate=false
```

Disabling validation and submitting the same resource to the API server results in a long-form error with the same root cause -- the etcd field `dataDir` is required.

I encountered this last week and used a work-around of just setting `dataDir` to its default value. However, @figo recently encountered the same issue, so I decided to track down why this was happening as it seems like it shouldn't. Here's what I discovered:

* It looks like kubeadm API types have been copied into the kubeadm bootstrapper rather than have kustomize point to an external repository for the kubeadm CRDs.
* Taking a look at [the `etcd` type](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/7b907ab78b8c28d62382e9f52148a72543de3cef/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml#L187-L258), the `dataDir` is in fact [**required**](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/7b907ab78b8c28d62382e9f52148a72543de3cef/config/crd/bases/bootstrap.cluster.x-k8s.io_kubeadmconfigs.yaml#L255-L256).
* Then it hit me -- when run as part of kubeadm, [the provided configuration is processed](https://github.com/kubernetes/kubernetes/blob/5e4abfb94613339d585e5d811e4fcec278ff06dc/cmd/kubeadm/app/cmd/init.go#L283-L288) to ensure proper defaults are in place.
* That’s why the field `dataDir` may be marked as required and still have documentation that states:

    > DataDir is the directory etcd will place its data. Defaults to “/var/lib/etcd”.

* When empty and run as part of kubeadm, the field is defaulted to `/var/lib/etcd`
* However, since the API server prior to 1.15 did not support defaulters except via webhooks, submitting a config with an `etcd` configuration and an empty `dataDir` field would result in a validation error.

My suggestion is this: as long as the bootstrapper is using copied kubeadm types anyway, why not add an `+optional` and `omitempty`. For example, take the following [`LocalEtcd` structure](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/7b907ab78b8c28d62382e9f52148a72543de3cef/kubeadm/v1beta2/types.go#L261-L278):

```golang
// LocalEtcd describes that kubeadm should run an etcd cluster locally
type LocalEtcd struct {
	// ImageMeta allows to customize the container used for etcd
	ImageMeta `json:",inline"`

	// DataDir is the directory etcd will place its data.
	// Defaults to "/var/lib/etcd".
	DataDir string `json:"dataDir"`

	// ExtraArgs are extra arguments provided to the etcd binary
	// when run inside a static pod.
	ExtraArgs map[string]string `json:"extraArgs,omitempty"`

	// ServerCertSANs sets extra Subject Alternative Names for the etcd server signing cert.
	ServerCertSANs []string `json:"serverCertSANs,omitempty"`
	// PeerCertSANs sets extra Subject Alternative Names for the etcd peer signing cert.
	PeerCertSANs []string `json:"peerCertSANs,omitempty"`
}
```

The `DataDir` field could be updated to:

```golang
	// DataDir is the directory etcd will place its data.
	// Defaults to "/var/lib/etcd".
	// +optional
	DataDir string `json:"dataDir,omitempty"`
```

Then, the kubeadm controller would ensure that the documented default value `/var/lib/etcd` would still be applied to any `KubeadmConfig` resources that includes `spec.clusterConfiguration.etcd.local` and an empty `dataDir` field. This change would allow specifying a custom etcd image repoository or version without having to worry about the unrelated data directory.

**What did you expect to happen:**
The resource should have been accepted with an omitted `etcd.dataDir` since the documentation states the field has a default value of `/var/lib/etcd`.

cc @chuckha @ncdc @figo

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
This PR adds a defaulting web hook for the KubeadmConfig. It also sets a default that Kubeadm would expect.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1770

/cc @akutz

### CODE REVIEW

**Comment by ncdc** [comment]
Sweet! I bet you could add a unit test in kubeadmbootstrapconfig_types_test.go for this too, to check the defaulting, right?

**Comment by ncdc** [comment]
Or maybe not, if that doesn't deploy usable webhooks/certs

**Comment by chuckha** [comment]
@ncdc I can add a unit test. I wouldn't unit test the web hook though I'd just call `.Default` on the `KubeadmConfig` type

File: bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_webhook.go [hunk 1]
```diff
@@ -18,10 +18,29 @@ package v1alpha3
...
 	return ctrl.NewWebhookManagedBy(mgr).
-		For(r).
+		For(k).
 		Complete()
 }
+
+func (k *KubeadmConfig) Default() {
+	if k.Spec.ClusterConfiguration != nil {
+		if k.Spec.ClusterConfiguration.Etcd.Local != nil {
+			if k.Spec.ClusterConfiguration.Etcd.Local.DataDir == "" {
```
Comment (vincepri) [inline bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_webhook.go]: Doesn't kubeadm already do this?  https://github.com/kubernetes-sigs/cluster-api/blob/master/bootstrap/kubeadm/types/v1beta1/types.go#L279

The webhook is fine, but we should probably change the type to add optional and omitempty instead?

Comment (chuckha) [reply bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_webhook.go]: I will add omitempty. And yep, kubeadm will default it for you. The only benefit of doing it here is that the default value will show up in the CAPI object. If we don't default here then we assume the user will know the kubeadm defaults, which seems fine since it's documented on the type. Will remove the web hook & test and reduce this to an API change

**Comment by chuckha** [comment]
/assign @vincepri 

updated!

File: bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_webhook.go (hunk 1 above)
Comment (vincepri) [reply bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_webhook.go]: Can we do the same for the other defaulted fields? Not in this PR, but I like the point you're making about observability

Comment (chuckha) [reply bootstrap/kubeadm/api/v1alpha3/kubeadmconfig_webhook.go]: Yep, I can open an issue
