### PR TITLE
🐛 Fix to enable bootstrap secret rotation if the secret itself missing

### LINKED ISSUE #6029: bootstrap tokens can expire before they can be used if the bootstrap cluster's time is sufficiently behind the workload cluster
**What steps did you take and what happened:**

1. Set the time on the bootstrap cluster 1 hour in the past.
    ```
    date -s $(date -d "1 hour ago")
    clusterctl init ...
    ```
1. Create a cluster (any cluster that uses the kubeadm bootstrap provider)

**What did you expect to happen:**

I expected the bootstrap controller to emit an error event and log entry because it cannot create a token that won't be expired before it can be used. With the expiration time in the past, Kubernetes will immediately clean it up.

**Anything else you would like to add:**

A secret, eg. `bootstrap-token-zuzhz4` is created in the workload cluster. Because the expiration time is in the past, [TokenCleaner](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/) deletes the token immediately after creation. One side-effect of this is that the `capi-kubeadm-bootstrap-controller-manager` logs will fill with lines like:

```
I0131 22:37:39.210898       1 kubeadmconfig_controller.go:285] controller/kubeadmconfig "msg"="Refreshing token until the infrastructure has a chance to consume it" "name"="cluster-ibs-ng-control-plane-vctx7" "namespace"="default" "reconciler group"="bootstrap.cluster.x-k8s.io" "reconciler kind"="KubeadmConfig" 
E0131 22:37:39.291993       1 controller.go:304] controller/kubeadmconfig "msg"="Reconciler error" "error"="failed to refresh bootstrap token: secrets \"bootstrap-token-zuzhz4\" not found" "name"="cluster-ibs-ng-control-plane-vctx7" "namespace"="default" "reconciler group"="bootstrap.cluster.x-k8s.io" "reconciler kind"="KubeadmConfig" 
```

**Environment:**

- Cluster-api version: v1.0.2
- Minikube/KIND version: kind v0.11.1
- Kubernetes version: (use `kubectl version`): 1.22.6

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by bdehri**
**What this PR does / why we need it**:

When the bootstrap token is expired and the respective secret is already cleaned up, MachinePools cannot be scaled up due to missing token.  In order to mitigate this issue, the secret can be rotated if it is missing.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6029

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
> Before reviewing the PR I would like to better understand in which case the bootstrap token for a machine poll can expire, given that we are continuously refreshing it.

I have the same question. Although the fix itself seems relatively harmless, in the worst case it's just dead code that is never reached. 

/cc @mboersma

**Comment by bdehri** [comment]
Hello @CecileRobertMichon, @fabriziopandini,

At the moment, cause of the deletion is unknown to us and we could not reproduce the issue in a reliable manner. We found that it happens some time passed after initial deployment. Until we discover the root cause, we wanted to make the code more resilient against such issues.

File: bootstrap/kubeadm/internal/controllers/token.go [hunk 1]
```diff
@@ -101,6 +102,9 @@ func refreshToken(ctx context.Context, c client.Client, token string, ttl time.D
 func shouldRotate(ctx context.Context, c client.Client, token string, ttl time.Duration) (bool, error) {
 	secret, err := getToken(ctx, c, token)
 	if err != nil {
+		if apierrors.IsNotFound(err) {
```
Comment (CecileRobertMichon) [inline bootstrap/kubeadm/internal/controllers/token.go:105]: could you please add a code comment that explains why this is needed (and that we normally don't expect to ever reach this)

**Comment by CecileRobertMichon** [comment]
@bdehri understood. In that case given

> the fix itself seems relatively harmless, in the worst case it's just dead code that is never reached

I'm okay with this fix if we add a code comment to explain why we need it

File: bootstrap/kubeadm/internal/controllers/token.go (hunk 1 above)
Comment (bdehri) [reply bootstrap/kubeadm/internal/controllers/token.go:108]: done

**Comment by fabriziopandini** [comment]
lgtm pending squash

**Comment by sbueringer** [comment]
> lgtm pending squash

@fabriziopandini Just a quick reminder (to everyone :)). We can now - if we want to - lgtm before the squash and the lgtm label will be preserved.

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
Seems to fall under "bugs without easy workarounds"

/cherry-pick release-1.3
