### PR TITLE
🐛 Change the number of expected etcd members

### LINKED ISSUE #2651: KCP: upgrade gets stuck after removing etcd member
**What happened**

When we initiated a KCP upgrade on a self-hosted ("pivoted") cluster, we observed the following sequence of events:

The KCP controller created a new machine, and it successfully joined the cluster (once we got rid of the smart quotes in the kubeadm config, but that's a different story).

At this point, the KCP logs look pretty standard:

```
E0311 21:59:52.529099       1 kubeadm_control_plane_controller.go:548] controllers/KubeadmControlPlane "msg"="waiting for control plane to pass etcd health check before removing a control plane machine" "error"="there are 3 control plane nodes, but 4 etcd members" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"
I0311 22:00:11.441365       1 kubeadm_control_plane_controller.go:269] controllers/KubeadmControlPlane "msg"="Upgrading Control Plane" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"
```

But then something surprising happened (immediately following the above statement):

```
I0311 22:00:24.199072       1 leaderelection.go:288] failed to renew lease capi-kubeadm-control-plane-system/kubeadm-control-plane-manager-leader-election-capi: failed to tryAcquireOrRenew context deadline exceeded
E0311 22:00:24.199149       1 main.go:121] setup "msg"="problem running manager" "error"="leader election lost"
```

And when the pod restarted and came back up, the 

```
I0311 22:00:43.533246       1 kubeadm_control_plane_controller.go:269] controllers/KubeadmControlPlane "msg"="Upgrading Control Plane" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"
E0311 22:00:49.132408       1 kubeadm_control_plane_controller.go:548] controllers/KubeadmControlPlane "msg"="waiting for control plane to pass etcd health check before removing a control plane machine" "error"="[there are 4 control plane nodes, but 3 etcd members, node \"ip-10-0-0-1.ec2.internal\": failed to create etcd client: unable to create etcd client: context deadline exceeded, node \"ip-10-0-0-2.ec2.internal\": failed to create etcd client: unable to create etcd client: context deadline exceeded]" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"
```

which repeats a few times for about a minute, though complaining about connection issues to different etcd members (but always `ip-10-0-0-1.ec2.internal` – the machine marked for removal). Then there's a spate of this error:

```
W0311 22:01:55.293805       1 http.go:392] Error reading backend response: unexpected EOF
W0311 22:01:55.293822       1 http.go:392] Error reading backend response: unexpected EOF
W0311 22:01:55.294615       1 http.go:392] Error reading backend response: unexpected EOF
W0311 22:01:55.294743       1 http.go:392] Error reading backend response: unexpected EOF
```

and then things settle down to consistently stuck on:

```
I0311 22:02:02.347903       1 kubeadm_control_plane_controller.go:269] controllers/KubeadmControlPlane "msg"="Upgrading Control Plane" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"
E0311 22:02:05.741965       1 kubeadm_control_plane_controller.go:548] controllers/KubeadmControlPlane "msg"="waiting for control plane to pass etcd health check before removing a control plane machine" "error"="[there are 4 control plane nodes, but 3 etcd members, node \"ip-10-0-0-1.ec2.internal\": failed to create etcd client: unable to create etcd client: context deadline exceeded]" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"
```

It looks like things got stuck between removing the etcd member and marking the member as having been removed from etcd via annotation, because once we manually added the `kubeadm.controlplane.cluster.x-k8s.io/scale-down-etcd-member-removed` the upgrade was again able to proceed. It did get stuck in the same way on the next node, but the one after that was smooth.

**Summary**

We noticed two things from this sequence of events:

1. The KCP controller is not able to recover effectively from a failure in etcd membership management (the self-hosting is pretty reliably injecting a fault into this process, but is not essential to the issue)
2. The upgrade process itself is fairly disruptive to API clients. We (the controller + the humans poking at things) observed a fair number of hung connections and refused connections during the upgrade itself

**Solutioneering**

Ideas for building some more resilience into the etcd membership process include:

- Teaching the healthcheck to ignore this condition (4 nodes, 3 members, the member that's been removed can't be communicated with) even if the machine hasn't been annotated
- Pre-marking the machine with a "about to remove" annotation before we start the etcd member removal as a declaration of intent

I'll open a separate issue around the upgrade disruptiveness for discussion on that. In this case a less disruptive upgrade process would help in that it would make failures during the removal less likely.

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
This PR allows the control plane to upgrade through an expected state where there are 4 control planes and 3 etcd members. This happens when the control plane controller dies after removing a member but not marking it as having been removed. It's one step closer to removing the annotations that manage state.

Some slightly larger changes due to fixing a stale fake etcd client that went unused in tests.

Adds a test for the particular case we are trying to fix.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2651

/cc @sethp-nr @rudoi 
/assign @vincepri

### CODE REVIEW

File: controlplane/kubeadm/internal/workload_cluster.go [hunk 1]
```diff
@@ -258,15 +263,39 @@ func (w *Workload) EtcdIsHealthy(ctx context.Context) (HealthCheckResult, error)
...
 
+func (w *Workload) etcdPods(ctx context.Context) (*corev1.PodList, error) {
+	podlist := &corev1.PodList{}
+	set, err := labels.ConvertSelectorToLabelsMap("component=etcd,tier=control-plane")
+	if err != nil {
+		return nil, err
+	}
+	err = w.Client.List(ctx, podlist, &ctrlclient.ListOptions{
+		LabelSelector: labels.SelectorFromSet(set),
+		Namespace:     "kube-system",
```
Comment (chuckha) [inline controlplane/kubeadm/internal/workload_cluster.go]: fixing

**Comment by sethp-nr** [comment]
I'm checking this out locally to test now.

**Comment by sethp-nr** [comment]
I commented out the annotation apply step to simulate the failure we experienced, and wanted to see it loop forever on re-removing the same etcd member. What I saw instead was a different health check failure:

> E0317 19:40:17.837043      39 kubeadm_control_plane_controller.go:537] controllers/KubeadmControlPlane "msg"="waiting for control plane to pass etcd health check before removing a control plane machine" "error"="node \"ip-10-0-122-121.ec2.internal\": failed to create etcd client: unable to create etcd client: context deadline exceeded" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"

That node happens to be the one that got member remove'd:

```
etcd-ip-10-0-122-121.ec2.internal                      0/1     CrashLoopBackOff   6          16m
etcd-ip-10-0-23-80.ec2.internal                        1/1     Running            0          6m29s
etcd-ip-10-0-36-60.ec2.internal                        1/1     Running            0          11m
etcd-ip-10-0-8-103.ec2.internal                        1/1     Running            0          19m
```

The good news is that it's no longer complaining about there being a mismatch in the number, though! 

How should we have the `for _, node := range controlPlaneNodes.Items {`  loop skip the remove'd member in this case?

**Comment by sethp-nr** [comment]
I'm tempted to suggest we check if the pod is ready in that loop and skip over it if not. It doesn't look like we're really waiting for etcd to be healthy again before deleting the control plane machine:


> I0317 19:37:52.065804      39 kubeadm_control_plane_controller.go:253] controllers/KubeadmControlPlane "msg"="Upgrading Control Plane" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"
E0317 19:37:57.127608      39 kubeadm_control_plane_controller.go:537] controllers/KubeadmControlPlane "msg"="waiting for control plane to pass etcd health check before removing a control plane machine" "error"="control plane machine test/test-controlplane-pq76m has no status.nodeRef" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"
I0317 19:38:07.514075      39 kubeadm_control_plane_controller.go:253] controllers/KubeadmControlPlane "msg"="Upgrading Control Plane" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"
E0317 19:38:18.326999      39 kubeadm_control_plane_controller.go:552] controllers/KubeadmControlPlane "msg"="waiting for control plane to pass control plane health check before removing a control plane machine" "error"="node \"ip-10-0-23-80.ec2.internal\": pods \"kube-apiserver-ip-10-0-23-80.ec2.internal\" not found" "cluster"="test" "kubeadmControlPlane"="test-controlplane" "namespace"="test"

It looks like a log line "Upgrading control plane" followed by "waiting for control plane to pass control plane health check before removing a control plane machine" is how the KCP reconciler spells "successfully removed an etcd member.

Also, looking more carefully now, I would expect this health check change to also remove the need for the annotation at all – it looks like we're counting on early returns from healthcheck failures to sequence the upgrade steps.

**Comment by chuckha** [comment]
> I'm tempted to suggest we check if the pod is ready in that loop and skip over it if not. It doesn't look like we're really waiting for etcd to be healthy again before deleting the control plane machine:

This was also my first instinct. just need to read a little more code to convince myself

**Comment by sethp-nr** [comment]
It makes me a little nervous in general, because I'm worried that means we'll give a pass to an etcd ring that has e.g. a single member who just got oomkilled. But hopefully we'll catch that by comparing against the `knownMemberIDSet`

**Comment by vincepri** [comment]
Reading through the code a little more, a few observations:

- The `Workload.EtcdIsHealthy` method should probably only return a HealthCheckResult without making assumption about when a node is healthy or not, this method seems more geared towards "check the health of each etcd member and report everything back".
- Callers of this method, can use the result to make their own decisions as if to proceed or not. For example, in the case of scale down, we can ignore the member currently in the process of being deleted as it was suggested above.
- The `HealthCheckResult` type can offer helper methods with pre-defined checks that callers can decide upon.

wdyt?

**Comment by chuckha** [comment]
> Reading through the code a little more, a few observations:
> 
> * The `Workload.EtcdIsHealthy` method should probably only return a HealthCheckResult without making assumption about when a node is healthy or not, this method seems more geared towards "check the health of each etcd member and report everything back".
> * Callers of this method, can use the result to make their own decisions as if to proceed or not. For example, in the case of scale down, we can ignore the member currently in the process of being deleted as it was suggested above.
> * The `HealthCheckResult` type can offer helper methods with pre-defined checks that callers can decide upon.
> 
> wdyt?

This requires more restructuring elsewhere. I think this could be a nice improvement but it's something a little more invasive than what is going on here. Want to open an issue with your thoughts on the matter?

**Comment by vincepri** [comment]
Sure yeah, let's wrap this up for now. Is there any other change that needs to happen in this PR?

**Comment by chuckha** [comment]
> Sure yeah, let's wrap this up for now. Is there any other change that needs to happen in this PR?

Yep. I'm adding a test for this and have some changes locally that need to be made.

File: controlplane/kubeadm/internal/etcd/fake/client.go [hunk 2]
```diff
@@ -18,173 +18,41 @@ package fake
```
Comment (chuckha) [inline controlplane/kubeadm/internal/etcd/fake/client.go]: This file was out of date since it was unused entirely. I updated it so I could fake etcd responses to simulate the situations necessary for the test.

**Comment by chuckha** [comment]
/test pull-cluster-api-make

o.o....compiles on my machine.....?

File: controlplane/kubeadm/internal/workload_cluster_test.go [hunk 3]
```diff
@@ -227,3 +231,88 @@ func getProxyImageInfo(ctx context.Context, client ctrlclient.Client) (string, e
...
+			list: &corev1.NodeList{
+				Items: []corev1.Node{
+					nodeNamed("test-1", withProviderID("my-provider-id-1")),
+					nodeNamed("test-2", withProviderID("my-provider-id-2")),
+					nodeNamed("test-3", withProviderID("my-provider-id-3")),
+					nodeNamed("test-4", withProviderID("my-provider-id-4")),
+				},
+			},
+		},
+		etcdClientGenerator: &fakeEtcdClientGenerator{
```
Comment (chuckha) [inline controlplane/kubeadm/internal/workload_cluster_test.go]: this isn't what i want it to look like, but i'm working with the existing structs in order to finish this up

**Comment by chuckha** [comment]
oh. issue with rebase on master, a bunch of stuff changed 🙃

**Comment by sethp-nr** [comment]
> /retest

o7

**Comment by sethp-nr** [comment]
sethp-nr test bot reports that with these two additional PRs:

- https://github.com/kubernetes-sigs/cluster-api/pull/2698
- https://github.com/kubernetes-sigs/cluster-api/pull/2700

I was able to successfully upgrade a KCP even without letting the reconciler add the "etcd member removed" annotation!

/lgtm
