### PR TITLE
🐛 Fix flaky Test_objectMover

### LINKED ISSUE #5938: Test_objectMover is flaky
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

The Test_objectMover is failing from time to time with the following error
```yaml
    mover_test.go:724: 
        Expected
            <time.Time>: 2022-01-10T22:00:03.398330287Z
        to be <
            <time.Time>: 2022-01-10T22:00:03.398330287Z
    --- FAIL: Test_objectMover_backupTargetObject/Cluster (0.03s)
```

Recent run:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1480660217195663360

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

Based on the Slack discussion (https://kubernetes.slack.com/archives/C8TSNPY4T/p1643414553424199) increasing the timeout has a chance to solve the flake. Let's try it.

Thx @Jont828 !

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5938

### CODE REVIEW

File: cmd/clusterctl/client/cluster/mover_test.go [hunk 1]
```diff
@@ -707,7 +724,7 @@ func Test_objectMover_backupTargetObject(t *testing.T) {
 				time.Sleep(time.Millisecond * 5)
```
Comment (Jont828) [inline cmd/clusterctl/client/cluster/mover_test.go:724]: @sbueringer I mentioned this in Slack too, but I was able to fix the test on my machine by changing the duration here.
```suggestion
				time.Sleep(time.Millisecond * 50)
```

Comment (sbueringer) [reply cmd/clusterctl/client/cluster/mover_test.go]: Thx. Let's just try that and then we see over the next weeks/months if the flake still occurs.

**Review by killianmuldoon — APPROVED** [review]
/lgtm

I'm not super happy that we still don't know why the timestamp wasn't changing. But let's fix the flake and leave FS timestamps to the kernel 😆
