### PR TITLE
🐛  Change delete behaviour to respect inventory

### LINKED ISSUE #5015: "clusterctl upgrade" fails during retry
**What steps did you take and what happened:**
1. Created a kind bootstrap cluster.
2. Install clusterctl v0.3.12 and run "clusterctl init" with the below configuration.
```
release:
    version: ""
providers:  
    - name: cluster-api
      type: CoreProvider
      url: https://github.com/kubernetes-sigs/cluster-api/releases/v0.3.12/core-components.yaml
    - name: kubeadm
      type: BootstrapProvider
      url: https://github.com/kubernetes-sigs/cluster-api/releases/v0.3.12/bootstrap-components.yaml
    - name: kubeadm
      type: ControlPlaneProvider
      url: https://github.com/kubernetes-sigs/cluster-api/releases/v0.3.12/control-plane-components.yaml
    - name: azure
      type: InfrastructureProvider
      url: https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/v0.4.10/infrastructure-components.yaml
```
3. Triggered upgrade and interrupted in-between
```
$clusterctl upgrade apply --management-group capi-system/cluster-api --contract v1alpha3
Checking cert-manager version...
Cert-manager is already up to date
Performing upgrade...
Deleting Provider="cluster-api" Version="v0.3.12" TargetNamespace="capi-system"
Installing Provider="cluster-api" Version="v0.3.22" TargetNamespace="capi-system"
^C
```

4. Retry upgrade is failing 
```
$clusterctl upgrade apply --management-group capi-system/cluster-api --contract v1alpha3  -v 10./clusterctl_0_3_12 upgrade apply --management-group capi-system/cluster-api --contract v1alpha3  -v 10
Using configuration File="/Users/saib/.cluster-api/clusterctl.yaml"
Checking cert-manager version...
Cert-manager is already up to datePerforming upgrade...
Error: Unable to identify management groups: provider capi-kubeadm-control-plane-system/control-plane-kubeadm 
can't be combined with any core provider
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.checkOverlappingProviders /workspace/cmd/clusterctl/client/cluster/inventory_managementgroup.go:131
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.deriveManagementGroups /workspace/cmd/clusterctl/client/cluster/inventory_managementgroup.go:72
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*inventoryClient).GetManagementGroups /workspace/cmd/clusterctl/client/cluster/inventory_managementgroup.go:153
sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*providerUpgrader).getManagementGroup /workspace/cmd/clusterctl/client/cluster/upgrader.go:207sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster.(*providerUpgrader).ApplyPlan /workspace/cmd/clusterctl/client/cluster/upgrader.go:147
sigs.k8s.io/cluster-api/cmd/clusterctl/client.(*clusterctlClient).ApplyUpgrade /workspace/cmd/clusterctl/client/upgrade.go:168
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.runUpgradeApply /workspace/cmd/clusterctl/cmd/upgrade_apply.go:96
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.glob..func12 /workspace/cmd/clusterctl/cmd/upgrade_apply.go:57
github.com/spf13/cobra.(*Command).execute /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.Execute /workspace/cmd/clusterctl/cmd/root.go:91main.main /workspace/cmd/clusterctl/main.go:25
runtime.main /usr/local/go/src/runtime/proc.go:203runtime.goexit
```
**What did you expect to happen:**
Upgrade should have gone through

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.12
- Minikube/KIND version: kind v0.9.0 go1.15.2 darwin/amd64
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by killianmuldoon**
Add an option to the delete functions in clusterctl too allow user
configuration of inventory deletion. Clusterctl no longer deletes
provider inventories during an upgrade. This reduces the chance of
an unrecoverable error during clusterctl upgrade.

Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5015

### CODE REVIEW

**Comment by killianmuldoon** [comment]
I've put this in WIP until I figure out a good way to test the actual issue encountered in #5015.

File: cmd/clusterctl/client/cluster/components_test.go [hunk 1]
```diff
@@ -17,6 +17,7 @@ limitations under the License.
 package cluster
 
 import (
+	"log"
```
Comment (killianmuldoon) [inline cmd/clusterctl/client/cluster/components_test.go:20]: debug: should be removed.

File: cmd/clusterctl/client/cluster/components_test.go [hunk 2]
```diff
@@ -205,20 +242,26 @@ func Test_providerComponents_Delete(t *testing.T) {
...
+				{object: corev1.ObjectReference{APIVersion: "clusterctl.cluster.x-k8s.io/v1alpha3", Kind: "Provider", Name: "providerOne"}, deleted: true},              // inventory should be deleted
 			},
 			wantErr: false,
 		},
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
 			g := NewWithT(t)
-
+			log.Print(tt.args.provider.Kind)
```
Comment (killianmuldoon) [inline cmd/clusterctl/client/cluster/components_test.go:253]: debug: to be removed

File: cmd/clusterctl/client/cluster/components_test.go [hunk 3]
```diff
@@ -83,6 +88,8 @@ func Test_providerComponents_Delete(t *testing.T) {
 		},
 		// CRDs (should be deleted only if includeCRD)
 		&crd,
+		// Inventory should be deleted ony if includeInventory
+		&inventory,
```
Comment (killianmuldoon) [inline cmd/clusterctl/client/cluster/components_test.go:92]: There's an ambiguity between the 'provider' set in this test and the 'inventory' that this PR actually addresses. I chose the less disruptive option here of just adding the 'Provider' type under the name inventory, and using the name inventory through the code for this PR. Should the ambiguity between the inventory provider type and the use of provider elsewhere in the code be addressed here?

Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/components_test.go:92]: what about using IncludeInventory instead of inventory?

File: cmd/clusterctl/client/cluster/upgrader.go [hunk 4]
```diff
@@ -361,6 +361,7 @@ func (u *providerUpgrader) doUpgrade(upgradePlan *UpgradePlan) error {
 			Provider:         upgradeItem.Provider,
 			IncludeNamespace: false,
 			IncludeCRDs:      false,
+			IncludeInventory: false,
```
Comment (killianmuldoon) [inline cmd/clusterctl/client/cluster/upgrader.go:364]: Add comment above with information on provider inventory being preserved.

File: cmd/clusterctl/client/cluster/components_test.go (hunk 3 above)
Comment (killianmuldoon) [reply cmd/clusterctl/client/cluster/components_test.go:92]: That's better than what I have here, but there's a broader issue that we have two types - a Go Provider type that stands in for providers in the code, and an api CRD  'Provider.clusterctl' type that serves as the inventory for clusterctl. Is this enough ambiguity to consider 1) Merging these two in the code or 2) Renaming the Provider api type to something that reflects its usage by clusterctl?

Comment (killianmuldoon) [reply cmd/clusterctl/client/cluster/components_test.go]: Updated to providerInventory for now. I think that solves the ambiguity in the test, but not in other places where this issue might come up.

File: cmd/clusterctl/client/cluster/components.go [hunk 5]
```diff
@@ -168,19 +169,30 @@ func (p *providerComponents) Delete(options DeleteOptions) error {
 			namespacesToDelete.Insert(obj.GetName())
 		}
 
+		// If the resource is part of the inventory for clusterctl don't delete it at this point as losing this information makes the
+		// upgrade function non-reentrant. Instead keep the inventory objects around until the upgrade is finished and working and
+		// delete them at the end of the upgrade flow.
+		isInventory := obj.GroupVersionKind().GroupKind().String() == providerGroupKind
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/components.go:175]: You have to check for group and kind only, given that version might change (we are not yet graduated).
Also group is defined in the clusterctl API, so you can reuse it.

File: cmd/clusterctl/client/cluster/components.go [hunk 6]
```diff
@@ -168,19 +169,30 @@ func (p *providerComponents) Delete(options DeleteOptions) error {
...
 		// This is required because there are cluster resources like e.g. ClusterRoles and ClusterRoleBinding, which are instance specific;
 		// During the installation, clusterctl adds the instance namespace prefix to such resources (see fixRBAC), and so we can rely
 		// on that for deleting only the global resources belonging the the instance we are processing.
 		// NOTE: namespace and CRD are special case managed above; webhook instead goes hand by hand with the controller they
 		// should always be deleted.
 		isWebhook := obj.GroupVersionKind().Kind == validatingWebhookConfigurationKind || obj.GroupVersionKind().Kind == mutatingWebhookConfigurationKind
+
 		if util.IsClusterResource(obj.GetKind()) &&
 			!isNamespace && !isCRD && !isWebhook &&
+			!isInventory &&
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/components.go:192]: I don't this this test is required here, given that inventory resource are namespaced and they will be filtered out by `util.IsClusterResource(obj.GetKind())` at the beginning of the if statement

File: cmd/clusterctl/client/cluster/components_test.go [hunk 7]
```diff
@@ -42,7 +42,11 @@ func Test_providerComponents_Delete(t *testing.T) {
 	crd.SetKind("CustomResourceDefinition")
 	crd.SetName("crd1")
 	crd.SetLabels(labels)
-
+	providerInventory := unstructured.Unstructured{}
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/components_test.go:45]: Q: is there a particular reason why you are using unstructured instead of using the typed object? (clusterctlv1 is already imported in this package)

File: cmd/clusterctl/client/cluster/components_test.go [hunk 8]
```diff
@@ -148,15 +157,17 @@ func Test_providerComponents_Delete(t *testing.T) {
 				{object: corev1.ObjectReference{APIVersion: "v1", Kind: "Pod", Namespace: "ns2", Name: "pod3"}, deleted: false},                                         // this object is in another namespace, and should never be touched by delete
 				{object: corev1.ObjectReference{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "ClusterRole", Name: "ns1-cluster-role"}, deleted: true},              // cluster-wide provider components should be deleted
 				{object: corev1.ObjectReference{APIVersion: "rbac.authorization.k8s.io/v1", Kind: "ClusterRole", Name: "some-cluster-role"}, deleted: false},            // other cluster-wide objects should be preserved
+				{object: corev1.ObjectReference{APIVersion: "clusterctl.cluster.x-k8s.io/v1alpha3", Kind: "Provider", Name: "providerOne"}, deleted: false},             // providerInventory should be preserved
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/cluster/components_test.go:160]: Let use the GroupVersion from the clusterctl API instead of "clusterctl.cluster.x-k8s.io/v1alpha3", so it will be easier to bump our API version in future

File: cmd/clusterctl/client/delete.go [hunk 9]
```diff
@@ -53,6 +53,9 @@ type DeleteOptions struct {
 
 	// IncludeCRDs forces the deletion of the provider's CRDs (and of all the related objects).
 	IncludeCRDs bool
+
+	// IncludeInventory forces the deletion of the inventory items used by clusterctl to track providers.
+	IncludeInventory bool
```
Comment (fabriziopandini) [inline cmd/clusterctl/client/delete.go:58]: I think we should invert this flag and name it skipInventory, so the inventory gets deleted by default (false).
Otherwise we are breaking all the clients calling delete and relying on the current behaviour

**Review by fabriziopandini — COMMENTED** [review]
I know this is a WIP, feel free to ignore comments if those parts are still being worked on

File: cmd/clusterctl/client/cluster/components.go (hunk 5 above)
Comment (killianmuldoon) [reply cmd/clusterctl/client/cluster/components.go:175]: I think this is only checking the group and kind though right? I'm accessing groupKind through the GroupVersionKind, but that's only for access.

File: cmd/clusterctl/client/cluster/components.go (hunk 6 above)
Comment (killianmuldoon) [reply cmd/clusterctl/client/cluster/components.go:192]: That's right - removed

File: cmd/clusterctl/client/cluster/components_test.go (hunk 7 above)
Comment (killianmuldoon) [reply cmd/clusterctl/client/cluster/components_test.go:45]: This is part of the issue I was mentioning above. The clusterctlv1.Provider kind doesn't have the Group or Kind by default so they have to be set. This test uses the Provider type to represent the actual providers being deleted (without using the provider type) so there's ambiguity as to which is which. I chose to go unstructured here as the lowest lift way of dealing with that issue.

File: cmd/clusterctl/client/cluster/components.go (hunk 5 above)
Comment (fabriziopandini) [reply cmd/clusterctl/client/cluster/components.go:175]: you are right... 😅

**Comment by fabriziopandini** [comment]
overall lgmt
@ykakarap PTAL

File: cmd/clusterctl/client/cluster/components.go [hunk 10]
```diff
@@ -168,19 +169,29 @@ func (p *providerComponents) Delete(options DeleteOptions) error {
...
 
+		// If the resource is part of the inventory for clusterctl don't delete it at this point as losing this information makes the
+		// upgrade function non-reentrant. Instead keep the inventory objects around until the upgrade is finished and working and
+		// delete them at the end of the upgrade flow.
+		isInventory := obj.GroupVersionKind().GroupKind().String() == providerGroupKind
+		if isInventory {
+			if options.SkipInventory {
+				continue
+			}
+		}
```
Comment (ykakarap) [inline cmd/clusterctl/client/cluster/components.go:180]: nit: 
```suggestion
		if isInventory && options.SkipInventory {
			continue
		}
```

**Review by ykakarap — COMMENTED** [review]
PR is LGTM for me besides a nit.

The original idea behind this PR was to make the `clusterclt upgrade` re-entrant. Can we add some tests around this case to see if it works as expected. May be in a follow-up PR?

**Review by vincepri — APPROVED** [review]
/assign @fabriziopandini 
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve
