### PR TITLE
✨ tilt-prepare: add a flag to skip image preloading

### LINKED ISSUE #13142: tilt-prepare: "kind load" fails for docker >= version 29
### What steps did you take and what happened?

When running `tilt up` locally on an Apple Silicon Mac (M1/M2/M3), the environment preparation fails during the tilt-prepare step. Specifically, it fails when attempting to pre-load `cert-manager` images into the kind cluster:

```
Image: "quay.io/jetstack/cert-manager-cainjector:v1.19.1" with ID "sha256:c7898aece8fb08102fca0b37683e37cb94e0a77c0d15b8e3c9128f6c04c868e0" not yet present on node "capi-test-control-plane", loading...
ERROR: failed to load image: command "docker exec --privileged -i capi-test-control-plane ctr --namespace=k8s.io images import --all-platforms --digests --snapshotter=overlayfs -" failed with error: exit status 1
Command Output: ctr: content digest sha256:d5578165a84137e9228e4573bb1697b6a3ca7de09b5b20f53a2c97137d57fcef: not found
```

### What did you expect to happen?

`tilt up` should complete successfully and the development environment should start without errors.

### Cluster API version

main branch

### Kubernetes version

$ k version
Client Version: v1.34.2
Kustomize Version: v5.7.1
Server Version: v1.31.2
Warning: version difference between client (1.34) and server (1.31) exceeds the supported minor version skew of +/-1

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
/area devtools

### PR DESCRIPTION
**Pull request by bnallapeta**
**What this PR does / why we need it**:

On Apple Silicon Macs, `kind load docker-image` fails for multi-arch images (like cert-manager) because Docker Desktop only stores the `arm64` layers locally. This causes `ctr` to fail when it tries to import all architectures, resulting in a "content digest not found" error that blocks `tilt up`.
This PR updates `tilt-prepare` to skip the preloading step specifically on `darwin/arm64`. Instead of preloading, we rely on the Kubelet to pull the images on-demand when the pods start. This bypasses the kind/docker import issue and allows the development environment to start correctly.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #13142 
Refs: https://github.com/kubernetes-sigs/kind/issues/3795

/area devtools

### CODE REVIEW

**Comment by chrischdi** [comment]
> **What this PR does / why we need it**:
> 
> On Apple Silicon Macs, `kind load docker-image` fails for multi-arch images (like cert-manager) because Docker Desktop only stores the `arm64` layers locally. This causes `ctr` to fail when it tries to import all architectures, resulting in a "content digest not found" error that blocks `tilt up`. This PR updates `tilt-prepare` to skip the preloading step specifically on `darwin/arm64`. Instead of preloading, we rely on the Kubelet to pull the images on-demand when the pods start. This bypasses the kind/docker import issue and allows the development environment to start correctly.
> 
> **Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_: Fixes #13142 Refs: [kubernetes-sigs/kind#3795](https://github.com/kubernetes-sigs/kind/issues/3795)
> 
> /area devtools

Note: this issue is also relevant when using docker community edition >= version 29 for any OS.

I think the workaround used in CI should work here too: using `crane pull "$image" "image.tar" ` to pull the image and `docker load -i "image.tar"` to load it.

Afterwards preload <should> work.

**Comment by bnallapeta** [comment]
> > **What this PR does / why we need it**:
> > On Apple Silicon Macs, `kind load docker-image` fails for multi-arch images (like cert-manager) because Docker Desktop only stores the `arm64` layers locally. This causes `ctr` to fail when it tries to import all architectures, resulting in a "content digest not found" error that blocks `tilt up`. This PR updates `tilt-prepare` to skip the preloading step specifically on `darwin/arm64`. Instead of preloading, we rely on the Kubelet to pull the images on-demand when the pods start. This bypasses the kind/docker import issue and allows the development environment to start correctly.
> > **Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_: Fixes #13142 Refs: [kubernetes-sigs/kind#3795](https://github.com/kubernetes-sigs/kind/issues/3795)
> > /area devtools
> 
> Note: this issue is also relevant when using docker community edition >= version 29 for any OS.
> 
> I think the workaround used in CI should work here too: using `crane pull "$image" "image.tar" ` to pull the image and `docker load -i "image.tar"` to load it.
> 
> Afterwards preload work.

Although crane would work, I am trying to avoid any dependencies for the user. Not everybody knows/uses crane in their local. 
Secondly, even if we were to automate this, right now, crane isn't a tool in the `tilt up` workflow unlike the CI workflow.

That's why I chose the skipping way since that's probably the simplest and most straight forward. It just relies on the standard way of kubelet pulling images.

**Comment by chrischdi** [comment]
The thing is this does not exclusively fail for `runtime.GOOS == "darwin" && runtime.GOARCH == "arm64" `, it can also fail for any variant of running against docker. So with that arguing we could say "we should remove it for all".

The issue here is not >how we load the images< (which is part of the tooling) it is >how we pull the images<.

I'd favor a toggle-able option to disable it if needed. Long-term this should work.

**Comment by bnallapeta** [comment]
@chrischdi Got it. I have now updated the PR so that users could provide a flag in `tilt-settings.yaml`. PTAL.

File: hack/tools/internal/tilt-prepare/main.go [hunk 1]
```diff
@@ -298,9 +299,13 @@ func tiltResources(ctx context.Context, ts *tiltSettings) error {
...
-			tasks["cert-manager-cainjector"] = preLoadImageTask(fmt.Sprintf("quay.io/jetstack/cert-manager-cainjector:%s", config.CertManagerDefaultVersion))
-			tasks["cert-manager-webhook"] = preLoadImageTask(fmt.Sprintf("quay.io/jetstack/cert-manager-webhook:%s", config.CertManagerDefaultVersion))
-			tasks["cert-manager-controller"] = preLoadImageTask(fmt.Sprintf("quay.io/jetstack/cert-manager-controller:%s", config.CertManagerDefaultVersion))
+			preloadImages := true
+			if ts.PreloadImages != nil {
+				preloadImages = *ts.PreloadImages
+			}
+			tasks["cert-manager-cainjector"] = preLoadImageTask(fmt.Sprintf("quay.io/jetstack/cert-manager-cainjector:%s", config.CertManagerDefaultVersion), preloadImages)
+			tasks["cert-manager-webhook"] = preLoadImageTask(fmt.Sprintf("quay.io/jetstack/cert-manager-webhook:%s", config.CertManagerDefaultVersion), preloadImages)
+			tasks["cert-manager-controller"] = preLoadImageTask(fmt.Sprintf("quay.io/jetstack/cert-manager-controller:%s", config.CertManagerDefaultVersion), preloadImages)
```
Comment (fabriziopandini) [inline hack/tools/internal/tilt-prepare/main.go]: Can we not create the tasks entirely when the flag is set? (vs creating task that are no op)

Comment (bnallapeta) [reply hack/tools/internal/tilt-prepare/main.go]: You're right. I modified the code to now conditionally execute this based on the bool. Also modified `preLoadImageTask` function accordingly.

**Comment by bnallapeta** [comment]
@chrischdi @fabriziopandini PTAL.
