### PR TITLE
:bug: fix error from duplicate bootstrap data secret

### LINKED ISSUE #2970: Failed to create bootstrap data secret for KubeadmConfig
What steps did you take and what happened
Launched a 3 masters/3 workers HA cluster in vSphere.
Updated the kubernetes version on this cluster by modifying  KCP, MachineDeployment and VSphereMachineTemplate. This triggered the rolling upgrade.

Error in the boostrap controller logs
kubectl logs -f  capi-kubeadm-bootstrap-controller-manager-5bb9bfdc46-ch5rg -n capi-kubeadm-bootstrap-system manager

> I0427 22:18:32.935314       1 kubeadmconfig_controller.go:416] controllers/KubeadmConfig "msg"="Creating BootstrapData for the worker node" "kind"="Machine" "kubeadmconfig"={"Namespace":"default","Name":"capi-quickstart-md-0-2vhvp"} "name"="capi-quickstart-md-0-b94d4dc9d-5z5rj" "version"="1269" 
I0427 22:18:32.935991       1 kubeadmconfig_controller.go:485] controllers/KubeadmConfig "msg"="Creating BootstrapData for the join control plane" "kind"="Machine" "kubeadmconfig"={"Namespace":"default","Name":"capi-quickstart-6mtfj"} "name"="capi-quickstart-kwnlm" "version"="4559" 
I0427 22:18:32.976280       1 control_plane_init_mutex.go:105] init-locker "msg"="Checking for lock" "cluster-name"="capi-quickstart" "configmap-name"="capi-quickstart-lock" "namespace"="default" 
I0427 22:18:32.976358       1 control_plane_init_mutex.go:112] init-locker "msg"="Control plane init lock not found, it may have been released already" "cluster-name"="capi-quickstart" "configmap-name"="capi-quickstart-lock" "namespace"="default" 
I0427 22:18:32.977906       1 kubeadmconfig_controller.go:416] controllers/KubeadmConfig "msg"="Creating BootstrapData for the worker node" "kind"="Machine" "kubeadmconfig"={"Namespace":"default","Name":"capi-quickstart-md-0-2vhvp"} "name"="capi-quickstart-md-0-b94d4dc9d-5z5rj" "version"="1269" 
E0427 22:18:32.986979       1 kubeadmconfig_controller.go:441] controllers/KubeadmConfig "msg"="failed to store bootstrap data" "error"="failed to create bootstrap data secret for KubeadmConfig default/capi-quickstart-md-0-2vhvp: secrets \"capi-quickstart-md-0-2vhvp\" already exists" "kind"="Machine" "kubeadmconfig"={"Namespace":"default","Name":"capi-quickstart-md-0-2vhvp"} "name"="capi-quickstart-md-0-b94d4dc9d-5z5rj" "version"="1269" 
E0427 22:18:32.987143       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create bootstrap data secret for KubeadmConfig default/capi-quickstart-md-0-2vhvp: secrets \"capi-quickstart-md-0-2vhvp\" already exists"  "controller"="kubeadmconfig" "request"={"Namespace":"default","Name":"capi-quickstart-md-0-2vhvp"}

What did you expect to happen:
Expected the kubeadmconfig controller to skip creation of boostrap data secret if it already exists. 

Environment:

- Cluster-api version: v0.3.3
- KIND version: v0.6.0
- Kubernetes version: 1.16.7
- OS: CentOS 7

/kind bug

### PR DESCRIPTION
**Pull request by abhinavnagaraj**
What this PR does / why we need it:
This PR skips the creation of boostrap data secret for KubeadmConfig if it already exists.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2970

### CODE REVIEW

**Comment by vincepri** [comment]
Can we have a failing test, to see how this fixes the issue? I need a little bit more time to look at the logs, but would like to understand in which circumstances the issue comes up.

**Comment by fabriziopandini** [comment]
+1 to better understand the use case.

File: bootstrap/kubeadm/controllers/kubeadmconfig_controller.go [hunk 1]
```diff
@@ -718,8 +718,14 @@ func (r *KubeadmConfigReconciler) storeBootstrapData(ctx context.Context, scope
...
 
+	// as secret creation and scope.Config status patch are not atomic operations
+	// it is possible that secret creation happens but the config.Status patches are not applied
 	if err := r.Client.Create(ctx, secret); err != nil {
-		return errors.Wrapf(err, "failed to create bootstrap data secret for KubeadmConfig %s/%s", scope.Config.Namespace, scope.Config.Name)
+		if !apierrors.IsAlreadyExists(err) {
+			return errors.Wrapf(err, "failed to create bootstrap data secret for KubeadmConfig %s/%s", scope.Config.Namespace, scope.Config.Name)
+		} else {
+			r.Log.Info("bootstrap data secret for KubeadmConfig already exists", "secret", secret.Name, "KubeadmConfig", scope.Config.Name)
+		}
```
Comment (vincepri) [inline bootstrap/kubeadm/controllers/kubeadmconfig_controller.go:728]: We can probably drop the `else` block here and log regardless
```suggestion
	r.Log.Info("Bootstrap data secret for KubeadmConfig already exists", "secret", secret.Name, "KubeadmConfig", scope.Config.Name)
```

Comment (sadysnaat) [reply bootstrap/kubeadm/controllers/kubeadmconfig_controller.go]: removed else, as suggested

**Comment by fabriziopandini** [comment]
Investigating the code I see only a use case where this problem can happen: when patchHelper.Patch failed.
Despite that, I think this change won't hurt anything....

**Comment by sadysnaat** [comment]
@fabriziopandini squash done
