### PR TITLE
:bug: MachineReconciler.getNodeReference use continue token

### LINKED ISSUE #2166: MachineReconciler.getNodeReference does not use the list continue token correctly
In MachineReconciler.getNodeReference, it looks like we have some leftover `metav1.ListOptions` from before we converted to use the controller-runtime `Client`.

I think the code should probably look like this:
```go
var continueToken string
for {
  nodeList := apicorev1.NodeList{}
  
  var listOptions []client.ListOption
  if continue != "" {
    listOptions = append(listOptions, client.Continue(continueToken))
  }
  err := client.List(ctx, &nodeList, listOptions...)
  // check error, do stuff
  
  if nodeList.Continue == "" {
    break
  }
  
  continueToken = nodeList.Continue
}
```

Note, we need to use the continue token here because `client` is a client for the remote cluster, so it's not informer-based (which handles the continue).

/help
/good-first-issue
/priority important-longterm
/milestone Next

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
/assign @ncdc

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2166

### CODE REVIEW

File: controllers/machine_controller_noderef.go [hunk 1]
```diff
@@ -89,16 +88,12 @@ func (r *MachineReconciler) reconcileNodeRef(_ context.Context, cluster *cluster
...
 
-	listOpt := metav1.ListOptions{}
-
+	nodeList := apicorev1.NodeList{}
 	for {
-		nodeList := apicorev1.NodeList{}
-		// TODO Add a context to this method
-		err := client.List(context.TODO(), &nodeList)
-		if err != nil {
+		if err := c.List(context.TODO(), &nodeList, client.Continue(nodeList.Continue)); err != nil {
```
Comment (ncdc) [inline controllers/machine_controller_noderef.go]: I guess this works if the continue token is the empty string (i.e. it performs the initial list)?

Comment (vincepri) [reply controllers/machine_controller_noderef.go]: Yeah, I looked in the default value of the option field set by `client.Continue`, and it's an empty string
